### ISSUE TITLE
[3.3.5] Compile errors VS 2019 latest release

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#25203] opened 2020-08-04 19:32 UTC
14>SmartAI.cpp
15>cs_account.cpp
15>cs_achievement.cpp
16>LINK : fatal error LNK1181: Eingabedatei "..\..\..\dep\g3dlite\Release\g3dlib.lib" kann nicht geöffnet werden.
14>SmartScript.cpp
15>cs_ahbot.cpp
15>cs_arena.cpp
14>SmartScriptMgr.cpp
16>Die Erstellung des Projekts "authserver.vcxproj" ist abgeschlossen -- FEHLER.
14>AccountMgr.cpp
15>cs_ban.cpp
15>cs_bf.cpp

17>TCSoap.cpp
17>WheatyExceptionReport.cpp
17>ServiceWin32.cpp
17>LINK : fatal error LNK1181: Eingabedatei "..\..\..\dep\g3dlite\Release\g3dlib.lib" kann nicht geöffnet werden.
17>Die Erstellung des Projekts "worldserver.vcxproj" ist abgeschlossen -- FEHLER.
18>------ Erstellen gestartet: Projekt: ALL_BUILD, Konfiguration: Release x64 ------
18>Building Custom Rule D:/TrinityCore335_SRC/TrinityCore/CMakeLists.txt
19>------ Erstellen übersprungen: Projekt: INSTALL, Konfiguration: Release x64 ------
19>Für diese Projektmappenkonfiguration wurde kein zu erstellendes Projekt ausgewählt. 
========== Erstellen: 15 erfolgreich, 3 fehlerhaft, 0 aktuell, 1 übersprungen ==========

**Branch(es):**3.3.5

**Operating system:** Win 7

**Comment by Faq** [comment] 2020-08-04 19:34
by latest you mean preview what version?

**Comment by jackpoz** [comment] 2020-08-04 19:37
have you tried re-running cmake ?

**Comment by Tauriella** [comment] 2020-08-04 19:38
This release I wanted to compile Carbenium committed "Scripts/AzjolNerub: Fix 
@jackpoz 
yes i have re-running cmak but I try again

**Comment by Shauren** [comment] 2020-08-04 19:39
You are on windows 7, I might have by accident removed support for it (wont fix, its unsupported by microsoft at this point)

**Comment by Tauriella** [comment] 2020-08-04 19:42
Yea
i tink your Hot Fix is reale Hot
Core/Misc: Fix compile errors found with msvc /permissive-

**Comment by Tauriella** [comment] 2020-08-04 19:55
re-running cmak does not work
I hope @Shauren fix this bug

**Comment by MaxtorCoder** [comment] 2020-08-04 19:59
> re-running cmak does not work
> I hope @Shauren fix this bug

He won't, look what he posted above.

**Comment by Shauren** [comment] 2020-08-04 20:02
Dropping support for outdated things is not a bug.

**Closed by Shauren** 2020-08-04 20:02 UTC
Labels: Branch-3.3.5a, Invalid-IncompleteData/OrNotTrinityCore

**Comment by Tauriella** [comment] 2020-08-04 20:09
But I don't want to upgrade my Windows :-1:

**Comment by Faq** [comment] 2020-08-04 20:10
remove that commit then.

**Comment by MaxtorCoder** [comment] 2020-08-04 20:11
> But I don't want to upgrade my Windows :-1: 

We don't care tho, why would we support software that is unsupported by the main creator heh

**Comment by jackpoz** [comment] 2020-08-04 20:41
Remove the commit in your fork as suggested, that's as far as we can help

**Comment by Tauriella** [comment] 2020-08-04 20:41
So now I upgrade the windows 7 to 10
how I hate the grrrrrrrr.... :-1:

**Comment by jackpoz** [comment] 2020-08-04 21:12
You could try installing Windows 10 SDK on Win 7 and see if TC builds, but that's more of something for you to try than something we will check

**Comment by Tauriella** [comment] 2020-08-04 21:28
I think the problem is this fix for Win7

https://github.com/TrinityCore/TrinityCore/commit/b3db50a3b41b2db209327387f59afa1c40532773#diff-4b0e18aff592df55779510f085292302

**Comment by Tauriella** [comment] 2020-08-04 23:31
Now I've upgraded the windows 7 to 10 and it's all worked properly.
Luckily :+1: 

17>TCSoap.cpp
17>WheatyExceptionReport.cpp
17>ServiceWin32.cpp
17>   Bibliothek "D:/TrinityCore3XCompile/src/server/worldserver/Release/worldserver.lib" und Objekt "D:/TrinityCore3XCompile/src/server/worldserver/Release/worldserver.exp" werden erstellt.
17>worldserver.vcxproj -> D:\TrinityCore3XCompile\bin\Release\worldserver.exe
18>------ Erstellen gestartet: Projekt: ALL_BUILD, Konfiguration: Release x64 ------
18>Building Custom Rule D:/TrinityCore335_SRC/TrinityCore/CMakeLists.txt
19>------ Erstellen übersprungen: Projekt: INSTALL, Konfiguration: Release x64 ------
19>Für diese Projektmappenkonfiguration wurde kein zu erstellendes Projekt ausgewählt. 
========== Erstellen: 18 erfolgreich, 0 fehlerhaft, 0 aktuell, 1 übersprungen ==========

But why is windows 7 no longer supported?

**Comment by Jinnaix** [comment] 2020-08-04 23:47
Why should it be supported? Microsoft officially stopped support for windows 7 in January 2020 and people should finally arrive in the same year and stop using dead software.

**Comment by Tauriella** [comment] 2020-08-04 23:52
Not all new is good :)

**Comment by jackpoz** [comment] 2020-08-05 11:02
@Tauriella you still didn't post the compile error nor tried the suggestion I wrote (Windows 10 SDK on Win 7), so if it's not supported it's because none tested our suggestions yet. We don't have an environment with Win7 anymore so it's up to users to test it.

**Comment by Tauriella** [comment] 2020-08-05 14:47
@jackpoz 
Ups sorry
I dont have anymore compile error log from Win7.
I use now Win10 SDK and it's work fine.
I hope an any Win7 user can confirm and post the error log.

**Comment by Faq** [comment] 2020-08-06 16:38
Selecting Windows SDK version 10.0.19041.0 to target Windows 6.1.7601.
The C compiler identification is MSVC 19.28.29115.0

* TrinityCore revision   : 2910d0fb2436 2020-08-06 17:59:36 +0200 (3.3.5 branch)
========== Rebuild All: 24 succeeded, 0 failed, 0 skipped ==========
