### ISSUE TITLE
[3.3.5] Pooling + dynamic_spawning

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#21519] opened 2018-02-27 18:31 UTC
Description:
The server crashes after starting

https://gist.github.com/Tauriella/7b4e94f73174fddea29e5bbd0266dacb

Branch(es):

TC rev. hash/commit:
TrinityCore rev. 3eab2d7efcc2 2018-02-27 16:18:38 +0100 (3.3.5 branch)

TDB version: TDB_full_world_335.64_2018_02_19 + all updates

Operating system: Win7

**Comment by Treeston** [comment] 2018-02-27 18:40
What assertion message, if any, is printed to the console?

**Comment by Tauriella** [comment] 2018-02-27 18:51
D:\TrinityCore335_SRC\TrinityCore\src\server\game\Entities\Creature\Creature.cpp
:1644 in Creature::LoadFromDB ASSERTION FAILED:
  m_respawnCompatibilityMode Creature (SpawnID 151932) trying to load despite a
respawn timer in progress.

**Comment by Tauriella** [comment] 2018-02-27 20:42
@Treeston 
If you use in the woldserver.conf  "BaseMapLoadAllGrids=1" 
your server will crash

**Comment by Treeston** [comment] 2018-02-27 20:49
Thanks - probably pooling not cooperating with `dynamic_spawning`. I will investigate (and it probably needs a re-write).

**Comment by Treeston** [comment] 2018-02-27 21:11
Tagging commit above should prevent the assert from crashing the core temporarily, issue will remain open until pooling is properly fixed.

**Comment by jackpoz** [comment] 2018-12-01 18:42
any update on this ?

**Comment by Ovahlord** [comment] 2018-12-27 15:18
Nope. The crash is also not fixed since the assert is still getting triggered. But this time it is not caused by poolings but by the GameEvent manager.
https://paste2.org/akzUI3ZF

**Comment by Kittnz** [comment] 2019-04-20 08:18
When starting event 61...

```
C:\Source\src\server\game\Entities\Creature\Creature.cpp:1607 in Creature::LoadFromDB ASSERTION FAILED:
  m_respawnCompatibilityMode || sPoolMgr->IsPartOfAPool<Creature>(spawnId)
Creature (SpawnID 208904) trying to load despite a respawn timer in progress.
MapID: 1 X: -706.873 Y: -5089.25 Z: 10.1878 O: 0
GUID Full: 0xf130009cf000031d Type: Creature Entry: 40176  Low: 797 Entry 40176
Name: Sen'jin Frog
IsAIEnabled: false DeathState: 0 UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 1
AIName: SmartAI ScriptName: WaypointPath: 0 SpawnId: 208904

**Comment by jackpoz** [comment] 2019-04-20 11:52
I'll change those asserts to error logs, no need to take down worldserver just for a spawn

**Comment by Treeston** [comment] 2019-04-20 11:54
Could you please not?

Removing the assert is not a fix to a bug. Why do I have to keep saying that?

**Comment by Ovahlord** [comment] 2019-04-20 12:04
Why do you want to crash a server because of a bug that does not really cause any further issues? It's a object with a respawn time but it gets spawned anyways so this does not sound to me like a reason to kill a server immediately.

**Comment by jackpoz** [comment] 2019-04-20 12:17
It's a 1 year old issue marked with priority high that crashes the server, still there has been no progress so far and it will be like that for a lot of time still, that's why an assert that is supposed to be triggered when the impossible happens is not a good choice in this case.
The how to reproduce steps are clear, you can fix the issue anytime you want.

**Comment by Treeston** [comment] 2019-04-20 12:35
The original priority high crash was addressed over a year ago in 9fc6b13. The issue remained open as a reminder that the pooling system needed adjustments to play nice with dynamic_spawning.

If gameevent logic is doing dumb things with low-level spawning methods, then fix gameevent logic. Asserts in dynamic_spawning exist for a reason. You do not want a single creating two respawn timers, ever. Bad things happen.

1 creature = 2 respawn entries. 2 creatures = 4 respawn entries. I don't need to explain to you how exponential growth works I think.

**Comment by killradio** [comment] 2019-05-10 17:52
In my case it is Minigob Manabonk caused crash.

To reproduce: go to Dalaran, start event 33, after Minigob disappear, go to other location, wait till event stop (30m occurrence + 5m length), go to Dalaran again and start event 33 -> crash.

**Comment by Kittnz** [comment] 2019-06-06 17:42
Can we have a fix for this, this is a server breaking issue really :/

**Comment by jackpoz** [comment] 2019-06-07 20:59
> When starting event 61...

@Kittnz if I ".event start 61" I don't get any crash. Do I need to be somewhere in particular ?

**Comment by Kittnz** [comment] 2019-06-08 08:56
Yes, echo isles, And dalaran when event 33 starts.

**Comment by jackpoz** [comment] 2019-06-08 09:42
>.go xyz  -773.906067  -5010.133301  17.237411
.event start 61

Confirm at 50ed1bb5b3d3
[50ed1bb5b3d3_worldserver.exe_[8-6_11-38-53].txt](https://github.com/TrinityCore/TrinityCore/files/3268390/50ed1bb5b3d3_worldserver.exe_.8-6_11-38-53.txt)

**Comment by jackpoz** [comment] 2019-06-08 11:33
Some refined steps:
- .go xyz -773.906067 -5010.133301 17.237411 1
- .event start 61
- /tar darkspear scout
- .damage 50000
- .event stop 61
- .event start 61

Killing the npc saves respawn time, stopping the event doesn't remove that and starting the event tries to summon a creature which still has a respawn time.

**Comment by r00ty-tc** [comment] 2019-06-08 12:58
Ick, to properly fix this.. In new pooling it's not so bad.. Pool respawn times are just poolId of root pool. Easy to run through and delete all of those on event stop.
But, old pooling.. The event triggers a pool, but respawn times are saved for the creature spawnId..
A bit messy but possible, and will probably solve https://github.com/TrinityCore/TrinityCore/issues/21132 at the same time.

**Comment by jackpoz** [comment] 2019-06-08 14:55
https://github.com/jackpoz/TrinityCore/commits/3.3.5-game_event_respawn removes the respawn time of creatures/gameobjects when starting/stopping an event . It doesn't handle pools.

**Comment by jackpoz** [comment] 2019-06-09 12:38
Opened a PR https://github.com/TrinityCore/TrinityCore/pull/23391

**Comment by akrom23** [comment] 2019-06-10 05:35
The same problem exists in instances, e.g. Onyxia's Lair, when you are using gm command to respawn the whole instance.

Steps to reproduce (Onyxia's Lair)
- Kill all mobs from trash
- Kill Onyxia
- Use .respawn on Onyxia

**Comment by jackpoz** [comment] 2019-06-10 06:19
that's another issue about .respawn command https://github.com/TrinityCore/TrinityCore/issues/23014

**Closed** 2019-06-15 12:19 UTC
Labels: Branch-3.3.5a, Comp-Core, Priority-High, Sub-Pools, Sub-Spawns
