### ISSUE TITLE
[3.3.5] Channeled spells are not interrupted by vanish

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21614] opened 2018-03-13 15:33 UTC
**Description:**

If a rogue vanishes while a mage is casting arcane missiles, then the channel should be interrupted as target is no longer present. However, atm it keeps firing the entire duration, damaging the rogue and removing his stealth.

**Expected behaviour:**

Should be interrupted and rogue should still be in stealth.

**Steps to reproduce the problem:**

1. start channeling on rogue
2. cast vanish

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/b978b673a9053bb0d7bd63ed9261117dc7845742

**TDB version:**  64

**Operating system:** ubuntu

**Comment by ariel-** [comment] 2018-03-13 16:41
Duplicate of #7425

**Closed by ariel-** 2018-03-13 16:41 UTC
