### ISSUE TITLE
Combustion Server crash

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28887] opened 2023-03-30 10:11 UTC
### Description

https://www.wowhead.com/spell=190319/combustion this spell has incorrect animation and crashes the server

https://gist.github.com/PivanDepolo/376b6a3b6fc91db100b62671fabd48a9

### Expected behaviour

Must not crash

### Steps to reproduce the problem

Just use that spell

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/98df53650b62695c2519014b4a7900fa88f356be

### Operating system

Debian 11

### Custom changes

None

**Comment by Shauren** [comment] 2023-03-30 20:33
Nope, those steps to reproduce are incorrect, just using that spell doesn't do anything

**Comment by PivanDepolo** [comment] 2023-03-31 08:51
> Nope, those steps to reproduce are incorrect, just using that spell doesn't do anything (complete talent tree and gear info required)

My bad. 

Looks like talent [Mass slow](https://www.wowhead.com/spell=391104/mass-slow) procs from any spell and crashes the server

**Comment by PivanDepolo** [comment] 2023-03-31 19:21
> Nope, those steps to reproduce are incorrect, just using that spell doesn't do anything (complete talent tree and gear info required)

![1](https://user-images.githubusercontent.com/64589699/229209288-b6356de8-c832-4f35-81b0-3ef91a8ba95d.png)

https://www.wowhead.com/spell=2120/flamestrike
https://www.wowhead.com/spell=153561/meteor
https://www.wowhead.com/spell=108853/fire-blast

With such a talent tree, using each of these spells crashes the server

https://gist.github.com/PivanDepolo/42911bbc7bbda60a0b9b74f7f40d395f

**Comment by ImmortalusDev** [comment] 2023-04-01 07:00
https://gist.github.com/PivanDepolo/42911bbc7bbda60a0b9b74f7f40d395f#file-gistfile1-txt-L54

**Comment by aquadeus** [comment] 2023-06-20 16:58
this crash is due to spell_mage_ignition script

**Comment by Shauren** [comment] 2023-06-20 17:01
No, it is not

**Comment by Shauren** [comment] 2023-06-29 09:26
Duplicate of #28887

**Closed by Shauren** 2023-06-29 09:26 UTC
Labels: HasBacktrace, Priority-High, Branch-master
