### ISSUE TITLE
[no path available] in ICC

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#14970] opened 2015-06-28 18:47 UTC
after this 91c399cad239b20dac68629587e7c8b4ec612be3 commit a issue appear with 
Demon Charge ( Warlock Charge ) doesn't work on a few bosses include rotface and festergut

GPS: X: 4277.612305 Y: 3158.892822 Z: 360.385529 Orientation: 3.145517

**Comment by jackpoz** [comment] 2015-07-03 19:49
gps is missing the map id, .go xyz format would be nice

**Comment by jackpoz** [comment] 2015-07-03 19:51
.go xyz 4277.612305 3158.892822 360.385529 631 3.145517
posting the command for reference

**Comment by Runico** [comment] 2015-07-03 20:12
@jackpoz doesn't matter where exactly you are just go near rotface or festergut  on those places 

GPS
```
Map: 631 (Icecrown Citadel) Zone: 4812 (Icecrown Citadel) Area: 4812 (Icecrown Citadel) Phase: 4294967295
X: 4260.922363 Y: 3126.634277 Z: 360.385590 Orientation: 5.743615
grid[39,37]cell[7,6] InstanceID: 82
 ZoneX: 26.557642 ZoneY: 20.562428
GroundZ: 53.647568 FloorZ: 360.385437 Have height data (Map: 1 VMap: 1 MMap: 1)
```

**Comment by jackpoz** [comment] 2015-07-03 20:35
@Runico the worst part for me is usually to reach the right place, even if it's very commonly known among players. "go near festergut" can be a pain to me.

The issue is caused by https://github.com/TrinityCore/TrinityCore/blob/622ff39f49e0b401c6a1a95727ad73ab96faa5e4/src/server/game/Movement/PathGenerator.cpp#L200 return a path of type PATHFIND_INCOMPLETE , I have no clue why the path is supposed to be marked as incomplete.

**Comment by Goatform** [comment] 2015-07-03 20:41
As temp fix , just disable MMAP support in that zone for now.

**Comment by jackpoz** [comment] 2015-07-03 20:50
this is actually caused by https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L5091 adding target->GetObjectSize() to Z coordinate, for Festergut that value is 8.f and it triggers the check of "destination too far away from polygon" code, returning an incomplete path. https://github.com/TrinityCore/TrinityCore/commit/91c399cad239b20dac68629587e7c8b4ec612be3 actually spotted this bug

**Comment by jackpoz** [comment] 2015-07-03 21:23
Fixed in https://github.com/TrinityCore/TrinityCore/commit/a328a119784252c6d514436f4ceffa693ac65453

I don't know if there are even bigger npcs with higher combat range than 8, if that's the case we'll clamp GetObjectSize() to [0,4] in charge calls

**Comment by Nyeriah** [comment] 2015-07-27 20:57
@jackpoz : There indeed are creatures with higher combat range than 8. For example, Lord Marrowgar which has combat reach = 20.25 and can't be charged atm.

http://www.wowhead.com/npc=36612/lord-marrowgar

```mysql SELECT * FROM `creature_model_info` WHERE `DisplayId` = 31119;```

**Comment by Runico** [comment] 2015-07-27 21:50
@Nyeriah, @jackpoz, i got report from halion too

**Comment by jackpoz** [comment] 2015-07-27 21:57
I just have to apply https://github.com/TrinityCore/TrinityCore/issues/14970#issuecomment-118427858 and check ingame that it works

**Comment by jackpoz** [comment] 2015-07-28 19:16
https://github.com/TrinityCore/TrinityCore/commit/0a94382637ba9212a23e224b4ac2df114acb4ca7

**Closed by jackpoz** 2015-07-28 19:16 UTC
Labels: Comp-Core, Sub-Maps/MMaps/Vmaps, Sub-Spells
