### ISSUE TITLE
DB/Quest: Healing the Lake 

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#21583] opened 2018-03-10 22:47 UTC
**Description:**

When you come to the stone you will neutralize.

**Current behaviour:**

When you come to the stone, neutralization can not be done .

**Expected behaviour:**

When you come to stone with "Neutralizing Agent" you perform neutralization.

**Steps to reproduce the problem:**

1. Fix the Neutralizer functionality error
   This is how it works: [https://youtu.be/b2h8trHWYSo](url) 
   Here's a more detailed description of queste : [http://www.wowhead.com/quest=9294/healing-the-lake](url) 
2. try functionality
3. to implement a fix

**Branch(es):**

7.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 12beb3dd1b51 2018-03-07 18:08:15 +0100 (master branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  735.00_2018_02_19

**Operating system:** Win 10 Pro x64

**Comment by tkrokli** [comment] 2018-03-10 23:58
Duplicate of #15961

**Closed by tkrokli** 2018-03-10 23:58 UTC
Labels: Branch-master, Sub-Quests

**Comment by shamage** [comment] 2018-03-11 09:01
tkrokli's correction here works. I tried it on: TrinityCore rev. 12beb3d 2018-03-07 18:08:15 +0100 (master branch) (Win64, RelWithDebInfo, Static)
could someone implement a patch repair please ?

![healing the lake](https://user-images.githubusercontent.com/7515044/37251565-b184729a-2512-11e8-8122-cda907f9b225.jpg)

 
`UPDATE `gameobject_template` SET `AIName`='SmartGameObjectAI', `ScriptName`='' WHERE`entry`IN(181433);`

```
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (181433);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(181433, 1, 0 ,0,70, 0, 100, 0, 2, 0, 0,0,1,0,0,0,0,0,0,19,20239,0,0,0, 0, 0, 0, 'Irradiated Power Crystal - On State Changed - Say Line 1 (Neutralizing Emote Placeholder)');
```

```
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry`=31515;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(13, 1, 31515, 0, 0, 31, 0, 3, 17947, 0, 0, 0, 0, '', 'Spell Red Beam targets Red Crystal Bunny');
```
