### ISSUE TITLE
The Shadow Grave Quest Issue

### ISSUE THREAD

**Issue by polpygamer** [TrinityCore/TrinityCore#27271] opened 2021-11-13 14:51 UTC
### Description

Both items cannot be loot, when clicking on those, nothing to loot, and first quest cannot be completed.

Undead

### Expected behaviour

Loot Thick Embalming Fluid and Corpse-Stiching twine

### Steps to reproduce the problem

create an undead level 1

accept the first quest

try to get items

### Branch

master

### TC rev. hash/commit

latest TC build 14b8d7d

client 9.1.5.41031

### Operating system

Windows 11 x64

### Custom changes

none

**Comment by polpygamer** [comment] 2021-11-13 14:53
![WoWScrnShot_111321_154607](https://user-images.githubusercontent.com/87237612/141648271-bd501e24-4b0c-478c-b0c6-3ceb2b332043.jpg)

**Comment by offl** [comment] 2021-11-13 15:08
Duplicate of #20066

**Closed by offl** 2021-11-13 15:08 UTC
Labels: Branch-master
