### ISSUE TITLE
Core/Movement: Unit with flee movement can get stuck in REACT_PASSIVE

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#28012] opened 2022-06-09 10:46 UTC
### Description

Its possible for creatures to get stuck in REACT_PASSIVE if combat gets dropped while creature is moving to seek for assistance - AssistanceDistractMovementGenerator::Finalize wont get called.

Seems to only be possible in Dungeons/Raids?

![image](https://user-images.githubusercontent.com/37972361/172829205-fb447cc1-0436-4350-b253-76c2c900a167.png)

### Expected behaviour

REACT_PASSIVE should get cleared.

### Steps to reproduce the problem

1. go creature id 4296
2.  damage below 16% hp mark
3. gm on while creature is fleeing

### Branch

3.3.5

### TC rev. hash/commit

b155209ec40f867fc90d64eb207f3d3e7f633c2b

### Operating system

Windows 11

### Custom changes

None

**Comment by offl** [comment] 2022-06-09 10:54
Duplicate of #23994

**Closed by offl** 2022-06-09 10:54 UTC
Labels: Branch-3.3.5a
