### ISSUE TITLE
[3.3.5] Grouploot thit QuestItems

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#15624] opened 2015-09-28 20:57 UTC
513b756ea8afcfeb65b97e8227669681e9cd9a40
latest DB 3.3.5

Der Gruppenloot mit Questitem ist einwenig verbuggt.
Sprich, wenn einer aus der Gruppe die Leiche plündert kann der andere die Leiche die trotz aufblinkt weder plündern (quest item looten) noch kürschnern (sprich wird komplett gespeert).

The Gruppenloot with Questitem is bugged a little .
Say, if one of the group loots the body , the other the body of the flashing neither plunder (quest item loot ) still Furries (pronounced completely closed ) despite .

**Comment by NorthStrider** [comment] 2015-10-02 14:44
English plz or nothing will happen

**Comment by dr-j** [comment] 2015-10-10 12:34
confirming this the perfect example of this is http://www.wowhead.com/quest=11911/quickening on retail when http://www.wowhead.com/item=35490/arcane-splinter drops everyone in party whos on the quest can loot same mob for quest item on tc only one player can loot at a time, making it so if everyone in party is on quest on tc theres not enough mobs for whole party to complete quest at same time or you have to do multiple runs to complete quest unless you are lucky enough to be only player on quest.

another example is http://www.wowhead.com/quest=12069/return-of-the-high-chief where quest item has to be looted from a gameobject, if in group only 1 player at a time gets to loot the quest item resulting in quest having to be repeated for each player in group rather than all players in party ben able to loot go.

**Comment by tkrokli** [comment] 2015-10-10 12:47
@genion18 : if I may suggest some slightly improved English in your issue title :
"Quest items in Group loot" or "Group loot with Quest items". OK? :-)

**Comment by Killyana** [comment] 2015-10-10 13:06
It affects all this kind of quests or only some of them?

**Comment by tkrokli** [comment] 2015-10-10 13:27
Users I have talked to, during the last 9 months, often complain that this is the case with most, if not all, shared group quests. Last summer I tried to replicate the issue by running 3 instances of my 3.3.5a game client simultaneously, but I was unable to reproduce the issue myself, at least as long as there was more than only the quest item in the loot. Unfortunately, I haven't been able to test lately with other users connecting to my computer, so I can't say for sure if this issue can be provoked by network lag or not.

**Comment by dr-j** [comment] 2015-10-10 18:18
No its not all quest items because a quest where current behaviour is correct is http://www.wowhead.com/quest=29840/for-posterity (ie each quest go can be looted by a single player and then despawns but is also a quest which is done in a group.

**Comment by Killyana** [comment] 2015-10-10 18:38
There's a difference between looting a mob and looting a gob type chest, the issue is not the same.

**Comment by PolarCookie** [comment] 2018-10-03 20:57
http://www.wowhead.com/quest=12069/return-of-the-high-chief was fixed with https://github.com/TrinityCore/TrinityCore/pull/22124

**Comment by Killyana** [comment] 2018-10-03 21:52
Gobs loot are fixed.
Creature loot works correctly you can test with https://woehead.way-of-elendil.fr/?item=3637#dropped-by
Party loot are handled by ( Flags=2048 -  Item is party loot and can be looted by all) on Item_template. 

I tested also  http://www.wowhead.com/quest=11911/quickening and each player get a quest Item form the creature.

**Closed by Killyana** 2018-10-03 21:52 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Quests
