### ISSUE TITLE
Empty Server, gradual mapupdatemgr delay increase

### ISSUE THREAD

**Issue by r00ty-tc** [TrinityCore/TrinityCore#19072] opened 2017-02-08 11:48 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
When loading all maps/grids with no unload, and leaving server empty there is an occasional UpdateMapMgr diff warning, which will begin around 2 days in, and increase exponentially.

This is just a place to collate investigation I've already done, and so that others can perhaps comment.

There's two backtraces I have, caused by setting a 1 second freeze handler. I'll paste them here and discuss in comments.

http://pastebin.com/UZ0RZyKh
http://pastebin.com/hGMAMq1i

**Current behaviour:** (Tell us what happens.)
UpdateMapMgr diff increases over time.

**Expected behaviour:** (Tell us what should happen instead.)
UpdateMapMgr diff should be relatively constant without a change in player load

**Steps to reproduce the problem:**

1. BaseMapLoadAllGrids = 1
2. GridUnload = 0
3. Ensure log misc is sent to console (to see UpdateMapMgr diff errors)

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5 (unknown master)

**TC rev. hash/commit:**  
3a65c706572ea0d0b66b9b79a275f8d230f7991d (confirmed on at least)

**TDB version:**  
TDB_full_world_335.62_2016_10_17 / updates upto hash above

**Operating system:**  
Linux (also happens on Windows)

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment] 2017-02-08 11:54
Server mining bitcoins xD

**Comment by r00ty-tc** [comment] 2017-02-08 12:04
Now, for my investigation so far.

First of all, I added some debug around the map threads. Ensuring that I could see which map was causing the delay. This identified the culprit as being map 571 (Northrend).

Next, as per advice on IRC I setup a server with debug/gdb and a very low freeze time trigger. This generated the two backtraces that are included. However, as expected this really just shows that "stuff it happening" in 571 and other maps long since finished their work.

They do show that there are some specific areas with a lot of activity though. @Shauren suggested perhaps this is to do with summons despawning in a different grid to their start location.

To me, the most likely cause is that something being iterated is growing constantly. So, I looked at grid containers. I added a new command called debug grid. Which allowed me to see object counts in maps as a whole and per grid. 

This has turned up something very interesting. Some grids specifically keep growing in terms of objects added to it. Well specifically just one.

TC>debug grid 571 36 42
TC>2017-02-08_12:57:26 CLI command under processing...
map 571 (36, 42) objects: 2571
map 571 total 36441

This starts at around 150-200. It seems to start growing slowly, but the rate of growth increases over time. The grid is around the area of Valiance Keep. This is where it gets a little odd.

If I go to that grid and look around the keep and the shore area.. Basically as soon as I move in that grid

TC> debug grid 571 36 42
TC>2017-02-08_13:01:25 CLI command under processing...
map 571 (36, 42) objects: 298
map 571 total 34159

It comes back down. Now, there's a huge amount of "setActive" activity here and so I don't know if that's the cause.

Regardless though, something odd is going on. Early tests suggest logging on and moving around reduces the count. However, the rate seems to be the same increased rate, and early checking seems to suggest this doesn't prevent the diff warnings.

So, it's still a mystery for now.

**Comment by Shauren** [comment] 2017-02-08 12:32
Active objects cause this to happen because the area they prevent from unloading is larger than the area they cause to update (meaning temporary summons cannot despawn themselves because they arent running Update and their grid cannot unload them either)

**Comment by r00ty-tc** [comment] 2017-02-08 12:36
Yeah, I expected something like this since a player entering clears it instantly. One thing that is odd, is that the rate remains the same. As an example, since I visited it's added 100 more in 20mins. But when first starting the server the addition rate so far as I can tell is slower than this.

In theory this potentially could cause a slowdown. I'll monitor. If it seems that visiting the area stops the slow down. Then OK that's where the problem is. Very basic checking seems to suggest this hasn't stopped the slowdown. But it'll take another day or so for me to be sure.

**Comment by ccrs** [comment] 2017-02-08 12:41
Why dont you track down the entity which is causing the summs to happen and check the related script?

**Comment by Shauren** [comment] 2017-02-08 13:15
I know exactly which piece of code is responsible for this, will fix when I get home

**Comment by r00ty-tc** [comment] 2017-02-08 13:15
For the slowdown, or the huge numbers, or both?

Good news either way I would say.

**Comment by Shauren** [comment] 2017-02-08 13:16
Slowdown is directly tied to huge numbers (constantly growing lists being iterated)
so both

**Comment by Shauren** [comment] 2017-02-08 19:26
I think that should take care of it

**Comment by ccrs** [comment] 2017-02-08 20:03
Grids are all loaded at start and grid unload is deactivated, how can that be the solution? O.o

**Comment by Shauren** [comment] 2017-02-08 20:16
if grid unload is deactivated? its not solving anything

**Comment by ccrs** [comment] 2017-02-08 20:20
````
Steps to reproduce the problem:

BaseMapLoadAllGrids = 1
GridUnload = 0
Ensure log misc is sent to console (to see UpdateMapMgr diff errors)
````

**Comment by r00ty-tc** [comment] 2017-02-09 00:40
Although, so far it does seem to have at least stopped the grid objects gradual increase.

debug grid 571 36 42
TC>2017-02-08_21:08:12 CLI command under processing...
map 571 (36, 42) objects: 282
map 571 total 34103

TC>debug grid 571 36 42
TC>2017-02-09_01:29:24 CLI command under processing...
map 571 (36, 42) objects: 283
map 571 total 34139

It was generally gaining 200 or so in that grid, or more over that time before.

Let's see in a few days how the map update diffs are in a few days

**Comment by ccrs** [comment] 2017-02-09 01:16
I just dont get it xD
Would be nice to know how changing the grid activation range would affect if all the grids are already loaded, I'm honestly confused.

````Map::Update```` -> ````VisitNearbyCellsOf```` (active objects) -> ````GetGridActivationRange()```` ->  ````EnsureGridLoaded````

I must be missing something xd

**Comment by r00ty-tc** [comment] 2017-02-09 09:42
I don't get it either. I never actually looked at the code yesterday. I just synced up dyn spawns, popped it over to my linux server where I run it with load all grids and added the debug command again. It seems fine. Overnight seems to confirm it. Yesterday overnight it jumped to 2500+ in this grid.

TC>debug grid 571 36 42
TC>2017-02-09_10:39:13 CLI command under processing...
map 571 (36, 42) objects: 283
map 571 total 34130

So, deliberate or not it seems to have solved this part of the problem.. In a day or two we'll know if it has solved the actual problem.

**Comment by Shauren** [comment] 2017-02-09 10:20
This is probably just luck in my opinion
![grid_activation](https://cloud.githubusercontent.com/assets/297439/22779019/61c6a448-eeb9-11e6-8a5d-745824a38881.jpg)

What my commit does is make blue and red squares equal and it probably catches the summon but what if it moves outside of that square? (both in player/active_creature case)
As you probably know there are only 2 ways to despawn temporary summons
* Grid unload (does not happen here)
* TempSummon::Update (self-despawn) that requires being visited by Map::VisitNearbyCellsOf

**Comment by r00ty-tc** [comment] 2017-02-09 10:46
Yes, but what was the actual size of the red previous active creature square. If it was sufficiently small enough it would explain why it fixes this part of the problem.

As I say, we need to wait a few days to know if it fixed the whole problem. In theory though, it will have.

**Comment by Shauren** [comment] 2017-02-09 10:54
Config:
RED: MonsterSight (50)
BLUE: Visibility.Distance.Continents (90)

**Comment by ccrs** [comment] 2017-02-09 19:42
Ohh I see, didnt know about he cleaning part.

But after checking this
````c++
        if (!grid.GetWorldObjectCountInNGrid<Player>() && !map.ActiveObjectsNearGrid(grid))
        {
            ObjectGridStoper worker;
            TypeContainerVisitor<ObjectGridStoper, GridTypeMapContainer> visitor(worker);
            grid.VisitAllGrids(visitor);
            grid.SetGridState(GRID_STATE_IDLE);
            TC_LOG_DEBUG("maps", "Grid[%u, %u] on map %u moved to IDLE state", grid.getX(), grid.getY(), map.GetId());
        }
        else
            map.ResetGridExpiry(grid, 0.1f);
````
Seems like STATE_IDLE -> STATE_REMOVAL is in fact prevented

**Comment by Shauren** [comment] 2017-02-10 08:59
getUnloadLock is the method checking GRID_UNLOAD config, STATE_ACTIVE -> STATE_IDLE -> STATE_REMOVAL is not prevented.

**Comment by r00ty-tc** [comment] 2017-02-10 09:40
However the original problem is still an issue:

2017-02-10_10:29:11 Difftime UpdateMapMgr: 103.

Only one message so far, so it could be some one-off. But, let's see. Over the next day if the issue is still present we'll see it rise fairly quickly.

No change in grid numbers:

debug grid 571 36 42
TC>2017-02-10_10:38:46 CLI command under processing...
map 571 (36, 42) objects: 283
map 571 total 34157

**Comment by r00ty-tc** [comment] 2017-02-10 14:33
Some more.

2017-02-10_11:25:35 Difftime UpdateMapMgr: 103.
2017-02-10_12:14:28 Difftime UpdateMapMgr: 116.
2017-02-10_13:09:16 Difftime UpdateMapMgr: 110.
2017-02-10_14:28:07 Difftime UpdateMapMgr: 120.

Still quite far apart. They will gradually get bigger, and more frequent.

**Comment by Undergarun** [comment] 2017-02-10 15:52
Confirmed

**Comment by r00ty-tc** [comment] 2017-02-10 23:46
Some more

2017-02-10_15:50:24 Difftime UpdateMapMgr: 120.
2017-02-10_16:47:52 Difftime UpdateMapMgr: 129.
TC> 2017-02-10_17:41:44 Difftime UpdateMapMgr: 116.
2017-02-10_18:27:54 Difftime UpdateMapMgr: 103.
2017-02-10_19:09:25 Difftime UpdateMapMgr: 123.
2017-02-10_19:42:13 Difftime UpdateMapMgr: 139.
2017-02-10_20:13:23 Difftime UpdateMapMgr: 128.
2017-02-10_20:43:43 Difftime UpdateMapMgr: 129.
2017-02-10_21:10:05 Difftime UpdateMapMgr: 131.
2017-02-10_21:34:45 Difftime UpdateMapMgr: 107.
2017-02-10_21:57:56 Difftime UpdateMapMgr: 136.
2017-02-10_22:18:28 Difftime UpdateMapMgr: 138.
2017-02-10_22:38:50 Difftime UpdateMapMgr: 104.
2017-02-10_22:57:42 Difftime UpdateMapMgr: 133.
2017-02-10_23:16:12 Difftime UpdateMapMgr: 101.
2017-02-10_23:32:03 Difftime UpdateMapMgr: 112.
2017-02-10_23:47:17 Difftime UpdateMapMgr: 102.
2017-02-11_00:01:50 Difftime UpdateMapMgr: 101.
2017-02-11_00:16:36 Difftime UpdateMapMgr: 108.
2017-02-11_00:30:17 Difftime UpdateMapMgr: 142.

Seems to be now more common. Every 15 mins.. I suppose I should be looking for events that run every 15mins, based off map 571.

**Comment by Killyana** [comment] 2017-02-11 01:21
I tried to find events with active npcs using your logs:
- https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/sql/old/6.x/world/03_2016_04_11/2016_04_09_17_world_2016_04_01_00_world.sql
- https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/sql/old/6.x/world/02_2015_11_08/2015_11_01_13_world_from_335.sql#L3116

**Comment by r00ty-tc** [comment] 2017-02-12 13:50
A bit more of an update. They've become much more common, but the numbers aren't moving up as fast as before. So maybe it's "linked" to the grid object count.

2017-02-12_14:12:19 Difftime UpdateMapMgr: 132.
2017-02-12_14:15:21 Difftime UpdateMapMgr: 146.
2017-02-12_14:18:26 Difftime UpdateMapMgr: 175.
2017-02-12_14:21:29 Difftime UpdateMapMgr: 170.
2017-02-12_14:24:33 Difftime UpdateMapMgr: 103.
2017-02-12_14:27:36 Difftime UpdateMapMgr: 172.
2017-02-12_14:30:38 Difftime UpdateMapMgr: 173.
2017-02-12_14:33:42 Difftime UpdateMapMgr: 131.
2017-02-12_14:36:46 Difftime UpdateMapMgr: 145.
2017-02-12_14:39:50 Difftime UpdateMapMgr: 105.

Now, yesterday evening it was every 4 minutes. Now it's every 3.

**Comment by r00ty-tc** [comment] 2017-02-17 21:26
So, a bit of an update

```
2017-02-17_22:15:39 Difftime UpdateMapMgr: 625.
2017-02-17_22:16:41 Difftime UpdateMapMgr: 1250.
2017-02-17_22:17:42 Difftime UpdateMapMgr: 1298.
2017-02-17_22:18:42 Difftime UpdateMapMgr: 1202.
2017-02-17_22:19:43 Difftime UpdateMapMgr: 1234.
2017-02-17_22:20:43 Difftime UpdateMapMgr: 1142.
2017-02-17_22:21:44 Difftime UpdateMapMgr: 1053.
```

But that's after 9 days uptime. So, things have improved. But still it does get worse over time.

**Comment by Aokromes** [comment] 2017-02-17 21:43
>7d of uptime is unblizzlike :trollface:

**Comment by reisa089** [comment] 2017-05-11 00:25
Hello,

We can confirm the problem today.

In this photo you can check a high latency with 1500 users online.

It is happening to us once or twice a day.

We have checked different configurations but we have not been able to avoid the problem.

If you need a registration of a server with users online we will help you in everything possible.


At the moment we have disabled these scripts in case the problem originates from both events.

Excuse my English.

UPDATE `creature_template` SET` AIName` = '' WHERE `entry`IN (24959,26583,26582,25220,25307);

Photos:
Http://subefotos.com/ver/?3eb95c3cd20515479dffd2b306b8e3afo.jpg
Http://subefotos.com/ver/?adb95033bdc6b2e2deedfef9ca70023bo.jpg
Http://subefotos.com/ver/?b2f171ec41fa8b6700adbd90f4ae3c68o.jpgos

**Comment by ccrs** [comment] 2017-05-11 15:05
report if there is any change after disabling those scripts

**Comment by reisa089** [comment] 2017-05-11 18:57
Hello again

The problem happened again although this time I could solve it by eliminating a lot of mobs in Angrathar (Dragonblight)

Today I will try again to confirm that the problem is given by this accumulation of mobs.

Photos: http://subefotos.com/ver/?2c3804b194d384d1437f57c003d5ff7ao.jpg

Mob Accumulated: http://www.wowhead.com/npc=27604/frail-construct

I think the problem originates there, today I confirm it if we suffer high latency and I leave it commented here.

**Comment by reisa089** [comment] 2017-05-11 21:29
We have again the problem but this time the high latency has not been reduced.

It seems to be failing elsewhere.

**Comment by ccrs** [comment] 2017-05-12 17:50
the original report refered to NPCs spawning around the Valiance Keep area

**Comment by reisa089** [comment] 2017-05-12 18:20
We will check it today to see if the source of the problem really comes from there and if we can prepare a solution for all of us.

I hope we can solve this problem together.

**Comment by reisa089** [comment] 2017-05-14 19:27
At the moment we have not been able to find the cause or avoid this problem. If you have any idea, we will try to help in every possible way.

**Comment by reisa089** [comment] 2017-05-19 22:25
535/5000
Goodnight

We've been preparing arrangements to control the number of summoned mobs for several days. Today thanks to these fixes and several logs we have been able to verify that today's overhead has been for the instance Azjol-Nerub, we think that the Hadronox boss is the problem.

Our logs have warned us that in this instance have accumulated more than 6,000 mobs.

We can not say that there is only an overload but it is a beginning. We closed the instance to the public to see how the emulator behaves.

We will inform you.

**Comment by Shauren** [comment] 2017-05-20 10:02
That would be strange, because no instances are loaded when you do it like the original issue suggests (instances need players)

**Comment by reisa089** [comment] 2017-05-20 10:10
Hi Shauren,

I showed you a photo of 2 overloads we had last night so you have data to verify.

Photo: http://subefotos.com/ver/?1753b8be93791d71257257c3933650e0o.jpg

I can not assure that there are only problems there, it is possible that we will have an overload in other areas too, but I can tell you that tonight closing the instance has been a quiet night for us.

Tonight we will check if everything is going well and if so we will inform you.

**Comment by reisa089** [comment] 2017-05-20 10:23
Forgive, I have to also indicate that we have several arrangements to control the invocations of the mobs on the map 571. I intuit that thanks to our arrangement and when closing the instance we should not have the overhead.

In a few days I indicate that we have added in case you are interested to review it and to do your own investigation or relevant arrangement.

**Comment by JarDv** [comment] 2017-05-20 20:56
I have found how to reproduce it, go to Azjol instance and enter, don't do anything for around 5 minutes and then move to hadronox boss. I think it is related to active and inactive grids, summoner is on an active grid but the summon move from  active grid to a inactive grid, so it does not update. Can be a litlle example for what happen on  world.

**Comment by JarDv** [comment] 2017-05-20 22:50
And a NPC marked like active that summon some creatures cause a huge numbers of summons if it is on a inactive grid because (map::Update) update it through m_activeNonPlayers, but the summon isn't an active object, and the update can't despawn it  by expire time.

 example: trigguers on valiance keep.

Temoral fix is to set those summons to be active objec, so they can unsumon by self

**Comment by ccrs** [comment] 2017-05-25 10:58
probably its better to just add these two checks
````diff
diff --git a/src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_hadronox.cpp b/src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_hadronox.cpp
index 008d13a..677dad3 100644
--- a/src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_hadronox.cpp
+++ b/src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_hadronox.cpp
@@ -972,6 +972,10 @@ class spell_hadronox_periodic_summon_template_AuraScript : public AuraScript
             InstanceScript* instance = caster->GetInstanceScript();
             if (!instance)
                 return;
+            if (instance->GetBossState(DATA_KRIKTHIR) != DONE)
+                return;
+            if (!instance->instance->HavePlayers())
+                return;
             if (instance->GetBossState(DATA_HADRONOX) == DONE)
                 GetAura()->Remove();
             else
````

**Comment by RedSonja** [comment] 2018-10-31 20:53
I am not at the tip but wondering if this issue has been fixed?

**Comment by Kittnz** [comment] 2019-06-03 09:20
If the event starts and grid pauses it, and it gets started several times, you get this issue i guess.

**Comment by Treeston** [comment] 2019-07-08 14:05
retest after a3c3526

**Comment by Shauren** [comment] 2019-07-08 15:47
This issue is older than that script

**Comment by jackpoz** [comment] 2020-06-12 00:54
Tagging this issue for https://github.com/TrinityCore/TrinityCore/issues/24356

**Comment by jackpoz** [comment] 2020-07-31 11:11
A lot of new metric have been added to Grafana. Update to latest version, import latest dashboards and monitor the number of mobs in each map, the world update loop and the map update loop.

**Comment by gtestdev** [comment] 2020-08-03 09:17
with gridunload = 0 and 4 days online:
https://snapshot.raintank.io/dashboard/snapshot/G18fv074p6Wf2O6olT5c5uJquNOXlhTu?orgId=2
seems map 533 (Naxxramas)

**Comment by jackpoz** [comment] 2020-08-03 09:48
what does the Maps, vmaps and mmaps dashboard show in the Creatures and Gameobjects panels ? do they increase over time for map 533 ?

**Comment by Shauren** [comment] 2020-08-03 09:51
I wonder if its this
https://github.com/TrinityCore/TrinityCore/blob/bfb041246f5c7c499ff365b38a281b0784f0bdb7/src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp#L475-L484

**Comment by Jildor** [comment] 2020-08-03 10:39
hmmm, can be posible when you enter naxx and EVENT_SUMMON_FROGGER_WAVE is executed and you leave the instance, the Frogger SAI isn't executed and they accumulate a lot?
10 minutes example: https://i.imgur.com/eXkYkPm.png

```sql
SELECT * FROM `smart_scripts` WHERE `entryorguid`=16027;

entryorguid  source_type      id    link  event_type  event_phase_mask  event_chance  event_flags  event_param1  event_param2  event_param3  event_param4  event_param5  action_type  action_param1  action_param2  action_param3  action_param4  action_param5  action_param6  target_type  target_param1  target_param2  target_param3  target_param4  target_x  target_y  target_z  target_o  comment                                                             
-----------  -----------  ------  ------  ----------  ----------------  ------------  -----------  ------------  ------------  ------------  ------------  ------------  -----------  -------------  -------------  -------------  -------------  -------------  -------------  -----------  -------------  -------------  -------------  -------------  --------  --------  --------  --------  --------------------------------------------------------------------
      16027            0       0       1          10                 1           100          513             0             1             0             0             1           19            256              0              0              0              0              0            1              0              0              0              0         0         0         0         0  Living Poison - OOC LOS - Remove Unit Flags Immune to PC (Phase 1)  
      16027            0       1       0          61                 1           100          513             0             0             0             0             0           11          28433              2              0              0              0              0            1              0              0              0              0         0         0         0         0  Living Poison - OOC LOS - Cast Explode (Phase 1)                    
```

last frogger event change: https://github.com/TrinityCore/TrinityCore/commit/7eda9fb617ef22b9ee6212d38b42a80a28c005dd

**Comment by gtestdev** [comment] 2020-08-04 09:00
Sorry jackpoz, don't look at that graph and the influxdb data has already been erased :(

**Comment by jackpoz** [comment] 2020-08-04 11:47
@gtestdev you could copy the panels Creatures and Gameobjects from that dashboard to the Performance profiling one

**Comment by jackpoz** [comment] 2020-08-05 12:28
https://github.com/TrinityCore/TrinityCore/commit/174ac958009222aeef83520101a28963f8c63b0e fixed the Naxxramas issue (at least the one found)

**Comment by jackpoz** [comment] 2020-09-16 11:00
> **Steps to reproduce the problem:**
> 
> 1. BaseMapLoadAllGrids = 1
> 2. GridUnload = 0
> 3. Ensure log misc is sent to console (to see UpdateMapMgr diff errors)

After 3 days things look very stable so closing this issue as fixed https://snapshot.raintank.io/dashboard/snapshot/9dMg0LN0QQNZPqiAbQzxUOwgL5zCQ5hE

Please open a new issue with a Grafana dashboard if a similar issue happens again. https://trinitycore.atlassian.net/wiki/spaces/tc/pages/19955721/Monitoring+a+TrinityCore+server describes how to setup Grafana.

**Closed by jackpoz** 2020-09-16 11:00 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Miscellaneous
