### ISSUE TITLE
Entire area npc missing.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#18519] opened 2016-12-19 06:54 UTC
**Description:**  
Entire area NPC are missing.  

**Current behaviour: (Tell us what happens.)**  
The mission called HERO,S CALL: WESTFALL(ID 26378) cannot be completed because the objective npc and the entire zone(id 916) npc are missing.  

**Expected behaviour: (Tell us what should happen instead.)**  
After accepting this mission (in stormwind) you should deliver the quest to a npc called LIEUTENANT HORATIO LANE but this npc is missing, it should be standing at this position X: -9847.775391 Y:918.883667 Z:31.163143 Orientation:3.7.56536 ZoneX:59.936657 ZoneY:19.190376 also there must be around this NPC some STORMWIND SOLDIERS tath are missing too. this is an important quest because begins a chain of quest.  

**Steps to reproduce the problem:**  

1- Travel to westfall to the jansen stead  
2- Stand at X: -9847.775391 Y:918.883667 Z:31.163143 where the npc are missing  

**Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)**   
Master  

**TC rev. hash/commit:**  
bc758991140e961ceac46b17b766b0d54b8129fb  

**TDB version:**  
7.0.3+updates  

**Operating system:** 
Windows 10

**Comment by nubqt** [comment] 2017-11-10 03:40
The issue is that the lieutenant and other lore-related NPCs have an invisible aura. Removing this aura makes the NPCs visible again.

In addition, the lieutenant should be kneeling rather than standing.

This fix solves both problems.

**Suggested fix:**

```sql
-- Making 'Lieutenant Horatio Laine' visible and forcing him to stay kneeled
UPDATE `creature_template_addon` SET `auras` = '', `bytes1` = '8' WHERE `entry` = '42308';
-- Making other lore-relevant NPCs visible as well
-- Making 'Farmer Fulbrow' visible while maintaining his 'Permanent Feign Death' aura
UPDATE `creature_template_addon` SET `auras` = '29266' WHERE `entry` = '237'; 
-- Making 'Verna Fulbrow' visible while maintaining her 'Permanent Feign Death' aura
UPDATE `creature_template_addon` SET `auras` = '29266' WHERE `entry` = '238';
-- Making 'Old Blanchy' visible while maintaining its 'Permanent Feign Death' aura
UPDATE `creature_template_addon` SET `auras` = '29266' WHERE `entry` = '582';
-- Making two 'Stormwind Investigator' visible
UPDATE `creature_template_addon` SET `auras` = '' WHERE `entry` = '42309';
-- Making four 'Crime Scene Alarm-o-Bot' visible
UPDATE `creature_template_addon` SET `auras` = '' WHERE `entry` = '42311';
```

**Comment by Aokromes** [comment] 2017-11-10 08:36
No, that's hack, like killyana said on the other thread zone needs scripting:

(42383, 0, 0, 0, 1, 0, '79116'), -- 42383 - 79116
(237, 0, 0, 65536, 1, 0, '79488 29266'), -- 237 - 79488, 29266
(42308, 0, 0, 65536, 1, 0, '79488'), -- 42308 - 79488
(238, 0, 0, 65536, 1, 0, '79488 29266'), -- 238 - 79488, 29266
(42391, 0, 0, 0, 1, 0, ''), -- 42391
(42311, 0, 0, 65536, 1, 0, '79488'), -- 42311 - 79488
(42309, 0, 0, 65536, 1, 0, '79488'), -- 42309 - 79488
(582, 0, 0, 65536, 1, 0, '79488 29266'), -- 582 - 79488, 29266

**Comment by nubqt** [comment] 2017-11-10 15:27
I believe the reason why you see those values is because the quest and its related NPCs are currently bugged in retail as well. See:

http://www.wowhead.com/quest=28562/heros-call-westfall#comments

> Lieutenant Horatio Laine is only visible to humans, but if you are another race, just relog where he stands, and you will be able to see him for a short moment and turn the quest in.
After that, he will remain visible and you can start questing in Westfall.

And http://www.wowhead.com/quest=26378/heros-call-westfall#comments

> Hey all!
> Just wanted to inform you that there’s an issue with this quest at the moment. Some players are not able to interact with Lieutenant Horatio Laine, and our developer team is already investigating this.

> Yeah, still not fixed. Came back several times, dude's not there. It's not that you can't interact, he's just not there. Wasn't there for me or my groupmate.

Makes no sense for them to have an invisible aura since the Lieutenant is the 'welcoming' quest-giver for Westfall.

What do we do in these cases? Do we have to wait for it to be fixed in retail before we proceed?

**Comment by Aokromes** [comment] 2017-11-10 19:01
No, it's not 7.2.5 thing, i got those values from various sniffs.

**Comment by nubqt** [comment] 2017-11-10 19:07
what actions did you perform to get those sniffs? and on what client version? also, can you please post the raw sniff?

**Comment by nubqt** [comment] 2017-11-16 23:49
I reviewed this quest and it seems that the lieutenant should be watching the murder scene when the Player enters Westfall for the first time. But once the Player completes all the objectives for the quest Murder Was The Case That They Gave Me, the lieutenant moves to inspect Old Blanchy and says some text.

**Comment by Killyana** [comment] 2018-02-02 21:48
Spawns are correct, just spell_areas area missing are nothing is scripted there.

**Closed by Killyana** 2018-02-02 21:48 UTC
Labels: Branch-master

**Comment by HannibalRoG** [comment] 2018-02-03 16:45
Then, issue solved or not?

**Comment by Killyana** [comment] 2018-02-03 16:52
Yes, spawns are there

**Comment by HannibalRoG** [comment] 2018-02-03 20:44
The issue is not only of the npc that did not exist but of the follow-up of a chain of quests that is not functional. Was that also fixed? Should we open another ticket with the quest tracking error or use this same one?

**Comment by tkrokli** [comment] 2018-02-03 20:56
@HannibalRoG : open a new issue ticket (if there is not one already open) and make sure that each issue ticket is about 1 single quest, script or NPC (or group of NPCs directly related to the same single event).

**Comment by Aokromes** [comment] 2018-02-03 21:11
a generic ticket for un-scripted zone already exists.

**Comment by tkrokli** [comment] 2018-02-03 21:28
Yes, just search for "zones" and you will find (among others) these open issue tickets:
- Empty zones #12975
- [DEV][master] Cataclysm Zones - Movement (20$ bounty) #15181
- [DEV][Master] Cataclysm Zones - Quests + Phasing (135$ bounty) #15182

**Comment by HannibalRoG** [comment] 2018-02-03 22:02
ok, fair enough ^^
