### ISSUE TITLE
DB/Quest: Decontamination (Alliance) - can't complete

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16224] opened 2016-01-09 17:36 UTC
This quest in the Gnome start zone is bugged. http://www.wowhead.com/quest=27635/decontamination

Quest wont work, player cannot mount or use machines. Gnome Mage. Level 5. No buffs - no addons.

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by Aokromes** [comment] 2016-06-15 09:13
This bug is still valid?

**Comment by Anddrw** [comment] 2016-06-24 14:22
Yes, its still valid

**Comment by tkrokli** [comment] 2016-07-03 17:26
TrinityCore rev. 04b7d90d8ba4 2016-07-03 03:03:59 +0200 (6.x branch) (Win64, Debug, Static)
(6.x rev. 77f980035a43 + cherry-picked 3.3.5 commit 1ad73212dca0 to get rid of repeated crashes)
TDB 6.04 plus updates up to and including `2016_06_30_00_world.sql`

Very simple to replicate: 1. Create a new gnome character. 2. Get this quest. 3. check the Sanitrons:

![wowscrnshot_070316_191721](https://cloud.githubusercontent.com/assets/4903600/16546717/6d879300-4153-11e6-8303-5d19ce11a466.jpg)
Notice that you get a green mount vehicle arrow cursor when pointing at the vehicles, but no reaction.

**Comment by nubqt** [comment] 2017-11-12 17:00
Bug solved somehow. Player can now mount the vehicle. I will create a separate issue for a different unexpected behavior: nothing happens after you mount the vehicle.

**Comment by Faq** [comment] 2017-11-12 17:11
@nubqt no need for new as the same quest.
Can you post picture what you see when mounted?

**Comment by nubqt** [comment] 2017-11-12 17:13
Nothing happens after mounting the 'Sanitron 500.' If I remember correctly, after the player mounts the vehicle, it automatically moves to the center of the room and (lore-wise) a 'decontamination' process occurs that (i) removes the player's irradiation, (ii) completes the quest objective, and (iii) dismounts the player.

This issue should be marked as **Critical** for several reasons:

1. There is no way to dismount from the Sanitron except from logging out.
2. Newbie Gnome players won't know how to get out of the starting zone since they won't be able to progress further in the questline that shows them how to do that.
3. Gnome players start with an Aura called 'Irradiated' that won't go away unless this quest is completed.

**Comment by nubqt** [comment] 2017-11-12 17:18
@Faq: attached is screenshot.
<img width="1378" alt="screen shot 2017-11-12 at 12 16 10 pm" src="https://user-images.githubusercontent.com/33535711/32701442-82b7d244-c7a3-11e7-8aaf-4998e535bd42.png">

**Comment by Aokromes** [comment] 2017-11-12 17:19
Critical is only for constant crashes.

**Comment by nubqt** [comment] 2017-11-12 17:26
@Aokromes: could you please show me where this project defines its [Checklist Incident Priority matrix](https://wiki.en.it-processmaps.com/index.php/Checklist_Incident_Priority)? I'm concerned about why an issue with such an impact on the gaming experience should not be considered critical.

**Comment by tkrokli** [comment] 2017-11-12 19:03
@nubqt : TrinityCore is about the learning experience, not supplying a gaming community.

**Comment by nubqt** [comment] 2017-11-12 19:42
@tkrokli: thanks, I appreciate the input, but can you please point me to where this is documented in the project?

**Comment by tkrokli** [comment] 2017-11-12 20:39
There is neither ITIL compliant documentation, nor any ISO 9001 documentation. TrinityCore is not a well funded and official organization, none of the members are paid to work on the issues. TrinityCore is a loose group of idealistic programmers on various levels, be it students or real life business programmers who like to spend some time with various pieces of code which can be run and tested with one of our favorite games.

We TrinityCore users have grown accustomed to the fact that many decisions are made as we go, depending on changes in the game or the supporting software used to handle the source code and DB content. Most decisions are made by the owners of the project, although there are also some decisions made from consensus in some cases. We are aware that the documentation could be better, but that is also the case for most projects. There simply is not any funding for the full time job it is to write a comprehensive documentation similar to what is used in business companies or well funded organizations.

You need to view TrinityCore as the forum-based user-oriented organization it is, given the fact that idealistic programmers come and go, while some stick around to form a more decisive group of owners with various responsibilities. One of the reasons we don't have more users as permanent members is the fact that users have to prove their proficiency while also contributing to the code in a controlled manner. A lot of membership activity is based on trust, grown from repeated interactions via IRC, forum activity and contributed solutions. You may also think of TrinityCore as an advanced forum group without funding. (This is all I can come up with as a reply to your question at the moment.)

For any and all further discussions, please use the IRC channel **#trinity** @ **irc.rizon.net** or post on https://community.trinitycore.org/ . Browse through articles in the Help and Support forum (https://community.trinitycore.org/forum/5-help-and-support/) and notice posts like this one: https://community.trinitycore.org/topic/4046-tired-of-asking-always-the-same-questions/

Because the issue tracker is not a forum, I strongly advise to move any further questions to those resources mentioned above.

**Comment by MauFus** [comment] 2018-03-26 23:41
Hello everyone,
may I propose a draft of fix for this issue? It isn't working 100%, but maybe someone is able to fix what i cannot do.

[DB-Quest Decontamization.txt](https://github.com/TrinityCore/TrinityCore/files/1849851/DB-Quest.Decontamization.txt)

Fixed:
- Sanitron 500 follows the (approximately) right path, telling quotes and stopping on waypoints
- "Irradiated" aura is removed on the way
- Quest is completed at the end of the script

Not Working:
- At the end of the scripted scene, Sanitron 500 doesn't respawn at home location, instead it respawns where the script ended; moreover, after respawn it isn't clickable in order to restart the script. I think I'm missing something here...
- Completion is awarded at the end of the script, but through the NPC slain (not as probably intended)
- During the scripted scene, no fancy animation are performed at waypoints

**Comment by MauFus** [comment] 2018-04-07 21:59
I reworked my solution posted above (modified inline) using phases, some different parameters for the script and the correct "credit spell". 
The npc respawn in now fully working and the quest is scripted and can be completed!

Only downside is that I didn't find correct animation to be performed on waypoints (I added pauses and placeholders), but it is esthetic stuff.

Actually, this is my first full DB script; please, provide me with feebacks, if any :)

**Comment by nyhmii** [comment] 2018-06-04 16:32
works quite nicely!

**Comment by welder1976** [comment] 2022-07-09 13:05
<pre>INSERT INTO smart_scripts (entryorguid,source_type,id,link,event_type,event_phase_mask,event_chance,event_flags,event_param1,event_param2,event_param3,event_param4,action_type,action_param1,action_param2,action_param3,action_param4,action_param5,action_param6,target_type,target_param1,target_param2,target_param3,target_x,target_y,target_z,target_o,comment) VALUES
(46185,0,0,1,11,0,100,0,0,0,0,0, 81,16777216,0,0,0,0,0, 1,0,0,0,0,0,0,0, "Sanitron 500 - On Respawn - Set npc flag"),
(46185,0,1,2,25,0,100,0,0,0,0,0, 66,0,0,0,0,0,0, 1,0,0,0,0,0,0,0, "Sanitron 500 - On Reset - Set Home Position"),
(46185,0,2,3,25,0,100,0,0,0,0,0, 22,1,0,0,0,0,0, 1,0,0,0,0,0,0,0, "Sanitron 500 - On Reset - Set Phase 1"),
(46185,0,3,0,27,1,100,0,0,0,0,0, 80,4618500,0,0,0,0,0, 1,0,0,0,0,0,0,0, "Sanitron 500 - Start Decontamination Script"),
(4618500,9,0,1,0,1,100,0,0,0,0,0, 22,2,0,0,0,0,0, 1,0,0,0,0,0,0,0, "Sanitron 500 - Script - Set Phase 2"),
(4618500,9,1,2,0,2,100,0,0,0,0,0, 1,0,0,0,0,0,0, 1,0,0,0,0,0,0,0, "Sanitron 500 - Script - Say 0"),
(4618500,9,2,3,0,2,100,0,2000,2000,0,0, 69,0,0,0,0,0,0, 8,0,0,0,-5173.94,725.62,291.387,0, "Sanitron 500 - Script - Move To Waypoint 1"),
(4618500,9,3,4,0,2,100,0,3000,3000,0,0, 86,0,0,19,0,0,0, 0,0,0,0,0,0,0,0, "Sanitron 500 - Script - Animation 1 [delay]"),
(4618500,9,4,5,0,2,100,0,0,0,0,0, 11,86075,0,0,0,0,0, 7,0,0,0,0,0,0,0, "Sanitron 500 - Script - Cast Decontaminate Stage 1'"),
(4618500,9,5,6,0,2,100,0,1000,1000,0,0, 69,0,0,0,0,0,0, 8,0,0,0,-5174.56,716.36,289.387,0, "Sanitron 500 - Script - Move To Waypoint 2"),
(4618500,9,6,7,0,2,100,0,3000,3000,0,0, 86,0,0,19,0,0,0, 0,0,0,0,0,0,0,0, "Sanitron 500 - Script - Animation 2 [delay]"),
(4618500,9,7,8,0,2,100,0,0,0,0,0, 11,86084,0,0,0,0,0, 7,0,0,0,0,0,0,0, "Sanitron 500 - Script - Cast Decontaminate Stage 2'"),
(4618500,9,8,9,0,2,100,0,2000,2000,0,0, 69,0,0,0,0,0,0, 8,0,0,0,-5175.21,707.18,291.887,0, "Sanitron 500 - Script - Move To Waypoint 3"),
(4618500,9,9,10,0,2,100,0,3000,3000,0,0, 86,0,0,19,0,0,0, 0,0,0,0,0,0,0,0, "Sanitron 500 - Script - Animation 3 [delay]"),
(4618500,9,10,11,0,2,100,0,1500,1500,0,0, 1,1,0,0,0,0,0, 1,0,0,0,0,0,0,0, "Sanitron 500 - Script - Say 1"),
(4618500,9,11,12,0,2,100,0,0,0,0,0, 11,86086,0,0,0,0,0, 7,0,0,0,0,0,0,0, "Sanitron 500 - Script - Cast Decontaminate Stage 3'"),
(4618500,9,12,13,0,2,100,0,1000,1000,0,0, 69,0,0,0,0,0,0, 8,0,0,0,-5175.98,700.18,291.387,0, "Sanitron 500 - Script - Move To Waypoint 4"),
(4618500,9,13,14,0,2,100,0,2000,2000,0,0, 1,2,0,0,0,0,0, 1,0,0,0,0,0,0,0, "Sanitron 500 - Script - Say 2"),
(4618500,9,14,11,0,2,100,0,0,0,0,0, 28,80653,0,0,0,0,0, 29,0,0,0,0,0,0,0, "Sanitron 500 - Script - Remove Irradiated Aura"),
(4618500,9,15,15,0,2,100,0,0,0,0,0, 37,0,0,0,0,0,0, 1,0,0,0,0,0,0,0,"Sanitron 500 - Script - Die"),
(4618500,9,16,16,0,2,100,0,0,0,0,0, 41,2000,0,0,0,0,0, 1,0,0,0,0,0,0,0,"Sanitron 500 - Script - Despawn After 2 Secounds"),
(4618500,9,17,0,0,2,100,0,0,0,0,0, 22,1,0,0,0,0,0, 1,0,0,0,0,0,0,0, "Sanitron 500 - Script - Set Phase 1");</pre>

**Closed** 2024-01-01 02:39 UTC
Labels: Sub-Quests, Feedback-FixOutdatedMissingWIP, Comp-Database, Branch-master
