### ISSUE TITLE
Cooldown problems

### ISSUE THREAD

**Issue by AisaRs** [TrinityCore/TrinityCore#9372] opened 2013-03-07 23:19 UTC
Hello!
         The main problem is with icc cooldowns, players made the instances in normal and heroic mode, but only in the normal mode, cooldowns are clean.
          Another problem is that sometimes player didn't made an instance and they have a cooldown anyway. Weird

Our Server has the last githut version and no custom patches.

**Comment by Aokromes** [comment] 2015-02-05 21:45
Try after d4db0c15c7e59f7139619720be3c26a48e6ff259

**Comment by Killyana** [comment] 2015-05-05 15:47
Fixed with: https://github.com/TrinityCore/TrinityCore/commit/d4db0c15c7e59f7139619720be3c26a48e6ff259
I will leave it open with cannot reproduce tag until confirmation.

**Comment by Killyana** [comment] 2015-05-20 18:49
If the issue still happen ask to reopen it.

**Closed by Killyana** 2015-05-20 18:49 UTC
Labels: Comp-Core, Invalid-CannotReproduce, Priority-High, Sub-Miscellaneous

**Comment by sirikfoll** [comment] 2016-05-10 15:11
This still happens, possible only with huge databases

**Comment by jackpoz** [comment] 2016-05-31 08:25
what are you database threads settings in worldserver.conf ?

**Comment by sirikfoll** [comment] 2016-05-31 14:48
```
LoginDatabase.WorkerThreads     = 2
WorldDatabase.WorkerThreads     = 4
CharacterDatabase.WorkerThreads = 5

LoginDatabase.SynchThreads     = 2
WorldDatabase.SynchThreads     = 4
CharacterDatabase.SynchThreads = 5

**Comment by Keader** [comment] 2016-06-05 04:49
@jackpoz any idea?

**Comment by jackpoz** [comment] 2016-06-05 09:54
Increase https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/database/Database/Transaction.cpp#L77 and https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/database/Database/DatabaseWorkerPool.cpp#L216 to "WorkerThreads + SynchThreads + 1" or reduce the number of database threads (are those numbers random or what's the purpose behind 5 CharDB async + 5 CharDB sync threads ?)

**Comment by sirikfoll** [comment] 2016-06-07 14:47
@jackpoz "WorkerThreads + SynchThreads + 1", should I consider only the CharacterDatabase ones? 11(if so, it doesn't worked), or all of them, 23.
The numbers weren't set by me, but supposedly this is to achieve better server performance, you who understands, can explain a bit about it, please?

**Comment by jackpoz** [comment] 2016-06-07 15:10
With that many threads you most likely achieve only MySQL deadlocks than better performance. Could you ask who changed them what's the purpose of having that many threads and how they improve performances ? I'm quite curious too.

I'd lower everything to 2, maybe 1 step at time (from 4 to 3, from 5 to 4, etc).

As for the "11(if so, it doesn't worked)", did you clear the cooldown table before trying it ?

**Comment by sirikfoll** [comment] 2016-06-07 15:16
No, only changed the config to 11 on Saturday and waited for the global reset that occured today, seems to be improved the situation, just don't solve it completely. Also, exactly which table do you refer to? `character_instance`, `instance` or another?

**Comment by jackpoz** [comment] 2016-06-07 15:22
Try to set a higher value then, like 20 instead of 11. I'd still suggest to lower the number of threads tho.
