### ISSUE TITLE
[Crash] ICC in Detour/intersectRay GameObjectModel

### ISSUE THREAD

**Issue by Astrono1293** [TrinityCore/TrinityCore#24513] opened 2020-04-28 16:55 UTC
Server Crashed few times with this crash log, it seems as the server froze completely then Antistuck kicked the server. I could not find the exact reason for this but it seems it has something to do with Detour , ICC Gunship as the String name in crash log suggests.

`000007F68E7B7144  00000051E7B1EC70  GameObjectModel::intersectRay+44  c:\dedi\Vendetta\src\common\collision\models\gameobjectmodel.cpp line 167`

Branch: 3.3.5a
Revision: 61aec37b4ffd5fbd0bdde4de1cf7313d578651a7
System : Windows 2012 Server Edition

[vendetta.txt](https://github.com/TrinityCore/TrinityCore/files/4547283/vendetta.txt)

**Comment by Aokromes** [comment] 2020-04-28 17:02
vs studio 2017? yesterday's commit needs vs 2019 to compile.

**Comment by xParad0x** [comment] 2020-04-28 17:07
Confirmed. Crash happens every few days

**Comment by Astrono1293** [comment] 2020-04-28 17:11
> vs studio 2017? yesterday's commit needs vs 2019 to compile.

apologies i linked a wrong ref commit

**Comment by jackpoz** [comment] 2020-04-28 17:38
> Confirmed. Crash happens every few days

could you post the crashlog too ?

**Comment by jackpoz** [comment] 2020-04-28 17:40
@Astrono1293 do you have any custom change ? could you push those changes to a fork on github ?

**Comment by Astrono1293** [comment] 2020-04-28 17:44
@jackpoz  The only changes I use are Transmog and Custom Scripts for faction/race change. I have nothing custom except these 2 scripts. Our server is blizzlike x1 so we use nothing custom at all.

**Comment by jackpoz** [comment] 2020-04-28 17:46
well the crashlog is supposed to have the commit and branch in the first lines but yours doesn't. did you edit it ?

**Comment by Duratans** [comment] 2020-04-28 18:35
Yeaap, this is a very annoying crash, I think it happens during Gunship Encounter "possibly elsewhere as well" I have to ask our devs what they did to fix this. Something to do with the cannons. I could be incorrect on that notion.

**Comment by lastdarken** [comment] 2020-05-03 06:38
Confrim

**Comment by Faq** [comment] 2020-05-03 07:51
@lastdarken do you have crashlog to add?

**Comment by jackpoz** [comment] 2020-05-03 20:33
When confirming a crash, post the crashlog and include the commit hash please so we can work on it

**Comment by micckkk** [comment] 2023-09-15 13:05
Confirmed. Crash happens every few days

**Comment by micckkk** [comment] 2023-09-15 13:05
Confirmed. Crash happens every few days

**Comment by acidmanifesto** [comment] 2023-09-15 13:08
> Confirmed. Crash happens every few days

Do u have a crash log? This issue is over 3 years old.

**Comment by jackpoz** [comment] 2023-09-16 09:55
@micckkk please read https://github.com/TrinityCore/TrinityCore/issues/24513#issuecomment-623177115

**Comment by micckkk** [comment] 2023-09-16 15:27
> > Confirmed. Crash happens every few days
> 
> Do u have a crash log? This issue is over 3 years old.

0000000140DE8984  00000000478FD940  ?intersectRay@GameObjectModel@@QEBA_NAEBVRay@G3D@@AEAM_NIW4ModelIgnoreFlags@VMAP@@@Z+44
Branch: 3.3.5a
Revision: https://github.com/TrinityCore/TrinityCore/commit/cf2ca013f7a365907cbdd395350f0345f07d942b
Custom changes:
AC2
System : Windows 2016 Server

**Comment by acidmanifesto** [comment] 2023-09-16 15:56
> > > Confirmed. Crash happens every few days
> > 
> > Do u have a crash log? This issue is over 3 years old.
> 
> 0000000140DE8984  00000000478FD940  ?intersectRay@GameObjectModel@@QEBA_NAEBVRay@G3D@@AEAM_NIW4ModelIgnoreFlags@VMAP@@@Z+44
> Branch: 3.3.5a
> Revision: https://github.com/TrinityCore/TrinityCore/commit/cf2ca013f7a365907cbdd395350f0345f07d942b
> Custom changes:
> AC2
> System : Windows 2016 Server
> [d10e42c049b5+_worldserver.exe_[16-9_20-3-8].txt](https://github.com/TrinityCore/TrinityCore/files/12641010/d10e42c049b5%2B_worldserver.exe_.16-9_20-3-8.txt)
> 

```
Revision: TrinityCore rev. d10e42c049b5+ 2018-10-17 15:43:38 +0200 (3.3.5 branch) (Win64, Release, Static) Date 16:9:2023. Time 20:3 
```

Please update your build. Its nearly 5 years old

**Comment by Aokromes** [comment] 2023-09-16 17:38
i think i go to close this bug since no one on 3 years have posted a crashlog with updated core.

**Closed** 2023-09-16 22:11 UTC
Labels: HasBacktrace, Branch-3.3.5a
