### ISSUE TITLE
Quest / The Emissary 

### ISSUE THREAD

**Issue by Aldoran2020** [TrinityCore/TrinityCore#26279] opened 2021-03-20 09:57 UTC
**Description:**

Quest ID: 11626 / The Emissary 
https://www.wowhead.com/quest=11626/the-emissary
when using the trident it kills instant the NPC, and it  is impossible to complete. 

**Expected behaviour:**

Use the Trident of Naz'jan to slay him and return to Karuk to the north of Riplash Strand.

**Steps to reproduce the problem:**

1. add quest 11626, go Borean Tundra and use Trident of Naz'jan

**Branch(es):**

335

**TC rev. hash/commit:** 

TrinityCore rev. 8c3cddd 2021-03-15 17:34:11 +0000 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** 

windows pro

**Comment by CraftedRO** [comment] 2021-03-20 10:04
Not the trident cast shoud complete the animation but when you kill him

**Comment by CraftedRO** [comment] 2021-03-20 10:14
Trident does only let him low health so you can slain him , have you slain him after you used trident ?
I tryed this right now but on a gm level account , and it works well .

**Comment by Aldoran2020** [comment] 2021-03-20 10:21
![image](https://user-images.githubusercontent.com/68305780/111866515-575c3280-896e-11eb-9c3f-32781080d459.png)

using the items makes Naz,Jan die instant

**Comment by CraftedRO** [comment] 2021-03-20 10:23
neah , stop testing this only with gm level account and beside in this screenshoot I don't see the quest in the log near minimap

**Comment by CraftedRO** [comment] 2021-03-20 10:25
you are level 4 and tryng to complete a quest that Requires Level 68 / 71

**Comment by CraftedRO** [comment] 2021-03-20 10:27
Trust me if u wanna help create a normal player account and test all of them back , otherwise it will be time wasting for everyone :)

**Comment by Aldoran2020** [comment] 2021-03-20 10:30
![image](https://user-images.githubusercontent.com/68305780/111866708-a5256a80-896f-11eb-8be4-50333b3ae1f2.png)

same with player account... something to say? 
this was reported from 5 + users

**Comment by Aokromes** [comment] 2021-03-20 10:43
https://i.imgur.com/Rfwz9j0.png

**Comment by Aldoran2020** [comment] 2021-03-20 10:57
good that for you its working but not for me, if you use the  trident you instant  kill the NPC 
TrinityCore rev. 8c3cddd 2021-03-15 17:34:11 +0000 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
Tested on diferent player accounts. 
so bug report.

**Comment by Aldoran2020** [comment] 2021-03-20 11:02
![image](https://user-images.githubusercontent.com/68305780/111867415-05b6a680-8974-11eb-8571-9de1d2c4a940.png)
![image](https://user-images.githubusercontent.com/68305780/111867421-12d39580-8974-11eb-9835-9dae2c4fb735.png)
![image](https://user-images.githubusercontent.com/68305780/111867428-241ca200-8974-11eb-8bf7-09d50660e086.png)

**Comment by offl** [comment] 2021-03-20 15:43
I need more details:
1. Is he unnatackable before you use the item?
2. How much HP does he have?

**Comment by Aldoran2020** [comment] 2021-03-20 15:57
1. Yes unnatackable
2. 96100

**Comment by offl** [comment] 2021-03-20 16:10
So you just used the item and he was killed?

To me it looks like it's not even possible to kill him by that item, doesn't matter what you do because spell script doesn't allow to cast damaging spell (damages him for 93% of his total health) if his current HP below 95%

Spell is handled here https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_item.cpp#L3009-L3040

**Comment by Aldoran2020** [comment] 2021-03-20 16:41
https://user-images.githubusercontent.com/68305780/111877393-77f2af80-89a3-11eb-9996-2dbf7fed68cc.mp4

**Comment by offl** [comment] 2021-03-20 16:51
Well, I have no explanation for this, I tried multiple times and every time it worked correctly
Maybe someone else could explain why that spell kills him

**Comment by Aldoran2020** [comment] 2021-03-20 17:03
No changes att all on DB all clean

**Comment by CraftedRO** [comment] 2021-03-20 20:13
Interesting fact is that someone from AC reported same thing and they closed it because coudn't reproduce it (like a year ago) but same after the merge of Trident of Naz'jan item to SAI .
https://github.com/azerothcore/azerothcore-wotlk/issues/2552

**Comment by Aldoran2020** [comment] 2021-03-20 20:33
i dont understant what i am doing rong to produce this, but it happens allways

**Comment by offl** [comment] 2021-03-20 21:10
What
```sql
SELECT * FROM `spell_custom_attr` WHERE `entry`=49882
```
returns?

**Comment by CraftedRO** [comment] 2021-03-20 21:12
![sqqs](https://user-images.githubusercontent.com/24683355/111885646-c5861100-89d1-11eb-8834-b35365acbb68.JPG)
this ?

**Comment by offl** [comment] 2021-03-20 21:33
> Interesting fact is that someone from AC reported same thing and they closed it because coudn't reproduce it (like a year ago) but same after the merge of Trident of Naz'jan item to SAI .
azerothcore/azerothcore-wotlk#2552

Idk when SAI part was implemented
But the item script was converted to spell script in 2012 and slighly changed in 2014

**Comment by CraftedRO** [comment] 2021-03-20 21:36
https://github.com/azerothcore/azerothcore-wotlk/pull/1736

**Comment by offl** [comment] 2021-03-20 21:38
I meant TC

**Comment by CraftedRO** [comment] 2021-03-20 21:43
this https://github.com/TrinityCore/TrinityCore/pull/20468 ?

**Comment by CraftedRO** [comment] 2021-03-20 22:06
what's happening with that 5 min buff that npc shoud give you when you accept this quest ?

**Comment by Conscript01** [comment] 2021-03-25 15:43
0ba62a45e5c60efd37a0b2c7534b44c3a3fc151e working properly

**Comment by illfated** [comment] 2021-03-26 07:00
Could this be caused by game client modifications or DBC editing, for example if the DBC source files are tailored to a different custom server setup?

**Comment by CraftedRO** [comment] 2021-03-28 17:30
or maybe some worldserver configs that land to this

**Comment by offl** [comment] 2021-04-01 18:22
> 0ba62a45e5c60efd37a0b2c7534b44c3a3fc151e working properly

This issue happens only to one user and of course it will work for you or for me, however he can try on another revision

**Comment by illfated** [comment] 2021-04-03 15:09
[16:54:44] TrinityCore rev. 80f30d5ca94f 2021-03-26 13:26:21 +0100 (3.3.5 branch) (Win64, Release, Static)
```sql
[16:54:44] Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
[16:54:44] Using Boost version: 1.74.0
[16:54:44] Using MySQL version: 50732
[16:54:44] Using CMake version: 3.19.2
[16:54:44] Compiled on: Windows 10.0.19042
[16:54:44] Automatic database updates are enabled for the following databases: Auth, Characters, World
[16:54:44] Worldserver listening connections on port 8085
[16:54:44] Realmlist (Realm Id: 1) configured in port 8085
[16:54:44] VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
[16:54:44] MMAPs status: Enabled
[16:54:46] maps directory located in ./maps. Total size: 251987687 bytes
[16:54:51] vmaps directory located in ./vmaps. Total size: 658130721 bytes
[16:54:52] mmaps directory located in ./mmaps. Total size: 1962379500 bytes
[16:54:52] Using enUS DBC Locale as default. All available DBC locales: enUS 
[16:54:52] Using World DB: TDB 335.21031
```

Yes, it is exactly as you said, @offl , this quest works just as expected for everyone else. I also finished the quest on the tcubuntu.northeurope.cloudapp.azure.com server in December or January, so I find it quite difficult to understand why it would not work unless some form of customization is involved.

Today, I used item 35850 (Trident of Naz'jan) more than 10 times in a row now, successfully lowering Leviroth's HP from 96100 to somewhere between 6471 and 6131 (on average) before killing the NPC as if it were a regular NPC with a regular health pool. The variation in HP reduction is a bit curious (maybe not to a real coder), so do you think it could possibly affect the item spell if the player character has got abnormally high crit + hit stats, maybe by wearing maxed-out gear (armor, weapons, rings, trinkets, enchants)?

- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=11626/the-emissary
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=26452/leviroth
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=35850/trident-of-nazjan
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=47170/impale-leviroth
- Effect # 1 [ Dummy | Radius: 18 yards | Server-side script ]

https://github.com/TrinityCore/TrinityCore/blob/80f30d5ca94f000962a06e398567aa0b1ddd706b/src/server/scripts/Spells/spell_item.cpp#L3009-L3040

**Comment by offl** [comment] 2021-04-03 15:19
> The variation in HP reduction is a bit curious (maybe not to a real coder), so do you think it could possibly affect the item spell if the player character has got abnormally high crit + hit stats, maybe by wearing maxed-out gear (armor, weapons, rings, trinkets, enchants)?

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=49882 is a self cast, it does not take player stats in consideration

**Comment by illfated** [comment] 2021-04-03 15:26
> https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=49882 is a self cast, it does not take player stats in consideration

Good point. All the more reason to close this issue as non-reproducible.

**Comment by offl** [comment] 2021-04-03 15:36
@Aldoran2020 you can

1. recompile again
2. change client to different(who knows)
3. downgrade core to revision before https://github.com/TrinityCore/TrinityCore/commit/17143938d7f5126b8c8e6ed5fc1229b6c2665ec3
4. remove this condition if it still exists https://github.com/TrinityCore/TrinityCore/commit/17143938d7f5126b8c8e6ed5fc1229b6c2665ec3#diff-7d50883eb734e553c80d5e8234f7b4a4789c6e4ea836fb6b2789da2c65eec17eR9
5. remove script from creature 26452 and remove its unit_flags to make creature attackable OR remove certain actions listed here https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=26452 (just keep in mind first three are linked together)

**Comment by offl** [comment] 2021-04-09 10:45
I can reopen if someone find what causes this issue

**Closed by offl** 2021-04-09 10:45 UTC
Labels: Branch-3.3.5a, Invalid-CannotReproduce, Sub-Quests
