### ISSUE TITLE
[BUG] The Black Knight's Order

### ISSUE THREAD

**Issue by DoctorHR** [TrinityCore/TrinityCore#7468] opened 2012-08-21 18:05 UTC
The quest [The Black Knight's Order] is bugged.
after you use the quest item, Enchanted Bridle, the black gryphon apears, a chat box opens but you cant get on the gryphon himself, which makes it impossible to complete.

Useful links:

Quest:
http://www.wowhead.com/quest=13663

Quest item:
http://www.wowhead.com/item=45083

thanks, DoctorHR

Hash: 3c42401

**Comment by Killyana** [comment] 2015-04-08 13:48
The hole  quest is already scripted the problem is https://github.com/TrinityCore/TrinityCore/issues/8195 if you use another vehicleid for http://www.wowhead.com/npc=33519 it works, but ti's a hack.

**Comment by StormBytePP** [comment] 2015-08-28 23:07
Fixed by rev ac2845ee77d0f3e838267ad424fbcf4894040333

**Closed by StormBytePP** 2015-08-28 23:07 UTC
Labels: Sub-Quests, Sub-Vehicles
