### ISSUE TITLE
[master] Core/Groups: group/raid issues - continued

### ISSUE THREAD

**Issue by DJScias** [TrinityCore/TrinityCore#19024] opened 2017-02-01 22:48 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Figured I'd make a new issue instead of necro'ing the old one (#18757).

There's still bugs with groups, even after 4275a9fdbf505834f7748b424a73d2dd4a5f6b4e and d2c77d823d6ab681a426aec9b179c54b29417ad6.

**Current behaviour:** (Tell us what happens.)
- Groups don't disband decently with 2+ players in it.
- Groups converted to raids don't show as raids when someone has had the "bugged group frames" before. This also fucks up their chatting in raid options.

**Expected behaviour:** (Tell us what should happen instead.)
- The group disbands and it's updated for all players
- Every group member sees the raid

**Steps to reproduce the problem:**

To reproduce the frame bugs :
1. Make a group with 2+ players (3 for example)
2. Leave the group
3. See the frames still exist.

For some members, the raid doesn't exist :
1. Follow the above steps.
2. re-invite the person that has bugged frames.
3. Convert to raid (either before or after inviting them, doesn't matter)
4. Everyone can talk in raid except for the person with bugged frames

A video showing these issues:
https://www.youtube.com/watch?v=U9U_-IoL5B0

**Branch(es):** `master`

**TC rev. hash/commit:**  d1e9bb6f2681adc199ea05af938c229779d98d07

**TDB version:**  TDB 703.00

**Operating system:**  Windows 10 Ultimate 64-Bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Skizooo** [comment] 2017-02-02 01:31
I don't got that issue, for me everything works as intended, after those commits.

**Comment by DJScias** [comment] 2017-02-02 02:28
@Skizooo Have you tried it with three players? Because it works as intended with two.

**Comment by Edreisantafe** [comment] 2017-02-02 16:22
This is a duplicate of #18789 open by me.

**Closed** 2017-02-02 17:00 UTC
Labels: Branch-master, Comp-Core, Sub-Instances
