### ISSUE TITLE
Core/Chat: chat text is not correctly sent when the player controls a creature

### ISSUE THREAD

**Issue by Wyrserth** [TrinityCore/TrinityCore#23587] opened 2019-07-12 14:47 UTC
**Description:**

When a player controls a creature (for example the [Eye of Acherus](https://www.wowhead.com/quest=12641)) they should be able to see the chat text that nearby creatures send ([example](https://youtu.be/mYXD-Z_ie7g?t=91)).

Right now they only receive the text from sources that are near the player, and the text from sources that are near the controlled creature are ignored.

This should be handled in a way that doesn't allow players to receive duplicated text packets when the controlled creature is near the player controlling it.

This also affects Eye of the Beast and any other case where the player can control and move a creature.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 6dfb4fde07082498a264ca0802ebdeb0bf3fa994

**Test case**:

Execute this script: https://gist.github.com/Wyrserth/f9f7d865f3e1d1f68bb435473e3fd7f1

Go near the creature High General Abbendis. She's together with a group of citizens near the point where the Eye of Acherus lands. The creatures will do their talk emotes but no text will appear in the chat log.

**Comment by Treeston** [comment] 2019-07-13 15:14
Should you still be able to see chatter from units near the player character?

**Comment by Wyrserth** [comment] 2019-07-13 15:24
I think you should see both, but I'm not 100% sure. I'll see if I can test it on the PTR, will report back.

**Comment by offl** [comment] 2022-01-20 23:05
Duplicate of #27652

**Closed by offl** 2022-01-20 23:05 UTC
Labels: Comp-Core, Branch-3.3.5a, Priority-Cosmetic, Sub-Chat
