### ISSUE TITLE
[3.3.5] Envenom vs Cleansing Totem.

### ISSUE THREAD

**Issue by DevRival** [TrinityCore/TrinityCore#15946] opened 2015-12-05 21:05 UTC
Core: [984bf32](https://github.com/TrinityCore/TrinityCore/commit/984bf32fa89d25000f3ff369092bf9034e7a860b)
TDB 335.60
When we get the buff after using a spell [Envenom](http://db.uawow.com/?spell=57993), friendly [Cleansing Totem](http://db.uawow.com/?spell=8170) removes it . But this should not be .

**Comment by tkrokli** [comment] 2015-12-05 22:34
3.3.5 information in English (the spells have different IDs on wowhead)
http://wotlk.openwow.com/spell=57993/envenom
http://wotlk.openwow.com/spell=8170/cleansing-totem

When you say "friendly Cleansing Totem", do you mean friendly to the rogue or to the victim?

**Comment by Demonid** [comment] 2015-12-06 01:52
https://github.com/TrinityCore/TrinityCore/issues/15321

**Comment by tkrokli** [comment] 2015-12-06 02:02
Yes, this issue is a duplicate of #15321 - please close this one.

**Closed** 2015-12-06 02:46 UTC
