### ISSUE TITLE
InstanceMap::Update crash

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22770] opened 2018-11-06 13:37 UTC
Description:  Crashed By Object

        Crash(formattedMessage.c_str());
        in GetMap ASSERTION FAILED:
        m_currMap
        obj = 0x7fff356bf000
        updater = {i_timeDiff = 100}
        world_object_update = {i_visitor = @0x7fff4d3fd600}
        grid_object_update = {i_visitor = @0x7fff4d3fd600}

https://gist.github.com/Hir0shi/c62dd95d2df07771dee28aa33f862842

Branch: 3.3.5

TC rev: https://github.com/TrinityCore/TrinityCore/commit/d8fee3c46b70fed660aec905a496e56d6a327aaf
Operating system: debian

**Comment by jackpoz** [comment] 2018-11-10 21:02
as the crashlog contains very few informations, this issue requires to rework what kind of informations we log when triggering an assert. I plan on opening a PR about it.

**Comment by sirikfoll** [comment] 2018-11-10 22:05
This crash seems to be the same as #21403
I have tried to investigate this, and so far I'm thinking thats something related to multithreading, because it makes no sense, in one line everything is ok, and on the next, whatever function call will cause a crash..
Also, afaik, it only happens in Naxxramas.

**Comment by jackpoz** [comment] 2018-11-10 22:16
it's more likely it's Naxxramas script being buggy then multithreading. Do you have any crashlog about it ?

**Comment by sirikfoll** [comment] 2018-11-10 23:11
https://gist.github.com/sirikfoll/e9b2c695754629ddb353e73bb111d9df (It'd not clean, i had some things here and there to try and get more info)
I know It's in Naxxramas because I had added a variable to catch mapId, seen by "debugMapID = 533" in the log.
Also know it can crash in anything you put under WorldObject::GetGridActivationRange, or even before that call, i had added some logs just above here, and it crashed as well
https://github.com/TrinityCore/TrinityCore/blob/be47254a4f7ac9fd0497477a597e2a09019561e9/src/server/game/Maps/Map.cpp#L708

**Comment by Hir0shi** [comment] 2018-11-11 01:58
I helped a programmer and the problem was resolved, this update

`
UPDATE creature_template SET `BaseAttackTime` = 2000 WHERE `BaseAttackTime` = 0;

`

**Comment by Hir0shi** [comment] 2018-11-11 02:15
hi all
I got help from a programmer and I think the problem was fixed!

i will to remove this line

float Object::GetFloatValue(uint16 index) const
{
- ASSERT(index < m_valuesCount || PrintIndexError(index, false));
return m_floatValues[index];
}

and import in world database

UPDATE creature_template SET `BaseAttackTime` = 2000 WHERE `BaseAttackTime` = 0;

------


But Server New Crashed By

https://gist.github.com/Hir0shi/286af76c0cf036d4fc89ba7c78e2b314

**Comment by pak3935** [comment] 2018-11-11 15:44
> UPDATE creature_template SET BaseAttackTime = 2000 WHERE BaseAttackTime = 0;

Does this solve the problem? о_О

**Comment by Aokromes** [comment] 2018-11-11 16:10
ofc no, there is no mob with that value on clean tdb 3.3.5a.

**Comment by illfated** [comment] 2018-11-11 18:18
TrinityCore rev. be47254a4f7a 2018-11-09 20:51:20 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
```sql
SELECT * FROM `creature_template` WHERE `BaseAttackTime` = 0;
```
`Result: 0 row(s)`

I suspect there is more custom content in Hir0shi's source and DB than we know.

**Comment by Hir0shi** [comment] 2018-11-12 02:00
@jackpoz 

i will to full tested naxxramas and crash is for this instance , boss = Thaddius

**Comment by jackpoz** [comment] 2018-12-01 18:40
anyone was able to repro the issue in Debug to get a detailed crashlog ? maybe even with Address Sanitizer ?

**Comment by TheWinchesters** [comment] 2018-12-01 21:57
I have had people doing Naxxramas and no crashs so far

**Comment by Hir0shi** [comment] 2018-12-27 16:11
Player cheat on, going for the last boss , objects It activates and server will to crashed.

**Comment by Faq** [comment] 2018-12-27 18:17
@Hir0shi where is new crashlog?

**Comment by Hir0shi** [comment] 2018-12-28 10:32
https://gist.github.com/Hir0shi/e7eca1dddfe5f7815f0a168552546a27

**Comment by illfated** [comment] 2018-12-29 09:31
That is the crash log from 2018-11-12 (12. November).
You commented as if you had a new crash, so Faq wanted to see the new crash log.
> Player cheat on, going for the last boss , objects It activates and server will to crashed.

**Comment by jackpoz** [comment] 2019-01-04 09:09
> anyone was able to repro the issue in Debug to get a detailed crashlog ?

anyone ?

**Comment by jackpoz** [comment] 2019-01-19 17:32
still waiting for a crash log in Debug

**Comment by TheWinchesters** [comment] 2019-01-19 17:38
@jackpoz I will recompile in debug mode and I'll give it a try.
If I understand correctyl, Thaddius is the target to test.

**Comment by jackpoz** [comment] 2019-01-19 17:39
even clear How To Reproduce steps would be nice, once we have those we can repro it in Debug and get a nice crash report

**Comment by jackpoz** [comment] 2019-01-20 08:20
Thaddius script looks like a huge hack with setActive() calls (and of course no comments about why those are needed)

**Comment by jackpoz** [comment] 2019-01-20 08:32
There are some leftovers from https://github.com/TrinityCore/TrinityCore/commit/184c45cfe0fbe4f3e4fb701f0f99994df98bdc8a too (starting 200 things and not finishing any...), maybe it's the cause of the issue. Thaddius reset for me also

**Comment by opiums9** [comment] 2019-01-23 06:44
Hello, I stumbled upon a similar problem:
https://gist.github.com/opiums9/4c3af260c7e99944aa2782927ec376c3
https://gist.github.com/opiums9/ee5d10ad772bed1c1ac0250a4f8f11e4

**Comment by jackpoz** [comment] 2019-04-25 19:01
was anyone able to reproduce the issue with TC build in debug mode ?

**Comment by jackpoz** [comment] 2019-04-25 19:15
same issue as https://github.com/TrinityCore/TrinityCore/issues/21403 most likely

**Comment by sirikfoll** [comment] 2019-04-25 19:47
Although I can't reproduce this crash, I'm pretty sure the problem here is that you can't call
`DespawnOrUnsummon` before `setActive(false);`
Just swapping the order of those calls in Thadius script is working for me

**Comment by jackpoz** [comment] 2019-04-26 17:21
Please meet the Thaddius crash:
![image](https://user-images.githubusercontent.com/1153754/56825066-6dcbe300-6858-11e9-8730-d8026ecbf4c6.png)

**Comment by jackpoz** [comment] 2019-04-26 19:06
strangely enough the crashing object doesn't have any of the typical VC++ magic numbers, maybe the memory was reused already before it crashed

![image](https://user-images.githubusercontent.com/1153754/56830631-1f721080-6867-11e9-8806-115276cfdb15.png)

**Comment by jackpoz** [comment] 2019-04-27 11:58
Fixed in https://github.com/TrinityCore/TrinityCore/commit/1c833f28e471e3787f1d328e44af5f065ad9ca8c

**Closed by jackpoz** 2019-04-27 11:58 UTC
Labels: Branch-3.3.5a, HasBacktrace
