### ISSUE TITLE
[3.3.5][6.x] Core/Instance: instance->GetPlayers(); issue

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#16932] opened 2016-04-10 19:25 UTC
**Description**:
instance->GetPlayers();
**Current behaviour**:
When called from "void OnCreatureCreate(Creature\* creature)" in Scripts, "players" is allways empty.
**Expected behaviour**:

``` c#
                    Map::PlayerList const &players = instance->GetPlayers();
                    if (!players.isEmpty())
                        if (Player* player = players.begin()->GetSource())
                            TeamInInstance = player->GetTeam();
```

"TeamInInstance" should be filled

_Any help or suggestions will be grateful_

**Branch(es)**: 335/6x
335
**TC hash/commit**:
7834d33
**TDB version**:
60
**Operating system**:
Linux

**Comment by jackpoz** [comment] 2016-04-10 20:43
isn't that OnCreatureCreate() is called when there are no players yet in the instance ?

**Comment by n4ndo** [comment] 2016-04-10 21:00
Hello @jackpoz, so how exactly works this part? https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp#L187, cuz in that case is not possible to

```c#
     if (TeamInInstance == ALLIANCE)
```

ve true ever.

**Comment by Ovahlord** [comment] 2016-04-10 21:17
It's an additional check in case that  void OnPlayerEnter(Player* player) override  is not going to work properly for example if you enter the instance by logging in for example.

**Comment by n4ndo** [comment] 2016-04-10 21:37
i see, so i dont understand why testing as ally, everytime i have garrosh instead Varian :/

GM mode should affect?

**Comment by tkrokli** [comment] 2016-04-10 22:20
GM mode (GM ON) invalidates testing because the player character will not have the right faction value.

**Comment by n4ndo** [comment] 2016-04-10 22:57
So weird, just re-test.

1. .instance unbind all
2. .gm off
3. join as team alliance

Garrosh appear.

**Comment by Aokromes** [comment] 2016-04-10 23:00
cannot reproduce: 

http://i.imgur.com/Cb1xRE4.jpg

**Comment by n4ndo** [comment] 2016-04-11 06:10
Hello, @jackpoz @Aokromes @tkrokli @Ovahlord; well, after some changes i change GameType option in worldserver.conf from 1 to 0 and the problem is now solved, but.... any ideas why happen this?

Thank you.

**Comment by Aokromes** [comment] 2016-04-11 06:47
Dunno, my gametype is 1.

**Comment by jackpoz** [comment] 2016-04-11 10:21
this issue is no longer about instance->GetPlayers() returning an empty container ? did you debug the code to ensure it was actually returning an empty container ?

**Comment by n4ndo** [comment] 2016-04-11 15:20
Hello @Aokromes my mistake, this happen with:

```c#
     GridUnload = 0
```

**Comment by tkrokli** [comment] 2016-04-11 15:41
Right. `GridUnload = 0` is not the default setting, so this would explain why others could not replicate it.

**Comment by jackpoz** [comment] 2016-04-12 08:53
Please stop @'ing me or I'll block you

**Comment by tkrokli** [comment] 2016-12-13 17:53
@n4ndo : is this issue still valid? If it is no longer showing up with default settings, it should be closed.

**Comment by n4ndo** [comment] 2016-12-13 18:42
Hello @tkrokli i still have GridUnload = 1, if you want i can test this again.

**Comment by tkrokli** [comment] 2016-12-14 18:19
Yes. please. If you can test with one of the new commits and confirm that it still is the same with default settings, it would be useful in order to keep the issue up to date so we know it hasn't changed yet.

I presume you know that issues should be confirmed on straight, unmodified TC source with no addons.

**Comment by Keader** [comment] 2017-01-08 04:04
Any news @n4ndo ?

**Comment by Aokromes** [comment] 2017-03-27 04:51
No answer after  near 4 months, closing, if this bug is still valid plz open a new ticket with one updated core.

**Closed by Aokromes** 2017-03-27 04:51 UTC
Labels: Comp-C++Script, Comp-Core, Feedback-WaitingResponse, Sub-Instances
