### ISSUE TITLE
Crash in Player::StopCastingCharm

### ISSUE THREAD

**Issue by gtestdev** [TrinityCore/TrinityCore#24876] opened 2020-06-23 09:09 UTC
**Description:**

Crashlog: https://gist.github.com/gtestdev/885806a70c355cebcf44dbfa62acfff7

I found that in server.log before crash:

```
2020-06-23_01:16:10 Player::StopCastingCharm: Player 'Icaru' (GUID Full: 0x000000000000617e Type: Player Low: 24958) is not able to uncharm unit (GUID Full: 0xf150006c2c00014d Type: Vehicle Entry: 27692  Low: 333)
2020-06-23_01:16:10 Player::StopCastingCharm: Charmed unit has charmer GUID Full: 0x000000000000617e Type: Player Low: 24958
```

**Steps to reproduce the problem:**

1. I don't know how to reproduce it, seems related with dungeon oculus and emerald drake (https://www.wowhead.com/npc=27692/emerald-drake)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

dc41aae0427faecef57b831f3a2ed735a9369dd7

**Operating system:** debian10

**Comment by jackpoz** [comment] 2020-07-05 18:32
do you have any custom change applied ?

**Comment by gtestdev** [comment] 2020-07-06 09:50
No, Icaru is a hunter and he did nothing special, maybe he lost the connection.
I did  a lot of test with that items inside oculus and summon dragons and logout and... a lot of things, but I can't reproduce it.

**Comment by Astrono1293** [comment] 2021-05-15 21:03
Confirmed. had this crash today with vehicle entry : 30161 exactly the same log as OP posted

**Comment by jackpoz** [comment] 2021-05-15 21:05
Please include commit hash and the actual crashlog when confirming a crash

**Comment by Astrono1293** [comment] 2021-05-25 15:46
There is nothing to confirm., its almost identical crash and it's happening on the latest hash. This problem is years old and still not fixed, at least remove FATAL and ABORT from the StopCastingCharm in Unit.cpp and Player.cpp until the issues is fixed.

**Comment by Demonasus** [comment] 2021-05-25 15:56
Yeap, annoying crash.  usually happens with Wyrmrest Skytalon [ID: 30161] . I cannot confirm if it's happening during the quest Aces High or in fact during Malygos encounter phase 3.

**Comment by Demonasus** [comment] 2021-05-25 16:55
> @Astrono1293 and @Demonasus the point of providing hash with comment is to track on what commit it still exists. And updated crashlog sometimes might give some extra information what would help to identify what could be the steps to reproduce it.

I never said otherwise, I just dont want to waste my time posting one to see 2-3 devs from TC telling me I have a custom core/fork as they always do and close the issue.

**Comment by jackpoz** [comment] 2021-05-25 20:25
Do you know the reason why we ask if you have custom changes? Like, why is it so important when checking a crashlog to know if there are custom changes ?

We know everyone has custom changes, but a crashlog contains only the file name and the line number, not the whole file. If you add 1 line, all the line numbers in the crashlog will not match TC sources and will make it impossible to read.

The best way would be to try reproducing the issue on a clean TC. If that's not possible, one could provide a link to a public fork on github with all the custom changes.

Please let's skip any time consuming discussion and focus instead on the actual issue. If you have a crashlog, post it with the commit hash and with the list of custom changes.

**Comment by Demonasus** [comment] 2021-05-25 22:43
Alright I will try this one more time and see what happens

**Comment by Astrono1293** [comment] 2021-05-25 23:42
> I never said otherwise, I just dont want to waste my time posting one to see 2-3 devs from TC telling me I have a custom core/fork as they always do and close the issue.

You were straight on point there! lol. 

To be perfectly logical, nobody uses latest TC on their Private Servers with an actual population. 99% of server owners use stable forks from 2017-2019. So how would you even try to absorb the message " Reproduce the issue on the latest TC" if you have 1 player online, I mean what are you supposed to do? Especially if you tried everything and still do not know what causes the crash. So you just have to build the latest TC and run around trying to reproduce the crash aimlessly? The whole idea is that the crashes mostly happen on live servers with hundreds online, that's when these crashes happen mostly and the fact nobody can post them because of a dumb rule "YOU NOT USING LATEST TC GTFO" so only thing supported here is a clean TC fork from present hash? it's so weird man.

**Comment by subsix-wow** [comment] 2021-05-26 00:00
I totally understand the point of the devs/contributors.
If you can't reproduce the crash on a clean TC Compile with clean TDB aswell, then stick to your custom fork and try to settle it on your own.
This project is built upon itself, not some fork. 
Each addition some "Dev" makes will likely break something.
It's not the responsibility of TC to fix such kind of issues.

Simply live with it. 
Be grateful for such great base we all have gotten to build our servers on.

**Comment by Astrono1293** [comment] 2021-05-26 03:11
You are a god damn retard. Maybe you should read the whole post. @Demonasus said he does not want to waste his time posting a crash log because of it and he was suggested to do it anyway. If you code/work for a server that makes such drastic changes to charmed units you must be a moron. Nobody is dumb enough to rewrite a system that's been in place for years? Custom forks 99% of the time means, that server owners/devs cherry pick commits to make sure the server is stable. 99% of servers do just that because of stability issues and i can most certain guarantee you none of them ever touched anything related to charmed units. Anyways, this is a waste of time talking to god damn retards.

**Comment by jackpoz** [comment] 2021-05-26 07:44
@Demonasus your crashlog has WorldSession::HandleLogoutRequestOpcode while the one from this issue has WorldSession::~WorldSession , so it happens in the 2 cases of user disconnecting or logging out manually (which helps so we don't need to try disconnecting)

**Comment by jackpoz** [comment] 2021-05-26 07:45
@Astrono1293 you can keep the insults out from TC project, ty.

**Comment by Rushor** [comment] 2021-05-29 16:57
30161 entry is related to EoE only, for quest Aces High, onlc creature Wyrmrest Skytalon npc=32535 is used, no crash related to that so far.

Someone experienced a simila crash by other creatures ids except 30161 ?

**Comment by gtestdev** [comment] 2021-05-30 09:05
as I put in the first comment, it happens with the drakes of the oculus, I have also had the crash with the drakes of eye of eternity.
I still don't know how to reproduce the crash

**Comment by CraftedRO** [comment] 2021-06-01 09:33
I managed to also crash the server today on rev. e7e47866066f (relwithdebuginfo) with gm account in oculus 5 heroic, but I coudn't explain exactly what I did (indeed seems drake related or something when you stack parachute and the other slow falling effect maybe - I only remember last seconds before I get disconnected I was falling after spamming drake spells) but I coudn't reproduce it . here's the log : [Crashes.zip](https://github.com/TrinityCore/TrinityCore/files/6575101/Crashes.zip)

**Comment by jackpoz** [comment] 2021-06-01 19:39
@CraftedRO that crashlog contains `FreezeDetector::Handler ABORTED` which means your server took too long to update, maybe caused by an infinite loop. It's a different case as this issue is about an assert triggered by Player::StopCastingCharm

**Comment by Demonasus** [comment] 2021-06-01 23:02
Wouldn't it be more efficient to change FATAL conditions to DEBUG? So the server would not crash instead?

**Comment by Aokromes** [comment] 2021-06-02 07:06
> Wouldn't it be more efficient to change FATAL conditions to DEBUG? So the server would not crash instead?

then no one will report the issue.

**Comment by jackpoz** [comment] 2021-06-02 09:48
That depends only by the issue and by the code. Chances are it will crash later on our the players will have strange issues, like being stuck.

The best thing to do is to fix the actual issue.

**Comment by jackpoz** [comment] 2021-06-05 12:34
I wonder if this is caused by this part:
```c++
        bool seatChange = (mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT)                             // Seat change on the same direct vehicle
            || target->HasAuraTypeWithCaster(SPELL_AURA_CONTROL_VEHICLE, caster->GetGUID());    // Seat change to a proxy vehicle (for example turret mounted on a siege engine)

        if (!seatChange)
            caster->_ExitVehicle();
        else
            target->GetVehicleKit()->RemovePassenger(caster);  // Only remove passenger from vehicle without launching exit movement or despawning the vehicle
```
in particular the seatChange case, as that doesn't despawn the vehicle.

**Comment by jackpoz** [comment] 2021-06-05 13:51
Can one die while mounting those dragons (while doing the actual action of entering the vehicle) ?

**Comment by jackpoz** [comment] 2021-06-05 16:43
https://github.com/TrinityCore/TrinityCore/commit/af815e991d3dc407846fcd05000b4e356d7336ed will log more information, which means next time someone confirms this crash please include the crashlog and the worldserver log.

**Comment by jackpoz** [comment] 2021-11-14 10:13
@gtestdev thanks for the log

**Comment by Shauren** [comment] 2021-11-14 14:54
Can you apply and report back if you get the new log I add there? "because of missing SPELL_AURA_CONTROL_VEHICLE"
```diff
diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index f2549dcf62..8d18dba876 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -20745,7 +20745,19 @@ void Player::StopCastingCharm()
         if (charm->ToCreature()->HasUnitTypeMask(UNIT_MASK_PUPPET))
             static_cast<Puppet*>(charm)->UnSummon();
         else if (charm->IsVehicle())
+        {
             ExitVehicle();
+
+            if (!GetCharmedGUID().IsEmpty() && !charm->HasAuraTypeWithCaster(SPELL_AURA_CONTROL_VEHICLE, GetGUID()))
+            {
+                TC_LOG_FATAL("entities.player", "Player::StopCastingCharm Player '%s' (%s) is not able to uncharm vehicle (%s) because of missing SPELL_AURA_CONTROL_VEHICLE",
+                    GetName().c_str(), GetGUID().ToString().c_str(), GetCharmedGUID().ToString().c_str());
+
+                // attempt to recover from missing HandleAuraControlVehicle unapply handling
+                // THIS IS A HACK, NEED TO FIND HOW IS IT EVEN POSSBLE TO NOT HAVE THE AURA
+                _ExitVehicle();
+            }
+        }
     }
     if (GetCharmedGUID())
         charm->RemoveCharmAuras();
```

**Comment by Aokromes** [comment] 2021-11-15 09:44
anyone of the persons having issues uses a 3rd party anticheat? if yes, witch one.

**Comment by gtestdev** [comment] 2021-11-27 09:48
I have obtained the log with the following information and without crash the server, also at the same time the same player has obtained another log, if it helps, I put both:
```
2021-11-24_03:52:06 Player::CreateViewpoint: Player 'Luzsy' (GUID Full: 0x0000000000071526 Type: Player Low: 464166) cannot add new viewpoint!
2021-11-24_03:52:06 Player::StopCastingCharm Player 'Luzsy' (GUID Full: 0x0000000000071526 Type: Player Low: 464166) is not able to uncharm vehicle (GUID Full: 0xf150006c6b0000de Type: Vehicle Entry: 27755  Low: 222) because of missing SPELL_AURA_CONTROL_VEHICLE
```

**Comment by Faq** [comment] 2021-11-27 10:14
@gtestdev what rev?

**Comment by Aokromes** [comment] 2021-11-27 11:48
again anyone of the persons having issues uses a 3rd party anticheat? if yes, which one.

**Comment by Shauren** [comment] 2021-11-27 15:37
Check if the log now completely disappears after 9174281b9253712982273b9b703d9fbac5cef9cd

**Comment by Shauren** [comment] 2022-02-10 22:53
Assuming this is fixed

**Closed by Shauren** 2022-02-10 22:53 UTC
Labels: HasBacktrace, Branch-3.3.5a

**Comment by gtestdev** [comment] 2022-02-11 10:04
Yes thanks.
Not knowing how to reproduce it, I was waiting to see, but everything was fine.

**Comment by Shauren** [comment] 2022-02-11 10:17
@gtestdev did the log containing `is not able to uncharm vehicle` appear again after 9174281b9253712982273b9b703d9fbac5cef9cd?

**Comment by gtestdev** [comment] 2022-02-11 10:24
I've had a single log about it a few weeks after that commit date, but I'm not 100% sure if I had updated to that commit on that date or it was a few days later.
but so far this year the log has not reappeared, although it is also true that this log appeared very few times, it is not frequent.

**Comment by gtestdev** [comment] 2022-02-11 12:37
You can revert the temporary commit if you want, I will keep it for a while and periodically check if it appears again or not, in case it appears I will indicate it
