### ISSUE TITLE
[Crash] npc_saurfang_event::npc_saurfang_eventAI::SetData

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#18193] opened 2016-11-03 21:20 UTC
**Description:** server crashes on starting boss

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  5868509a6366d0ba7a0fe819c3ece0e4a57c7029

**TDB version:**  61

**Operating system:**  Debian 8

http://paste.ubuntu.com/23422500/
http://paste.ubuntu.com/23422501/

**Comment by tkrokli** [comment] 2016-11-03 21:36
Please notice that [src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp) was last updated on September 26, 2016 (as of the time of this issue and my comment), which puts your core revision more than 2 months behind current source, if that file is the only cause of your issue. While I am unable to tell if this makes a difference to your issue, TrinityCore developers will normally ask users to update to more current source to see if the issue goes away with recent source.

**Comment by sirikfoll** [comment] 2016-11-03 22:05
@sucklifex Try running this query and check the result, there should be 5 npcs of entry=37920 only, if there is anything more than those 5, could be the cause of your crash
```sql
SELECT * FROM `creature` WHERE `id` IN (37920,37830);

**Comment by sucklifex** [comment] 2016-11-04 01:53
Result
```
INSERT INTO `creature` VALUES (200907, 37920, 631, 0, 0, 15, 1, 0, 1, -557.304, 2208.2, 539.37, 0, 86400, 0, 0, 134810, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` VALUES (200944, 37920, 631, 0, 0, 15, 1, 0, 1, -559.167, 2211.43, 539.369, 0, 86400, 0, 0, 134810, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` VALUES (201034, 37920, 631, 0, 0, 15, 1, 0, 1, -557.264, 2215.06, 539.37, 0, 86400, 0, 0, 134810, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` VALUES (201069, 37920, 631, 0, 0, 15, 1, 0, 1, -561.049, 2207.88, 539.368, 0, 86400, 0, 0, 134810, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` VALUES (201184, 37920, 631, 0, 0, 15, 1, 0, 1, -560.901, 2214.58, 539.368, 0, 86400, 0, 0, 134810, 0, 0, 0, 0, 0, 0);
```

**Comment by Aokromes** [comment] 2016-11-04 07:44
The script was updated 3 times between your commit and now.

**Comment by jackpoz** [comment] 2016-11-04 09:14
is this a crashlog from worldserver built in Debug mode ?

**Comment by jackpoz** [comment] 2016-11-04 09:29
why is there a container storing Creature* in a AI script o.O https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp#L809

**Comment by sucklifex** [comment] 2016-11-04 12:43
@jackpoz it has compiled in RelWithDebug

**Comment by jackpoz** [comment] 2016-11-04 13:42
> if there is anything more than those 5, could be the cause of your crash

lol just noticed what you mean, that's the worst code ever triggering an assert if there are more than 5 npcs. it should be fixed!

**Comment by Aokromes** [comment] 2017-03-11 12:00
No one else reported this crash, and like i wrote months ago this scripts changed 3 times between the hash used on the report and the date of report, closing.

**Comment by jackpoz** [comment] 2017-03-11 12:57
> it should be fixed!

**Comment by jackpoz** [comment] 2017-03-11 13:24
hash 8f2bcd79da39
crash reproduced (assertion triggered) https://gist.github.com/jackpoz/6b04d908bff7c93119cd31ac71086a23

**Comment by sirikfoll** [comment] 2017-11-05 04:16
Not sure if this should really be changed, the assertion is there to ensure the correct amount of npcs, because that number is used later to access the waypoints vector.
It is @Shauren's code, what would you like to be done?

**Comment by jackpoz** [comment] 2017-11-06 20:58
change the assert to a sanity check, asserts are not supposed to be triggered depending on the db data (especially spawns that can be modified as simple as executing an ingame command)

**Comment by jackpoz** [comment] 2018-05-05 17:47
https://github.com/TrinityCore/TrinityCore/commit/953640d56369abd979d194b83df90b20f50b2720 fixes this

**Closed by jackpoz** 2018-05-05 17:47 UTC
Labels: Branch-3.3.5a, Comp-C++Script, HasBacktrace, Sub-Instances, Sub-Spawns
