### ISSUE TITLE
[335] [DB] Missing update - King Jotum Vehicule

### ISSUE THREAD

**Issue by danlapps** [TrinityCore/TrinityCore#14301] opened 2015-03-07 00:01 UTC
runtime error Script named 'npc_king_jokkum_vehicle' does not have a script name assigned in database.

Fix :present in some old file, seems to have been left out of new base file.
```SQL
UPDATE `creature_template` SET `ScriptName`="npc_king_jokkum_vehicle" WHERE `entry`=30331;
```

**Comment by Aokromes** [comment] 2015-03-07 00:02
Nope, c++ needs to be removed. also duplicate of #13707

**Closed by Aokromes** 2015-03-07 00:02 UTC
