### ISSUE TITLE
[3.3.5] DB/Quest: Where in the World is Hemet Nesingwary? (12521)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15989] opened 2015-12-12 10:14 UTC
Branch 3.3.5, revision 01beba21b5210860ddd6a37471c6b2bea77a369e

Quest [Where in the World is Hemet Nesingwary](http://www.wowhead.com/quest=12521/where-in-the-world-is-hemet-nesingwary)

The [Archmage Penturus' Flying Machine](http://www.wowhead.com/npc=28192/archmage-pentarus-flying-machine) that you enter on the Sholazar Basin side of the portal is incredibly, incredibly slow. It takes over 10 minutes to get to the quest waypoint.

**Comment by Killyana** [comment] 2015-12-12 14:38
The problem is: sometimes the teleportation of the vehicle fails, in this case the waypoint starts from Dalaran to Sholazar, even if you're seeing the flying machine in Sholazar it's not the real position, if the speed it too slow look to the map to see the real position of the flying machine.

**Comment by Treeston** [comment] 2016-02-12 01:27
Still an issue on 8e6fb3b1c50f

Oh, and you don't get a parachute at the end, meaning you die. Horribly.

**Comment by genion18** [comment] 2019-08-06 20:35
Hy,

Very Horribly, the Flights end here and when logout/login is the Charakter at the Air in Dalaran to the death flight at the ground.

greets

**Comment by genion18** [comment] 2019-08-06 20:37
Hy,

Very Horribly, the Flights end here and when logout/login is the Charakter at the Air in Dalaran to the death flight at the ground.

greets

**Comment by genion18** [comment] 2019-08-06 20:38
Hy,

Very Horribly, the Flights end here and when logout/login is the Charakter at the Air in Dalaran to the death flight at the ground.

greets

![WoWScrnShot_080619_222346](https://user-images.githubusercontent.com/321832/62575365-dfc1b880-b89a-11e9-9b1b-cab6675b0a8b.jpg)

**Comment by Duratans** [comment] 2019-08-21 22:37
confirm, sometimes you end up completely in a weird location flying in the abyss.,

**Comment by jackpoz** [comment] 2019-12-21 15:29
Fixed by https://github.com/TrinityCore/TrinityCore/commit/afbc47891965f9c31c4b31c66931a2dbc9846f93

**Closed by jackpoz** 2019-12-21 15:29 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Vehicles
