### ISSUE TITLE
Objects pooling system taking over 5 minutes to load

### ISSUE THREAD

**Issue by obsidean** [TrinityCore/TrinityCore#23715] opened 2019-08-14 13:08 UTC
**Description:**

The objects pooling system takes over 5 minutes to finish loading.  Why?  Maybe if someone could tell me what database table(s) are affected I could have a look.  Could it be an indexing issue?

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce the problem:**

1. Startup auth server then startup world server.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

95284b23d1e4 

Mac OS X 10.14.5 Mojave

**Comment by jackpoz** [comment] 2019-08-14 14:31
could you provide the Server.log that worldserver creates ?

**Comment by jackpoz** [comment] 2019-08-14 14:34
This is what I get:
World initialized in 1 minutes 33 seconds
TrinityCore rev. af874a211c0f 2019-08-12 22:30:28 -0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...

**Comment by Killyana** [comment] 2019-08-14 14:54
It's was introduced by dynamic spawns, also if you cache queries it will load faster next time you start the server.

**Comment by obsidean** [comment] 2019-08-14 15:11
World initialized in 11 minutes 54 seconds
TrinityCore rev. 95284b23d1e4 2019-08-13 08:55:00 -0300 (3.3.5 branch) (MacOSX, RelWithDebInfo, Static) (worldserver-daemon) ready...

**Comment by Ovahlord** [comment] 2019-08-14 18:34
disable the pre-caching option in the worldserver config.

Calculate.Creature.Zone.Area.Data = 0
Calculate.Gameoject.Zone.Area.Data = 0

Pretty sure you have them active

**Comment by illfated** [comment] 2019-08-14 20:32
Ah. Good point. I get the same result as jackpoz, mostly less than 2 minutes.
Then again, `[server.loading] Starting objects pooling system...`
usually takes more than a minute to complete with default settings.
I often wish there could be some kind of "progress indicator" when that line appears.

**Comment by obsidean** [comment] 2019-08-15 14:00
those settings are already set to 0.  One thing I do remember noticing is that when I upload a fresh world database, the server runs fine.  It seems to get progressively slower the more I play.  That's why I was wondering if there could be an indexing problem.  But, you said you don't have this issue.  Maybe I'll just have to live with it.  It's not the end of the world I suppose

**Comment by Ovahlord** [comment] 2019-08-15 17:04
I can tell you one thing for sure: the pooling itself is not the cause of the problem. You might try a new startup with a empty respawn time database. Because right now active respawn times causes the core to create grids on startup because someone decided that calling GetZoneId during startup is a great idea so the more different locations are affected by respawns the more grids are getting created.

**Comment by illfated** [comment] 2019-08-15 17:34
Thank you for the insight. Practical knowledge.

**Comment by Killyana** [comment] 2019-08-17 21:01
Fixed by https://github.com/TrinityCore/TrinityCore/commit/3a4216fd979eb2a7667b0861a770e9af4f242eab

**Closed by Killyana** 2019-08-17 21:01 UTC
Labels: Branch-3.3.5a

**Comment by misch14** [comment] 2023-07-20 19:39
How did he fixed this @Killyana
