### ISSUE TITLE
Fresh install of master branch on Ubuntu 16.04 fails at 29%

### ISSUE THREAD

**Issue by dipdill** [TrinityCore/TrinityCore#19453] opened 2017-04-13 01:35 UTC
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**  

When doing a fresh install of the master branch on Ubuntu 16.04 it fails at 29% on the make command.

**Current behaviour:**

When doing the make after the cmake command it errors here:

```
[ 29%] Building CXX object src/server/game/CMakeFiles/game.dir/Spells/SpellMgr.cpp.o
/wowserver/TrinityCore/src/server/game/Spells/SpellMgr.cpp: In member function ‘void SpellMgr::LoadSpellInfoCorrections()’:
/wowserver/TrinityCore/src/server/game/Spells/SpellMgr.cpp:2927:24: error: ‘class SpellInfo’ has no member named ‘ActiveIconID’
         if (spellInfo->ActiveIconID == 2158)  // flight
                        ^
compilation terminated due to -Wfatal-errors.
src/server/game/CMakeFiles/game.dir/build.make:1142: recipe for target 'src/server/game/CMakeFiles/game.dir/Spells/SpellMgr.cpp.o' failed
make[2]: *** [src/server/game/CMakeFiles/game.dir/Spells/SpellMgr.cpp.o] Error 1
CMakeFiles/Makefile2:1688: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```
**Expected behaviour:**

Should make it to 100% and complete the make as expected.

**Steps to reproduce the problem:**

```
cd TrinityCore
rm -rf build
mkdir build
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=/wowserver -DWITH_WARNINGS=1
make
```

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore revision   : 3c2843551158 2017-04-12 00:11:54 +0200 (master branch)

**TDB version:**  N/A

**Operating system:** Ubuntu 16.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Lordron** [comment] 2017-04-13 02:15
according to @Shauren master branch isn't ready yet, lots of works has to be done to make in work at 7.2

**Comment by Shauren** [comment] 2017-04-13 06:44
Duplicate of #19426 anyway

**Closed by Shauren** 2017-04-13 06:44 UTC
