### ISSUE TITLE
Sometimes it is impossible to complete the quest

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26237] opened 2021-03-13 18:34 UTC
Sometimes it is impossible to complete the quest, it does not apply to a specific quest or level.
You will not be able to complete the quest (**the complete button is inactive**), however, I noticed that this often does not work with quests where it is required (according to the purpose of the task) some items.

But, if you restart the server, then everything will work out.

I thought the problem was in the client cache, but I cleaned it and still the problem remained
(the problem is not in the client cache, it looks like)
I managed to complete this task from another account.

3.3.5
rev. 0dee695

**Comment by Jinnaix** [comment] 2021-03-13 18:40
While i know what you are talking about (i have encountered this myself in the past) its impossible to dig into this without clear steps to reproduce it. No one will randomly quest around for this, takes too much time.
And yes, it appears to only affect quests where you have to turn in items.

Sidenote: Try to keep your core somewhat more up to date, you are nearly 1,5 months behind :)

**Comment by illfated** [comment] 2021-03-13 18:50
Also: Many of those quest issues can be caused by either incorrect quest chaining or already completed follow-up quests.
You have to report each quest issue individually, posting all the quest details and related links to make it a useful issue ticket.

Please use the full issue ticket template next time. You disrespect TrinityCore and its contributors when you remove template details.

**Comment by gygyti** [comment] 2021-03-13 18:51
I don't even know how to reproduce it, it happens by accident. If we know that this is related to the items in the quest, then I think this can help in solving the problem 

_I try to update the core once a month)_

**Comment by offl** [comment] 2021-03-13 18:52
Duplicate of #25331

**Closed by offl** 2021-03-13 18:52 UTC
Labels: Branch-3.3.5a
