### ISSUE TITLE
Core/Spells: Frostbolt bug

### ISSUE THREAD

**Issue by A2dikted** [TrinityCore/TrinityCore#23031] opened 2019-02-07 21:07 UTC
**Description:**
Frostbolt spell is bug.

**Current behaviour:**
Problem is Frostbolt snares (reduces target movement speed) but when targets it's re-affected by Frostbolt, it gains normal movement speed for 100ms then snared again.
**LINK TO VIDEO - GOOGLE DRIVE:**
https://drive.google.com/file/d/16F77vzNwVv9ZYVnsBaJeW72ILGrMauTi/view?usp=sharing

**Expected behaviour:**
How should this work? Frostbolt > snares target / reduced movement speed > Re cast-Frostbolt > snare resets duration, target keeps reduced movement speed.

**Steps to reproduce the problem:**
1. Cast Frostbolt (from Mage or whatever frostbolt it is) on a target
2. Target gets snared, reduced movement speed.
3. Re-Cast Frostbolt
4. Target gets normal movement speed for 100ms or something, then reduced movement speed.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. b1604ba0cd6d+

**Operating system:**
Windows OS

**Comment by Killyana** [comment] 2019-02-08 06:22
Probably the same issue as https://github.com/TrinityCore/TrinityCore/issues/22999

**Comment by illfated** [comment] 2019-02-08 13:02
At least closely related, as far as aura remove/reapply goes:
> [...] this cause the aura to be removed an reapplied [...]

True, it looks like TC core often removes auras when auras should only be reapplied.
Thanks for pointing to the similar issue.

**Comment by A2dikted** [comment] 2019-02-17 01:11
Hey guys, I need help!
I been 3 hours trying to find the damn code where to edit the green number in Attack Power:
https://i.imgur.com/0xEA6tM.jpg
(It's set to int16 and want to set it to int32, because max value (green) is 32767 and want to set it max to 2.476..... whatever int32 max is)
I know this is irrelevant to the post, and did not want to make an "Issue" Thread because this is not an issue.
I hope you guys can help me please.
Thanks.

**Comment by ratkosrb** [comment] 2019-02-17 04:10
> I been 3 hours trying to find the damn code where to edit the green number in Attack Power:

I assume this is send in the update object packet, so it is an update field, which means if you change the size server side it will bug out the client (second half of that int32 will be interpreted to be the next field and every value after will be read wrong). I am just guessing though.

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Object/Updates/UpdateFields.h#L163

**Comment by A2dikted** [comment] 2019-02-17 04:56
Hey ratkosrb thanks you a lot for your reply.
After 6 hours of searching into Core I found what I need to edit is UNIT_FIELD_ATTACK_POWER_MODS and Ranged AP.
Is theres any way to edit this? I get that point about wrong read data but I need to fix this!
Again, thanks a lot for your comment

**Comment by ratkosrb** [comment] 2019-02-17 16:41
I don't think you can change the size of the field because it would bug out the game as I explained. The client expects every field to be a certain size, and if it doesn't match, it would cause all fields after it to be read wrong.

**Comment by A2dikted** [comment] 2019-02-17 16:58
So I would need to edit the client lets say with ollydbg?
Sorry, I get your point because I understand this. But I mean, then it is impossible to edit that size?

**Comment by Killyana** [comment] 2019-03-08 14:43
Cannot reproduce on rev. ec3cb05d7fbc

**Closed by Killyana** 2019-03-08 14:43 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Spells

**Comment by Laintime** [comment] 2020-02-08 19:29
Confirm on https://github.com/TrinityCore/TrinityCore/commit/5fa77744e4495a77dea734330d5ae9e113b8a7f1 
@Killyana reopen pls.
How to
1 - Create paladin and use https://wotlkdb.com/?spell=1044
2 - Create mage and caste frost bolt
3 - Hand of Freedom done, Frostbolt effect no decrease movement speed.
This bag on all Effect decrease movement speed.
