### ISSUE TITLE
[Master] Quest: Death Comes from on High (12641)/ Spell: Eye of Acherus (51852)

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18362] opened 2016-11-30 18:15 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
In the quest, death comes from on high, the deathknight controls the eye of acherus to survey the human town below.
**Current behaviour:** (Tell us what happens.)
Player is able to control and launch the eye of acherus, but once controlled, the eye of acherus lacks any of the spells necessary to complete the quest.
http://imgur.com/a/Zf581
**Expected behaviour:** (Tell us what should happen instead.)
The player is able to use the eye of acherus spells to complete the quest
**Steps to reproduce the problem:**

1.  Play DK
2.  Complete intro quest chain up until this point
3.  Begin quest and use eye of acherus.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master
**TC rev. hash/commit:**  
9b006e511bf40020e1660adf290ceb6ed6f4fd86
**TDB version:**  
703.00
**Operating system:**  
Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Arles91** [comment] 2016-12-15 17:51
Tested quests:
1. In Service Of The Lich King -> OK
2. The Emblazoned Runeblade -> OK
3. Runeforging: Preparation For Battle -> Autocomplete
4. The Endless Hunger -> OK
5. The Eye Of Acherus -> OK
6. Death Comes From On High -> BUG (the eye hasn't required spells)
7. The Might Of The Scourge -> OK
8. Report To Scourge Commander Thalanor -> OK
9. The Scarlet Harvest -> OK
10. If Chaos Drives, Let Suffering Hold The Reins -> OK, but the phases are overlapping.

We can't level up because the Hearthglen's npcs interfere between different phases...

**Comment by nubqt** [comment] 2017-11-12 17:43
Confirmed: (i) vehicle still does not show controls for the Eye of Acherus, (ii) Avalon is empty on NPCs. See screenshot attached, and thus (iii) quest cannot be completed.

This issue should be marked as Critical since the quest is required to progress further in the Death Knight storyline. If the quest is not completed, the character won't be able to get out of the DK starting area.

<img width="1378" alt="screen shot 2017-11-12 at 12 37 50 pm" src="https://user-images.githubusercontent.com/33535711/32701604-cf656644-c7a6-11e7-8b31-436dc250a3b8.png">

**Comment by Killyana** [comment] 2017-11-24 16:25
This issue is  fixed, just cherry picks from 3.3.5 are required: spawns (DK DB/Misc: Death knights area rework) + remove phase hack https://github.com/TrinityCore/TrinityCore/commit/f3a00a1822bfbdf0a14eaf3afc503e034d9d56c6

**Comment by Killyana** [comment] 2018-03-26 10:01
The remaining issue here is spells from DB are not loaded on the spell bar, probably a generic issue for charmed unit.

**Closed** 2018-06-11 18:25 UTC
Labels: Branch-master, Comp-C++Script, Sub-Quests, Sub-Spells
