### ISSUE TITLE
[Crash] Player::UnbindInstance

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#15515] opened 2015-09-14 21:36 UTC
Yesterday I had this crash. It was when the server weekly instance reset.

http://pastebin.com/RSYyUZJh

da612f2041b15bb6f19cee01bd201d63e304d4dc

3.3.5

**Comment by jackpoz** [comment] 2015-09-17 13:48
Duplicate of https://github.com/TrinityCore/TrinityCore/issues/14983 .
Thank you for the crash report, it has been linked to the main issue already on GitHub. Feel free to keep posting any other crash report of same type here or on the other open issue.

**Closed by jackpoz** 2015-09-17 13:48 UTC
Labels: Comp-Core, HasBacktrace
