### ISSUE TITLE
[3.3.5][Quest] Torch Tossing / Torch Tossing (Daily) - "Braziers Hit" never triggers.

### ISSUE THREAD

**Issue by funar** [TrinityCore/TrinityCore#22093] opened 2018-06-27 19:16 UTC
**Description:**
Torch Tossing / Torch Tossing (Daily)
( Reported previously as #17492 )

**Current behaviour:**
Quest is not completed after throwing 8 torches.  "Braziers hit" does not increment.  However, the "flame effect" on the brazier on a successful torch toss is getting triggered.

**Expected behaviour:**
The "Braziers Hit" count should increment, with the quest completing at 8 (normal), 40 (daily version)

**Steps to reproduce the problem:**
1. Pick up the quest Torch Tossing (http://www.wowhead.com/quest=11922/torch-tossing)
2. Toss 8 (40 for daily quest) torches at the braziers, witness flame effect, but no increment of the quest requirement of "Braziers Hit."

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 16f524ff2537 2018-06-26 20:17:59 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.62.0
Using MySQL version: 10.1.30-MariaDB
Using CMake version: 3.9.1
Compiled on: Linux 4.13.0-41-generic
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /opt/trinity/server/data/maps. Total size: 252191207 bytes
vmaps directory located in /opt/trinity/server/data/vmaps. Total size: 588247501 bytes
mmaps directory located in /opt/trinity/server/data/mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:**
Ubuntu Linux 17.10

**Comment by Kobiesan** [comment] 2018-06-28 03:09
I can confirm this is how it's happening for me as well.

**Comment by illfated** [comment] 2018-06-28 17:33
@Kobiesan : thank you for confirming, but it would be a lot more useful if you could add your TC core revision hash to your comment for future tracking of this issue.

**Comment by truliaswotlk** [comment] 2018-07-02 08:56
35ba5aa138ed+ is this the hash? I am having same issue and thats the latest revision compiled in June. No releases after Feb.

**Comment by illfated** [comment] 2018-07-02 19:55
@truliaswotlk : correct,  35ba5aa+ is your TC rev. hash/commit.
Notice the **+** sign after your hash, it means you have added minor changes to it.

**Comment by soniczhang11** [comment] 2019-06-24 12:32
same in 3c77c04b052f721efb96bdaaceeca8de09926f12

**Comment by illfated** [comment] 2019-06-24 16:35
Is this a problem with spell hit in combination with gameobjects, maybe incorrect targets?

**Comment by ipriver** [comment] 2020-06-22 16:38
Did someone fix it and forget to close the issue or did people use some custom patches that broke the quest? Haven't found any commits that modified it since 2016.

Works in dc41aae0427f with fresh DB
https://imgur.com/a/NnZEcRL

**Comment by offl** [comment] 2020-06-22 16:46
Idk if all similar quests works, I tried once and only the first quest worked for me
Maybe some quest givers scripts are complete and some are not, idk, didn't checked yet
I tried in Exodar

**Comment by ipriver** [comment] 2020-06-22 17:04
That would be weird if there are different scripts (copy-paste) for different capital zones.
There are only 2 NPC quest givers: [alliance](https://www.wowhead.com/npc=25975/master-fire-eater) and [horde](https://www.wowhead.com/npc=26113/master-flame-eater).
@offl, after your comment I manually checked every quest in every capital and every quest worked to me :)

**Comment by offl** [comment] 2020-06-22 17:15
Maybe Torch Catching was broken to me

**Comment by ipriver** [comment] 2020-06-22 17:20
yep, "Torch Catching" doesn't work for me either, but this ticket is only about "Torch Tossing" quest.

**Comment by illfated** [comment] 2020-06-22 18:00
https://www.wowhead.com/quest=11922/torch-tossing and https://www.wowhead.com/quest=11926/more-torch-tossing worked fine for me too in Orgrimmar, on the tcubuntu.northeurope.cloudapp.azure.com server (https://tcubuntu.northeurope.cloudapp.azure.com/) :

[19:43:33] TrinityCore rev. a9f9f737b2c9 2020-06-22 09:53:10 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
```
[19:43:35] Joined Channel: [1. General - Shadowmoon Valley]
[19:43:35] Joined Channel: [3. LocalDefense - Shadowmoon Valley]
[19:45:14] Changed Channel: [1. General - Orgrimmar]
[19:45:14] Joined Channel: [2. Trade - City]
[19:45:14] Changed Channel: [3. LocalDefense - Orgrimmar]
[19:45:14] Joined Channel: [4. GuildRecruitment - City]
[19:45:14] Joined Channel: [5. LookingForGroup]
[19:45:36] Quest accepted: The Spinner of Summer Tales
[19:46:36] The Spinner of Summer Tales completed.
[19:46:36] Received item: [Burning Blossom].
[19:47:06] You receive item: [Summer Incense].
[19:47:06] Quest accepted: Incense for the Festival Scorchlings
[19:47:33] You receive item: [Practice Torches].
[19:47:33] Quest accepted: Torch Tossing
[19:48:18] Torch Tossing failed.
[19:48:37] You receive item: [Practice Torches].
[19:48:37] Quest accepted: Torch Tossing
[19:48:56] CARBONITE Quest Complete 'Torch Tossing'
[19:49:06] You gain 25894 experience.
[19:49:06] Torch Tossing completed.
[19:49:06] Experience gained: 25894.
[19:49:06] Received 7 Gold, 40 Silver.
[19:49:06] Received 5 of item: [Burning Blossom].
[19:49:21] Quest accepted: More Torch Tossing
[19:50:10] CARBONITE Quest Complete 'More Torch Tossing'
[19:50:21] You gain 25894 experience.
[19:50:21] [Zogzog] has earned the achievement [50 Daily Quests Complete]!
[19:50:21] More Torch Tossing completed.
[19:50:21] Experience gained: 25894.
[19:50:21] Received 4 Silver.
[19:50:21] Received 5 of item: [Burning Blossom].
[19:50:21] You can only complete 24 more daily quests today.
[19:50:39] 19:50:39 Midsummer Celebrant says: The Horde fires will never be extinguished!
```
Maybe time to close this ticket and open a new one for "Torch Catching"?
- https://www.wowhead.com/quest=11657/torch-catching (Alliance)
- https://www.wowhead.com/quest=11923/torch-catching (Horde)

Yes, I know, it would be nice to be able to tell which commit fixed this issue. Feel free to dig down in the commit history and see if you can find it.

**Comment by Aokromes** [comment] 2020-06-22 18:06
https://github.com/TrinityCore/TrinityCore/issues/17446

**Closed** 2020-06-22 18:05 UTC
Labels: Branch-3.3.5a, Comp-C++Script, Sub-Quests, Sub-Spells
