### ISSUE TITLE
[Master Branch] Problem to complete a quest with kills of creatures

### ISSUE THREAD

**Issue by XEQT** [TrinityCore/TrinityCore#26824] opened 2021-08-15 20:24 UTC
### Description

In latest Core therer is a bug that makes people that take a quest or more to not be able to complete them even after you have relogedin.

### Expected behaviour

Relogin and be able to kill the creatures for the quests that you have in list and just finish them.

### Steps to reproduce the problem

Step 1.
Take Quest
Step 2.
Logout
Step 3.
login again with the same character then kill any creature that you have in the total list of quests and it dosent add a +1 on counter for any of the quests.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. fb6761c273d5 2021-08-15 11:09:46 +0200 (master branch) (Unix, Release, Static)

### Operating system

Debian 10 x64

### Custom changes

None

**Comment by offl** [comment] 2021-08-15 20:49
Duplicate of #26823

**Closed by offl** 2021-08-15 20:49 UTC
Labels: Branch-master
