### ISSUE TITLE
Quest: Sabotage

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20881] opened 2017-11-15 06:39 UTC
**Description:**
http://www.wowhead.com/quest=12676/sabotage

This quest requires the completion of Disclosure (#20882) as quest criteria.

**Current behaviour:**
Using the [Explosive Charges](http://www.wowhead.com/item=39165/explosive-charges) near a Scourgewagon places the charges and blows up the wagon but does not give credit toward the quest.

**Expected behaviour:**
Using the [Explosive Charges](http://www.wowhead.com/item=39165/explosive-charges) near a Scourgewagon should give credit toward the quest.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 30c2a96f16ef

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by Killyana** [comment] 2017-11-15 08:54
The sai was working correctly, the credit is given by the spell: 52346 casted by the npc trigger summoned by http://www.wowhead.com/spell=52315/place-charges
I don't know what caused  the issue.
``` sql
2878000, 9, 6, 0, 0, 0, 100, 0, 0, 0, 0, 0, 11, 52346, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, Explosive Charges Bunny - On Script - Cast 'Kill Credit'

**Comment by jerbookins** [comment] 2017-11-16 09:25
So you found a fix?

**Comment by offl** [comment] 2017-11-19 20:25
Anyway the order of events is too wrong. Maybe it is due to the order?
```sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=2878000 AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(2878000,9,0,0,0,0,100,0,0,0,0,0,11,52346,0,0,0,0,0,7,0,0,0,0,0,0,0,"Explosive Charges Bunny - On Script - Cast 'Kill Credit'"),
(2878000,9,1,0,0,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Explosive Charges Bunny - On Script - Say Line 0"),
(2878000,9,2,0,0,0,100,0,1000,1000,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Explosive Charges Bunny - On Script - Say Line 1"),
(2878000,9,3,0,0,0,100,0,1000,1000,0,0,1,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Explosive Charges Bunny - On Script - Say Line 2"),
(2878000,9,4,0,0,0,100,0,1000,1000,0,0,1,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Explosive Charges Bunny - On Script - Say Line 3"),
(2878000,9,5,0,0,0,100,0,1000,1000,0,0,1,4,0,0,0,0,0,1,0,0,0,0,0,0,0,"Explosive Charges Bunny - On Script - Say Line 4"),
(2878000,9,6,0,0,0,100,0,1000,1000,0,0,11,52322,0,0,0,0,0,1,0,0,0,0,0,0,0,"Explosive Charges Bunny - On Script - Cast 'Detonate Charges'");
```

**Comment by Killyana** [comment] 2017-11-19 21:17
The order is correct you can check a video, also it doesn't matter as the spell must just be casted, if you select any npc then .cast self 52346  you well get the credit, you can do it with this npc trigger when it spawns (with gm on) and also you will get the credit, so I think the spell is just not casted, or there's something wrong with credits as it's not the only quest in this case.

**Comment by offl** [comment] 2017-11-19 21:35
I checked in this video https://youtu.be/ndCNE4bNAZI?t=68

**Comment by Killyana** [comment] 2017-11-19 21:41
What's wrong with the order of actions?

**Comment by offl** [comment] 2017-11-19 21:51
According to videos you should receive the credit right after use the item(right after just summoned).

**Comment by Killyana** [comment] 2017-11-19 21:59
Ah, was thinking the linked SAI was the one from the DB, any way it doesn't really mater, the explosion from the spell happen but the spell credit doesn't work.
Also with your sai I didn't get the credit neither.

**Comment by offl** [comment] 2017-11-19 22:37
Maybe LOS is the cause?

**Comment by Keader** [comment] 2017-11-19 22:44
i dont think so @offl 
Spell has AttributesEx2: 0x00000004 (SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS)

**Comment by Killyana** [comment] 2017-11-19 23:04
No the same SAI is working in an older core.

**Comment by sirikfoll** [comment] 2017-11-20 06:24
Problm is `GetScript()->OnReset();` called twice, Invoker will be saved after the call, but on the second call, invoker will be cleared.
Calls come from `void SmartAI::InitializeAI()` and `void SmartAI::JustAppeared()`

**Comment by Killyana** [comment] 2017-11-20 13:44
Removing: GetScript()->OnReset();  fix the issue.
There's a similar issue https://github.com/TrinityCore/TrinityCore/issues/20102 but I don't get the credit using the same fix.

**Comment by offl** [comment] 2017-12-15 10:35
So one-row fix? Or it will break something else?

**Comment by Killyana** [comment] 2017-12-15 15:46
No it looks it's related to other issues, @ccrs will probably fix it with the movement generator issue.

**Comment by ccrs** [comment] 2017-12-15 16:03
https://github.com/TrinityCore/TrinityCore/commit/e10d7dd45cfc073c791cd5e5f3f964d14b37df3d#diff-703f1f16a955ae7ddc7caf673a75d85aR626

the behaviour is just the same

**Comment by Keader** [comment] 2017-12-16 02:33
if is the same, why is called twice now? o.O (https://github.com/TrinityCore/TrinityCore/issues/20881#issuecomment-345602686)

**Comment by sirikfoll** [comment] 2017-12-16 02:59
@Treeston  Could you take a look at this, please? :blush:

**Comment by Treeston** [comment] 2017-12-16 03:02
If there's a duplicate call, we can get rid of one of them. Any reasons why we'd prefer to keep a certain one? Intuitively it fits better in `JustAppeared` (since that behaves the same for compatibility creatures), but I'm not overly attached to either one.

**Comment by ccrs** [comment] 2017-12-16 13:40
its is not called twice NOW, the behaviour is the same as ALWAYS
open ur eyes and check the code, dont just assume something because one person tells it

**Comment by ccrs** [comment] 2017-12-16 13:43
> Calls come from void SmartAI::InitializeAI() and void SmartAI::JustAppeared()

This has been there since the creation of SAI, and we have discussed this for ages.
The solution is simple, remove the call on InitializeAI.
But, the job that NO ONE wants to do is to check all the affected scripts and see if they get fucked up.

End of this nonsense.

**Comment by ccrs** [comment] 2017-12-16 13:44
Like really, how simple is to point to someone and beg or blame to get a solution, move ur ass and try to figure out whats wrong -.-

**Comment by ccrs** [comment] 2017-12-16 13:49
And just because I'm already imagining whats comming up next,

https://github.com/TrinityCore/TrinityCore/commit/e10d7dd45cfc073c791cd5e5f3f964d14b37df3d#diff-703f1f16a955ae7ddc7caf673a75d85aR626
old version:
JustAppeared/JustRespawned -> JustReachedHome -> OnReset
new version:
JustAppeared -> OnReset

**Comment by Treeston** [comment] 2017-12-16 15:12
It's not the same, @ccrs. `JustRespawned` used to happen on _re_-spawn, while `InitializeAI` used to happen on _initial_ spawn.

Now both happen on each spawn, no matter if initial or re-. This was a behavior change in dynspawn since there is no difference between the two anymore.

**Comment by Shauren** [comment] 2018-01-26 23:05
reverted, reopening

**Comment by Killyana** [comment] 2018-02-12 15:38
This issue still happen on rev. e73bfe8df89
The invoker is cleared on:
SmartAI::JustAppeared()
GetScript()->OnReset();

**Closed** 2018-02-13 00:28 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Quests
