### ISSUE TITLE
[6.x][CRASH] WorldSession::QueuePacket

### ISSUE THREAD

**Issue by letor** [TrinityCore/TrinityCore#15892] opened 2015-11-24 08:35 UTC
Greetings!

This crash happens quite often 30-40 minutes into, and I'm attaching crash log below.
Crash log 1: http://pastebin.com/V8JMyU4W
Crash log 2: http://pastebin.com/g0B7cjQQ

Revision: fc852181c578e2ab8644bebfef13199a7897ebe9

**Comment by Maibenrai** [comment] 2015-11-24 09:23
https://www.trinitycore.info/display/tc/Requirements
Boost 1.59
and
https://community.trinitycore.org/topic/345-howto-properly-install-git-on-windows-fix-trinitycore-rev-1970-01-01-000000-0000/

**Comment by letor** [comment] 2015-11-24 15:09
I've updated to boost 1.5.9 and the crash still happens. 
New crash log: http://pastebin.com/wkDnNjp9

**Comment by tkrokli** [comment] 2015-11-24 15:22
Have you tried compiling it in Release instead of RelWithDebInfo ? According to what most TC devs say, RelWithDebInfo does not provide enough debug information for actually debugging an issue.

**Comment by jackpoz** [comment] 2015-11-24 20:59
can you fix the part
>Revision: TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, RelWithDebInfo)

of your crashlog ? The link posted above should explain how to do it.

Since it happens this often, please try building in Debug and post a crash log with that mode

**Comment by Shauren** [comment] 2015-11-24 21:34
This is the same old deleted session crash reported long time ago only happenin on 6.x branch

**Comment by et65** [comment] 2015-12-06 19:52
Same thing for me. It happens every 30-40 minutes like letor

http://pastebin.com/bA6HxGG8

**Comment by letor** [comment] 2015-12-27 21:57
This crash is happening still and very often
Yet another crash log: http://pastebin.com/qAZ0z8Aj
Pleasee fix those -boost- errors.

**Comment by letor** [comment] 2015-12-27 21:58
^ Latest crashlog was tested on newest boost 1.6.0, although crash still happens

**Comment by Shauren** [comment] 2015-12-29 20:22
Recheck after 6ace6aabbff91ebc487f43276d5b1861968c59db

**Comment by letor** [comment] 2015-12-30 13:59
Will report back whether the 6ace6aa fix worked after 24 hours of testing.

**Comment by letor** [comment] 2015-12-30 16:15
Crash still happening even after 6ace6aa. Same crash log like before.
http://pastebin.com/2dh6gFf1

**Comment by Sar777** [comment] 2016-01-15 14:53
related https://gist.github.com/Sar777/81315c213b4d39bb7914?

**Comment by streetrat** [comment] 2016-01-22 20:47
still randomly crashing in WorldSession::QueuePacket

**Comment by streetrat** [comment] 2016-01-29 10:57
why does a deleted session want to queue any packets?

**Comment by Shauren** [comment] 2016-01-29 12:48
Wrong question. Why and HOW is the session deleted in the first place (if thats the case and not some other memory corruption)

**Comment by letor** [comment] 2016-02-25 17:52
Still happening on the e40371909cd7e8c5ce29b96e46161bc88bf75b2c

A hint: happened when i went afk for a while and got disconnected, logged back in and it crashed while entering the world. So maybe old sessions (the ones that got disconnected after afking)  somehow crash it when you try to log back into world.

**Comment by n4ndo** [comment] 2016-03-15 05:21
Any news?

**Comment by letor** [comment] 2016-03-15 15:33
nope, looks like nobody knows why its crashing

**Comment by Palabola** [comment] 2016-04-06 19:19
Same problem here:

http://pastebin.com/g3VECe98

**Comment by Palabola** [comment] 2016-04-24 16:05
Crash point at:

WorldSocket::HandleAuthSession: Sent Auth Response (unknown account).

http://pastebin.com/nF1t83Lj

**Comment by Sar777** [comment] 2016-04-24 16:13
no, next find =\

**Comment by letor** [comment] 2016-05-05 19:55
This issue has been ongoing for 6 months. TrinityCore please gather the forces and fix this, this is literally the only crash on 6.x branch and it's happening so often. So many people reporting the same crash.

**Comment by Aokromes** [comment] 2016-05-05 20:17
Get a way to 100% reproduce the crash, then maybe it will be fixed.

**Comment by et65** [comment] 2016-05-10 05:50
Problem solved ;).
Thanks @Shauren

**Closed** 2016-05-10 06:03 UTC
Labels: Branch-6.x, Comp-Core, HasBacktrace

**Comment by letor** [comment] 2016-05-10 08:08
Shauren 1 : Aokromes 0 hahahaha
