### ISSUE TITLE
Quest - Army of the Damned (13236, 13395)

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#28004] opened 2022-06-05 09:18 UTC
### Description

Army of the Damned

Horde
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=13236
Alliance
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=13395

In this quest, the Player turns into Arthas Menethil, and the phase also changes (after talking with Matthias Netler), allowing the player to see how Arthas killed his own soldiers.
However, Arthas can't auto-attack against soldiers, and his ability SpellID 58913 doesn't work either.

Since I have no friends, I tweaked the server settings:

<details>

Rate.Creature.Normal.Damage          = 0.4
Rate.Creature.Elite.Elite.Damage     = 0.1
Rate.Creature.Elite.RARE.Damage      = 0.5
Rate.Creature.Elite.RAREELITE.Damage = 0.2
Rate.Creature.Elite.WORLDBOSS.Damage = 0.025

Rate.Creature.Normal.SpellDamage          = 0.8
Rate.Creature.Elite.Elite.SpellDamage     = 0.2
Rate.Creature.Elite.RARE.SpellDamage      = 0.7
Rate.Creature.Elite.RAREELITE.SpellDamage = 0.5
Rate.Creature.Elite.WORLDBOSS.SpellDamage = 0.015

Rate.Creature.Normal.HP          = 1
Rate.Creature.Elite.Elite.HP     = 0.7
Rate.Creature.Elite.RARE.HP      = 1
Rate.Creature.Elite.RAREELITE.HP = 1
Rate.Creature.Elite.WORLDBOSS.HP = 0.1

</details>

Because of these changes, the soldiers have 12600 health, and Arthas' first ability (SpellID 58912) deals 5000 damage to several soldiers at the same time spent more than half of the mana (there will not be enough mana for the second use of the ability, and it itself is restored very slowly). Naturally there is a desire to replenish mana with the second ability (SpellID 58913), but it does not work with the message: "No target" (Of course, I tried to approach the soldier within melee range, looked at him and tried to use the ability.). Then there is a desire to kill the soldiers with an auto attack, but for some reason it also does not work.

### Expected behaviour

In [this](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=13236) and [this](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=13395) quest, Arthas should have auto-attack and ability SpellID 58913 working.

### Steps to reproduce the problem

1. Start one of these quests for your faction:

Horde
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=13236
Alliance
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=13395
2. Talk to [Matthias Lehner](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=32404) to change phase;
3. Attack the soldiers with SpellID 58912 and make sure that this ability uses up more than half of the mana (there will not be enough mana for the second use of the ability, and it itself is restored very slowly);
4. Try auto-attacking soldiers and make sure it doesn't work;
5. Try restoring mana with SpellID 58913, and see if it doesn't work either.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/38dc5667ba13d5c1d094330b0f57ba0ee9b2dde5
TrinityCore rev. 2022-05-29 ‏‎‏‎‏‎‏‎10:00:15 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

See above.

**Comment by Jinnaix** [comment] 2022-06-05 09:27
Duplicate of https://github.com/TrinityCore/TrinityCore/issues/17205

Seems to be a faction related issue.

**Closed** 2022-06-05 10:43 UTC
Labels: Branch-3.3.5a
