### ISSUE TITLE
[Freeze] - npc_air_force_bots

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#18535] opened 2016-12-20 10:24 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Freeze with npc_air_force_bots here:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/World/npcs_special.cpp#L214

**Crashlog:** https://gist.github.com/Jildor/a457f4ebc36a9f90bca8540478ae3160

**Steps to reproduce the problem:**

1. Go to NPC with script npc_air_force_bots (player Opposite faction)
2. Remove aura SPELL_GUARDS_MARK (38067) with command .unaura all or force core to remove (join arena for remove auras)
3. Freeze completed

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/c809c220e29f7094121cc8489f5588d8bfee414d

**TDB version:**  TDB335.62

**Operating system:**  Debian

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jackpoz** [comment] 2019-04-27 12:13
do you have a .go xyz coordinates to reproduce the issue ?

**Comment by illfated** [comment] 2019-04-27 12:44
Judging by the occurrence of entries/names in this query, I think any alliance/horde town in Outland will do, as long as you go near the opposite faction town (level 70 NPCs):
```sql
SELECT * FROM `creature_template` WHERE `ScriptName`='npc_air_force_bots';
```
```
entry  modelid1  modelid2  name                                                       minlevel  maxlevel     exp  faction  speed_walk  speed_run   scale  BaseAttackTime  RangeAttackTime  BaseVariance  RangeVariance  unit_class  unit_flags  unit_flags2    type  AIName  MovementType  HoverHeight  HealthModifier  ManaModifier  ArmorModifier  DamageModifier  ExperienceModifier  RegenHealth  flags_extra  ScriptName          VerifiedBuild
-----  --------  --------  ---------------------------------------------------------  --------  --------  ------  -------  ----------  ---------  ------  --------------  ---------------  ------------  -------------  ----------  ----------  -----------  ------  ------  ------------  -----------  --------------  ------------  -------------  --------------  ------------------  -----------  -----------  ------------------  -------------
 2614      7288     11686  Air Force Alarm Bot (Alliance)                                   70        70       1       11           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
 2615     19013     11686  Air Force Alarm Bot (Horde)                                      70        70       1      125           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
21974     20417     11686  Air Force Alarm Bot (Area 52)                                    70        70       1     1806           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
21993     20698     11686  Air Force Guard Post (Horde - Bat Rider)                         70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
21996     20698     11686  Air Force Guard Post (Alliance - Gryphon)                        70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
21997     20698     11686  Air Force Guard Post (Goblin - Area 52 - Zeppelin)               70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
21999     20691     11686  Air Force Trip Wire - Rooftop (Alliance)                         70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33555200         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22001     20688     11686  Air Force Trip Wire - Rooftop (Horde)                            70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33555200         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22002     20689     11686  Air Force Trip Wire - Ground (Horde)                             70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33555200         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22003     20690     11686  Air Force Trip Wire - Ground (Alliance)                          70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33555200         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22063     20688     11686  Air Force Trip Wire - Rooftop (Goblin - Area 52)                 70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33555200         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22065     20698     11686  Air Force Guard Post (Ethereal - Stormspire)                     70        70       1      190       1.125    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22066     20698     11686  Air Force Guard Post (Scryer - Dragonhawk)                       70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22068     20688     11686  Air Force Trip Wire - Rooftop (Ethereal - Stormspire)            70        70       1      190       1.125    1.14286       1            2000             2000             1              1           1    33555200         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22069     20417     11686  Air Force Alarm Bot (Stormspire)                                 70        70       1     1806       1.125    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22070     20688     11686  Air Force Trip Wire - Rooftop (Scryer)                           70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33555200         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22071     20417     11686  Air Force Alarm Bot (Scryer)                                     70        70       1     1806           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22078     20417     20577  Air Force Alarm Bot (Aldor)                                      70        70       1     1776       1.125    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22079     20698     11686  Air Force Guard Post (Aldor - Gryphon)                           70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22080     20688     11686  Air Force Trip Wire - Rooftop (Aldor)                            70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33555200         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22086     20417     11686  Air Force Alarm Bot (Sporeggar)                                  70        70       1     1837           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22087     20698     11686  Air Force Guard Post (Sporeggar - Sporebat)                      70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22088     20688     11686  Air Force Trip Wire - Rooftop (Sporeggar)                        70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33555200         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22090     20698     11686  Air Force Guard Post (Toshley's Station - Flying Machine)        70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22124     20417     11686  Air Force Alarm Bot (Cenarion)                                   70        70       1     1661           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22125     20698     11686  Air Force Guard Post (Cenarion - Stormcrow)                      70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33554432         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
22126     20688     11686  Air Force Trip Wire - Rooftop (Cenarion Expedition)              70        70       1      190           1    1.14286       1            2000             2000             1              1           1    33555200         2048      10                     1            1             1.1             1              1               1                   1            1          194  npc_air_force_bots          12340
```
(removed all columns containing **only** empty/NULL/zero values)

**Comment by jackpoz** [comment] 2019-04-27 13:30
This is caused by AuraEffect::HandleAuraModStalked() calling UpdateObjectVisibility() that calls MoveInLineOfSight that cast again the spell https://wotlk.evowow.com/spell=38067

callstack
>	worldserver.exe!WorldObject::CastSpell(WorldObject * target, unsigned int spellId, const CastSpellExtraArgs & args) Line 2779	C++
 	worldserver.exe!npc_air_force_bots::npc_air_force_botsAI::MoveInLineOfSight(Unit * who) Line 218	C++
 	worldserver.exe!CreatureAI::MoveInLineOfSight_Safe(Unit * who) Line 103	C++
 	worldserver.exe!CreatureUnitRelocationWorker(Creature * c, Unit * u) Line 138	C++
 	worldserver.exe!Trinity::AIRelocationNotifier::Visit(GridRefManager<Creature> & m) Line 249	C++
 	worldserver.exe!VisitorHelper<Trinity::AIRelocationNotifier,Creature>(Trinity::AIRelocationNotifier & v, ContainerMapList<Creature> & c) Line 46	C++
 	worldserver.exe!VisitorHelper<Trinity::AIRelocationNotifier,Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > >(Trinity::AIRelocationNotifier & v, ContainerMapList<TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > & c) Line 52	C++
 	worldserver.exe!VisitorHelper<Trinity::AIRelocationNotifier,GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > >(Trinity::AIRelocationNotifier & v, ContainerMapList<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > & c) Line 53	C++
 	worldserver.exe!VisitorHelper<Trinity::AIRelocationNotifier,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > >(Trinity::AIRelocationNotifier & v, TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > & c) Line 59	C++
 	worldserver.exe!TypeContainerVisitor<Trinity::AIRelocationNotifier,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > >::Visit(TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > & c) Line 93	C++
 	worldserver.exe!Grid<Player,TypeList<Player,TypeList<Creature,TypeList<Corpse,TypeList<DynamicObject,TypeNull> > > >,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > >::Visit<Trinity::AIRelocationNotifier>(TypeContainerVisitor<Trinity::AIRelocationNotifier,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > > & visitor) Line 92	C++
 	worldserver.exe!NGrid<8,Player,TypeList<Player,TypeList<Creature,TypeList<Corpse,TypeList<DynamicObject,TypeNull> > > >,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > >::VisitGrid<Trinity::AIRelocationNotifier,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > >(const unsigned int x, const unsigned int y, TypeContainerVisitor<Trinity::AIRelocationNotifier,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > > & visitor) Line 154	C++
 	worldserver.exe!Map::Visit<Trinity::AIRelocationNotifier,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > >(const Cell & cell, TypeContainerVisitor<Trinity::AIRelocationNotifier,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > > & visitor) Line 967	C++
 	worldserver.exe!Cell::Visit<Trinity::AIRelocationNotifier,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > >(const CoordPair<512> & standing_cell, TypeContainerVisitor<Trinity::AIRelocationNotifier,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > > & visitor, Map & map, float x_off, float y_off, float radius) Line 113	C++
 	worldserver.exe!Cell::Visit<Trinity::AIRelocationNotifier,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > >(const CoordPair<512> & standing_cell, TypeContainerVisitor<Trinity::AIRelocationNotifier,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > > & visitor, Map & map, const WorldObject & obj, float radius) Line 69	C++
 	worldserver.exe!Cell::VisitAllObjects<Trinity::AIRelocationNotifier>(const WorldObject * center_obj, Trinity::AIRelocationNotifier & visitor, float radius, bool dont_load) Line 217	C++
 	worldserver.exe!Unit::UpdateObjectVisibility(bool forced) Line 12024	C++
 	worldserver.exe!Player::UpdateObjectVisibility(bool forced) Line 22401	C++
 	worldserver.exe!AuraEffect::HandleAuraModStalked(const AuraApplication * aurApp, unsigned char mode, bool apply) Line 2505	C++
 	worldserver.exe!AuraEffect::HandleEffect(AuraApplication * aurApp, unsigned char mode, bool apply) Line 735	C++
 	worldserver.exe!AuraApplication::_HandleEffect(unsigned char effIndex, bool apply) Line 186	C++
 	worldserver.exe!Unit::_UnapplyAura(std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const ,AuraApplication *> > > > & i, AuraRemoveMode removeMode) Line 3445	C++
 	worldserver.exe!Unit::RemoveAllAuras() Line 4151	C++
 	worldserver.exe!misc_commandscript::HandleUnAuraCommand(ChatHandler * handler, const char * args) Line 343	C++
 	worldserver.exe!advstd::apply_impl<bool,ChatHandler *,char const *,0,1>(bool(*)(ChatHandler *, const char *) func, std::tuple<ChatHandler *,char const *> && args, std::integer_sequence<unsigned __int64,0,1> __formal) Line 36	C++
 	worldserver.exe!advstd::apply<bool,ChatHandler *,char const *>(bool(*)(ChatHandler *, const char *) func, std::tuple<ChatHandler *,char const *> && args) Line 41	C++
 	worldserver.exe!ChatCommand::{ctor}::__l2::<lambda>(void * handler, ChatHandler * chatHandler, const char * argsStr) Line 245	C++
 	worldserver.exe!bool <lambda>(void *, ChatHandler *, const char *)::<lambda_invoker_cdecl>(void * handler, ChatHandler * chatHandler, const char * argsStr) Line 249	C++
 	worldserver.exe!ChatCommand::operator()(ChatHandler * chatHandler, const char * args) Line 264	C++
 	worldserver.exe!ChatHandler::ExecuteCommandInTable(const std::vector<ChatCommand,std::allocator<ChatCommand> > & table, const char * text, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & fullcmd) Line 279	C++
 	worldserver.exe!ChatHandler::_ParseCommands(const char * text) Line 382	C++
 	worldserver.exe!ChatHandler::ParseCommands(const char * text) Line 413	C++
 	worldserver.exe!WorldSession::HandleMessagechatOpcode(WorldPacket & recvData) Line 238	C++
 	worldserver.exe!PacketHandler<WorldPacket,&WorldSession::HandleMessagechatOpcode>::Call(WorldSession * session, WorldPacket & packet) Line 49	C++
 	worldserver.exe!WorldSession::Update(unsigned int diff, PacketFilter & updater) Line 317	C++
 	worldserver.exe!World::UpdateSessions(unsigned int diff) Line 2987	C++
 	worldserver.exe!World::Update(unsigned int diff) Line 2330	C++
 	worldserver.exe!WorldUpdateLoop() Line 435	C++
 	worldserver.exe!main(int argc, char * * argv) Line 342	C++

**Comment by jackpoz** [comment] 2019-04-27 14:33
fixed in https://github.com/TrinityCore/TrinityCore/commit/844e7ee9262a5ba035ac9e8a6ffc298fb97fd3a9

**Closed by jackpoz** 2019-04-27 14:33 UTC
Labels: HasBacktrace
