### ISSUE TITLE
[3.3.5][6.x] The Light of Dawn

### ISSUE THREAD

**Issue by scorchedwow** [TrinityCore/TrinityCore#13294] opened 2014-10-09 23:06 UTC
The Light of Dawn - DeathKnight Quest.
There is no display of start of battle & no npc spawn. 
Like this
https://www.youtube.com/watch?v=IILivTprE-E
would anyone fix this issues? 

Core Rev: d1d03aa44f79
DB Rev: TDB335.56

Change NPC and it's working ok but It's dont show how many left to kill. 

And also Death Gate can only port to Death Knight Training area but it's wont go back to place where belong to.
##

**Comment by cavaclub** [comment] 2016-12-27 03:45
https://youtu.be/oFmIextbmbI

**Comment by sawd20** [comment] 2020-11-26 13:02
@illfated @scorchedwow  if You use .Evade on Highlord darion the quest will continue to complete mybe this npc wont evade the fight thats the reason that the quest wont complete

**Comment by illfated** [comment] 2020-11-26 18:19
Hmm. I used to test this issue myself, but I usually made it work by keeping my DK character close to Highlord Darion Mograine all the time, from the point of mustering and up to Light's Hope Chapel, just following the fight without doing much (I don't remember if the player is supposed to make a big difference in that fight). That tactic worked all the time for me, but it has been about a year since I last tested this issue.

From my point of view, this ticket should be remade and based both on current TC source (3.3.5) and with a new issue ticket properly filled in with all the necessary details, without removing any of the template text lines.

Not sure what you others think of that opinion.

**Comment by offl** [comment] 2020-11-26 20:41
> From my point of view, this ticket should be remade and based both on current TC source (3.3.5) and with a new issue ticket properly filled in with all the necessary details, without removing any of the template text lines.

Exactly

Why this was closed https://github.com/TrinityCore/TrinityCore/issues/23335

**Comment by illfated** [comment] 2020-11-26 20:50
> Why this was closed #23335

I think the ticket closure was motivated by ticket age, more so than any other qualifications. 
I would be pleased to see the closure reverted to this ticket being closed and ticket https://github.com/TrinityCore/TrinityCore/issues/23335 reopened.

**Comment by offl** [comment] 2020-11-26 20:58
Nah, better to write new one

**Comment by illfated** [comment] 2020-11-26 21:18
Sure, that is also fine with me. I just hope as much of the details as possible will be filled in by using the full issue ticket template without any removals.

**Comment by offl** [comment] 2020-11-26 21:22
Just basic description with repro steps

**Comment by sawd20** [comment] 2020-11-26 23:23
Look becuase of the knock back the mobs will seprate and stay away  from the church in the midle of the fight highlords leave the fight and if the knock backs make darion away from church the quest wont complete anymore also many of npcs are naked 😁
I think making lord darion immue to abilities can make it better

**Comment by offl** [comment] 2021-02-23 18:24
Duplicate of #26135

**Closed by offl** 2021-02-23 18:24 UTC
Labels: Priority-Cosmetic, Sub-Quests
