### ISSUE TITLE
Mind Control while shadowfiend

### ISSUE THREAD

**Issue by johndays** [TrinityCore/TrinityCore#5990] opened 2012-04-02 15:39 UTC
Well, when you have summoned your shadowfiend to attack someone, you can't Mind Control anyone, error message is :

"You already control a summoned creature"

Same for Inferno spell's lock.

http://oi43.tinypic.com/xoqw0m.jpg

What is expected :

dismiss your currently creature, and summon the new one.
##

**Comment by Raydor** [comment] 2015-01-27 10:36
Bump, still bugged https://github.com/TrinityCore/TrinityCore/commit/0b8a86886bec1979b698b4109c1f667ba1257fc0

**Comment by Raydor** [comment] 2017-06-29 13:44
This has been fixed at some point (don't know when and how), but can't reproduce in https://github.com/TrinityCore/TrinityCore/commit/e35092c6a164e929f9684b350093b2beefee5d86.

Now the shadowfiend gets despawned when the enemy is mind controlled.

**Comment by Keader** [comment] 2017-06-29 13:45
Cool, so closing.
If someone still can reproduce it in current revs, please talk to us :)

**Closed by Keader** 2017-06-29 13:45 UTC
Labels: Sub-Spells
