### ISSUE TITLE
[3.3.5] Shadowform priest

### ISSUE THREAD

**Issue by DeActiver** [TrinityCore/TrinityCore#18178] opened 2016-10-31 02:44 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** if spam change form , stop cooldown and can't back form.
must logout for back form .

**Current behaviour:** (Tell us what happens.) stop cooldown for spam form before 1.5 sec

**Expected behaviour:** (Tell us what should happen instead.) 1.5 sec time coold down.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  697147a596515c82817a161e7a9a5f07cdf9a8f3

**TDB version:**  62

**Operating system:**  win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment] 2016-10-31 03:22
#657 fixed by 6d07fbf07c9f1387644d8ec0c1905edc838b1273

**Comment by DeActiver** [comment] 2016-10-31 03:26
teank you ariel- test code ,

**Comment by Ghost-R** [comment] 2016-10-31 05:19
Confirm
**Steps to reproduce the problem:**
1. Cast "Flash Heal"
2. Before cast finish spam Shadowform
Try 2 or 3 time Shadowform will be Lock.
I use this [hacky fix](https://github.com/TrinityCore/TrinityCore/issues/657#issuecomment-8433390)

**Comment by ariel-** [comment] 2016-10-31 05:38
Ok, tagging @mik1893 since he did the initial fix.

**Comment by Keader** [comment] 2016-11-01 02:32
like i told to Mik, that commit don't fix the problem... only make occurs more rarely... And dont fix MD btw

**Comment by SnapperRy** [comment] 2016-11-01 14:13
Same thing still happens with the Raise Ghoul Death Knight spell, albeit very rarely. Haven't found a reliable way to reproduce that yet.

**Comment by Strazhnik** [comment] 2017-11-07 10:35
Confirm.
While in combat and try 2 or 3 time use Shadowform - will be Lock.

**Comment by Langerz82** [comment] 2018-02-20 05:15
Confirmed in latest 335, looking into it.

**Comment by Langerz82** [comment] 2018-02-20 06:46
This is a hack and I am not sure if it will break anything else, needs proper testing.

```
diff --git src/server/game/Spells/Spell.cpp src/server/game/Spells/Spell.cpp
index 03d45aa223..6efafeff21 100644
--- src/server/game/Spells/Spell.cpp
+++ src/server/game/Spells/Spell.cpp
@@ -4909,8 +4909,10 @@ SpellCastResult Spell::CheckCast(bool strict, uint32* param1 /*= nullptr*/, uint
         {
             if (m_triggeredByAuraSpell)
                 return SPELL_FAILED_DONT_REPORT;
-            else
+            else if (m_castItemEntry)
                 return SPELL_FAILED_NOT_READY;
+            else
+                return SPELL_FAILED_DONT_REPORT;
         }
     }
 

```

**Comment by Keader** [comment] 2018-06-03 14:13
@Langerz82 Pr it.

**Comment by Riztazz** [comment] 2019-05-30 09:03
> Confirm
> **Steps to reproduce the problem:**
> 
> 1. Cast [Flash Heal]
> 2. Before cast finish spam Shadowform
>    Try 2 or 3 time Shadowform will be Lock.
>    I use this [hacky fix](https://github.com/TrinityCore/TrinityCore/issues/657#issuecomment-8433390)
> 
> I test other spell like [Lesser Heal], [Heal], [Greater Heal] no problem found, just when using [Flash Heal].

That's the way to go about it really, just use IsCooldownStartedOnEvent() instead of ID checking

**Closed** 2024-04-06 20:53 UTC
Labels: Sub-Spells, Comp-Core, Branch-3.3.5a, Feedback-FixHack
