### ISSUE TITLE
[3.3.5] Core/Crash: _M_find_before_node (__k=<error reading variable: access outside bounds of object referenced via synthetic pointer>, __code=66114, this=<optimized out>, __n=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/hashtable.h:1448 1448		  if (!__p->_M_nxt || _M_bucket_index(__p->_M_next()) != __n)

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#16341] opened 2016-01-22 12:05 UTC
http://paste.ubuntu.com/14597169/
Rev: 8ef9ea9157ca6c04194888a2118be7daf303856f

**Comment by Carbenium** [comment] 2016-01-22 12:35
Lol. Never saw a SIGBUS before

**Comment by Shauren** [comment] 2016-01-22 13:15
instance reset times? 99% sure the cause of this one is the same as infamous #14477

**Comment by Runico** [comment] 2016-01-22 16:23
@Shauren, I have disabled all of HandleCalendar by putting return; after first { at every functions,

Like this one
```
void WorldSession::HandleCalendarGetCalendar(WorldPacket& /*recvData*/)
{
    return;
```

**Comment by Shauren** [comment] 2016-01-22 16:50
well yeah but that one crashed in getting instance reset times... accesses the same memory

**Comment by jackpoz** [comment] 2016-01-23 10:06
> I have disabled all of HandleCalendar by putting return

lol, that change makes no sense since HandleCalendar crash is not cause but the effect.

**Comment by Runico** [comment] 2016-01-30 13:14
http://paste.ubuntu.com/14731130/
http://paste.ubuntu.com/14731131/

**Comment by Aokromes** [comment] 2017-07-16 12:34
Over a year since the last crashlog, and original and unique reported deleted account, closing, if this bug is still valid post one NEW ticket with updated core.

**Closed by Aokromes** 2017-07-16 12:34 UTC
Labels: Branch-3.3.5a, Comp-Core, HasBacktrace
