### ISSUE TITLE
Core/Movement/Maps: Spells ignoring textures

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#21255] opened 2018-01-18 01:39 UTC
**Description:**  Fear movement is broken. Blink Destination is broken. Shadow step destination is broken. Charge/Intersept destination is broken

**Current behaviour:** Players affected by fear, just ignore map. They start fly, enter in textures, a real mess. Maybe MMaps/Vmaps issue?
Same to Blink, Shadow step, Charge/Intersept.

**Expected behaviour:** Players affected by fear should run around like a normal player. Players teleported by Blink should not drop of map ( same in Shadow Step/Charge )

**Steps to reproduce the problem:**

1. I tested in Warsong map
2. just add Fear aura in some place, and see how broken it is (.aura 5782)

Check: https://youtu.be/-V0H3wx1TU8 (fear)
Check2: https://youtu.be/Z75TuzmaKj4 (blink)

PS: Vmaps/MMaps is active

Edit: Bug intoduced by https://github.com/TrinityCore/TrinityCore/commit/e42903ec16f4849b71bc8736e3151a1e11d3cd25

**Branch(es):** 3.3.5

**TC rev. hash/commit:** ccf0807be0974dfb8080cb2fc6ea616cc96f062c

**Comment by Keader** [comment] 2018-01-18 12:03
Hapening with Shadowstep too.

**Comment by Persephone** [comment] 2018-01-18 12:49
Confirmed, really ancient bug

**Comment by Keader** [comment] 2018-01-18 13:37
With fear is ancient, but now alot spells is droping you of map

**Comment by Foereaper** [comment] 2018-01-18 17:15
This happens with Mage Blink and Warrior Charge as well, not sure if it is relevant to the above issue, but I have noticed it happening more recently than before.

**Comment by Jildor** [comment] 2018-01-18 17:21
Maybe @Golrag commit
https://github.com/TrinityCore/TrinityCore/commit/e42903ec16f4849b71bc8736e3151a1e11d3cd25

**Comment by Keader** [comment] 2018-01-18 17:27
No @Jildor  already checked it.
I reverted localy https://github.com/TrinityCore/TrinityCore/commit/95456ab5d8bd623481d315ae55dfbb44b45ba9f5 and https://github.com/TrinityCore/TrinityCore/commit/e42903ec16f4849b71bc8736e3151a1e11d3cd25 and is not the cause.

**Comment by Jildor** [comment] 2018-01-19 07:53
@Keader can you try to revert  @jackpoz mmaps commits? like this: https://github.com/TrinityCore/TrinityCore/commit/f8fd0b7a2c0a9acd084f011c614d529e49397479

**Comment by Keader** [comment] 2018-01-19 07:55
Already did with recast stuff and not causes it

**Comment by jackpoz** [comment] 2018-01-19 10:00
lol @Jildor https://github.com/TrinityCore/TrinityCore/commit/f8fd0b7a2c0a9acd084f011c614d529e49397479 increases the accuracy of mmaps, it actually makes issues like this happen less often.

@Keader are you doing your tests in a plain field or on a very edgy slope ? I did some tests years ago trying to fix this issue (making the points closer in the path, changing Z for raycast) but I never found a way to send the client a path that it will not make it fall.
I chose a x,y,z and kept porting there, then charged to a spawned NPC that didn't move and debugged/tested that single case at a time, it helps when dealing with these random issues. There is most likely an issue on GitHub about it.

**Comment by jackpoz** [comment] 2018-01-19 10:08
https://github.com/TrinityCore/TrinityCore/issues/11526#issuecomment-118539986

**Comment by Keader** [comment] 2018-01-19 10:15
I did my tests in warsong (as a vídeo)

**Comment by Persephone** [comment] 2018-01-19 15:16
Blinking through objects didn't happend not long ago o.0 woah that video is scary.. but confirmed :(

**Comment by tje3d** [comment] 2018-01-19 18:45
Also Blink not works properly in slope.
Video: https://youtu.be/rQeXnpWjbhk

**Comment by Keader** [comment] 2018-01-19 20:06
Ok i miss test it.
I found what commit cause it
@Golrag / @jackpoz  (https://github.com/TrinityCore/TrinityCore/commit/e42903ec16f4849b71bc8736e3151a1e11d3cd25) cause drop of texture issues.
Without it, all spells "work" (with old issues, but dont ignore textures anymore).

**Comment by Jildor** [comment] 2018-01-19 20:35
So, summon @Golrag :smile:

**Comment by Golrag** [comment] 2018-01-19 21:07
I will take a look sometime later (after next week maybe), but if it is like the bug (or same cause) I described in my PR then I wont be able to fix it :/. To me, on the video when you walk in the air or you walk a really steep "mountain" you shouldn't get a path to that point.

**Comment by Keader** [comment] 2018-01-19 21:08
Yes, it's a old issue.
But still, you should not drop of map when it happens xD

**Comment by Golrag** [comment] 2018-01-19 22:13
just did some quick testing and yea I'm afraid its kinda the same issue I had when testing my previous PR when you go to 1486 1602 357 in warsong gulch, the hill wont break (vmap/gameobject) LoS.
Yet height data seems to work correctly on it

**Comment by kvipka** [comment] 2018-01-20 12:08
i think you talking about other problem (wrong calculation in LoS checking). Textures working perfect

blink WSG slope : [video](https://www.youtube.com/watch?v=gk-h7j00bvw&feature=youtu.be)
blink in Dalaran : [video](https://www.youtube.com/watch?v=vXcaRPYF8Ok&feature=youtu.be)

**Comment by Keader** [comment] 2018-01-20 12:14
Nope @kvipka.
I'm have 2 cores, 1 with your blink patch, 1 without it (Clean TC).
With your patch blink still work, without drop textures, but with Clean TC dont.
I belive that you trying with a not clean TC ^^

**Comment by kvipka** [comment] 2018-01-20 12:24
nope, i using last TC always, with my changes ofc =)
2 suggestions : 
1 : https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Object/Object.h#L450
change on 0.5f
2 : https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Object/Object.cpp#L2367
change on 
`UpdateAllowedPositionZ(pos.m_positionX, pos.m_positionY, pos.m_positionZ);`

i did more, but can't remember now what else

**Comment by Golrag** [comment] 2018-01-20 13:26
btw I am able to reproduce it while reverting https://github.com/TrinityCore/TrinityCore/commit/e42903ec16f4849b71bc8736e3151a1e11d3cd25 while less likely tho (might be unlucky/lucky)

**Comment by Golrag** [comment] 2018-01-23 16:55
Playing around locally with some changes I made.
https://puu.sh/z7USN/4e09d7cd07.mp4

Will try to finish it after friday...

**Comment by Persephone** [comment] 2018-01-24 08:21
@Golrag that looks amazing, hope you will share what you find <3

**Comment by Persephone** [comment] 2018-01-26 09:38
@Golrag any news? <3

**Comment by Jildor** [comment] 2018-01-26 10:03
>Will try to finish it after friday...

patience 😄

**Comment by Golrag** [comment] 2018-01-26 17:29
Need more time, but I'm not trying to have a blizzlike blink (this is not really possible I think with our current pathfinder). But I'm trying to get rid of most undermaps caused by it tho.

**Comment by jackpoz** [comment] 2018-01-27 08:18
Fix fear first, blink already had its own branch

**Comment by Shauren** [comment] 2018-01-27 11:07
no, pretend that branch does not exist

**Comment by Golrag** [comment] 2018-01-27 20:29
The main issue here is that GetHeight/UpdateAllowedPositionZ doest not return the z we want, compared to where we are standing. Both blink and fear use MovePositionToFirstCollision so "fixing" the blink under map issue *should* fix the fear undermap thing. Unless pathfinder makes a shortcut for some reason.

I kinda re-implemented the previous function we previously used in MovePositionToFirstCollision but tweeked it alot.. and I am absolutely not really happy with it but w/e.
It's mainly checking if the z we got should go to the nearest vmap height or gridheight and it's such a pain to find that out lol

**Comment by Golrag** [comment] 2018-01-28 13:48
Welp, I looks like I can't make any good fix for this.. shall I PR it anyway ? Code is a mess tho and I think it's an improvement

**Comment by tkrokli** [comment] 2018-01-28 16:38
No harm in making a PR and get proper feedback to the code you have written so far.

**Comment by zabiksandbox** [comment] 2018-02-20 06:36
Vmap totaly dont work, with all spells. I can cast spells through a tree, a rock, a hill, a wall.
In door check dont work too, with the exception of the floor.

I've seen this bug more than a month ago. 
vmap.enableLOS    = 1
vmap.enableHeight = 1
vmap.enableIndoorCheck = 1
All "data" re-export with updated tools.

3535 branch, last commit - 1cc3d33 . TDB 335.64. - ed63d15

**Comment by Jildor** [comment] 2018-02-20 06:59
Not relates with the issue, this is blizzlike #19185

**Comment by zabiksandbox** [comment] 2018-02-20 07:02
Okay, what's LOS for then? On than LOS can be test?

**Comment by Jildor** [comment] 2018-02-20 07:04
On  M2 (trees, rocks) ignore LoS

**Comment by zabiksandbox** [comment] 2018-02-20 07:10
What about the hills on terrain, they should ignore LOS, too?
I can cast through everything except the floors. It seems to me that it's not blizzlike.

**Comment by Jildor** [comment] 2018-02-20 07:25
I can't test it by now, but it shouldn't ignore LoS I think

**Comment by Aokromes** [comment] 2018-02-20 08:05
LOS is really tricky, even on retail, on a lot of places you can ignore LOS even on floor on retail.

**Comment by jackpoz** [comment] 2018-02-20 08:14
@Keader could you check if fear works better and close this issue if so ? thanks

**Comment by Jildor** [comment] 2018-02-20 08:26
So blink PR and branch still needed with this?

**Comment by kvipka** [comment] 2018-02-20 09:19
@Jildor , it's not correct a question.

blink branch not for "stop falling undergroung" , it's a algorythm for calculation correct path instead of pathfinder. ( it's maybe big code, yes, but idea alternative! )

look at this : 
![blinkpath](https://user-images.githubusercontent.com/2619928/36415764-185a17c0-1638-11e8-849b-81fd73951b65.png)

**Comment by Jildor** [comment] 2018-02-20 09:28
Aah, ok thx :+1:

**Comment by zabiksandbox** [comment] 2018-02-23 07:25
@Jildor , so. I remvoe "VMAP::ModelIgnoreFlags::M2" from Spell.cpp - only GO can ignore M2. 
And los will work exacly  like "blizzlike".

**Comment by Warpten** [comment] 2018-02-23 07:33
Spells always ignored terrains. The only map structures obstructing visions are large wmos and gameobjects ((trap)doors only if open)

**Comment by zabiksandbox** [comment] 2018-02-23 08:49
its bullshit, go to blizzard server now and check it, kid

**Comment by Jildor** [comment] 2018-02-23 09:29
>Yes, on retail spells ignore terrain (mountains, floor) and M2 models (trees, that huge tree stump in warsong) but not buildings (WMO)

Yep, Warsong is the best example 😄 
All trees and rocks are M2, tha houses are WMO ;)

**Comment by Warpten** [comment] 2018-02-23 11:51
You don't even need an active sub to test it. Make a human warlock and go near the back of the start area. Kill the goblins through the goddamn terrain.

**Comment by Pugnadeus** [comment] 2018-03-09 09:05
Any update on this yet? Fear just makes people rage quit in Warsong Gulch.

**Comment by SoulKah** [comment] 2018-04-29 13:10
Bump to give this issue some attention, first attempts looked promising but the topic died ;(

**Comment by Marcussiah** [comment] 2018-08-04 23:41
bump

**Comment by illfated** [comment] 2018-08-05 11:46
Please note that TrinityCore is about learning how to apply proper C++ or MySQL DB coding to the source and see the results in the game client. Posting suggestions on how to improve the current source code is a much better way to give this issue attention than posting a useless "bump" comment which (more often than not) will be removed, because it does not add anything useful to the issue report.

**Comment by pravietis** [comment] 2018-09-28 13:37
Have Lastest Trinity Core 3.3.5 version and have problem, when using Blink Fear charge i Faling in textures charge. How to Fix that Problem?

**Comment by Marcussiah** [comment] 2018-09-28 15:59
> 
> 
> Have Lastest Trinity Core 3.3.5 version and have problem, when using Blink Fear charge i Faling in textures charge. How to Fix that Problem?

Having the same issue issue here. It looks like it is a TC broken issue.

**Comment by devfrom** [comment] 2018-09-28 16:46
Error confirmed!

@Golrag @Keader @ccrs

**Comment by kvipka** [comment] 2018-09-28 17:47
Object.cpp
```
@@ -1498,7 +1498,11 @@ void WorldObject::UpdateAllowedPositionZ(float x, float y, float &z) const
                     z = ground_z;
             }
             else
-                z = GetMapWaterOrGroundLevel(x, y, z);
+            {
+                z = GetMapHeight(x, y, z + (3 * unit->GetCollisionHeight()));
+                if (z < INVALID_HEIGHT)
+                    z = GetMapHeight(x, y, z + 10.0f);
+            }
         }
         else
         {

```

**Comment by Tateruvatar** [comment] 2018-10-28 11:39
could this be tagged as critical? it makes pvp pretty unplayable

**Comment by Aokromes** [comment] 2018-10-28 12:39
critical is only constant crashes or data loss.

**Comment by illfated** [comment] 2018-10-28 15:52
... or worldserver/authserver (built on current HEAD) not starting/loading/completing.

**Comment by yvomsx** [comment] 2018-11-19 01:09
> @Jildor , so. I remvoe "VMAP::ModelIgnoreFlags::M2" from Spell.cpp - only GO can ignore M2.
> And los will work exacly like "blizzlike".

How does this affect spells from causing u to drop falling trough the world?

**Comment by yvomsx** [comment] 2018-11-23 01:18
@Aokromes at what point do bounties get appended?

**Comment by illfated** [comment] 2018-11-23 17:43
Usually the same day as a bounty is increased or created.
Depends on if there is a working link between the bounty and the issue.
Has a bounty been created for this issue page?

**Comment by Golrag** [comment] 2019-01-02 20:45
Sorry have been quite busy, not really sure i can fix it but i can try again,   https://gist.github.com/Golrag/1dfc4045a74dad26195970db03e7ce04 (this is not tested, can test tomorrow maybe)

**Comment by Golrag** [comment] 2019-01-03 17:56
updated my gist file
with this you will blink more on the same place. Still managed to fall through the floor above the tunnels in warsong gulch but that's because pathfinder gave a path with final dest z under gridheight and closer to vmap height and a "valid" path (dont know where to look for that)

No time to be busy with PR sorry, feel free to test it tho

**Comment by Keader** [comment] 2019-01-05 12:16
Sirikfoll tested it @Golrag and still not good.
He still fall of map with a high frequency

**Comment by Cobus420** [comment] 2019-01-07 14:21
Do we got some news on this?

**Comment by Golrag** [comment] 2019-01-07 14:53
Can I get some examples of the failing locations ? So I can know why it fails (I think I know why but I want to be sure). Will take another look at this this week :)

**Comment by Golrag** [comment] 2019-01-07 21:45
Did you try it with my patch ? Anyway I updated it. Not sure at all about the changes in path finder (just playing around with it a bit). Oh and don't test it with .gm fly on.

Small summary of the changes: Don't flee (or confuse) to a location which path is a shortcut. I think that was one of the biggest issues, fear dropping while walking through terrain

**Comment by sirikfoll** [comment] 2019-01-08 02:21
Now Fear movement looks really good :)

**Comment by Cobus420** [comment] 2019-01-08 17:51
confirmed. Nice thank you. :) But the "Blink Problem" is still there. Got some idea on this one to?

**Comment by Killyana** [comment] 2019-01-08 22:04
I tested the change, it fixes fear, blink and knock back issue https://github.com/TrinityCore/TrinityCore/issues/21839

**Comment by Cobus420** [comment] 2019-01-08 22:43
Hmh. I agree with the fear. But i can still blink trough walls/ground.

**Comment by Killyana** [comment] 2019-01-08 23:00
Could you provide coords?

**Comment by Cobus420** [comment] 2019-01-08 23:11
Testet Desolace and Thousand needles. Trying to Blink up normal ways and staying a bit in front of a mountain. Its working fine when trying to blink down but not up.

**Comment by Killyana** [comment] 2019-01-08 23:14
use .gps to get the exact position where the blink make your char undermap

**Comment by Cobus420** [comment] 2019-01-08 23:17
X: -1845.736938 Y: 2884.162842 Z: 45.698051

**Comment by Killyana** [comment] 2019-01-08 23:49
You didn't update your core with the patch, or you're using the original version
Blink on (.go xyz -1835.21, 2880.902, 47.82452 1) will cause an undermap on the current revision, but not with the Golrag patch.
For me every thing is fine for fear, blink and knock back.

**Comment by Persephone** [comment] 2019-01-09 00:55
@Killyana can you still blink through the tunnel in WSG with golrag patch? I am unable to test the patch atm, but being able to do that at the horde base has been a bug for years xD

**Comment by TheWinchesters** [comment] 2019-01-09 01:37
What about Warrior charge?

**Comment by Killyana** [comment] 2019-01-09 02:04
Warrior charge is slightly better but still you can end undermap, it's caused by the charge not checking for available path via mmaps, so not related to this issue.
In WSG tunnel you can blink in some spots, but in other ones the character will not move at all, there's already an issue for that.

**Comment by TheWinchesters** [comment] 2019-01-09 02:42
Thank you Killyana.
Is there a open issue about those spells with the same effect that Warrior Charge?

**Comment by Aokromes** [comment] 2019-01-09 08:35
https://github.com/TrinityCore/TrinityCore/issues/11526

**Comment by Aokromes** [comment] 2019-01-09 20:21
@Golrag 
src/server/game/Maps/Map.cpp:2444:82: warning: unused parameter 'maxSearchDist' [-Wunused-parameter]
float Map::GetHeight(float x, float y, float z, bool checkVMap /*= true*/, float maxSearchDist /*= DEFAULT_HEIGHT_SEARCH*/) const
                                                                                 ^
other than that my mages are really happy with this patch

**Comment by jackpoz** [comment] 2019-01-11 12:59
@Golrag please push your changes to a branch and link the branch instead of using gists, even better if you open a PR so the discussion can continue there (even if it's a WIP, PRs are cheap :) )

**Comment by Golrag** [comment] 2019-01-11 15:43
Will make a PR tomorrow afternoon

**Comment by Aokromes** [comment] 2019-02-23 10:47
review https://github.com/TrinityCore/TrinityCore/pull/22937

**Comment by Killyana** [comment] 2019-04-07 19:36
The pr was merged if you encounter any  under-maps caused by : Blink, Shadow step, fear, knock back, provide the gps position and how to reproduce the issue.
Intercept and charge ar not related to this ticket.

**Comment by sirikfoll** [comment] 2019-04-07 20:04
.go xyz 2849.114990 5941.172363 11.285686 530
.aura 12096

**Comment by Golrag** [comment] 2019-04-07 20:45
Seems like pathfinder generated a path with PATHFIND_INCOMPLETE
Destination: 2848.41504 5942.22168 11.2501392
Path:
2849.11499 5941.17236  11.2875738
2848.41504 5942.22168 0.860420227

**Comment by Aokromes** [comment] 2019-04-07 21:00
try after e061663

**Comment by Golrag** [comment] 2019-04-08 20:28
That's the rev I tried it on
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Movement/PathGenerator.cpp#L242
The position returned here is wrong :/

**Comment by Killyana** [comment] 2019-04-08 20:39
Yes it happen in the current revision.

**Comment by jackpoz** [comment] 2019-04-09 08:52
did it happen before too ?

**Comment by jackpoz** [comment] 2019-04-09 10:12
nvm, found https://github.com/TrinityCore/TrinityCore/issues/23080#issuecomment-479736297 so it did happen before (and the issue is the same as what I described in https://github.com/TrinityCore/TrinityCore/issues/23080#issuecomment-469034643

**Comment by Hir0shi** [comment] 2019-05-22 16:57
ConfirM

@jackpoz

**Comment by jackpoz** [comment] 2020-01-11 20:17
please try after https://github.com/TrinityCore/TrinityCore/commit/29bf280e3496cf13c24ccb20e37da29d3bfa74d9 to see if anything improved

**Comment by jackpoz** [comment] 2020-02-10 06:33
Anyone up to test this after the  commit of 1 month ago ?

**Comment by illfated** [comment] 2020-02-10 12:19
Maybe treat those who complain the most about issues (like this one) that if nobody says anything, it is all good.
Most people only say something if it does not work as expected, but stop talking when things work again.

**Comment by Jinnaix** [comment] 2020-02-10 12:25
That should work in more then only WSG cases, right? 
I have 1-2 Spots noted down that have critical undermap issues with being feared. (critical in terms of its a boss fight and can affect multiple people at once -> result is a wipe)
Will test and provide feedback tuesday evening.

**Comment by Jinnaix** [comment] 2020-02-12 18:44
.go xyz -7566.065918 -1253.730835 476.800049
.aura 12096 
you will fall trough the ground 
or learn blink and blink from that point - you wont move at all

.go xyz 2849.114990 5941.172363 11.285686 530
.aura 12096
no movement at all

**Comment by illfated** [comment] 2020-02-12 19:42
Not sure where you intend to go with those coordinates, but my player ended up 742.76 meters up in the air above Un'goro Crater.

<details>

![WoWScrnShot_021220_203547](https://user-images.githubusercontent.com/38162891/74370716-dd0ac780-4dd7-11ea-8e3d-7606498f67b8.jpg)

</details>

Does it make a difference where your character is placed before issuing the command `.go xyz -7566.065918 -1253.730835 476.800049` ? My character stood on top of the Orgrimmar Bank (teleport location).

**Comment by Jinnaix** [comment] 2020-02-12 19:48
haha, mabye - these coordinates are inside black wing lair

**Comment by illfated** [comment] 2020-02-12 19:49
OK, fair enough. Would have been useful to know that you need to move inside the Blackwing Lair instance first.

**Comment by Jinnaix** [comment] 2020-02-12 19:51
I didnt know that this is necessary - Sorry! Learned something again.

**Comment by illfated** [comment] 2020-02-12 20:58
Fair enough. Steps to reproduce (to get to Nefarian's Lair) :
1. `.gm on` + `.gm fly on`
2. `.tele BlackwingLair`
3. Enter the raid instance (with or without fighting the 3 guards)
4. `.go xyz -7566.065918 -1253.730835 476.800049` (Nefarian's Lair)
5. `.aura 12096` (cast Fear on yourself)
6. Observe how the character ends up below the surface (this is where `.gm fly on` becomes useful)

I also tested using the `.go xyz -7566.065918 -1253.730835 476.800049` command from outside the Black Rock Depths entrance and from Elwynn Forest, I simply ended up hanging in the air somewhere in or around Black Rock Spire.

**Comment by jackpoz** [comment] 2020-02-13 07:34
.go xyz has map id as parameter, please include that in the How To Reproduce steps

**Comment by illfated** [comment] 2020-02-13 18:21
Is there a map ID for Nefarian's Lair or Blackwing Lair? I could not see one when I tested (in-game map ID 0,0), but maybe it does not show up in the game client?

For the Circle of Blood Arena, the `.go` command contains the map ID already:
```
.go xyz 2849.114990 5941.172363 11.285686 530
```

**Comment by jackpoz** [comment] 2020-02-14 07:29
.gps should return the map id

**Comment by jackpoz** [comment] 2020-02-14 07:48
@Jinnaix the "no movement at all" is the way we handle places that have no mmaps support so that's the expected behavior.
As for the falling underground, what I was looking for was "is the initial issue any better now compared to when this issue was opened ?" . In particular
>Players affected by fear, just ignore map. They start fly, enter in textures, a real mess. Maybe MMaps/Vmaps issue?
Same to Blink, Shadow step, Charge/Intersept.

**Comment by illfated** [comment] 2020-02-14 17:54
```
[18:51:02] Map: 469 (Blackwing Lair) Zone: 2677 (Blackwing Lair) Area: 2677 (Blackwing Lair) Phase: 4294967295
[18:51:02] X: -7566.065918 Y: -1253.730835 Z: 476.800049 Orientation: 0.000000
[18:51:02] grid[17,29]cell[6,5] InstanceID: 2
[18:51:02]  ZoneX: -7566.065918 ZoneY: -1253.730835
[18:51:02] GroundZ: 474.649902 FloorZ: 476.799835 Have height data (Map: 1 VMap: 1 MMap: 1)
```
Regarding the Circle of Blood Arena, it is the pillar in the middle of the arena, where the player character does not move when feared. There does not seem to be any gameobject nearby, so I don't know what keeps the player from moving, or whether that is intended or not.

**Comment by jackpoz** [comment] 2020-02-15 14:22
I don't see how "player not moving" is an issue if not purely cosmetic. It has little to do with this issue about "spells ignoring textures"

**Comment by illfated** [comment] 2020-02-15 14:47
Fair enough. I was mostly just expanding on the OP's details. Then again, I also presume that your comment is directed to the OP.

**Comment by Jinnaix** [comment] 2020-02-17 11:35
First of all - sorry. I wasnt aware that the .go xyz command has/needs a map parameter since i dont work with gps coordinates that much. Thanks for the clarification and thanks @illfated for providing the corrected xyz coordinates.

For the Arena gps i took what @sirikfoll provided because the only selffound issue i had was located in BWL.
It might be the fact that "no movement at all" is intended for areas without mmaps support but creature/player movement while being feared is a essential part of the mechanic. Since these coordinates had already been reported, i decided to recheck them after your request to do so, thinking it was a valid report.

For my report in general i sticked to Killyanas message:

>The pr was merged if you encounter any under-maps caused by : Blink, Shadow step, fear, knock back, provide the gps position and how to reproduce the issue.
Intercept and charge ar not related to this ticket.

I would say that the problems related to Nefarians Lair are valid in this point since fear movement seems to target a point right below the ground texture and forcemoves you there (what eventually results in player falls trough ground layer).

But if i missed the topic here, im sorry.

**Comment by Killyana** [comment] 2020-02-28 20:48
I'm no longer able to reproduce the under map issue in .go xyz -7566.065918 -1253.730835 476.800049 469 (Nefarian's Lair) with fear
I will close this issue as all main issue are fixed in rev. ffede34ba9a3

**Closed by Killyana** 2020-02-28 20:48 UTC
Labels: Branch-3.3.5a, Comp-Core, Priority-High, Sub-Maps/MMaps/Vmaps, Sub-Movement, Sub-Spells, help wanted
