### ISSUE TITLE
[3.3.5][Crash] Worldserver crash when selling Forest Mushroom Cap

### ISSUE THREAD

**Issue by Phentora** [TrinityCore/TrinityCore#19457] opened 2017-04-14 11:11 UTC
**Description:**

World server crashed when selling [Forest Mushroom Cap](http://www.wowhead.com/item=4604/forest-mushroom-cap). When i restarted the server and sold the same item again, the server did not crash.

https://gist.github.com/Phentora/084a4d6fcb83fa7a0e941f2eee2d9d12

**Expected behaviour:**

Server should not crash.

**Steps to reproduce the problem:**

1. Have Forest Mushroom Cap.
2. Sell Forest Mushroom Cap.
3. Notice that the worldserver might crash.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 83177e771a37 2017-04-12 02:53:25 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**
335.62

**Operating system:**
Windows Server 2008r2

**Comment by Aokromes** [comment] 2017-04-14 11:13
release mode crashlogs are useless.

**Comment by Phentora** [comment] 2017-04-14 11:14
I will compile in debug mode and see if i can repro.

**Comment by Aokromes** [comment] 2017-04-14 11:15
also, cannot reproduce:
http://i.imgur.com/84injcc.png

**Comment by Aokromes** [comment] 2017-04-14 11:16
and update your core, a crash was fixed on a newer build.

**Comment by Phentora** [comment] 2017-04-14 11:21
Sorry about that. I forgot to git pull. Will compile in debug mode with the latest commit.

**Comment by ariel-** [comment] 2017-04-14 15:34
To reproduce you had to fill the merchant buyback, was fixed in d914c55c0585fe31a9a1b9fe4e9d4a9b498e8e8f

**Closed by ariel-** 2017-04-14 15:34 UTC
