### ISSUE TITLE
Hallows End Headless Horseman

### ISSUE THREAD

**Issue by Frayre** [TrinityCore/TrinityCore#25592] opened 2020-10-19 17:17 UTC
**Description:**

Headless Horsman even does not work properly. i found several issues. He should fly up into the air when he spawns. he runs across the ground and glitches up onto a roof and eventually engages you

after that i was able to attack him his nameplate sais Unknown. then he goes into a kill/split loop and is impossible to kill. you get his health down. his head splits from his body to a wind elimental? not sure why that's there. you attack the head and it rejoins the body and this cycle contiues...

also i went through this loop several times solo on a protection spec pally i would have thought he would hit harder.

**Expected behaviour:**

i dont know the exact fight but he should be able to be killed. (maybe not solo )

**Steps to reproduce the problem:**

1.Engage the headless horseman. 

**Branch(es):**

3.3.5 Not sure if this boss is avaliable in Master
**TC rev. hash/commit:** 

TrinityCore rev. 07845b4eceed 2020-10-05 01:55:34 +0300 (3.3.5 branch) (Win64, Release, Static)

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** 

Server runs on 2012r2  game client on windows 10 Pro (1909)

**Comment by Ovahlord** [comment] 2020-10-20 20:30
The flight issue is caused by (oh surprise) wrong scripting. It uses the CanFly movement flag while it's suposed to use DisableGravity. So long story short: the whole encounter is outdated and in need of sniff based patchups

**Comment by Keader** [comment] 2020-10-21 12:25
i wanna rewrite it, but we dont have any sniff of this creature.
if someone have... and can share, i can rewrite this encounter.

**Comment by Javilico92** [comment] 2020-10-21 15:32
> The flight issue is caused by (oh surprise) wrong scripting. It uses the CanFly movement flag while it's suposed to use DisableGravity. So long story short: the whole encounter is outdated and in need of sniff based patchups

Tested myself, waypoints are wrong, he want to fly... text are fixed in the script... but i can let him fly with "Movement.Flight = CreatureFlightMovementType::CanFly" (SetCanFly and SetDisableGravity do nothing ?) I only have a few videos from the battle in wotlk, so, waypoints is the hardest part

**Comment by Kittnz** [comment] 2020-10-21 17:58
Summoning @MantisLord

**Comment by Tauriella** [comment] 2020-10-22 12:49
@Keader 

Take a look in the cmangos scipt
the headless horseman have a smooth behavior and correct waypoint

**Comment by Keader** [comment] 2020-10-22 14:14
Yeah, i got some sniffs, working on it already
fixed the path already. I'm trusting in TC provided (to me, only first point was wrong). Because the problem there was not the path, was movement flags + wrong script.
Bad part is: all sniffs that i got, is from WOD -> Legion.
And this boss changed in MOP...
But right now, script it like in WOD/Legion is better then having this shit current script xd

**Comment by Aokromes** [comment] 2020-10-22 15:49
Aokromes: it should be just as easy as checking if there is a NPC_HEADLESS_HORSEMAN_MOUNTED around and alive and skip starting a new even if that's the case

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletMonastery/boss_headless_horseman.cpp#L912

**Comment by offl** [comment] 2020-10-22 17:15
@Keader maybe you can take a look at https://github.com/TrinityCore/TrinityCore/issues/22664 & https://github.com/TrinityCore/TrinityCore/issues/22667 too?

**Comment by Keader** [comment] 2020-10-23 00:07
sure

**Comment by Keader** [comment] 2020-10-26 17:05
https://github.com/TrinityCore/TrinityCore/commit/a93abcf8031fc3b4dc6db16aa09d92a221bc6a77

**Closed by Keader** 2020-10-26 17:05 UTC
Labels: Comp-C++Script, Sub-Creature
