### ISSUE TITLE
6.X.X Compile error

### ISSUE THREAD

**Issue by madmax765** [TrinityCore/TrinityCore#16103] opened 2015-12-26 20:41 UTC
Cant compile I get two 2 errors.
running windwos 10 pro 64 bit
V.S 2013 with update 4

on build Dec 25, 2015  https://github.com/TrinityCore/TrinityCore/commit/921d893c2a82eb6ac0762bf7001df87911b44611

cmake looks good

Detected 64-bit platform
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled increased number of sections in object files
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
Found OpenSSL library: optimized;C:/Max/OpenSSL-Win64/lib/VC/ssleay32MD.lib;C:/Max/OpenSSL-Win64/lib/VC/libeay32MD.lib;debug;C:/Max/OpenSSL-Win64/lib/VC/ssleay32MDd.lib;C:/Max/OpenSSL-Win64/lib/VC/libeay32MDd.lib
Found OpenSSL headers: C:/Max/OpenSSL-Win64/include
Found MySQL library: C:/Program Files/MySQL/MySQL Server 5.6/lib/libmysql.lib
Found MySQL headers: C:/Program Files/MySQL/MySQL Server 5.6/include
Found MySQL executable: C:/Program Files/MySQL/MySQL Server 5.6/bin/mysql.exe
Boost version: 1.59.0
Found the following Boost libraries:
  system
  filesystem
  thread
  program_options
  iostreams
  regex
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
Found git binary : C:/Program Files (x86)/Git/cmd/git.exe

* TrinityCore revision   : 921d893c2a82 2015-12-26 00:33:14 +0100 (6.x branch)

* Install core to        : C:/Program Files/TrinityCore

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (default)
* Build map/vmap tools   : Yes
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : No  (default)
* Use GIT revision hash  : Yes

Found ZMQ library: C:/Max/ZeroMQ 4.0.4/lib/libzmq-v120-mt-4_0_4.lib
Found ZMQ headers: C:/Max/ZeroMQ 4.0.4/include
SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: Custom
  -> Prepared: World
  -> Prepared: Outdoor PVP Zones
  -> Prepared: Eastern Kingdoms
  -> Prepared: Kalimdor
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: The Maelstrom
  -> Prepared: Events
  -> Prepared: Pet
SCRIPT PREPARATION COMPLETE

Configuring done
Generating done

but on compile i see 

24>LINK : fatal error LNK1181: cannot open input file '..\game\Release\game.lib'
25>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------

**Comment by tkrokli** [comment] 2015-12-26 22:28
921d893 Confirmed. VisualStudioVersion = 12.0.40629.0 (VS2013 Update 5). Release x64 build:
```
24>  WheatyExceptionReport.cpp
24>LINK : fatal error LNK1181: cannot open input file '..\game\Release\game.lib'
25>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
25>  Building Custom Rule C:/github.com/tkrokli/TrinityCore/CMakeLists.txt
25>  CMake does not need to re-run because C:\Build\TC_6x_x64\CMakeFiles\generate.stamp is up-to-date.
26>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
26>Project not selected to build for this solution configuration 
========== Build: 23 succeeded, 2 failed, 0 up-to-date, 1 skipped ==========
```
No other occurrences found for '..\game\Release\game.lib' in the Output page.
Error page:
```
Error	1	error LNK1181: cannot open input file '..\game\Release\game.lib'	C:\Build\TC_6x_x64\src\server\worldserver\LINK	worldserver
```
Not sure what more information would be helpful here, but I'll provide what I got:
Win10 Home x64, Boost 1.59.0, MySQL 5.6.28, OpenSSL 1.0.2e (1.0.2.5), CMake 3.4.0, ZeroMQ 4.0.4

**Comment by Shauren** [comment] 2015-12-27 00:21
Fixed in 9ab10d6e680ca835d1dfdfbceb9f18f330f994fc

**Closed by Shauren** 2015-12-27 00:21 UTC

**Comment by madmax765** [comment] 2015-12-27 12:38
Thanks Shauren Working now :D

**Comment by mhubregtse** [comment] 2016-07-17 20:04
I have this now in `df53a08`

**Comment by Aokromes** [comment] 2016-07-17 20:25
I sugest you to switch to visual studio 2015.

**Comment by mehrdadh** [comment] 2016-08-17 11:30
Cant compile I get two 2 errors.(wod 6.x)
running windows 7 ultimate 32 bit
V.S 2013 with update 5
how fix these Errors ???
----------------------------------------
24>LINK : fatal error LNK1181: cannot open input file '..\game\Release\game.lib'
24>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(607,5): error MSB6006: "link.exe" exited with code 1181.
25>------ Build started: Project: ALL_BUILD, Configuration: Release Win32 ------
25>  Building Custom Rule C:/Trinity/TrinityCore/CMakeLists.txt
25>  CMake does not need to re-run because I:\trinity test1\CMakeFiles\generate.stamp is up-to-date.
========== Build: 23 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by tkrokli** [comment] 2016-08-17 13:19
@mehrdadh : read the post above yours (https://github.com/TrinityCore/TrinityCore/issues/16103#issuecomment-233202055)

"I sugest you to switch to visual studio 2015."

TrinityCore source code (6.x for now, maybe 3.3.5 later) **is not supported in Visual Studio 2013**
- only Visual Studio 2015 + updates is the supported version of Visual Studio for TrinityCore.
