### ISSUE TITLE
Too far away

### ISSUE THREAD

**Issue by Regrad** [TrinityCore/TrinityCore#19874] opened 2017-06-10 22:39 UTC
b3336cf9433f14dbcc2e9a7eecb4062a936401b2 3.3.5

The mob can not be beat when the character is standing on a hill. The distance is too large. This is critical for long-range characters, as they can use a bug for dishonest games.

Video of bug:
https://youtu.be/q87jPhY42uw

**Comment by sirikfoll** [comment] 2017-06-14 15:30
That's a duplicate of issue #16549

**Closed by sirikfoll** 2017-06-14 15:30 UTC
