### ISSUE TITLE
[3.3.5] Warrior charge through traps

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21603] opened 2018-03-12 22:57 UTC
**Description:**

Warriors can charge through hunter traps (and i believe they can basically charge through any sort of trap).

**Expected behaviour:**

Should be stopped by the trap if it is in their path.

**Steps to reproduce the problem:**

1. place hunter Freeze Trap or something similar to stop the warrior
2. Charge to the hunter over the trap
3. Notice that the warrior does not stop before reaching the hunter.

**Branch(es):**  3.3.5

**TC rev. hash/commit:**   https://github.com/TrinityCore/TrinityCore/commit/abb602f7c12b00480899d245ad81abdf41f39621

**TDB version:**  335.64

**Operating system:** ubuntu

**Comment by tkrokli** [comment] 2018-03-12 23:41
I don't remember if this is a Core issue, Scripts issue or both.
(ariel- or Killyana will add the correct label & title)

**Comment by Killyana** [comment] 2018-03-13 00:08
Invalid-Intended/WontFix/Blizzlike probably, I don't think traps must or could be activated with a charge, even if it's the case looks too hard to fix.

**Comment by tkrokli** [comment] 2018-03-13 00:46
@Persephone : Looks like you may have to dig up some verifiable evidence for that "Expected behaviour" to have a good case.

**Comment by Persephone** [comment] 2018-03-13 09:54
Alright let me try find some i was just told by some people it was blizz :-)

**Comment by robinsch** [comment] 2018-03-13 10:25
It's not, you could charge over traps on 3.3.5

**Comment by Persephone** [comment] 2018-03-13 10:32
Ah okay :-)

**Closed** 2018-03-13 11:03 UTC
Labels: Branch-3.3.5a, Sub-Spells
