### ISSUE TITLE
Scripts/Quest: Rescue OOX-17/TN

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12295] opened 2014-06-17 10:34 UTC
Bugs:
1. This quest hasn't been updated with the 3.2.0. It should be shorter.
2. "Homing Robot OOX-17/TN" doesn't aggro nearby mobs.

Links:
Homing Robot OOX-17/TN - http://www.wowhead.com/npc=7784
Rescue OOX-17/TN! - http://www.wowhead.com/quest=648
Video of the quest(needed version) - https://www.youtube.com/watch?v=nRkxNk3YYD0
Video of the quest(current version) - https://www.youtube.com/watch?v=uJZYfAOPtsc

Core revision: 0f0cea104dcceb029fc74e12f60f913e55d267fc
Database version: TDB 335.53
Addons: Anticheat1
##

**Comment by tkrokli** [comment] 2017-07-10 11:53
TrinityCore rev. ed241a2fd6c8 2017-07-09 13:58:59 +0200 (3.3.5 branch) (Win64, Release, Static)
TDB 335.63 plus updates up to and including `2017_07_08_00_world.sql`

> 2. "Homing Robot OOX-17/TN" doesn't aggro nearby mobs.

That part of the issue is no longer true. All 3 Homing Robot OOX chickens aggro mobs easily, any random aggressive NPC within shooting distance from its path and the scripted temp spawn groups. I noticed it particularly when I lagged behind because I was looting and skinning the last killed attacking NPC, while the robot chicken ran along and got attacked again a little bit ahead of me, but still in viewing distance.
***
However, aggro is still part of this issue. I found a new issue in this escort event, whenever `Homing Robot OOX-17/TN` detects a random threat, it spams the chat log with something like 20 or more warning lines selected from its creature_text aggro lines:
```
Homing Robot OOX-17/TN says: Physical threat detected!  Evasive action!  CLUCK!
Homing Robot OOX-17/TN says: Threat analyzed!  Activating combat plan beta!  CLUCK!
Homing Robot OOX-17/TN says: CLUCK!  Sensors detect spatial anomaly -- danger imminent!  CLUCK!
```
(Lines are repeated about 10 times each.)

The practical issue here is that when those text lines are spammed from the exact moment when a mob attacks, the spam causes the attacking NPC to freeze and glide at running speed towards the Homing Robot until the text spam has ended. Is this a core issue or core script issue, seeing that the `creature_text` spam freezes the attacking unit while the `SAY_OOX_AGGRO` part of the script is looping?

Here is the `EnterCombat` part for `Talk(SAY_OOX_AGGRO);` of script `npc_OOX17` in the zone script:
https://github.com/TrinityCore/TrinityCore/blob/ed241a2fd6c8fd419d350210aa61eb1ad05b27bb/src/server/scripts/Kalimdor/zone_tanaris.cpp#L356-L359

I only noticed this last weekend while leveling a character with focus on Loremaster of Kalimdor. Unfortunately, I did not set up my logging for chat log to capture the exact spam sequence (I guess I was too annoyed with this glitch to do anything besides finishing the quest). I would need to run the quest again on a new char to collect that data. If and when I do so, are there any other types of data I should try to collect from the client or server? I should have tested this quest again, because I think most of the spawned group attacks worked without this text spam issue, but I don't remember if that is a 100% correct observation.

**Comment by tkrokli** [comment] 2017-07-17 12:07
The second part of my comment above is not caused by this quest script itself. It is currently an issue with all escort quests, as well as a general issue with strange NPC movement behavior (see issue https://github.com/TrinityCore/TrinityCore/issues/19998).

The aggro encounters only highlight the movement/waypoint handling issue by spamming the chat log due to repeated backwards + forwards steps made by the scripted NPC when nearby hostile mobs get aggro and try to attack. During the last weekend, I took the horde quest http://www.wowhead.com/quest=435/escorting-erland (https://db.rising-gods.de/?quest=435). This time, on aggro, the escortee (Deathstalker Erland) began moving like described in issue 19998. He moved one step back and one step forward repeatedly while slightly spamming the chat log with attack messages. The weird thing this time is that the attacking beast mirrored his moves while also not attacking, almost as if it evaded for each repeated movement (but with no evade message).

**Comment by offl** [comment] 2017-12-09 21:56
All three quests can be sniffed and today.

**Comment by tkrokli** [comment] 2017-12-09 21:59
Thanks for the info. Wish I could do it, but I don't have the necessary tools available.

**Comment by offl** [comment] 2020-05-21 00:42
> All three quests can be sniffed and today.

If anyone got something I can convert & update all 3 quests.
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=OOX#npcs

**Comment by illfated** [comment] 2020-05-21 09:29
Is it likely to be just as easy to sniff these quests in the new Classic Blizzard servers as it used to be on Blizzard servers before Legion or Warlords?

**Comment by Aokromes** [comment] 2020-05-21 09:52
> Is it likely to be just as easy to sniff these quests in the new Classic Blizzard servers as it used to be on Blizzard servers before Legion or Warlords?

it was updated on 3.2.0 to make it less anoying.

**Comment by illfated** [comment] 2020-05-21 09:58
> > Is it likely to be just as easy to sniff these quests in the new Classic Blizzard servers as it used to be on Blizzard servers before Legion or Warlords?
> 
> it was updated on 3.2.0 to make it less anoying.

Oh, OK. So to make sure that sniff contains the correct quest content for 3.3.5, any attempts at sniffing have to be done on Battle for Azeroth retail servers. I see.

**Comment by offl** [comment] 2020-08-12 16:15
Duplicate of #25239

**Closed by offl** 2020-08-12 16:15 UTC
Labels: Comp-Database, Priority-Low, Sub-Quests
