### ISSUE TITLE
[Crash] ObjectAccessor::AddCorpse

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#15593] opened 2015-09-24 19:22 UTC
I just had this crashlog.

http://pastebin.com/FsE45RXv

a3dbb0dd9caa1af61ff4e313ef1b75a98c17e30b
3.3.5

**Comment by Aokromes** [comment] 2015-09-24 19:57
No rows, useless crashlog.

**Comment by Pirricli** [comment] 2015-09-24 20:21
ummm... it's on debug mod like others... I don't know the reasons...

**Comment by DDuarte** [comment] 2015-09-24 20:27
This might be related to the guid PR by rooty.
The crashlog is not *that* useless since there's only two asserts in `AddCorpse`, still it would be better if the log was more complete.

**Comment by pete318** [comment] 2015-09-26 13:53
Just for completeness. Here's how it should have looked.

http://pastebin.com/qyw9giDy

**Comment by shenhuyong** [comment] 2015-09-26 14:28
confirmed

**Comment by Shauren** [comment] 2015-09-28 22:12
Fixed in cd27fd38b93884797c094a82dc7beb0498e2f124 (TODO: port to 3.3.5)

**Closed by Shauren** 2015-09-28 22:12 UTC
Labels: Branch-3.3.5a, Comp-Core, HasBacktrace
