### ISSUE TITLE
[3.3.5] Tailoring Embroidery procs

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#14726] opened 2015-05-20 02:41 UTC
http://wotlk.openwow.com/spell=55769
http://wotlk.openwow.com/spell=55642
http://wotlk.openwow.com/spell=55777

I personally tested http://wotlk.openwow.com/spell=55642, and it procs just randomly.
(I guess it procs on new auras or something like that)

9d12df69ca77a6c5522a0803d6aa5b8328575a13
##

**Comment by ccrs** [comment] 2015-05-20 02:42
I dont now if this is specific, or a general error on this type of procs.

**Comment by Tangol** [comment] 2015-05-20 11:08
Confirmed.
If you're a Warlock it's easier to reproduce by using Fel Armor. 
The HP regen activates the Lightweave Embroidery. It's like you're casting a healing spell on yourself.

**Comment by Keader** [comment] 2015-05-20 19:27
Confirmed.
At a time ago there was an issue about it, was closed by this merge: https://github.com/TrinityCore/TrinityCore/pull/11957
However ... the fix was removed by other commits some time later, causing the problem persists to this day.

**Comment by Keader** [comment] 2015-06-02 21:57
@robinsch You could take a look at it please?

**Comment by robinsch** [comment] 2015-06-02 22:05
If you complete the report. What should proc it, what should not. Missing infos.

**Comment by Keader** [comment] 2015-06-02 22:11
Active in cast spells. The problem is that is activating in Passive Heals, and heals over time too.

**Comment by robinsch** [comment] 2015-06-02 22:16
But then it's a general problem.

**Comment by Keader** [comment] 2015-06-10 14:10
No idea solution for this?

**Comment by tkrokli** [comment] 2015-06-10 15:08
@Keader : I think @robinsch means that we need to find a core solution to this issue by looking for a common denominator for all those caster classes and find out where the spell issue manifests. It needs to be fixed by making a change in one of the central scripts that affects all cast forms, regardless of class. I wish I knew how to find that part of the code, but I don't know the structure well enough. Sorry.

**Comment by Keader** [comment] 2015-06-10 15:11
In commit: #11957 fixed the problem. However it was removed some time later. I believe that there were side effects

**Comment by tkrokli** [comment] 2015-06-10 16:17
OK, have any of you tried to add back the changes in

https://github.com/TrinityCore/TrinityCore/blob/d86ff0814526cf1fefb1b37e487d9d414086eead/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L6204
```diff
@@ -6099,7 +6099,7 @@ void AuraEffect::HandlePeriodicHealAurasTick(Unit* target, Unit* caster) const
     uint32 procVictim   = PROC_FLAG_TAKEN_PERIODIC;
     uint32 procEx = (crit ? PROC_EX_CRITICAL_HIT : PROC_EX_NORMAL_HIT) | PROC_EX_INTERNAL_HOT;
     // ignore item heals
-    if (!haveCastItem)
+    if (!haveCastItem && GetAuraType() != SPELL_AURA_OBS_MOD_HEALTH)
         caster->ProcDamageAndSpell(target, procAttacker, procVictim, procEx, damage, BASE_ATTACK, GetSpellInfo());
 }
```
and also tried to find out how to add back the change inside the expanded subscript in

https://github.com/TrinityCore/TrinityCore/blob/d86ff0814526cf1fefb1b37e487d9d414086eead/src/server/game/Spells/SpellMgr.cpp#L821-L860
```diff
     /// Quick Check - If PROC_FLAG_TAKEN_DAMAGE is set for aura and procSpell dealt damage, proc no matter what kind of spell that deals the damage.
     if (procFlags & PROC_FLAG_TAKEN_DAMAGE && EventProcFlag & PROC_FLAG_TAKEN_DAMAGE)
         return true;

-    /// Any aura that has only PROC_FLAG_DONE_PERIODIC or PROC_FLAG_TAKEN_PERIODIC should always proc, if procSpell is correct or not is checked in Unit::HandleAuraProc
-    if ((EventProcFlag == PROC_FLAG_DONE_PERIODIC && procFlags == PROC_FLAG_DONE_PERIODIC) || (EventProcFlag == PROC_FLAG_TAKEN_PERIODIC && procFlags == PROC_FLAG_TAKEN_PERIODIC))
-        return true;
-
     if (procFlags & PROC_FLAG_DONE_PERIODIC && EventProcFlag & PROC_FLAG_DONE_PERIODIC)
    {
-        /// Aura must have positive procflags for a HOT to proc
        if (procExtra & PROC_EX_INTERNAL_HOT)
        {
+            if (EventProcFlag == PROC_FLAG_DONE_PERIODIC)
+            {
+                /// no aura with only PROC_FLAG_DONE_PERIODIC and spellFamilyName == 0 can proc from a HOT.
+                if (!spellProto->SpellFamilyName)
+                    return false;
+            }
+            /// Aura must have positive procflags for a HOT to proc
-            if (!(EventProcFlag & (PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_POS | PROC_FLAG_DONE_SPELL_NONE_DMG_CLASS_POS)))
+            else if (!(EventProcFlag & (PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_POS | PROC_FLAG_DONE_SPELL_NONE_DMG_CLASS_POS)))
                return false;
        }
-        /// Aura must have negative procflags for a DOT to proc
+        /// Aura must have negative or neutral(PROC_FLAG_DONE_PERIODIC only) procflags for a DOT to proc
+        else if (EventProcFlag != PROC_FLAG_DONE_PERIODIC)
-        else if (!(EventProcFlag & (PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG | PROC_FLAG_DONE_SPELL_NONE_DMG_CLASS_NEG)))
-            return false;
+            if (!(EventProcFlag & (PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG | PROC_FLAG_DONE_SPELL_NONE_DMG_CLASS_NEG)))
+                return false;
    }

    if (procFlags & PROC_FLAG_TAKEN_PERIODIC && EventProcFlag & PROC_FLAG_TAKEN_PERIODIC)
    {
-        /// Aura must have positive procflags for a HOT to proc
        if (procExtra & PROC_EX_INTERNAL_HOT)
        {
+            /// No aura that only has PROC_FLAG_TAKEN_PERIODIC can proc from a HOT.
+            if (EventProcFlag == PROC_FLAG_TAKEN_PERIODIC)
+                return false;
+            /// Aura must have positive procflags for a HOT to proc
            if (!(EventProcFlag & (PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_POS | PROC_FLAG_TAKEN_SPELL_NONE_DMG_CLASS_POS)))
                return false;
        }
-        /// Aura must have negative procflags for a DOT to proc
+        /// Aura must have negative or neutral(PROC_FLAG_TAKEN_PERIODIC only) procflags for a DOT to proc
+        else if (EventProcFlag != PROC_FLAG_TAKEN_PERIODIC)
-        else if (!(EventProcFlag & (PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_NEG | PROC_FLAG_TAKEN_SPELL_NONE_DMG_CLASS_NEG)))
-            return false;
+            if (!(EventProcFlag & (PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_NEG | PROC_FLAG_TAKEN_SPELL_NONE_DMG_CLASS_NEG)))
+                return false;
    }
```
to see if it works? **SpellAuraEffects.cpp** is relatively unchanged, but **SpellMgr.cpp** has changed a lot.
(Sorry that I don't have the diff values for SpellMgr.cpp - this is just a quick diff made "on the fly".)

**Comment by Keader** [comment] 2015-06-11 17:11
Only modifying the SpellAuraEffects.cpp works ... I do not know if you have side effects.

```diff

@@ -6099,7 +6099,7 @@ void AuraEffect::HandlePeriodicHealAurasTick(Unit* target, Unit* caster) const
     uint32 procVictim   = PROC_FLAG_TAKEN_PERIODIC;
     uint32 procEx = (crit ? PROC_EX_CRITICAL_HIT : PROC_EX_NORMAL_HIT) | PROC_EX_INTERNAL_HOT;
     // ignore item heals
-    if (!haveCastItem)
+    if (!haveCastItem && GetAuraType() != SPELL_AURA_OBS_MOD_HEALTH)
         caster->ProcDamageAndSpell(target, procAttacker, procVictim, procEx, damage, BASE_ATTACK, GetSpellInfo());
 }

**Comment by robinsch** [comment] 2015-06-11 19:02
Did you actual checked if those spells should not proc anything at all?

**Comment by Keader** [comment] 2015-06-11 20:14
Just by modifying above stops to activate with passive healing Fel Armor.
However continues by activating with Heal Over Time.

**Comment by tkrokli** [comment] 2015-06-11 23:51
Maybe we need to look at how `EventProcFlag` and `PROC_FLAG_DONE_PERIODIC` is handled in SpellMgr.cpp to find out if they enable something they should not enable. (Just a thought.)

**Comment by Keader** [comment] 2015-06-19 00:50
I still can not identify any side effects using https://github.com/TrinityCore/TrinityCore/issues/14726#issuecomment-111209717

**Comment by Killyana** [comment] 2015-06-19 01:17
Values in spell_proc_event seems wrong. Example for 55776.

**Comment by Keader** [comment] 2015-06-19 01:53
@Killyana Following your suggestion, I modified the spell 55640 (Lightweave) and is working here in my TC properly now.

```sql
UPDATE `spell_proc_event` SET `ProcFlags`='81920' WHERE `entry`=55640;

**Comment by Keader** [comment] 2015-06-29 22:25
Val'anyr, Hammer of Ancient Kings It is also turning the wrong way. Should enable only cast cures, but is activating with Heal Over Time (renew, rejuvenation, etc.)

http://wotlk.openwow.com/item=46017
http://wotlk.openwow.com/spell=64415

**Comment by Keader** [comment] 2015-08-20 17:50
No news?

**Comment by Aokromes** [comment] 2016-06-15 06:22
If anything here is valid, plz open a pr for this.

**Comment by tkrokli** [comment] 2016-06-16 19:14
@Keader : did you find out if SQL is enough or if C++ scripting is needed too?

**Comment by Keader** [comment] 2016-06-16 19:41
sql dont work... (work, but break something)

**Comment by Keader** [comment] 2016-11-01 12:53
@ariel- this already fixed by proc system?

**Comment by ariel-** [comment] 2016-11-02 07:33
Ok patch 3.2.2 says:

> WotLK Patch 3.2.2 (2009-09-22): This tailoring item enhancement will no longer trigger from the periodic healing granted by the warlock spell [Fel Armor].

Since this is the exception and not the rule, my best approach would be filtering Fel armor out with conditions.

**Closed** 2016-12-29 08:07 UTC
Labels: Branch-3.3.5a, Comp-Core, Feedback-FixOutdatedMissingWIP, Sub-Spells
