### ISSUE TITLE
Deathgrip ("Missle Speed")

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#565] opened 2011-05-16 21:53 UTC
Deathgrip should pull players much faster than it currently does.
Right now it almost pulls players in slow motion and they seem to "parachute" in the air during the spell and often times disappear briefly before reaching final destination.

Should not be effected by player to player latency?
##

**Comment by declart** [comment] 2016-01-10 18:21
I noticed that when I'm in bg , or duel , despite not having problems of latency Death 's Grip needs much time to bring my opponent in front of me , so if I make movements my target is brought to its previous position which I casted the Death's Grip.
Rarely it works properly .
Sometimes I click the icon of the Death's grip but the spell does not hit the opponent and then hits him after two seconds or more .
Not a problem of latency , because I can safely cast other spells.

so confirmed on rev https://github.com/TrinityCore/TrinityCore/commit/3e42d83e9cb86695a0467726f327599ff354293f

**Comment by Killyana** [comment] 2019-06-18 13:42
Fixed by https://github.com/TrinityCore/TrinityCore/commit/0197a2f990aa7c7eaf8637a2a5da7f43def9c4bd

**Closed by Killyana** 2019-06-18 13:42 UTC
Labels: Comp-Core, Sub-Spells
