### ISSUE TITLE
[master] Missing names from worldserver.conf

### ISSUE THREAD

**Issue by Maibenrai** [TrinityCore/TrinityCore#18273] opened 2016-11-19 12:17 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** 
Missing names (MonsterSight, GuarderSight, Guild.SaveInterval, Guild.UndeletableLevel) from worldserver.conf.

**Current behaviour:**
Missing name MonsterSight in config file /home/trinity/raidi/trinitycore/etc/worldserver.conf, add "MonsterSight = 50.000000" to this file
Missing name GuarderSight in config file /home/trinity/raidi/trinitycore/etc/worldserver.conf, add "GuarderSight = 50.000000" to this file
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Using DataDir /home/trinity/raidi/trinitycore/data/
WORLD: MMap data directory is: /home/trinity/raidi/trinitycore/data/mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: /home/trinity/raidi/trinitycore/data/vmaps
Missing name Guild.SaveInterval in config file /home/trinity/raidi/trinitycore/etc/worldserver.conf, add "Guild.SaveInterval = 15" to this file
Missing name Guild.UndeletableLevel in config file /home/trinity/raidi/trinitycore/etc/worldserver.conf, add "Guild.UndeletableLevel = 4" to this file

**Expected behaviour:**
Those should be added to worldserver.conf.dist.

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):**  
master
**TC rev. hash/commit:**  
d64da044d87d

**TDB version:**  
TDB 703.00

**Operating system:**  
Debian 8.6 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment] 2016-11-19 12:19
Duplicate of **Undocumented config options** #16859

**Closed by tkrokli** 2016-11-19 12:19 UTC

**Comment by Danie123** [comment] 2017-09-10 20:03
Good Day,

Wonder if someone can help me with this.

For a week now i seem to have this problem. i use win 10 64bit and all the programs as the wiki tells me with a fresh compiled server. for some reason the world.exe keeps telling me the following.

TrinityCore rev. 99346b78c5fa 2017-09-04 00:09:37 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file E:/Trinity/Build/bin/RelWithDebInfo/worldserver.conf.
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May 2017)
Using Boost version: 1.64.0
Updating Auth database...
>> Auth database is up-to-date! Containing 11 new and 97 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 7 new and 67 archived updates.
Updating World database...
Duplicate filename "E:/Trinity/TrinityCore/sql/updates/world/master/2017_04_19_00_world.sql" occurred. Because updates are ordered by their filenames, every name needs to be unique!
Could not update the World database, see log for details.

i have checked there is no duplicate. any help will be great.

Thanks in advance

**Comment by Aokromes** [comment] 2017-09-10 21:16
delete the repository and start again. also user issues don't belongs to tracker, instead forum or irc.
