### ISSUE TITLE
Missing Breathing Bar

### ISSUE THREAD

**Issue by Harrith** [TrinityCore/TrinityCore#24373] opened 2020-03-30 07:26 UTC
**Description:**

There are some places where player should have breathing bar but server doesn't have water at that place.

Here is a screenshot from Recast from Orgrimmar coords 1990, -4624, 25:

![OG](https://user-images.githubusercontent.com/40215976/77885329-22d7fe00-7267-11ea-935f-6a2c9d8f8506.png)

Ingame it looks like this:
![OG](https://user-images.githubusercontent.com/40215976/77886405-194f9580-7269-11ea-8edf-76ecb855c61f.png)

As you can see under the waterfall there should be water.
There are more places like this for example in Uldum -9289.477 -584.692 102

I checked parsing MH2O chunk in map extractor and it doesn't have water there and I also didn't find any WMO object around.

**Steps to reproduce the problem:**

1. .go 1989 -4628 21 1

**Branch(es):**

Checked in 4.3.4 (The-Cataclysm-Preservation-Project) but this probably affects master and 3.3.5 branch too.

**TC rev. hash/commit:** 

fe4ff01e30df59e97261bca045a7b3572e14fe07

**Operating system:** Win 10

**Comment by illfated** [comment] 2020-03-30 08:28
When you say "under the waterfall there should be water" -- have you verified that this spot activates the [ Breath ] bar for players?
I would think that waterfalls are considered more than 50% access to air, but I may have overlooked something.

**Comment by Harrith** [comment] 2020-03-30 08:38
Well, I didn't mean exactly the place under the waterfalls but I meant more the area around. I have just checked it on retail and I had there the breath bar.

**Comment by Harrith** [comment] 2020-03-30 08:44
Here I marked the area.

![77885329-22d7fe00-7267-11ea-935f-6a2c9d8f8506](https://user-images.githubusercontent.com/40215976/77892808-7b14fd00-7273-11ea-904e-f040f9113595.png)

**Comment by illfated** [comment] 2020-03-30 17:41
Well, I sort of get what you are saying. This is Orgrimmar after Cataclysm (hence more water than before). Myself, I have not used retail or master branch since before Legion, so I might be missing out on some changes.

Are you talking about tiles where the player is submerged in water, but does not get the breathing debuff bar?

**Comment by Ovahlord** [comment] 2020-03-30 20:08
Basically duplicate issue of https://github.com/TrinityCore/TrinityCore/issues/20221

It's literally the same issue, just inverted.
Also don't post issues of inofficial branches, such as mine here. Either reproduce it on master or 3.3.5 or.

**Comment by jackpoz** [comment] 2020-03-31 11:26
Closing as branch 4.3.4 is not supported anymore in this repo We can reopen the issue if you end up reproducing it in either 3.3.5 or master

**Closed by jackpoz** 2020-03-31 11:26 UTC
Labels: Branch-4.3.4

**Comment by Harrith** [comment] 2020-04-02 17:36
First I would like to apologize that I am writing into the closed topic, the second I would like to apologize that I did not test it in the master branch before, it works in master branch. But I would like to write what was the problem because maybe someone could face this problem too. 

According to https://wowdev.wiki/ADT/v18#MH2O_chunk_.28WotLK.2B.29 in SMLiquidChunk is layer_count, which is currently called "used" in code (also in master branch). These layers are not yet implemented. In System.cpp (in mapextractor), when parsing WH2O chunk there should be one more for loop which iterates over all layers, and pick correct adt_liquid_instance, because it should act like a array where layer is an index.

**Comment by Faq** [comment] 2020-04-02 19:05
If you willing to implement that part, feel free to open PR. :)

**Comment by Harrith** [comment] 2020-04-02 19:33
I can post code here or create PR in 4.3.4 branch (maybe in The-Cataclysm-Preservation-Project), but I don't know if I should create PR here because this issue is not present in Orgrimmar where I tested this.
