### ISSUE TITLE
[Quest/Bug 3.3.5] Into the Realm of Shadows!

### ISSUE THREAD

**Issue by Hitox** [TrinityCore/TrinityCore#10279] opened 2013-07-13 19:33 UTC
When you accept the quest you dont get into the Shadow realm!

http://www.wowhead.com/quest=12687
http://www.youtube.com/watch?v=9yaFEnfAhDQ

Tested on  b7cf456
DB: TDB 335.51

**Comment by Killyana** [comment] 2015-03-16 22:58
I cannot reproduce, as soon as I accept the quest I get the the aura.

**Comment by Rushor** [comment] 2015-03-16 23:22
two against it https://youtu.be/kaWVeq5V994 - closing
https://github.com/TrinityCore/TrinityCore/commit/f723b18164b07378ba4d149590ab87504fb14dc4

**Closed by Rushor** 2015-03-16 23:22 UTC
Labels: Comp-Database, Invalid-CannotReproduce, Sub-Quests

**Comment by yvomsx** [comment] 2018-01-29 06:27
@Rushor How can u reference to another issue while this is yet bugged?
/open.
