### ISSUE TITLE
World PVP Issues

### ISSUE THREAD

**Issue by TULOA** [TrinityCore/TrinityCore#20082] opened 2017-07-27 04:07 UTC
**Description:**

Hellfire Peninsula capture points and Eastern Plaguelands both don't function. You can sit in the area and it complains if not pvp flagged but no progress bar and no capture.

I cant find the spots to check for any issues with the scripts for this.
I have tried changing the worldserver conf gametype from 0 to 4 to 1 and none make a difference.

**Current behaviour:**

Stand in Broken Hill. No bar shows up. (Video to be here later. Recording right now)

**Expected behaviour:**

Should get the capture bar as was present in earlier versions as seen in a invalid bug report earlier.
Issue report I'm referring to: https://github.com/TrinityCore/TrinityCore/issues/17719
I know the cause is that it was a wrong server type. However the replies shown it working at one point before.

**Steps to reproduce the problem:**

1. Go to Broken Hill in Hellfire Peninsula

**Branch:**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 331e463de83e 2017-07-21 23:00:14 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  TDB 335.63

**Operating system:** Windows 10 Pro 64-Bit

**Comment by tkrokli** [comment] 2017-07-27 04:19
This issue has been solved in the 3.3.5 commit https://github.com/TrinityCore/TrinityCore/commit/28b3469e89f89a8c87fad06bad27800939abf0f5 (**[Core/WorldObject: Properly initialize position data for all types when initially creating them. Fixes some issues with PvP objectives not having the correct area ID set on initialization.](https://github.com/TrinityCore/TrinityCore/commit/28b3469e89f89a8c87fad06bad27800939abf0f5) Closes #20028.**)

(This issue is also practically a duplicate of issue #20028 , where the problem of capturing PvP objectives was brought up in https://github.com/TrinityCore/TrinityCore/issues/20028#issuecomment-316409441 .)

Please make sure your source code is up to date and search for existing issues if your issue has not been solved by the latest commit.

**Closed by tkrokli** 2017-07-27 04:19 UTC

**Comment by TULOA** [comment] 2017-07-27 04:21
I did search all I could and nothing mentioned it. I will give it a shot right now.

**Comment by tkrokli** [comment] 2017-07-27 04:26
Sure, it works just fine in all commits after https://github.com/TrinityCore/TrinityCore/commit/28b3469e89f89a8c87fad06bad27800939abf0f5 (including that commit). I have tested it myself and was able to capture all 3 objectives at least 1 time each day during the last 3 days. If you still get this issue, make sure you have deleted your game client Cache folder before you start the game. Not sure if retaking the quest is needed, but it should be possible to capture PvP objects in both vanilla and TBC areas from what I have tested. (I have not tested Northrend PvP objectives because I play alone on my own computer and I find it impractical to do PvP Battlegrounds and Wintergrasp alone.)

**Comment by TULOA** [comment] 2017-07-27 04:44
Ahh it is now present and working. Thanks for the tip. I meant to upgrade tonight anyway but its nice to see it working in either case.

**Comment by TULOA** [comment] 2017-07-27 18:32
@tkrokli It appears though it is working the server doesn't update the icon to actually be capture either right away or until its on the respective faction. It doesn't reset to neutral from what I'm seeing. And the capture area for the place is pretty big. I don't think you were originally able to capture it outside of the locations walls.

[http://tpras.com/HPOverlook.png](url)

The normal minimap shows this also.

**Comment by tkrokli** [comment] 2017-07-27 20:42
Well, that is a cosmetic issue. The player character is able to capture the required objectives, even if the minimap icons don't get updated. There are several other cosmetic issues like that, e.g. like the minimap quest icon for repeatable quests being a blue ❕ (exclamation mark) instead of a ❔ (question mark), and some quest target areas are somewhat off the mark on the map when using questing addons.

If you feel like opening a new ticket for this cosmetic issue, feel free to do so (although there could be something general covering it in open issues, I don't know).

**Comment by tkrokli** [comment] 2017-07-27 21:51
By the way, I just tested the 4 towers in Eastern Plaguelands and the my minimap (although using the Carbonite minimap) shows the correct faction color on the icons there. I will test Hellfire Peninsula (maybe even Terokkar Forest and Zangarmarsh) later to see if it works for me there or not.

**Comment by TULOA** [comment] 2017-07-27 22:56
Sure.

**Comment by tkrokli** [comment] 2017-07-29 17:06
TrinityCore rev. d24ce1739a79 2017-07-29 15:04:45 +0200 (3.3.5 branch) (Win64, Release, Static)

I have just finished trying to replicate your PvP minimap icon issue in both Hellfire Peninsula and Zangarmarsh. I tested this both on a GM account character and on a normal account character, both with and without addons enabled (Carbonite among others). I have also tested it on all the commits since my last update. I did not find any issues so I could not replicate your issue. I can only imagine that you have had either a configuration issue or some sort of game client addon issue or perhaps a game client Cache issue which did not allow you to see the correct icons in your minimap. Either way, it is not caused by anything in the TC source itself.

I could only find minor issues not directly related to the issues suggested on this page, like the Horde Field Scout and the Alliance Field Scout in Zangarmarsh not giving out any Battle Standards to capture the Twin Spire Graveyard, but that is because this feature is not yet implemented (NYI). It left me a bit miffed that nobody has taken the time to implement that feature yet, but I suppose it is not considered important enough even for 3.3.5, because it was mostly useful during The Burning Crusade when raiding Serpentshrine Cavern (the raid wing of Coilfang Reservoir) when level 70 was the highest level you could reach in-game. The zone-wide Twin Spire Blessing buff can not be attained unless GM characters cast that spell on a player or themselves to carry the Battle Standard to the Twin Spire Ruins graveyard to capture it.

I also noticed that my characters sometimes get unflagged for PvP without being AFK and still within the PvP objective area, but the occurrences were too uncertain and could in theory be caused by brief pauses when travelling between the PvP objects (outside PvP areas). Sometimes my characters also did not get unflagged when reaching `<Away>` status for idling too long during the capture attempt. Not sure if either of those two events could be caused by a missing Player status update or something else. Anyway, those events were too intermittent for me to actually report it as an issue, since I could not verify them repeatedly.

So far, as of current 3.3.5 source, I don't see a reason for reopening this issue, because the issues you reported don't seem to be caused by the source itself.
