### ISSUE TITLE
Sequence / Script Dwarven Mortar Team

### ISSUE THREAD

**Issue by Bluechen80** [TrinityCore/TrinityCore#22357] opened 2018-08-31 03:52 UTC
Description:
Im sure u all remember the funny Sequene in WoW where the Dwarven Mortar Team and the Shooters talk. I realy miss this on the Trinity Server.

Current behaviour:
Well the Dwarfs just stand there

Expected behaviour:
They should walk and should also play some sound samples u can see this here: 

https://www.youtube.com/watch?v=DPZ5uAR9lfI

and in a poor Quality here:

https://www.youtube.com/watch?v=lugkFfTfjMU

Maybe someone is in the mood to make a script.

TrinityCore rev. 8e4f677 2018-08-30 21:08:28 +0200 (3.3.5 branch)

TDB version: TDB 335.64 latest updates installed

Operating system: Windows 10
Using SSL version: OpenSSL 1.0.2p 14 Aug 2018 (library: OpenSSL 1.0.2p 14 Aug 2018)
Using Boost version: 1.68.0
MySQL client library: 5.6.39
MySQL server ver: 5.6.39-log

**Comment by Bluechen80** [comment] 2018-08-31 05:38
Mhh ill check this out this evening and let you know then.

**Comment by illfated** [comment] 2018-08-31 20:14
Just as I expected. Completing and handing in https://woehead.way-of-elendil.fr/?quest=5541 (**Ammo for Rumbleshot**) triggers the event (they are out of ammo until you deliver https://woehead.way-of-elendil.fr/?item=13850 (**Rumbleshot's Ammo**) to Hegnar Rumbleshot).

As far as I know (I can't remember if it worked differently on retail), this is how it is scripted in TrinityCore 3.3.5 and has been for several years.

See also issue [**[Bug]This...is...my...BOOMSTICK!**](https://github.com/TrinityCore/TrinityCore/issues/12582) #12582 which was solved and closed on May 24, 2015 (commit https://github.com/TrinityCore/TrinityCore/commit/cdb16ea27fe4776c8dc0add4d2828839f6565278).

Unless you have got documentation saying that this event should trigger on its own, I suggest we close this issue as "working as intended".

Maybe there could be an unknown bug specific to the German quest version, I don't know. Since I don't have a German version of the game client, I can't test that version of the quest & script.

TrinityCore rev. 8a45191e92a2 2018-08-30 23:24:52 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.41
Using CMake version: 3.10.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Comment by Bluechen80** [comment] 2018-08-31 21:00
@illfated ur absolutley right its 100% cosmetic

**Comment by offl** [comment] 2020-08-12 00:00
Event starts only when player turns in quest: https://youtu.be/ZcVm5P8y9gg?t=172
It's already implemented and works in 8a9cc0f65d8f, also event implementation is based on sniffs.

**Closed by offl** 2020-08-12 00:00 UTC
Labels: Priority-Cosmetic
