### ISSUE TITLE
[3.3.5] ICC / The Lich King: Infest

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22819] opened 2018-11-21 00:05 UTC
**Description:**
As the spell says: "Deals 6598 to 7402 Shadow damage to all enemy players within 50000 yards. In addition, the targets will take increasing Shadow damage per second. This effect is removed when the target has more than 90% health."

**Current behaviour:**
Infest works in these two cases:
Case 1: Healing one raid member with this debuff makes the debuff dissapear for the whole raid.
Case 2: (This one ocurrs usually in second phase) Healing one raid member with this debuff does not remove it till (some condition I still do not know, looks like something like "healing X members or X quantity of members").

**Expected behaviour:**
Healing one raid member should remove the debuff only for that member if he/she has more than 90% health

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
bc1f456

**Operating system:**
Win 8.1

**Comment by TheWinchesters** [comment] 2018-11-21 02:57
Update:
I think the problem is generic for some type of spells.
Forgemaster Garfrost (https://www.wowhead.com/npc=36494) casts Permafrost (https://www.wowhead.com/spell=68786) to all the members of the group and it is enough to cleanse the debuff on only one member to remove the debuff for everyone.

**Comment by Killyana** [comment] 2018-11-21 19:36
Related to https://github.com/TrinityCore/TrinityCore/issues/22051

**Comment by Ovahlord** [comment] 2018-12-22 15:30
Can be fixed via spell_proc and spellscript. Just create a proc entry that procs after healing spells have done all effects on the target, use a proc aurascript to remove the aura when targets health is >= 90%

**Comment by illfated** [comment] 2018-12-22 20:40
Just to nitpick - `when the target's health is > 90%`
(based on the spell description above and from https://woehead.way-of-elendil.fr/?spell=70541/infest)

**Comment by Shauren** [comment] 2018-12-22 22:37
@Ovahlord no, this is about general aura system bug, this spell is scripted

**Comment by TheWinchesters** [comment] 2018-12-24 06:18
I should change the name and description of this issue so it talks about the generic problem.
Which name should it be?

**Comment by Shauren** [comment] 2018-12-24 14:45
I'm pretty sure its already reported somewhere

**Comment by Killyana** [comment] 2019-06-22 14:50
Cannot reproduce on rev. 40b09e3df144
Probably fixed by https://github.com/TrinityCore/TrinityCore/commit/ec3cb05d7fbc5cef60d000af910dc39dd3af92bf

**Closed by Killyana** 2019-06-22 14:50 UTC
Labels: Branch-3.3.5a, Comp-Core, Priority-High, Sub-Spells
