### ISSUE TITLE
whirlwind hits twice with 2-handed weapons

### ISSUE THREAD

**Issue by bidibam** [TrinityCore/TrinityCore#9721] opened 2013-04-27 00:56 UTC
Whirlwind should only hit once per weapons wielded... right now its hitting with a two-handed weapon + off-hand (naked)

118ec195a64bf706b65bbf8c292232148ae84de9
##

**Comment by Keader** [comment] 2015-09-04 13:02
still dont work :(
on rev 02d014c69d53a4298db1747e9c848d10b84e91d2

**Comment by Keader** [comment] 2015-12-13 05:28
@robinsch can you take a look this?

**Comment by Keader** [comment] 2015-12-13 11:03
@jackpoz Can you confirm if 20e913efa685695a721e44931b4f939e6bfe7733 can be reverted? it shouldnt skip checks?! can you analyze and confirm with similar spells?!

**Comment by Shocker** [comment] 2015-12-13 23:37
I don't consider reverting the commit to be the correct approach. Probably an additional check for whirlwind should be done. Still, any other spells in this situation?

**Comment by Keader** [comment] 2015-12-14 01:14
@Shocker nop, i noticed this only gives problem

**Comment by Voidx** [comment] 2016-01-24 03:54
important bug here

**Comment by noryad** [comment] 2016-11-03 20:22
@ariel- Please this is a very important bug. Confirmed in aeb5762.

**Comment by ariel-** [comment] 2016-11-03 20:57
This is because triggered spells ignore equipped item check. If whirlwind should be the exception, it can be fixed with a SpellScript.

If this is the rule, triggered support for ignoring items shall be dropped.

**Closed** 2016-11-07 23:36 UTC
Labels: Comp-Core, Sub-Spells
