### ISSUE TITLE
DB/Quest: Recover the Cargo!

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25099] opened 2020-07-23 04:35 UTC
**Description:**

When using the **Salvage Kit** on **Shipwreck Debris**, nothing happens. No **Salvaged Strongbox** or **Mirefin Ambusher** appears.
There was a similar [issue](https://github.com/TrinityCore/TrinityCore/issues/22245) before.

**Expected behaviour:**

According to [Wowhead](https://www.wowhead.com/quest=11140/deprecated-recover-the-cargo#comments) comments, the item or the ambusher should appear.

**Steps to reproduce the problem:**

1. `.go creature id 23569`
2. `.quest add 11140`
3. Do the quest normally and try to salvage the **Salvaged Strongboxes**.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d974800e9d1e393ce3459ed8be4f4bd9defcc8f3

**Operating system:** Windows 7 Enterprise 64bit

**Comment by dr-j** [comment] 2020-07-23 08:31
I will find fix for this as already fixed this a while ago just needs 2 events swapping around as current script try’s to give credit after despawn change it so it gives credit before despawn and works

**Comment by dr-j** [comment] 2020-07-23 18:20
~~~sql 
DELETE FROM `smart_scripts` WHERE `entryorguid`=186283 AND `source_type`=1;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN(18628300,18628301) AND `source_type`=9;

INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(186283, 1, 0, 1, 8, 0, 100, 0, 42287, 0, 0, 0, 0, 64, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Shipwreck Debris - On Spellhit \'Salvage Wreckage\'  - Store Target List'),
(186283, 1, 1, 2,61, 0, 100, 0, 42287, 0, 0, 0, 0, 41, 0, 120, 0, 0, 0, 0, 20, 186278, 0, 0, 0, 0, 0, 0, 0, 'Shipwreck Debris - On Spellhit \'Salvage Wreckage\'  - Despawn Closest Gameobject \'Burning Wreckage\''),
(186283, 1, 2, 0,61, 0, 100, 0, 42287, 0, 0, 0, 0, 87, 18628300, 18628301, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Shipwreck Debris - On Spellhit \'Salvage Wreckage\' - Run Random Script'),
(18628300, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 85, 42289, 0, 0, 0, 0, 0, 12, 1, 0, 0, 0, 0, 0, 0, 0, 'Shipwreck Debris - On Script - Invoker Cast \'Summon Mirefin Burrower\''),
(18628300, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 41, 1000, 120, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Shipwreck Debris - On Script - Despawn'),
(18628301, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 85, 42288, 0, 0, 0, 0, 0, 12, 1, 0, 0, 0, 0, 0, 0, 0, 'Shipwreck Debris - On Script - Invoker Cast \'Summon Salvaged Lockbox\''),
(18628301, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 41, 1000, 120, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Shipwreck Debris - On Script - Despawn');

**Comment by offl** [comment] 2020-07-23 19:17
Duplicate of #25053

**Comment by offl** [comment] 2020-08-07 16:44
In order to fix this we need a spell script for effect 0 of spell https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=42287
To cast randomly https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=42288 on self or https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=42289 on self(nullptr if I'm not wrong since the spell has condition to target gameobject)

This sql is too needed to apply correct conditions and remove unneeded script
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 13 AND `SourceEntry` = 42287;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(13,1,42287,0,0,31,0,5,186283,0,0,0,0,"","Group 0: Spell 'Salvage Wreckage' (Effect 0) targets object 'Shipwreck Debris'"),
(13,2,42287,0,1,31,0,5,186283,0,0,0,0,"","Group 1: Spell 'Salvage Wreckage' (Effect 1) targets object 'Shipwreck Debris'"),
(13,4,42287,0,2,31,0,5,186278,0,0,0,0,"","Group 2: Spell 'Salvage Wreckage' (Effect 2) targets object 'Burning Wreckage'");

DELETE FROM `smart_scripts` WHERE `entryorguid` = 186283 AND `source_type` = 1;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (18628300,18628301) AND `source_type` = 9;
UPDATE `gameobject_template` SET `AIName` = "" WHERE `entry` = 186283;
```

**Closed** 2021-04-13 10:44 UTC
Labels: Comp-C++Script, Sub-Quests, Sub-Spells
