### ISSUE TITLE
[3.3.5] Core/Entities: Stealth can't be reactivated after Faerie Fire

### ISSUE THREAD

**Issue by VincentVanclef** [TrinityCore/TrinityCore#21632] opened 2018-03-15 13:46 UTC
**Description:**
Stealth can't be reactivated after being affected by Faerie Fire.

**Current behaviour:**

Since https://github.com/TrinityCore/TrinityCore/commit/9e0a343f729eb7e172c447dccb066f4f236aa11e , when you activate stealth while affected by https://woehead.way-of-elendil.fr/?spell=13752 (Faerie Fire), it says "immune" but you can never re-activate stealth. it continues to say "Ability is not ready yet" and Stealth is grayed out.

**Expected behaviour:**

Should be able to re-activate stealth.

**Steps to reproduce the problem:**

1. Apply https://woehead.way-of-elendil.fr/?spell=13752 (Faerie Fire) on rogue
2. Try to use Stealth
3. Wait hours, minutes or seconds, it doesn't matter. You cannot re-activate stealth.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/9e0a343f729eb7e172c447dccb066f4f236aa11e

**Operating system:** ubuntu

**Comment by tkrokli** [comment] 2018-03-15 14:42
By reading your issue (before & after I edited it) I presume it takes a server restart to reactivate Stealth for a rogue affected by Faerie Fire, is that correct?

**Comment by ariel-** [comment] 2018-03-15 14:54
Sounds a lot like #6457, but I can't see which commit closed it (the referenced commit has nothing to do with it)

**Comment by Persephone** [comment] 2018-03-15 15:13
@tkrokli  no a relog is enough but you cannot use stealth again until relog, really gamebreaking atm

**Comment by Jildor** [comment] 2018-03-15 15:19
I think it not caused by this commit, it's a old bug

**Comment by Nitair** [comment] 2018-03-15 20:51
I can agree with @Jildor , this bug is old

**Comment by tkrokli** [comment] 2018-03-15 22:02
Maybe mark this issue as a duplicate and close it, if this is covered in any of the hits found by the search term "rogue stealth" + open issue?
 (https://github.com/TrinityCore/TrinityCore/search?q=rogue+stealth&state=open&type=Issues&utf8=✓ )

**Comment by ariel-** [comment] 2018-03-15 22:19
#6457 which is autoclosed

**Comment by Langerz82** [comment] 2018-07-01 08:46
Faerie Fire doesnt look like it has the aura effect to disable stealth. If it does anyone know what function I should be looking at to correct the cooldowns?

**Comment by Langerz82** [comment] 2018-07-01 11:04
Think I have a solution, just needs a bit of testing first.

**Comment by Langerz82** [comment] 2018-07-01 11:12
SQL:
```
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('770', 'spell_dru_faeriefire');
```
See:
https://gist.github.com/Langerz82/86b332b776384f6e53d9d7bbd4c99990

**Comment by CraftedRO** [comment] 2023-01-24 08:41
835e2918319e Seems no longer valid (tested for druid prowl too):


https://user-images.githubusercontent.com/24683355/214246282-08a316a4-f692-4b65-aa49-298f7a5512af.mp4


https://user-images.githubusercontent.com/24683355/214246300-c5fd3be6-05e4-4819-8e3c-2511544689e8.mp4

**Comment by CraftedRO** [comment] 2023-01-24 09:04
835e2918319e Seems for that specific Faerie Fire from [Dazzling Longsword](https://www.wowhead.com/wotlk/item=869/dazzling-longsword)
 is still valid, if you try to cast stealth or even prowl while being debuffed you broke it and you can't never cast it:

https://user-images.githubusercontent.com/24683355/214250717-4d55e7c9-54d0-4579-abf1-ca3f563f7184.mp4

**Comment by CraftedRO** [comment] 2023-01-24 09:08
835e2918319e Seems for this specific [Faerie Fire](https://www.wowhead.com/wotlk/spell=13752/faerie-fire) from [Dazzling Longsword](https://www.wowhead.com/wotlk/item=869/dazzling-longsword)
 is still valid, if you try to cast stealth or even prowl while being debuffed you broke it and you can't never cast it:

https://user-images.githubusercontent.com/24683355/214250717-4d55e7c9-54d0-4579-abf1-ca3f563f7184.mp4

**Comment by CraftedRO** [comment] 2024-04-07 02:12
018e66bc914e3e39b01e15a51ad683a5e881d156 I'm back with a nice but working hack:
```sql
-- Condition to disable Stealth and Prowl while having Faerie Fire 13752 aura
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceGroup`=0 AND `SourceEntry`IN (1784,5215);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(17, 0, 1784, 0, 0, 1, 0, 13752, 0, 0, 1, 0, 0, '', "Can't cast Stealth while having Faerie Fire aura"),
(17, 0, 5215, 0, 0, 1, 0, 13752, 0, 0, 1, 0, 0, '', "Can't cast Prowl while having Faerie Fire aura");
```

**Closed** 2024-04-08 09:40 UTC
Labels: Sub-Entities, Comp-Core, Branch-3.3.5a, Feedback-FixHack
