### ISSUE TITLE
Core/Objects: Objects are not updated for nearby player

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26106] opened 2021-02-17 08:17 UTC
Now this is the problem:

We must do - Close off the Fuel Control Valve, the Regulator Valve and the Main Control Valve then use the control console again. 

When you come to the valve, you will not be able to click on it for the **account of a regular player** _but_ if you activate the valve for the **GM account**, then after that regular players will be able to activate the valve 
_(GM must activate all 3 valves )_

.quest add 900
[https://classic.wowhead.com/quest=900/samophlange](https://classic.wowhead.com/quest=900/samophlange)

3.3.5
rev. 0dee695

**Comment by offl** [comment] 2021-02-19 00:01
The problem is not-selectable flag is supposed to be removed instantly after player took the quest but objects are updated only if you re-enter the zone. In other words objects are not updated for nearby player
And of course they remain selectable if you abandon the quest

.go game id 4072
.gm off
.q a 900
re-enter the zone

If I'm not wrong this thing is as old as emu and may be related to how conditions are handled, it's just negative without specific quest id
```sql
SELECT * FROM gameobject_template WHERE data1=-1
```

DB part is fine

**Comment by offl** [comment] 2021-04-29 01:46
Duplicate of #24952

**Closed by offl** 2021-04-29 01:46 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-GameObject
