### ISSUE TITLE
[3.3.5] Core/Creature: Thaladred the Darkener

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#15915] opened 2015-11-29 04:41 UTC
core:https://github.com/TrinityCore/TrinityCore/commit/c1b4cd21f3debc2eb5e462c5adce659b558c7dc9
DB:TDB60
update:2015_11_27_00_world.sql
boss_kaelthas.cpp

haladred the Darkener（http://www.wowhead.com/npc=20064）Rend（http://www.wowhead.com/spell=36965） The effect was not used to the player.（http://www.wowdb.com/npcs/20064-thaladred-the-darkener#casts） http://wowwiki.wikia.com/wiki/Thaladred_the_Darkener

https://github.com/TrinityCore/TrinityCore/blob/9fe29de260b704603f40a8912c66dccf76fd0db8/src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp#L144

**Comment by w5860363** [comment] 2015-11-29 04:45
think it would work

// Thaladred the Darkener spells
	SPELL_PSYCHIC_BLOW = 10689,
	SPELL_SILENCE = 30225,
	++SPELL_Rend = 36965,

//Silence_Timer
			if (Silence_Timer <= diff)
			{
				DoCastVictim(SPELL_SILENCE);
				Silence_Timer = 20000;
			}
			else
				Silence_Timer -= diff;
			++//Rand_Timer
			++if (Silence_Timer <= diff)
			++{
				++DoCastVictim(SPELL_Rend);
				++Silence_Timer = 8000;
			+}
			++else
				++Silence_Timer -= diff;

**Comment by w5860363** [comment] 2015-11-29 04:51
https://github.com/TrinityCore/TrinityCore/blob/9fe29de260b704603f40a8912c66dccf76fd0db8/src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp#L144
// Thaladred the Darkener spells
	SPELL_PSYCHIC_BLOW = 10689,
	SPELL_SILENCE = 30225,
	+SPELL_Rend = 36965,
	// Lord Sanguinar spells
	SPELL_BELLOWING_ROAR = 40636,

https://github.com/TrinityCore/TrinityCore/blob/9fe29de260b704603f40a8912c66dccf76fd0db8/src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp#L933
			//Rand_Timer
			if (Silence_Timer <= diff)
			{
				DoCastVictim(SPELL_Rend);
				Silence_Timer = 8000;
			}
			else
				Silence_Timer -= diff;

Think it will work please forgive my English

**Comment by Kittnz** [comment] 2015-11-29 09:30
Can you make a PR for these changes?

**Comment by tkrokli** [comment] 2015-11-29 16:15
I don't know, but it just looks a little odd to me to replace Silence with Rend within the Silence_Timer.
Then again, in a PR this will be looked at by someone who is better suited than me to say if it is OK.

**Comment by w5860363** [comment] 2015-11-30 06:47
https://github.com/w5860363/TrinityCore/blob/w5860363-patch-10/src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp

**Comment by w5860363** [comment] 2015-11-30 06:49
@tkrokli I did not want to delete the original code, it is to add on the basis

**Comment by tkrokli** [comment] 2015-11-30 09:45
OK, I see. You just forgot to make a duplicate of those lines before you entered the new values.
What about the `Silence_Timer = 20000;` => `Silence_Timer = 8000;` diff, is that a double line too, or did you mean to add only 1 extra line with `DoCastVictim(SPELL_REND);` in it? (sorry, my brain is slow)

**Comment by w5860363** [comment] 2015-11-30 13:47
@tkrokli                
                //Silence_Timer
                if (Silence_Timer <= diff)
                {
                    DoCastVictim(SPELL_SILENCE);
                    Silence_Timer = 20000;
                }
                else
                    Silence_Timer -= diff;
                 +   
                +//REND_Timer
                +if (Silence_Timer <= diff)
                +{
                    +DoCastVictim(SPELL_REND);
                    +Silence_Timer = 8000;
               +}
                +else
                    +Silence_Timer -= diff;

                //PsychicBlow_Timer

**Comment by w5860363** [comment] 2015-11-30 13:48
//Silence_Timer
                if (Silence_Timer <= diff)
                {
                    DoCastVictim(SPELL_SILENCE);
                    Silence_Timer = 20000;
                }
                else
                    Silence_Timer -= diff;
                    
                //REND_Timer
                if (Silence_Timer <= diff)
                {
                    DoCastVictim(SPELL_REND);
                    Silence_Timer = 8000;
                }
                else
                    Silence_Timer -= diff;
				
                //PsychicBlow_Timer
                if (PsychicBlow_Timer <= diff)
                {
                    DoCastVictim(SPE

**Comment by w5860363** [comment] 2015-11-30 13:49
@tkrokli I would like to add a new one on the basis of the code.

**Comment by tkrokli** [comment] 2015-11-30 16:32
I see. Thanks for the update and example code. I am not a real programmer, but it looks to me as if the `Silence_Timer` condition is exactly the same, `if (Silence_Timer <= diff)` in both loops. Have you tested this to see if this works as intended, that there is a noticeable change in the spells cast by Thaladred, compared to before making this change? (I am unable to tell if your suggestion is different from my first example:
```diff
@@ -933,8 +934,8 @@ class boss_thaladred_the_darkener : public CreatureScript
                 //Silence_Timer
                 if (Silence_Timer <= diff)
                 {
                     DoCastVictim(SPELL_SILENCE);
                     Silence_Timer = 20000;
+                    DoCastVictim(SPELL_REND);
+                    Silence_Timer = 8000;
                 }
                 else
                     Silence_Timer -= diff;
```
Both the `if (Silence_Timer <= diff)` and `else`  `Silence_Timer -= diff;` is identical in your sample.
If you or someone else with coding knowledge could explain if our examples work differently, I would feel more comfortable about taking this further. Please notice: the TC developers recommend that the original author creates the PR when suggesting changes in the TC source. :)

**Comment by Rushor** [comment] 2016-02-04 08:27
@w5860363: open up a pr for these changes pls https://trinitycore.atlassian.net/wiki/display/tc/Creating+a+Pull+Request

**Closed** 2016-02-13 13:34 UTC
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Core, Feedback-PatchFix
