### ISSUE TITLE
First character camera stuck

### ISSUE THREAD

**Issue by dio85** [TrinityCore/TrinityCore#24258] opened 2020-03-06 17:13 UTC
If you create one new character, after the cinematic end, the camera set to the first camera position(maybe). and if you use .unaura command(character have one charm????) the server crash.
Unit.cpp 422 line. ASSERT(m_sharedVision.empty());  
Crashlog:

https://gist.github.com/dio85/c61ddcb4312ebbd0e2ba560832608a80

Branch: master

**Comment by illfated** [comment] 2020-03-06 17:16
Please add back the issue ticket template (or close this and open a new ticket, if you don't know how to edit) and fill in the required info, otherwise it is less likely that this will be seen as a real issue other than for you alone. TC often closes issue tickets like this one if not enough information is provided.

**Comment by dio85** [comment] 2020-03-06 17:19
this is enough information...

**Comment by MaxtorCoder** [comment] 2020-03-06 17:20
You need to follow the issue template in order for this to be a valid issue. So please add back the issue template.

**Comment by illfated** [comment] 2020-03-06 17:21
Oh WTH. I will check if that OP statement holds water on https://tcubuntu.northeurope.cloudapp.azure.com/ .

**Comment by illfated** [comment] 2020-03-06 17:28
Cannot reproduce. There is no instruction other than how to get the following response:

[18:23:48] TrinityCore rev. d1080af8db63 2020-03-04 20:59:04 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**[18:25:20] Syntax: .unaura #spellid
[18:25:20] 
[18:25:20] Remove aura due to spell #spellid from the selected Unit.**

**Comment by illfated** [comment] 2020-03-06 17:29
#please-close

**Comment by illfated** [comment] 2020-03-06 17:57
Full debug crash log (based on the link in the first ticket comment):
https://gist.githubusercontent.com/dio85/c61ddcb4312ebbd0e2ba560832608a80/raw/96d3846ac78fb9540095850e124855ce0d99997b/gistfile1.txt

**Comment by Shirasho** [comment] 2020-03-12 23:42
Unfortunately I do not have more information for you, but I can confirm this is an issue as it happened to me when I created my first character (a death knight).

**Comment by illfated** [comment] 2020-03-12 23:48
Seems to be an unusual case. Possibly also intermittent, but I don't know yet. Can be challenging to find out how to fix, if there are no steps to reproduce, or if not confirmed by others.

**Comment by Shirasho** [comment] 2020-03-13 03:55
I am doing a fresh reinstall (re-extracted files, database wipe, and recompilation) tomorrow. If I see this again, what information should I report and how can I get that information?

**Comment by illfated** [comment] 2020-03-13 07:17
I believe it will be good to get the debug crash log (although this does not seem to be an actual crash), also tell us if there is any difference between normal build & debug build in this case. Tell us also if this is regardless of race, faction and startup zone, because that part is not clear to all of us (at least not me).

**Comment by dio85** [comment] 2020-03-13 09:08
illfated commented 9 hours ago
Seems to be an unusual case. Possibly also intermittent, but I don't know yet. Can be challenging to find out how to fix, if there are no steps to reproduce, or if not confirmed by others.

You can reproduce, if you create one new character, my teory for this, the viewpoint what want to create is not empty, then cannot create one new at start. So maybe the latest camera position cant clear/empty this function first?

**Comment by illfated** [comment] 2020-03-13 13:12
I hope someone else will be able to reproduce your issue by testing your issue description. Myself, I barely have time to contribute at all in the 3.3.5 branch, due to the time I spend working and having some free time for myself otherwise. I also find it difficult to keep up with the master branch and its game client version, the master branch source as well as its issues.

**Comment by MaxtorCoder** [comment] 2020-03-13 13:13
I think the master branch always had that, never found a way to fix it.

**Comment by mcsescott** [comment] 2020-03-16 13:09
I can confirm this issue/similar issue.


**Description:**

When creating a new character, logging in for the first time the camera is "stuck" after the cinematic.

**Current behavior:**

Upon creating a new character and logging in for the first time, the camera gets stuck "in the air" and you have to log off and back on to view your character and NPCs.

**Expected behavior:** After the cinematic, you should see your character and be able to accept the first quest.

**Steps to reproduce the problem:**   Create a new character and log in.  Either watch the cinematic, or "esc" out of it.  You will not see your character, and must log off and back in to see your character.

----------

**Branch(es):** master

**TC rev. hash/commit:** 569f1c9

**Operating System:** Windows 10

**Comment by Shirasho** [comment] 2020-03-17 19:32
I've pretty much confirmed that you can reproduce this 100% of the time when skipping a cinematic on a new character. The camera will stay at the location it was in the cinematic instead of snapping to the character.

**Comment by illfated** [comment] 2020-03-17 20:41
@mcsescott : Thank you for demonstrating how the issue ticket template can be put to good use. That is exactly what we like to see here.

**Comment by Teppic1** [comment] 2020-03-17 21:46
I wasn't able to reproduce this with regular chars or a DK. Current build running on Debian 10.

I have camera files installed if that makes any difference. I did notice they're not all working properly though so this may be related.

**Comment by illfated** [comment] 2020-03-18 02:45
> I wasn't able to reproduce this with regular chars or a DK. Current build running on Debian 10.
> 
> I have camera files installed if that makes any difference. I did notice they're not all working properly though so this may be related.

@Shirasho : Could you check if your server camera files (extracted from the correct game client version) are not updated to match the current master branch, maybe that could be the cause of your issue?

**Comment by mindevis** [comment] 2020-03-19 15:04
There is this problem.
Video recorded by https://youtu.be/Ns5ncfwTB5Q
Client Version: 8.3.0.33528 (eng)

I tried re-unpacking the cards, to no avail.
This problem is reproducible on different OS versions.
Debian 10, Windows 10, Windows Server 2019

**Comment by Dev-Incognito** [comment] 2020-03-23 15:20
Can confirm this camera stuck on master. It's not related to older camera files. I have extracted newest stuff from client and problem is still there. @illfated

**Comment by illfated** [comment] 2020-03-23 19:26
Thank you for the feedback. Sorry that I can't provide any help here, I am stuck with 3.3.5 on a limited performance laptop at home.

**Comment by dio85** [comment] 2020-03-25 07:16
Yeah, and on server console give cannot create new viewpoint error.

**Comment by ImmortalusDev** [comment] 2020-03-27 08:39
Player::CreateViewpoint: Player 'Kaelynitha' (GUID Full: 0x08000400000000000000000000000013 Type: Player Entry: 0 Low: 19) cannot add new viewpoint!

**Comment by Aokromes** [comment] 2020-03-27 12:15
try removing cameras directory to se if it hangs or no.

**Comment by ImmortalusDev** [comment] 2020-03-27 12:20
Yep, it's working fully if you remove cameras directory.

**Comment by Teppic1** [comment] 2020-03-27 18:34
On 3.3.5 the camera files aren't working properly any more, for the dwarf starter zone for example nothing loads while it's fine for the human cinematic. I'm pretty sure this used to be fine so it's maybe related to the master issue.

**Closed** 2020-03-27 20:44 UTC
Labels: Branch-master

**Comment by dio85** [comment] 2020-03-28 08:02
Thanks Shauren!
