### ISSUE TITLE
[3.3.5][Spell] Jagged Knife 

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#14966] opened 2015-06-28 09:56 UTC
rev: https://github.com/TrinityCore/TrinityCore/commit/7c01638d45b3eaed7af124a43f21cc6d15407667

How it is:
npc=29836 cast http://wotlk.openwow.com/spell=55348 and http://wotlk.openwow.com/spell=55521
Both Spellvisuals look like cubes.
Proof:
http://i.imgur.com/WOm9mvj.jpg

How it should be:
Both Spellvisuals should look like knifes

**Comment by Aokromes** [comment] 2015-06-28 10:06
Confirmed, really really ancient bug.

**Comment by Trisjdc** [comment] 2015-06-28 22:27
The cause of the bug is SMSG_SPELL_GO missing CAST_FLAG_AMMO on the cast flags for this spell. I'm not aware of a general solution...

**Comment by Kinzcool** [comment] 2015-06-28 23:10
The spellvisuals look like cubes because no path is set for a model in SpellVisual.dbc. That being said, all the ones having a spell visual with no path set is going to have this problem.

``sql
(8908, "<Ammo - Basic>", "", 1, 1, 0.01, 100, 4, 1, 0);
(8909, "<Ammo - Preferred>", "", 1, 1, 0.01, 100, 5, 1, 0);
``

**Comment by Rushor** [comment] 2015-06-29 08:34
maybe all these ones have the same spelliconid?

**Comment by Rushor** [comment] 2015-06-29 18:09
one more spell=55550  maybe a more generic solution can  be found with the data of these 3

**Comment by Kinzcool** [comment] 2015-06-29 20:53
My comment above is your generic pattern to find all the spells that will have their spellvisuals represented as cubes.

**Comment by Rushor** [comment] 2015-12-11 22:52
oh and @Trisjdc, the hack sadly does not work :(

**Comment by Rushor** [comment] 2016-03-23 18:54
@Treeston concernig the pr, maybe you can try to add the attribute to all spells which look like freaking cubes :>

**Comment by Treeston** [comment] 2016-03-23 19:18
@Rushor feel free to, it's merged into mainline 3.3.5 now.

**Closed** 2016-03-23 19:17 UTC
Labels: Branch-3.3.5a, Comp-Core, Priority-Cosmetic, Sub-Spells

**Comment by Rushor** [comment] 2016-03-24 09:07
thx :)
