### ISSUE TITLE
[3.3.5][6.x][Pit of Saron] Scourgelord Tyrannus - Small Events

### ISSUE THREAD

**Issue by Gargarensis** [TrinityCore/TrinityCore#15949] opened 2015-12-06 14:26 UTC
rev: cdb5bd3eb78ea40fbd927c5662e1dad778bf12d5

A small event at the very beginning of the instance.
<b>Description</b>: 
The soldiers attacks the necromancers but Scourgelord Tyrannus kills them.
They are morphed into skeletons which attacks the players.
Tyrannus goes away while Sylvanas/Jaina and the other npcs takes care of the skeleton.
<b>Source</b>: <a href="https://youtu.be/5E_E-w3KxxY?t=17">0.17</a> - <a href="https://youtu.be/5E_E-w3KxxY?t=70">1.10</a>

<b>The Gauntlet</b>: https://github.com/TrinityCore/TrinityCore/issues/6155

A small event at the end of the instance.
<b>Description</b>
After killing Scourgelord Tyrannus there should be a small event involving Jaina (A) or Sylvanas (H) and other npcs.
The npcs are dancing until Sindragosa come and slay them.
Sylvanas/Jaina saves the players and head toward the Halls of Reflections.
<b>Source</b>: https://youtu.be/5E_E-w3KxxY?t=501

**Comment by offl** [comment] 2020-09-11 20:57
Duplicate of #25186

**Closed by offl** 2020-09-11 20:57 UTC
Labels: Comp-C++Script, Priority-Cosmetic, Sub-Instances
