### ISSUE TITLE
Worldserver crash/freeze 

### ISSUE THREAD

**Issue by jaxidor** [TrinityCore/TrinityCore#24747] opened 2020-06-03 22:37 UTC
**Description:**

call stack
call stack: https://i.imgur.com/pgZqIRE.png
https://i.imgur.com/YUmHMxy.png
breakpoint: https://i.imgur.com/IYMFvyD.png
console: https://i.imgur.com/G1qRNsd.png

I am running the server in relwithdebinfo and attaching visual studio debugging, not sure if that could cause any issues.

**Expected behaviour:**

Should not crash the worldserver

**Steps to reproduce the problem:**

unknown currently

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 0e9eb8e7f5ea+ 2020-06-01 23:43:38 +0200 (3.3.5 branch)

**Operating system:** Windows

**Comment by Shauren** [comment] 2020-06-03 22:46
You can use the debugger, great. But you left out the most important detail, call stack

**Comment by jaxidor** [comment] 2020-06-03 23:01
oh sorry https://i.imgur.com/pgZqIRE.png

**Comment by pedroevil51** [comment] 2020-10-24 22:14
I Have the same crash happening. 
Rev aff9cf4

**Comment by illfated** [comment] 2020-10-25 17:34
Unfortunate that there is so little information provided about the scenario where this crash happens. Difficult to find somewhere to start looking. Just hoping someone will post real debug crash logs and ideas about what event could cause this to happen. (Otherwise, it would be more productive to close this ticket.)

**Comment by acidmanifesto** [comment] 2021-02-02 20:40
Branch(es):

3.3.5

TC rev. hash/commit:

Parent: 1ff4a7e (DB/Quest: Fix CompletionText of 'The Balance of Nature')
Branch: 3.3.5
Follows: TDB335.64

Hitting this issue alot while checking on creature kill for about 2 minutes when working on the dynamic resurrection module on Trinitycore Custom Branch. Will see what logs i ha e to post in a bit

**Comment by acidmanifesto** [comment] 2021-02-02 20:44
[a2c659e8279a+_worldserver.exe_[1-2_11-47-50].txt](https://github.com/TrinityCore/TrinityCore/files/5914358/a2c659e8279a%2B_worldserver.exe_.1-2_11-47-50.txt)

**Comment by illfated** [comment] 2021-02-02 22:02
Made a gist file for you, with tab2spaces & EOL whitespace removal:

a2c659e8279a+ (TC custom) worldserver 2021-02-01 11-47-50

https://gist.github.com/illfated/c836e6df182d868432d2e8bae4e49a46#file-a2c659e8279a-_worldserver_-1-2_11-47-50_tabs_to_spaces-txt

Looks like some of your issues may be caused by NULL pointers:
```
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
00007FF6BF0CF75B  000000E8E38FA910  std::list<Group::MemberSlot,std::allocator<Group::MemberSlot> >::size+B  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\list line 1171
    Local std::list<Group::MemberSlot,std::allocator<Group::MemberSlot> >* this = NULL

00007FF6BF9B4E0B  000000E8E38FA940  Group::GetMembersCount+2B  C:\Users\MDic\Desktop\gits\TrinityCoreCustomChanges\src\server\game\Groups\Group.h line 248
    Local Group* this = NULL

00007FF6C06FC14A  000000E8E38FA9D0  Dynamic_Resurrection::IsInDungeonOrRaid+BA  C:\Users\MDic\Desktop\gits\TrinityCoreCustomChanges\src\server\game\Custom\DynamicResurrection\DynamicResurrection.cpp line 30
    Local Group* group = NULL
    Local Dynamic_Resurrection* this = 0x7FF6C2469F94
    Parameter Player* player = 0x2D00578F2B0
```

**Comment by illfated** [comment] 2021-02-02 22:04
a2c659e8279a does not seem to translate to a valid TC core rev. hash, indicating that too much is different from TC source.

**Comment by acidmanifesto** [comment] 2021-02-03 02:29
Its the dynamic resurrection module branch of trinity core custom i been working on.

**Comment by Shauren** [comment] 2021-02-03 10:51
@jackpoz is the original issue that respawn iterator invalidation thingy you fixed?

@acidmanifesto please don't post additional comments on crash issues that have completely different call stacks than the original (and your is 100% caused by your own custom code)

**Comment by jackpoz** [comment] 2021-02-03 15:31
> Hitting this issue alot while checking on creature kill for about 2 minutes when working on the dynamic resurrection module on

were you debugging for 2 minutes with a breakpoint and https://github.com/TrinityCore/TrinityCore/blob/184372500d1f2faa41d682bea04eb103487a4adb/src/server/worldserver/worldserver.conf.dist#L456 enabled ? if you are debugging then that setting should be set to 0

**Comment by jackpoz** [comment] 2021-02-03 20:22
Btw this issue has been most likely fixed already

**Closed by jackpoz** 2021-02-03 20:22 UTC
Labels: Branch-3.3.5a
