### ISSUE TITLE
[3.3.5/Quest] Protecting Our Own

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26767] opened 2021-07-31 11:43 UTC
### Description

The quest [Protecting Our Own](https://tbc.wowhead.com/quest=10457/protecting-our-own) works, but when using a [Rina's Bough](https://tbc.wowhead.com/item=29952/rinas-bough) on [Grove Seedlings](https://tbc.wowhead.com/object=184631/grove-seedling), the counter increases by 2. I know this is a minor problem, but solving such problems leads to the great goal of 100% server functioning.

### Expected behaviour

The counter should increase by 1 for each use of the [Rina's Bough](https://tbc.wowhead.com/item=29952/rinas-bough) on [Grove Seedlings](https://tbc.wowhead.com/object=184631/grove-seedling).

### Steps to reproduce the problem

1. Create an alliance character;
2. Go to Sylvanaar on Blade's Edge Mountains;
3. **.character level 65**
4. Take quest [Protecting Our Own](https://tbc.wowhead.com/quest=10457/protecting-our-own) from [Rina Moonspring](https://tbc.wowhead.com/npc=21066/rina-moonspring);
5. Try using a [Rina's Bough](https://tbc.wowhead.com/item=29952/rinas-bough) on [Grove Seedlings](https://tbc.wowhead.com/object=184631/grove-seedling) and make sure the counter increases by 2 for each use.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/caf68840b9bc6a435a59b2fb954c1fe779a27c66
TrinityCore rev. 2021-07-24 ‏‎12:46:23 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by offl** [comment] 2021-07-31 11:55
Duplicate of #14736

**Closed by offl** 2021-07-31 11:55 UTC
Labels: Branch-3.3.5a

**Comment by Freeman256** [comment] 2021-07-31 11:59
Oh sorry.
