### ISSUE TITLE
Quest: Protecting Our Own

### ISSUE THREAD

**Issue by tarnreich** [TrinityCore/TrinityCore#26173] opened 2021-02-27 08:49 UTC
**Description:**

When using using  [Rina's Bough](https://www.wowhead.com/item=29952/rinas-bough) on [Grove Seedling](https://www.wowhead.com/object=184631/grove-seedling) the quest registers two "Living Grove Defenders" being summoned.

**Expected behaviour:**

One charge/use only results in a single quest completion increment.

**Steps to reproduce the problem:**

1. Accept quest "Protecting Our Own".
2. Use quest item "Rina's Bough"on "Grove Seedling".

**Branch(es):**

3.3.5
(not tested on master)

**TC rev. hash/commit:** 

1ff4a7e75b56e1ad68d83f75b493a42ac1ae85c3

**Operating system:** 

Windows 10

**Comment by offl** [comment] 2021-02-27 10:25
Duplicate of #14736

**Closed by offl** 2021-02-27 10:25 UTC
