### ISSUE TITLE
Scripts/Ulduar: Mimiron P3Wx2 Laser Barrage not in sync with his body (hands) [$15 bounty]

### ISSUE THREAD

**Issue by Cyclone47** [TrinityCore/TrinityCore#21424] opened 2018-02-15 14:32 UTC
**Description:**
Mimirons spell:  P3Wx2 Laser Barrage is not in sync with his body (hands) on phase 4 of the fight. Most likely because his lower part of the body moves.

**Current behaviour:**
The laser barrage is shooting in wrong position. Not in line of mimirons hands (guns).

**Expected behaviour:**
The laser barrage is supposed to shoot out of mimirons hands (guns) on phase 4. Just like it works on phase 2.

**Steps to reproduce the problem:**
1. Attack Mimiron
2. Clear phase 1, see how the laser barrage works fine on phase 2.
3. Clear phase 3 and look how the laser barrage does not sync with mimiron on phase 4.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 4da9321d2bdd+ 2018-02-15 12:23:05 +0100 (3.3.5 branch) (Win64, Debug, Static) (worldserver-daemon)

**TDB version:**  TDB 335.63

**Operating system:** Windows Server 2008 R2

**Minor other issue:**
The loot Chest only remains for about 10 seconds and then despawns.

**Comment by Keader** [comment] 2018-02-15 22:54
It jus visual but not cosmetic
It break all phases after it :/

**Comment by ccrs** [comment] 2018-02-15 22:58
weird, I remember it working before

**Comment by Foereaper** [comment] 2018-02-15 23:13
It seems to be random honestly, some attempts we have done on the boss the barrage has worked like it should, but other times it breaks and he shoots behind himself. Not really sure what causes it.

**Comment by ariel-** [comment] 2018-02-16 00:59
Try after 29f7258dc824659cb2de81c5ff3b3b3853de2a8b

**Comment by Infinito47** [comment] 2018-02-16 08:20
@ariel- It feels a little better, but managed to reproduce the issue again:

See below image:
https://i.imgur.com/2XNNmVy.jpg

**Comment by Foereaper** [comment] 2018-02-16 09:09
It seems as if the barrage follows the bottom part of mimiron instead of the middle part that is actually shooting

**Comment by tkrokli** [comment] 2018-02-16 14:43
Hmm. That image (https://i.imgur.com/2XNNmVy.jpg) looks eerily similar to how the floodlight / spotlight gameobjects I have seen in Uldaman are inverted at random times. When they are inverted, they shine backwards through the wood columns / wooden support beams they are attached to, instead of shining outwards. (Maybe this is completely unrelated, it just had this immediate resemblance to me.)

**Comment by Infinito47** [comment] 2018-02-17 10:42
Created a bounty
https://www.bountysource.com/issues/55091771-scripts-ulduar-mimiron-p3wx2-laser-barrage-not-in-sync-with-his-body-hands

**Comment by Shauren** [comment] 2018-02-20 11:02
Thats master specific, on 3.3.5 there can only be a single CHANNEL_OBJECT

**Comment by Cyclone47** [comment] 2018-07-19 13:47
Anyone wants to take this challenge? I'll the bounty to $30 if so.

**Comment by Keader** [comment] 2018-08-14 00:18
Testing in rev 2ce57399c4bf442c68a1dd44e04380a67453077f i cant reproduce anymore :/

**Comment by Cyclone47** [comment] 2018-08-16 07:06
I'll test later!

**Comment by Aokromes** [comment] 2019-07-18 01:20
near 1 year without answer and keader said unable to reproduce, closing.

**Comment by Treeston** [comment] 2019-07-18 01:21
do we know what fixed it?

**Closed by Aokromes** 2019-07-18 01:20 UTC
Labels: Branch-3.3.5a, Comp-C++Script, Comp-Core, Feedback-WaitingResponse, Sub-Instances, Sub-Movement, Sub-Vehicles, bounty

**Comment by Aokromes** [comment] 2019-07-18 01:22
go figure.

**Comment by Treeston** [comment] 2019-07-18 01:23
reason i am asking is that somebody needs to claim the $15 on the issue

**Comment by ccrs** [comment] 2019-07-18 13:20
Probably the movement related stuff, cause this uses rotation right?
Not saying that I want the money, just pointing

**Comment by Keader** [comment] 2019-07-18 13:21
Yes, it uses rotation.
I realy dont know what exactly fixed it.
I still have a old core with this issue, i can help test if you send me what commits fixed it.

**Comment by Warpten** [comment] 2019-07-18 15:34
Good luck bisecting

**Comment by Aokromes** [comment] 2019-07-18 15:43
i can claim it to trinitycore and put it as new bounty xd

**Comment by Treeston** [comment] 2019-07-18 15:45
sounds reasonable if nobody claims in a week or so
