### ISSUE TITLE
Quest: Changing the Wind's Course

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24343] opened 2020-03-21 20:47 UTC
If you die while completing this quest (use the hammer), you will not be able to resurrect in any way and remain in the spirit.

https://www.wowhead.com/quest=13058/changing-the-winds-course

Branch(es): 3.3.5
TDB: 335.20021
Ubuntu 18.04
Rev. 40acf3c

**Comment by Killyana** [comment] 2020-03-21 20:53
The quest item use a spell with the effect: Apply Aura : Phase (256) so you corpse will be in this phase, but you spirit into a different one.
No Idea how to fix that, and this not a unique case.

**Comment by Rushor** [comment] 2020-03-22 20:47
can someone check that on retail?

**Comment by offl** [comment] 2021-04-07 15:58
Duplicate of #25996

**Closed by offl** 2021-04-07 15:58 UTC
Labels: Comp-Core, Sub-Phasing, Sub-Player
