### ISSUE TITLE
[3.3.5] High Uptime Diff

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#13849] opened 2015-01-03 15:51 UTC
I was have on server the 3 years old core from TC with 500-700 peoples online, uptime 80-100 it was okay. In full Alterac Valley was 120 diff.

But now, i'm using https://github.com/TrinityCore/TrinityCore/commit/51f5ce1b7364b730cb0bdabcfd6ad18794213f95

First Outpout Result: Diff with 1 player online is 50. 

Second Outpout Result: With 500-700 players i have 120-170 diff, its still okay.

Third Outpout Result: When etc. Alterac Valley start, there is so much spell at one time with full bg, the diff of server is 700-1200. It's terribly lagging.

**Comment by AriDEV** [comment] 2015-01-03 16:21
Time to Upgrade Server Hardware ? XD

**Comment by streetrat** [comment] 2015-01-03 16:25
3 years ago there wasnt even pathfinding in core i guess

**Comment by jackpoz** [comment] 2015-01-03 17:04
Performance are platform and hardware dependent so you should at least write more details about your platform and hardware. Profile the resources usage at high diff to see if you have a hardware bottleneck.
 You should also write the commit hash of the "3 years old core".

**Comment by leak** [comment] 2015-01-03 17:08
Also we're talking 350+ commits (educated guess as of lacking "old" commit hash), so somehow this needs to be narrowed down.

Could you give rev b17e3246fe769e6dc388612d5764150a184aef07 a shot?

**Comment by cshaaa** [comment] 2015-01-03 18:32
i think i had the similar problem.i didnot remember when i have update the core recently(about november ) then the server is so laging,but the old core(september 13) is okay.

**Comment by Frytiks** [comment] 2015-01-04 20:28
@AriDEV It's not problem in my hardware. I have 24 GB ram , and 4x Intel Xeon 2,4GHZ with ssd disk. 
@leak U think try this revert commit ?
@jackpoz That rev https://github.com/TrinityCore/TrinityCore/commit/4ca6939b8bd4ec51594c6e2425860aebfacfd8d5

**Comment by Frytiks** [comment] 2015-01-05 19:55
I can run perf, someone know how to ?

**Comment by leak** [comment] 2015-01-06 10:23
No, i mean updating your core to the revision i specified rather than updating directly to HEAD.

**Comment by Frytiks** [comment] 2015-01-06 11:15
I can't. I'm running now on new core.

**Comment by Aaron126** [comment] 2015-01-09 14:04
this isn't an issue, it's intentional.
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/Main.cpp#L390

**Comment by Frytiks** [comment] 2015-01-09 14:21
Thanks for info. I will try

**Comment by jackpoz** [comment] 2015-01-09 18:27
a graph of resources usage (CPU/Bandwidth/HDD) might help find the bottleneck

**Comment by Takenbacon** [comment] 2015-01-13 22:05
Probably boost locking.

**Comment by jackpoz** [comment] 2015-01-17 16:12
still no profiling data ?

**Comment by killradio** [comment] 2015-01-21 09:23
Ask ur players for test, compile b17e3246fe769e6dc388612d5764150a184aef07 version and check if its laggin same or not. This commit just before boost added to source.

**Comment by secreal** [comment] 2015-01-31 17:19
disable these spell and check your diff
try to enable it 1 by 1
![clipboard02](https://cloud.githubusercontent.com/assets/586113/5988934/cf98743c-a9a7-11e4-8394-9521333cb7d3.jpg)

**Comment by killradio** [comment] 2015-01-31 19:07
@secreal where did u get info about those spells are cause lags? Oo

**Comment by secreal** [comment] 2015-02-01 03:12
~~there is so much spell at one time with full bg, the diff of server is 700-1200. It's terribly lagging~~
I tried to cast spells one by one while looking at diff

**Comment by Aaron126** [comment] 2015-02-01 05:18
unless you're working on a toaster(and i mean that literally), casting any one of those spells wouldn't cause your time diff to flinch.

those spells do nothing special at all, I'd be more inclined to believe that they were the cause if they were AoE spells, but they aren't. So most likely what you encountered @secreal is just a coincidence, that or there's something wrong with your server

**Comment by secreal** [comment] 2015-02-01 06:25
Today I tried hunter auto shot, causing high diff, then 10 minutes later the auto shot again not make a diff height, if there are problems in the buff?

**Comment by Frytiks** [comment] 2015-02-02 10:34
Maybe u have right. I will try to test

**Comment by Frytiks** [comment] 2015-02-20 16:02
Someone told here WORLD_SLEEP_CONST IS 50. Then say me why the f*ck today i got http://prntscr.com/67kpaq

**Comment by Aaron126** [comment] 2015-02-22 18:49
it can be more or less, depending. but the server tries to keep the update interval at 50ms.

see https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/Main.cpp#L404

**Comment by DDuarte** [comment] 2015-04-27 22:06
Did this get fixed?...

**Comment by killradio** [comment] 2015-06-19 16:39
@DDuarte dunno why @Frytiks closed this issue, but my freshly compiled 335 still has random diff spikes with 2 players online.

**Comment by Frytiks** [comment] 2015-06-19 17:29
Because no more peoples for test it.

**Comment by secreal** [comment] 2015-06-19 17:37
anyone know the methods to find the causes of high diff? or some kind of tools, or something can reliable to check what causes of high diff?

**Comment by killradio** [comment] 2015-06-19 17:44
@Frytiks it seems like only you here have real server machine and enough online players for tests...
@secreal slow machine, corrupted db, wrong data in db, high online, cheaters/hackers, random bugs, broken logic in code, etc. etc. There is no single method for this.

**Comment by secreal** [comment] 2015-06-19 18:09
im already doing that kind of method... sometimes it so fun... trial and error....
but, this trinitycore even can tell the diff with number...
that makes me thinking of some kind of method... (still thinking...)

**Comment by DDuarte** [comment] 2015-06-19 18:42
![](http://i.imgur.com/lLed1UO.jpg)

Still waiting for a reliable way to reproduce the issue.

**Comment by Frytiks** [comment] 2015-06-19 20:42
How can we reproduce if we don't know it too

**Comment by jackpoz** [comment] 2015-06-20 18:57
what are your GridUnload and MapUpdate.Threads settings ? Try setting GridUnload to 0

**Comment by Frytiks** [comment] 2015-06-20 20:00
Sorry i cant test it now, because not much players

**Comment by L30m4nc3r** [comment] 2016-02-07 18:58
@jackpoz if set gridunload to 0 have problem with Doors in arenas.
After join in arenas not see door and run in center.

**Comment by Rushor** [comment] 2016-02-08 10:44
@Frytiks: this issue is still present?

**Comment by Aokromes** [comment] 2016-06-15 05:27
No answer after more than 4 months, closing.

**Closed by Aokromes** 2016-06-15 05:27 UTC
Labels: Branch-3.3.5a, Comp-Core

**Comment by Nelidon** [comment] 2016-08-24 08:47
400 players => 100 to 300 update diff time without the modification said above in Main.cpp.
6.x branch. This issue seems be on the two branches.

**Comment by Takenbacon** [comment] 2016-08-24 09:13
@Nelidon :laughing:

**Comment by Nelidon** [comment] 2016-08-24 09:59
@Taken give me your knowledge ^^

**Comment by jackpoz** [comment] 2016-08-24 18:55
could we get a Grafana shared report ?
