### ISSUE TITLE
6.x  Attacking (Specific) Mobs Causing Game Server / Client Freeze / Crash

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18027] opened 2016-10-01 03:41 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: Hey folks! Been a long while since I posted. Finally got my connection issues / patching issues resolved. Anyway, all was ok right up to the time of the issue at hand. I was hanging around the Brewfest outside Orgrimmar and decided to grind a little so I chose the battling elementals as my victims. When I killed the first one, the game locked up - spinning ball, and then the game became unresponsive and I had to close it / force quit. Reboot  and retest caused same thing so I was able to duplicate the issue. Server admin monitored same issue and spinning wheel occurred for him as well after I engaged mobs. Same issues occur when using alts; I have not tested on alternate mobs but will do so very soon.

**Current behaviour**: Game runs fine until I attack mobs. Then freezes / lags out til game is forced to shut down. 

**Expected behaviour**: Mobs should die, experience should be awarded. Loot should appear. (if applicable)

**Steps to reproduce the problem**:

1. Attempt to kill earth elemental / water elementals.
2. Game freezes til unresponsive prompt appears. 
3. Restart, lather rinse repeat.

**Branch(es)**: 6.x

**TC hash/commit**:  TrinityCore rev. c676e80c456e 2016-09-29 23:30:47 +0200 (6.x branch) (Unix, Release, Static)

**TDB version**:  6.04

**Operating system**:  Win 10, client. 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Nelidon** [comment] 2016-10-01 12:37
Wrong title.
Game freeze and not server side.

**Comment by BahDumbBugs** [comment] 2016-10-01 17:31
*HOWEVER* anyone who is in game also locks up.

**Comment by BahDumbBugs** [comment] 2016-10-01 17:37
Our server is equipped with a watchdog to automatically reboot when it crashes. So thats why it may sound confusing as opposed to a game vs. server issue.

**Comment by Nelidon** [comment] 2016-10-01 18:21
I invite you to change the title so because it's not the server which crash.
It happens only with earth/water elementals?

**Comment by BahDumbBugs** [comment] 2016-10-02 05:24
Id like to change the title, honestly, but it is a server issue. Our server owner has stated it as such.

**Comment by BahDumbBugs** [comment] 2016-10-02 08:18
So far its just the Teeming Waterguard and Furious Earthguard that are causing the crash. Killing other spawns and mobs in the area have not brought it down yet.

**Comment by jcmillions** [comment] 2016-10-03 08:46
I have a kind of similar issue. When I aggro Blackrock Worgs in Northshire Valley The client freezes and then my whole computer freezes, although it only freezes after killing your third or fourth Blackrock Worg. Tested on 3 different PCs.

**Comment by Aokromes** [comment] 2016-10-03 09:04
If the issue is the same of jcmillions it's duplicate ticket and client crash.

**Comment by Palabola** [comment] 2016-10-03 11:36
**Problem:**
- Emote states from (35,36,37,38) creature_template and creature_template_addon should be removed, since blizzard also didn't use this Emotes to make NPC's "attacking" visualy. (It can be keept on visual only NPC's).

Proper solution, implement fake attacking as it should.

**Comment by tkrokli** [comment] 2016-10-03 15:50
@jcmillions : the game client freeze problem from Blackrock Worg emotes is known and already reported in issue #15263 [**[6.x] Freeze on Emotes (35$ bounty)**](15263). It would be more interesting to verify if it is the exact same type of issue in Durotar with the elementals fighting each other (see Aokromes' comment).

**Comment by BahDumbBugs** [comment] 2016-10-03 21:08
Alright. Should I link this to the same issue as #15263 and close this one?

**Comment by tkrokli** [comment] 2016-10-03 21:46
Link is there already. Only close this issue if you are fairly sure that it is the same type of issue as #15263 .

**Comment by BahDumbBugs** [comment] 2016-10-03 22:02
I'll head out to Northshire Valley and test. Thanks @tkrokli

**Comment by tkrokli** [comment] 2016-10-03 22:05
GL & HF, you will need patience with that freeze issue in Northshire Valley.  :-P  ;-)

**Comment by Ovahlord** [comment] 2016-10-03 22:39
It happens whan you kill creatures that have a emoteId like the 1h attack of the guards. That's non-blizzlike and wrong. Remove that and script proper attack events and the crash will be gone.

**Closed** 2016-10-04 15:51 UTC

**Comment by BahDumbBugs** [comment] 2016-10-05 17:01
I was just thinking. Since the issue of Blackrock Worgs is a low level mob on the alliance side, and the battling Elementals are low level mobs on the horde side, are mirror images of the same problem - they may be related. By editing the emote states as @Palabola said - and subsequently fixing them, we can set sights on additional Horde/Alliance/Faction mirror issues. Right?

**Comment by tkrokli** [comment] 2016-10-05 20:33
@BahDumbBugs : it is OK to have a theory about cross-faction correlation, but you need more examples.
It is better to compare already reported issues and see if you find similarities then and act on that result (which usually is the case when TC team members close issues as duplicates).

**Comment by BahDumbBugs** [comment] 2016-10-07 06:42
@tkrokli - Understood. Thanks! :)
