### ISSUE TITLE
[3.3.5] On entering cave in durotar you can chat in tanaris

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#19761] opened 2017-05-15 13:00 UTC
**Description:**

There is a cave in Durotar where you when you are at a certain spot can talk in tanaris.

**Current behaviour:**

Spot in durotar makes you able to talk in tanaris

**Expected behaviour:**

Since we are in durotar we should only be able to talk in durotar, not tanaris

**Steps to reproduce the problem:**

1. go to dustwind cave in durotar

![schermafbeelding 2017-05-15 om 14 58 18](https://cloud.githubusercontent.com/assets/11842306/26058636/009c51fc-397f-11e7-91d1-db88d1630ccd.png)

2. go into the cave.. and at a certain point you see that you are in general tanaris

![schermafbeelding 2017-05-15 om 14 20 05](https://cloud.githubusercontent.com/assets/11842306/26058662/1f68d4b6-397f-11e7-8dbd-1e37abdbddc4.png)

![schermafbeelding 2017-05-15 om 14 20 14](https://cloud.githubusercontent.com/assets/11842306/26058681/2a08e82a-397f-11e7-9e9a-3e1da6b0d08c.png)

3. you are now able to speak with people in tanaris 👍 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. e036d2232dae+ 2017-05-10 02:41:50 +0200 (3.3.5 branch) (Unix, Debug, Static)

**TDB version:**  TDB 335.63

**Operating system:** Ubuntu server 16.04

**Comment by tkrokli** [comment] 2017-05-16 00:09
TrinityCore rev. 2ff76e828f7c 2017-05-14 21:40:11 +0200 (3.3.5 branch) (Win64, Release, Static)
TDB 335.63 + updates up to and including `2017_05_14_01_world.sql`

Confirmed.

![wowscrnshot_051517_233002](https://cloud.githubusercontent.com/assets/4903600/26084179/7895555e-39da-11e7-81dc-88d45d51b4eb.jpg)

**Comment by r00ty-tc** [comment] 2017-06-02 22:33
There's several areas where this happens.

One in Winterspring where you enter AV general chat (it thinks you're in Winterax Hold) is for sure one I remember.

 I did investigate a bit once. But didn't spent a serious amount of time on it.

**Comment by offl** [comment] 2020-09-12 23:58
Can't reproduce in aba0704

**Comment by illfated** [comment] 2020-09-13 11:39
Pretty simple to re-create still. I just walked right into "discovering" Lost Rigger Cove and entering Tanaris chat:

![WoWScrnShot_091320_133457](https://user-images.githubusercontent.com/38162891/93017102-5a90f300-f5c6-11ea-9119-94f3fbd49c15.jpg)


`TC> server debug`
TrinityCore rev. 14fa6c3a725f 2020-09-13 00:37:54 +0200 (3.3.5 branch) (Win64, Release, Static)
```
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.73.0
Using MySQL version: 50731
Using CMake version: 3.18.2
Compiled on: Windows 10.0.19041
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 3901434544 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.20082
TC> _
```

**Comment by illfated** [comment] 2020-09-13 11:43
Oh, right, including the chat log with `.gps` output at the end:
```
[13:34:45] You loot 10 Copper
[13:34:52] You gain 345 experience.
[13:34:52] Discovered Lost Rigger Cove: 345 experience gained
[13:34:52] Changed Channel: [1. General - Tanaris]
[13:34:52] Changed Channel: [3. LocalDefense - Tanaris]
[13:34:53] You loot 10 Copper
[13:39:50] Changed Channel: [1. General - Durotar]
[13:39:50] Changed Channel: [3. LocalDefense - Durotar]
[13:39:53] You loot 15 Copper
[13:39:53] You receive loot: [Loose Chain Cloak].
[13:39:56] Your skill in Defense has increased to 184.
[13:39:58] Changed Channel: [1. General - Tanaris]
[13:39:58] Changed Channel: [3. LocalDefense - Tanaris]
[13:39:59] Changed Channel: [1. General - Durotar]
[13:39:59] Changed Channel: [3. LocalDefense - Durotar]
[13:40:15] Changed Channel: [1. General - Tanaris]
[13:40:15] Changed Channel: [3. LocalDefense - Tanaris]
[13:40:21] Changed Channel: [1. General - Durotar]
[13:40:21] Changed Channel: [3. LocalDefense - Durotar]
[13:40:26] Changed Channel: [1. General - Tanaris]
[13:40:26] Changed Channel: [3. LocalDefense - Tanaris]
[13:40:30] Changed Channel: [1. General - Durotar]
[13:40:30] Changed Channel: [3. LocalDefense - Durotar]
[13:40:40] Changed Channel: [1. General - Tanaris]
[13:40:40] Changed Channel: [3. LocalDefense - Tanaris]
[13:40:41] Changed Channel: [1. General - Durotar]
[13:40:41] Changed Channel: [3. LocalDefense - Durotar]
[13:40:45] Changed Channel: [1. General - Tanaris]
[13:40:45] Changed Channel: [3. LocalDefense - Tanaris]
[13:40:46] Changed Channel: [1. General - Durotar]
[13:40:46] Changed Channel: [3. LocalDefense - Durotar]
[13:40:48] Changed Channel: [1. General - Tanaris]
[13:40:48] Changed Channel: [3. LocalDefense - Tanaris]
[13:40:49] Changed Channel: [1. General - Durotar]
[13:40:49] Changed Channel: [3. LocalDefense - Durotar]
[13:40:52] Changed Channel: [1. General - Tanaris]
[13:40:52] Changed Channel: [3. LocalDefense - Tanaris]
[13:40:53] Changed Channel: [1. General - Durotar]
[13:40:53] Changed Channel: [3. LocalDefense - Durotar]
[13:40:59] Changed Channel: [1. General - Tanaris]
[13:40:59] Changed Channel: [3. LocalDefense - Tanaris]
[13:41:07] You are indoors.
[13:41:07] Map: 1 (Kalimdor) Zone: 14 (Durotar) Area: 371 (Dustwind Cave) Phase: 1
[13:41:07] X: 860.597839 Y: -4720.015137 Z: 32.377415 Orientation: 4.403315
[13:41:07] grid[33,23]cell[4,1] InstanceID: 0
[13:41:07]  ZoneX: 52.151588 ZoneY: 26.886110
[13:41:07] GroundZ: 58.116879 FloorZ: 32.269043 Have height data (Map: 1 VMap: 1 MMap: 1)
```

**Comment by illfated** [comment] 2021-02-12 21:14
(ref. recent discovery in chromiecraft/chromiecraft#30)

**Comment by T1ti** [comment] 2024-11-18 20:19
Here is the issue, the cave below's bounds slightly overlap with the cave, the cave below's nameset 2 is Lost Rigger cove, nameset 2 is the active namesetindex of the dustwind cave WMO 
![image](https://github.com/user-attachments/assets/590219ce-6401-454f-b9a1-17410c8be55a)
![image](https://github.com/user-attachments/assets/e58b0af3-eec3-45d3-b69f-e8251b27d6b4)

**Comment by T1ti** [comment] 2024-11-18 20:22
![image](https://github.com/user-attachments/assets/db173e83-b98f-43ce-8436-9b5e3455f312)
This is specifically the location where the bug occurs, it's further confirmed because moving up in GM mode changes zone

**Comment by Shauren** [comment] 2024-11-18 21:33
eh, this is already fixed in master branch

**Closed** 2024-11-18 21:39 UTC
Labels: Sub-Maps/MMaps/Vmaps, Comp-Core, Branch-3.3.5a

**Comment by T1ti** [comment] 2024-11-18 21:48
> eh, this is already fixed in master branch

Does this fix only ensures we get the right nameset/adtId for the WMO below (Group hitModel) or does it also fixes that it finds the wrong model ?

**Comment by Shauren** [comment] 2024-11-18 21:51
It fixes model selection
