### ISSUE TITLE
Core/MMAPs: Issue with merge tiles

### ISSUE THREAD

**Issue by DoctorKraft** [TrinityCore/TrinityCore#26618] opened 2021-06-23 11:48 UTC
Hello !

**Description:**

In some case the pathfinding doesn't works well. Something are wrong in generation of tiles when extractor merging meshes. I'm gonna give you an example for this happen in others maps or etc..

**What Recast Demo output (when using files generated by extractor):**

![image](https://user-images.githubusercontent.com/25483209/123086384-a90bd180-d423-11eb-8e05-6ce4bd649f9d.png)

**What Recast Demo output (when using the debug output 3D):**

![c7784e562f](https://user-images.githubusercontent.com/25483209/123086878-38b18000-d424-11eb-8e9c-53fe9cadee20.jpg)

**The place IG where the issue exist in this example:**

![image](https://user-images.githubusercontent.com/25483209/123086300-8a0d3f80-d423-11eb-9caa-d9a62d1fd756.png)

**If you disable the TILES_PER_MAP (divison by little tiles and merging) the result are correct:**
But there should be a reason why it's like this, right? :)

![21402c6f5d](https://user-images.githubusercontent.com/25483209/123088716-5f70b600-d426-11eb-92be-666c61f26c0a.jpg)

**Expected behaviour:**

The npc should have a correct path

**Steps to reproduce the problem:**

* .go 3725.4756 3400.4158 6.4095 1877
* .npc add temp 68 (for example)
* .go 3771.6238 3412.1707 -2.7539 1877
* Target the previously spawn
* .mmap path

You gonna see a result like this:

![image](https://user-images.githubusercontent.com/25483209/123086126-55998380-d423-11eb-8c38-d1959824a93f.png)

**Branch(es):**

Master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/4621babae70f97adcfc4b749253e137d9f5d20ae

**Operating system:** 

Windows

**Comment by Aokromes** [comment] 2021-06-23 11:49
very likely this will be fixed when mmaps updates from 3.3.5a branch are cherry picked.

**Comment by Izidor** [comment] 2021-06-23 16:02
The issue is caused by wrong calcul of tiles bounding box.

You can find more informations added by the recast navigation guys here : https://github.com/recastnavigation/recastnavigation/commit/65b844170f702b1da492b9a83546a907abd599b1#diff-1005326e93b71f82aefe093d7c4a09290ddff353219dabda4bfe4133dd86cd31

Here is the fix i've done following how they do it in Sample_TileMesh.cpp of recast demo : https://gist.github.com/Izidor/2a8ba0d1ea925a3b107300bd062094e6

I can confirm on both recast demo tool and ingame its working.

**Comment by jackpoz** [comment] 2021-07-27 18:15
> The issue is caused by a wrong calculation of the tiles bounding box.

the wrong calculation is the usual floating point precision issues, good that the recast code handles it better

**Comment by jackpoz** [comment] 2021-07-28 10:29
for master: cherrypick https://github.com/TrinityCore/TrinityCore/commit/e615e2ddefd2c18b6dec8e08fb3d17580b64ea99

**Comment by Aokromes** [comment] 2022-03-26 20:21
picked already. @DoctorKraft

**Comment by funjoker** [comment] 2022-03-26 23:58
![image](https://user-images.githubusercontent.com/846960/160260953-f0b82730-e2d3-4373-ad01-4331eb06a48a.png)

![image](https://user-images.githubusercontent.com/846960/160260956-c6f4e526-542d-4f70-823e-535509f2daf3.png)

That's what i currently get

**Comment by jackpoz** [comment] 2022-03-27 09:05
Is that with the tiles being loaded ? "Load mmtile" button

**Comment by funjoker** [comment] 2022-03-27 12:06
yes

**Comment by funjoker** [comment] 2022-03-27 14:34
Ok something is wrong with recast demo atm. 
So stuff i found is incorrect

**Comment by funjoker** [comment] 2022-03-27 15:02
![image](https://user-images.githubusercontent.com/846960/160287313-d8350a89-2b5c-4ac4-a118-e715fd50c7d2.png)

![image](https://user-images.githubusercontent.com/846960/160287681-cf915732-e956-4535-a820-280431587bb6.png)

![image](https://user-images.githubusercontent.com/846960/160287710-0b98a45b-0fa8-4f34-bf42-8158cd31427e.png)


works for me now

**Closed** 2022-03-27 15:19 UTC
Labels: Sub-Maps/MMaps/Vmaps, Comp-Core, Branch-master
