### ISSUE TITLE
Gobject: The Raven's Claw

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22717] opened 2018-10-25 19:19 UTC
**Description:**
The gobject https://es.wowhead.com/object=185554/the-ravens-claw is used to summon Anzu.

**Current behaviour:**
You can summon the NPC Anzu as many times as you want.
**Expected behaviour:**
The gobject should be deactivated once Anzu is summoned.

**Steps to reproduce the problem:**
1. .add 32449 (Gobject needs this key)
2. .go gameobject 44722
4. Click the gobject several times

Branch: 3.3.5a
TC rev: 0a0312b
OS: Win 8.1

**Comment by RedSonja** [comment] 2018-12-19 23:00
confirmed

**Comment by TheWinchesters** [comment] 2019-01-31 04:11
This worked for me
```sql
UPDATE `gameobject_template` SET data3 = 86400000 WHERE entry = 185554;
```
I do not know if this could be a good solution to apply here.

**Comment by offl** [comment] 2020-09-21 11:50
Duplicate of #25481

**Comment by jackpoz** [comment] 2020-09-21 12:49
let's do the other way around

**Comment by jackpoz** [comment] 2020-09-21 12:50
https://github.com/TrinityCore/TrinityCore/issues/25481#issuecomment-696021124 has some useful info for a related error log triggered by this issue

**Comment by jackpoz** [comment] 2020-09-21 12:51
can a check be implemented with conditions ?

**Comment by Keader** [comment] 2020-09-21 13:07
InstanceScript has support to implement it

**Closed** 2020-09-22 00:07 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-GameObject
