### ISSUE TITLE
[3.3.5] Quest The Fel and the Furious (10613)  

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18785] opened 2017-01-10 14:01 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
If you use the Control Console nothing happens.

https://www.youtube.com/watch?v=_hCpLHyn4tI
http://www.wowhead.com/object=185057/fel-reaver-control-console

1. Click on the Control Console
**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  
TrinityCore rev. b42369389b20 2017-01-10 14:29:44 +0100 (335 branch)

**TDB version:** 
 TDB_full_world_335.62_2016_10_17.sql + updates

**Operating system:**  
Win 7 64Bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment] 2017-01-10 14:02
#6778

**Comment by Rushor** [comment] 2017-01-10 14:02
duplicate of https://github.com/TrinityCore/TrinityCore/issues/6778

**Closed by Aokromes** 2017-01-10 14:02 UTC

**Comment by Tauriella** [comment] 2017-01-10 14:06
damn :dancer:
