### ISSUE TITLE
Quest 'A Blue Light Bargain'

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19329] opened 2017-03-19 08:01 UTC
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
The quest ["A Blue Light Bargain" (ID 7652)](http://www.wowhead.com/quest=7652/a-blue-light-bargain) from [Derotain Mudsipper (ID 14567)](http://www.wowhead.com/npc=14567/derotain-mudsipper) in [Gadgetzan](http://www.wowhead.com/maps?data=440) is not supposed to have a "starting quest". It appears above Derotain's head as an exclamation point when it should simply be a yellow question mark *even though there isn't a "starting quest".* http://www.wowhead.com/quest=7652/a-blue-light-bargain

Evidence: https://youtu.be/AihYSbButXc?t=4444

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 3b27a06265e4 2017-03-16 02:55:48 -0300 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**
Windows 10 Client and Server

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment] 2017-03-19 08:34
A quest giver NPC having a question mark instead of an exclamation mark above its head, when you don't receive any quests in your quest log, means that the quest type is Repeatable (not daily or weekly).

I don't think your video is any actual "proof", because it is from a private server, uploaded (and presumably played) now in 2017, so I think we need to look for better evidence of how it looked on Blizzard servers back in 2010 (or at least before the quest became deprecated). One of the hints that the video is not old enough to be from 2005-2007 is that the vanilla game client only supports a 4:3 screen format while the screen itself is widescreen (notice how stretched it looks).

If the NPC is actually supposed to show a Question Mark and not an Exclamation Mark, this can be fixed in DB by changing the quest type or by checking the `conditions` for this quest and/or NPC.

**Comment by tkrokli** [comment] 2017-03-19 11:09
Some of the things that make it difficult to find documentation or a real video from Blizzard servers or even having sniffs of this from before Cataclysm (removed in patch 4.0.3a), is the fact that these "repeatable" quests were only available for players leveling up blacksmithing to 265 as well as being level 50+ in classic/TBC/WotLK. Not that it is very unique, but few enough that sniffs or video uploads of the NPC & his quests is almost non-existing. A possible reason for Derotain Mudsipper showing an exclamation mark for this quest could be that he is shown on the wowhead pages with both marks (quest starter + quest ender).

I was able to find wowwiki/wowpedia pages about getting the plans for Imperial Plate Armor, but none of them mentioning the quest "A Blue Light Bargain":
- http://wowwiki.wikia.com/wiki/Derotain_Mudsipper
- http://wow.gamepedia.com/Derotain_Mudsipper#Quests
- http://www.wowhead.com/quest=7652/a-blue-light-bargain#comments
- https://web.archive.org/web/20101027132903/http://www.wowhead.com/quest=7652
- https://web.archive.org/web/20110630150723/http://www.wowhead.com/npc=14567

**Comment by Aokromes** [comment] 2017-03-19 11:16
do you realize that video comes from a private server and cannot be used as evidence?

**Comment by tkrokli** [comment] 2017-03-19 11:19
I am aware of it (https://github.com/TrinityCore/TrinityCore/issues/19329#issuecomment-287602228), but I don't think @jerbookins knows that.

**Comment by Aokromes** [comment] 2017-03-19 11:23
i wanted to tell that to jerbookings xd

**Comment by tkrokli** [comment] 2017-03-20 12:54
@jerbookins : Do you know any other classic/vanilla high skill profession quests handled in the same way, which could be an indicator that your claim is valid?

Tagging @Killyana for comment as well (I hope you don't mind).

**Comment by jerbookins** [comment] 2017-03-21 00:12
@Aokromes @tkrokli Crap! No, I didn't notice that it wasn't from a live server. Sorry about that.

**Comment by jerbookins** [comment] 2017-03-21 00:13
@tkrokli Just to be clear, this quest is *not* repeatable.

**Comment by tkrokli** [comment] 2017-03-25 23:39
TrinityCore rev. 01aaafb0834d 2017-03-25 16:26:44 -0300 (3.3.5 branch) (Win64, Release, Static)
TDB 335.62 plus updates up to and including `2017_03_25_01_world.sql`

Confirmed. Quests which either used to have a 🔵 light blue or yellow ❔ Question mark seem to have been changed to show a blue or yellow ❕ Exclamation mark now. Unless this was NOT blizzlike before, these types of quest marks have now become broken.

- http://www.wowhead.com/quest=924/the-demon-seed
- http://wow.gamepedia.com/Quest:The_Demon_Seed
  - http://wow.gamepedia.com/Quest:Flawed_Power_Stone
  - object http://wow.gamepedia.com/Flawed_Power_Stone
  - http://www.wowhead.com/object=5619/flawed-power-stone
  - http://www.wowhead.com/object=5620/flawed-power-stones
  - http://www.wowhead.com/item=4986/flawed-power-stone
(gameobject entry 5619, 5620, 5621, 5622 ).

Flawed Power Stones are supposed to show a 🔵 light blue ❔ Question mark (quest is repeatable as long as you have lost your old power stone or you have waited 30 minutes for it to expire). This has now changed to look like a yellow ❕ Exclamation mark instead. This goes against the definition of such quests and their icons.

**Comment by Aokromes** [comment] 2017-03-27 04:55
broken or simply shows different color? very different.

**Comment by tkrokli** [comment] 2017-03-28 17:47
Well, the icons have changed completely. Different icon _and_ different colour, indicating different interpretation of the icon. A repeatable quest which also is just there to enable an item pickup does not need a full quest indicator.

**Closed** 2017-04-01 12:23 UTC
Labels: Branch-3.3.5a, Comp-Database, Sub-Conditions, Sub-Quests

**Comment by tkrokli** [comment] 2017-04-01 17:24
Hmm, I was going to check whether the quest "Chen's Empty Keg" from Brewmaster Drohn has become different too.
- http://www.wowhead.com/npc=3292/brewmaster-drohn
- http://www.wowhead.com/quest=819/chens-empty-keg
- http://www.wowhead.com/quest=821/chens-empty-keg
- http://www.wowhead.com/quest=822/chens-empty-keg

Although it is difficult to find images or videos of what the quest icons were, since it was removed in Cataclysm patch 4.0.3a.
