### ISSUE TITLE
Server Crash - ASSERTION FAILED: !aura->IsRemoved()

### ISSUE THREAD

**Issue by pedroevil51** [TrinityCore/TrinityCore#22306] opened 2018-08-24 01:45 UTC
**Description:**

Server random crash (i think), here is a print'screen of what shows
https://prnt.sc/km95l5
`Unit::_CreateAuraApplication ASSERTION FAILED: !aura->IsRemoved()`
Server is compiled on RelWithDebInfo, but there is no crashlog
I Left my server on a debug compile to see if there was any log when the crash happens, nothing at all

**Current behaviour:**

The server crashes, it shows this message on the screen.
https://pastebin.com/WjCidvxj - Crash 1
https://pastebin.com/KQLa1feW - Crash 2
Dump 1 - http://www.mediafire.com/file/8mxwbao8nzx8b3c/unknown_LiveServer11.exe_%5B24-8_7-3-49%5D.dmp
Dump 2 - http://www.mediafire.com/file/a2r5466gsu6cn50/unknown_LiveServer11.exe_%5B24-8_3-28-35%5D.dmp/file

**Expected behaviour:**

Not crash :/ 
**Steps to reproduce the problem:**

1. Server running about 7-8 hours, random crash every few hours

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/d2d9f470c388a80d395e9a49a860ceb0b7e27fd3

**Operating system:** Windows Server 2012 R2

**Comment by Aokromes** [comment] 2018-08-24 01:47
update your core before reporting crashes, one crash was fixed after your revision.

**Comment by pedroevil51** [comment] 2018-08-24 01:55
@Aokromes Was? what crash ?

**Comment by pedroevil51** [comment] 2018-08-24 01:58
Also, maybe its related to this > https://github.com/TrinityCore/TrinityCore/issues/21810
a person on the thread had the same crash

**Comment by illfated** [comment] 2018-08-24 04:39
Your error message is referenced in
https://github.com/TrinityCore/TrinityCore/blob/0e4a49b0a4c86eb4a2d0d128e24bc8aaabb47e31/src/server/game/Entities/Unit/Unit.cpp#L3288-L3301
Then again, there could be a spell issue causing your crash.
Without a crash log, it will be hard to tell what causes it.

Since you referenced #21810 , do you think it happens with Anub'arak in Azjol'nerub?

**Comment by pedroevil51** [comment] 2018-08-24 05:50
@illfated Can't be as azjol nerub is disabled on my server.

**Comment by jackpoz** [comment] 2018-08-24 08:09
do you get any other message on the console other than that ?

**Comment by pedroevil51** [comment] 2018-08-24 10:26
@jackpoz Just got a crash , and it created a dmp and a crash log 
https://pastebin.com/WjCidvxj - Crash 1
https://pastebin.com/KQLa1feW - Crash 2
Dump 1 - http://www.mediafire.com/file/8mxwbao8nzx8b3c/unknown_LiveServer11.exe_%5B24-8_7-3-49%5D.dmp
Dump 2 - http://www.mediafire.com/file/a2r5466gsu6cn50/unknown_LiveServer11.exe_%5B24-8_3-28-35%5D.dmp/file

**Comment by pedroevil51** [comment] 2018-08-24 10:27
Even trying to play with my friends its hard, server keeps crashing

**Comment by pedroevil51** [comment] 2018-08-24 10:32
https://github.com/TrinityCore/TrinityCore/issues/21980
https://gist.github.com/Gooyeth/fbbae9815c04abd98daa2eb9cc2d7907 
Maybe related?

**Comment by pedroevil51** [comment] 2018-08-24 10:47
News everyone, sounds like the crash is related to > https://wotlk.evowow.com/?spell=47574#used-by-npc
Freezing Cloud
At least thats what i see when i debug, i disabled the dungeon just for testing, to see where this goes

**Comment by jackpoz** [comment] 2018-08-24 11:01
the first 2 crashlogs are missing symbols, it means the .pdb files have been moved or are not on the same machine where you built worldserver. please copy the .pdb files in the same folder as where worldserver.exe is, it should work then

**Comment by illfated** [comment] 2018-08-24 14:40
Maybe related to issue #21856 (**Crash on _CreateAuraApplication**) ?

**Comment by Hir0shi** [comment] 2018-09-14 15:19
CONFiRM

**Comment by illfated** [comment] 2018-09-14 19:36
@Hir0shi : Please include your TC rev. hash/commit when you confirm issues (edit your existing message). Without a commit hash (mine is currently TrinityCore rev. 67e839b6bf46 2018-09-13 23:38:10 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) before updating), a "confirm" message is not as useful as it could have been with a commit hash. Tracking an issue is easier with a commit hash from those who confirm the issue. And no, I haven't had this crash myself, but I try to help other users who are less used to how the TC issue tracker works.

**Comment by Jildor** [comment] 2018-09-15 07:57
If you have a crash, put your crashlog, this can help mora than "Confirm" text ;)

**Comment by Winchester1987** [comment] 2018-09-17 03:27
Crashlog: https://pastebin.com/i9wG2Sax
Rev: ce46a0d53c3dbd6d2837020686e3880d98c545ed

**Comment by TheWinchesters** [comment] 2018-09-19 20:26
I have disabled Azjol'Nerub and Utarde Pinnacle on my server since I posted the crashlog here and I have not had more crashes related to this for now.
I do not know if this means something or it's just pure chance.

**Comment by Aokromes** [comment] 2019-01-07 11:07
@TheWinchesters can you reopen azjol again to see if you get new crash after latest changes to get better details and you can close it again if it crashes?

**Comment by TheWinchesters** [comment] 2019-01-07 20:43
Yep, I will come back when I have a crashlog.

**Comment by TheWinchesters** [comment] 2019-01-12 20:01
I had a crash 3 times. (crash log is the same)
Basic scenario for them:
Fighting Anub'arak in Azjol'Nerub, I just let him summon a looot of Carrion Beetles and I was casting Pound (https://www.wowhead.com/spell=59433) and Mass Dispel (https://www.wowhead.com/spell=32375/mass-dispel) every now and then.

Detail of each crash:
1st time: Not sure what exactly happened, server crashed
2nd time: I casted Pound (https://www.wowhead.com/spell=59433) to see what happens and server crashed, but this could not be possible in a normal encounter.
3rd time: Same than the 2nd one.

Crash log: https://gist.github.com/TheWinchesters/568b95609f70782e5944818b07546e07

I will be trying more times to see if I can find something else.

**Comment by Faq** [comment] 2019-01-13 05:12
so those mobs are moving slow, like was mentioned here https://github.com/TrinityCore/TrinityCore/issues/22304

**Comment by TheWinchesters** [comment] 2019-01-16 16:04
@jackpoz Is my comment above enough or do I need to try something else?

**Comment by jackpoz** [comment] 2019-01-17 07:10
I'll try to repro the crash and let you know if I need anything else

**Comment by jackpoz** [comment] 2019-01-19 15:51
I reproduced the crash in Elwynn Forest casting spell 59433 to a wolf standing very close (dist < 2.4 y)

**Comment by jackpoz** [comment] 2019-01-19 16:42
Fixed in https://github.com/TrinityCore/TrinityCore/commit/518e6299ca08a362bc3709daaaa5e5d5633d1bf1

**Closed** 2019-01-19 16:41 UTC
Labels: Branch-3.3.5a, Comp-Core, HasBacktrace
