### ISSUE TITLE
Hunter Spell: Eyes of the Beast (1002)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21514] opened 2018-02-27 08:32 UTC
**Description:**
http://wowwiki.wikia.com/wiki/Eyes_of_the_Beast

**Current behaviour:**
Casting Eyes of the Beast does not work. It does appear to channel the spell but I do not gain control of my character.

**Expected behaviour:**
Should allow me to see through my pet's eyes and control my pet. Basically MC for my pet.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
b197529f1e89

**TDB version:**
335.63

**Operating system:**
Windows 10

**Comment by ariel-** [comment] 2018-02-27 21:43
Duplicate of #21471 (and fixed)

Update your core and DB

**Closed by ariel-** 2018-02-27 21:43 UTC
Labels: Branch-3.3.5a, Sub-Spells
