### ISSUE TITLE
[Crash] Player::_SaveSpells  0x0000000000c91fb5 in Player::_SaveSpells (this=this@entry=0x7fff6d2f9000, trans=...) at /home/server/TrinityCore/src/server/game/Entities/Player/Player.cpp:20045

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#14792] opened 2015-05-28 20:52 UTC
Worldserver crashed with the following crashlog:

http://pastebin.com/JkafvPnP

51c9bc75aa20f21bbbb0ff3e7eb73d3ae455704b

The first time I see it.
I have Crossfactionbg, passive anticheat and transmogrification patches.

**Comment by DJScias** [comment] 2015-05-28 20:54
Revision is about 5 days old, I suggest pulling the latest source and updating your core and database.

**Comment by Voidx** [comment] 2015-05-30 17:15
Have you had any crash more?

**Comment by Frytiks** [comment] 2015-05-30 17:37
Its CFBG issue. Custom patch crash.

**Comment by tkrokli** [comment] 2015-05-30 19:07
... and thereby not caused by clean TC source.

**Comment by Runico** [comment] 2015-05-30 21:26
As far as i know CFBG is popular script, so any update on it would be great

**Comment by tkrokli** [comment] 2015-05-30 21:31
To say that a script is popular is not the same as to say that it is supported by TrinityCore.

**Comment by Aokromes** [comment] 2016-01-22 16:52
This crash is still valid?

**Comment by Rushor** [comment] 2016-02-05 09:46
no answer after 14 days - closing

**Closed by Rushor** 2016-02-05 09:46 UTC
Labels: Comp-Core, HasBacktrace

**Comment by sucklifex** [comment] 2016-10-20 14:19
http://paste.ubuntu.com/23353832/
