### ISSUE TITLE
Regarding mounts

### ISSUE THREAD

**Issue by AKees2011** [TrinityCore/TrinityCore#15269] opened 2015-08-12 21:46 UTC
Everytime i try to learn the new draenor mounts on core 81abfe93bb96e5a769dc855f06fdc7578b352b39

they are white horse instead for example "Core hound"

**Comment by tkrokli** [comment] 2015-08-12 21:49
Duplicate of issue  #15113 [6.2] Mount spell effect issue

**Closed** 2015-08-12 21:51 UTC
