### ISSUE TITLE
Crash without crashlog

### ISSUE THREAD

**Issue by jimteck** [TrinityCore/TrinityCore#21246] opened 2018-01-16 06:33 UTC
Sometimes there is crash core, but there is no log crash

Branch(es):

3.3.5

TC rev. hash/commit:

TrinityCore rev. 1847555c8c9e+ 2018-01-15 15:42:41 +0100 (3.3.5 branch) (Win64, Release, Static)

TDB version: 335.63

Operating system: Windows Server 2012

<a href="http://piccy.info/view3/11966800/e36801b2a8346189722267a9fa7c0f0b/1200/" target="_blank"><img src="http://i.piccy.info/i9/de26c1ede780b10168b449cbe4eef282/1516084370/39051/1213344/FbmoFQwQN5M_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-01-16-06-32/i9-11966800/800x500-r" target="_blank"><img src="http://i.piccy.info/a3/2018-01-16-06-32/i9-11966800/800x500-r/i.gif" alt="" border="0" /></a>

**Comment by jackpoz** [comment] 2018-01-16 07:33
does the console show anything when that happens ?

**Comment by jimteck** [comment] 2018-01-16 07:59
"does the console show anything when that happens ?" no i just atack  mod 31147 and 31139 creature agro 38493 (Argent Crusader) and core freez and crash. No log and no what happend in console/

**Comment by jackpoz** [comment] 2018-01-16 13:48
Please rebuild in RelWithDebInfo or even better in Debug mode

**Comment by Infernales** [comment] 2018-01-16 14:24
@jackpoz Most likely he has some kind of curve custom script. This is indicated by "+" in the revision.
@jimteck To test the crash use a clean TrinityCore, the developers don't support custom code.

**Comment by Seyden** [comment] 2018-01-16 17:47
There is a way to reproduce crashes like this... In my case i triggered this kind of crashes when i set attributemask Triggered in spell_proc. Its a special case with this attributemask crash.. had this spell_proc settings

SpellId: 207316
SpellFamilyName: 15
SpellFamilyMask2: 4096
ProcFlags: 81920
SpellPhaseMask: 2
AttributesMask: 2
Chance: 100

**Comment by daddycaddy** [comment] 2018-01-16 18:39
hi there
I have this crash also, it happens randomly, no crash log, both files are 0 size
thanks

**Comment by jackpoz** [comment] 2018-01-16 18:52
@Seyden spell 207316 doesn't exist on 335 branch

**Comment by Seyden** [comment] 2018-01-16 19:06
I have this crash on master too, thats what i meant, sry :)

**Comment by jackpoz** [comment] 2018-01-16 19:28
could you find how to reproduce steps on 335 too ?

**Comment by jackpoz** [comment] 2018-01-16 19:45
@jimteck I tried ".npc add 19668", attacked the NPC and I got a triggered assert in the console
>D:\wow\TrinityCore\src\server\game\AI\CoreAI\PetAI.cpp:546 in PetAI::CanAttack ASSERTION FAILED:
me->GetCharmInfo()

It created correctly both .dmp and .txt file. Is this a case where you get empty files too ? As asked above, please build in RelWithDebInfo and try again.

**Comment by daddycaddy** [comment] 2018-01-19 00:50
hi there,
I'm building with RelWithDebInfo  and I have no crash logs or dmp logs
it just crashes...

**Comment by jackpoz** [comment] 2018-01-19 07:32
@daddycaddy nothing in the console either ?

**Comment by daddycaddy** [comment] 2018-01-19 17:51
hi there,
there is nothing in console either, just the crash popup, that's all
thanks

**Comment by tkrokli** [comment] 2018-01-19 18:07
Since you get that "no crash logs" issue on a server, maybe it is caused by any Virtual Machine setup or disk caching in the OS.

**Comment by daddycaddy** [comment] 2018-01-19 18:18
hi there,
I had other crashes that made logs, so I don't think it's caused by OS and I do not use virtual machine for my server
Only this crash doesn't leave a trace

PS: look at this issue: https://github.com/TrinityCore/TrinityCore/issues/21258 that was reported by me, as u can see for that crash it made logs, so it's not a machine or OS issue, this crash just doesn't write any output and the crash from issue 21258 happen in between crashes that make no logs

**Comment by Treeston** [comment] 2018-02-01 15:06
is this the same as #21247?

**Comment by jackpoz** [comment] 2018-02-02 13:25
no clue, https://github.com/TrinityCore/TrinityCore/issues/21247 correctly creates a crashdump and crashlog while this issue doesn't (at least on the author's machine). every crash is supposed to create a crashlog, if it doesn't that's an issue

**Comment by jackpoz** [comment] 2018-02-04 20:49
Please try after https://github.com/TrinityCore/TrinityCore/commit/95a76a83fcbad0e52c6013697544e3c5691e7e24

**Comment by Aokromes** [comment] 2018-09-17 11:17
no answer after more than 6 months, closing, if this bug is still valid open a new ticket on one updated core.

**Closed by Aokromes** 2018-09-17 11:17 UTC
Labels: Branch-3.3.5a
