### ISSUE TITLE
[3.3.5] Arcane Missiles/drain life do not keep target in combat

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18259] opened 2016-11-16 12:37 UTC
**Description:** Hitting an enemy with mages arcane missiles do not keep them in combat. 

**Current behaviour:** (Tell us what happens.) ^

**Expected behaviour:** (Tell us what should happen instead.) You should be kept flagged as in combat. 

**Steps to reproduce the problem:**

1. Cast arcane missiles on target.
2. Notice enemy does not stay in combat.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/400a69bf9efb227e8734668f07ed2f3f2863ba47

**TDB version:**  TDB 62, updated as of https://github.com/TrinityCore/TrinityCore/commit/400a69bf9efb227e8734668f07ed2f3f2863ba47

**Operating system:**  ubuntu 14.04

**Comment by Aokromes** [comment] 2016-11-16 12:38
the 2nd part is blizzlike.

**Comment by Persephone** [comment] 2016-11-16 12:39
Really? didnt know :P

**Comment by Aokromes** [comment] 2016-11-16 12:40
http://wowwiki.wikia.com/wiki/Channeling

Currently, all channeling spells (except Arcane Missiles) technically cause periodic damage, which means that they behave like damage over time spells for the most part. As a result, those spells cannot crit and do not cause interruption. In addition, they have only one line of sight check at the cast of the spell; as soon as the spell hits the target, the caster does not need to maintain LoS in order to keep the channel active.

**Comment by Persephone** [comment] 2016-11-16 12:44
K makes sense, wasnt aware of that. But the part about not triggering combat is legit :P

**Comment by Aokromes** [comment] 2016-11-16 12:58
that's why i said "the 2nd part" :P

**Comment by Persephone** [comment] 2016-11-16 15:28
Update: its more like half way through they go out of combat etc, so rogues can go into stealth which is a really annoying advantage

**Comment by Persephone** [comment] 2016-11-16 18:27
adding this:

case 689:
			case 7269:
				spellInfo->AttributesCu |= SPELL_ATTR0_CU_NEGATIVE;
				break;

in spellmgr.cpp LoadSpellinfocorrections fixed both drain life and arcane missiles

**Comment by ariel-** [comment] 2016-11-17 00:30
Weird. Arcane Missiles should already be marked as negative by core (SPELL_EFFECT_SCHOOL_DAMAGE is considered negative effect)

**Comment by amaroc** [comment] 2017-04-18 09:54
This problem also related to Penance http://www.wowhead.com/spell=47540/penance
Can we add "dummy" effects, wich trigger combat,  when player cast spells like:
Penance
Drain Life
Arcane Missiles

or it is a bad hack?

**Comment by ariel-** [comment] 2017-04-18 18:36
> or it is a bad hack?

The whole positive/negative stuff is a giant hack (because there's no good generic way to classify spells), what we've is a best effort, however there are edge cases where the spell isn't assigned correct possitivity status, and causes weird bugs.

Btw, arcane missiles is already set as negative (can't link commit right now, but it fixed the spell downscaling when targetting lower lever enemies, as if it were a buff)

**Comment by Jildor** [comment] 2017-12-09 09:51
I can only reproduce the problem with Arcane Missile, and only vs another player, with NPCs I think works fine.
869affa89300c24b85896a050b58241714786454

**Closed** 2017-12-13 20:46 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Spells
