### ISSUE TITLE
[6.x]Char Creation Client Crash

### ISSUE THREAD

**Issue by alexandre433** [TrinityCore/TrinityCore#17903] opened 2016-09-05 15:27 UTC
**Description**: I recompiled the core 6.x with the new updates, and I added the .sql's to the db world.
I logged in just to the character selector, created an orc and it crashed my game.

**Current behaviour**: After creating an orc and relogging, it crashed my game and it sends a bunch of error codes to my worldserver.exe
It happened to me before when i tried to enter with a blood elf BUT it had no error after the char was created, only when I tried to log in.

**Error Log**: https://gist.github.com/alexandre433/a7a4a9a7e835a577dc4da8d4575274f2

**Branch(es)**: 6.x

**TC hash/commit**:  cfaf8fc34fa9edddc4c02bc375fd340ba7a2cd66

**TDB version**:  6.04

**Operating system**:  Windows 10 64 bit

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by alexandre433** [comment] 2016-09-06 22:09
up

**Comment by tkrokli** [comment] 2016-09-06 22:27
Please tell us which character **class** (or classes)  cause(s) crash in your game client. TC has had a hunter class issue causing a 6,x/7.x  game client crash. It could be a class issue, but I don't know without more info.

**Comment by alexandre433** [comment] 2016-09-06 22:46
The ones that I tried was:
- Human, Warrior
- Orc, Warrior
- Blood Elf, Mage
- Pandaren, Monk - This one didn't crash anything, just printed out error codes on the worldserver.exe

**Comment by alexandre433** [comment] 2016-09-07 21:21
up

**Comment by tkrokli** [comment] 2016-09-08 04:10
If the characters have not been used yet, try emptying the characters database (or delete that DB), then see if it works differently or still crashes your game client if you try creating a new character.

Notice that we already know about the issue where the game client freezes in the human starter area if you kill [Blackrock Worg](http://www.wowhead.com/npc=49871/blackrock-worg) creatures.

**Comment by alexandre433** [comment] 2016-09-09 00:25
Still crashes :/

**Comment by alexandre433** [comment] 2016-09-16 16:01
up

**Comment by alexandre433** [comment] 2016-09-16 16:04
tkrokli I did what you said, now I cannot even start my worldserver.exe because of the db characters..

**Comment by tkrokli** [comment] 2016-09-16 16:49
Are you sure your worldserver.conf is set to default and that your source dir is up to date?
If you use default CMake settings, Worldserver should be able to create or update your world DB, depending on the current state of your world DB. DB Auto Updater usually works for me without issues.

**Comment by alexandre433** [comment] 2016-09-18 15:08
It worked now, i deleted it and added it again and it worked.

**Comment by tkrokli** [comment] 2016-09-18 16:55
OK, good to hear that. Few things are as annoying as when you can't even log in because of client crash.

BTW, is your original issue solved, or is this only that your servers work when all  is deleted & rebuilt?

**Comment by alexandre433** [comment] 2016-09-18 21:18
My original issue isn't solved :/

I checked again just to be sure but when I create a character human it crashes my client :/

**Comment by Aokromes** [comment] 2016-09-18 21:48
If it's human start zone only, then duplicate of #15263

**Comment by alexandre433** [comment] 2016-09-18 22:18
Dude you need to read and not rush things https://github.com/TrinityCore/TrinityCore/issues/17903#issuecomment-245119587 these are what I tried and crashed, I said I just teste with a human to check if it still crashes or not..

**Comment by Aokromes** [comment] 2016-09-18 22:28
You said here https://github.com/TrinityCore/TrinityCore/issues/17903#issuecomment-247853040 it's fixed minus human character, so clarify.

**Comment by alexandre433** [comment] 2016-09-19 13:22
No I did not.

I just simply checked if the error was fixed or not with ONLY a character human, I did not check the others but I will and I'll let you know.

**Comment by Shauren** [comment] 2016-09-20 06:24
Very important question to determine whether this is a duplicate issue or not
Does it crash when clicking "Enter world" button OR after loading finishes and you can see npcs around you?

**Comment by alexandre433** [comment] 2016-09-20 07:10
After I press "Enter World" it loads it then the npc's appear for 1 second and it crashes.

**Comment by Shauren** [comment] 2016-09-20 08:32
Then it IS a duplicate of #15263

**Closed by Shauren** 2016-09-20 08:32 UTC

**Comment by alexandre433** [comment] 2016-09-20 17:28
It is not because I do NOT even move my own character AND it's not ONLY a human, it's also with orcs and blood elfs

**Comment by tkrokli** [comment] 2016-09-20 17:59
If you have had a crash with a human character, even if you try to log in with other races, the issue will still manifest because of crash using your human character. You will have to retry using any race but human, while still rebuilding your characters DB & deleting Cache etc. on your game client.

**Comment by Shauren** [comment] 2016-09-20 18:26
You don't have to move to get it to crash, noone ever said that.
