### ISSUE TITLE
[3.3.5][Quest] "It's All Fun and Games" stopped working

### ISSUE THREAD

**Issue by hlainin** [TrinityCore/TrinityCore#17507] opened 2016-07-04 06:16 UTC
**Description**: The eye pursues the player, it needs to stand still.

**Current behaviour**: the eyes pursuing the player when he was attacked

**Expected behaviour**: the eyes should stand still

**Steps to reproduce the problem**:

1. quest 12887 and 12892
2. http://www.wowhead.com/quest=12892/its-all-fun-and-games

**Branch(es)**:
3.3.5

**TC hash/commit**:  
TrinityCore rev [1ad7321](https://github.com/TrinityCore/TrinityCore/commit/1ad73212dca0cf8a829d15ffdbcc4cd611e64d4e)
**TDB version**:  
335.61
**Operating system**:  
Debian

previously, the quest worked
not working disable_move
please help

**Comment by tkrokli** [comment] 2016-07-04 19:29
TrinityCore rev. dd363662810e 2016-07-04 18:17:36 +0100 (3.3.5 branch) (Win64, Release, Static)
TDB 335.61 plus updates up to and including `2016_07_04_12_world.sql`

Confirmed. The Ocular (http://www.wowhead.com/npc=29747/the-ocular) has got several issues.
1. First of all, the inner eye moves outside of the outer transparent shell, like stated in this issue.
2. When player moves to evade distance, the NPC briefly changes model to Infernal on its return path.
3. The Ocular should not restore its HP when player moves out of range to eat or heal.
4. If the videos on the wowhead quest page can be trusted, the Eyesore Blaster target should be lower:
  - http://www.wowhead.com/quest=12887/its-all-fun-and-games#videos:id=73596
  - http://www.wowhead.com/quest=12887/its-all-fun-and-games#videos:id=87488

Additional YouTube video from 23. September 2011: https://youtu.be/hXQL6QRHHNg
(I don't know how valid the videos that I have linked are, maybe one or more could be from a pserver.)

**Comment by SnapperRy** [comment] 2016-07-04 19:57
4th one is very strange. Some videos from Retail show that the target of the beam is lower, but the [screenshots on the Wowhead page](http://www.wowhead.com/item=41265/eyesore-blaster#screenshots:id=106920) show it to be right where it's supposed to be.

Somehow I'm more inclined to trust the screenshot. I mean, it's not called "**Eye**sore Blaster" for nothing :P

2th one is because the npc uses SmartAI to cast the visual spell on itself.

**Comment by tkrokli** [comment] 2016-07-04 20:39
Regarding my 3. point, Ocular should not restore HP after player moves out of combat range to heal or eat, I would think that removing `unit_flag2` 2048 (0x00000800) `UNIT_FLAG2_REGENERATE_POWER` would fix that issue, but it is not available to change in the `creature` table and I presume that the `creature_table` info is from sniffs. Maybe add it to SAI by using `SMART_ACTION_REMOVE_UNIT_FLAG` + `Param2`= 1 like this:
```sql
DELETE FROM `smart_scripts` WHERE `entryorguid` = 29747 AND `source_type` = 0 AND `id`= 3;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(29747, 0, 3, 0, 7, 0, 100, 0, 0, 0, 0, 0, 19, 2048, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'The Ocular - On Evade - Remove Flags UNIT_FLAG2_REGENERATE_POWER');
```
(I know this is sort of besides the original issue, just wanted to discuss this option)

**Comment by SnapperRy** [comment] 2016-07-04 20:48
@tkrokli: UNIT_FLAG2_REGENERATE_POWER only affects mana/energy regen, not health :P I'm not sure there even is a way to prevent health regen currently.

**Comment by tkrokli** [comment] 2016-07-04 20:57
OK, what about this instead, `SMART_ACTION_SET_HEALTH_REGEN` `= 0`:
```sql
DELETE FROM `smart_scripts` WHERE `entryorguid` = 29747 AND `source_type` = 0 AND `id`= 3;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(29747,0,3,0,25,0,100,0,0,0,0,0,102,0,0,0,0,0,0,1,0,0,0,0,0,0,0, 'The Ocular - On Reset - Set Health Regeneration Off');
```

**Comment by SnapperRy** [comment] 2016-07-04 23:52
Nice one, didn't recall that smart action :)

So it can be done like this:
```sql
UPDATE `smart_scripts` SET `link`=3 WHERE `entryorguid`=29747 AND `id`=2;
DELETE FROM `smart_scripts` WHERE `entryorguid`=29747 AND `id` IN (3, 4);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(29747, 0, 3, 4, 61, 0, 100, 0, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "The Ocular - On Reset - Disable combat movement"),
(29747, 0, 4, 0, 61, 0, 100, 0, 0, 0, 0, 0, 102, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "The Ocular - On Reset - Set Health Regeneration Off");
```

**Comment by Killyana** [comment] 2016-07-05 09:12
For the regen-health you can just change RegenHealth on creature_template to 0, also we need to find why this npc is moving now and which commit did this as it probably affect other npcs.

**Comment by Pitcrawler** [comment] 2016-07-05 12:05
Maybe this one: b36da771857554c5bd652bf8ccc1386d4be607b0

**Comment by Killyana** [comment] 2016-07-05 13:15
An other npc: http://www.wowhead.com/npc=23876/spore
The unit_flags=4 is no longer rooting npcs, so an other solution must be used.

**Comment by SnapperRy** [comment] 2016-07-05 13:27
Maybe adding a special_flag is a good solution? Or do we have to stop movement on reset in smartai/core scripts?

**Comment by Killyana** [comment] 2016-07-05 13:42
Maybe @Shauren could gives us a solution, also for this kind of npcs: https://github.com/TrinityCore/TrinityCore/issues/17019 a root via smartai doesn't work.

**Comment by Killyana** [comment] 2016-08-15 19:31
Fixed by 17543

**Closed by Killyana** 2016-08-15 19:31 UTC
Labels: Feedback-PatchFix, Sub-Entities
