### ISSUE TITLE
[3.3.5] Dire Maul north entrance is not clickable

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14684] opened 2015-05-12 06:07 UTC
Players can't normally enter Dire Maul north, the door is not clickable, it should just need crescent key

DB 335.58
rev 2b95a5fe3562 2015-04-26

**Comment by dr-j** [comment] 2015-05-12 09:00
cannot reproduce and the actual door to dire maul north has not been changed at all the court yard door and inner courtyard door are now summoned but you need to obtain the keys from chests.

If its the door which leads to dire maul north from east after that long corrider did have problem at first when door could not be clicked and was missing tooltip info but simply clearing cache seemed to solve that.

**Comment by dr-j** [comment] 2015-05-12 09:27
ok seems go flags are responsible for this or namely flag 1 (in use), seems go flags where changed (not by me since I never touched that door),  flags where set at 31 making door non clickable as was marked as in use), seems flag 2 had also been removed so it appears as locked ie when flag 1 was removed door could be opened without key,

**Closed** 2015-05-12 10:01 UTC

**Comment by ikir83** [comment] 2015-05-12 19:07
I'm talking about the doors in the common central area. I've not tried to go from Dire Maul west to north.
Noone in the party was able to active door
