### ISSUE TITLE
[3.3.5/Master] Core/Creature Movement Bug

### ISSUE THREAD

**Issue by Kizarr** [TrinityCore/TrinityCore#18504] opened 2016-12-17 08:26 UTC
**Description:** Many NPCs in the game globally have a movement bug. I think this is due to a larger issue within the core making this happen on a global scale. 

**Current behavior:** NPCs movement bug walking in the air.

**Expected behavior:**  NPCs should correctly follow the movement coordinates. 

**Steps to reproduce the problem:** Example video:  https://www.youtube.com/watch?v=o1tNTzrD7i8

**Branch(es):** 3.3.5 / master

**TC rev. hash/commit:** c809c22

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:** Windows Server 2012 R2 Standard

**Comment by Eredar** [comment] 2016-12-17 17:52
It's not a bug. It's wrong value of InhabitType field in database. If 3.3.5 database have save structure as master one, then you should find bugged npc guid ingame through .npc info command, than find your npc in creature database and fix it manually. You can use value "3"(land and water), but you can look deeper in "creature" database trinity documentation page, movementtype and inhabittype fields and find apropriate value. 

Mobs are moving this way because in sniffed data many of them have "7" value, and 7 means they can fly.
All of this is my notes on master database and sniffs, so on 3.3.5 it could be different.

**Comment by Killyana** [comment] 2016-12-17 18:36
Inhabittype on 3.3.5 are correct, for this npc:
Entry: 31563.
InhabitType: 3
I noticed this issue after https://github.com/TrinityCore/TrinityCore/commit/28050f338dfc66e0c40b6a3915bf96e38e0613e5 on many npcs like: http://www.wowhead.com/npc=14321/guard-fengus

**Comment by Eredar** [comment] 2016-12-17 18:41
Well. if inhabit and movement types are correct, you should look for waypoints. Maybe some of them set in the air. It can explain twitching in their moves. Ie they cant fly, but waypoint still in the air (wrong Z coordinate).

**Comment by Kittnz** [comment] 2016-12-18 10:47
this happens a lot, even with mmaps on etc

**Comment by MrSmite** [comment] 2016-12-20 07:51
This happens when waypoints are too far apart and point A is at a lower elevation than point B (and so on).

For example:

Type __*.tele Darnassus*__, turn around and watch the NPCs that are walking up the ramp. They will get to a certain point and begin slowly bouncing higher and higher in the air until they reach the WP at the top of the ramp. If you select one of them and type __*.wp show on*__ you will see there are no interim waypoints between the bottom of the ramp and the top.

**Comment by akrom23** [comment] 2017-01-01 07:56
MrSmite is right. MMAPs are no longer used in pathing, so the only solution is to compare these waypoints with sniff.

**Comment by Killyana** [comment] 2017-01-27 16:01
Fixed after https://github.com/TrinityCore/TrinityCore/commit/a3c6880579f3326088ecbe5b8c08c4b75ed91a59

**Closed by Killyana** 2017-01-27 16:01 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Waypoints
