### ISSUE TITLE
[Crash] bitmap_set (bit=18446744073709551615, binfo=0x1f11068 <arena_bin_info+456>, bitmap=0x7fff88447010) at /home/server/TrinityCore/dep/jemalloc/include/jemalloc/internal/bitmap.h:105

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#14533] opened 2015-04-11 12:20 UTC
http://pastebin.com/sRawJN7q

08a62f19b808a347aae56b4f5a689233c6a03db0

**Comment by w1sht0l1v3** [comment] 2015-04-16 15:48
I can confirm this one.
Anyone else gets this one?

**Comment by Pirricli** [comment] 2015-04-16 19:27
http://pastebin.com/tmgjLqaa

08a62f19b808a347aae56b4f5a689233c6a03db0

**Comment by Pirricli** [comment] 2015-04-16 19:29
http://pastebin.com/jqdsn3MD

1019649f93ae8f45f0d15a9eeeb803901c3c15cf

**Comment by jackpoz** [comment] 2015-06-18 20:08
could you try disabling jemalloc and see if the crash happens in another place ?

**Comment by Aokromes** [comment] 2015-11-03 19:58
To long time since the last crash closing, if anyone have any new crash related to this open a new ticket.
Also i suggest to compile without jemalloc in case of jemalloc crashes.

**Closed by Aokromes** 2015-11-03 19:58 UTC
Labels: Comp-Core, HasBacktrace

**Comment by maheshmk8** [comment] 2019-06-14 21:01
@Aokromes 
@Pirricli 
@jackpoz 
With which version of jemalloc this issue is seen?
I do see this kind of crash with my code.
Any idea about how this was solved or what caused this crash?
