### ISSUE TITLE
[6.x] New orgrimmar spawns + Brawl'gar arena 

### ISSUE THREAD

**Issue by ElleEntertainment** [TrinityCore/TrinityCore#14638] opened 2015-05-02 12:20 UTC
Deleted all orgrimmar spawns with new (sniffs from 6.1.2 retail)
Added spawns + areatrigger of brawl'gar arena
http://pastebin.com/TunVtbpp
##

**Comment by Kinzcool** [comment] 2015-05-02 15:44
Don't delete all the old ones as they are correct. Just look through your data, and try to filter the IDs higher than cata for both, gambobjects and creatures. Exception cases of moved NPCs can be looked after later if you don't know them.

**Comment by gegge** [comment] 2015-05-02 17:44
Ok so for ecamole 4000 is the highest id for cataclism, i should only insert ids > than 4000, is it right?

**Comment by Killyana** [comment] 2015-05-02 17:52
The highest id is 58864 for cataclysm.

**Comment by VirusEntertainment** [comment] 2015-05-02 17:53
and for gameobject?

**Comment by Kinzcool** [comment] 2015-05-02 17:54
For gameobjects, MoP IDs start at 209k.

**Comment by Killyana** [comment] 2015-05-02 17:55
We have ids until 211084 on 4.x DB

**Comment by VirusEntertainment** [comment] 2015-05-02 18:44
http://pastebin.com/Bmv5410q

now it should be correct ;)

**Comment by Aokromes** [comment] 2015-05-03 17:05
ugly like hell sql.

**Comment by VirusEntertainment** [comment] 2015-05-03 17:07
it is gives no error btw..

**Comment by Kinzcool** [comment] 2015-05-03 17:27
Codesyle does matter, and also please use gist instead of pastebin for fixes.

**Comment by VirusEntertainment** [comment] 2015-05-03 17:32
oook

**Comment by tkrokli** [comment] 2015-05-03 19:38
@VirusEntertainment : in case you haven't had time to clean up that pastebin SQL, I have created a gist version for you with the top section cleaned up: https://gist.github.com/tkrokli/ec5042be578c3a272fdc

Notice also that I have added a couple of questions and suggestions towards the end of that page.

**Comment by Aokromes** [comment] 2017-03-26 00:18
This can be merged?

**Comment by tkrokli** [comment] 2017-03-26 00:24
`SET @CGUID := 370837;` needs to be checked first to see if that GUID is free.
Otherwise, you know just as much as me about checking if it works as intended.

**Comment by Aokromes** [comment] 2017-03-26 00:28
It needs to be 450000+ because it's mop+ spawns

**Comment by tkrokli** [comment] 2017-03-26 13:48
Replaced the GUID value with XXXXXX and added a comment. Also removed the incorrect column names for the `areatrigger_teleport` query, which seems less than complete (maybe it should have been replaced with an `UPDATE` query instead? (I don't have the master DBs rebuilt on my computer at the moment, feel free to check the `areatrigger_teleport` part vs master branch.

**Comment by Aokromes** [comment] 2018-01-06 09:59
4810e02

**Closed by Aokromes** 2018-01-06 09:59 UTC
Labels: Branch-master, Comp-Database, Feedback-PatchFix, Sub-Spawns
