### ISSUE TITLE
[3.3.5] Client freezes in connected message

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#19182] opened 2017-02-22 01:23 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
After the server starts with many connections sometimes the client freezes in connected message. It occurs after recent commits.

**Current behaviour:** 
The client freezes in connected message.

**Expected behaviour:** 
The client must enter the world.

**Steps to reproduce the problem:**
1. Try to sign in a server with concurrent conections.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  b4b031b

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Treeston** [comment] 2017-02-22 01:33
That's existed for a very long time.

**Comment by Noryad** [comment] 2017-02-22 01:36
Has never happened to me and the number of users is the same

**Comment by CDawg** [comment] 2017-02-22 02:23
How recent? Can you pin point a commit where there were less client connection issues?

**Comment by Noryad** [comment] 2017-02-22 04:05
Feb 20 and 21, 2017

**Comment by jackpoz** [comment] 2017-02-22 08:04
with https://github.com/jackpoz/BotFarm I can usually login with 1000 users at the same time

**Comment by Re3os** [comment] 2017-02-22 08:24
@Noryad no't confirm use last trinity 200+ players.Check custom scripts.

**Comment by Palabola** [comment] 2017-02-22 08:25
@jackpoz It has no connection with number of connections until the connections are "safe". It should be some unhandled exception or some unclosed socket.

**Comment by Noryad** [comment] 2017-02-22 12:48
Last night it happened with f96f1ce, my fast solution was to return to 1beb2e5. I do not say that the number of online users is a pattern, just that it does not happen with the first ones to log in. For now is the information i can provide. I can do more tests today at night.

**Comment by Treeston** [comment] 2017-02-22 16:44
I suspect it's a client issue, really. This happen with some regularity on retail servers too back in wrath.

**Comment by xjose93** [comment] 2017-02-23 14:39
I can confirm that, not sure how many time ago but before wasn't happening (discover that 2 days ago when i tried to login from same pc 6x clients).

**Comment by jackpoz** [comment] 2017-02-24 09:02
> The client must enter the world

does the connected message appear before or after the character selection screen ?

**Comment by Aokromes** [comment] 2017-02-24 09:13
I reproduced the bug, the client got stuck between login and character selection (no list of characters)

**Comment by Noryad** [comment] 2017-02-24 12:10
Exactly as it says @Aokromes, when the server reaches "that state" if someone logs out or logs in can not get the list of characters. Yesterday happened again and this time I did not go back to an earlier version (i confirm that works ok until 1beb2e5) just i disconnected the network cable for a few seconds and reconnected it, solved the problem "spectacularly".

**Comment by Keader** [comment] 2017-02-24 13:35
I saw this bug in my old server before 2015

**Comment by Noryad** [comment] 2017-02-24 16:00
In my case at least since September 2016 the client never got stuck until now.

**Comment by Viste** [comment] 2017-02-24 20:39
its happen some times for me to, but its not new bug, see this bug from dec 2016 when i back to WoW )

**Comment by MrSmite** [comment] 2017-02-26 07:01
I've had this happen on my server with no players on and me logging in. The client gets stuck after clicking 'login'.

In my case it's usually when I haven't had the server running for days. When the client first starts up, AHBot has to expire a crap ton of auctions (I have mine set to 500,000 total auctions for fun) which makes the core unresponsive to login attempts.

**Comment by Adizbek** [comment] 2017-02-26 09:16
It's doesn't seem client problem. After updating to the last version: TrinityCore rev. 278353673639 2017-02-21 21:02:12 +0500 (3.3.5 branch) (Unix, Release, Static)
This bug occured. After downgrading server worked like before. And players can join..

**Comment by Shauren** [comment] 2017-02-26 09:53
Can all of you at least try to be helpful? I would like all reports to provide two commit hashes, the one that worked and the one that didn't work

**Comment by Aokromes** [comment] 2017-02-26 10:35
Try to downgrade to ae9d01a3245c59a8a8d50516a79b79250337450d if it still freezes try 4eae29d421e1d7a28aaa50d401cbbf09c50bd476

**Comment by Treeston** [comment] 2017-02-26 14:26
If it's a random occurrence problem, any sort of "I downgraded to X and it worked again" report is fairly pointless.

**Comment by Killyana** [comment] 2017-02-27 19:33
When this happen some errors appears on server log:
```
Received unexpected opcode [CMSG_CANCEL_TRADE 0x011C (284)] Status: STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT Reason: the player has not logged in yet and not recently logout from [Player: Account: 104225]
Received unexpected opcode [CMSG_CANCEL_TRADE 0x011C (284)] Status: STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT Reason: the player has not logged in yet and not recently logout from [Player: Account: 41985]
Received unexpected opcode [CMSG_CANCEL_TRADE 0x011C (284)] Status: STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT Reason: the player has not logged in yet and not recently logout from [Player: Account: 105562]
Received unexpected opcode [CMSG_CANCEL_TRADE 0x011C (284)] Status: STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT Reason: the player has not logged in yet and not recently logout from [Player: Account: 96033]

**Comment by Moorgoth** [comment] 2017-03-03 02:55
again on f612b1c :(

**Comment by Aokromes** [comment] 2017-03-03 08:56
https://github.com/TrinityCore/TrinityCore/issues/19182#issuecomment-282546946

**Comment by Demonid** [comment] 2017-03-11 06:08
Just today i got 2 freezes with 90 players, it doesn't freeze at the startup, but after the server has been online for a while.

Rev: 340ce38e01fed2e523784ee7a80f9fa25782d447

Can anyone share the latest Rev where this issue does not happen?

**Comment by Demonid** [comment] 2017-03-12 18:40
Btw, im still getting freezes on 4eae29d421e1d7a28aaa50d401cbbf09c50bd476

**Comment by Demonid** [comment] 2017-03-13 23:36
So here what i know so far...

This was the newest rev i tried that STILL has the issue: 4eae29d421e1d7a28aaa50d401cbbf09c50bd476

This is the rev doesn't have the issue d42faefe9a8c1a3f805e34cf0985dcab109ff8f5.

After looking between all the commints between Commit A and Commit B, i think the issue is related to https://github.com/TrinityCore/TrinityCore/commit/4c27203c8f36dd2a5df0a4ae69fbdc4c9140b29d or the commits fixup commits after it.

Right now i cant test anymore for a couple of days to give players a sense of stability, but i'll try updating all the way to f57132b795a097a2c4c863a8153b0c1be5e008c0 (one commit before the one i think its the one causing the bug) and report feedback over here.

@Shauren

**Comment by ariel-** [comment] 2017-03-14 04:42
Could you try reverting 684a5fd3f1895703a52cff7e7f762883c74c5aba?

**Comment by Demonid** [comment] 2017-03-14 07:02
Sure, i'll give it a try.

**Comment by Killyana** [comment] 2017-03-14 15:59
@ariel-  this freez happen rarely, you can run the server over 7 days of up-time without any problem.

**Comment by CDawg** [comment] 2017-03-15 01:49
@Noryad I'm confused, reading through all the commits and doing tons of commit testing.
You originally said that you went to https://github.com/TrinityCore/TrinityCore/commit/1beb2e5fd6e85332173b1f3e414d5b385c3022fb to revert back because of the incident of freezing.
However, later you say that it works UNTIL https://github.com/TrinityCore/TrinityCore/commit/1beb2e5fd6e85332173b1f3e414d5b385c3022fb
is that correct?

**Comment by Noryad** [comment] 2017-03-15 16:45
In my case detect it after 1beb2e5

**Comment by Demonid** [comment] 2017-03-17 07:11
@Killyana I had it happen 2 days in arrow like 4 - 5 once reaching +90 players, before reaching 90 i had it working without issues for 4-5 days.

@Noryad What rev are you using right now and how many players do you have on average ?

@ariel- Tried but having issues installing Boost 1.63 on Debian =/

**Comment by MrSmite** [comment] 2017-03-18 01:20
Out of curiosity, did you try tweaking the Player save interval? Maybe there's a bug with handling too many players.

**Comment by joshwhedon** [comment] 2017-03-20 12:57
@ariel- : Sadly reverting just this commit would not be enough, as this commit was fixing some compilation errors :(.

**Comment by Killyana** [comment] 2017-03-20 16:09
@Tonghost Can you take a look to this, looks like you commit https://github.com/TrinityCore/TrinityCore/commit/684a5fd3f1895703a52cff7e7f762883c74c5aba  is involved

**Comment by Killyana** [comment] 2017-03-24 00:21
So when this issue starts you have to wait a long time before the authserv respond to be connected, it could take more than 40 secs, but after some time to will not respond at all, it looks like something is making it lagging.

**Comment by MrSmite** [comment] 2017-03-24 01:59
> but after some time to will not respond at all, it looks like something is making it lagging.

Probably a long shot but this is what happens to me if I have too many items from AHBot exipring at the same time and I haven't started the server in a while. Has anything changed in the bot?

**Comment by Demonid** [comment] 2017-03-24 03:01
@MrSmite I didn't had AHBot enabled, and the Save Interval was 90 seconds (Default) for 70-90 players on average.

The DB for that server was brand new so there wasn't much to load.

**Comment by ImMoonlight** [comment] 2017-04-02 02:25
hi my server update to 8e1e081d6cd3826a46e96cac211d5c12f5d8536b two days ago but after some minutes players cant log in, restarting authserver not work, i have to restart worldserver to fix it and it happens very soon after each restart

before i have 91201f11f805a7bd21291717af8008c6b5e855fe and dont have login prblems

this is really critical bug, please fix soon if you can

**Comment by ariel-** [comment] 2017-04-04 01:23
Expiring auctions from AHBot also have a noticeable impact on login delay. I'll cap the amount of item deletions we process at the same time (like we do with session updates)

**Comment by MrSmite** [comment] 2017-04-04 05:07
> Expiring auctions from AHBot also have a noticeable impact on login delay

Indeed, as I mentioned earlier [(comment)](https://github.com/TrinityCore/TrinityCore/issues/19182#issuecomment-288912239). The OP said however that he didn't have AHBot enabled. While I like your fix for wrapping deletions in a transaction, it may not help this exact issue.

**Comment by ariel-** [comment] 2017-04-04 05:10
That's why I made the commit a reference to this issue, instead of closing. I'm fully aware of OP not having AHBot active :)

**Comment by joshwhedon** [comment] 2017-04-04 05:16
So, we have encountered this issue for a few weeks too, following us disabling the graphana service. However, what we forgot to do is disabling the posting of the metrics, which resulted in a 404 not found. After disabling the metrics, we did not encounter that issue anymore. I am not saying it is the cause of your particular issue, but it was the cause of ours, with the same symptoms.

**Comment by Demonid** [comment] 2017-04-04 05:19
@joshwhedon Just to know, what rev were you using and how many players did you had on average?

**Comment by joshwhedon** [comment] 2017-04-04 05:26
I can't check the rev right now, but 3.3.5 no older than 1 month. 350 players on peak hours, 200 on average through the day.
After a day or two, players could not log in anymore. And if the world server was restarted, there was always a huge rollback (as if no db save happened during the time where players could not log in).
We haven't had that issue since a week and half or so (after we disabled the metrics).

**Comment by Demonid** [comment] 2017-04-04 07:30
@joshwhedon Yeah i can confirm that, after the login freezes, the only way to fix it is by doing a worldserver restart, and the rollback is huge, our rollbacks were between 10 and 20 minutes since i was restarting the server as soon as a player reported me the login issue.

The weird part is that i just check my configs and didn't had any DB Stressful config enable, no metrics, no AHBot, so i guess my issue is related to what @A-Metaphysical-Drama say.

Thanks again for the info ;)

**Closed** 2017-04-12 02:24 UTC
Labels: Branch-3.3.5a, Comp-Core, Priority-High

**Comment by ariel-** [comment] 2017-04-12 02:26
> This commit is the problem source: 3ddcf40
std::numeric_limits<time_t>::max() causes an overflow in linked respawn (Linked spawns are set to boss + 1-59 secs), this causes a database loop in the respawn function.

> The easy fix is to just clear the respawn table with entries lower than 60 sec and replace std::numeric_limits<time_t>::max() with time(NULL) + YEAR, year should be enough

> Cheers

Indeed this was the cause, thanks for taking your time :)

**Comment by Treeston** [comment] 2017-04-12 10:24
Very good catch, :+1:

**Comment by Re3os** [comment] 2017-04-19 06:10
SQL(p): REPLACE INTO creature_respawn (guid, respawnTime, mapId, instanceId) VALUES (202796, 9223372036854775807, 724, 18)
 [ERROR]: [1264] Out of range value for column 'respawnTime' at row 1

**Comment by Aokromes** [comment] 2017-04-19 06:32
O_o
9223372036854775807

**Comment by offl** [comment] 2017-04-19 07:03
We all will die, our Sun will die, everything will turn to dust, but this creature will be still not respawned.

**Comment by Aokromes** [comment] 2017-04-19 07:12
hell, even universe will die and still not respawned.

**Comment by tkrokli** [comment] 2017-04-19 07:22
If the wiki info is correct, (**respawntime** The time when the creature should be respawned in Unix time.),
https://www.epochconverter.com/
```
Assuming that this timestamp is in microseconds (1/1,000,000 second):
GMT: Fri, 11 Apr 2262 23:47:16 GMT
Your time zone: 12/04/2262, 01:47:16 GMT+2:00 DST
```

**Comment by Shauren** [comment] 2017-04-19 08:12
That value is std::numeric_limits<int64>::max()

**Comment by ariel-** [comment] 2017-04-19 17:03
> Assuming that this timestamp is in microseconds (1/1,000,000 second):

Those are actual seconds, meaning the real timestamp is that much further into the future :P

@Re3os as previously stated you're missing updates, please setup the automatic updater so you don't need to worry about having missing sqls

**Comment by Killyana** [comment] 2017-09-24 17:16
Someone can confirm the issue on TrinityCore rev. d7e4dcc16e71 2017-09-17 or after https://github.com/TrinityCore/TrinityCore/commit/66755eecf117d21504b13a86410aa01cfc44c3ba  ?
