### ISSUE TITLE
3.3.5 Permanent Updating Realm List...

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16743] opened 2016-03-07 15:22 UTC
**Description**:
Updating Realm List...

**Current behaviour**: Tell us what happens
Spam Updating the Realmlist in the authserver

**Branch(es)**: 335/6x

**TC hash/commit**:TC>TrinityCore rev. 7ee7548b9443 2016-03-07 10:35:33 +0100 (335 branch)

**Operating system**: Windows 7 64Bit

**Comment by DDuarte** [comment] 2016-03-07 15:26
Why is this an issue? The message appears every 10 seconds (`RealmsStateUpdateDelay` in config)

**Comment by Tauriella** [comment] 2016-03-07 15:45
Arrrg sorry my mistake

**Comment by DDuarte** [comment] 2016-03-07 15:57
Ahm, you didn't need to close the issue. I just wanted to hear your opinion.

**Comment by Tauriella** [comment] 2016-03-07 16:44
in my config is the timer every 20 seconds but in my opinion is this quite annoying 
But i can turn off this feature

**Comment by Shauren** [comment] 2016-03-07 16:47
Then disable this log in config - server.authserver is the logger used at level INFO

**Comment by Tauriella** [comment] 2016-03-07 16:52
Yes i have

**Comment by Shauren** [comment] 2016-03-09 14:24
in any case, not a bug

**Closed by Shauren** 2016-03-09 14:24 UTC
