### ISSUE TITLE
Ravager - hunter pet - stun has no CD

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#15137] opened 2015-07-21 18:47 UTC
http://www.wowhead.com/pet=31/ravager

His stunning spell has no cooldown. Stuns every 3 seconds.

b574c99

**Comment by Nyeriah** [comment] 2015-07-21 19:04
PetAI only checks for cooldown if the spell is positive, anything else skips the check and has no cooldown

https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/AI/CoreAI/PetAI.cpp#L154-L160

**Comment by xjose93** [comment] 2015-07-21 20:03
Then on https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/AI/CoreAI/PetAI.cpp#L216 should be enough with:

`else if (me->GetVictim() && CanAttack(me->GetVictim()) && spellInfo->CanBeUsedInCombat())`
=>
`else if (me->GetVictim() && CanAttack(me->GetVictim()) && spellInfo->CanBeUsedInCombat() && me->GetSpellHistory()->IsReady(spellInfo))`
?

**Comment by Nyeriah** [comment] 2015-07-21 20:10
Either that or move it out of the IsPositive() if block, I don't know what'd be better, but I guess either would work

**Comment by RelevantJesse** [comment] 2015-07-21 21:22
Probably best going with xjose93's suggestion. Not sure what the purpose is for the IsPositive() check, but I'm guessing it's there for a reason. I'm curious why the spell is not positive, but in any case, it should still follow the same logic and check to see if the spell is ready, I'd think.

**Comment by RelevantJesse** [comment] 2015-07-21 21:54
Probably moving the check for IsReady that's inside of the IsPositive block to outside, since it needs to be checked in either case. Probably best to check for IsReady in all situations.

**Comment by MrSmite** [comment] 2015-08-22 06:31
This isn't an issue with the AI though, the spell should be failing in *Cast()* because of cooldown.

**Comment by Keader** [comment] 2015-10-14 19:06
Reproduction method: https://github.com/TrinityCore/TrinityCore/pull/15140#issuecomment-148146422

**Comment by sirikfoll** [comment] 2015-10-15 03:21
The use of the spell [Wolverine Bite] (http://wotlk.openwow.com/spell=53508) Add/Modify the Cooldown of the spell Ravage to 5 seconds.
Really really odd

**Comment by sirikfoll** [comment] 2015-10-15 23:36
The problem happens in this block
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellHistory.cpp#L367

**Comment by MrSmite** [comment] 2015-10-16 00:27
@sirikfoll 

Thanks for the research. *SpellHistory.cpp* is new to me, when I worked on the AI long ago it didn't exist. If you want to take a stab at fixing it that would be great, it will take me some time to get acquainted with that system and I've already got a couple other projects on my plate (eg: AHBot).

**Comment by Keader** [comment] 2015-10-16 00:29
@MrSmite look this: https://github.com/TrinityCore/TrinityCore/pull/15140#issuecomment-148559413

**Closed** 2015-10-29 16:56 UTC
Labels: Comp-Core, Feedback-PatchFix, Sub-Spells
