### ISSUE TITLE
Gossip texts for Wyrmrest Temple taxis are incorrect.

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#15957] opened 2015-12-07 23:48 UTC
c703e01

The texts for the taxi flights between the levels of Wyrmrest Temple are incorrect as is. I tried to look at doing it properly versus just changing strings per Aokromes's suggestion in #15883, but I had to give up - just don't know enough about C++. Thus, decided to open an issue regarding it so that it can be tracked.

The texts are correct in the database already.

[Lord Afrasastrasz](http://www.wowhead.com/npc=27575/lord-afrasastrasz)
[Tariolstrasz](http://www.wowhead.com/npc=26443/tariolstrasz)
[Torastrasza](http://www.wowhead.com/npc=26949/torastrasza)

**Comment by tkrokli** [comment] 2015-12-08 01:08
Could you say a little bit more about in which ways the texts are incorrect?
Maybe it could be fixed in the database by using SAI and conditions?

**Comment by velinath** [comment] 2015-12-08 01:37
Sure! The server is currently pulling the gossip options from src/server/scripts/World/npc_taxi.cpp. In that file right now, the gossip options are incorrect - they should be different strings, per commit b403f98 from my PR.

@Aokromes suggested converting to read the gossip options from the database. At the time I made the PR, I did check the values in the DB and found that they were already there and are in fact correct in DB. Unfortunately I didn't keep the data for which table I pulled those texts from or I'd note that here as well.

Let me know if I can provide any further information.

**Comment by tkrokli** [comment] 2015-12-08 13:55
OK, I see. The Wyrmrest FP gossip is currently set in
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/World/npc_taxi.cpp#L50-L55
for the 3 FP handlers you linked above.

When comparing those with the actual texts in the database, I see there are several differences:
```sql
SELECT * FROM `broadcast_text` WHERE `MaleText` LIKE '%Afrasastrasz%'
OR `MaleText` LIKE '%of the temple?'
OR `MaleText` LIKE '%of the temple.';
```
```
    ID  Language  MaleText                                                                                                                        FemaleText                                                                                           EmoteID0  EmoteID1  EmoteID2  EmoteDelay0  EmoteDelay1  EmoteDelay2  SoundId    Unk1    Unk2  VerifiedBuild
------  --------  ------------------------------------------------------------------------------------------------------------------------------  ---------------------------------------------------------------------------------------------------  --------  --------  --------  -----------  -----------  -----------  -------  ------  ------  -------------
 26100         0  Yes, please, I would like to return to the ground level of the temple.                                                          Yes, please, I would like to return to the ground level of the temple.                                      0         0         0            0            0            0        0       0       1          18019
 26795         0  Steward, please allow me to ride one of the drakes to the queen's chamber at the top of the temple.                             Steward, please allow me to ride one of the drakes to the queen's chamber at the top of the temple.         0         0         0            0            0            0        0       0       1          18019
 26936         0  Greetings, $r.$B$BIf you are interested in helping with the defense of the temple, please speak with Lord Afrasastrasz inside.                                                                                                              1         0         0            0            0            0        0       0       1          18019
 26956         0  Lord Afrasastrasz, with your leave, I wish to defend the temple.                                                                Lord Afrasastrasz, with your leave, I wish to defend the temple.                                            0         0         0            0            0            0        0       0       1          18019
 27042         0  I would like to go to Lord Afrasastrasz in the middle of the temple.                                                            I would like to go to Lord Afrasastrasz in the middle of the temple.                                        0         0         0            0            0            0        0       0       1          18019
 27043         0  My lord, I need to get to the top of the temple.                                                                                My lord, I need to get to the top of the temple.                                                            0         0         0            0            0            0        0       0       1          18019
 27046         0  Can I get a ride back to ground level, Lord Afrasastrasz?                                                                       Can I get a ride back to ground level, Lord Afrasastrasz?                                                   0         0         0            0            0            0        0       0       1          18019
 27048         0  Can you spare a drake to take me to Lord Afrasastrasz in the middle of the temple?                                              Can you spare a drake to take me to Lord Afrasastrasz in the middle of the temple?                          0         0         0            0            0            0        0       0       1          18019
 54347         0  Lord Afrasastrasz sent me. He said you have a message to decode?                                                                Lord Afrasastrasz sent me. He said you have a message to decode?                                            0         0         0            0            0            0        0       0       1          18019
```
Just disregard the 3 extra lines and compare the 6 relevant lines with the lines in the current script:
```cpp
#define GOSSIP_AFRASASTRASZ1    "I would like to take a flight to the ground, Lord Of Afrasastrasz."
#define GOSSIP_AFRASASTRASZ2    "My Lord, I must go to the upper floor of the temple."
#define GOSSIP_TARIOLSTRASZ1    "My Lord, I must go to the upper floor of the temple."
#define GOSSIP_TARIOLSTRASZ2    "Can you spare a drake to travel to Lord Of Afrasastrasz, in the middle of the temple?"
#define GOSSIP_TORASTRASZA1     "I would like to see Lord Of Afrasastrasz, in the middle of the temple."
#define GOSSIP_TORASTRASZA2     "Yes, Please. I would like to return to the ground floor of the temple."
```
There are some deviances, like naming Lord Afrasastrasz "Lord **of** Afrasastrasz" and using "must" instead of "need to". I am guessing that the script was written without sniffed or verified texts.

Besides the wrong texts in the sense of 'not correctly written', are there functional errors too, like the text being misleading in relation to their order and placement in the gossip windows?

Do we need the script to be changed in how the gossip is handled in
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/World/npc_taxi.cpp#L142-L159
in order to work as intended, in case it would not be possible to rewrite it in SQL/SAI?

**Comment by velinath** [comment] 2015-12-08 14:47
No functional errors that I know of; all the taxi options work as you would expect currently.

**Comment by tkrokli** [comment] 2015-12-08 15:00
OK, so if I understand you correctly, we basically need to correct the text based on the DB info? :)

**Comment by velinath** [comment] 2015-12-08 15:30
Yes, exactly.

Per your edit: As I understand it, per @Aokromes comment on the PR (#15883 for reference), should be converted to SQL. I tried to look at it on my own but don't know enough to actually make a proper fix.

**Comment by tkrokli** [comment] 2015-12-08 16:22
OK, I see. The converting part is mostly about removing the gossip lines in the existing script and adding proper `gossip_menu_option`s for the 3 NPCs. Thanks also for confirming that a DB/SQL gossip solution is the preferred solution, so I don't spend any time redoing what you already did in #15883 .

I need to do a little research. Also, some current DB info about the 3 NPCs is nice to keep around:
```sql
SELECT `entry`,`name`,`subname`,`gossip_menu_id`,`unit_class`,`AIName`,`HoverHeight`,`ScriptName`,`VerifiedBuild` 
FROM `creature_template` WHERE `entry` IN (26443,26949,27575);
```
```
 entry  name               subname                                 gossip_menu_id  unit_class  AIName    HoverHeight  ScriptName  VerifiedBuild 
------  -----------------  -------------------------------------   --------------  ----------  ------    -----------  ----------  --------------
 26443  Tariolstrasz       Steward of Wyrmrest Temple                        9455           2                      1  npc_taxi            12340 
 26949  Torastrasza        Majordomo to the Ruling Council                   9457           2                     10  npc_taxi            12340 
 27575  Lord Afrasastrasz  Commander of Wyrmrest Temple Defenses             9563           1                      1  npc_taxi            12340 
```
(I skipped columns with identical/'zero' values or irrelevant info.)

Then there is the list of existing `gossip_menu_options`:
```sql
SELECT * FROM `gossip_menu_option` WHERE `menu_id` IN (9455,9457,9563);
```
```
menu_id      id  option_icon  option_text                                                                                          OptionBroadcastTextID  option_id  npc_option_npcflag  action_menu_id  action_poi_id  box_coded  box_money  box_text  BoxBroadcastTextID 
-------  ------  -----------  ---------------------------------------------------------------------------------------------------  ---------------------  ---------  ------------------  --------------  -------------  ---------  ---------  --------  -------------------
   9455       0            0  Steward, please allow me to ride one of the drakes to the queen's chamber at the top of the temple.                  26795          1                   1               0              0          0          0                             0
   9455       1            0  Can you spare a drake to take me to Lord Afrasastrasz in the middle of the temple?                                   27048          1                   1               0              0          0          0                             0
   9457       0            0  Yes, please, I would like to return to the ground level of the temple.                                               26100          1                   1               0              0          0          0                             0
   9457       1            0  I would like to go to Lord Afrasastrasz in the middle of the temple.                                                 27042          1                   1               0              0          0          0                             0
   9563       0            0  My lord, I need to get to the top of the temple.                                                                     27043          1                   1               0              0          0          0                             0
   9563       1            0  Can I get a ride back to ground level, Lord Afrasastrasz?                                                            27046          1                   1               0              0          0          0                             0
```
Notice that these texts are correct, they are also linked to their entries in `broadcast_text` via `OptionBroadcastTextID`. It still remains to create a linked SAI script to make them give you a ride.

**Comment by velinath** [comment] 2015-12-09 02:10
@tkrokli Thanks very much for outlining your thought process. I learned a lot by being able to follow along and watch what you were doing.

**Comment by tkrokli** [comment] 2015-12-09 02:16
Thanks for the feedback. That was my intention, in the hope that it will be useful for others in the future, in case anything would happen that would make me unavailable for additional questions. :)

**Closed** 2016-01-02 22:14 UTC
Labels: Branch-3.3.5a, Branch-6.x, Comp-C++Script
