### ISSUE TITLE
quest: 5624:Garments of the Light,9586:Help Tavara can not complete.

### ISSUE THREAD

**Issue by wywgk** [TrinityCore/TrinityCore#27840] opened 2022-03-01 01:18 UTC
### Description

quest can not complete.
Cannot heal the target

### Expected behaviour

quest can not complete.
Cannot heal the target

### Steps to reproduce the problem

。。

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. cb15c9111068 2022-02-27 22:09:21 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)
Using World DB: TDB 335.22021

### Operating system

 Debian 11 x64,

### Custom changes

none

**Comment by offl** [comment] 2022-03-01 01:23
Duplicate of #26009

**Closed by offl** 2022-03-01 01:23 UTC
Labels: Branch-3.3.5a
