### ISSUE TITLE
[3.3.5] Warlock spell Drain soul

### ISSUE THREAD

**Issue by gearsofdeath** [TrinityCore/TrinityCore#14859] opened 2015-06-09 14:26 UTC
Rev:https://github.com/TrinityCore/TrinityCore/commit/abda6840e1ac3c8140af59c619bef934761db5ee

When a mob is killed while using drain soul the buff "x Shadow damage every 3 seconds" does not fade from the warlock.

http://i.imgur.com/SduRgjr.jpg

**Comment by ccrs** [comment] 2015-06-09 19:33
confirm dbaf88566be7083408fb8324d7886dc3e0a45cc0

**Comment by Thulium-Drake** [comment] 2016-10-16 08:26
This still exists in dc0b1e0 and there is an additional issue with this spell. Players are rewarded the additional mana for the talent without using the spell.

**Comment by tkrokli** [comment] 2016-10-16 11:11
Commit https://github.com/TrinityCore/TrinityCore/commit/2ff855054f52bf2dcf81aa7a7da7bab7f8a99686 contains most of what you are looking at, so @ariel- would likely know more about this.
(https://github.com/TrinityCore/TrinityCore/commit/2ff855054f52bf2dcf81aa7a7da7bab7f8a99686#diff-e79e7bf7de4a9812ee5baa193adea79eR758 is where the code was added)

**Comment by ariel-** [comment] 2016-10-17 06:32
d9743c984f11069bddab9d7f006293c18a400765 only fixes new issue (mana return when killing, no matter if it was with drain soul or not, and also on creatures not giving experience). It should've been reported on a new ticket.

Original issue remains, and its a little bit more general (channeled spells on dead targets). See #16707

**Comment by Thulium-Drake** [comment] 2016-10-17 06:37
As the issue with Channeling is a duplicate of the ticket you linked, would it be an idea to close this one? And continue to work on the channeling issue for the other issues?

**Closed** 2016-10-17 07:34 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Spells
