### ISSUE TITLE
Scripts/Utgarde Pinnacle: Svala Sorrowgrave don't work

### ISSUE THREAD

**Issue by citizenwow** [TrinityCore/TrinityCore#23912] opened 2019-11-14 12:11 UTC
Description:
Svala Sorrowgrave After the change of form, she stands still and does nothing.

Steps to reproduce the problem:
Start fight Svala Sorrowgrave and wait the change of form.

Branch(es): 3.3.5

TC rev. hash/commit:
TrinityCore rev. c79571a 2019-11-03 17:00:24

TDB version: TDB 335.19101

Operating system: CentOS 7

**Comment by Riztazz** [comment] 2019-11-14 12:44
duplicate of https://github.com/TrinityCore/TrinityCore/issues/23610

**Closed** 2019-11-14 13:04 UTC
