### ISSUE TITLE
Mangle's damage

### ISSUE THREAD

**Issue by Theblues** [TrinityCore/TrinityCore#1696] opened 2011-05-25 23:24 UTC
Mangle, which is supposed to only increase periodic damage (30% of extra damages), increases every damages.
Tested on a Trinity Core version dated from the beginning of the month.

Spell : 
http://www.wowhead.com/spell=33876
http://www.wowhead.com/spell=33878
But I have not got the aura's ID on my server the .list aura do crash =/

Mangle
All bleed effects cause 30% additional damage.
1 minute remaining

ps : 1k crit with mangle and 600 crit without mangle

**Comment by danlapps** [comment] 2015-03-15 21:18
close to 3 years without anything, is this still a valid issue or has it been fixed on the go ?

**Comment by Killyana** [comment] 2015-04-15 15:10
Cannot reproduce only bleeding periodic damage is increased by 30%.

**Closed** 2015-05-20 18:45 UTC
Labels: Comp-Core, Invalid-CannotReproduce, Sub-Spells
