### ISSUE TITLE
[3.3.5] Sister Svalna - Crok event does not start

### ISSUE THREAD

**Issue by JudgeGM** [TrinityCore/TrinityCore#8186] opened 2012-10-26 14:39 UTC
Hi :)
I have encounter with a bug that related to Sister Svalna.
Sometimes when you arrive to Crok Scourgebane <Grand Champion of the Ebon Blade> the script doesn't start .
I mean that he doesn't start to run into the mobs but stands there without moving , and after you kill them without him , you can't attack Sister Svalna. (She is unattackable)

Yes i know that the script start when you arrive to Crok Scourgebane.
#7458

http://www.wowhead.com/npc=37126 - Sister-svalna
http://www.wowhead.com/npc=37129 - Crok Scourgebane <Grand Champion of the Ebon Blade>
http://www.wowhead.com/zone=4812 - Icecrown Citadel

Hash : 69a81836
Tdb: 335.11.47+
##

**Comment by Keader** [comment] 2015-06-27 22:11
I know that the bug exists but can not reproduce it, so I can not tell if your fix works.

**Comment by Keader** [comment] 2015-07-06 17:02
Still buged on rev b574c99549bb8cf1d95bd4bc0c319548a678799a

**Comment by Laintime** [comment] 2016-02-12 19:24
confirm https://github.com/TrinityCore/TrinityCore/commit/a23ccc1b83ded39501d690e288be49be8f32b539

**Comment by Greymane** [comment] 2016-03-24 17:05
confirmed on https://github.com/TrinityCore/TrinityCore/commit/c9751eb1f822df6a92b7820328a7b7f025d0c997

**Comment by tkrokli** [comment] 2016-03-25 11:02
@Greymane : it looks like cr4st has not done anything on github since 2015-03-25 or earlier:
- https://github.com/cr4st
- https://github.com/cr4st?tab=activity
- https://github.com/TrinityCore/TrinityCore/commits?author=cr4st

**Comment by Keader** [comment] 2017-01-18 20:24
> The event works ok if the raid is not attacked by Val'kyr Herald. When Val'kyr Herald attacks the raid the NPC Crok Scourgebane helps to defeat her. After that the event does not continue. Frequently the event is canceled without the Val'kyr Herald attack, but I can not identify that pattern. This makes Sister Svalna unable to be defeated and no access to Valithria Dreamwalker.

https://github.com/TrinityCore/TrinityCore/issues/18874#issue-201332548

**Comment by Noryad** [comment] 2017-01-20 15:27
In a review dated 06/18/2016 the event works fine, I do not know when it broke, but it is really important to solve it, since it disables Valithria Dreamwalker, Sindragosa and The King Lich. This issue is assigned to @Shauren but now he is doing a great work in Legion, maybe @Keader, @jackpoz , @joschiwald  or another member can help us.

**Comment by Keader** [comment] 2017-01-20 15:29
It happens before 06/18/2016

**Comment by Aokromes** [comment] 2017-01-20 15:48
Oct 26, 2012 minimum.

**Comment by Noryad** [comment] 2017-01-20 17:55
@Aokromes , @Keader 
Please check ad6cd70 
In that review, the event works, I do not say it works at 100%, but at least it ends and Sister Svalna can be defeated, enabling Valithria Dreamwalker and thus Sindragosa, an important step in the race towards King Lich. Keep in mind that Crok Scourgebane focuses on the event, for example does not intervene when Val'kyr Herald attacks contrary to what happens in the current revision.

**Comment by Keader** [comment] 2017-01-20 18:01
i will try look it tonight

**Comment by Dalgurakk** [comment] 2017-01-20 18:16
then can the lich king be defeated?

**Comment by Noryad** [comment] 2017-01-20 18:17
no :(

**Comment by jackpoz** [comment] 2017-01-20 19:02
@Noryad please don't @ me

**Comment by Noryad** [comment] 2017-01-20 19:03
ok

**Comment by Noryad** [comment] 2017-01-20 19:18
> Keep in mind that Crok Scourgebane focuses on the event, for example does not intervene when Val'kyr Herald attacks contrary to what happens in the current revision (9355945).

Another observation: The event in ad6cd70 starts at a shorter distance from Crok Scourgebane than in 9355945

**Comment by Dalgurakk** [comment] 2017-01-21 07:54
This affects the main pve content of 3.3.5

**Comment by Keader** [comment] 2017-01-21 13:39
i cant reproduce with Valkyr, but i can with creatures of plagueworks.

**Closed** 2017-01-21 14:03 UTC
Labels: Branch-3.3.5a, Comp-C++Script, Sub-Instances
