### ISSUE TITLE
[Crash] 

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#17910] opened 2016-09-06 10:20 UTC
http://paste.ubuntu.com/23140954/

**Branch(es)**: 3.3.5
**TC hash/commit**:  5868509a6366d0ba7a0fe819c3ece0e4a57c7029
**TDB version**:  61
**Operating system**:  Debian

**Comment by jackpoz** [comment] 2016-09-06 14:27
>perm = true
        extendState = EXTEND_STATE_EXPIRED
        resetTime = 0
        deleteInstance = false
        mapId = 578
        mapname = "The Oculus"
        fields = <optimized out>
        instanceId = 221
        difficulty = 1 '\001'
        group = 0x24200000000

**Comment by jackpoz** [comment] 2016-09-06 14:46
The crash happened during std::unordered_map::find() on a member of a static instance during the thread-safe WorldUpdateLoop(). It is very likely that the actual cause of the crash is unrelated to this stacktrace and happened before, causing the std::unordered_map to be in an invalid state.

**Comment by jackpoz** [comment] 2016-09-06 14:47
@sucklifex do you have any custom change at all in the whole sources ?

**Comment by sirikfoll** [comment] 2016-09-06 14:53
Old issue about this crash at #12317, there's some logs and discussion there

**Comment by tkrokli** [comment] 2016-09-06 15:22
@sucklifex : Your source is 7 weeks old. Also check #12317 to see if this issue can be closed.

**Comment by jackpoz** [comment] 2016-09-06 15:39
In addition to the usual "race condition" and "random heap corruption" causes, there could be a stale compilation unit that is mixing different object layouts and causing random crashes. A "make clean" or "rm -f -r builddirectory" should be enough if that's the case.

**Comment by sucklifex** [comment] 2016-09-06 21:08
@jackpoz Compiler was GCC, pch or no-pch i don't know, it was default config, i have custom changes most of them are unrelated, but transmogrify and  crossfaction  may  related

**Comment by jackpoz** [comment] 2016-09-07 09:05
point is even if the changes might look unrelated because they are not in the same file as the crash, there's a chance the cause might be related to custom changes.
could you please try to always clear your build folder and do a full build instead of incremental one ?
could you push your modified sources somewhere on your fork so we can give it a try locally ?

**Comment by Aokromes** [comment] 2016-11-14 16:42
Still no answer to jackpoz's request

**Comment by Aokromes** [comment] 2016-11-26 04:33
no answer after 12d, closing, if this bug is still valid open a new ticket on one updated core.

**Closed by Aokromes** 2016-11-26 04:33 UTC
Labels: Feedback-WaitingResponse, HasBacktrace
