### ISSUE TITLE
Worldserver.exe crash.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19228] opened 2017-03-01 04:05 UTC
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Before you tell me that the hash of the log does not belong to Trinity keep in mind that this branch only has added the 3 PRs that are currently waiting for revision, the rest is pure Trinity lol. Also I think the crash has to do with the handling of the db2 by the core.
[21ee33610f2f_worldserver.exe_[28-2_13-51-20].txt](https://github.com/TrinityCore/TrinityCore/files/809654/21ee33610f2f_worldserver.exe_.28-2_13-51-20.txt)

**Branch(es):**

Master

**TC rev. hash/commit:** 
8ad043ba692ad4cfaca24fb086053ae046467b4e

**TDB version:**  7.0.3+updates

**Operating system:** Read logs

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Ovahlord** [comment] 2017-03-01 10:00
Did you modify your DB2 files in any way or do you use outdated ones?

**Comment by DDuarte** [comment] 2017-03-01 12:47
Duplicate of #19218

**Closed by DDuarte** 2017-03-01 12:47 UTC
Labels: Branch-master, Comp-Core, HasBacktrace, Invalid-Duplicate
