### ISSUE TITLE
[7.x] Worldserver don't launch correctly (DB2)

### ISSUE THREAD

**Issue by emilieAnd** [TrinityCore/TrinityCore#18156] opened 2016-10-28 07:19 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Server don't launch

**Current behaviour:** When i launch : worldserver i have this error : 

Loading Trinity strings...
>> Loaded 1054 trinity strings in 1 ms
Initialize data stores...
Segmentation fault

**Expected behaviour:** i have extract  all the DB2 from the game (full game)

i have 566 db2 and still have the problem, i have update all the SQL patch and still have this

**Steps to reproduce the problem:**

1. git pull the core
2. update the sql
3. extract the DB2
4. launch the worldserver

**Branch(es):**  Branch : master (7.1.0)

**TC rev. hash/commit:**  e9fb1301e9b53f8ebc88d5f984524f131d794b61

**TDB version:**  6.04

**Operating system:**  linux

**Logs:** http://pastebin.com/ji4DeCXz

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by LuigiElleBalotta** [comment] 2016-10-28 08:54
I know that most people here won't suggest this, but try to download them from a repack to know if it's tour fault or tc fault

**Comment by emilieAnd** [comment] 2016-10-28 09:03
0 Repack found in 7.1 :/

**Comment by jackpoz** [comment] 2016-10-28 09:27
When reporting crashlogs that are 100% reproducible please do that building in Debug mode first

**Comment by Aokromes** [comment] 2016-10-28 09:40
Also, fix this:
TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Unix, Release, Static) (worldserver-daemon)

**Comment by emilieAnd** [comment] 2016-10-28 10:20
Hi @jackpoz / @Aokromes 

I didn't notice sorry, i already try the cmake in debug mode.

**Comment by emilieAnd** [comment] 2016-10-28 11:26
@jackpoz @Aokromes Maybe some trouble with the DB ? should i check ?

**Comment by jackpoz** [comment] 2016-10-28 12:16
still waiting for the actual crashlog

**Comment by cocolino** [comment] 2016-10-28 13:57
7.1 has 569 db2 files and 31 gt files and you can get them using CASCExplorer directly from the viewed data.

**Comment by Aokromes** [comment] 2016-10-28 14:00
yeah indeed, master is 7.1.0 not 7.0.3 update your client.

**Comment by emilieAnd** [comment] 2016-10-28 14:17
i just extracted all the db2 with the CASCExplorer i have 569 you're right, but still have the same error and yes @Aokromes i'm in 7.1.0 sorry my fault i edited now

**Comment by cocolino** [comment] 2016-10-28 14:25
src/tools/map_extractor/loadlib/DBFilesClientList.h try to remove the 3 deprecated db2's, and after check the structs in metadata versus ones in db2structure. Changed extra in 7.1 from 7.0.3: QuestPOIBlobEntry, PvpTalent, PvpTalentUnlock, GarrMission. If you have any of these the structure must be corrected and synced with the MetaData. Some stuff there is wrong too (example PvpTalentUnlockMeta is bbb, not iii, but that's a different conversation). To see exactly what is going on and where it crashes i suggest you to compile in debug and open vs and attach it to worldserver process. That way you can catch the crash in VS and check the call stacks and debug data to see exactly what storage file it crashes on, and from there you can check and fix it / we can help further.

**Comment by cocolino** [comment] 2016-10-28 14:34
Before any of these though please check your db2's are in the correct folder for your locale (example, for us, they should be placed in dbc/enUS, and that you have the game tables in the gt folder too (the dbc and gt folders should be in the worldserver launch app location).

**Comment by emilieAnd** [comment] 2016-10-28 14:41
@cocolino Already try to get the crash log but didn't work, https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/?#comment-47672
i don't know why but nothing happened when i launch the file with the command line : screen -A -m -d -S tri_world gdb -x crashreport.gdb ./worldserver -c ../etc/worldserver.conf

Already fix for the rev and already check the .conf for the enUS db2 files, and yes they are all in the good emplacement

Anyway thank you for you help ! and your time !

**Comment by jackpoz** [comment] 2016-10-28 14:44
@Aokromes 
```
gdb -x crashreport.gdb ./worldserver -c ../etc/worldserver.conf
```
should be enough to get a crashlog (skipping the screen part)

**Comment by emilieAnd** [comment] 2016-10-28 14:48
@jackpoz gdb: command not found

**Comment by emilieAnd** [comment] 2016-10-28 14:58
@jackpoz @Aokromes @cocolino Crashlog:  http://pastebin.com/zAGXPkqh

**Comment by cocolino** [comment] 2016-10-28 15:08
Yes well it tells you the problem, "Used MySQL library version (%s) does not match the version used to compile TrinityCore (%s). Search on forum for TCE00011.". Your libmysql.dll is probably from an outdated version of mysql and you should update it (check the minimum version requirements TC has - if you have at least that version installed you can go to the installation folder and copy the file from the lib folder there to the server launch folder).

**Comment by jackpoz** [comment] 2016-10-28 15:17
it doesn't mean it's outdated, it means the MySQL sources don't match the MySQL binaries (also on linux there's no *.dll). the forum most likely explains more in detail about the issue.

since this is a user issue and not an actual code error I'm closing the issue (users can still comment/help)

**Closed by jackpoz** 2016-10-28 15:17 UTC
Labels: Branch-master

**Comment by emilieAnd** [comment] 2016-10-29 03:42
@jackpoz @Aokromes @cocolino Anyone of you know how can i fix that ?

crash log : http://pastebin.com/fxhr84DZ

Thank you for your time !

**Comment by tkrokli** [comment] 2016-10-29 09:19
@emilieAnd : I am not an expert on debug logs, so I may be wrong in my assumptions or guesses.
To me, it looks more like some kind of OS performance problem, not sure if it is related to hardware.

**Comment by b0ne** [comment] 2016-10-30 15:40
I have the same problem on linux @emilieAnd  did you find a solution...

**Comment by tkrokli** [comment] 2016-10-30 16:08
Is this similar or related to [**[7.1] Can't start server under linux / DB2 error**](18166) #18166 ?
If yes, please follow the other (open) issue.

**Comment by tkrokli** [comment] 2016-10-30 19:04
Sorry, browser page mixup.
