### ISSUE TITLE
[3.3.5] Blizzard skill animation does not end

### ISSUE THREAD

**Issue by Wombyte2** [TrinityCore/TrinityCore#25604] opened 2020-10-23 13:26 UTC
**Description:**

Sometimes when casting "Blizzard" (the mage skill) the animation does not end. 
I can't tell what's the reason for this, it might be if you get interrupted while casting it, but i'm not sure about that.

**Expected behaviour:**

If you end casting the skill, the animation should end. 

**Steps to reproduce the problem:**

1. Cast Blizzard while in battle. It won't happen very often, we usually have this 1-2 times while in a dungeon. 

**Branch(es):**

3.3.5 October 2020 release

**Comment by offl** [comment] 2020-10-23 13:33
Duplicate of #5727

**Closed by offl** 2020-10-23 13:33 UTC
Labels: Branch-3.3.5a, Invalid-IncompleteData/OrNotTrinityCore
