### ISSUE TITLE
[Crash-6.x]  0x0000000000dc3ab5 in GameObject::UpdateRotationFields (this=0x0, rotation2=rotation2@entry=1, rotation3=rotation3@entry=0,000199999995) at /home/wod/TrinityCore/src/server/game/Entities/GameObject/GameObject.cpp:1936

### ISSUE THREAD

**Issue by Darkiu** [TrinityCore/TrinityCore#14906] opened 2015-06-17 17:29 UTC
We tested the BGs of Strand of the Ancients and has given us the next crash.

REV: https://github.com/TrinityCore/TrinityCore/commit/d2142ac380863716ecea6f4aa44f7e556e44dfd9

Link: http://pastebin.com/2p8aL9Px

Thanks.

**Comment by jackpoz** [comment] 2015-06-17 17:54
Looks like a NULL deref caused by gameobjects not being spawing, there should be an error logged too about gameobjects

**Comment by Aokromes** [comment] 2015-11-03 20:04
To long time since the last crash closing, if anyone have any new crash related to this open a new ticket.

**Closed by Aokromes** 2015-11-03 20:04 UTC
Labels: Branch-6.x, HasBacktrace
