### ISSUE TITLE
[3.3.5a] Can cast on fear if rooted

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#13964] opened 2015-01-27 17:25 UTC
Core rev: https://github.com/TrinityCore/TrinityCore/commit/0b8a86886bec1979b698b4109c1f667ba1257fc0

When you are on fear and then you get rooted, you can cast when rooted (until roots end), even dispel the fear.

Screenshots (in this case I used .aura just to not login with a third account, I used root spell 64695 which is the roots of the shaman totem: http://www.wowhead.com/spell=64695/earthgrab (tested without .aura and it got bugged too), tested with frost nova and the same):

![](http://puu.sh/f6tF7/ec2b3d0ede.jpg)
![](http://puu.sh/f6tFP/ee4b1dfbeb.jpg)
![](http://puu.sh/f6tGv/99ab292ed5.jpg)

Notice that as soon as I got rooted, I was able to cast anything.

When roots end, if you are still in fear, you start to move in fear again and you can't cast so the bug is only when you are rooted.

**Comment by Raydor** [comment] 2015-01-27 19:43
In 

    void Unit::SetControlled(bool apply, UnitState state) 

inside

    case UNIT_STATE_ROOT:

I deleted:

    if (HasUnitState(UNIT_STATE_FLEEING))
        SetFeared(false);

It fixed my issue, I don't know what bad behaviour can cause the delete of that, just put it here so devs can see better where is the issue and fix it correctly (I don't think deleting that is the correct way).

**Comment by xiledra** [comment] 2015-05-01 02:27
http://pastebin.com/sJHhWyNu disabled returning client controll to player with fear under root effects

**Comment by Raydor** [comment] 2015-05-01 08:38
@xiledra not working, try it yourself, cast fear and then root (only this way because casting first root and then fear is working correctly), the enemy cast still cast, but with your patch, the difference is that my spells are dark (like when you can't cast, but still can cast them).

I fixed this issue by moving if (!isFear) return; to the start of the function http://puu.sh/hxh2r/8c32bf1d2f.png

**Comment by xiledra** [comment] 2015-05-01 13:12
Oh well, I see.
Well, moving it to the start of function would just be reverting of https://github.com/TrinityCore/TrinityCore/pull/13095 which will make your character to teleport again with roots & fear... If you add http://pastebin.com/xr3CCN8s to the 1st part it won't teleport you and it will not allow you to cast spells with fear.

**Comment by Raydor** [comment] 2015-05-01 19:13
Looks like it's working ok now.

**Comment by tkrokli** [comment] 2015-05-01 21:28
Would you like to share with us which solution made it work for you? :smirk_cat:

**Comment by Raydor** [comment] 2015-05-02 08:17
@tkrokli Implementing everything @xiledra said :D

**Comment by tkrokli** [comment] 2015-05-02 16:28
OK, that sounds nice. Did it cause any other bugs, or do you think it is worth while creating a PR on it?

**Comment by xiledra** [comment] 2015-05-02 17:20
Well, I think I have found another solution for this... http://pastebin.com/WePNFChs
Currently there is disabled call for StopMoving() for players in SetRooted(true) and SetStunned(true) functions, but it is called anyway in FleeingMovementGenerator<Player>::DoFinalize(Player* owner).

It should be enough to just enable StopMoving() while setting rooted / stunned state and forget about calling SetFeared(false), which also allowed player to cast spells.

It works pretty much the same way as what I have sent above, it just avoid unnecessary calls for SetFeared(false), which in fact used only StopMoving() after patch above :D

**Comment by tkrokli** [comment] 2015-05-02 17:49
Thanks for your reply, I'm just thinking that if you have to apply the extra fix for the game to work correctly and blizzlike, perhaps this indicates that the fix is needed in the TC source. Or did I miss something?

**Comment by xiledra** [comment] 2015-05-02 18:00
Well, you are right, but I do not have fork on github and I have not found any way to create pull request across two different git servers... Maybe someone else could create pull request?

**Comment by tkrokli** [comment] 2015-05-02 18:28
> Well, you are right, but I do not have fork on github and I have not found any way to create pull request across two different git servers... Maybe someone else could create pull request?

I have got current forks on github, frequently updated and no PR going currently. If you like, I can create a PR and give you credit for the source. :smirk_cat:

**Comment by xiledra** [comment] 2015-05-02 18:34
Well, if you want to, feel free then, I would appreciate it :D

**Comment by tkrokli** [comment] 2015-05-02 22:31
The line numbers in the source have changed since your diff was made, @Xiledria.
This is what the diff looks like now: http://pastebin.com/ws0riJ2i

**Comment by Xiledria** [comment] 2015-05-02 22:48
Oh, I am sorry for that, it is caused by my custom modifications in core :\
Anyways, its a bit different - above roots is something same thing under stun (line 15537)
You can replace SetFeared() there too, because it is not realy necessary there to end fear (even though it is not possible to cast, because you still have stun aura)

**Comment by tkrokli** [comment] 2015-05-02 22:51
> You can replace SetFeared() there too, because it is not realy necessary there to end fear (even though it is not possible to cast, because you still have stun aura)

I not sure if I want to change it, unless you think it will make the code better, as in "not wasting resources".

**Comment by Xiledria** [comment] 2015-05-02 23:02
Well, it is some kind of limitation of Github, because if you look at the very begining there are some meta datas about file
17961 lines (15697 sloc)  687.314 kb
it has 17961 lines, but only 13026 of them are shown :\ it is still possible to display it in raw mode (but there are no lines)

**Comment by tkrokli** [comment] 2015-05-02 23:05
OK, maybe you can just refer the code sections in a post, with ```cpp on a blank line above the text? :-)

**Comment by Xiledria** [comment] 2015-05-02 23:14
That section is visible on your paste - http://pastebin.com/ws0riJ2i
That CastStop() should not be deleted, but these 3 lines above it could be
Something like http://pastebin.com/USXv5pzR (the 1st part of it)

**Comment by tkrokli** [comment] 2015-05-03 00:07
OK, I found it now by looking up line 15537 in my local file. The section is exactly like the one I removed before (or did something happen that did not remove it?). Anyway, seems I may have misread something.

**Comment by tkrokli** [comment] 2015-05-03 00:10
Removed line 15535-15537 and updated the commit.

**Comment by Xiledria** [comment] 2015-05-03 00:19
Now it looks the same, thanks for your pull request, I appreciate your help :)

**Comment by tkrokli** [comment] 2015-05-03 00:22
You are very welcome. Since I'm not a real programmer, I place my trust in those who knows the code. :+1:

**Comment by tkrokli** [comment] 2015-05-05 17:15
@Xiledria : just out of curiosity, I looked up your github account and I found https://github.com/Xiledria/TrinityCore/tree/3.3.5 which seems to be an updated fork of the TC source here on github. :smirk_cat:

**Comment by Xiledria** [comment] 2015-05-05 18:25
@tkrokli Well, I forked it few hours after your pull request ^^
I have some other bug fixes, so I though I could share them, but I had no time for it yet :\
(exams at school and so on...)
It will be easier to create pull request from clear TC than making diffs from modified core and posting them in issues :D
Atleast it won't cause any further complications because of different line numbers and in some places different structure :D

**Comment by Frytiks** [comment] 2015-05-05 18:56
Maybe u can post there diff if u want. I will convert, cleanup and prepare it

**Comment by Aokromes** [comment] 2015-05-06 18:41
c54cbeb

**Closed** 2015-05-06 18:40 UTC
Labels: Branch-3.3.5a, Comp-Core

**Comment by tkrokli** [comment] 2015-05-06 18:48
Credit: @Xiledria -- see also PR #14641 and https://github.com/TrinityCore/TrinityCore/commit/1161295f4f933661ea9738e0c57049a1e38ec8f2
