### ISSUE TITLE
NPC: Empoor non Blizz like behavior

### ISSUE THREAD

**Issue by Jonne733** [TrinityCore/TrinityCore#22016] opened 2018-06-11 00:07 UTC
**Description:**
You do not have to fight [Empoor](https://woehead.way-of-elendil.fr/?npc=18482) when he has the quest [Wind Trader Lathrai](https://woehead.way-of-elendil.fr/?quest=9979) available and he is patrolling. Which you have to do on live servers.

**Current behaviour:**
No fighting is needed and you can just pick the quest up normally.

**Expected behaviour:**
If for some reason you don't immediately accept the quest [Wind Trader Lathrai](https://woehead.way-of-elendil.fr/?quest=9979) from Empoor after turning in [the previous one](https://woehead.way-of-elendil.fr/?quest=9978) and instead wait for him go back to patrolling the yellow "!" will disappear above his head and a gossip option will instead be available. It will say "Tell me again what you know!" as you can see in the fallowing screenshot: 
![empoor_gossip](https://user-images.githubusercontent.com/40151102/41207546-5d4ba1e6-6d18-11e8-9620-593990b5c926.jpg)

This particular one I couldn't find in the "gossip_menu_options" table.
After you turn the quest in to [Wind Trader Lathrai](https://woehead.way-of-elendil.fr/?npc=18484) the gossip option will no longer be available.

**Steps to reproduce the problem:**

1.  Turn in quest the [By Any Means Necessary](https://woehead.way-of-elendil.fr/?quest=9978) to Empoor
2. Don't accept the fallowing quest and instead let him return to patrolling.

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 5fa783bd34d8e5b32aded6b87a1e4b196b7c4022
**TDB version**: ed63d15
**Operating system:** Windows 10

**Additional info**

- This is info taken from live server
- This issue is semi related to [this one](https://github.com/TrinityCore/TrinityCore/issues/22015).

**Comment by illfated** [comment] 2018-06-11 02:00
Duplicate of issue https://github.com/TrinityCore/TrinityCore/issues/22015 . (The gossip and behaviour of the NPC Empoor is directly related to the quest, not "semi related".)

**Comment by Jonne733** [comment] 2018-06-11 08:02
Hmm, fair enough. I wasn't really sure if I should put them as the same issue or separate. But choose separate because one happens during a quest and the other is before taking the followup quest which comes after, and also that they use two separate "gossip_menu_option" where one exist and the other one dose not as far as I could see.
But if you guys feel that this is an duplicate issue of my previous one I suppose I could  just merge them into one.

**Comment by illfated** [comment] 2018-06-11 17:02
OK, fair enough. I agree.

**Closed** 2018-06-13 19:54 UTC
Labels: Comp-Database, Sub-Quests
