### ISSUE TITLE
Black Morass spawns first 7 portals almost instantly

### ISSUE THREAD

**Issue by Kensaki** [TrinityCore/TrinityCore#17088] opened 2016-05-06 11:18 UTC
**Description**:  
Black Morass seems really bugged, it spawns the first 7 portals almost instantly, spawning the mobs on top of eachother. And only the rift mob spawns, no whelps or adds. After first boss they seem to work as normal minus the adds.
Also bosses in the instance can be stunned and interrupted.

**Current Behavior**:
The first 7 portals leading up to the first boss spawn quickly after eachother leaving no time to clear the spawned mob before the next portal. The mob spawned just stands still for a long while until it despawns.

**Expected Behaviour**:  
There is supposed to be a timer between each portal spawning, the mob spawned should, if not engaged for a little while(dont know how long) run to the dark portal and start wearing down medivhs shield. Also adds should spawn with each portal.

**Branch(es)**: 335/6x  
335

**TC hash/commit**:  
d82534a7bbd4

**TDB version**:  
TDB_full_world_335.61_2016_04_11

**Operating system**:  
windows 8.1

**Comment by jackpoz** [comment] 2016-05-06 15:10
few months (years ?) ago it was spawning the portals correctly

**Comment by jackpoz** [comment] 2016-05-06 15:18
Also
>**Description**:
**Current behaviour**: Tell us what happens
**Expected behaviour**: Tell us what should happen instead

you didn't specify the Expected behaviour about "it spawns the first 7 portals almost instantly" part

**Comment by Aokromes** [comment] 2016-05-06 15:29
Nothing changed there since late 2014.
https://github.com/TrinityCore/TrinityCore/commit/79b9ca4a58175bcbfe859446dbb36ba4b30216b9

**Comment by Kensaki** [comment] 2016-05-06 17:37
Updated the first post with behaviours. Sorry

Am I the only one experiencing this issue? Just wondering if it's something I have done wrong

**Comment by jackpoz** [comment] 2016-05-06 22:00
This is caused by Portal channelling http://wotlk.openwow.com/spell=31387 being interrupted by the spell cast itself https://gist.github.com/jackpoz/1f18c3de9ca858c2e478a568800b56aa

**Comment by jackpoz** [comment] 2016-05-06 22:13
Fixed with https://github.com/TrinityCore/TrinityCore/commit/66006e3d0dd499152ce367e72fbf223356670eb6 .
Tested ingame, the first portal is the only one active till boss is killed

**Closed by jackpoz** 2016-05-06 22:13 UTC
Labels: Sub-Spells
