### ISSUE TITLE
Objects are not updated on quest status change

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#23734] opened 2019-08-23 16:23 UTC
**Description:**

When quest status changes, related conditions are not reloaded and player cannot interact with objects.

Example cases:
- GO_FLAG_INTERACT_COND   = 0x00000004 - when accepting quest that requires looting an GO, this GO is not lootable
- GO_FLAG_IDK = 0x00010000 - when accepting quest that requires interaction with GO, this flag should make the GO glow. It doesn't.
- CONDITION_SOURCE_TYPE_SPELL_CLICK_EVENT when CONDITION_QUESTTAKEN - when accepting quest that requires interaction with NPC with spellclick, this spellclick is now shown

I don't remember if this should be fixed only for new accepted quests, or also other quest statuses. 

**Current behaviour:**

Objects are not updated according to actual conditions, resulting in non-interactable objects. Relog makes an update and they are fine afterwards.

**Expected behaviour:**

Objects should be updated according to current condition status.

**Steps to reproduce the problem:**

1. .go xyz -10952 1561 47 0 
2. .quest add 26295
3. book on the barrel is not lootable
4. relog (or .gm off)
5. book is now lootable

**Branch(es):**

master

**TC rev. hash/commit:** 

a778f757836f7173eff4674fca94ce081f62d8e8

**Operating system:** Win 10 Pro x64

**Comment by funjoker** [comment] 2021-11-22 16:35
The cause is inside Player.cpp

inside
`void Player::UpdateForQuestWorldObjects()`
in the check:
`if (sObjectMgr->IsGameObjectForQuests(obj->GetEntry()))`

Normally goobers and other gameobjects which are used in quests have the questID inside their data columns.
Goobers for example in data1.

If a gameobject has a questID linked in their template IsGameObjectForQuests returns true.

In the newer expansions blizard changed their system since they added Objective based quests.
Now the Objective contains the related gameobjectID.

So old-style quests (cata bla) work.
And newer won't work properly.

I recommend replacing
`if (sObjectMgr->IsGameObjectForQuests(obj->GetEntry()))`
with
`if (obj->ActivateToQuest(this))`

ActivateToQuest also covers the gameobjects which have no quest link in their data fields

**Comment by funjoker** [comment] 2021-12-05 04:11
Should be fixed in 6e5f35a14ce0b894d95434f27fab8f7d0ba6dedc

**Comment by Shauren** [comment] 2021-12-05 11:15
That quest doesn't work but for a different reason, loot is now moved to personalLoot field (which is not implemented)

**Closed** 2021-12-05 11:15 UTC
Labels: Branch-master
