### ISSUE TITLE
Core/Movement: infinite loop

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#23883] opened 2019-10-22 09:40 UTC
> yes @ccrs this line: i_motionMaster->AddToWorld();

> causes the infinite loop, when you attempt to login on any character the worldserver is stale. Loading screen never ends and no further progress can be done.

> and this is on revision: e1df7b7

e1df7b7

**Comment by ccrs** [comment] 2019-10-22 09:41
ref https://github.com/TrinityCore/TrinityCore/commit/d033032d33cff5dae76000f8432d78746cda9e06#commitcomment-35605170

**Comment by ccrs** [comment] 2019-10-22 09:41
I need a crashlog, a callstack, something

**Comment by jackpoz** [comment] 2019-10-22 09:56
How to reproduce steps:
- Login

**Comment by jackpoz** [comment] 2019-10-22 10:19
Also while at it make sure it fixes the crash described at https://github.com/TrinityCore/TrinityCore/issues/23199#issuecomment-544193144 since that was the whole point of the code

**Comment by ccrs** [comment] 2019-10-22 10:32
well the commit goes beyond that, but sure, that was the focus 👍

**Comment by ccrs** [comment] 2019-10-22 10:40
there is a movement action that resolves into adding a new movement action, but I need to know which, that callstack, the crashlog

**Comment by Shauren** [comment] 2019-10-22 11:04
If you get infinite loop - attach debugger and hit the pause button... debuggers have this "fancy" feature that you can stop execution at any point, not just breakpoint/crashes

**Comment by jackpoz** [comment] 2019-10-22 12:34
@Shauren you might want to explain how a debugger works to who wrote the code

**Comment by ccrs** [comment] 2019-10-22 12:44
Chill man, I already told I cant have access to a full set up

**Comment by jackpoz** [comment] 2019-10-22 12:51
Then please stop pushing code to the main branches, push your changes as PRs so someone else with a "full setup" can check your code

**Comment by shenhuyong** [comment] 2019-10-22 15:11
Yes, 5d056f37c74b652b3a3372d6aa88ac5e183f9d98 fixed infinite loop when players login game, but if someone teleport into a battleground, the infinite loop is back.

**Comment by VincentVanclef** [comment] 2019-10-22 15:20
Ah, I havent tried login into a battleground :P

**Comment by ccrs** [comment] 2019-10-22 15:28
that doesn't make sense, can you please provide more information?
Is that player already logged in --> accepts battleground queue --> is teleported?
Does that player log directly into the battleground?

**Comment by ccrs** [comment] 2019-10-22 15:29
@jackpoz can you please confirm this?

**Comment by shenhuyong** [comment] 2019-10-22 15:37
@ccrs How to reproduce steps:
.debug bg
Into a AV queue
Accept into BG
then you can see the loading screen some hours.

**Comment by Aokromes** [comment] 2019-10-22 16:20
[18:18:04] TrinityCore rev. 5e1b828365b6 2019-10-22 16:07:26 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
[18:18:54] Battlegrounds are set to 1v0 for debugging.
[18:19:19] You have joined a raid group.
[18:19:19] [1]  Changed Channel: [1. General - Alterac Valley]
[18:19:19] [2]  Left Channel: [2. Trade - City]
[18:19:19] [3]  Changed Channel: [3. LocalDefense - Alterac Valley]
[18:19:19] [4]  Left Channel: [4. LookingForGroup]
[18:19:20] The battle begins in 2 minutes!

No freeze.

**Comment by Tauriella** [comment] 2019-10-22 17:04
This Bug is not realy fixed
You can now login but if you play a less time you loos the connect and you cant relog

**Comment by jackpoz** [comment] 2019-10-22 18:31
>worldserver.exe!std::deque<MotionMaster::DelayedAction,std::allocator<MotionMaster::DelayedAction>>::emplace_back<std::function<void __cdecl(void)>,enum MotionMasterDelayedActionType>(std::function<void __cdecl(void)> && <_Val_0>, MotionMasterDelayedActionType && <_Val_1>) Line 836	C++
 	worldserver.exe!MotionMaster::Clear() Line 436	C++
 	worldserver.exe!MotionMaster::Clear::__l5::<lambda>() Line 435	C++
 	worldserver.exe!std::_Invoker_functor::_Call<void <lambda>(void) &>(MotionMaster::Clear::__l5::void <lambda>(void) & _Obj) Line 1571	C++
 	worldserver.exe!std::invoke<void <lambda>(void) &>(MotionMaster::Clear::__l5::void <lambda>(void) & _Obj) Line 1571	C++
 	worldserver.exe!std::_Invoker_ret<void,1>::_Call<void <lambda>(void) &>(MotionMaster::Clear::__l5::void <lambda>(void) & <_Vals_0>) Line 1590	C++
 	worldserver.exe!std::_Func_impl_no_alloc<void <lambda>(void),void>::_Do_call() Line 965	C++
 	worldserver.exe!std::_Func_class<void>::operator()() Line 1008	C++
 	worldserver.exe!MotionMaster::DelayedAction::Resolve() Line 107	C++
 	worldserver.exe!MotionMaster::ResolveDelayedActions() Line 1039	C++
 	worldserver.exe!MotionMaster::Update(unsigned int diff) Line 324	C++
 	worldserver.exe!Unit::Update(unsigned int p_time) Line 459	C++
 	worldserver.exe!Creature::Update(unsigned int diff) Line 751	C++
 	worldserver.exe!Trinity::ObjectUpdater::Visit<Creature>(GridRefManager<Creature> & m) Line 406	C++
 	worldserver.exe!VisitorHelper<Trinity::ObjectUpdater,Creature>(Trinity::ObjectUpdater & v, ContainerMapList<Creature> & c) Line 46	C++
 	worldserver.exe!VisitorHelper<Trinity::ObjectUpdater,Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>(Trinity::ObjectUpdater & v, ContainerMapList<TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>> & c) Line 52	C++
 	worldserver.exe!VisitorHelper<Trinity::ObjectUpdater,GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>(Trinity::ObjectUpdater & v, ContainerMapList<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>> & c) Line 53	C++
 	worldserver.exe!VisitorHelper<Trinity::ObjectUpdater,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>>(Trinity::ObjectUpdater & v, TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>> & c) Line 59	C++
 	worldserver.exe!TypeContainerVisitor<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>>>::Visit(TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>> & c) Line 93	C++
 	worldserver.exe!Grid<Player,TypeList<Player,TypeList<Creature,TypeList<Corpse,TypeList<DynamicObject,TypeNull>>>>,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>>::Visit<Trinity::ObjectUpdater>(TypeContainerVisitor<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>>> & visitor) Line 92	C++
 	worldserver.exe!NGrid<8,Player,TypeList<Player,TypeList<Creature,TypeList<Corpse,TypeList<DynamicObject,TypeNull>>>>,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>>::VisitGrid<Trinity::ObjectUpdater,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>>(const unsigned int x, const unsigned int y, TypeContainerVisitor<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>>> & visitor) Line 154	C++
 	worldserver.exe!Map::Visit<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>>>(const Cell & cell, TypeContainerVisitor<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>>> & visitor) Line 972	C++
 	worldserver.exe!Map::VisitNearbyCellsOf(WorldObject * obj, TypeContainerVisitor<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull>>>>>> & gridVisitor, TypeContainerVisitor<Trinity::ObjectUpdater,TypeMapContainer<TypeList<Player,TypeList<Creature,TypeList<Corpse,TypeList<DynamicObject,TypeNull>>>>>> & worldVisitor) Line 733	C++
 	worldserver.exe!Map::Update(unsigned int t_diff) Line 802	C++
 	worldserver.exe!MapUpdateRequest::call() Line 43	C++
 	worldserver.exe!MapUpdater::WorkerThread() Line 115	C++
 	worldserver.exe!std::_Invoker_pmf_pointer::_Call<void (__cdecl MapUpdater::*)(void),MapUpdater *>(void(MapUpdater::*)() _Pmf, MapUpdater * && _Arg1) Line 1571	C++
 	worldserver.exe!std::invoke<void (__cdecl MapUpdater::*)(void),MapUpdater *>(void(MapUpdater::*)() && _Obj, MapUpdater * && <_Args_0>) Line 1571	C++
 	worldserver.exe!std::thread::_Invoke<std::tuple<void (__cdecl MapUpdater::*)(void),MapUpdater *>,0,1>(void * _RawVals) Line 40	C++
 	ucrtbased.dll!invoke_thread_procedure(unsigned int(*)(void *) procedure, void * const context) Line 92	C++
 	ucrtbased.dll!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const parameter) Line 115	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

**Comment by jackpoz** [comment] 2019-10-22 18:34
@ccrs what about reverting everything and working in a PR ?

**Comment by jackpoz** [comment] 2019-10-22 18:43
Full crashlog https://gist.github.com/jackpoz/8c014ca46d59380dfcfd0e8e98ba1496

**Closed** 2019-10-23 01:29 UTC
Labels: Branch-3.3.5a, Comp-Core, Priority-Critical, Sub-Movement, help wanted

**Comment by illfated** [comment] 2019-10-23 06:27
Reason for closing? New issue ticket? Commit solving the issue?

**Comment by jackpoz** [comment] 2019-10-23 07:45
https://github.com/TrinityCore/TrinityCore/commit/bc9a9ad7e1226573493e3cb10885365322fdbbbf
