### ISSUE TITLE
Scripts/The Steamvault: boss Warlord Kalithresh --  Warlord's Rage is bugged

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#23827] opened 2019-09-24 22:35 UTC
**Description:**

When fighting https://www.wowhead.com/npc=17798/warlord-kalithresh#encounter, he turns to the Naga Distillers to gain the buff https://www.wowhead.com/spell=36453/warlords-rage, if you destroy the distiller, he still gains the buff.

**Expected behaviour:**

Destroying the Naga Distillers should block Kalithresh from gaining Warlord's Rage.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/c8dc9fdc418d9703893e21603b7593b015f08fea

**Operating system:** Win 10 x64

**Comment by offl** [comment] 2019-10-02 21:56
Duplicate of #16178

**Closed** 2019-10-02 21:58 UTC
Labels: Branch-3.3.5a, Comp-C++Script, Sub-Instances
