### ISSUE TITLE
Core/Movement: Flying npcs remains in the air once dead

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#8204] opened 2012-10-28 18:36 UTC
When a player dies while he's in the air, the body remains in the air instead of falling down to the ground.

This bug makes resurrection spells harder and sometimes impossible to cast. Same with self resurrection.

---

Core  rev. hash: f2e92b81a30da8150d99644c4f112bd712dbf28e
TDB: 335.49+
OS: Unix 64bit

---
##

**Comment by Killyana** [comment] 2015-02-26 20:01
Cannot reproduce on rev. 68c4ea314443, every time I die in the air the corpse fall down.

**Comment by tkrokli** [comment] 2015-05-31 07:26
**jackpoz** commented on 1 Mar 2014 :
> is the body supposed to appear in air and then fall down or it should be spawned on the ground already ?

The body is supposed to fall to the ground. I just tested this on rev. 562da2e8b2b0 2015-05-31 01:01:55 +0200 (3.3.5 branch) (Win64, Release), used a level 64 horde DK character and a level 64 alliance hunter character on the ground, firing at the DK. When the DK died, he lost the flying mount aura and fell down. Then again, when testing a duel between 2 characters, either 2x horde or horde + alliance, the character mounted on the flying mount stayed in the air when defeated, while the duel flag floated up to the defeated character.

While this test seems inconclusive, I flew to Skettis in Terokkar Forest to look for flying enemies. Using the command **.die** on the Monstrous Kaliri birds, they fall down when killed. Also testing the character on a flying mount, I let my character get killed by those NPCs and the dead character fell to the ground (repeatedly).

If there are other ways to test this issue, please explain what to test to replicate the issue properly.

**Comment by emptyus** [comment] 2015-05-31 10:50
tkrokli, jackpoz asked if the body is supposed to do one or the other thing on live severs, actually, what it did in 3.3.5a live, not what happens in TC. :)

Someone should also test following scenario. Fly high, really high, or get to some high grounds, and jump down. I remember that many times your corpse would not spawn on the spot you died on the ground, rather in the air, sometimes making it impossible to resurrect in some cases. I can't do test myself atm.

**Comment by tkrokli** [comment] 2015-05-31 11:56
Well, if he wanted to ask what happens on live servers, he could have said so. Is my testing invalid? I conferred with Aokromes on this, though he told me that this is very, very difficult to test, because you need to be 3 players on a very low latency connection to verify this in a satisfactory manner. If it is not enough to verify this against @Dexie's original post, then this issue will stay open for years to come.

**Comment by Aokromes** [comment] 2015-05-31 12:42
As for creature bodies, it's really easy to test it on the eye's kaelthas on fly phase.

Reproduced on 35f2f5530abc.

http://i.imgur.com/fCEtexl.jpg

**Comment by Killyana** [comment] 2015-05-31 14:12
For kaelthas  it's another issue: the position of the boss is not updated for the clients, if this issue happen go with a gm and you will see kaelthas  in another position in the ground.

**Comment by Goatform** [comment] 2016-09-12 15:30
Not tested and not sure if this is correct:

``` diff

diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index ef92797..eba8180 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -1536,8 +1536,7 @@ void Creature::setDeathState(DeathState s)
         if (m_formation && m_formation->getLeader() == this)
             m_formation->FormationReset(true);
 
-        if ((CanFly() || IsFlying()))
-            GetMotionMaster()->MoveFall();
+        GetMotionMaster()->MoveFall();
 
         Unit::setDeathState(CORPSE);
     }

**Comment by Keader** [comment] 2016-10-25 14:35
any news?

**Comment by ariel-** [comment] 2016-10-25 17:37
Not all creatures should fall on death (see Kologarn for example)

**Comment by Aokromes** [comment] 2017-03-26 00:34
Anything here is valid? if yes, plz open a pr for it.

**Comment by Killyana** [comment] 2019-03-05 15:30
The remaining issue is flying npc remains in the air once dead if they have "CanFly" instead of "DisableGravity".

**Comment by Aokromes** [comment] 2019-03-05 15:52
yeah i got one report yesterday of onixia's body being on air because it was killed to fast.

**Comment by Killyana** [comment] 2019-03-05 16:12
fixed like this:
``` cpp
diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index c3a46e44a2..d5450c6a47 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -1934,9 +1934,7 @@ void Creature::setDeathState(DeathState s)
 
         bool needsFalling = IsFlying() || IsHovering();
         SetHover(false);
-
-        if (needsFalling)
-            GetMotionMaster()->MoveFall();
+        GetMotionMaster()->MoveFall();
 
         Unit::setDeathState(CORPSE);
     }

**Comment by Shauren** [comment] 2019-03-07 10:54
Reason for that is simple
https://github.com/TrinityCore/TrinityCore/blob/70cefbe86616aa6411a85e1622c82c12a1ca67fa/src/server/game/Entities/Unit/Unit.h#L1636
It checks FLYING instead of CAN_FLY flag

Its kind of a weird situation but FLYING flag is set only for players that are in air and have CAN_FLY flag while creatures also use CAN_FLY but never get FLYING one (and this is blizzlike)

**Comment by Killyana** [comment] 2019-03-07 12:37
In this case we need to add CanFly() to needsFalling  or just replace IsFlying() ?

**Comment by Killyana** [comment] 2022-11-20 15:53
Remaining cases fixed on https://github.com/TrinityCore/TrinityCore/commit/441c126002c2f0518ee0c7cafa6453c3f16bec3f

**Closed by Killyana** 2022-11-20 15:53 UTC
Labels: Feedback-FixOutdatedMissingWIP, Comp-Core, Sub-Movement

**Comment by offl** [comment] 2022-11-20 16:24
But C++ scripts should be changed too, some of them should have extra flag and maybe that will be not enough in some cases

**Comment by Killyana** [comment] 2022-11-20 17:05
Yes, kael'thas script for example needs update.

**Comment by offl** [comment] 2022-11-21 14:23
I meant recently updated creatures
It wasn't changed at once for all creatures because that can break some of them now or later
