### ISSUE TITLE
[3.3.5] Core/Scripts/Quest: Massacre at Light's Point

### ISSUE THREAD

**Issue by Demonith** [TrinityCore/TrinityCore#17816] opened 2016-08-19 09:05 UTC
**Description**: 
In their haste, the Crusade will make one fatal error: forgetting to check the mine cars.
You are to return to Havenshire Mine, east of here, and locate the mine car that my minions have planted near the outhouse. Climb inside the mine car and a Scarlet miner will unwittingly see to it that you are placed safely behind enemy lines.

Once aboard one of their ships, use the cannons against them! SLAUGHTER THEM ALL!

Call the Scourge gryphon from the cannon when you are ready to return.

**Current behaviour**: First need to use the mine car to get to the other point, but the enemy discover me every time no matter what.

**Expected behaviour**: While in the cart, the NPC Scarlet Miner should bring me past guards and get me to the ship 

**Steps to reproduce the problem**:

1. Take quest 12701 "Massacre At Light's Point".
2. Only kill NPCs that you aggro on your way to the Mine Car.
3. Enter the Mine Car and see how the NPCs detect you although you are in the cart.

**Branch(es)**: 3.3.5 rev: dc78f1ecfc25

**TDB version**:  3.3.5.61

**Operating system**:  Windows 10

**Comment by Skilledx21** [comment] 2016-08-21 10:39
try this 

`class npc_scarlet_miner_cart : public CreatureScript
{
    public:
        npc_scarlet_miner_cart() : CreatureScript("npc_scarlet_miner_cart") { }

        struct npc_scarlet_miner_cartAI : public PassiveAI
        {
            npc_scarlet_miner_cartAI(Creature* creature) : PassiveAI(creature)
            {
				me->setFaction(35);
				me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC && UNIT_FLAG_IMMUNE_TO_PC);
                me->SetDisplayId(me->GetCreatureTemplate()->Modelid1); // Modelid2 is a horse.
            }
`

**Comment by Demonith** [comment] 2016-08-21 13:02
Can u tell me how to add that

**Comment by Skilledx21** [comment] 2016-08-21 13:07
Go to core Search for Chapter1.cpp Ctrl+F npc_scarlet_miner_cart than u will find 

`                me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);`

replace with 

`                me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC && UNIT_FLAG_IMMUNE_TO_PC);
`

**Comment by Demonith** [comment] 2016-08-21 13:20
Core u mean in folder or in DB with HeidiSQL ?

**Comment by Skilledx21** [comment] 2016-08-21 13:27
@Demonith Yes in trinitycore Folder

**Comment by Demonith** [comment] 2016-08-21 13:31
Do i need compile again ?

**Comment by tkrokli** [comment] 2016-08-21 13:33
Yes, of course. Any and all changes in code needs to be recompiled.

**Comment by Demonith** [comment] 2016-08-21 13:33
Tnx sry for bother :) :+1:

**Comment by Demonith** [comment] 2016-08-21 14:43
Just tested it still aggro when in card but when i try with gm on and gm off and miner dies at half trip ???

**Comment by Skilledx21** [comment] 2016-08-21 14:46
Use .gm on and check why the miner die xD easy

**Comment by Demonith** [comment] 2016-08-21 14:48
But why still aggro when in cart ??

**Comment by Demonith** [comment] 2016-08-21 14:49
https://s14.postimg.io/v752bmild/Wo_WScrn_Shot_082116_164727.jpg

**Comment by Skilledx21** [comment] 2016-08-21 14:51
Try this not sure if its work or not but u can give it a try 
`me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC); `

**Comment by Demonith** [comment] 2016-08-21 14:59
Will try

**Comment by Demonith** [comment] 2016-08-21 15:33
Try this not sure if its work or not but u can give it a try 
me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);

This worked

**Comment by tkrokli** [comment] 2016-08-22 00:48
TrinityCore rev. f183ed3c50cd 2016-08-21 18:02:36 -0300 (3.3.5 branch) (Win64, Release, Static)

Confirmed. Multiple mobs aggro when you enter the mine car, more than the char can handle.
Looks like that `unit_flags` change is needed, but I think it can be done in DB:
```sql
-- Scarlet Enclave, chapter 1: the Mine Car player transforms to should not aggro NPCs
UPDATE `creature_template` SET `unit_flags`= `unit_flags`| 512 WHERE `entry`= 28817;
```
But if that flag is not found in sniffs, it must be set in the script `npc_scarlet_miner_cart` .
***
OK, so it started back in 2012-02-03 (3. February 2012) when QAston made the following changes:
https://github.com/TrinityCore/TrinityCore/commit/c7ea952a4795c959b1d1de02c2cb5e498d6391aa#diff-baeb010bab3defc8b23a63d10965f7e8

```diff
diff --git a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
index a7d1c3a..a2c8a89 100644
--- a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
+++ b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
@@ -125,7 +125,7 @@ public:
             phase = PHASE_CHAINED;
             events.Reset();
             me->setFaction(7);
-            me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_OOC_NOT_ATTACKABLE);
+            me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             me->SetUInt32Value(UNIT_FIELD_BYTES_1, 8);
             me->LoadEquipment(0, true);
         }
@@ -230,7 +230,7 @@ public:
                     else
                     {
                         me->setFaction(14);
-                        me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_OOC_NOT_ATTACKABLE);
+                        me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                         phase = PHASE_ATTACKING;
 
                         if (Player* target = Unit::GetPlayer(*me, playerGUID))
@@ -378,7 +378,7 @@ public:
                     return true;
             }
 
-            creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_OOC_NOT_ATTACKABLE);
+            creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_UNK_15);
 
             int32 uiSayId = rand()% (sizeof(m_auiRandomSay)/sizeof(int32));
@@ -877,7 +877,7 @@ public:
     {
         npc_scarlet_miner_cartAI(Creature* c) : PassiveAI(c), minerGUID(0)
         {
-            me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_OOC_NOT_ATTACKABLE);
+            me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             me->SetDisplayId(me->GetCreatureInfo()->Modelid1); // Modelid2 is a horse.
         }
```
So the proper way to do it is in the script. Here is a diff based on current 3.3.5 rev. f183ed3c50cd :
```diff
diff --git a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
index 3cf78b7..dc91e9d 100644
--- a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
+++ b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
@@ -1023,7 +1023,7 @@ class npc_scarlet_miner_cart : public CreatureScript
         {
             npc_scarlet_miner_cartAI(Creature* creature) : PassiveAI(creature)
             {
-                me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
+                me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                 me->SetDisplayId(me->GetCreatureTemplate()->Modelid1); // Modelid2 is a horse.
             }
```

**Comment by r00ty-tc** [comment] 2016-08-22 19:48
@tkrokli just to say from a sniff (in cata, but still)

[1] UpdateType: CreateObject1
[1] GUID: Full: 0xF1507091001852C8 Type: Vehicle Entry: 28817 Low: 1594056
[1] Object Type: Unit (3) (0x0003)
[1] Update Flags: Living, StationaryObject, Vehicle (224) (0x00E0)
[1] Movement Flags: None (0) (0x0000)
[1] Extra Movement Flags: None (0) (0x0000)
.........
[1] UNIT_FIELD_FLAGS: 520/7.286752E-43
[1] UNIT_FIELD_FLAGS_2: 2048/2.869859E-42

So, I reckon adding 512 was perfectly fine.

**Comment by tkrokli** [comment] 2016-08-23 01:42
Thank you very much for providing the sniff information, r00ty. I had too much difficulty in finding that in the sniff samples I got 6 months ago from Aokromes (from Cata & WotLK). I will close my PR #17844 and repost the SQL update query as the **suggested fix** for this issue:
```sql
-- player transformed to Scarlet Mine Car should not aggro NPCs
UPDATE `creature_template` SET `unit_flags`= `unit_flags`| 512 WHERE `entry`= 28817;
```

**Comment by tkrokli** [comment] 2016-08-23 03:36
Please ignore my statement above. This has to be fixed in the PR, because the lines manipulating UNIT_FIELD_FLAGS in the core script need to be removed too, in addition to setting the flag in DB.

**Comment by tkrokli** [comment] 2016-08-23 04:33
Derp. I did not read your sniff properly and check what the UNIT_FIELD_FLAGS value is (520).

From https://trinitycore.atlassian.net/wiki/display/tc/creature_template#creature_template-unit_flags :

| Flag  | Hex    | Name                     | Comment                                                                              |
| ----- | ------ | ------------------------ | ------------------------------------------------------------------------------------ |
| 8     | 0x0008 | UNIT_FLAG_PVP_ATTACKABLE | Allows to apply PvP rules to attackable state in addition to faction dependent state |
| 512   | 0x0200 | UNIT_FLAG_IMMUNE_TO_NPC  | Disables combat/assistance with NonPlayerCharacters (NPC)                            |

Combined, this makes the `unit_flags` value 520 instead of 512 as I first suggested. Update incoming.

**Comment by r00ty-tc** [comment] 2016-08-23 11:33
Good stuff. Not sure when the cart could be attacked by players mind you (the zone being what it is). But, it's for sure how blizz set it up :)

**Closed** 2016-08-23 23:07 UTC
Labels: Comp-C++Script, Sub-Quests
