### ISSUE TITLE
hangs computer

### ISSUE THREAD

**Issue by ter884** [TrinityCore/TrinityCore#17830] opened 2016-08-20 12:13 UTC
1 - the range of the review 533
![default](https://cloud.githubusercontent.com/assets/6825541/17831108/ead01fde-66e8-11e6-8a8a-15fed40ee5db.PNG)

2 - player level 1 -3
![2](https://cloud.githubusercontent.com/assets/6825541/17831110/ed1640d4-66e8-11e6-8a38-59027ff05c0f.png)

3- fighting them may computer to hang 

chance ~ 50%
it is not very nice. helps only restart the computer.

7.0.3
https://github.com/TrinityCore/TrinityCore/commit/3ab2f69f6459cbf74b32d564634cc266e19b757d

**Comment by Aokromes** [comment] 2016-08-20 12:21
human start zone? if yes. duplicate of #15263

**Closed** 2016-08-20 12:22 UTC
