### ISSUE TITLE
[master] DB/graveyard: Night Elf start zone GY: Westfall (Sentinel Hill)

### ISSUE THREAD

**Issue by adryan66** [TrinityCore/TrinityCore#18432] opened 2016-12-08 11:42 UTC
**Description:**
When you die in Shadowglen you get teleported to a spirit healer in Westfall
**Current behaviour:** (Tell us what happens.)
When you die in Shadowglen you are teleported to Westfall graveyard. Using ".neargrave" says it has no graveyard assigned.
**Expected behaviour:** (Tell us what should happen instead.)
Should be teleported to a graveyard in shadowglen.
**Steps to reproduce the problem:**

1. Create Nightelf Character
2. Die
3. Ressurected in Westfall

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master
**TC rev. hash/commit:**  
TrinityCore rev. bb15e2c158ea
**TDB version:**  
TDB 703.00
**Operating system:**  
Windows 10 Pro x64

Same happens with Pandaren Starting Zone : Zone 5736
Just Tested Bloodelf (6455) also , seems it happens to most starting zones.

**Comment by tkrokli** [comment] 2016-12-08 17:42
In addition to Zone # 6450 not having any linked graveyard, the Spirit Healer is also missing in Shadowglen.
I am not 100% certain, but I guess sniff is needed for exact position + orientation of the Spirit Healer.

**Comment by funjoker** [comment] 2016-12-08 17:47
Well, Spirit Healers are spawns.
GY Locations missing assignment.
Who ever does the Area needs to do the Spirit Healer spawns too.

**Comment by tkrokli** [comment] 2016-12-08 17:55
Zone (`GhostZone`) for Aldrassil, Teldrassil has changed ID from 141 to 6450:
```sql
-- set correct zone for GY Teldrassil, Aldrassil GY - Teldrassil
UPDATE `graveyard_zone` SET `GhostZone`= 6450 WHERE `ID`= 93;
```
Tested in-game and works as intended/expected. Spirit Healer is still missing, though.

**Comment by funjoker** [comment] 2016-12-08 18:06
They have split the whole Zone into smaller Zones. That'S why it is not working anymore.

**Comment by tkrokli** [comment] 2016-12-08 18:08
Wandering Isle does not seem to have any Graveyards yet, lots of stuff missing there anyway (meh).
I can only push the Shadowglen fix for now if really needed, but a Spirit Healer would be nice to have too.

**Comment by tkrokli** [comment] 2016-12-08 18:29
Going to focus this issue to Shadowglen GY, Teldrassil, keeping this issue isolated from Pandaria issues which should be posted separately. If anyone would post the Spirit Healer coordinates from retail sniff, we can close this issue based on fixing the double issue in Shadowglen.

**Comment by adryan66** [comment] 2016-12-08 18:36
A few extra bugs also related to this one : 
Human Start Zone - Good respawn location but no Spirit Healer
Dwarf Start Zone - respawn location is Westfall
Orc Start Zone - Good location but no Spirit Healer
Bloodelf Start Zone - respawn location is Northern Barrens
Undead Start Zone - respawn location is Northern Barrens
Tauren Start Zone - respawn location is Northern Barrens
Troll Start Zone - respawn location is Northern Barrens
Goblin Start Zone - Good location but no Spirit Healer
Bloodelf Demon Hunter - respawn location is Northern Barrens
Nightelf Demon Hunter - respawn location is Westfall

Theese are all of the starting zones issues atm regarding death

**Comment by adryan66** [comment] 2016-12-08 18:48
Coords for the shadowglen spirit healer are 45.9 66.3 , looking south-east. SS Attached
![wowscrnshot_120816_204644](https://cloud.githubusercontent.com/assets/24454600/21023081/a79da196-bd87-11e6-8be8-26134021d78f.jpg)

**Comment by tkrokli** [comment] 2016-12-08 18:50
Could you provide the coordinates in X, Y, Z and Orientation? It would save a lot of time for pushing a fix.

**Comment by Aokromes** [comment] 2016-12-08 18:57
maybe you can take coords from 3.3.5a db

**Comment by funjoker** [comment] 2016-12-08 18:57
If you ahve applied tkroklis SQL.

Can you go into Aldrassil Tree and kill yourself?

**Comment by tkrokli** [comment] 2016-12-08 19:22
I don't think the Spirit Healer spawn point should be the exact same as player ghost point, but I can get you the one I get now on rev. eba8ed329fc5 2016-12-07 23:24:32 +0100 (master branch):

`X: 10384.809570 / Y: 811.531189 / Z: 1317.538208 / O: 1.115265 (player)`

![aldrassil_gy](https://cloud.githubusercontent.com/assets/4903600/21024012/3f94595e-bd83-11e6-9b1a-eda28d572b2e.png)

**Comment by tkrokli** [comment] 2016-12-08 20:27
OK, these are the correct `GhostZone` values so far:
```sql
-- set correct GhostZone for current starter zones in the 'master' branch
UPDATE `graveyard_zone` SET `GhostZone`= 6176 WHERE `ID`= 100; -- Dun Morogh, Anvilmar
UPDATE `graveyard_zone` SET `GhostZone`= 6450 WHERE `ID`= 93; -- Teldrassil, Aldrassil GY
UPDATE `graveyard_zone` SET `GhostZone`= 6452 WHERE `ID`= 34; -- Mulgore, Red Cloud Mesa GY
UPDATE `graveyard_zone` SET `GhostZone`= 6453 WHERE `ID`= 1700; -- Durotar, Echo Isles GY
UPDATE `graveyard_zone` SET `GhostZone`= 6454 WHERE `ID`= 94; -- Tirisfal Glades, Deathknell
UPDATE `graveyard_zone` SET `GhostZone`= 6455, `Faction`= 67 WHERE `ID`= 912; -- Eversong Woods, Sunstrider Isle
UPDATE `graveyard_zone` SET `Comment`= "Eversong Woods, Farstrider Retreat GY - Eversong Woods" WHERE `ID`= 914;
```
I am going to compare the missing Spirit Healer spawns with the coordinates from 3.3.5 and see if they match so they can be reused in `master`. I will not do any of the Demon Hunter graveyards because they have not even been created in the DB yet, because too much info is missing for Pandaria (5.4.8) and later.

**Comment by adryan66** [comment] 2016-12-08 20:59
Cool. Regarding the same thing, the spirit healer at darnassus exit might be missing, will check myself in 2 hours to be sure. Which are the bugs which should be report , any specific or just all of them which aren't reported yet ?

**Comment by tkrokli** [comment] 2016-12-08 21:09
If you can provide a text list something similar to this, it would be helpful for easier access to use in the commit we want to make from the info above.
```
X: 10384.809570 / Y: 811.531189 / Z: 1317.538208 / O: 1.115265 (player) -- Aldrassil GY (master)

Human start zone  - no Spirit Healer
Dwarf Start zone  - no Spirit Healer
Orc start zone    - no Spirit Healer
Troll start zone  - ?
Goblin start zone - no Spirit Healer
```

**Comment by tkrokli** [comment] 2016-12-08 21:34
BTW, you may want to test the Pandaria GY list I updated in https://github.com/TrinityCore/TrinityCore/issues/14160#issuecomment-265854671 .

**Comment by adryan66** [comment] 2016-12-08 21:48
Didn't add those fixes yet, will do , seems i need to check fixes inside the issues threads.
Kinda new to this server , was planning to fix the world issues first but i have the feeling most of those are from wod / legion. Will see what i can help.

**Comment by adryan66** [comment] 2016-12-09 22:29
Added sniffs for the above spirit healers in the sniffs forum topic and another one with 2 zones, can you check and see if they are of any use ?

**Comment by tkrokli** [comment] 2016-12-10 12:21
Myself, I don't have access to the content posted in https://community.trinitycore.org/forum/13-wdbadbsniffs/ , but I hope one of the devs with access can post the related content here. I was hoping to get time to do more with this issue this weekend, but that also depends on what else happens in my offline life.

**Comment by tkrokli** [comment] 2016-12-13 01:35
sniff supplied by Kittnz:
```sql
-- Spirit Healer for 6 starter areas.
SET @CGUID := 452536;

DELETE FROM `creature` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+5;
INSERT INTO `creature` (`guid`,`id`,`map`,`zoneId`,`areaId`,`spawnMask`,`PhaseId`,`PhaseGroup`,`modelid`,`equipment_id`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`spawndist`,`currentwaypoint`,`curhealth`,`curmana`,`MovementType`,`npcflag`,`unit_flags`,`dynamicflags`,`VerifiedBuild`) VALUES
(@CGUID+0, 6491,  0,0,0,1,1,0,0,0, -8946.229, -183.4772, 79.99528, 5.88176,  120,0,0,0,0,0,0,0,0,23222), -- Northshire Valley
(@CGUID+1, 6491,  0,0,0,1,1,0,0,0, -6169.814,  346.8438, 400.1516, 5.27905,  120,0,0,0,0,0,0,0,0,23222), -- Coldridge Valley
(@CGUID+2, 6491,  1,0,0,1,1,0,0,0,  10391.85,  826.4149, 1317.602, 4.118977, 120,0,0,0,0,0,0,0,0,23222), -- Aldrassil
(@CGUID+3, 6491,  1,0,0,1,1,0,0,0, -637.971,  -4295.86,  40.90933, 1.169371, 120,0,0,0,0,0,0,0,0,23222), -- Valley of Trials
(@CGUID+4, 6491,  1,0,0,1,1,0,0,0, -1039.63,  -5416.73,  13.37213, 3.141593, 120,0,0,0,0,0,0,0,0,23222), -- Echo Isles
(@CGUID+5,39660,648,0,0,1,1,0,0,0, -8115.33,   1520.22,  10.34157, 3.193953, 120,0,0,0,0,0,0,0,0,23222); -- Kezan
```
Auras: 9036 (client-side), 10848 (server-side). Only 10848 appears in DB.
- http://www.wowhead.com/spell=9036/ghost
- http://www.wowhead.com/spell=10848/shroud-of-death

**Comment by tkrokli** [comment] 2016-12-13 05:40
Kezan spawn info from sniff was a duplicate, already spawned in DB. Fixed Phase ID for KTC HQ GY instead.

**Closed** 2016-12-13 05:45 UTC
Labels: Branch-master, Comp-Database, Feedback-PatchFix
