### ISSUE TITLE
[ICC Raid]Sister Svalna and Val'kyr Shadowguard

### ISSUE THREAD

**Issue by blackcat2** [TrinityCore/TrinityCore#4495] opened 2011-12-27 01:01 UTC
Hi,

When engaging Sister Svalna, she come down and then she goes underground (below the floor). As a result, players can't target her, she can't be killed and players cannot continue to Valithria Dreamwalker.

This issue also occur while engaging Lich King in phase 2. When Lich King summon Val'kyr Shadowguard, they fly/come down and then they go underground (below platform). As a result they can't be targeted and when they pickup a player, the player gets stuck somewhere below the platform. The only way out is to move a bit and then they die from "falling".

I'm using revision e6a3dc679f96
https://github.com/TrinityCore/TrinityCore/commit/e6a3dc679f96365d2d1883a22cf6fdd2c2602dc0

Compiled with MS Visual Studio Pro 2008, release build, 32 bit.
Database Version: TDB 335.11.44 with updates until rev e6a3dc679f96..

Thanks..
BC

**Comment by Aokromes** [comment] 2016-06-14 06:42
This bug is still valid? if yes, it's related to inhabitat type 4 bug?

**Comment by Killyana** [comment] 2016-06-15 18:17
Probably hover is not removed once the npc turn attackable.

**Comment by Keader** [comment] 2016-10-24 13:05
caused by #15177

**Comment by Aokromes** [comment] 2016-10-24 13:08
then closing this as generic bug.

**Closed by Aokromes** 2016-10-24 13:08 UTC
Labels: Sub-Instances
