### ISSUE TITLE
Spell: Ice Lance

### ISSUE THREAD

**Issue by NiganNi** [TrinityCore/TrinityCore#25760] opened 2020-12-24 13:35 UTC
**Description:**
Ice Lance(class:mage) doesn't work, does not damage

Branch(es):
master

TrinityCore rev. 5710f377e76e 2020-12-23 17:53:13 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

OS: Win

**Steps to reproduce the problem:**
1)Create characters mage.
2)cmd .levelup 9.
3)Use ice talents
4)Use spell Ice Lance ( https://www.wowhead.com/spell=30455/ice-lance )

**Comment by MaxtorCoder** [comment] 2020-12-24 13:39
Duplicate of #19087

**Closed** 2020-12-24 13:57 UTC
Labels: Branch-master, Invalid-IncompleteData/OrNotTrinityCore
