### ISSUE TITLE
[master] [NPC] Worldserver crash when talking to Coldridge Citizen

### ISSUE THREAD

**Issue by AlcDenat** [TrinityCore/TrinityCore#19219] opened 2017-02-27 21:28 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
When talking to any Coldridge Citizen the worldserver crashes
**Current behaviour:** (Tell us what happens.)
worldserver.exe crashes
**Expected behaviour:** (Tell us what should happen instead.)
You should get random gossip from them like in the comments here; http://www.wowhead.com/npc=37218/coldridge-citizen
**Steps to reproduce the problem:**

1. Create any dwarfen charakter
2. Run into Anvilmar 
3. Talk to any Coldridge Citizen

**Branch(es):** master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  87b6b9c27fa5 

**TDB version:**  TDB_world_703.00_2016_10_17.sql + Updates

**Operating system:** Windows Server 2016 standard (with gui)

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ArcaneFox** [comment] 2017-02-27 21:30
https://github.com/TrinityCore/TrinityCore/issues/18935

**Comment by DDuarte** [comment] 2017-02-27 21:37
Post a crashlog.

**Comment by Eredar** [comment] 2017-02-27 23:56
http://www.mediafire.com/file/gnj5nf9paplszxb

**Comment by tortosi** [comment] 2017-02-28 14:56
exactly some problem.

Operating system: Debian jessie 8.7

**Comment by DDuarte** [comment] 2017-03-01 12:40
Duplicate of #19218

**Closed by DDuarte** 2017-03-01 12:40 UTC
Labels: Branch-master, Comp-Core, HasBacktrace, Invalid-Duplicate
