### ISSUE TITLE
[Core/Spell] Warrior Charge

### ISSUE THREAD

**Issue by Nephelion** [TrinityCore/TrinityCore#11526] opened 2014-01-28 15:41 UTC
https://github.com/TrinityCore/TrinityCore/commit/1b48c7b977b19f990b7f1389f48a0a45cdde9784

when charge with warr some time go underground and buged ...
##

**Comment by lainimer** [comment] 2015-02-19 19:43
confirm baged

**Comment by SQLfix** [comment] 2015-03-17 17:58
Any news ?

**Comment by Aokromes** [comment] 2015-03-17 22:19
No.

**Comment by jackpoz** [comment] 2015-06-17 17:42
Please try after https://github.com/TrinityCore/TrinityCore/commit/91c399cad239b20dac68629587e7c8b4ec612be3

**Comment by jackpoz** [comment] 2015-07-02 20:21
any feedback ?

**Comment by ccrs** [comment] 2015-07-02 20:24
I tested it and got same results as https://github.com/TrinityCore/TrinityCore/commit/91c399cad239b20dac68629587e7c8b4ec612be3 comments

**Comment by jackpoz** [comment] 2015-07-02 20:52
No more charge into the void tho ? Can we close this issue?

**Comment by ccrs** [comment] 2015-07-02 20:59
it's so restrictive that I guess yes xd

**Comment by Runico** [comment] 2015-07-02 21:07
No, it still charge into void

**Comment by jackpoz** [comment] 2015-07-03 07:09
@Runico post gps coordinates of start and end position, even better if you post them in the .go xyz format

**Comment by Frytiks** [comment] 2015-07-03 08:56
Add IsArena check With pathfind_nopath should be tempfix

**Comment by Runico** [comment] 2015-07-03 09:25
@jackpoz this is coordinates of start and end position
```
Start Point:
Map: 530 (Outland) Zone: 3522 (Blade's Edge Mountains) Area: 3784 (Forge Camp: Terror) Phase: 4294967295
X: 1453.244507 Y: 7314.201660 Z: 364.589569 Orientation: 3.726342
grid[34,45]cell[5,5] InstanceID: 0
 ZoneX: 28.232836 ZoneY: 81.707520
GroundZ: 364.590057 FloorZ: 364.590057 Have height data (Map: 1 VMap: 1 MMap: 1)
```
End Point:
```
Map: 530 (Outland) Zone: 3522 (Blade's Edge Mountains) Area: 3784 (Forge Camp: Terror) Phase: 4294967295
X: 1437.925903 Y: 7303.247070 Z: 372.203339 Orientation: 3.702782
grid[34,45]cell[5,5] InstanceID: 0
 ZoneX: 28.434763 ZoneY: 82.131081
GroundZ: 372.205139 FloorZ: 372.205139 Have height data (Map: 1 VMap: 1 MMap: 1)
```

**Comment by jackpoz** [comment] 2015-07-04 18:20
.go xyz 1453.244507 7314.201660 364.589569 530
.go xyz 1437.925903 7303.247070 372.203339 530

**Comment by Runico** [comment] 2015-07-04 23:05
@jackpoz it will falling in the ground, just stay at the edge of that place or something

**Comment by jackpoz** [comment] 2015-07-05 09:51
I don't know if there is some missing stuff that should be triggered client-side to avoid making the spline go underground, the server-side path looks correct.

**Comment by Goatform** [comment] 2015-07-05 14:11
Weird, I can't reproduce that issue on my core.

**Comment by cemak** [comment] 2015-09-28 09:50
@Goatform  me too.

**Comment by Goatform** [comment] 2015-09-28 12:09
If I was you, I would share idea and fix.

**Comment by cemak** [comment] 2015-09-28 13:04
1. https://github.com/TrinityCore/TrinityCore/issues/15011#issuecomment-137701483 need for compare target z and last point path Z above 5 yards.
2. Compare target Z and last point path Z above caster objectScale
```javascript 
void PathGenerator::SetPositionZIfNeed(float caster_scale, float target_z)
{
    G3D::Vector3 endPos = GetActualEndPosition();
    if (target_z - endPos.z >  caster_scale)
        endPos.z = target_z;
      
   _pathPoints[_pathPoints.size()-1] = G3D::Vector3(endPos.x, endPos.y, endPos.z);
}
   
```
Add SetPositionZIfNeed  in void MotionMaster::MoveCharge(PathGenerator path, float speed, float z)  After MoveCharge(dest.x, dest.y, dest.z, speed, EVENT_CHARGE_PREPATH);
. It's  idea should work. Good luck.

**Comment by jackpoz** [comment] 2015-09-28 13:29
you can't fix an issue that you can't reproduce

**Comment by Goatform** [comment] 2015-09-28 13:36
@cemak, this function isn't same (on TC and on my core) which you gave me:

``` c++
void MotionMaster::MoveCharge(PathGenerator path, float speed, float z)
```
It looks like this:

``` c++
void MotionMaster::MoveCharge(PathGenerator const& path, float speed /*= SPEED_CHARGE*/)
```

So this won't work because "z" doesn't exist:
``` c++
path.SetPositionZIfNeed(_owner->GetObjectSize(), z);
```

**Comment by cemak** [comment] 2015-09-28 13:38
@Goatform, for me
```javascript  void MotionMaster::MoveCharge(PathGenerator path, float speed, float z) ```

**Comment by Goatform** [comment] 2015-09-28 13:42
Then, as you know, we can't test this possible fix.

**Comment by cemak** [comment] 2015-09-28 13:45
@Goatform I only suggested the idea but not the fix

**Comment by Goatform** [comment] 2015-09-28 14:11
Alright, bttw, I reproduced this issue.

- RED LINE: player & target
- GREEN LINE: empty space
- BLUE LINE: correct (retail path)
- BLACK LINE: TC path (broken path)

![ub8fvrl](https://cloud.githubusercontent.com/assets/8354705/10137343/55125b6a-65f9-11e5-87f1-76036a2404b6.png)

As you can see on the picture, currently path is marked with black line and it shouldn't work like that because player shouldn't charge through object or ground. Since objects/ground have empty space inside of model it will make you fall underground (empty space is marked with green line).

If player get into empty space and he don't fall on ground again he will fall underground.

Charge path should work in 2 ways:

1. To let you "climb" over object/ground and reach target if object/ground isn't bigger than 5 yards.

2. If object/ground is bigger than 5 yards then it will let you to generate new path to go around object/ground and to reach target.

**Comment by Runico** [comment] 2015-12-06 19:06
any progress ?

**Comment by cemak** [comment] 2015-12-13 01:22
so far not fixed ? oO

**Comment by DevRival** [comment] 2015-12-13 12:12
cemak i test you fix.
Player falls into the textures.

**Comment by cemak** [comment] 2015-12-13 23:39
@DevRival, ok.
https://github.com/TrinityCore/TrinityCore/issues/11526#issuecomment-143753562 fix ?

**Comment by cemak** [comment] 2015-12-14 00:12
http://pastebin.com/KY24SPKB This fix close issue #11526 and #15011, BUT this hack

**Comment by Re3os** [comment] 2015-12-27 06:41
@cemak it's not work,meybe update?

**Comment by Keader** [comment] 2016-02-05 14:01
Patch by @cemak  work for me

**Comment by Rushor** [comment] 2016-02-05 14:03
> http://pastebin.com/KY24SPKB This fix issue #11526 and #15011, **BUT this is hack**

we need a smarter solution :

**Comment by Keader** [comment] 2016-02-05 14:17
Improved a lot here. However depending on the position a part of the character's body is below ground. But he did not fall from the map

![wowscrnshot_020516_110347](https://cloud.githubusercontent.com/assets/7120913/12848397/6b7634ac-cbf8-11e5-80d6-9afcab42edd0.jpg)

**Comment by DevRival** [comment] 2016-02-05 14:22
I hasten to disappoint , he falls . 5 of 10 attempts , he dropped all the envy of the starting point . Try to use a spell from different angles .

**Comment by Keader** [comment] 2016-02-05 14:25
@DevRival  Mmaps is enabled?

**Comment by Goatform** [comment] 2016-02-05 14:33
Yes, that part is improved, but look at this situation here for example:

![vq035x9](https://cloud.githubusercontent.com/assets/8354705/12848978/43640e7e-cc1d-11e5-98fa-4c5cb23a0a6b.png)

RED LINE - Currently pathing
GREEN LINE - Empty space

We still need to add checks for this kind of ground. Player will get "No path" error or to generate new path if there is some availabe path near that ground/object.

**Comment by DevRival** [comment] 2016-02-05 14:34
@Keader yes of course.

**Comment by Keader** [comment] 2016-02-05 15:02
Yeah ... some angles drop in infinite yet

**Comment by jackpoz** [comment] 2016-02-05 15:17
The patch above reverts commit https://github.com/TrinityCore/TrinityCore/commit/272009ebeed80bc7749c004348fb1057761cf268 , in particular is reverts the "fixing strange behaviors when using Charge with mmaps enabled" part so. Too bad it wasn't pushed anywhere on github so it cannot be commented properly to improve it

**Comment by lineagedr** [comment] 2016-04-29 12:42
Tested with @cemak hackfix

on 
.go xyz 1453.244507 7314.201660 364.589569 530
.go xyz 1437.925903 7303.247070 372.203339 530

and still drops me under the map.

**Comment by cemak** [comment] 2016-04-29 13:44
@lineagedr, try

```
void PathGenerator::SetPositionZ(float z)
{
    float new_z = _pathPoints[_pathPoints.size()-1].z;
    if (z - new_z >= 3.f)
        new_z = z + 1.f;
    else if (z - new_z > 1.f)
        new_z = z + 0.05f;
      
   _pathPoints[_pathPoints.size()-1] = G3D::Vector3(_pathPoints[_pathPoints.size()-1].x, _pathPoints[_pathPoints.size()-1].y, new_z);
}
```

**Comment by lineagedr** [comment] 2016-04-29 16:35
@cemak Damn that fast reply, brb trying. will let you know ^^

**Comment by Aokromes** [comment] 2016-11-27 05:59
This bug is still valid after fe68b2e99851a888c5182d7bebddfea67459afd3 ?

**Comment by Keader** [comment] 2016-11-27 06:05
i think so, he dont fix anything, just reorder/cleanup/rename stuffs :)

**Comment by HelloKitty** [comment] 2016-12-10 13:41
Yea this is still an issue. If we could inspect normal vectors from the ground at the generated path points we could easily determine if a path was valid. I don't know much about TC but afaik it doesn't contain such functionality.

Or does it?

**Comment by Aokromes** [comment] 2017-11-20 18:39
Test after f8fd0b7a2c0a9acd084f011c614d529e49397479

**Comment by Re3os** [comment] 2017-11-23 17:54
@Aokromes  Still bagged https://github.com/TrinityCore/TrinityCore/commit/1c07b178a0b69c05bf3a4d4ee3aa7b2e428b7395

**Comment by Killyana** [comment] 2018-02-26 18:19
Still happen on rev. ec916db29476 with SpawnID: 12105

**Comment by WOW-Reborn** [comment] 2018-08-03 17:09
This is still an issue on 5cdb53896f89+.  It took a little while to get the bug to replicate, but it happened for me while attacking a raptor on the steep hills in the Barrens.  I charged and fell straight through the map.  I attempted to apply the previous persons "hack" but the server wouldn't compile with it anymore since it was so old.

**Comment by Killyana** [comment] 2019-12-28 23:22
Reference position:
.go xyz  1120.87451, -4967.526367, 13.4715 (player position)
target position .go xyz 1132.08007, -4984.297363, 15.9737 (.npc add temp 3100)

**Comment by jackpoz** [comment] 2019-12-30 14:59
https://github.com/TrinityCore/TrinityCore/pull/24010

**Closed by jackpoz** 2019-12-30 14:59 UTC
Labels: Comp-Core, Sub-Spells
