### ISSUE TITLE
Zone Dk Bug's

### ISSUE THREAD

**Issue by Sworken** [TrinityCore/TrinityCore#9215] opened 2013-02-14 13:18 UTC
Upon entering this area, the npc kill you launch arrows from a distance, without even time to finish the previous quest and continue the next.

www.wowhead.com/quest=12779
www.wowhead.com/npc=29102

Spells:
www.wowhead.com/spell=53348
www.wowhead.com/spell=53345

DB: TDB 3.3.5.50 + full updates - clean database 
20cd6cf

https://github.com/TrinityCore/TrinityCore/commit/203cf7cbf0d860dcc12ab625226b1c7567854356

no scripts customized
##

**Comment by Killyana** [comment] 2015-05-05 14:18
This issue still happen?

**Comment by ShinDarth** [comment] 2015-12-03 17:07
Confirmed on: https://github.com/TrinityCore/TrinityCore/commit/302623a1516e487ad64f2028aec287b99372e33a

**Comment by tkrokli** [comment] 2015-12-03 19:49
This issue has also been discussed in [**[3.3.5][DB] Wrong Hearthglen Crusader spawns in Death Knight starting zone**](15083)  #15083, not sure if that issue is a duplicate of this one or not.

Links from the OP (and a few more), to have the related info more available here on this page:

Quests:
- http://www.wowhead.com/quest=12778/the-scarlet-apocalypse
- http://www.wowhead.com/quest=12779/an-end-to-all-things

Spells:
- http://www.wowhead.com/spell=53345/arrow-assault
- http://www.wowhead.com/spell=53348/arrow-assault

NPCs:
- http://www.wowhead.com/npc=29102/hearthglen-crusader
- http://www.wowhead.com/npc=29103/tirisfal-crusader

**Comment by Rushor** [comment] 2016-02-05 08:34
https://github.com/TrinityCore/TrinityCore/issues/15083 is more about the wrong spawns

**Comment by tkrokli** [comment] 2016-02-05 13:06
Yes, I am fairly convinced that the actual reason for this issue is caused by incorrectly spawned Death Knight Champions to engage the Hearthglen Crusaders & Tirisfal Crusaders to keep the fights balanced. As it is now, the Crusaders win the fight on the ramp up from the mine and up to the FP landing spot, while the Death Knight Champions win on the far side of Death's Breach. Both sides should have balanced fights so they fight continuously and keep targeting each other, instead of targeting the player.

**Comment by Killyana** [comment] 2017-06-27 12:23
Dup #15083

**Closed by Killyana** 2017-06-27 12:23 UTC
Labels: Comp-Database, Sub-Conditions
