### ISSUE TITLE
[3.3.5a] Magic Broom mounts

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#13928] opened 2015-01-17 10:14 UTC
When you first mount "Old Magic Broom" then while on, 
you mount "Swift Flying Broom" you will look as if you are floating in air.

I am running revision [db849e7](https://github.com/TrinityCore/TrinityCore/commit/f94cfc65771f53cd2b693779ecd00705cd66593a)
##

**Comment by Rushor** [comment] 2016-02-08 10:38
http://wotlk.openwow.com/item=33183
http://wotlk.openwow.com/item=33182

**Comment by tkrokli** [comment] 2016-02-16 11:28
rev. 655fc0135fe5 2016-02-16 00:16:31 +0100 (3.3.5 branch) (Win64, Release) / TDB 335.60

Confirmed. The issue happens when changing from any of the 2 brooms to the other, just make sure you are riding at ground level on the flying broom to be able to switch from the "Swift Flying Broom" to the "Old Magic Broom". Mounting them independently without riding the other broom will not create this issue.

**Comment by Langerz82** [comment] 2018-02-06 01:28
Cannot reproduce. Old bug?

**Comment by tkrokli** [comment] 2018-02-06 08:15
TrinityCore rev. cfaa4e6caf8f 2018-02-05 21:27:13 -0200 (3.3.5 branch) (Win64, Release, Static)

I am still able to reproduce the glitch that the mount is not shown, in more than 50% of the attempts. All it takes is to create a generic character and level it to 70 (to be able to use both items) and learn the appropriate riding skills. When attempting to switch between the mounts, I often get a lot of "You are mounted" warnings, even though the items are not on cooldown and regardless of if the visual mount can be seen or not.

To me, this is only cosmetic (visual part of the spell), not sure if the issue is deeper than that.

I only tested this on a sec.level 3 account (GM off), have not tested if it is different on a sec.level 0 account.

**Comment by Keader** [comment] 2018-06-03 02:43
Work in 4fe5a167d298ad6fcb9a5f130035abcb98fa5eae
(Fixed by ariel)

**Closed by Keader** 2018-06-03 02:43 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Spells
