### ISSUE TITLE
[Core / Spell] Furious Howl does not provide proper AP increase to pet

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#9002] opened 2013-01-19 21:45 UTC
**Rev:** https://github.com/TrinityCore/TrinityCore/commit/98f502f32f092fe1bcb9e19c32c189d2ea552d19

**Bug:**

The Hunter Wolf pet spell Furious Howl does not provide the proper AP increase to the pet however it does apply properly to the owner.

> Please note: I could not find a proper link to the 3.3.5a version, wowhead and wowiki have links for 4.x and 5.x series.

**Details:**

The tooltip for rank 1 says "Increases melee and ranged AP of the hunter and pet by 43"

Here are the stats of my pet **_before_** casting FH:
- Melee Attack Power 170 (127 + 43)
- Note the 43 is in green to indicate Hunter -> pet scaling

Here are the stats of my pet **_after_** casting FH:
- Melee Attack Power **180** ( **137** + 43)
- Note the 43 is in green to indicate Hunter -> pet scaling

Notice that the bonus applied to the base AP is only **10** when the tooltip clearly states **43**.

Also, don't be confused by the "43" in green and the "43" in the FH tooltip. The "43" in green is always there no matter which pet I have because it is due to the pet scaling feature.

> **_For comparison..._**

Here are my stats **_before_** casting FH:
- Melee Attack Power 198 (137 + 61)
- Note the 61 is in green to indicate AP from items

Here are my stats **_after_** casting FH:
- Melee Attack Power **241** (137 + **104** )
- Note the 104 is in green to indicate AP from items plus FH

As you can see, FH is properly applied to the Hunter...
##

**Comment by Rothend** [comment] 2020-06-24 18:49
Cannot reproduce in 93fee78c3c6b9277d884ee710b7efc20e93452ba. Pet damage shows in white regardless of talents, then using Furious Howl it shows the proper amount of attack power added in green text. When the aura expires the green text goes away.

Maybe this was fixed in a past commit?

**Closed** 2020-06-24 19:20 UTC
Labels: Comp-Core, Sub-PetMinion, Sub-Spells
