### ISSUE TITLE
[master] Worldserver crash when talking to any class trainer inside Aldrassil

### ISSUE THREAD

**Issue by AlcDenat** [TrinityCore/TrinityCore#19229] opened 2017-03-01 12:33 UTC
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Worldserver crash

**Current behaviour:**

The worldserver.exe crashes as soon as you talk to a class trainer
-> https://gist.github.com/AlcDenat/054b87b0205e0f4b1a9d8a5f290fe3a6

**Expected behaviour:**

Gossip menu should come up without a crash

**Steps to reproduce the problem:**

1. Create any nightelf character
2. Run into Aldrassil (That big tree building)
3. Talk to any class trainer like Rhyanda or Shanda
4. Notice how the world server crashes

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 8ad043ba692a 2017-02-28 20:41:40 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  TDB_world_703.00_2016_10_17.sql + Updates

**Operating system:** Windows Server 2016 standard (with gui)

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DDuarte** [comment] 2017-03-01 12:40
Duplicate of #19218

**Closed by DDuarte** 2017-03-01 12:41 UTC
Labels: Branch-master, Comp-Core, HasBacktrace, Invalid-Duplicate
