### ISSUE TITLE
DB/Quest: Imperial Plate Leggings

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26745] opened 2021-07-24 11:51 UTC
### Description

This quest is missing text.

<details>

![image](https://user-images.githubusercontent.com/66294837/126867520-6f98e464-4f43-4a51-b9a4-ef20533b2af5.png)

</details>

### Expected behaviour

The quest text is listed correctly [here](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=7658).

**Note:** The other Imperial plate quests have text.

### Steps to reproduce the problem

1. Have 300 Blacksmithing
2. Travel to Gadgetzan
3. Speak to [Derotain Mudsipper](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=14567)
4. Choose [Imperial Plate Leggings](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=7658)
5. Quest is missing text

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 87a4bc3 2021-07-23 00:12:58 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots

**Comment by offl** [comment] 2021-07-24 11:55
Duplicate of #26052

**Closed by offl** 2021-07-24 11:55 UTC
Labels: Branch-3.3.5a
