### ISSUE TITLE
[6.x] Core/Quests showing up as not completed (Grey question mark)

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#15973] opened 2015-12-09 17:07 UTC
5bf9d2bed434

This seems like a general issue, as I've been able to reproduce it on all NPCs so far.
Easier to show it with a screenshot, than try to explain it:
![greyquestionmark](https://cloud.githubusercontent.com/assets/1616448/11692360/6c7ec980-9e9f-11e5-9340-e5cc961c1ea4.png)
Even though the quest has been completed, it is shown with a grey question mark to the left.

**Comment by tkrokli** [comment] 2015-12-09 22:14
In 3.3.5 there is a similar bug, but it is only temporary and it does not affect the quest turn-in. This only seems to happen with the low-level class trainer, I think I have seen it on other classes / races too.

TrinityCore rev. c182ea0 2015-12-09 17:12:49 +0100 (3.3.5 branch) (Win64, Release)
TDB 335.60 . updates up to and including 2015_12_09_01_world.sql

**1. Quest turn-in, not yet delivered:**

![wowscrnshot_120915_230203](https://cloud.githubusercontent.com/assets/4903600/11700344/97fb2a84-9ec9-11e5-933b-42415a731fb6.jpg)
The quest icon in the gossip is gray instead of yellow, but turning in the quest works as inteded.

**2. Quest turned in/ delivered:**

![wowscrnshot_120915_230222](https://cloud.githubusercontent.com/assets/4903600/11700389/c78c1646-9ec9-11e5-9591-9c9f29ae2368.jpg)
Quest turned in, but the NPC has still got the big yellow question mark (?) on him.

**3. After a quick walk around the outside of the building, the yellow question mark is gone:**

![wowscrnshot_120915_230456](https://cloud.githubusercontent.com/assets/4903600/11700449/369585ae-9eca-11e5-81e1-219c018d0bb4.jpg)

I know that my example is from 3.3.5, not from 6.x and may not be the same issue, but maybe it could help somehow in finding out what goes on with the quest gossip and quest giver icon status.

**Comment by Aokromes** [comment] 2016-06-15 08:32
This bug was fixed on 3.3.5a, idk if the fix was pushed also to 6.x

**Comment by tkrokli** [comment] 2016-06-16 18:00
Will test this later on 6.x as soon as I have finished compiling the latest updates to 3.3.5 (+ DB update).

**Comment by GnaXi** [comment] 2016-06-16 18:01
I can confirm that this is still a general issue on the latest rev of 6.x

**Comment by tkrokli** [comment] 2016-06-16 18:35
Thank you for responding. Please note: "latest" is very imprecise or ambiguous. Several commits are pushed each day, so it would be nice if you actually posted the TC rev. hash from your log files or consoles.

**Comment by GnaXi** [comment] 2016-06-16 18:45
Sorry about that. I'm currently on rev 5da217877be7

**Comment by tkrokli** [comment] 2016-06-16 18:54
:+1: Thank you for confirming the rev. hash. At the moment when you posted your previous comment, https://github.com/TrinityCore/TrinityCore/commit/cfc40f2 was the so-called "latest" commit (before any more commits are made to the 6.x branch). I hope you see now what I mean when I say that it is difficult to tell which revision you are on unless specified.

**Comment by tkrokli** [comment] 2016-06-16 23:36
TrinityCore rev. cfc40f2cccee 2016-06-16 17:47:10 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_06_16_00_world.sql`

OK, so I could confirm that this detail is still an issue in 6.x - the 3.3.5 solved issue was about quest giver NPCs quest complete icon (question mark "?") not going away immediately upon quest turn-in.

The easiest example in 3.3.5 I can think of, is the level 56 turn-in to the NPC "Lord Thorval" (ID 28472) and the quest "The Power Of Blood, Frost And Unholy" (quest ID 12849, turn-in only) where the gossip question mark is gray instead of yellow. Most other quests show a yellow question mark in the gossip when the quest is complete, though. I don't remember if this could be caused by some kind of quest DB flag or other value. Maybe @SnapperRy remembers something about this?

**Comment by Aokromes** [comment] 2019-08-20 08:26
check if this bug is still valid after the wave of cherry picks.

**Comment by Naddley** [comment] 2022-11-20 18:51
works rev. 85205d8ca5d4

![Screen](https://user-images.githubusercontent.com/64811442/202920288-0d4b1a17-2ddd-4553-a05a-a86a74652235.PNG)

**Closed by Naddley** 2022-11-20 18:51 UTC
Labels: Sub-Quests, Comp-Core, Branch-master
