### ISSUE TITLE
[Quest] The Tome of Valor

### ISSUE THREAD

**Issue by starrheld** [TrinityCore/TrinityCore#18762] opened 2017-01-07 19:12 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Description: Causes server to crash

Current behaviour: When you are on the quest The Tome of Valor with id (1651) in Westfall and you are on the 3rd "step" and Daphne is running back it causes the server to crash.

Expected behaviour: Not crash 

Steps to reproduce the problem:

1. Go to Westfall, get the quest The Tome of Valor - .quest add 1651
2. Start the event
3. Kill the 3 packs and wait for the server to crash

Branch(es): 3.3.5

TC rev. hash/commit: b1fa8ff028fb

TDB version: 3.3.5.62

Operating system: Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment] 2017-01-08 11:01
probably caused by https://github.com/TrinityCore/TrinityCore/issues/18401

**Comment by Staleness89** [comment] 2017-01-08 23:43
Confirmed crash. Tried testing this myself, Daphne seems to die pretty fast, amirite? Also, is the quest suppose to fail upon her death because it didn't for me.

**Comment by Aokromes** [comment] 2017-01-08 23:53
plz supply a crashlog, i am unable to crash it.

**Comment by Staleness89** [comment] 2017-01-09 01:30
tried to reproduce a couple times in debug mode, but now daphne freezes up in the middle of the event, essentially paused in the script, where she can no longer give or receive quests. happened to me after the first wave. here is a post on the Dalaran forums describing the same issue and a response from a GM.

http://www.dalaran-wow.com/forums/input-and-assistance/community-support/topic/7356/tome-of-valor-quest-is-bugged

As said in the GM post, it requires a server restart to fix.

**Comment by Rushor** [comment] 2017-01-11 10:24
fix here https://github.com/callmephil/SunWellCore/blob/2f2f8a61101ff15878b5e40473a8aae9028a4607/src/server/scripts/EasternKingdoms/zone_westfall.cpp#L61

**Comment by Staleness89** [comment] 2017-01-11 11:10
might require some DB changes? I tried it and she froze after her first text over on quest accept.

**Comment by Rushor** [comment] 2017-01-11 11:31
shure search for script_waypoint ids in the sql files there

**Comment by Staleness89** [comment] 2017-01-11 11:37
works beautifully now. i'll make the sql for the script_waypoint

**Comment by Staleness89** [comment] 2017-01-11 11:44
```SQL
DELETE FROM `script_waypoint` WHERE `entry`=6182;
INSERT INTO `script_waypoint` (`entry`, `pointid`, `location_x`, `location_y`, `location_z`, `waittime`, `point_comment`)
(6182, 0, -11480.7, 1545.09, 49.8986, 0, ''),
(6182, 1, -11466.8, 1530.15, 50.2636, 0, ''),
(6182, 2, -11465.2, 1528.34, 50.9544, 0, 'entrance hut'),
(6182, 3, -11463, 1525.24, 50.9377, 0, ''),
(6182, 4, -11461, 1526.61, 50.9377, 5000, 'pick up rifle'),
(6182, 5, -11463, 1525.24, 50.9377, 0, ''),
(6182, 6, -11465.2, 1528.34, 50.9544, 0, ''),
(6182, 7, -11468.4, 1535.08, 50.4009, 15000, 'hold, prepare for wave1'),
(6182, 8, -11468.4, 1535.08, 50.4009, 15000, 'hold, prepare for wave2'),
(6182, 9, -11468.4, 1535.08, 50.4009, 10000, 'hold, prepare for wave3'),
(6182, 10, -11467.9, 1532.46, 50.3489, 0, 'we are done'),
(6182, 11, -11466.1, 1529.86, 50.2094, 0, ''),
(6182, 12, -11463, 1525.24, 50.9377, 0, ''),
(6182, 13, -11461, 1526.61, 50.9377, 5000, 'deliver rifle'),
(6182, 14, -11463, 1525.24, 50.9377, 0, ''),
(6182, 15, -11465.2, 1528.34, 50.9544, 0, ''),
(6182, 16, -11470.3, 1537.28, 50.3785, 0, ''),
(6182, 17, -11475.6, 1548.68, 50.1844, 0, 'complete quest'),
(6182, 18, -11482.3, 1557.41, 48.6245, 0, '');
```

**Comment by Xiledria** [comment] 2017-01-11 21:09
confirmed
http://logon.deffender.eu/crash/view/4dd07f7c
http://logon.deffender.eu/crash/view/fba9feea
http://logon.deffender.eu/crash/view/e369327c

also C++ & SQL fix above also works for this issue - well, kind of, there is missing VALUES keyword and after INSERT statement and ScriptName update for creature_template.

**Comment by Rushor** [comment] 2017-01-11 21:32
nevertheless the corescript is a hack.

**Comment by Xiledria** [comment] 2017-01-11 21:49
It seems like some issue with SmartAI crashing server, there is the same problem in Dire Maul with http://www.wowhead.com/npc=14354/pusillin - if you start an event and wait a few seconds, server crashes.
Sadly, I have no debug crash log for that, only release one - http://logon.deffender.eu/crash/view/99aa798d but I would say it is pretty much the same issue

**Comment by Staleness89** [comment] 2017-01-11 23:04
@Rushor does that mean it probably won't get pushed? I'm still learning, so I'm curious what makes the script hacky? What can be done to make it better?

**Comment by tkrokli** [comment] 2017-01-12 02:11
@Staleness89 : he did not mean your SQL , he was referring to the existing script in `zone_westfall.cpp`.

**Comment by Aokromes** [comment] 2017-01-12 02:14
There is no zone_westfall.cpp on clean TC, it was converted to SAI.

**Comment by tkrokli** [comment] 2017-01-12 02:25
https://github.com/TrinityCore/TrinityCore/issues/18762#issuecomment-271832523

> fix here https://github.com/callmephil/SunWellCore/blob/2f2f8a61101ff15878b5e40473a8aae9028a4607/src/server/scripts/EasternKingdoms/zone_westfall.cpp#L61

https://github.com/TrinityCore/TrinityCore/issues/18762#issuecomment-272001414
> nevertheless the corescript is a hack.

**Comment by Staleness89** [comment] 2017-01-12 02:27
@tkrokli yes I realize. I was wondering about the C++ script.
@Aokromes right, but it causes server crashes and freezes up mid script occassionally and this fix works a lot better. Do you think I can open a PR to push it?

**Comment by tkrokli** [comment] 2017-01-12 02:35
Put fixes with SQL in issue comments. Pull Request is for C++ files & other non-SQL files.

**Comment by Aokromes** [comment] 2017-01-12 02:35
if it's a hack it never will be acepted, fix the SAI.

**Comment by Staleness89** [comment] 2017-01-12 02:47
What makes the C++ script a hack though? Why can't it be fixed and pulled instead?

**Comment by tkrokli** [comment] 2017-01-12 02:53
Well, if someone writes a non-hacky script (I leave it to real coders to explain why the Sunwell script is hacky), it could be accepted in a PR. The main point being that a suggested script needs to be approved.

**Comment by Staleness89** [comment] 2017-01-12 03:00
Sorry, just trying to get a description of why the script is hacky, and what if anything can be done to fix it.

**Comment by Aokromes** [comment] 2017-01-12 03:21
Also, we prefer SAI when it's possible.

**Comment by Staleness89** [comment] 2017-01-12 03:48
well I'll leave it alone then.. works pretty damn well though, especially compared to the current implementation

**Comment by Rushor** [comment] 2017-01-12 07:52
we need a way to fix the events and actions in SAI that are the reason for this issue :)

**Comment by Rushor** [comment] 2017-01-20 13:36
can be closed since https://github.com/TrinityCore/TrinityCore/pull/18888 was merged

**Comment by Aokromes** [comment] 2017-01-20 13:36
a3c6880

**Closed** 2017-01-20 13:36 UTC
Labels: Branch-3.3.5a, Comp-Database, Priority-High, Sub-Quests
