### ISSUE TITLE
[Mac][master] connection_patcher error

### ISSUE THREAD

**Issue by yslim** [TrinityCore/TrinityCore#19917] opened 2017-06-19 00:24 UTC
**Description:**

connection_patcher failed for Wow 7.2.5(24367) on Mac.

**Current behaviour:**

Creating patched binary...
Determined build number: 24367
Mac client...
patching Portal
Found offset 22121776
patching redirect RSA Modulus
Found offset 22099120
patching BNet certificate file location
Found offset 22711548
patching BNet certificate file to load from local path instead of CASC
EX: unable to find pattern
An error occurred. Press ENTER to continue...^C

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. cf5aa01be7ee+ 2017-06-18 22:17:48 +0200 (master branch) (MacOSX, Release, Static) (bnetserver)

**TDB version:**  TDB_720 + updates

**Operating system:** macOS Sierra 10.12.5

**Comment by Carbenium** [comment] 2017-06-19 00:25
Duplicate of #19916

**Closed by Carbenium** 2017-06-19 00:25 UTC
