### ISSUE TITLE
Quest Jaina's Autograph (558) can't complete

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17087] opened 2016-05-06 10:53 UTC
Quest Jaina's Autograph can't complete 

If you talk with Jaina and you click the Dialog nothing happens
Jaina don't gif me Jaina's Autograph

http://www.wowhead.com/quest=558/jainas-autograph
https://www.youtube.com/watch?v=zBdE8czwJMw

**Branch(es)**: 335

**TC hash/commit**:  
TC>TrinityCore rev. 8d0906552513 2016-05-06 08:17:30 +0200 (335 branch)

**TDB version**:  
335.61 + all Updates

**Operating system**:  
Win7 64Bit

**Comment by dr-j** [comment] 2016-05-06 11:50
Ye because I screwed script up when updating a previous error with her script
~~~sql
DELETE FROM `smart_scripts` WHERE `entryorguid` IN(4968) AND `source_type`=0 AND `id`=1;
UPDATE `smart_scripts` SET `link`=1 WHERE  `entryorguid`=4968 AND `source_type`=0 AND `id`=0 AND `link`=0;

INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(4968, 0, 1, 0, 61, 0, 100, 0, 0, 0, 0, 0, 11, 23122, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Lady Jaina Proudmoore - On Gossip Select - Cast Jaina''s Autograph');

**Comment by tkrokli** [comment] 2016-05-06 14:31
TrinityCore rev. 59ac77522347 2016-05-05 13:20:52 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.61 + updates up to and including `2016_05_05_01_world.sql`

Your fix works as intended, quest completes after selecting the gossip option (tested only on 1 char.).

At the same time as adding this SQL update/spell addition, would it be practical to look into the `creature_template`.`entry` 17772 Lady Jaina Proudmoore (no subname) which is still listed in the DB with `ScriptName` = `npc_jaina_proudmoore` (removed core script)? It is not possible to teleport to this NPC (`creature`.`guid` 48419) with either `.go creature 48419` (no error message) or `.go creature ID 17772` (error message: `Creature not found!`).
```sql
SELECT * FROM `creature_template` WHERE `entry` IN (4968, 17772);
```
```
 entry  difficulty_entry_1  difficulty_entry_2  difficulty_entry_3  KillCredit1  KillCredit2  modelid1  modelid2  modelid3  modelid4  name                   subname             IconName  gossip_menu_id  minlevel  maxlevel     exp  faction  npcflag  speed_walk  speed_run   scale    rank  dmgschool  BaseAttackTime  RangeAttackTime  BaseVariance  RangeVariance  unit_class  unit_flags  unit_flags2  dynamicflags  family  trainer_type  trainer_spell  trainer_class  trainer_race    type  type_flags  lootid  pickpocketloot  skinloot  resistance1  resistance2  resistance3  resistance4  resistance5  resistance6  spell1  spell2  spell3  spell4  spell5  spell6  spell7  spell8  PetSpellDataId  VehicleId  mingold  maxgold  AIName   MovementType  InhabitType  HoverHeight  HealthModifier  ManaModifier  ArmorModifier  DamageModifier  ExperienceModifier  RacialLeader  movementId  RegenHealth  mechanic_immune_mask  flags_extra  ScriptName            VerifiedBuild
------  ------------------  ------------------  ------------------  -----------  -----------  --------  --------  --------  --------  ---------------------  ------------------  --------  --------------  --------  --------  ------  -------  -------  ----------  ---------  ------  ------  ---------  --------------  ---------------  ------------  -------------  ----------  ----------  -----------  ------------  ------  ------------  -------------  -------------  ------------  ------  ----------  ------  --------------  --------  -----------  -----------  -----------  -----------  -----------  -----------  ------  ------  ------  ------  ------  ------  ------  ------  --------------  ---------  -------  -------  -------  ------------  -----------  -----------  --------------  ------------  -------------  --------------  ------------------  ------------  ----------  -----------  --------------------  -----------  --------------------  ---------------
  4968                   0                   0                   0            0            0     30863         0         0         0  Lady Jaina Proudmoore  Ruler of Theramore  (NULL)              2465        83        83       2     1096        3           1          1       1       3          0            2000             2000             1              1           8          64         2048             0       0             0              0              0             0       7          12       0               0         0            0            0            0            0            0            0   20692   20681       0       0       0       0       0       0               0          0   700000   750000  SmartAI             0            3            1         529.505            80              1              35                   1             0           0            1             619397119            2                                12340
 17772                   0                   0                   0            0            0     30864         0         0         0  Lady Jaina Proudmoore                      (NULL)              7552        73        73       1     1718        1         1.2    1.14286       1       3          0            1200             2000             1              1           2          64         2048             0       0             0              0              0             0       7          76       0               0         0            0            0            0            0            0            0       0       0       0       0       0       0       0       0               0          0        0        0                      0            3            1              75            20              1              35                   1             0         167            1             617299803            1  npc_jaina_proudmoore          12340
```

**Comment by wonder2011** [comment] 2016-05-06 15:16
Then this quest is fixed now ?

**Comment by tkrokli** [comment] 2016-05-06 15:21
If you apply **dr-j**'s fix manually, yes. Otherwise, you will have to wait until a commit is made by a TC dev.

**Comment by wonder2011** [comment] 2016-05-06 15:22
Ok thanks, i will apply this now and wait for a TC dev commit !

**Closed** 2016-05-07 10:53 UTC
