### ISSUE TITLE
DB/Quest: A Boar's Vitality (Repeat issue)

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25660] opened 2020-11-19 10:28 UTC
**Description:**

(Repeatable?) quest in Blasted Lands, A Boar's Vitality from Bloodmage Drazial, cannot be turned in (more than once?)
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=2583

<details>

![image](https://user-images.githubusercontent.com/66294837/99635909-cbf19400-2a96-11eb-94ea-b772d45a1ab3.png)

</details>

Notice the items and completion steps are met, however, the icon to say it's complete does not show and the option to turn the quest in when you click him is missing so it cannot be completed.

I am certain I already completed this one before - along with 1-2 others. So this is likely the second turn-in.

**Expected behaviour:**

Collect items and hand in quest - receive reward

Edit: Following the behaviour of the other quests given out by the 2 NPCs in this area - A Boar's Vitality is a complete once quest and once completed changes to a different name which is repeatable - Spirit of the Boar

Complete once quests and their replacements:
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=7505#starts

Spirit of the Boar (Repeatable)
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=2584

**Steps to reproduce the problem:**

1. Accept quest from Bloodmage Drazial
2. Collect the items
3. Turn in for reward
4. Retake quest
5. Collect the items
6. Cannot turn in again

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. cc8287927b9c 2020-11-18 20:09:34 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:** Windows 7 64bit

**Comment by Faq** [comment] 2020-11-19 10:37
Don't use classic links, use something like https://tcubuntu.northeurope.cloudapp.azure.com/aowow/ what is for 335

**Comment by illfated** [comment] 2020-11-19 22:44
Possibly related to issue ticket #25662 (NPC: Bloodmage Lynnore displaying incorrect quest status icon), and this could possibly have something to do with the item count, especially because some of the quest items are required items in at least 2 quests taken at the same time.

**Comment by TQPS** [comment] 2020-11-19 23:35
Of all the quests available from the 2 NPCs in this area, I have been able to complete them all and have no others outstanding - with the exception of "A Boar's Vitality".

Note I did neglect to show that the quest turn-in was not available so this is a little different to original screenshot.

<details>

![image](https://user-images.githubusercontent.com/66294837/99736200-18ca7e80-2b1a-11eb-9a23-28e6e3a2e250.png)

</details>

- Objectives are complete
- Quest details are complete (See original screenshot)
- Quest status on NPC show completed (with a golden ?)
- All items are in inventory

However,
- Quest giver does not show quest complete
- Quest cannot be handed in (greyed out)

Workaround found:
- delete the quest and retake it when you have all the items 
- quest will automatically be available for turn-in (correct symbol shows)
- "Spirit of the Boar" becomes available

<details>

![image](https://user-images.githubusercontent.com/66294837/99737174-dace5a00-2b1b-11eb-8db6-d85341b049d3.png)

</details>

Perhaps something odd with the order of completing them messed with something?

**Comment by illfated** [comment] 2020-11-20 00:19
I have noticed a few times that the quest item issue can occur in different scenarios, especially with some of the profession quests to deliver a certain amount of more than one kind of quest item. One theory is that this can occur if the quest items get moved around after starting to accumulate them in the inventory bags, as well as moving them between inventory and bank bags. It is as if the quest item count becomes disturbed by item movement, although I have not tested this theory in detail yet. It just seems to occur more often when the quest items don't stay in the same slot all the time between starting the quest and completing it. I have got a "slightly bad" habit of sorting my bags as often as possible, not thinking about if it will upset the quest completion.

**Comment by TQPS** [comment] 2020-11-20 01:18
I'm with you on the bag sorting - especially with these items because they aren't a strict requirement per se for a quest - you just accumulate them as you go and turn in when you meet the requirement. 

There are no item/quest counts and creatures do not indicate they possibly contain a quest item - and this is correct behaviour.

I did notice that the requirement numbers did fluctuate correctly when you turn in one quest which reduces the numbers - the game did a good job at adjusting the other quest counts - and this happened a few times.

So these items don't get mixed up with cooking items or other non-junk (they don't display item values until you're at a vendor), I also moved them to a quest item location in my bags. Some of those quests did take some time to complete ("A Boar's Vitality" for example) due to a variation in drops so I probably did these quests over a couple of days, and several vendor trips. A lot of bag swapping involved is my point.

Repeated some as I noticed the names changed - I did not realize at the time that they were just a repeat or their originals with different names. I know that now.

**Comment by illfated** [comment] 2020-11-20 01:44
> I'm with you on the bag sorting - especially with these items because they aren't a strict requirement per se for a quest - you just accumulate them as you go and turn in when you meet the requirement.
>
Fair enough. I am with you so far.

> There are no item/quest counts and creatures do not indicate they possibly contain a quest item - and this is correct behaviour.
>
Yes, I noticed that pointing at some creatures did not produce a quest indication in the creature description, but the quest name "Vulture's Vigor" showed up as part of the flavor text -- not sure what is unique about that quest compared to the related ones. I am using the addon "Carbonite" which could possibly affect the quest flavor text. My own issue is that the minimap area coloring is sometimes slightly shifted (or not covering the correct area) from the location of some quest creatures or objects.

> I did notice that the requirement numbers did fluctuate correctly when you turn in one quest which reduces the numbers - the game did a good job at adjusting the other quest counts - and this happened a few times.
> 
Well, thank you for noticing that bit. I did not check, mostly because I did not complete the last 2 quests outlined in ticket #25662 .

> So these items don't get mixed up with cooking items or other non-junk (they don't display item values until you're at a vendor), I also moved them to a quest item location in my bags. Some of those quests did take some time to complete ("A Boar's Vitality" for example) due to a variation in drops so I probably did these quests over a couple of days, and several vendor trips. A lot of bag swapping involved is my point.
> 
The quest items are (as far as I can tell) clearly marked as quest items without a selling price. No confusion there, from what I can see. And yes, it sure did take time to collect some items, because the drop rate is pretty low for some of the quest items. Note: I did not visit any vendor during my testing for ticket #25662 .

My own concern is my use of the following:
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=23162/forors-crate-of-endless-resist-gear-storage
- the addon "BagSorter" (XML + Lua files) and me frequently using the slash command `/bs` to sort bag contents

> Repeated some as I noticed the names changed - I did not realize at the time that they were just a repeat or their originals with different names. I know that now.

I haven't gone this far yet. I might test the issue in this ticket later, unless it gets resolved sooner than expected. These repeat quests are not something I have spent much time checking earlier either. Good to know that there may be quest item counting issues in those quests too.

**Comment by offl** [comment] 2020-11-23 16:25
Duplicate of #25603

**Closed by offl** 2020-11-23 16:25 UTC
Labels: Branch-3.3.5a
