### ISSUE TITLE
class_unit Legion

### ISSUE THREAD

**Issue by vato312199** [TrinityCore/TrinityCore#18000] opened 2016-09-25 13:06 UTC
**Description:**

Hello, help me.. How to make an NPC appeared resource such as energy or rage? I have instead is a general in the NPC no resource except for mana. I 7.0.3.22624 build. Build me officially to the Trinity. Help!!

**Steps to reproduce the problem:** no resource from NPC. There is no life in NPCs, those who should be the rage, or energy.

**TC hash/commit:**
TC>TrinityCore rev. unknown 1970-00-00 00:00:000 (604 branch)(Win64, Release, Static)

**Current behaviour**: not work

**Expected behaviour**: Will see resource from a NPC

**Branch(es)**: 6.x 

**Tags 7.0.3/22624**

**TDB version:** TDB 6.04

**Operating system:** Win x64

**Comment by tkrokli** [comment] 2016-09-25 13:24
If you want to help TC improving the code, please follow [the TC installation guide](https://trinitycore.atlassian.net/wiki/display/tc/Installation+Guide) on how to clone the source properly before compiling it. TC rev. hash is still missing, given by you as "unknown".
(how did you do that and still get date/time info instead of 000-00-00 00:00:00 ? )

BTW, I closing your issue #17998 - it is less useful than this one (although improvement is possible).

**Comment by DDuarte** [comment] 2016-09-25 15:16
Change class in creature_template table.

This is not a bug report.

**Closed by DDuarte** 2016-09-25 15:16 UTC
