### ISSUE TITLE
Core/Scripts: Aspect of the Cheetah is missing Effect 2

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19611] opened 2017-05-08 21:18 UTC
**Description:**

The spell ''Aspect of the Cheetah'' [Spell ID: 186257] of the Hunter class, has an issue.

**Current behaviour:**

The spell ''Aspect of the Cheetah'' [Spell ID: 186257] increases the movement speed by 90% for 3 sec, but then it does not increase the character's movement speed by 30% for 9 sec.

**Expected behaviour:**

The spell ''Aspect of the Cheetah'' [Spell ID: 186257] should increase the movement speed by 90% for 3 sec and then by 30% for another 9 sec.

**Steps to reproduce the problem:**

1. Create a Hunter character.
2. Reach level 22 in order to learn the spell ''Aspect of the Cheetah'' [Spell ID: 186257].
3. Then use the spell ''Aspect of the Cheetah'' [Spell ID: 186257].

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=186257/aspect-of-the-cheetah

**Comment by MartGon** [comment] 2017-05-11 21:13
Should be fixed by this
https://github.com/MartGon/TrinityCore/commit/41ac0e7202f162596909399aab656e1fa5635fe6
Tested in-game, and it's working as intended.

**Comment by HannibalRoG** [comment] 2017-05-11 21:24
I will tested today, thanks.

**Comment by HannibalRoG** [comment] 2017-05-11 23:00
Yes, that solved the problem.

**Comment by HannibalRoG** [comment] 2017-05-12 01:33
Somebody labeled this with Feedback-PatchFix, please.

**Comment by Aokromes** [comment] 2017-05-12 02:02
It's hack.

**Comment by HannibalRoG** [comment] 2017-05-12 03:35
@Aokromes Can you explain me what its a hack?

**Comment by MartGon** [comment] 2017-05-12 08:16
It's considered hack because it's fixed by using the _spell_linked_spell_ table.@Aokromes Should it be fixed by using a script?

**Comment by tkrokli** [comment] 2017-05-12 09:38
Yes, that is true. Using the table `spell_linked_spell` is a hack more than 90% of the time.
Creating a proper spell script is a lot better for spells not working directly from dbc/DB2.

**Comment by Keader** [comment] 2017-05-12 12:01
Yes @MartGon. Use OnEffectHitTarget hook
Has some exemples in boss scripts, like : https://github.com/Keader/TrinityCore/blob/4d3e4fde14289a446e112ebe24c21c26ebf10b11/src/server/scripts/Outland/BlackTemple/boss_illidan.cpp#L2237-L2268

**Closed** 2017-05-14 09:05 UTC
Labels: Branch-master, Comp-C++Script, Sub-Spells
