### ISSUE TITLE
No locales detected

### ISSUE THREAD

**Issue by Xunil1337** [TrinityCore/TrinityCore#13965] opened 2015-01-27 19:19 UTC
https://github.com/TrinityCore/TrinityCore/commit/34bbf031c04916b104432dc6e5d12b5ab05c4833

```
Map & DBC Extractor tools
===================
opened casc storage 'F:/Program Files (x86)\World of Warcraft\Data'
Locale none not installed.
Locale enUS not installed.
Locale koKR not installed.
Locale unknown not installed.
Locale frFR not installed.
Locale deDE not installed.
Locale zhCN not installed.
Locale esES not installed.
Locale zhTW not installed.
Locale enGB not installed.
Locale enCN not installed.
Locale enTW not installed.
Locale esMX not installed.
Locale ruRU not installed.
Locale ptBR not installed.
Locale itIT not installed.
Locale ptPT not installed.
No locales detected
                                "File(s) Created"
                     Press any key to go back to the main menu.

Is that my fail ?
```

**Comment by scorched-wow** [comment] 2015-01-28 00:11
Have you installed WoW Client? Best use change language to US or GB so you can extractor after you installed patch.

**Comment by et65** [comment] 2015-01-28 12:37
Confirm, occurs since last CascLib update (https://github.com/TrinityCore/TrinityCore/commit/31e3dc2e75459f681480ae09641f1087096dfd69).

**Comment by DDuarte** [comment] 2015-01-28 13:48
@et65, can you make sure that the commit you linked is the culprit and not https://github.com/TrinityCore/TrinityCore/commit/1406536a2c12159424dee0df6486276a28f0d34c ?

**Comment by Shauren** [comment] 2015-01-28 13:51
https://github.com/ladislav-zezula/CascLib/commit/68596ff5b4a8ac3174701f8daf489edb7e6ec168
This looks promising (newer than our)

**Comment by et65** [comment] 2015-01-28 16:32
@DDuarte: I'm sure, i've tested to revert the CascLib update commit and all work fine.

**Comment by DDuarte** [comment] 2015-01-28 17:12
Could you test the commit Shauren linked?

**Comment by Xunil1337** [comment] 2015-01-28 19:09
I compile it and give feedback later... i have update it and let me test it !

**Comment by Aokromes** [comment] 2015-02-15 18:35
@Xunil1337 you tested that?

**Comment by zwj-2014** [comment] 2015-02-16 14:44
use https://github.com/ladislav-zezula/CascLib/commit/4235e5f2033e2de709c83034503d49e532d03630 work good for dbc, test with zhCN client 6.0.3.

**Comment by et65** [comment] 2015-02-16 18:01
work good with frFR on rev https://github.com/TrinityCore/TrinityCore/commit/17361275c520a94db9168e486a47cf368147dd58 :)

**Comment by Xunil1337** [comment] 2015-02-16 23:33
No, atm i have real live stress..

**Comment by iceyman** [comment] 2015-02-22 08:19
map extractor ----> http://pastebin.com/JuLi1r9q and there are a few double ups in the pastbin Vmap ---> http://pastebin.com/jgzNSUfS

**Comment by Aokromes** [comment] 2015-02-22 11:45
Try after 4235e5f2033e2de709c83034503d49e532d03630

**Comment by Aokromes** [comment] 2015-03-09 18:35
No word after 15d, closing, if this bug is still valid open a new ticket.

**Closed by Aokromes** 2015-03-09 18:35 UTC
Labels: Branch-6.x, Comp-Tools

**Comment by n4ndo** [comment] 2015-03-27 07:14
@Aokromes Try today with latest TC, latest version of WoW, and say "No locales detected"

**Comment by hackersrage** [comment] 2015-11-06 11:50
Still failing with current build for 6.x .

Map & DBC Extractor
===================
error opening casc storage '/root/wow/Data' locale enUS: FILE_NOT_FOUND
error opening casc storage '/root/wow/Data' locale koKR: FILE_NOT_FOUND
error opening casc storage '/root/wow/Data' locale frFR: FILE_NOT_FOUND
error opening casc storage '/root/wow/Data' locale deDE: FILE_NOT_FOUND
error opening casc storage '/root/wow/Data' locale zhCN: FILE_NOT_FOUND
error opening casc storage '/root/wow/Data' locale zhTW: FILE_NOT_FOUND
error opening casc storage '/root/wow/Data' locale esES: FILE_NOT_FOUND
error opening casc storage '/root/wow/Data' locale esMX: FILE_NOT_FOUND
error opening casc storage '/root/wow/Data' locale ruRU: FILE_NOT_FOUND
error opening casc storage '/root/wow/Data' locale ptBR: FILE_NOT_FOUND
error opening casc storage '/root/wow/Data' locale itIT: FILE_NOT_FOUND
No locales detected

**Comment by Smokexyz** [comment] 2015-11-21 14:28
Still valid 
$ ./mapextractor 
Map & DBC Extractor
===================
error opening casc storage '/Applications/WoW/Data' locale enUS: FILE_NOT_FOUND
error opening casc storage '/Applications/WoW/Data' locale koKR: FILE_NOT_FOUND
error opening casc storage '/Applications/WoW/Data' locale frFR: FILE_NOT_FOUND
error opening casc storage '/Applications/WoW/Data' locale deDE: FILE_NOT_FOUND
error opening casc storage '/Applications/WoW/Data' locale zhCN: FILE_NOT_FOUND
error opening casc storage '/Applications/WoW/Data' locale zhTW: FILE_NOT_FOUND
error opening casc storage '/Applications/WoW/Data' locale esES: FILE_NOT_FOUND
error opening casc storage '/Applications/WoW/Data' locale esMX: FILE_NOT_FOUND
error opening casc storage '/Applications/WoW/Data' locale ruRU: FILE_NOT_FOUND
error opening casc storage '/Applications/WoW/Data' locale ptBR: FILE_NOT_FOUND
error opening casc storage '/Applications/WoW/Data' locale itIT: FILE_NOT_FOUND
No locales detected

on OSX 10.11.1

**Comment by Maibenrai** [comment] 2015-11-21 15:01
Build 7f075ae746a2d6d3750db608f6d7a7cff6dfd761

Extracts maps even client is 6.2.3.

```

Map & DBC Extractor
===================
opened casc storage 'E:/Games\World of Warcraft\Data' locale enUS
Detected client build 20726 for locale enUS

Extracting dbc/db2 files...
locale enUS output path E:\Games\World of Warcraft/dbc/enUS/
Unable to open file DBFilesClient\DeclinedWord in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\DeclinedWordCases in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\MovieOverlays in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\QuestObjectiveCliTask in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAttackPower in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAttackPowerRanged in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAvoidanceDim in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtChanceToDodgeBase in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtChanceToParryBase in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtItemLevelByLevel in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp1 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp3 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp4 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp5 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClass in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp1 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp3 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp4 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp5 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcGuildExperience in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcTotalMp in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTChanceToDodge in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTChanceToParry in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassCombatRatingScalar in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassStats in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTHPFromItems in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPFromItems in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPPerIntellect in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCDpsScaler in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedAgility in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedIntellect in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedResistPhysical in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedSpirit in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStamina in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStrength in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCHPScaler in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTRaceStats in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseAgility in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseIntellect in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseSpirit in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStamina in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStrength in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedAgility in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedIntellect in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedSpirit in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStamina in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStrength in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPVPRanks in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtRageGenScaler in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFire in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFrost in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateHoly in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateNature in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateShadow in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtShieldBlockRegular in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtXPGroupBonus in the archive for locale enUS: FILE_NOT_FOUND
Extracted 0 files

opened casc storage 'E:/Games\World of Warcraft\Data' locale koKR
Locale koKR not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale frFR
Locale frFR not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale deDE
Locale deDE not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale zhCN
Locale zhCN not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale zhTW
Locale zhTW not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale esES
Locale esES not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale esMX
Locale esMX not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale ruRU
Locale ruRU not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale ptBR
Locale ptBR not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale itIT
Locale itIT not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale enUS
Extracting maps...
Read Map.dbc file... Done! (548 maps loaded)
Read AreaTable.dbc file...Done! (4687 areas loaded)
Read LiquidType.dbc file...Done! (83 LiqTypes loaded)
Convert map files
Extract Azeroth (1/548)

```
etc...

**Comment by Aokromes** [comment] 2015-11-21 15:52
We don't support 6.2.3 yet.

**Comment by Gacko** [comment] 2015-11-21 17:27
... you can not extract data for a localization you do not have installed. So...
```
opened casc storage 'E:/Games\World of Warcraft\Data' locale koKR
Locale koKR not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale frFR
Locale frFR not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale deDE
Locale deDE not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale zhCN
Locale zhCN not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale zhTW
Locale zhTW not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale esES
Locale esES not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale esMX
Locale esMX not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale ruRU
Locale ruRU not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale ptBR
Locale ptBR not installed.
opened casc storage 'E:/Games\World of Warcraft\Data' locale itIT
Locale itIT not installed.
```
is not a bug.

```
Unable to open file DBFilesClient\DeclinedWord in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\DeclinedWordCases in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\MovieOverlays in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\QuestObjectiveCliTask in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAttackPower in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAttackPowerRanged in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAvoidanceDim in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtChanceToDodgeBase in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtChanceToParryBase in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtItemLevelByLevel in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp1 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp3 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp4 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp5 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClass in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp1 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp3 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp4 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp5 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcGuildExperience in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcTotalMp in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTChanceToDodge in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTChanceToParry in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassCombatRatingScalar in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassStats in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTHPFromItems in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPFromItems in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPPerIntellect in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCDpsScaler in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedAgility in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedIntellect in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedResistPhysical in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedSpirit in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStamina in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStrength in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCHPScaler in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTRaceStats in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseAgility in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseIntellect in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseSpirit in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStamina in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStrength in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedAgility in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedIntellect in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedSpirit in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStamina in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStrength in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPVPRanks in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtRageGenScaler in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFire in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFrost in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateHoly in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateNature in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateShadow in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtShieldBlockRegular in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtXPGroupBonus in the archive for locale enUS: FILE_NOT_FOUND
```
Some of those are listed but not included in the client.

**Comment by dschallert** [comment] 2016-01-23 23:11
same here on osx with latest 6.2.3 client:

	root@macbook:/Applications/World of Warcraft$ ls
	Buildings/                      Launcher.db*                    WoW.mfil*
	Cache/                          Logs/                           World of Warcraft Launcher.app/
	Errors/                         Movies/                         World of Warcraft.app/
	Interface/                      WTF/                            data/
	
	root@macbook:/Applications/World of Warcraft$ /Users/schallert/Desktop/Trinity/bin/mapextractor
	Map & DBC Extractor
	===================
	error opening casc storage '/Applications/World of Warcraft/Data' locale enUS: FILE_NOT_FOUND
	error opening casc storage '/Applications/World of Warcraft/Data' locale koKR: FILE_NOT_FOUND
	error opening casc storage '/Applications/World of Warcraft/Data' locale frFR: FILE_NOT_FOUND
	error opening casc storage '/Applications/World of Warcraft/Data' locale deDE: FILE_NOT_FOUND
	error opening casc storage '/Applications/World of Warcraft/Data' locale zhCN: FILE_NOT_FOUND
	error opening casc storage '/Applications/World of Warcraft/Data' locale zhTW: FILE_NOT_FOUND
	error opening casc storage '/Applications/World of Warcraft/Data' locale esES: FILE_NOT_FOUND
	error opening casc storage '/Applications/World of Warcraft/Data' locale esMX: FILE_NOT_FOUND
	error opening casc storage '/Applications/World of Warcraft/Data' locale ruRU: FILE_NOT_FOUND
	error opening casc storage '/Applications/World of Warcraft/Data' locale ptBR: FILE_NOT_FOUND
	error opening casc storage '/Applications/World of Warcraft/Data' locale itIT: FILE_NOT_FOUND
	No locales detected

**Comment by Aokromes** [comment] 2016-01-23 23:55
Change locales to other language then return to english.

**Comment by Gacko** [comment] 2016-02-21 19:46
Please do a ls -la. It has to look like this. The .build.info is important!
```
total 16
drwxr-xr-x   6 gacko  admin   204 18 Feb 20:51 .
drwxrwxr-x+ 42 root   admin  1428 16 Feb 18:03 ..
-rw-r--r--   1 gacko  admin   508  5 Feb 22:13 .build.info
drwxr-xr-x   6 gacko  admin   204  6 Feb 10:01 Data
drwxr-xr-x   3 gacko  admin   102  5 Feb 22:11 World of Warcraft.app
```

**Comment by bluflippy** [comment] 2017-02-07 19:01
I'm having the same problem, but it's only occurring on my ext4 drive. When my wow client is on an NTFS drive I don't get the error. I'm expecting it has something to do with filename cases.

**Comment by Gacko** [comment] 2017-02-11 13:02
Did you check the file permissions for ext4? I guess you're trying to access NTFS from a Linux system which does not regard Windows permissions.
