### ISSUE TITLE
[3.3.5] DB/Quest: Escape from Skettis (Daily)

### ISSUE THREAD

**Issue by Kodekc** [TrinityCore/TrinityCore#16953] opened 2016-04-12 17:57 UTC
http://www.wowhead.com/quest=11085/escape-from-skettis
http://www.wowhead.com/npc=23383/skyguard-prisoner
http://wotlk.openwow.com/object=185952

.go creature id 23383
Accept quest
- Quest-escort is not working
- Missing NPC Skyguard Prisoner (There are three points of location, but there is only one)

Branch: 3.3.5
TC hash/commit: d59e1b2
TDB version: 335.61

**Comment by offl** [comment] 2020-06-23 11:17
Duplicate of #24878

**Comment by Rothend** [comment] 2020-06-23 11:26
Didn't notice this issue, thanks :P

The multiple spawns are still missing, currently there's only one spawned. Only one of them is active at any given time so they're hard to sniff.

**Comment by offl** [comment] 2020-06-23 11:31
> Missing NPC Skyguard Prisoner (There are three points of location, but there is only one)

Didn't noticed this part

Let's leave it open then with https://github.com/TrinityCore/TrinityCore/issues/24878#issuecomment-648084637 as note?

**Comment by Rothend** [comment] 2020-06-23 11:34
The NPC is more complex than I thought, I'll work on it some more :)

**Comment by offl** [comment] 2020-06-23 23:54
Duplicate of #24878
(attempt №2)

**Closed** 2020-07-03 22:20 UTC
Labels: Comp-Database
