### ISSUE TITLE
DB/trainers: Tailoring trainers offer high level profession skills to low level players

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#18755] opened 2017-01-07 05:17 UTC
Description:
When learn the profession "Tailoring" appear high level items.

Current behaviour:
In Stormwind City, the NPC [Georgio Bolero](http://www.wowhead.com/npc=1346/georgio-bolero) (DB GUID: 313886 Entry 1346) teaches the Tailoring profession in the mage quarter (Area 5154). When you have learnt it, high level items appear.

[**Silkwave Shade**](http://www.wowhead.com/item=127031/silkweave-shade) / [pattern ID 137984](http://www.wowhead.com/item=137984/pattern-silkweave-shade) / http://www.wowhead.com/spell=186091/silkweave-shade
[**Silkwave Flourish**](http://www.wowhead.com/item=127032/silkweave-flourish) / [pattern ID 137987](http://www.wowhead.com/item=137987/pattern-silkweave-flourish) / http://www.wowhead.com/spell=186094/silkweave-flourish
[**Silkwave Cover**](http://www.wowhead.com/item=127016/silkweave-cover) / [pattern ID 137990](http://www.wowhead.com/item=137990/pattern-silkweave-cover) / http://www.wowhead.com/spell=186097/silkweave-cover
[**Silkwave Drape**](http://www.wowhead.com/item=127017/silkweave-drape) / [pattern ID 137993](http://www.wowhead.com/item=137993/pattern-silkweave-drape) / http://www.wowhead.com/spell=186100/silkweave-drape

Expected behaviour:
Learn from the NPC [Georgio Bolero](http://www.wowhead.com/npc=1346/georgio-bolero) in the mage quarter in Stormwind city, the profession "tailoring". And should only appear to learn the design "White Linen Shirt"

Steps to reproduce the problem:

1. Create a Human player/Priest (or any class to use for tailoring)
2. Reach level 5
3. Go to the mage quarter in Stormwind city
4. Search for the NPC [Georgio Bolero](http://www.wowhead.com/npc=1346/georgio-bolero) and learn the profession "Tailoring"

Branch(es): master

TC rev. hash/commit: 176efd27

TDB version: 703.00 + updates

Operating system: Window 10

**Comment by tkrokli** [comment] 2017-01-07 18:42
TrinityCore rev. a82488a0c1fe 2017-01-07 03:34:54 +0100 (master branch) (Win64, Release, Static) / TDB 703.00

![image](https://cloud.githubusercontent.com/assets/4903600/21744170/05f0f540-d511-11e6-97eb-a6bfd73a3d1b.png)

Looks normal to me. I did learn First Aid before Tailoring, although they should not affect each other.

**Comment by BahDumbBugs** [comment] 2017-01-09 08:17
Commit c23dd79 confirms issue.
http://i.imgur.com/ErJ1FSO.jpg

I will update my commit tomorrow and re-test with new character.

**Comment by tkrokli** [comment] 2017-01-10 08:52
Looks like I totally misunderstood the issue here. Then again, the issue post lacks precise description.

**Comment by Edreisantafe** [comment] 2017-01-11 06:18
@tkrokli Do not have the precise description and @BahDumbBugs could get to reproduce the problem?

**Comment by BahDumbBugs** [comment] 2017-02-03 08:08
@Edreisantafe - Followed directions somewhat as original poster stated. 

1) Create new alliance player
2) Run or tele to Stormwind
3) Locate Tailoring trainer Georgio Bolero
4) Don't purchase anything he offers to train you..... rather *look* at what he offers. The high level training skills stuff should not be visible to beginners or low level tailors.

**Comment by tkrokli** [comment] 2017-02-03 19:10
@BahDumbBugs : You are correct, I misunderstood what to look for. I did not understand that the issue is that the trainer offers too high level crafting skills in the trainer UI list, I thought it was about the player profession (Tailoring) UI list. I will see if it works to do a simple 1-10 leveling online (trial account) and see how it compares to what is in current TDB 703.00 + updates.

**Comment by tkrokli** [comment] 2017-02-03 22:10
OK, I see what went wrong in the SQL @clintskie provided for Tailoring in https://github.com/TrinityCore/TrinityCore/issues/14682#issuecomment-264131643 :
```sql
INSERT INTO `npc_trainer` (`ID`,`SpellID`,`MoneyCost`,`ReqSkillLine`,`ReqSkillRank`,`ReqLevel`) VALUES
-- [skip trainer list]
-- Tailoring spells
-- [skip down to Zen Master]
(201039, 110427,  600000, 197, 500, 85), -- Zen Master Tailor
(201039, 125551,   24000, 197, 500,  0), -- Bolt of Windwool Cloth
(201039, 134585,  180000, 197, 515,  0), -- Bipsi's Gloves
(201039, 125528,   24000, 197, 525,  0), -- Windwool Bracers
(201039, 125552,   24000, 197, 530,  0), -- Pearlescent Spellthread
(201039, 125524,   24000, 197, 535,  0), -- Windwool Shoulders
(201039, 125526,   24000, 197, 535,  0), -- Windwool Gloves
(201039, 125530,   24000, 197, 535,  0), -- Windwool Belt
(201039, 125529,   24000, 197, 545,  0), -- Windwool Boots
(201039, 125527,   24000, 197, 545,  0), -- Windwool Pants
(201039, 125553,   24000, 197, 550,  0), -- Cerulean Spellthread
(201039, 125557,  240000, 197, 550,  0), -- Imperial Silk
(201039, 125523,   24000, 197, 555,  0), -- Windwool Hood
(201039, 125525,   24000, 197, 555,  0), -- Windwool Tunic
(201039, 130325,  240000, 197, 560,  0), -- Song of Harmony
(201039, 186091, 2000000, 197,   1,  0), -- Silkweave Shade
(201039, 186094, 2000000, 197,   1,  0), -- Silkweave Flourish
(201039, 186097, 2000000, 197,   1,  0), -- Silkweave Cover   
(201039, 186100, 2000000, 197,   1,  0); -- Silkweave Drape
```
Column 5 `ReqSkillRank` = 1 for the last 4 spells, it is what the wowhead page shows as starting Difficulty.
I am thinking that the ReqSkillRank should be above 500 for those 4 spells, but could it be as high as 700? (the next Difficulty number in the info box on wowhead - check the pages below to see for yourself) :

- Silkwave Shade http://www.wowhead.com/spell=186091/silkweave-shade
- Silkwave Flourish http://www.wowhead.com/spell=186094/silkweave-flourish
- Silkwave Cover http://www.wowhead.com/spell=186097/silkweave-cover
- Silkwave Drape http://www.wowhead.com/spell=186100/silkweave-drape

Could someone confirm the correct skill level when these 4 spells should become available to players?

BTW, here is an interesting way of sorting the current TDB 703.00 content for the tailoring profession:
```sql
SELECT * FROM `npc_trainer` WHERE `ID`= 201039 OR `SpellID`= -201039 ORDER BY `ReqSkillRank`,`ID`,`SpellID`;
```

**Comment by Killyana** [comment] 2018-04-17 14:43
Fixed By funjoker.

**Closed by Killyana** 2018-04-17 14:43 UTC
Labels: Branch-master, Comp-Database, Sub-Conditions, Sub-Gossips/Texts, Sub-Spells
