### ISSUE TITLE
Inn rested state fades too early

### ISSUE THREAD

**Issue by Trisjdc** [TrinityCore/TrinityCore#15325] opened 2015-08-21 09:31 UTC
Inn rested state is fading as soon as the player is out of range of the areatrigger. Especially noticeable in major cities, where the areatrigger is located at the entrance and not at the inn, and the player can't keep rested state on the inn (in Ironforge for example)
Issue caused by https://github.com/TrinityCore/TrinityCore/commit/12931f4762d2592e4b28c6e6bf137b3348230c45

On https://www.youtube.com/watch?v=m29ZM6ZiALg, it can be seen you only lose the rested state when you leave the Ironforge area. It's possible that the rested state should only fade if you leave the area in which the areatrigger is.

Core revision: https://github.com/TrinityCore/TrinityCore/commit/e287d243a3e4b58b597e284f32f6c59b6417c7e2
TDB 335.59_2015_07_14

**Comment by Rochet2** [comment] 2015-08-21 10:26
> and the player can't keep rested state on the inn (in Ironforge for example)

Did you mean the actual inn with this or just the issue with leaving ironforge?

**Comment by Trisjdc** [comment] 2015-08-21 10:35
>Did you mean the actual inn with this or just the issue with leaving ironforge?
The first. You can't keep the state in the actual inn, only in the open area close to the bank.

**Comment by Rochet2** [comment] 2015-08-21 10:36
Any spot to test that at? I cant seem to be able to lose the resting status.

**Comment by Trisjdc** [comment] 2015-08-21 11:56
I've setup a clean TC just to be sure the problem isn't on my side. Looks like it is. I'll diff to see where things went wrong, but it's clearly not a TC issue.
Will reopen if I find another problem.

**Comment by Trisjdc** [comment] 2015-08-21 12:46
It's a real issue, I just couldn't replicate because of a small DB change.
Run
```DELETE FROM areatrigger_scripts WHERE entry=4769;```

The tavern areatrigger in Ironforge just happens to have SAI for an unrelated Brewfest event. The SAI blocks the tavern behavior (another bug?).
Without the SAI, the player gains REST_TYPE_IN_TAVERN, and loses reststate when out of the reach of the areatrigger, even though in the case of Orgrimmar the player is still in a city area.

**Comment by Rochet2** [comment] 2015-08-21 14:55
It seems having a smart script returns true for the hook handler and true means that the default action is skipped. Areatrigger scripts in general should probably mostly return false in any situation to allow normal trigger behavior.

**Comment by Killyana** [comment] 2015-08-21 15:16
@Rochet2 it's the same issue as: https://github.com/TrinityCore/TrinityCore/issues/13572#issuecomment-88520961 ?

**Comment by Trisjdc** [comment] 2015-08-21 15:42
>it's the same issue as: #13572 (comment) ?

No, different issue.

**Comment by MrSmite** [comment] 2015-08-22 04:40
This doesn't seem to be a problem with free-standing inns. You can obtain rested state in Goldshire just by standing in the flowers outside the back of the Inn.

**Comment by StormBytePP** [comment] 2015-08-23 16:00
I've tried everything mentioned here, and still can not lose resting status. Even performed the delete sentence, and walking through all ironforge (inn included) without losing resting status. Any specific steps to reproduce this issue?

**Comment by Rochet2** [comment] 2015-08-23 17:45
> Any specific steps to reproduce this issue?

Running the SQL `DELETE FROM areatrigger_scripts WHERE entry=4769;` and walking to ironforge should have the resting status. But when you walk to the bank and from there to auction house and then to the inn, you will lose the rest status since apparently there is an areatrigger there of entry 4769 which applies the areatrigger rest status on you, but when you get out of it's reach the rest status of areatrigger is removed and it removes any other resting status as well.

I could easily reproduce it by doing that.

**Comment by StormBytePP** [comment] 2015-08-23 18:23
Confirmed, thanks @Rochet2

**Comment by StormBytePP** [comment] 2015-08-23 18:35
Fixed by 603f49a55134de21b6c02b3cfcd9cb32b44c5f7b

**Closed by StormBytePP** 2015-08-23 18:35 UTC
Labels: Branch-3.3.5a, Comp-Core
