### ISSUE TITLE
[CRASH] Duplicate threat list entry being inserted - memory leak

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#21187] opened 2018-01-05 22:22 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
Trinity::Assert (file=file@entry=0x23e1240 "/Sources/src/server/game/Combat/ThreatManager.cpp", line=line@entry=687, function=function@entry=0x23e15f0 <ThreatManager::PutThreatListRef(ObjectGuid const&, ThreatReference*)::__FUNCTION__> "PutThreatListRef", message=message@entry=0x23e1288 "!inMap && \"Duplicate threat list entry being inserted - memory leak!\"")

**Current behaviour**: 
Believe related to threat system rewrite

(Right now crashing like hell)
- https://pastebin.com/X4H3PYwN
- https://pastebin.com/ga1NzjL4

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
Dont know

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
e0b609a178528995959e5ea54255a3f856e62913

**TDB version**:  
335.63

**Operating system**:  
Linux x64, Static

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment] 2018-01-05 22:34
@Treeston

**Comment by Treeston** [comment] 2018-01-05 23:22
Any idea what's happening just prior to the crash? Seems like UB somewhere, that assertion should be impossible to trigger.

**Comment by Shauren** [comment] 2018-01-05 23:41
This assertion message is completely useless. You should change it to include some more info - don't forget that ASSERT accepts format arguments `ASSERT(condition, format, args)`

**Comment by Treeston** [comment] 2018-01-05 23:52
Good point. @n4ndo, would you mind going to 5a9fdda since your population seems to be able to reproduce this with some consistency?

**Comment by n4ndo** [comment] 2018-01-06 01:42
Sure no problem, let me just arrive home and i give feedback.

**Comment by Treeston** [comment] 2018-01-07 15:00
@n4ndo what happened to further crash dumps?

**Comment by tje3d** [comment] 2018-01-07 15:04
@Treeston No problem here for about 1 day ( with 30-40 players )

**Comment by Treeston** [comment] 2018-01-07 15:05
Are you _sure_ the original crashes happened on e0b609a, and not some earlier rev?

**Comment by Treeston** [comment] 2018-01-08 15:24
> Are you sure the original crashes happened on e0b609a, and not some earlier rev?

@tje3d

**Comment by tje3d** [comment] 2018-01-08 15:42
@Treeston Eveyrthing works fine, i have no problem for days.

**Comment by Treeston** [comment] 2018-01-08 15:44
.....I will assume you posted the incorrect commit hash in the original issue then. Closing.

**Comment by n4ndo** [comment] 2018-01-08 16:13
Hello @Treeston i'm sorry, i put the correct commit hash, since this pased days was holydays, i was forced to revert up to 425b181544a21d2246fdf0261ba76a37e2510883 (can't leave the server crashing).

I go to update up to 57672fdf259d1106420e6a2c91f6f1b65b00fbc9 and tell you the results, sorry my delay.

**Comment by Treeston** [comment] 2018-01-08 16:35
Oh - apologies, confused you two. Re-opening until confirmation.

**Comment by n4ndo** [comment] 2018-01-09 16:40
Ok, so, today i finally update to 274dede3dc89fa72ec1687d5ff454feba9849e47, and first crash:

```
Sources/src/server/game/Combat/ThreatManager.cpp:696 in PutThreatListRef ASSERTION FAILED:
  !inMap Duplicate threat reference at 0x7f538d790f40 being inserted on GUID Full: 0xf1300079aa000024 Type: Creature Entry: 31146  Low: 36 for GUID Full: 0xf1300079f0003099 Type: Creature Entry: 31216  Low: 12441 - memory leak!
```

-

**Comment by Treeston** [comment] 2018-01-09 16:41
Thanks, will take a look.

**Comment by n4ndo** [comment] 2018-01-09 17:07
Another:

- https://pastebin.com/pnHqrGVf

**Comment by Treeston** [comment] 2018-01-09 17:17
Can you post assertion output + crash dump for these?

**Comment by Treeston** [comment] 2018-01-09 17:33
`31216` is a target dummy...the plot thickens.

**Comment by Treeston** [comment] 2018-01-09 23:22
3dcd49e fixes a super edge case iterator invalidation that could _potentially_ be the cause of this. Could you update and report back?

**Comment by n4ndo** [comment] 2018-01-10 02:05
sure @Treeston let me update again and i tell you the results.

**Comment by n4ndo** [comment] 2018-01-13 16:37
Sorry @Treeston my delay, tomorrow i go to update and tell you the results.

**Comment by Foereaper** [comment] 2018-01-13 19:35
Updated to latest rev 46e1e35, hitting the assert in ThreatManager::PutThreatListRef ThreatManager.cpp

Every time it has happened so far on my end is when a mage has used Mirror Image when attacking a target dummy, not sure if it is relevant or not though.

**Comment by Treeston** [comment] 2018-01-13 19:35
That's very interesting, @Foereaper. I'll take a look at that specific case when I find the time.

**Comment by Foereaper** [comment] 2018-01-13 19:44
Yeah, just checked all the dumps I have so far, and they all point to creature ID 31216, which is Mirror Image

http://prntscr.com/i00bl0

**Comment by Laintime** [comment] 2018-01-13 19:54
@Treeston https://pastebin.com/WTTUChVv 5 crashes fo 6h ,uptame 1h.
last rev clean tk

**Comment by tkrokli** [comment] 2018-01-14 04:57
@Laintime : instead of "last rev clean tk" (?) please post your actual revision info.
("last rev" can change several times & every day, so "last rev" is not useful info)

**Comment by Laintime** [comment] 2018-01-14 09:47
@tkrokli update

**Comment by Laintime** [comment] 2018-01-15 06:09
@Treeston any news???it's critical

**Comment by tkrokli** [comment] 2018-01-15 10:41
If this problem is critical to you, feel free to go back to an earlier and more stable version.

**Comment by Treeston** [comment] 2018-01-15 12:11
Should have some time a bit later today.

**Comment by Treeston** [comment] 2018-01-15 13:03
Bingo, with mirror images I can reproduce this.

**Comment by Treeston** [comment] 2018-01-15 14:45
@Laintime @Foereaper @n4ndo 1847555 should fix the underlying issue here. Mirror Image AI is a tad naughty - but that's fine, and the core should handle it gracefully.

I couldn't reproduce it at all after this commit, so I believe this should fix the issue. Please report back.

**Comment by Laintime** [comment] 2018-01-15 15:07
@Treeston thanks!

**Comment by Treeston** [comment] 2018-01-16 20:30
@Laintime @Foereaper @n4ndo have any of you updated yet? Has this resolved the issue?

**Comment by Foereaper** [comment] 2018-01-16 21:12
I have yet to get my test server back up and running, but will do so hopefully tomorrow, I'll let you know asap

**Comment by Laintime** [comment] 2018-01-17 11:16
@Treeston I put only today,we wait.

**Comment by Treeston** [comment] 2018-01-19 14:12
@Laintime @Foereaper @n4ndo any updates?

**Comment by Laintime** [comment] 2018-01-19 17:19
@Treeston yes,two days this ok.

**Comment by Foereaper** [comment] 2018-01-19 17:20
Seems good so far!

**Comment by Laintime** [comment] 2018-01-19 20:37
@Treeston reopen https://pastebin.com/QGC8qEmu rev https://github.com/TrinityCore/TrinityCore/commit/b8c281f497d5da2251b11ab09f182a23a5721a1c  (TrinityCore branch) (Unix, RelWithDebInfo, Static)
crash :'(

**Comment by Laintime** [comment] 2018-01-19 20:49
@Jildor Any ideas?

**Comment by Treeston** [comment] 2018-01-19 21:05
f*ing mirror images, how do they work

**Comment by Treeston** [comment] 2018-01-19 21:05
(but yeah, that's a release crashdump, not much info in there - any idea what caused it?9

**Comment by Foereaper** [comment] 2018-01-19 21:06
No crash here so far, running debug though and will let you know if/when it happens

**Comment by Laintime** [comment] 2018-01-19 21:16
@Treeston CombatManager::IsInCombatWith (this=0x7fff175ce790, guid=...) at /home/source/azur/src/server/game/Combat/CombatManager.cpp:210
210     return (_pveRefs.find(guid) != _pveRefs.end()) || (_pvpRefs.find(guid) != _pvpRefs.end());

No find guid,maybe summon ads fo boss,no guid target die,crash

**Comment by Langerz82** [comment] 2018-01-21 09:58
have you got the call stack?

**Comment by Treeston** [comment] 2018-01-21 12:58
what @Laintime is not a line that could ever crash in a debug context

**Comment by Laintime** [comment] 2018-01-21 19:30
@Treeston Tomorrow I'll put the debug on my server

**Comment by n4ndo** [comment] 2018-01-30 14:03
Well i update today up to 1acfefb973895b0e3df3c8d9b43b920d2a1b5392 and 20 crash until now, (i revert again to 01/01/2018).

Now i shows Creature::SelectVictim():


- https://pastebin.com/fQ3PEU8Y
- https://pastebin.com/s9bKJ9iM
- https://pastebin.com/CdbXQ257

Cordially

**Comment by Treeston** [comment] 2018-01-30 16:05
Yeah, see if 1acfefb fixes this.

**Comment by Treeston** [comment] 2018-02-01 15:04
@Laintime @Foereaper @n4ndo any updates since 1acfefb?

**Comment by Foereaper** [comment] 2018-02-01 15:24
I haven't experienced anything at least

**Comment by Treeston** [comment] 2018-02-11 22:11
assuming fixed

**Closed by Treeston** 2018-02-11 22:11 UTC
Labels: Branch-3.3.5a, Comp-Core, HasBacktrace
