### ISSUE TITLE
Explosive Sheep (Engineering) Not Functioning Correctly

### ISSUE THREAD

**Issue by Vavehl** [TrinityCore/TrinityCore#1729] opened 2011-05-29 02:47 UTC
Explosive Sheep do not explode, although they will randomly charge enemies.  The sheep appear to last for the correct duration (3 minutes) before disappearing, but will not detonate at all.

TrinityCore Revision: 44bb64295b3eda254a83 (from 17-May-2011)
TrinityCore Database: 335.11.40
##

**Comment by offl** [comment] 2020-08-12 01:37
Duplicate of #21753

**Closed by offl** 2020-08-12 01:37 UTC
Labels: Sub-Spells
