### ISSUE TITLE
Quest Garments of the Light & Garments of the Moon

### ISSUE THREAD

**Issue by Aldoran2020** [TrinityCore/TrinityCore#26230] opened 2021-03-12 15:42 UTC
**Description:**
 
 Its not possible to use spells on the targets npc for priest class quest,.

**Expected behaviour:**

Use the spells on the npcs and the quests completed

**Steps to reproduce the problem:**

1. Quest ids 5621 and 5624
2. NPC entry 12476 and 12423

**Branch(es):**

3.3.5

TrinityCore rev. cfe5b6452bdd 2021-02-15 15:14:59 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) 
TDB 335.21021

**Operating system:** 

Windows 10 x64

**Comment by offl** [comment] 2021-03-12 15:44
Duplicate of #26009

**Closed by offl** 2021-03-12 15:44 UTC
Labels: Branch-3.3.5a
