### ISSUE TITLE
Worldserver crash,  player_levelstats need update

### ISSUE THREAD

**Issue by tctwod** [TrinityCore/TrinityCore#13876] opened 2015-01-10 14:13 UTC
Image: http://i61.tinypic.com/ouyv7s.jpg

By adding this commit sql: https://github.com/TrinityCore/TrinityCore/commit/f4047d5b31b4c0413476c726fa710c863e06e9eb the emulator fails, the error is in player_levelstats need updating. 

Db error: http://pastebin.com/bQudLPph

i have fixed this crash, please check out 

http://cloud.tecnolatin.com/public.php?service=files&t=af4a8805e5a993150ec49cb204b0c4eb

**Comment by xerkoss** [comment] 2015-01-10 14:33
Where did you get those values?

**Comment by msoky** [comment] 2015-01-10 14:47
https://github.com/TrinityCore/TrinityCore/issues/13842
https://github.com/TrinityCore/TrinityCore/issues/13818

**Comment by tctwod** [comment] 2015-01-10 14:53
msoky dat commits are added on official branch?

**Comment by msoky** [comment] 2015-01-10 14:55
not yet

**Comment by tctwod** [comment] 2015-01-10 14:56
but works or need update for add on trinity branch

**Comment by tctwod** [comment] 2015-01-10 15:02
thanks vincent

**Comment by DDuarte** [comment] 2015-01-10 19:17
Dupe of #13823

**Closed by DDuarte** 2015-01-10 19:17 UTC
Labels: Branch-6.x, Comp-Database, Priority-FutureFeatureRequest, Sub-Entities
