### ISSUE TITLE
[3.3.5] Thel'zan's Phylactery

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16329] opened 2016-01-19 21:09 UTC
Branch 3.3.5, rev. 8a0bbc386982

[GO: Thel'zan's Phylactery](http://www.wowhead.com/item=37920/thelzans-phylactery)
Only one of [Thel'zan's Phylactery](http://www.wowhead.com/item=37920/thelzans-phylactery) drops, instead of one dropping for every player on the [quest](http://www.wowhead.com/quest=12467/chasing-icestorm-thelzans-phylactery).

EDIT: Same issue for [Scythe of Antiok](http://www.wowhead.com/item=38305/scythe-of-antiok) from [Scythe of Antiok](http://www.wowhead.com/object=190354/scythe-of-antiok) for [On Ruby Wings](http://www.wowhead.com/object=190354/scythe-of-antiok).

EDIT: Also [Drakuru's Skull](http://www.wowhead.com/item=40425/drakurus-skull) from [Drakuru's Skull](http://www.wowhead.com/object=191458/drakurus-skull).

**Comment by tkrokli** [comment] 2016-01-19 21:13
Is this the quest http://www.wowhead.com/quest=12467/chasing-icestorm-thelzans-phylactery
or the other quest, http://www.wowhead.com/quest=12472/finality ?

**Comment by Treeston** [comment] 2016-01-19 21:59
Same issue for [Scythe of Antiok](http://www.wowhead.com/item=38305/scythe-of-antiok) from [Scythe of Antiok](http://www.wowhead.com/object=190354/scythe-of-antiok) for [On Ruby Wings](http://www.wowhead.com/object=190354/scythe-of-antiok).

**Comment by tkrokli** [comment] 2016-01-19 22:36
Maybe a condition issue? Or could it have something to do with items or GOs not handling group quests?

**Comment by Killyana** [comment] 2016-01-20 01:15
Because the gob despawn once looted, you have to check how this kind of objects are handled on retail when player are in party.

**Comment by Aokromes** [comment] 2016-01-20 01:51
Duplicate of #12842?

**Comment by tkrokli** [comment] 2016-01-20 06:48
Maybe, I am not sure. If the issue causing this problem is a GO issue, yes. I was thinking about GO being the cause of this issue like in Krom'zar's Banner, but if this one can be solved by conditions, it could be different. This issue looks like it is more about a quest item not dropping for all from an NPC corpse.
Then again, #12842 mentions other issues where the GO in question is lootable from an NPC.

**Comment by dr-j** [comment] 2016-01-20 11:34
theres no condition which will help here once the go is sucessfully looted by a single player they despawn, maybe these goes should actually behave more like raid chests and despawn once last player who is elegible to loot loots chest.

**Comment by dr-j** [comment] 2016-01-20 12:00
in fact can anyone think of a single gameobject outside of a raid which contains a quest item which is lootable by multiple players.

.Like this issue is still present in 5 man instances ie that research by bonus boss in nexus can only be looted by one player at a time then next player must wait for respawn before can loot.

But same happens with mobs there are some mobs which were a quest item drops all elegible players in party should also receive that same quest item from same mob but on tc only 1 player receives ie http://www.wowhead.com/item=35490/arcane-splinter

**Comment by Treeston** [comment] 2016-01-20 12:11
On retail, every player present can loot these GOs regardless of party, and they will never despawn due to being empty (as they are never "empty"), only due to time.

**Comment by Killyana** [comment] 2016-01-20 12:51
Ok so it's a core issue.

**Comment by tkrokli** [comment] 2016-01-20 20:39
Is this also the case for any quest item to be looted in any 5-man normal instance like Ragefire Chasm?

**Comment by Treeston** [comment] 2016-01-20 22:46
I think the difference is that creatures have a concept of "tagging player", and generate a separate instance of the quest item for any tagging player that has the required quest.

GOs do not have any concept of tagging player (they don't on retail either), but on TC they only generate a single quest item (which can be looted by the first player to loot the GO) while on retail the quest item can be looted by arbitrarily many different players until the GO despawns.

**Comment by dr-j** [comment] 2016-01-20 22:54
This is probably related too https://github.com/TrinityCore/TrinityCore/issues/8952

**Comment by tkrokli** [comment] 2016-01-20 23:03
@Treeston : thanks for the info about GOs. I hope you will be able to find a solution sooner or later. :+1:

**Comment by Rushor** [comment] 2016-02-09 09:05
this is exactly the same issue: https://github.com/TrinityCore/TrinityCore/issues/12842

i added the cases from this issue to https://github.com/TrinityCore/TrinityCore/issues/12842

https://github.com/TrinityCore/TrinityCore/issues/12842#issuecomment-52561152

**Closed by Rushor** 2016-02-09 09:05 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Quests
