### ISSUE TITLE
Raider Jhash and Raider Kerr are missing their RP script

### ISSUE THREAD

**Issue by Rothend** [TrinityCore/TrinityCore#24857] opened 2020-06-21 06:02 UTC
**Description:**

From what I could see from Classic's PTR, [Raider Jhash](https://classic.wowhead.com/npc=10676/raider-jhash) and [Raider Kerr](https://classic.wowhead.com/npc=10682/raider-kerr) are supposed to run from Razor Hill to Valley of Trials and back (at some point they walk, at other points they run) and have some associated emotes:

- "%s and Raider Kerr let their wolves rest a bit and drink..." (broadcast text id: 5986)
- "%s and Raider Kerr charge into battle..." (broadcast text id: 5987)

I couldn't get an useable footage because I don't have a character on Classic. A 100% mount is probably needed to follow those NPCs without losing them.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 05025d79f3cb34fa135cb820badeef32883f7eb4

**Comment by offl** [comment] 2022-01-28 00:18
Duplicate of #27680

**Closed by offl** 2022-01-28 00:18 UTC
Labels: Comp-Database, Branch-3.3.5a
