### ISSUE TITLE
[3.3.5] Scrolls dispell Mark of the wild and scrolls dispell are other scrolls instantly

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#25405] opened 2020-09-05 19:12 UTC
reproduce 1:

1. mark of the wild from 15er Druid  https://classic.wowhead.com/spell=24752/mark-of-the-wild
2. I take the item scroll-of-intellect  https://classic.wowhead.com/item=955/scroll-of-intellect
3. Mark of wild are dispellt from 2.
4. I take other scroll and this dispell the other scroll.

the rigt is to stack all scrolls and no dispell then i take a other scroll or when i have a scroll to become a spell from druid thit no error message.

reproduce 2. 

1 .i take scroll-of-stamina https://classic.wowhead.com/item=1180/scroll-of-stamina (or other scroll)
2. The druid can´t give me mark of the wild from 15er Druid  https://classic.wowhead.com/spell=24752/mark-of-the-wild

reproduce 3.

1. druid make self mark of wild
2. druid take a scroll of intellect and the mark of wild are dispell from this
3. other scrolls dispell the aktualy scroll
4. mark of wild are blocked

3.3.5

1e446b021b704818fb4ef9bd8622716d138295b0

**Comment by offl** [comment] 2020-09-05 20:41
Duplicate of #17912

**Closed by offl** 2020-09-05 20:41 UTC
Labels: Branch-3.3.5a
