### ISSUE TITLE
expired instance lock

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17105] opened 2016-05-09 13:00 UTC
when player go instance and saved 
when instance lock time end write on instance lock "expired"
and instance save cannot remove

Screen shot (example FOS-POS)
http://uploads.im/MyLje.png

1. go instance [Dungeon/raid] and kill boss (saved instance)
2. wait to instance lock time 0
3. instance lock dont remove and u see [expired in black

335/

https://github.com/TrinityCore/TrinityCore/commit/775b03bf6f345ac2bdc4936bb0ead5b0ad4fb193
 
Centos 6

**Comment by Ovahlord** [comment] 2016-05-09 14:33
It's not a bug, it's a feature. Intended.

**Comment by tkrokli** [comment] 2016-05-09 16:36
Looks normal and working as intended to me. The **[Expired]** status is present to make it possible to **extend the lock duration** by pressing the **[Reactivate Raid Lock]** button. This feature can be very useful in case you need to visit the raid instance again without any of the bosses being present, like if you need to activate a gameobject or talk to a friendly or neutral NPC. Unless you have observed any other issues happening because of this Raid Lock status, I am pretty sure this issue can be closed with the label **[Invalid-Intended-WontFix]** applied when closing.

**Closed** 2016-05-09 16:40 UTC

**Comment by SQLfix** [comment] 2016-05-09 21:21
how can disable it ? 
2- or how player can delete expired lock [remove]

**Comment by tkrokli** [comment] 2016-05-09 21:25
Just ignore the  [Expired] status and you are most likely going to get a new raid lock upon entering with a new raid group.

**Comment by SQLfix** [comment] 2016-05-09 21:59
we can disable this feature ?

**Comment by Aokromes** [comment] 2016-05-09 22:10
No, it's blizzlike.
