### ISSUE TITLE
DB/Creature: Arch Mage Xintor ooc event

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#27221] opened 2021-10-31 12:31 UTC
### Description

Arch Mage Xintor atm is doing nothing and Hellfire Combat Dummys are not spawned (the big ones).
also his SAI spells need to be reworked ~~[and most likely Shroud of Death need to be added as aura and removed from SAI.](https://github.com/TrinityCore/TrinityCore/commit/3e6a4e0b4484b241a103a912ebc180b163fe815c)~~

I tried something like this as a test on small dummyes but it doesn't face the target :

```sql
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 16977;
DELETE FROM `smart_scripts` WHERE (`entryorguid` = 16977) AND (`source_type` = 0) AND (`id` IN (6));
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(16977, 0, 6, 0, 1, 0, 100, 0, 0, 0, 3400, 13800, 0, 11, 29456, 0, 0, 0, 0, 0, 10, 86051, 17060, 0, 0, 0, 0, 0, 0, "Arch Mage Xintor - OOC - Cast 'Fireball'");
```

https://user-images.githubusercontent.com/24683355/139583240-ed5381a4-a837-4fed-9165-0d3daf15932c.mp4

### Expected behaviour

Arch Mage Xintor when out of combat shoud have a event and cast Fireball ID 29456 and /or possible Pyroblast 29459 on some Hellfire Combat Dummys that are not spawned on TC.
See videos below:
https://youtu.be/WcBhqVn6xrQ?t=44 - here it does cast when ooc
https://youtu.be/1ougucIEN0M?t=52 - here as another look at the dummys

### Steps to reproduce the problem

.go c id 16977

### Branch

3.3.5

### TC rev. hash/commit

ee263a3e2f7b

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by CraftedRO** [comment] 2021-10-31 12:39
Also his respawn timer need to be lower , atm is 5min

```sql
-- Set Arch Mage Xintor spawntime 1min 12sec according to https://tbc.wowhead.com/npc=16977/arch-mage-xintor#comments
UPDATE `creature` SET `spawntimesecs` = 72 WHERE `id` = 16977 AND `guid` = 86049;
```

**Comment by Rushor** [comment] 2021-11-05 19:46
what is that dwarf that spawned after the kill?

**Comment by CraftedRO** [comment] 2021-11-06 09:49
Yea they're most likely Ghostly Denizen https://tbc.wowhead.com/npc=16976/ghostly-denizen and it seems after killing him they come and sit near corpose.

**Comment by CraftedRO** [comment] 2021-11-06 09:55
Yea they're most likely Ghostly Denizen https://tbc.wowhead.com/npc=16976/ghostly-denizen and it seems after killing him they come and sit near corpse.

**Comment by offl** [comment] 2021-11-06 12:40
Duplicate of #11387

**Closed by offl** 2021-11-06 12:40 UTC
Labels: Comp-Database, Branch-3.3.5a
