### ISSUE TITLE
[master(7.x)] Scenes leaving blackscreen

### ISSUE THREAD

**Issue by nerv234** [TrinityCore/TrinityCore#18422] opened 2016-12-06 19:43 UTC
**Description:** Some scenes don't clear black screen effect.

**Current behaviour:** Some scenes don't clear black screen effect.

**Expected behaviour:** Some scenes should clear black screen effect.

**Steps to reproduce the problem:**
1. Create dh.
2. Insert those values to db:
`DELETE FROM `scene_template` WHERE  `SceneId`=1116;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`) VALUES 
(1116, 27, 1493);`
this is data from sniff.
3. just use command: .scene play 1116
4. and you can see that after completing scene the black screen effect on entire screen stays instead of unapplying.

**Branch(es):** master

**TC rev. hash/commit:**  784d70af7b77674373a355a9f60f37931451d3b2

**TDB version:**  up to commit 784d70af7b77674373a355a9f60f37931451d3b2

**Operating system:**  not related(win7)

**Comment by Shauren** [comment] 2016-12-06 19:45
duplicate of #18294

**Comment by Aokromes** [comment] 2016-12-06 19:45
#18294

**Closed** 2016-12-06 19:45 UTC
