### ISSUE TITLE
Channeled auras are sometimes getting interrupted during movement

### ISSUE THREAD

**Issue by Ovahlord** [TrinityCore/TrinityCore#22152] opened 2018-07-11 20:59 UTC
**Description:**
It appears that somewhere in the depths of the core the movement-checks for channeled spells are getting applied a bit too late. When you fight against a creature that is using channeled spells and kite the creature arround, in some rare cases the channeled spell is getting interrupted for no reason. 
This case happens even more often when multiple targets fight against a creature for example like a dungeon boss.

**Current behaviour:**
In some very rare cases channeled spells are getting interrupted due to movement.

**Expected behaviour:**
The creature should stop moving and channel the spell until the end of its casting time / duration if not having the corresponding attribute to be allowed to move.

**Steps to reproduce the problem:**

1. pick a creature that can chase you and is using channeled spells. Preferably a creature with a spell that is using a channeled aura.
2. Kite the creature arround and wait until the channeling kicks in.
3. Retry until you see the interrupt happening. The propability that this issue happens increases with multiple characters fighting one creature.

**Branch(es):**
 both

**TC rev. hash/commit:** 
rev.: ee632276934e8799eacb4caaa49d535bfd42527e

**Operating system:** Win10 Pro x64

**Comment by Keader** [comment] 2018-07-11 21:05
I got some reports about kite Lich King cause interrupt in Spirits Summon (Channel) too

**Comment by Krudor** [comment] 2018-07-13 20:53
Duplicate of https://github.com/TrinityCore/TrinityCore/issues/21048

**Closed** 2018-07-13 21:08 UTC
Labels: Branch-3.3.5a, Branch-master, Comp-Core, Sub-Spells
