### ISSUE TITLE
DB/Quests: quest rewards for Those That Couldn't Be Saved (26799) & Recruitment (26800)

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19849] opened 2017-06-05 01:14 UTC
Description: 
- http://www.wowhead.com/quest=26799/those-that-couldnt-be-saved
- http://www.wowhead.com/npc=1501/mindless-zombie
- http://www.wowhead.com/npc=1568/undertaker-mordo

The third quest of the beginnings of undead. Given by Undertaker Mordo (ID:1568). He asks us to kill 6 Mindless Zombies (ID:1501) to complete it and continue with the other quests.

**Current behaviour:** (Tell us what happens.)

We can kill the Mindless Zombies (ID:1501) without problems, but when we deliver it, we can not use the [Complete] button.

**Expected behaviour:** (Tell us what should happen instead.)

When killing Mindless Zombies (ID:1501) , we should be able to complete the quest without problems and get the rewards.

**Steps to reproduces the problem:**

1. Create an undead character (it can be any class, but in this case the report was made with a Warrior)
2. Complete the first 2 quests from start until the quest "Those That Couldn't Be Saved" (ID:26799)
3. Kill 6 Mindless Zombies.
4. Try to deliver the quest to Undertaker Mordo (ID:1568)

**Branch(es): Master

**TC rev. hash/commit:** ae83739ac7b4a47703f0960e22ed0caf240a023c

**TDB version:** TDB 7.2.0+updates

**Operating system:** Windows 10

**Comment by tkrokli** [comment] 2017-06-05 14:32
TrinityCore rev. 555fc9d3d5ed 2017-06-05 03:47:14 -0300 (master branch) (Win64, Release, Static)
TDB 720.00 + updates up to and including `2017_06_03_01_world.sql`

Partially confirmed. This looks like a bug caused by the quest reward item [**Battered Cloak**](http://www.wowhead.com/item=11847/battered-cloak):
- http://www.wowhead.com/item=11847/battered-cloak

I tested all available undead classes except for Death Knight, which would take me too long to play through for testing purposes.
Depending on your character class and reward selection, the issue is caused by the item Battered Cloak (item 11847):
- if you are an undead Warrior, Rogue, Hunter or Monk (and likely DK), your only available item is Battered Cloak (item 11847) and the quest cannot be completed.
- if character is a Mage, Priest or Warlock, you can select [**Flax Gloves**](http://www.wowhead.com/item=3275/flax-gloves) and get the reward and complete the quest.
    - if any of these 3 classes select the reward item [**Battered Cloak**](http://www.wowhead.com/item=11847/battered-cloak), the quest gossip gets stuck (incomplete).

Using either Mage, Priest or Warlock, I can block the quest from being completed by selecting the reward item Battered Cloak, then it would not help to select the other item and try again unless I closed the gossip and opened it again. When re-opening the quest gossip and selecting Flax Gloves, I was able to complete the quest as Mage, Priest or Warlock.

I don't know how correct the wowhead page is for these quest items, it seems to show that all classes only get 1 of the items and not be able to choose between 2. I am going to test this on retail to see if Mage, Priest and Warlock get to choose or not.

**Comment by tkrokli** [comment] 2017-06-07 00:11
Aha. I see. This seems to be related to issue #18955 **[master] fix for broken quest Blood Elf/Sunstrider Isle**
There is no data in the DB quest_template table for the following fields (columns):
```
RewardChoiceItemID1 / RewardChoiceItemQuantity1 / RewardChoiceItemDisplayID1
RewardChoiceItemID2 / RewardChoiceItemQuantity2 / RewardChoiceItemDisplayID2
```
All these columns show 0 instead of item ID, item displayID & quantity (1). Yes, I know. Devs have said that this is supposed to be handled by the core, but either the core is not able to look up the proper item info, or the DB needs table info for these items to handle them properly. I suggest testing if it works by adding the item info in the following update query:
```sql
UPDATE `quest_template` SET `RewardChoiceItemID1` = 3275, `RewardChoiceItemQuantity1`= 1, `RewardChoiceItemID2`= 11847, `RewardChoiceItemQuantity2`=1 WHERE `ID`=26799;
```
@HannibalRoG : can you test and see if this works and still offers different items to different classes?
- Warrior & Hunter & Rogue & Death Knight & Monk should receive only Battered Cloak (11847)
- Priest & Mage & Warlock should receive either only Flax Gloves (3275) or also Battered Cloak (11847) (if that is how the quest rewards are supposed to be).

**Comment by HannibalRoG** [comment] 2017-06-07 01:15
Yes, give me 20 minutes.

**Comment by HannibalRoG** [comment] 2017-06-07 01:25
Yujuuu... it solve the problems for Warrior, now we can complete quest, now i will see if Priest and other have multiple choises.

**Comment by HannibalRoG** [comment] 2017-06-07 01:29
Yehaaa now you can choses any of the item en quest and complete it.
@tkrokli quest 26800 comment above need the same fix.

**Comment by tkrokli** [comment] 2017-06-07 01:32
Very well. I guess there is something else controlling exactly which quest rewards are supposed to be offered. If the wowhead info is correct, there should be only 1 item available to all classes, but I hope the current TC selections are based on sniffs.

By the way, feel free to add any other quests where you find this same issue, so we can solve them the same way, in the same SQL solution. 👍

**Comment by HannibalRoG** [comment] 2017-06-07 01:41
I think it would be better to go fix as they appear, I can even expect to have several to do a single sql, but as we do not know how many are in that situation and there are thousands in the DB should be as they appear appearing not wait until they all appear. Do you think?

**Comment by tkrokli** [comment] 2017-06-07 01:44
Well, you do have a point. Let us just focus on the 2 quests you have  pointed out here so far and let the SQL solution close this issue. It is totally OK to open a new issue for new quests, although it would be nice to group similar quests together (quests you find in the same area or in the same quest chain). 👍

**Comment by tkrokli** [comment] 2017-06-07 01:56
**Suggested solution:**
```sql
-- Quests: Those That Couldn't Be Saved (26799) / Recruitment (26800)
-- make the quest rewards selectable for all classes, not only one of them
UPDATE `quest_template` SET `RewardChoiceItemID1` = 3275, `RewardChoiceItemQuantity1`= 1, `RewardChoiceItemID2`= 11847, `RewardChoiceItemQuantity2`=1
 WHERE `ID`=26799;
UPDATE `quest_template` SET `RewardChoiceItemID1` =11848, `RewardChoiceItemQuantity1`= 1, `RewardChoiceItemID2`= 11849, `RewardChoiceItemQuantity2`=1, `RewardChoiceItemID3`= 11850, `RewardChoiceItemQuantity3`=1
 WHERE `ID`=26800;
```

**Closed** 2017-06-07 02:45 UTC
Labels: Branch-master, Comp-Database, Feedback-PatchFix, Sub-Quests
