### ISSUE TITLE
Professions

### ISSUE THREAD

**Issue by LewisPotato** [TrinityCore/TrinityCore#22903] opened 2019-01-02 02:12 UTC
**Description:**

For some reason I can learn more than 2 primary professions.

**Current behaviour:**

I just went and learned Alchemy and Herbalism and for some reason it'll let me learn Tailoring, Blacksmithing and Engineering. The whole lot pretty much.

**Expected behaviour:**

Should not be able to have more than 2 professions learned unless of course you change the setting from 2 to whatever in the config.

**Steps to reproduce the problem:**

1. Go to any profession trainer and you should (well I can) learn all the primary professions.

**Branch(es):**

3.3.5a

**TC rev. hash/commit:** 

TrinityCore rev. 66720e5fd940 2018-12-31 11:50:16 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Windows Server 2016

**Comment by Killyana** [comment] 2019-01-02 09:39
Confirm on rev. 1c4cdfd32503
Probably caused by the new trainer system.

**Comment by jackpoz** [comment] 2019-01-02 11:52
@Ghaster could you check this issue ?

**Comment by LewisPotato** [comment] 2019-01-02 12:06
It's definitely not my configuration as I have everything blizzlike.

**Comment by Ghaster** [comment] 2019-01-02 13:02
Hmmm, try this:

In Trainer::CanTeachSpell replace:
```
        SpellInfo const* trainerSpellInfo = sSpellMgr->AssertSpellInfo(trainerSpell->SpellId);
        if (trainerSpellInfo->IsPrimaryProfessionFirstRank() && !player->GetFreePrimaryProfessionPoints())
            return false;
```
with the following:
```
        for (int32 reqAbility : trainerSpell->ReqAbility)
        {
            SpellInfo const* trainerSpellInfo = sSpellMgr->AssertSpellInfo(trainerSpell->SpellId);
            if (trainerSpellInfo->IsPrimaryProfessionFirstRank() && !player->GetFreePrimaryProfessionPoints())
                return false;
        }
```

**Comment by LewisPotato** [comment] 2019-01-02 14:08
Once it has been implemented I'll recompile and test it.

**Comment by Ghaster** [comment] 2019-01-02 14:20
I did find one more bug, which is professions "ranks" counting as a seperate profession. I believe I know why that's broken aswell, but at this point I think it easier to open a PR for all of these fixes.

**Comment by LewisPotato** [comment] 2019-01-02 14:21
Hope it doesn't take too long to fix, itching to start playing!

And yeah I agree.

**Comment by LewisPotato** [comment] 2019-01-02 14:43
> I did find one more bug, which is professions "ranks" counting as a seperate profession. I believe I know why that's broken aswell, but at this point I think it easier to open a PR for all of these fixes.

Is it okay if you can open a PR? I have no clue what I'm doing past opening an issue.

**Comment by LewisPotato** [comment] 2019-01-02 17:19
This issue has been closed as a pull request has been made.

**Comment by Killyana** [comment] 2019-01-02 17:20
The pr must close the issue.

**Closed** 2019-01-03 15:52 UTC
Labels: Branch-3.3.5a, Comp-Core

**Comment by Killyana** [comment] 2019-01-03 18:55
@Ghaster Do you know if this is the correct behavior, when you learn 2 professions, if you try to learn a third one it appears in green and not in red, it was always like this on TC it's not new.

![image](https://user-images.githubusercontent.com/6587064/50655721-42637680-0f91-11e9-9ef1-b9cc8bbbae37.png)

**Comment by LewisPotato** [comment] 2019-01-03 19:00
Yeah, that is an odd one, I always thought it was normal behavior.

**Comment by Kittnz** [comment] 2019-01-03 19:11
Not normal ^^

**Comment by LewisPotato** [comment] 2019-01-03 19:12
Has a fix ever been attempted?

**Comment by Shauren** [comment] 2019-01-03 19:34
Its correct. Spell is showed in green when you meet all requirements for it - and those are: level, skill rank, required previous spells
The other part of UI is disabled learn button - it is disabled only in one case, when you dont have enough "things" to pay for the cost. Cost is defined as a combination of 3 things: gold, character points (free profession count) and talent points (yes, client supports trainer spells that cost talents)
