### ISSUE TITLE
[6.x.x] Incorrect Location Of Graveyards

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#14089] opened 2015-02-10 01:36 UTC
Rev: https://github.com/TrinityCore/TrinityCore/commit/36963f244279b958d9808aa4e3a420328a53e9ef

Issue: For example you create a level 1 orc and you die, you go to barrens as a spirit, and you shouldnt go so far

**Comment by Kittnz** [comment] 2015-02-10 07:42
Where would you respawn then?

**Comment by Rushor** [comment] 2015-02-10 11:31
the correct point: http://pokit.org/get/?ac6166201f10f38026427cac11b9f9c5.jpg

**Comment by flippy84** [comment] 2015-02-11 15:06
I have the same problem and i get this error:
"No graveyards found for zone 6170 for GUID Full: 0x0000000000000005 Type: Player
 Entry: 0  Low: 5 (team 469) in CMSG_REQUEST_CEMETERY_LIST"
Only difference is that this is in the human starting zone.

**Comment by Aokromes** [comment] 2015-02-12 07:17
Plz, supply logs of all affected graveyards.

**Comment by Frytiks** [comment] 2015-06-13 10:49
Any news on this ? So huge bug

**Comment by Aokromes** [comment] 2015-06-13 10:50
https://github.com/TrinityCore/TrinityCore/issues/14089#issuecomment-74027821

**Comment by Frytiks** [comment] 2015-06-13 11:27
You want to test all graveyards ?

**Comment by Aokromes** [comment] 2015-06-13 11:42
If you report graveyard bugged the minimum you must supply is a list of bugged graveyards.

**Comment by Frytiks** [comment] 2015-06-13 16:28
I not report it, im just asked if something is new there

**Comment by djbeauchamp** [comment] 2016-05-22 18:43
I can confirm that if you die in Northshire Valley you end of at the Westfall Graveyard.
Table `game_graveyard_zone` incomplete: Zone 6170 Team 469 does not have a linked graveyard.

Sniff from Retail: https://community.trinitycore.org/topic/12683-northshire-valley-sniff/

**Comment by Aokromes** [comment] 2016-06-15 05:46
When https://github.com/TrinityCore/TrinityCore/commit/e2c01899272d1e6c6bbf990676b818cceaf18c9c is merged into 6.x we will have a easy way to fix this issue.

**Comment by mhubregtse** [comment] 2016-08-03 15:05
any updates on this?

**Comment by JaredNinja** [comment] 2016-09-26 14:15
I found the problem:

When dying in Northshire, trinity is looking for a graveyard near (sub)zone 6170 (team 469:alliance).

It states in the worldserver console: "Table 'game_graveyard_zone' incomplete: Zone 6170 Team 469 does not have a linked graveyard"

Expecting to go to:
graveyard 105, zone 12, team 469: elwynn - northshire

Actually going to:
graveyard 4, zone 40, team 0: westfall sentinel hill

So what is happening? I followed the code..

Since 6170 (Northshire) seems like a subzone of 12 (Elwynn).. I noticed the following..

ObjMgr::LoadGraveyardZones() will not accept a new DB record (graveyard_zones table) using: 105,6170,469. It skips loading subzones intentionally (line 6000).

Meanwhile ObjMgr::GetClosestGraveyard() does not translate subzones into parent zones (line 6055-6059).

Conclusion; it cannot process death in Northshire (6170) correctly. Its the subzone numbers causing it. Or, the loading skipping subzones, or, the getclosest function not translating subzones into parent zones.

**Closed** 2016-09-27 06:43 UTC
Labels: Branch-6.x, Comp-Database
