### ISSUE TITLE
Druid/Spells Prowl shapeshift 

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#26222] opened 2021-03-09 22:41 UTC
**Description:**

If you use Prowl you get in stealth and Catform BUT you can remove Catform and you still be in Prowl Stealth
https://github.com/TrinityCore/TrinityCore/pull/26088

**Expected behaviour:**

If you are in Prowl stealth and remove Catform you should also get removed Prowl.

**Steps to reproduce the problem:**

1. create a Druid
2. use Prowl
3. remove Catform

**Branch(es):**

master

**TC rev. hash/commit:** 

0aa3a0b0b9430d2b92e6a69e6c3bc205bfebfa57

**Operating system:** 

Win10

**Comment by offl** [comment] 2021-03-09 22:53
I'd like to leave this more fresh issue open but old one has reference to 'may-be-similar' issue
Duplicate of #17410

**Closed by offl** 2021-03-09 22:53 UTC
Labels: Branch-master

**Comment by CraftedRO** [comment] 2021-03-09 23:34
Imagine that issue wasn't fixed since 6.x aka draenor , don't get me wrong but I don't see the point to keep working on latest master patch instead for example a stable cata 4.3 core but this is just my point idk .

**Comment by offl** [comment] 2021-03-09 23:46
Thing is all the work people do for master also helps a lot to continue to work on 3.3.5 and Cata
Some people like to stay on one place, some people like to move. In the end they all helps each other
