### ISSUE TITLE
[3.3.5] Spell/Warlock: Succubus-Seduction not work propertly

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18289] opened 2016-11-21 03:34 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
After the Succubus casts Seduction the charm is canceled, then (in Passive) begins to attack the target with diminishing returns. @ariel- I found a pattern about distance, Seduction range is 30 yd and only works when the Succubus is in melee range, otherwise Seduction is canceled. The Succubus is fundamental for warlocks. For us this is a very important bug.

**Current behaviour:** 
To more than 5 yd approximately Seduction not work because is cancelled.

**Expected behaviour:** 
Seductiond should work ok up to 30 yd.

**Steps to reproduce the problem:**
1. Duel vs warlock with Succubus
2. Succubus casts Seduction out of melee range.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  50d9a74

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by noryad** [comment] 2016-11-21 14:47
@ariel- I found a pattern about distance, Seduction range is 30 yards and only works from 0 to 5 yards. Maybe this can be useful.

**Comment by Keader** [comment] 2016-11-22 15:08
@SnapperRy maybe relaed with Range Issues? #17545

**Comment by noryad** [comment] 2016-11-22 17:01
About the range and the spell:
1- Succubus casts Seduction in correct range but running to target and should not.
2- The charm effect only works if the Succubus start the cast at 5 yd or less from target.
Confirmed in b333c92

**Comment by Keader** [comment] 2016-11-22 17:12
@noryad please you can give me seduction spell id?

**Comment by Keader** [comment] 2016-11-22 17:17
@noryad i'm not sure if seduction id is correct (i cant load in game right now), and idk if seduction has another spell rankings...
btw test if works:

```diff
diff --git a/src/server/game/Spells/SpellMgr.cpp b/src/server/game/Spells/SpellMgr.cpp
index d034c74..33bd085 100644
--- a/src/server/game/Spells/SpellMgr.cpp
+++ b/src/server/game/Spells/SpellMgr.cpp
@@ -3040,6 +3040,9 @@ void SpellMgr::LoadSpellInfoCorrections()
             case 46947: // Safeguard (Rank 2)
                 spellInfo->RangeEntry = sSpellRangeStore.LookupEntry(34); // Twenty-Five yards
                 break;
+            case 6358: // Seduction
+                spellInfo->RangeEntry = sSpellRangeStore.LookupEntry(4); // Medium Range
+                break;
             // VIOLET HOLD SPELLS
             //
             case 54258: // Water Globule (Ichoron)
```

**Comment by Keader** [comment] 2016-11-22 18:04
naah, dont work
It's not only range issue.
When she is close to target, after 5 sec of cast she top cast too...

**Comment by noryad** [comment] 2016-11-22 18:07
Thank you anyway

**Comment by Keader** [comment] 2016-11-22 18:09
Hmm, looks the "old issue" is back
Should be fixed by: https://github.com/TrinityCore/TrinityCore/commit/66006e3d0dd499152ce367e72fbf223356670eb6

Old issue:  #16628

**Comment by noryad** [comment] 2016-11-22 18:23
The actual code contains this fix but Seduction is broken.

**Comment by djbv** [comment] 2016-11-23 14:56
Please Trinity fix this.

**Comment by noryad** [comment] 2016-11-23 17:55
@ariel- @Keader @Shauren 
I have the c70edcf release dated 04-11-2016 where Seduction works fine, so the error was introduced between 04-11-2016 (c70edcf) and 22-11-2016 (b333c92). For now is the help I can provide.

**Comment by robinsch** [comment] 2016-11-24 10:47
Can't confirm - I'm running without the spell range changes.

**Comment by Shauren** [comment] 2016-11-24 14:56
@robinsch its not.
```
ID - 6358 Seduction
=================================================
Description: Seduces the target, preventing all actions for up to $d.  Any damage caused will remove the effect.  Only works against Humanoids.
ToolTip: Charmed.
Category = 0, SpellIconID = 48, activeIconID = 0, SpellVisual = (2576,0)
Family SPELLFAMILY_WARLOCK, flag [0] 0x40000000 [1] 0x10000000 [2] 0x00000000

SpellSchoolMask = 32 (SPELL_SCHOOL_MASK_SHADOW)
DamageClass = 1 (SPELL_DAMAGE_CLASS_MAGIC)
PreventionType = 1 (SPELL_PREVENTION_TYPE_SILENCE)
=================================================
Attributes: 0x40010000 (SPELL_ATTR0_NOT_SHAPESHIFT, SPELL_ATTR0_HEARTBEAT_RESIST_CHECK)
AttributesEx1: 0x00004004 (SPELL_ATTR1_CHANNELED_1, SPELL_ATTR1_CHANNEL_TRACK_TARGET)
=================================================
Creature Type Mask = 0x00000040 (HUMANOID)
Skill (Id 205) "Pet - Succubus"
    ReqSkillValue 1, Forward Spell = 0, MinMaxValue (0, 0), CharacterPoints (0, 0)Spell Level = 26, base 26, max 0, maxTarget 0

Category = 0
DispelType = 1 (DISPEL_MAGIC)
Mechanic = 1 (MECHANIC_CHARM)
SpellRange: (Id 4) "Medium Range":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 30, MaxRangeFriendly = 30

CastingTime (Id 16) = 1,50
RecoveryTime: 0 ms, CategoryRecoveryTime: 0 ms
StartRecoveryCategory = 133, StartRecoveryTime = 1500,00 ms
Duration: ID (8)  15000, 0, 15000
Power POWER_MANA, Cost 24 %
Interrupt Flags: 0x0000000F, AuraIF 0x00000002, ChannelIF 0x00007C3C
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)
Aura Id 12 (SPELL_AURA_MOD_STUN), value = 0, misc = 0 (0), miscB = 0, periodic = 0

Effect 1:  NO EFFECT

Effect 2:  NO EFFECT

```

**Comment by Keader** [comment] 2016-11-24 14:58
@robinsch  if caused by spell range stuff, should be fixed by https://github.com/TrinityCore/TrinityCore/issues/18289#issuecomment-262304218
``` sSpellRangeStore.LookupEntry(4)``` = 30y

**Comment by Shauren** [comment] 2016-11-24 16:39
Found the cause for this - movement interrupts it.

**Closed** 2016-11-24 19:22 UTC
Labels: Branch-3.3.5a, Sub-PetMinion, Sub-Spells
