### ISSUE TITLE
[DB/Events] Midsummer Fire Festival Missing Spawns

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#14630] opened 2015-04-30 21:12 UTC
There are several Gameobjects and Creatures with spawn missing for the Midsummer event,

I've used as base the work of @Trista(http://www.trinitycore.org/f/topic/6192-wip-event-midsummer-fire-festival-70-complete) the positions from the spawns came from there,I don't know if is sniffed or not, but looks good to me. 

The fix:
          It's a large code, so code in 
                                                     http://pastebin.com/bt1nAbXk    or
                                                    https://gist.github.com/sirikfoll/e4839b2cf187976f67f1

Please give some feedback

**Comment by Kinzcool** [comment] 2015-05-10 05:11
Positions aren't sniffed - you can easily tell just by looking at the coords. One should look in the sniffs, and see what's in them.

**Comment by sirikfoll** [comment] 2015-05-10 11:06
alright, then I'll try to sniff them once the event start on retail. :)

**Comment by Killyana** [comment] 2015-05-20 01:21
Also this spell focus 181371 (Midsummer Bonfire Spell Focus) must be added in the same position for all 181288 Midsummer Bonfire. https://github.com/TrinityCore/TrinityCore/issues/12159

**Comment by sirikfoll** [comment] 2015-05-20 01:58
As seems that this can't be commited until I change the current positions for sniffed ones, soon as i get sniffs i will update it with the Focus  :)

**Comment by Demonid** [comment] 2015-05-27 23:12
Alliance Testing:

NPC: http://wotlk.openwow.com/npc=25909 is missing.

The rest of the Alliance NPC for these achievements are spawned:

http://www.wowhead.com/achievement=1024
http://www.wowhead.com/achievement=1023
http://www.wowhead.com/achievement=1022

Gobs Missing for http://www.wowhead.com/npc=25938
Gobs Missing for http://www.wowhead.com/npc=25918
Gobs Missing for http://www.wowhead.com/npc=25936
Quest Missing for Bonfire http://www.wowhead.com/npc=25939

Horde Testing:

**Comment by Aokromes** [comment] 2015-06-23 21:59
Quest Missing for Bonfire http://www.wowhead.com/npc=25939

Fixed. c8ee638

**Comment by sirikfoll** [comment] 2015-06-24 03:45
I wont open a issue for this, but here's another similar:
```sql
-- Fix A Thief's Reward
DELETE FROM `creature_queststarter` WHERE `quest` IN (9365, 9339);
UPDATE `quest_template` SET `NextQuestId`=9365 WHERE `Id` IN (9324,9325,9326,11935);
UPDATE `quest_template` SET `NextQuestId`=9339 WHERE `Id` IN (9330,9331,9332,11933);

**Comment by Aokromes** [comment] 2016-06-14 03:53
sql needs to be updated.

**Comment by tkrokli** [comment] 2016-06-14 04:43
If you are only waiting for the SQL in https://github.com/TrinityCore/TrinityCore/issues/14630#issuecomment-114719234, you can close this issue now (see info below):

Current TDB 335.61 content (with updates up to and including `2016_06_13_06_world.sql`) :
```sql
SELECT * FROM `creature_queststarter` WHERE `quest` IN (9365, 9339);
```
```
    id   quest  
------  --------
```
```sql
SELECT * FROM `quest_template_addon` WHERE `Id` IN (9324,9325,9326,9330,9331,9332,11933,11935)
 ORDER BY `NextQuestID`;
```
```
   ID  NextQuestID
-----  -----------
 9330         9339
 9331         9339
 9332         9339
11933         9339
 9324         9365
 9325         9365
 9326         9365
11935         9365
```
I haven't checked, but this could have been one of @SnapperRy's fixes during the last few weeks.

**Comment by Aokromes** [comment] 2016-06-14 04:47
we need the spawns to be sniffed then.

**Comment by tkrokli** [comment] 2016-06-14 05:09
Midsummer Fire Festival should start on retail servers in about 1 week's time (around June 20, 2016).

**Comment by Demonid** [comment] 2016-06-21 13:38
Any updates on this to provide feedback?

**Comment by tkrokli** [comment] 2016-06-21 13:43
Sniffs of the Midsummer Fire Festival spawns would be appreciated.
@GnaXi - is this something you would like to give us a hand with? :-)

**Comment by GnaXi** [comment] 2016-06-21 14:05
I'll start up the sniffer right away!

**Comment by GnaXi** [comment] 2016-06-21 15:05
https://community.trinitycore.org/topic/12756-midsummer-fire-festival-missing-spawns/

**Closed** 2016-06-22 11:51 UTC
Labels: Comp-Database, Feedback-FixOutdatedMissingWIP, Sub-Spawns

**Comment by BahDumbBugs** [comment] 2017-06-26 16:55
We may need to re-open this. The Alliance bonfire on Bloodmyst Isle is not working properly. It shows up on the mini map but cannot be selected to desecrate. This is the only one so far I've encountered with issues.

http://i.imgur.com/DgilfCT.jpg

At least as of commit 85a2e (3.3.5). Please advise if I'm incorrect.

**Comment by Killyana** [comment] 2017-06-26 17:06
I cannot reproduce. Try with another character and gm off.

**Comment by BahDumbBugs** [comment] 2017-06-26 17:44
Gm was off at the time. I got it to work, it was just a very funky location the selectable object was in (the icon was actually *INSIDE* the fire itself). Can you post a photo of the location of your "!" or "?" icon on the bonfire please?

**Comment by BahDumbBugs** [comment] 2017-06-26 17:51
Also @Killyana - Did you check on an Alliance toon or Horde toon? Because it was for the Desecration achievement, not the honoring. i.e. Achievement 1032. http://www.wowhead.com/achievement=1032

**Comment by Aokromes** [comment] 2017-06-26 17:55
this ticket is missing spawns, not broken achivements anyway.

**Comment by tkrokli** [comment] 2017-06-26 18:07
@BahDumbBugs : that issue of yours is related to GameObjects and player reach (GameObject size/interaction distance), not with spawns. More related to **[3.3.5a] Large GOs and gossip availability #15453** or maybe other gameobject related issues.

**Comment by BahDumbBugs** [comment] 2017-06-26 19:58
My bad @Aokromes . I just figured if it was part of the same ticket, I stuck it here. (And only as a question related to the Midsummer Fire Festival issues). Hence why I didn't bother opening a new ticket. 
@tkrokli - That makes sense as a better place to put it. But like I said above, it was related to a World Event that comes and goes, not so much a fixed object ingame. - Cheers!
