### ISSUE TITLE
[CRASH] Vehicle::RemovePendingEvent

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#18430] opened 2016-12-08 01:46 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
Vehicle::RemovePendingEvent
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Vehicle/Vehicle.cpp#L685

**Current behaviour**: Tell us what happens
Not sure why is this happening. 4-5 crashes per day.

https://gist.github.com/Jildor/1899485a2d1193293fdfece2352791bc
...

I have another crash and show something like this, but i dont know if is a different crash.

```
Unit (Entry 36656) is trying to delete its updating Movement Generator (Type 2)!
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 0)
Segmentation fault
```

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
Dont know

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
3d5c1b83b15cfc9f73888eb525c64323266c1fd4

**TDB version**:  
62

**Operating system**:  
Linux x64, Dynamic

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by fr4z3n** [comment] 2016-12-08 12:58
Might be related to: https://github.com/TrinityCore/TrinityCore/commit/600e0be7e1f1654a2223ef22559dbd3adb6b100a

**Comment by Undergarun** [comment] 2016-12-11 18:47
I think happen even before

**Comment by Keader** [comment] 2016-12-11 19:32
yeap, i my old server we get this crashs since 2014 +-

**Comment by n4ndo** [comment] 2016-12-12 12:28
Any suggest? this is crashing like hell now, i think someone knows how to crash and is having lots of fun right now :/

**Comment by Shauren** [comment] 2016-12-12 12:52
Nope. And you even wrote it yourself why noone is even looking into it 
>Steps to reproduce the problem:
Dont know

Chasing any crash without any leads is not a good use of anyone's time.

**Comment by Keader** [comment] 2016-12-12 12:57
will not help @n4ndo... that crash fixed by Naios, only happens with me, with dynamic build (hotswap).
btw, your crash happens since 2014... is not caused by Naios commit.

**Comment by n4ndo** [comment] 2016-12-12 16:44
Ok @Shauren, so i remove dynamic building to static and now this is the crash (Maybe more clear?):

- http://pastebin.com/hLz60wvt

**Comment by n4ndo** [comment] 2016-12-21 12:57
Well, with static building i have less crashes but still, 2-3 per day.

- http://pastebin.com/LfK33ZhF

**Comment by Undergarun** [comment] 2016-12-21 22:48
I can confirm the crash with static building

**Comment by Keader** [comment] 2017-09-23 13:03
@n4ndo your pastebin links is not working anymore.

**Comment by Jildor** [comment] 2017-09-23 15:29
Crashlog: https://gist.github.com/Jildor/1899485a2d1193293fdfece2352791bc

**Fix:**
```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index dbed36caee..c9596fcbcc 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -13030,9 +13030,9 @@ void Unit::RemoveVehicleKit()
         return;
 
     m_vehicleKit->Uninstall();
-    delete m_vehicleKit;
 
     m_vehicleKit = nullptr;
+    delete m_vehicleKit;
 
     m_updateFlag &= ~UPDATEFLAG_VEHICLE;
     m_unitTypeMask &= ~UNIT_MASK_VEHICLE;
```

**Comment by Keader** [comment] 2017-09-23 15:35
not make sense this fix to me =x
you will delete VehicleKit after you transform pointer in null? in the end, you just skip delete

**Comment by fvicaria** [comment] 2017-12-17 11:12
The fix suggested is just nonsense. I am also getting this from time to time.

**Comment by Aokromes** [comment] 2019-04-01 13:09
this bug is still valid?

**Comment by Aokromes** [comment] 2019-04-27 12:18
no answer after 26d, if this bug is still valid open a NEW ticket with updated core.

**Closed by Aokromes** 2019-04-27 12:18 UTC
Labels: Branch-3.3.5a, Feedback-WaitingResponse, HasBacktrace
