### ISSUE TITLE
3.3.5 have a dberror when Launching worldserver

### ISSUE THREAD

**Issue by lwyjdgv** [TrinityCore/TrinityCore#14495] opened 2015-04-03 14:08 UTC
Spell 43770 Effect: 43789 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 48750 Effect: 48770 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 53099 Effect: 53098 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 54640 Effect: 54643 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 55288 Effect: 55289 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
ScriptName 'npc_brann_bronzebeard' exists in database, but no core script found!

**Comment by DDuarte** [comment] 2015-04-03 14:09
Duplicate of #13707

Search before creating a new issue.

**Closed by DDuarte** 2015-04-03 14:09 UTC
