### ISSUE TITLE
[3.3.5a] The Lost Mistwhisper Treasure [quest]

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#15620] opened 2015-09-28 02:06 UTC
The Lost Mistwhisper Treasure quest is completed but cannot turn in.
Wowhead link: http://www.wowhead.com/quest=12575/the-lost-mistwhisper-treasure

![q3](https://cloud.githubusercontent.com/assets/1736110/10126622/8670e266-65c8-11e5-8e6d-b07de093dd61.jpg)
![q2](https://cloud.githubusercontent.com/assets/1736110/10126623/881f93a0-65c8-11e5-829f-c46ed2fcfa4c.jpg)

Revision: 747a3f1d38abdb9b711877c168243f0d398b615f

**Comment by tkrokli** [comment] 2015-09-28 05:47
Try running this SQL query to see if it changes anything in your issue:
```sql
UPDATE `quest_template` SET `RequiredItemId1`= 38601 AND `RequiredItemId2`= 0 WHERE `ID`= 12575;
```
If it does not work, you can choose to revert the changes by running this query:
```sql
UPDATE `quest_template` SET `RequiredItemId2`= 38601 AND `RequiredItemId1`= 0 WHERE `ID`= 12575;
```

**Comment by digz6666** [comment] 2015-09-28 06:03
@tkrokli 
![tc](https://cloud.githubusercontent.com/assets/1736110/10128808/a4db229a-65e9-11e5-95a5-00929a936631.png)

When reload quest_template it says error.

**Comment by tkrokli** [comment] 2015-09-28 06:19
Ah, yes of course, you are correct. Silly of me to skip testing the effect of that query before I posted it.

**Comment by digz6666** [comment] 2015-09-28 07:04
@tkrokli It's not working, I've checked if the correct values exist in creature_queststarter and creature_questender tables as well.

**Comment by Treeston** [comment] 2015-09-28 13:15
Try deleting cache/questcache.wdb, feels like data desync.

**Comment by Killyana** [comment] 2015-09-28 13:56
Works for me.
Requirement:
	Warlord Tartek slain
	Mistwhisper Treasure

**Comment by ccrs** [comment] 2015-11-21 14:25
problem here, appart form hardcoded pacify (in fact another issue), is that player cant select a reward and therefore cant turn in the quest.

**Comment by Killyana** [comment] 2015-11-23 16:08
I cannot reproduce the issue, I took the quest, loot the item, the npc spawn with his drake, I killed him, the quest was completed, then back to the quest giver I can choose an reward and complete the quest.

**Comment by ccrs** [comment] 2015-11-23 18:38
how do you killed it?

**Comment by sirikfoll** [comment] 2015-11-23 18:54
I guess this: https://github.com/TrinityCore/TrinityCore/issues/9469#issuecomment-99227360 can solve this issue too

**Comment by Killyana** [comment] 2015-11-23 19:38
I killed it with spell like a player.

**Comment by tkrokli** [comment] 2015-11-23 20:44
@ 2015-11-23, 20:38 CET, Killyana said:
> I killed it with spell like a player.

Hehe ... "like a baws". ;-)
No, I have not tested this myself yet.
(feel free to delete this comment)

**Comment by dr-j** [comment] 2016-01-05 17:02
just remove special flags which say this quest needs to be completed by an external event since the two objectives are a requirednpcorgo and required item.

**Comment by Rushor** [comment] 2016-02-04 09:36
the we need to add a ticket which describes, that killcredits should be redirected to the player if a pet/guardian kills it. fixtry in 2015 was: http://pastebin.com/eWB0pq6w

there was also a pr to this issue, but it was deleted due to the deltion of the 4.x branch, cannot find it anymore

**Comment by Rushor** [comment] 2016-04-12 07:46
issue with missing creditrewards for several sai-actions will be handled/fixed in https://github.com/TrinityCore/TrinityCore/issues/16470

**Closed by Rushor** 2016-04-12 07:46 UTC
Labels: Invalid-CannotReproduce
