### ISSUE TITLE
[Scripts/Onyxia] Onyxia errors in third phase

### ISSUE THREAD

**Issue by MitchesD** [TrinityCore/TrinityCore#11877] opened 2014-04-12 18:44 UTC
Rev.: 870d5d9c45ddf8331f7029072f44f4b1cfa3b54b
TDB 335.53

```
http://s13.postimg.org/k1gpgsqxz/Wo_WScrn_Shot_041114_235342.jpg
```

DBErrors spam:

```
Entry 426151096 not found in `trinity_string` table.
```
##

**Comment by illfated** [comment] 2019-09-11 16:37
Ref. closed issue #23789 .

**Comment by RR2739-VCN** [comment] 2019-10-08 11:27
And the issue again dissapears and becomes dormant. Shame, TC needs to stop closing issues frim 2019 by referencing issues from 2014. I mean wtf is the point? So i reported this issue and TC closed it and referenced this old one. Whats the point? That is why i dont report anymore because Akro closes everything and loves to reference 6 year old open issues.

**Comment by Keader** [comment] 2019-10-08 13:43
@RR2739-VCN because has a open issue about same issue already.
And already has more information in old issue.

**Comment by RR2739-VCN** [comment] 2019-10-08 18:04
I agree merging issues is a great idea. However closing it and saying " hey someone opened the same issue 5 years ago, closed" is not the right way to go about it. I believe merging issues is the right way to go about it.

**Comment by Aokromes** [comment] 2019-10-08 19:51
contributing guidelines states to search before posting new issues writing onyxia shows this same ticket on 1st possition.

**Comment by RR2739-VCN** [comment] 2019-10-09 11:12
Contributing becomes simply tediouswhen you close issues and referencing issues from 5 years ago. You would be correct the issue reported already exists in recent reports but you close issues and referencing 5 years old FORGOTTEN issue sweeping new reports under a rug. Stop closing reports from the community and stop referencing 5 years old issues and do as @Keader said, merge them. Away you approach this is incorrect. Once again, rethink your strategy here abd do what people suggested "merge , dont close"

**Comment by Killyana** [comment] 2020-04-26 20:43
No need for any condition as this traps are listed in the cpp.

**Comment by xvwyh** [comment] 2020-04-27 04:18
Have you tested what would happen if there are any player-spawned gameobjects around Onyxia? They would also get "activated".

**Comment by xvwyh** [comment] 2020-04-27 05:21
The cause of this issue is invalid memory reads. The horrific mess that is SPELL_EFFECT_ACTIVATE_OBJECT creates a temporary object on the stack and passes a reference to it to MapScripts handler, but MapScripts handler can save a pointer to it and execute it *later*. By that time the object on the stack is already destroyed and the pointer dereferences into garbage, which is what's causing these weird error messages about non-existent commands and values.

Fixing this would require getting rid of the horrific mess that is SPELL_EFFECT_ACTIVATE_OBJECT handler and replacing it with, for example, my implementation: https://github.com/TrinityCore/TrinityCore/issues/21078#issuecomment-420115205

That would fix #23789, because MapScripts will no longer be used by Onyxia's spells, and it seems like MapScripts really don't like when they are invoked by GameObjects instead of creatures/players, which is what's causing the error messages in that issue.

It wouldn't, of course, fix the terrible script for eruptions. Instead of relying on traps to do all the work, it's all hardcoded in C++ scripts and it causes excessive server work where a simple spellcast would be enough.

Here's how it's supposed to work (well, rather how I made it work on my server, but I bet it's miles closer to blizzlike script than what TC has right now):

- There are 52 traps (lava fissures) on Onyxia
- Onyxia casts a single spell: `DoCastAOE(SPELL_BELLOWING_ROAR);` (spell 18431). Nothing else is needed. All the rest of the code in boss_onyxia.cpp and instance_onyxias_lair.cpp related to that spell and eruptions can be stripped away.
- Bellowing Roar "distrubs" all lava fissure traps in 13 yards radius around Onyxia.
- Each trap, when disturbed, goes on 10-secs cooldown (this is to prevent it from repeating eternally) and casts its spell - Eruption (17731/69294)
- Eruption does its AoE damage and, in turn, also disturbs all traps (that aren't yet on cooldown) in 13 yards around itself, triggering the next wave of eruptions, and the cycle repeats until all the traps in the arena are on cooldown.

However, there's a problem. If you were to let it work like that, you would notice that all the traps in the entire arena go off at the same time. This is because all these spells are instant cast. All disturbed traps will go off and trigger the next wave, and the next wave will go off and trigger the next, and so on and so on, all within the same world update tick. So we must delay the cast somehow.

Eruption spells don't have a cast time. You could hackishly add cast time, but do GameObject casters even support it? I don't think so, but I may be wrong. Blizzard didn't add a cast time to them, so they must have delayed them in some other way. I don't have an answer for this. It may be possible to add an artificial delay to targets affected by the second effect from a spell script (basically edit `m_UniqueGOTargetInfo[...].TimeDelay`, but it requires messing with some other spell internals (`m_delayMoment` being one of them) for it to work properly), I have no idea how blizzlike it is, but it should work. As for me, I just hacked in a cast time, because on my server GO casting wasn't implemented yet, and the WORLD_TRIGGERs, that were summoned for that task, were perfectly content with having cast times.

**Comment by Faq** [comment] 2020-04-27 05:50
I just love the way you describe everything each time, so detailed. Thank you for sharing all the knowledge.
[#21078 (comment)](https://github.com/TrinityCore/TrinityCore/issues/21078#issuecomment-420115205) 1. done, 3. still in my to do list, will try to open some PR to implement at least some part of it.

**Comment by xvwyh** [comment] 2020-04-27 14:10
I appreciate your efforts, but I have to warn you - porting that thing would be a *considerable* long-term effort. **Many things will break**. Many old scripts that relied on `SPELL_EFFECT_ACTIVATE_OBJECT` to have either default effect or no effect on GOs will have to be reworked.

**Comment by Jildor** [comment] 2020-04-28 08:58
@Killyana isn't better revert this: https://github.com/TrinityCore/TrinityCore/commit/477f1baf9e9d57e3ae29e1631d76d92702083867
and add missing conditions in 25 mode until get the appropriate solution as @xvwyh says?

**Comment by Killyana** [comment] 2020-04-28 15:50
This conditions are not working properly, the amount of errors you will get in the log is insane, also both difficulties are the same, if we add the conditions it will be for both

**Comment by xvwyh** [comment] 2020-04-28 19:27
How will removing targeting conditions solve the errors caused by the spell effect? Removing conditions will only cause the effect to target ALL gameobjects, instead of just lava fissures. If anything, you should be having even more errors now.

Conditions should be there for both difficulties, of course.

**Comment by Killyana** [comment] 2020-04-28 19:43
I pushed the conditions, but I don't think this errors will be fixed before years.

**Comment by Rushor** [comment] 2020-04-29 16:06
the reason is the effect of the spell, why not removing it in spellmgr if it is already handled with core script?

**Comment by illfated** [comment] 2020-04-29 19:02
Sounds reasonable and test-worthy (unless someone knows the answer to your question already).

**Comment by jackpoz** [comment] 2020-05-11 20:00
> The cause of this issue is invalid memory reads.

https://gist.github.com/jackpoz/12792452796257eab486b34b05da2cc0

**Comment by jackpoz** [comment] 2020-07-14 08:37
please test it again on https://github.com/TrinityCore/TrinityCore/commit/203573db83fb1d3f141b5aadbf1d1ca0a637bf94 (or newer version)

**Comment by Aokromes** [comment] 2021-03-30 16:10
no answer after near a year, closing. if this issue is still valid open a NEW ticket with UPDATED core

**Closed by Aokromes** 2021-03-30 16:10 UTC
Labels: Comp-C++Script, Feedback-WaitingResponse, Sub-Instances
