### ISSUE TITLE
Death Knight Entry Level Changes

### ISSUE THREAD

**Issue by NiganNi** [TrinityCore/TrinityCore#25755] opened 2020-12-23 19:42 UTC
**Description:**
The character's initial level has changed. And in the location, the NPC remained unchanged. Unable to complete tasks.

Branch(es):
master

TrinityCore rev. 2a1066839596 2020-12-23 00:13:59 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

OS: Win

**Steps to reproduce the problem:**
1)Create death knight.
2)Reach the kill quest.

**Example:**
![111](https://user-images.githubusercontent.com/61392055/103031816-a5c88380-456f-11eb-9e5e-6d408d23d88a.jpg)

**Comment by illfated** [comment] 2020-12-23 22:00
OK, so I presume you now start with player char level 10, but the surrounding NPCs are level 55 and upwards. Not sure if that needs to change in DB or core handling of dynamic levels. Have to wait and see what the real coders can find out.

**Comment by Aokromes** [comment] 2020-12-23 23:20
classic dk start zone is deprecated on retail. you don't need to do quest chain anymore.

**Comment by illfated** [comment] 2020-12-24 02:46
> classic dk start zone is deprecated on retail. you don't need to do quest chain anymore.

I don't know how it works to start a DK for the first time on retail now, but I would think that goes against the norm to let new players learn their character skills in a step-by-step fashion.

**Comment by Fabi** [comment] 2020-12-24 03:50
> classic dk start zone is deprecated on retail. you don't need to do quest chain anymore.

That's wrong. Non allied races/panda are still in their old starting area. Only the new DKs that came with SL are in the new 'zone'.

**Comment by offl** [comment] 2021-09-06 01:38
Duplicate of #26673 / #26845

**Closed by offl** 2021-09-06 01:38 UTC
Labels: Branch-master
