### ISSUE TITLE
[3.3.5][6.x][Instance] Sindragosa Ice Tomb Damage

### ISSUE THREAD

**Issue by Butterfly69** [TrinityCore/TrinityCore#7808] opened 2012-09-18 13:39 UTC
Hi
In the boss Sindragosa there is a another problem with ice tomb

- What should happen ? (from wowwiki.com) : Since Ice Tombs not only damage their targets, but also everyone else in a 10 yard radius, it's important for the ice tomb targets to move away from all non-targets and from each other

- Whats happen now: it just damage freezed players,not who is in a 10 yard radius.

Rev: 3c42401
Source: http://www.wowwiki.com/Sindragosa_(tactics)
Thanks in advance.

**Comment by D4R4** [comment] 2015-03-07 06:41
As of today's update this issue still persists,
my first conclusion was LoS problems but the spell has SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS flag so I have no clue why it is not working as it should,,

**Comment by demooo** [comment] 2015-03-09 21:54
use this script :
http://codepad.org/62P5oYPq

**Comment by DeActiveDev** [comment] 2015-03-09 22:03
use this script :
http://codepad.org/62P5oYPq#output
and u must some change in object.cpp
u test now script and after object.cpp and must some change update sql

**Comment by D4R4** [comment] 2015-03-10 05:59
Wut

**Comment by Demonid** [comment] 2015-03-10 06:41
@D4R4 Confirmed.

**Comment by P-Kito** [comment] 2015-09-19 03:20
I am stuck on this, tried everything. 

Targets which were marked by sindragosa will get the damage and targets near them.
But not target that were also marked. (They should get damage for their own ice tomb "explosion" and the one near them)

**Comment by Rushor** [comment] 2016-02-01 19:08
@DeActiveDev: create a plaindiff for your changes from http://codepad.org/62P5oYPq#output in order to get a better overview what was actually fixed by you

**Comment by P-Kito** [comment] 2016-02-02 01:12
I have got that fixed, just cant remember coz its long time back when I fixed it xD

**Comment by tkrokli** [comment] 2016-02-02 01:19
@P-Kito : there are plenty of diff sites you can use to compare the TC file(s) to your file(s).
I would think that could help you find those changes, unless you have changed too much.

**Comment by dixanackmad** [comment] 2016-02-03 08:42
This bug is confirmed on b1d0855624d1c83850fc36f5242437d7f7c1336b

**Comment by DDuarte** [comment] 2016-03-28 00:30
> A bounty has just been posted on a project you follow, TrinityCore/TrinityCore: $15 on [3.3.5][6.x][Instance] Sindragosa Ice Tomb Damage by Yehonal.

> The bounty will be awarded to the developer who successfully closes out this issue.

> You can view the issue and increase the bounty at https://www.bountysource.com/issues/63965-3-3-5-6-x-instance-sindragosa-ice-tomb-damage

**Comment by P-Kito** [comment] 2016-03-28 17:59
There you go. :) Keader is testing it right now.

**Comment by Keader** [comment] 2016-03-28 18:06
P-Kito Fix is working :+1:

**Comment by P-Kito** [comment] 2016-03-30 21:58
Can the issue creator confirm that my fix works, so I can claim the bounty?

**Comment by djbeauchamp** [comment] 2016-05-04 13:31
Can we mark this as resolved?

**Comment by DDuarte** [comment] 2016-05-04 13:37
I guess it's resolved once #16863 gets merged

**Closed** 2016-05-04 15:19 UTC
Labels: bounty, Branch-3.3.5a, Branch-6.x, Comp-C++Script, Sub-Instances, Sub-Spells

**Comment by tkrokli** [comment] 2016-05-05 12:05
@P-Kito : since @Yehonal is the user who posted the bounty, https://www.bountysource.com/issues/63965-3-3-5-6-x-instance-sindragosa-ice-tomb-damage/backers a confirmation from him should be OK.

**Comment by Yehonal** [comment] 2016-05-05 12:15
I cannot test it in these days..however i trust in @DDuarte , no problem for me

**Comment by P-Kito** [comment] 2016-07-06 08:12
If g.ronca@hyperweb2.com is your current email, I dropped you a mail.

**Comment by Yehonal** [comment] 2016-07-25 15:42
@P-Kito sorry for long delay

You can retrieve the bounty ofc
