### ISSUE TITLE
[3.3.5] Boss encounters against walls

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23613] opened 2019-07-20 10:26 UTC
**Description:**
In a normal boss encounter, if the target of the boss is too close to certain walls (not all of them), the boss will stop, evade everything and his life will regenerate.

I am not talking about weird places or spots where a player would try to cheat and it will be obvious if the boss resets, I am talking about being just against a wall.

Looks like CanNotReachTarget is true even when there are normal places for a player.
You can see this issue in a lot of bosses, you just need to find which wall will do the trick.
This is a big problem when some raids like to fight bosses against walls (to save space or because it is a tactic), and you can not say 'well, do not go too close to the walls' because the player could be pushed against a wall because of NPC's spells.
If someone ever heard about Halls of Reflection's waves going back to 0 during the encounter, this is the reason too.

**Steps to reproduce the problem:**
1. go c id 36678
2. inst setboss 0 3 (up to 5)
3. Use this spot during the fight or .damage 1 Professor Putricide from here: .go xyz 4404.6938 3224.091 389.4179

If anyone can not reproduce this issue, I can show it in the tc test realm or upload a video.

**Branch(es):** 3.3.5
**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/28b8c369bb75d0a73c61e3a7e1694f989ca20cb7
**Operating system:** Ubuntu? (The one that the tc test realm uses)

**Comment by jackpoz** [comment] 2019-07-20 10:46
We could reduce the distance from walls in mmaps to allow creatures get closer to walls

**Comment by Keader** [comment] 2019-07-20 12:03
Not caused by Boundary?

**Comment by OcelotGear** [comment] 2019-07-27 22:33
![WoWScrnShot_072719_192444](https://user-images.githubusercontent.com/49760010/62000068-4843b500-b0a5-11e9-8ace-3ac3ba8b2eda.jpg)
If you LOS him with the columns of festergur or rotface occurs the same.

**Comment by Aokromes** [comment] 2019-08-17 10:03
https://dl.dropboxusercontent.com/s/lmmtrojt2n59f7f/2019-08-17_12-01-56.mp4

**Comment by jackpoz** [comment] 2019-08-17 11:06
I would just revert whatever new evade "fix" is causing this, or put it in a conf variable disabled by default

**Comment by jackpoz** [comment] 2019-08-18 09:08
Issue added in https://github.com/TrinityCore/TrinityCore/commit/c602220e02bed1ad76c9e60064eeec5fd97bfe80#diff-61dd1cb015dd02635cca299472b41422R824

**Comment by jackpoz** [comment] 2019-08-18 09:08
Fixed in https://github.com/TrinityCore/TrinityCore/commit/5a980226497605b18f1855fa39f340c10ee9dd53

**Closed by jackpoz** 2019-08-18 09:08 UTC
Labels: Branch-3.3.5a, Priority-High
