### ISSUE TITLE
[6.x] Localization scripting

### ISSUE THREAD

**Issue by ElleEntertainment** [TrinityCore/TrinityCore#14575] opened 2015-04-19 08:04 UTC
![codice](https://cloud.githubusercontent.com/assets/10599040/7218661/20fb841c-e67b-11e4-92c5-75cd16ad07f4.png)
![heidisql](https://cloud.githubusercontent.com/assets/10599040/7218662/2544887a-e67b-11e4-959c-01f3d150fe32.PNG)
![game](https://cloud.githubusercontent.com/assets/10599040/7218663/28411516-e67b-11e4-963c-eab3d3365e60.PNG)

as you can see i converted LoadCreatureLocales() to the new format, i inserted a value in locales_creature and then i tested in game, but the name of the npc is still taken from creature_template..
What have i missed?
##

**Comment by Aokromes** [comment] 2015-04-19 08:38
If you wanna get help with code, share the code on that way it can be reviewed and merged, if you don't have plans to share the code, this question don't belongs here.

**Comment by VirusEntertainment** [comment] 2015-04-19 10:40
https://github.com/gegge6265/TrinityCore/commit/5625d963601ef2633e8900a3acc616316aadada9

here :)

**Comment by Aokromes** [comment] 2016-01-18 02:06
@Vincent-Michael this is still needed?

**Comment by Rushor** [comment] 2016-02-02 07:52
@VirusEntertainment: open up a pr for these changes.

**Comment by Aokromes** [comment] 2016-06-15 05:47
@Vincent-Michael this is still needed?

**Comment by Killyana** [comment] 2016-06-15 19:33
Same issue with  (creature, creature_text, gameobject, gossip_menu_option, achievement_reward).

**Comment by tkrokli** [comment] 2016-09-01 14:54
@ElleEntertainment : Are you still interested in following up on this issue?

**Comment by Druson** [comment] 2016-09-02 17:18
I have fixed this case #17884  by myself.  Seems the cause is that there is no BroadcastTextLocale.db2 file named extracted so it is not implemented. I amend some code and it works now.

**Comment by DDuarte** [comment] 2016-09-02 17:25
@Druson: perhaps you can create a patch?

**Comment by Druson** [comment] 2016-09-02 17:28
@DDuarte  I just attached the code here.

**Comment by tkrokli** [comment] 2016-09-02 21:29
The .zip file contains 3 .cpp files and 2 .h files, which means that TC expects a Pull Request for that change.
Fork the TrinityCore repository and apply the changes to your local TC repository (in a new branch), then open a Pull Request to the main TrinityCore repository.

**Comment by Aokromes** [comment] 2017-12-17 18:57
there is no locales_* anymore.

**Closed by Aokromes** 2017-12-17 18:57 UTC
Labels: Branch-master, Comp-Core, Sub-ScriptingEngine
