### ISSUE TITLE
Core/Player average Item level shows 0

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#26126] opened 2021-02-22 16:37 UTC
**Description:**

The average Item Level in Characterinfo shows everytime 0.

**Expected behaviour:**

If you equip Items with an Itemlevel, the Characterinfo should show you the average Item Level of your Items.

**Steps to reproduce the problem:**

1. create a Character
2. equip some Items with Item Level
3. Take a look at your Characterinfo

**Branch(es):**

master

**TC rev. hash/commit:** 

01a3be276f4076762290e985d10d5c4ab1176ce0

**Operating system:** 

Win10

**Comment by MaxtorCoder** [comment] 2021-02-22 17:37
Duplicate of #25721

**Closed** 2021-02-22 17:43 UTC
Labels: Branch-master
