### ISSUE TITLE
Ebon plague stack

### ISSUE THREAD

**Issue by siley** [TrinityCore/TrinityCore#12314] opened 2014-06-19 14:39 UTC
Hi

Ebon plague stack 30% bonus for disease.
stack every 30% from actual dmg.   dmg_1,3= new dmg_1,3 = new dmg*1,3....

I think is spell 65142 (no name, no info on wowhead). Its aply with ebon plague and when I do unaura 65142 dmg for disease lost.

rev: https://github.com/TrinityCore/TrinityCore/commit/232eaae69cd774fb2ce4014c61c77d6a5c685b01
##

**Comment by Killyana** [comment] 2019-03-08 13:52
This issue is still valid?

**Comment by Jildor** [comment] 2019-07-10 17:46
I think the main issue isn't valid (only partly), but the fix: https://github.com/TrinityCore/TrinityCore/pull/13334
I thik isn't correctly, because Crypt Fever/ Ebon Plaguebringer talent part (increases disease damage) should be only for the owner diseases (the DK).
Actually Crypt Fever/ Ebon Plaguebringer apply on target 65142 aura (can't stack for different casters) and this aura apply auraeffect:
```Aura Id 255 (SPELL_AURA_MOD_MECHANIC_DAMAGE_TAKEN_PERCENT)```
And this effect incrase the damage for all spells with this mechanic without matter who is the caster, so another DKs with our diseases or priest with devouring plague increases the damage without the talent Crypt Fever or Ebon Plaguebringer.

So, I think, aura 65142 should stack with diff casters, but, only should increase the damage of owner diseases.

**Comment by Jildor** [comment] 2019-07-11 10:25
I see a few logs and I can confirm Crypt Fever and Ebon Plague increase diseases damage effect should increase the diseases of anothers players:
http://www.worldoflogs.com/reports/iy9e50worxwzuvsv/xe/?s=14240&e=14814&x=spell+%3D+%22Ebon+Plague%22+or+spell+%3D+%22Frost+Fever%22+or+spell+%3D+%22Blood+Plague%22+or+spell+%3D+%22Devouring+Plague%22+&page=1

Maybe blizzard change this mechanic during wotlk, but in last wotlk time seems works like here.
Seems blizzard is more crazy than @Keader 😄 
So, I don't see any reason to keep open this issue (@Aokromes closing issue in 3, 2.... 😄 )

**Closed** 2019-07-11 10:27 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Spells
