### ISSUE TITLE
[CRASH] Group::GetInvited (Multithreading issue?)

### ISSUE THREAD

**Issue by Maiievs** [TrinityCore/TrinityCore#21505] opened 2018-02-26 21:25 UTC
**Description:**
Crash due to possible iterator invalidation in Group::GetInvited.
Apparently it was already reported here some time ago, in #15071, seems very rare tho, only saw it 1 time.
I do have custom changes, but nothing huge, none that could possible cause that.

**CrashLog:** 
[gdblog2018-02-26-10-04-34.txt](https://github.com/TrinityCore/TrinityCore/files/1760318/gdblog2018-02-26-10-04-34.txt)

**Steps to reproduce the problem:**
Unknown.
I use MapUpdate.Threads = 3

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 425b181544a21d2246fdf0261ba76a37e2510883

**Comment by tkrokli** [comment] 2018-02-26 21:56
Your core is quite old, from 8 weeks ago. We recommend that you update your core to a more recent one. There has been more than one crash fix since that time (even if they were not specific to your issue).

**Comment by Rochet2** [comment] 2018-02-26 23:50
In both cases accessing m_invitees crashes in one way or another.
In the other issue I proposed this kind of attempt to try to find out what is wrong, maybe you could try it - at least if no better suggestions come by?
```c++
#include <thread>

static auto main_thread = std::this_thread::get_id();
ASSERT(std::this_thread::get_id() == main_thread);
```
This should be added to `Group::RemoveAllInvites`, `Group::RemoveInvite`, `Group::AddInvite` in `Group.cpp` with the include at the top of the file.
It would crash (assert fails) when a situation that would cause a multithreading error eventually occurs with the functions accessing m_invitees.

**Comment by tkrokli** [comment] 2018-02-27 07:11
@Maiievs : Please try what Rochet2 suggests, it would help us find relevant info.

**Comment by jackpoz** [comment] 2018-02-27 08:52
@Maiievs could you please push your custom changes to a public fork and include a link to that in the issue description ? Lines don't match between the crashlog and the TC sources.

**Comment by Maiievs** [comment] 2018-03-01 00:55
@Rochet2 Got the crash with your suggestion.
Repro steps:
.tele wintergrasp
.bf start 1
Accept the group invite
Leave the area, by flying to Dragonblight (for instance)

[gdblog2018-02-28-18-42-44.log](https://github.com/TrinityCore/TrinityCore/files/1769283/gdblog2018-02-28-18-42-44.log)

**Comment by Rochet2** [comment] 2018-03-01 03:38
Hmm, did not expect there to be such exceptions...
Should exclude all maps that are BG or BF:
`ASSERT(isBFGroup() || isBGGroup() || std::this_thread::get_id() == main_thread);`
The BG/BF code can be unsafe if any other map can call any of the group methods related to invitees. (the already mentioned functions + `Group::GetInvited` and `Group::GetInviteeCount`)

Do your custom changes have anything to do with: kick, ban, login, logout, groups, raids, battlefields, battlegrounds, deleting an account, deleting a character .. or similar? If yes, what kind of activity is it?
I tried looking through the functions and nothing looks suspicious (apart from the BG functions).
My guesses are that its either custom code, the BG/BF code, something doesn't call leave group on logout etc or not related to the invitees (something else is messing this up).
Btw. the config says wintergrasp is not finished and shouldn't be used.

Other than just to keep looking, one thing that could be done is to change the pointers to GUIDs. I cant see any real reason to use the pointers (except that it may be slightly faster than fetching the player).

**Comment by Shauren** [comment] 2018-03-01 08:11
Its possible that bgs and bfs are the cause of this crash in the first place

**Comment by jackpoz** [comment] 2018-03-01 08:20
> .tele wintergrasp
> .bf start 1

that's usually a source of crashes

**Comment by jackpoz** [comment] 2018-03-01 08:20
> I do have custom changes, but nothing huge, none that could possible cause that.

still waiting for the custom changes

**Comment by tkrokli** [comment] 2018-03-01 14:23
Will the label [Invalid-Intended/WontFix/Blizzlike] be correct for this issue, because it may be the result of ignoring warnings in the source code?

**Comment by irgc** [comment] 2018-03-04 20:04
Confirm

**Comment by tkrokli** [comment] 2018-03-04 20:47
confirmation without core rev. hash is less than useful.

**Comment by jackpoz** [comment] 2018-12-01 18:48
@Maiievs did this issue happen anymore ?

**Comment by Aokromes** [comment] 2019-04-01 13:15
no answer after 5 months, closing, if this bug is still valid open a new ticket with one updated core and gdb script.

**Closed by Aokromes** 2019-04-01 13:15 UTC
Labels: Branch-3.3.5a, HasBacktrace
