### ISSUE TITLE
Recruit a Friend summon bug

### ISSUE THREAD

**Issue by starrheld** [TrinityCore/TrinityCore#18705] opened 2017-01-01 14:39 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Description: Can't summon friend if too far away

Current behaviour: When you try to summon someone that is too far away, it says invalid target, when you log off and on the "Summon Friend"

Expected behaviour: Summon should work regardless of class/race and distance

Steps to reproduce the problem: Create two characters etc: two orcs, it works if you stand on top of each other, walk away to Orgrimmar or even Razor Hill and it doens't work and says "invalid target" log off and invite your friend again... and the "Summon Friend" from the target interface is gone.

1. http://imgur.com/a/xdjy5
2. http://imgur.com/a/xdjy5
3. http://imgur.com/a/xdjy5

Branch(es): 3.3.5

TC rev. hash/commit: 96f7ce4

TDB version: 3.3.5.62

Operating system: Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment] 2017-01-01 14:41
duplicate of https://github.com/TrinityCore/TrinityCore/issues/7395

**Closed** 2017-01-01 14:42 UTC
