### ISSUE TITLE
[3.3.5][Priest] Core/Spell: Spirit of Redemption

### ISSUE THREAD

**Issue by Weley** [TrinityCore/TrinityCore#4099] opened 2011-11-27 10:50 UTC
If priest die and have talent Spirit of Redemption (http://old.wowhead.com/spell=27827) , he turn in angell form and should be imune to all damage (melee, spell, environmental damage), but it doesnt works. Priest after death sometimes have hight aggro and creatures can attack him, so priest loss item durability.

rev. - 414987541cb7

(Sorry for my bad english)

**Comment by Rushor** [comment] 2016-01-05 21:22
update

```c++
class spell_pri_spirit_of_redemption_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_pri_spirit_of_redemption_SpellScript);

            void HandleAfterCast()
            {
                if (Unit* caster = GetCaster())
                {
                    caster->SetHealth(caster->GetMaxHealth());
                    caster->AddAura(PRIEST_SPIRIT_OF_REDEMPTION, caster);
                }
            }

            void Register()
            {
                AfterCast += SpellCastFn(spell_pri_spirit_of_redemption_SpellScript::HandleAfterCast);
            }
        };

SpellScript* GetSpellScript() const override
        {
            return new spell_pri_spirit_of_redemption_SpellScript();
        }
```

**Comment by Rushor** [comment] 2016-01-05 21:29
the whole script

```c++
// - 27827 Spirit of Redemption
class spell_pri_spirit_of_redemption : public SpellScriptLoader
{
    public:
        spell_pri_spirit_of_redemption() : SpellScriptLoader("spell_pri_spirit_of_redemption") { }

        class spell_pri_spirit_of_redemption_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_pri_spirit_of_redemption_AuraScript);

            void HandleOnEffectRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
            {
                if (Unit* target = GetTarget())
                    target->RemoveAura(PRIEST_SPIRIT_OF_REDEMPTION);
            }

            void Register()
            {
                OnEffectRemove += AuraEffectRemoveFn(spell_pri_spirit_of_redemption_AuraScript::HandleOnEffectRemove, EFFECT_2, SPELL_AURA_MOD_SHAPESHIFT, AURA_EFFECT_HANDLE_REAL);
            }
        };

        class spell_pri_spirit_of_redemption_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_pri_spirit_of_redemption_SpellScript);

            void HandleAfterCast()
            {
                if (Unit* caster = GetCaster())
                {
                    caster->SetHealth(caster->GetMaxHealth());
                    caster->AddAura(PRIEST_SPIRIT_OF_REDEMPTION, caster);
                }
            }

            void Register()
            {
                AfterCast += SpellCastFn(spell_pri_spirit_of_redemption_SpellScript::HandleAfterCast);
            }
        };

        AuraScript* GetAuraScript() const override
        {
            return new spell_pri_spirit_of_redemption_AuraScript();
        }

        SpellScript* GetSpellScript() const override
        {
            return new spell_pri_spirit_of_redemption_SpellScript();
        }
};
```

not tested yet

**Comment by Keader** [comment] 2016-01-06 00:32
@Rushor work for me
Tested on Slime Puddle (Professor Putricide) and Defile (Lich King)
These boss always takes place in Holy Priest killed in the area, the buff be 'renewed' and pieces of armor all break

Tested with:

INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('27827', 'spell_pri_spirit_of_redemption');

```diff

diff --git a/src/server/scripts/Spells/spell_priest.cpp b/src/server/scripts/Spells/spell_priest.cpp
index b5c3b26..1b53cb2 100644
--- a/src/server/scripts/Spells/spell_priest.cpp
+++ b/src/server/scripts/Spells/spell_priest.cpp
@@ -45,6 +45,7 @@ enum PriestSpells
     SPELL_PRIEST_SHADOW_WORD_DEATH                  = 32409,
     SPELL_PRIEST_T9_HEALING_2P                      = 67201,
     SPELL_PRIEST_VAMPIRIC_TOUCH_DISPEL              = 64085,
+    PRIEST_SPIRIT_OF_REDEMPTION                     = 62371,
 };
 
 enum PriestSpellIcons
@@ -867,6 +868,58 @@ class spell_pri_vampiric_touch : public SpellScriptLoader
         }
 };
 
+// - 27827 Spirit of Redemption
+class spell_pri_spirit_of_redemption : public SpellScriptLoader
+{
+public:
+    spell_pri_spirit_of_redemption() : SpellScriptLoader("spell_pri_spirit_of_redemption") { }
+
+    class spell_pri_spirit_of_redemption_AuraScript : public AuraScript
+    {
+        PrepareAuraScript(spell_pri_spirit_of_redemption_AuraScript);
+
+        void HandleOnEffectRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
+        {
+            if (Unit* target = GetTarget())
+                target->RemoveAura(PRIEST_SPIRIT_OF_REDEMPTION);
+        }
+
+        void Register()
+        {
+            OnEffectRemove += AuraEffectRemoveFn(spell_pri_spirit_of_redemption_AuraScript::HandleOnEffectRemove, EFFECT_2, SPELL_AURA_MOD_SHAPESHIFT, AURA_EFFECT_HANDLE_REAL);
+        }
+    };
+
+    class spell_pri_spirit_of_redemption_SpellScript : public SpellScript
+    {
+        PrepareSpellScript(spell_pri_spirit_of_redemption_SpellScript);
+
+        void HandleAfterCast()
+        {
+            if (Unit* caster = GetCaster())
+            {
+                caster->SetHealth(caster->GetMaxHealth());
+                caster->AddAura(PRIEST_SPIRIT_OF_REDEMPTION, caster);
+            }
+        }
+
+        void Register()
+        {
+            AfterCast += SpellCastFn(spell_pri_spirit_of_redemption_SpellScript::HandleAfterCast);
+        }
+    };
+
+    AuraScript* GetAuraScript() const override
+    {
+        return new spell_pri_spirit_of_redemption_AuraScript();
+    }
+
+    SpellScript* GetSpellScript() const override
+    {
+        return new spell_pri_spirit_of_redemption_SpellScript();
+    }
+};
+
 void AddSC_priest_spell_scripts()
 {
     new spell_pri_circle_of_healing();
@@ -887,4 +940,5 @@ void AddSC_priest_spell_scripts()
     new spell_pri_renew();
     new spell_pri_shadow_word_death();
     new spell_pri_vampiric_touch();
+    new spell_pri_spirit_of_redemption();
 }
```

Did I correct?

**Comment by sirikfoll** [comment] 2016-01-06 01:28
Isn't a spell_linked_spell enough?
```sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger`=27792;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
(27792,62371,2,'Spirit of Redemption trigger Spirit of Redemption(Imunity)');

**Comment by tkrokli** [comment] 2016-01-06 11:05
Very good point, @sirikfoll. If it can be done with linking spells that are meant to be linked, it would be a simple and also better solution, given that your suggestion is tested and that it works as expected. :)

**Comment by Keader** [comment] 2016-01-06 11:12
Yeah, @sirikfoll  fix work for me too

**Comment by Rushor** [comment] 2016-01-06 11:30
and the aura is also removed if 27792 fades away?

for me spell_linked_spell for classfixes is a hack, dunno what other people say to it :D

**Comment by Keader** [comment] 2016-01-06 11:34
Hey @Rushor Rushor, On:

```cpp

 void HandleOnEffectRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
 {
          if (Unit* target = GetTarget())
              target->RemoveAura(PRIEST_SPIRIT_OF_REDEMPTION);
}

```
```cpp
target->RemoveAura(PRIEST_SPIRIT_OF_REDEMPTION);
```

Not shold be?!

```cpp
target->RemoveAurasDueToSpell(PRIEST_SPIRIT_OF_REDEMPTION);
```

**Comment by Aokromes** [comment] 2016-05-26 01:38
If anything here is valid, plz create a PR.

**Comment by Keader** [comment] 2016-10-24 13:09
Both fixs works, idk how is more clean.

**Comment by Keader** [comment] 2016-11-28 01:21
can be closed, i cant reproduce in current revs anymore
tested with professor putricide.

**Comment by tkrokli** [comment] 2016-11-29 00:25
Closing this issue based on @Keader's suggestion. If you find that this issue happens in current source, please open a new ticket with documentation based on current & up to date TC source.

**Closed by tkrokli** 2016-11-29 00:25 UTC
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Spells
