### ISSUE TITLE
Core/Db Flesh Eating Worm

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27608] opened 2022-01-13 13:30 UTC
### Description

https://www.wowhead.com/npc=2462/flesh-eating-worm

Sai error: the creature is dead after refresh and cannot be killed

### Expected behaviour

Fix Sai or unit_ flag

### Steps to reproduce the problem

1.npc add temp 2462
2.gm off

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/fde8619dacf50159e5b94f2c00d56755b7e6c36a

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by offl** [comment] 2022-01-13 13:52
Duplicate of #25612

**Closed by offl** 2022-01-13 13:52 UTC
Labels: Branch-3.3.5a
