### ISSUE TITLE
[Bug]Plague Walkers and The Aura of Lost Hope

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#8675] opened 2012-12-15 14:09 UTC
Bug:
The Aura of Lost Hope has a few bugs which at the start of the instance of Ahn'Kahet The Old Kingdom may be really deal braking. It is used by the Plague Walkers.

1 - Aura of Lost Hope has an enormous range of applying Aura of Lost Hope debuff to another player which pulls the mob using it and every mob near him to the player who got the debuff, That range is approximately 100 yards.

2 - When the Plague Walker is put into combat and then out of it, the aura disappears from his buff list. So if a player gets applied by the debuff in stealth mode, the aura will disappear from the Plague Walker immediatly since stealthed players will not be put in combat, if the player who got the debuff leaves the instance along with his party and then reenters, the aura will be removed from the Plague Walker as well and the same will happen if the party dies.

3 - For some reason half of the Plague Walkers in the instance have Aura of Lost Hope and the others Contagion of Rot. I think all of them should have both of these spells.

4 - Not really sure if this is a bug or not, but the stacks from Aura of Lost Hope are not constant, they happen randomly, not at a predetermined timer so the debuff on players may actually disappear before the next stack has been applied.
Links:

Links:
Plague Walker - http://www.wowhead.com/npc=30283
Aura of Lost Hope - http://www.wowhead.com/search?q=Aura+of+Lost+Hope
Contagion of Rot - http://www.wowhead.com/spell=56707

**Comment by ikir83** [comment] 2016-06-26 22:19
Never fixed? This still happens making the dungeon unplayable

**Comment by AciDCooL** [comment] 2016-07-10 01:12
I can confirm some of this behavior on heroic.To add on to this bug the instance on heroic has multiple issues. I think this entire instance needs to be looked after. (running latest to date Tcore)


First off the range is not the issue, this seems to be fine. But the Plague Walkers cast their aura debuff while not in combat. just by walking into the room everyone gets the aura debuff while being out of combat.

Maybe this is not the right bugreport to add all of this but we had the problem at the start of the dungeon there are creeps linked which should not be. attacking the first few spiders a pack from the third rooms comes charging toward the entrance area. Had a plague walker involved but dont think this is related.

After those two debacles we engaged Prince Taldaram. apparently he spawns 3 orbs which did dmg in the thousands instead a few honderd. Which would be much of a problem but the orbs stayed inside of the combat area and they should have gone far far away. This wiped us 5times after I could only use .die to get on with the instance.

The moral was on all time low after these many bugs so we wanted to try the optional boss Amanitar. Apparently he keeps spawning so many mushroom clouds that some wow clients almost froze. Although this was the highlight of my night but it was not for the rest of my party :). [Pic for reference](http://i68.tinypic.com/s15d3p.png)
Well after a few good wipes on this one it became clear it is just not possible to complete this one.

Jedoga Shadowseeker was a blast. The only comment here was that she moved from her spot for some wierd reason while a disciple was walking towards her. But it was to our benefit since she walked the other way. All other Mechanics worked nothing to add here.

Then came Herald Volazj which is mentioned in some other post in this tracker and just as wel in normal and in heroic I can confirm both are not working as intended. All "clones" spawn at the bosses feet, that may not be pretty although functional. They all come at you at the same time and hit you at the same time for immense amount of damage. Only myself as tank could survive this initial damage, then I had to fend of 4 more waves since the entire party died from them. Seemed that the phases weren't linked for some reason but I cant confirm it since everyone was dead anyway.


Think there should be some easy\good fixes for these issues

1. the mobs at the entrance need to be looked at, I have no clue how to check which ones are wrongfully linked (this didn't happen on normal as I recall).

2. Then the aura of the plague dudes should only be active whilst in combat with them.

3. Amanitar really needs a good looking after, think his mushroom clouds are being cast way too often of the amount of the cast is too much.

4. Heralds clones need massive nerfing.



\\Better rename this bug to The old kingdom, bugs and issues.

**Comment by tkrokli** [comment] 2016-07-10 21:38
I disagree with your suggestion to rename this issue. Better keep issues separated so they can be fixed separately too.Entering multiple bugs into one issue page keeps it open forever because only some of the bugs will be fixed, not all (and some bugs might even reappear during future changes).

**Comment by Aokromes** [comment] 2016-07-10 21:54
Tracker rule are: 1 issue / ticket, minus when they are generic bugs.

**Comment by SnapperRy** [comment] 2016-10-26 20:23
Aura of Lost Hope should only be active when entering combat, as seen [here](https://youtu.be/RUdzXxdRGFI?t=228).

Contagion of Rot seems to be a heroic-only ability.

**Closed** 2016-10-26 20:45 UTC
Labels: Sub-Spells
