### ISSUE TITLE
[3.3.5] Core/Battleground: Bgs Buffs Do not Work / Spell Trap GameObject

### ISSUE THREAD

**Issue by vhipercode** [TrinityCore/TrinityCore#22292] opened 2018-08-20 03:41 UTC
**Description:**
Batllegrounds FOOD / REGEN & BERSERK are not being added to players as they pass by them.

**Current behavior:**
Inside the BGS When the player passes over the object that has the buffs Food or Berserk the spell is not being added and the object disappears see the video that will demonstrate exactly how it happens.

https://www.youtube.com/watch?v=K_kroXeYV00&feature=youtu.be

**Expected behavior:**
When going over the Food / Regen and Berserk gob the spell should be added.

Steps to reproduce the problem:

I added in 
TrinityCore/src/server/game/Entities/GameObject/GameObject.cpp

else if (Unit* target = ObjectAccessor::GetUnit(*this, m_lootStateUnitGUID))
{
    // Some traps do not have a spell but should be triggered
    CastSpellExtraArgs args;
    args.SetOriginalCaster(GetOwnerGUID());
    if (goInfo->trap.spellId)
        CastSpell(target, goInfo->trap.spellId, args);

   **if (goInfo->trap.spellId)
        target->AddAura(goInfo->trap.spellId, target);**

after I add I tried again to get the buffs and it worked. but the Trap [Freezing Trap] is set to 20 seconds when the trap is triggered every 20 seconds. When the correct one should start in 9 seconds.

The error can happen because the Berserk spell of the Battleground is recognized only as *AddAura* and not as CastSpell in objects.

Branch (s):

3.3.5

TC rev. hash / commit:

https://github.com/TrinityCore/TrinityCore/commit/a8dd266704acf630102eae473b8822a8de9a7795

**Operational system:**

Windows Server 2008 R2

**Comment by Killyana** [comment] 2018-08-20 12:32
Duplicate of #21615

**Closed by Killyana** 2018-08-20 12:32 UTC
