### ISSUE TITLE
Pet AOE can hit friendly creatures 

### ISSUE THREAD

**Issue by mogudy** [TrinityCore/TrinityCore#11132] opened 2013-10-27 10:03 UTC
Core revision: 0177d1c4d4267836c55c0294aa359e131a5680fd + ahbot
DB version:    3.3.5.52

when you break netherweb victim, normally u expect for sha'tar warriors. If any mobs coming out as well, and ur pet hit them using thunderstorm or swipe, u can see that the friendly Sha'tar warrior start attacking ur pet.

**Comment by Killyana** [comment] 2015-04-14 18:55
Cannot reproduce, maybe fixed by the last factions update

**Closed by Killyana** 2015-04-14 18:55 UTC
Labels: Comp-Core
