### ISSUE TITLE
[3.3.5] - Boss Sindragora bug Freez

### ISSUE THREAD

**Issue by oelsaid** [TrinityCore/TrinityCore#14602] opened 2015-04-24 19:59 UTC
TrinityCore rev. 3761d2411968+ 2015-02-20 22:44:04 +0100 (3.3.5 branch) (Win64, Release)
TDB 335.57 + Updates
Linux ubuntu

Bug: the ice of sindragora not this giving to break!
http://prntscr.com/6xqc3d
Bug: o gelo da sindragora não esta dando para quebrar!

**Comment by Rushor** [comment] 2015-04-24 21:06
what? google translater is a bad idea ^^

https://github.com/TrinityCore/TrinityCore/issues/6541

**Comment by Nyeriah** [comment] 2015-04-24 21:10
Yes, it's a duplicate of that bug

**Closed by Nyeriah** 2015-04-24 21:10 UTC

**Comment by oelsaid** [comment] 2015-04-24 22:31
sorry, google translate. bug confirmed ?

**Comment by Nyeriah** [comment] 2015-04-24 22:36
Yes, there's already a report for this issue.
Sim, já existe um ticket sobre este problema.

**Comment by oelsaid** [comment] 2015-04-25 00:08
Obrigado caso eu queira retirar a skill do boss é possivel pois preciso de urgencia

**Comment by Nyeriah** [comment] 2015-04-25 00:15
Yes, but if you need help with it you'll need to use our forums.
Sim, mas se precisas de ajuda com isso terás que usar o forum.

http://www.trinitycore.org/f/
