### ISSUE TITLE
[Crash] warlock spell eye of kilrogg carsh

### ISSUE THREAD

**Issue by zcbw761** [TrinityCore/TrinityCore#27249] opened 2021-11-04 07:29 UTC
### Description

cast spell [eye of kilrogg] https://www.wowhead.com/spell=126/eye-of-kilrogg  server crash 

### Expected behaviour

not crash

### Steps to reproduce the problem

cast spell eye of kilrogg

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/a54c51c362426613be658e4a471b8fc866e82d57

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by zcbw761** [comment] 2021-11-04 07:30
[Crashes.zip](https://github.com/TrinityCore/TrinityCore/files/7472988/Crashes.zip)

**Comment by MaxtorCoder** [comment] 2021-11-04 07:33
Duplicate of #27168

**Closed** 2021-11-04 10:09 UTC
Labels: Branch-master
