### ISSUE TITLE
Assertion crash in Unit destructor

### ISSUE THREAD

**Issue by silviu20092** [TrinityCore/TrinityCore#26325] opened 2021-03-27 18:01 UTC
**Description:**

Assertion crash in Unit destructor.
https://gist.github.com/silviu20092/8d98e52f2a8be380f5c83aa99790c96f

**Steps to reproduce the problem:**

Seems to be random and pretty rare, I don't know the exact steps to reproduce it.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/80f30d5ca94f000962a06e398567aa0b1ddd706b

**Operating system:** 

Debian 10

**Comment by jackpoz** [comment] 2021-03-27 18:02
do you have any custom change ?

**Comment by silviu20092** [comment] 2021-03-27 18:06
I do have a couple of extra spell scripts and some custom player scripts (pvp/duels hooks related) and the Autobalance patch from here: https://github.com/trickerer/Autobalance_for_NPCBots

**Comment by acidmanifesto** [comment] 2021-03-27 18:11
https://github.com/TrinityCore/TrinityCore/blob/80f30d5ca94f000962a06e398567aa0b1ddd706b/src/server/game/Entities/Unit/Unit.cpp#L414
Im just pasting this here for quicker reference on the issue to the line that is present in that gist. I have not encountered it personally. just posting the referenced file and line link.

**Comment by jackpoz** [comment] 2021-03-27 18:23
@silviu20092 when reporting an issue please mention if you have custom changes and if possible include a link to the public github fork with the version you are running.

I assume you have npc bots too as you have autobalance ?

**Comment by silviu20092** [comment] 2021-03-27 18:48
@jackpoz sorry, nope there is no NPC bots, that patch is meant to work with the npc bots aswell but I don't use them. For this test server there is just the autobalance and a couple of spellscripts (just written for fun really, not meant to mean anything). Besides the autobalance changes there are 0 changes to 3.3.5 TC branch.

**Comment by silviu20092** [comment] 2021-03-27 19:20
I see that in Map.cpp at line 3620 we have:
`RemoveFromMap(obj->ToCreature(), true);`
Inside this function is the following code:
`obj->RemoveFromWorld();`
This will remove everything in m_Controlled (if the object is in world at the time of call). Then later in the same RemoveFromMap function `DeleteFromWorld(obj);` is called which essentially does a `delete obj` and Unit destructor gets called. 

So how is m_Controlled not empty at the time of object deletion if it was cleared just earlier?

**Comment by jackpoz** [comment] 2021-03-27 19:52
did Server.log show any message by the way before the crash ?

**Comment by silviu20092** [comment] 2021-03-27 19:56
Unfortunately I had it on overwrite mode and I didn't get to see anything before the crash.

**Comment by jackpoz** [comment] 2021-04-05 10:09
Server.log should contain more information, either change to append mode or add the date to the log name from the settings.

**Comment by illfated** [comment] 2021-04-05 11:09
I always create a new log file with date & time included in the file name.
Related lines in my worldserver.conf file:
```sql
#  Appender config values: Given an appender "name"
#    Appender.name
#        Description: Defines 'where to log'.

Appender.Console=1,3,0
Appender.Server=2,2,15,World/Server.log
Appender.GM=2,2,15,gm/gm_%s.log
Appender.DBErrors=2,2,15,DBErrors/DBErrors.log

#  Logger config values: Given a logger "name"
#    Logger.name
#        Description: Defines 'What to log'

Logger.root=5,Console Server
Logger.server=3,Console Server
Logger.commands.gm=3,GM
Logger.scripts.hotswap=3,Console Server
Logger.sql.sql=5,Console DBErrors
Logger.sql.updates=3,Console Server
Logger.mmaps=3,Server
```

**Comment by silviu20092** [comment] 2021-04-05 11:40
Yeah I have set it up on append mode now, however I did not encounter this crash anymore, seems to be really isolated.

**Comment by ckegg** [comment] 2021-05-04 20:16
Here are 4 crash logs from different time but always on the same creature 37134, Ymirjar Huntress
[crash-2021-04-21-23-52-19.log](https://github.com/TrinityCore/TrinityCore/files/6423677/crash-2021-04-21-23-52-19.log)
[crash-2021-04-22-00-22-20.log](https://github.com/TrinityCore/TrinityCore/files/6423678/crash-2021-04-22-00-22-20.log)
[crash-2021-05-04-22-07-30.log](https://github.com/TrinityCore/TrinityCore/files/6423679/crash-2021-05-04-22-07-30.log)
[crash-2021-05-04-22-36-01.log](https://github.com/TrinityCore/TrinityCore/files/6423680/crash-2021-05-04-22-36-01.log)

**Comment by jackpoz** [comment] 2021-05-06 07:38
@ckegg do you have any custom changes ? could you try reproducing the assert ? we might aswell log the actual controlled unit if possible. Are you using the latest version of https://github.com/TrinityCore/TrinityCore/tree/3.3.5/contrib/debugger to create the crashlog ? it should show the full assert message, not just a part

**Comment by silviu20092** [comment] 2021-05-06 22:24
The controlled unit is Warhawk (entry 38154) and it is summoned via spell SPELL_SUMMON_WARHAWK = 71705 in npc_frostwing_ymirjar_vrykul. Still don't know the exact steps on how to reproduce this issue but seems to happen pretty often now.

**Comment by ckegg** [comment] 2021-05-07 04:11
> 
> 
> @ckegg do you have any custom changes ? could you try reproducing the assert ? we might aswell log the actual controlled unit if possible. Are you using the latest version of https://github.com/TrinityCore/TrinityCore/tree/3.3.5/contrib/debugger to create the crashlog ? it should show the full assert message, not just a part

This had been happening for a month. I pull and build every week. I am using clean build on cd853118b6cc on last two logs generated on 5/4. For 4/21 and 4/22 I forgot which commit I used but also clean build. All these 4 logs were generated with debug mode and gdb under debian 10.4

**Comment by gtestdev** [comment] 2021-06-21 09:00
I can confirm it, I don't know how to reproduce it: https://gist.github.com/gtestdev/1e147dee32d63d400d7a4fc8105bce48

**Comment by Aokromes** [comment] 2021-06-21 11:00
never seen myself, it looks to require one hunter having warhawk as pet?

**Comment by ckegg** [comment] 2021-06-30 19:57
Better crash log
3.3.5 b596ea298a7b
[crash-2021-06-30-23-19-22.log](https://github.com/TrinityCore/TrinityCore/files/6743659/crash-2021-06-30-23-19-22.log)

**Comment by jackpoz** [comment] 2021-07-01 08:15
I'll add m_Controlled to GetDebugInfo() so it will get logged in the crashlog

**Comment by jackpoz** [comment] 2021-07-11 09:42
btw both crashlogs are at position MapID: 631 Map name: 'Icecrown Citadel' X: 4362.18 Y: 2642.97 Z: 351.1 O: 1.5331 , is that the spawn point of the boss or is it the position of any particular event ?
Maybe the order of "who dies first" between the boss and the minion matters ? It would be nice to try killing the boss first once, then the minion first once.

**Comment by jackpoz** [comment] 2021-07-11 09:59
> The controlled unit is Warhawk (entry 38154) and it is summoned via spell SPELL_SUMMON_WARHAWK = 71705 in npc_frostwing_ymirjar_vrykul. Still don't know the exact steps on how to reproduce this issue but seems to happen pretty often now.

@silviu20092 is that information in one of the crashlogs or ?

**Comment by jackpoz** [comment] 2021-07-11 12:15
By the way could the people having these crashes check if the logs contain any message like this ?
>"entities.unit", "SetMinion: Minion %u is not the minion of owner %u"

**Comment by jackpoz** [comment] 2021-07-11 12:27
What are your GridUnload and InstanceMapLoadAllGrids settings ?

**Comment by ckegg** [comment] 2021-07-11 20:06
Mine is
GridUnload = 1
BaseMapLoadAllGrids = 0
InstanceMapLoadAllGrids = 0

still waiting for a crash

**Comment by ckegg** [comment] 2021-07-16 03:19
Here are logs
[crash-2021-07-15-21-19-59.log](https://github.com/TrinityCore/TrinityCore/files/6827545/crash-2021-07-15-21-19-59.log)
[crash-2021-07-15-21-24-59.log](https://github.com/TrinityCore/TrinityCore/files/6827546/crash-2021-07-15-21-24-59.log)
[crash-2021-07-15-21-28-59.log](https://github.com/TrinityCore/TrinityCore/files/6827547/crash-2021-07-15-21-28-59.log)

Not sure why one of the log is not giving m_Controlled details
3.3.5, commit ae7b6fbabb6c

**Comment by jackpoz** [comment] 2021-07-16 09:46
well that confirms it's https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=38154 the controlled one, thanks for the crashlogs

**Comment by jackpoz** [comment] 2021-07-16 12:00
@ckegg do you have any log in category "entities.unit" that looks like this ?
>"SetMinion: Minion %u is not the minion of owner %u"

**Comment by ckegg** [comment] 2021-07-17 03:33
> 
> 
> @ckegg do you have any log in category "entities.unit" that looks like this ?
> 
> > "SetMinion: Minion %u is not the minion of owner %u"

No, but I will turn it on now and let's see

**Comment by jackpoz** [comment] 2021-07-17 10:55
https://github.com/TrinityCore/TrinityCore/commit/8c42b3bd88fe7bd3e959664312e818e25996873a is an attempt to blindly fix the crash (as it's unclear how to reproduce it yet), with not much hope that it actually fixes it but who knows

**Comment by ckegg** [comment] 2021-07-20 17:36
> 
> 
> @ckegg do you have any log in category "entities.unit" that looks like this ?
> 
> > "SetMinion: Minion %u is not the minion of owner %u"

Unfortunately logs has is not showing anything like "SetMinion: Minion %u is not the minion of owner %u"
Here are today's crash logs and special logs showing entities.unit just right before crashes
These are generated before your fix, I just want to make sure I am still be able to get the crash, and from now on I will apply the fix and continue monitoring

3.3.5 commit aa7279df095d
[crash-2021-07-20-22-17-22.log](https://github.com/TrinityCore/TrinityCore/files/6850198/crash-2021-07-20-22-17-22.log)
[crash-2021-07-20-22-57-22.log](https://github.com/TrinityCore/TrinityCore/files/6850199/crash-2021-07-20-22-57-22.log)
[Special_2021-07-18_09-26-39.log](https://github.com/TrinityCore/TrinityCore/files/6850200/Special_2021-07-18_09-26-39.log) (only entities.unit)
[Special_2021-07-20_22-17-32.log](https://github.com/TrinityCore/TrinityCore/files/6850201/Special_2021-07-20_22-17-32.log) (only entities.unit)

**Comment by jackpoz** [comment] 2021-07-21 07:21
There are a few JUST_DIED lines that might be related to other creatures, maybe the owner or the pet just died/are dead and a IsAlive() check could fix the issue.

**Comment by ckegg** [comment] 2021-07-21 17:18
I updated my previous log report, grouping corresponding logs together.
My feeling is this is not about Ymirjar Huntress's death

taking crash-2021-07-20-22-17-22.log
```
/Trinity/source/src/server/game/Entities/Unit/Unit.cpp:419 in ~Unit ASSERTION FAILED:
  m_Controlled.empty()
MapID: 631 Map name: 'Icecrown Citadel' X: 4364.69 Y: 2666.76 Z: 349.242 O: 2.44554
GUID Full: 0xf13000910e000647 Type: Creature Entry: 37134  Low: 1607 Entry 37134
Name: Ymirjar Huntress
IsAIEnabled: true DeathState: 0 UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 2
MoveSpline
spline Id: 3112089
flags:  Done CanSwim Final_Angle
facing  angle: 3.05002
time passed: 1
total  time: 1495284022
spline point Id: 1
path  point  Id: 1
mode: Linear
points count: 4
point 0 : (4365.69, 2666.67, 349.242)
point 1 : (4364.69, 2666.76, 349.242)
point 2 : (4364.69, 2666.76, 349.242)
point 3 : (4364.69, 2666.76, 349.242)
GetCharmedGUID(): GUID Full: 0x0000000000000000 Type: None Low: 0
GetCharmerGUID(): GUID Full: 0x0000000000000000 Type: None Low: 0
No vehicle kit
GetGameClientMovingMe(): NULL
m_Controlled size: 1
m_Controlled 1 : GUID Full: 0xf13000950a000657 Type: Creature Entry: 38154  Low: 1623
```

Lookup those GUID Full: 0xf13000910e000647 (Entry: 37134) and the controller 0xf13000950a000657 (Entry: 38154) in Special_2021-07-18_09-26-39.log, does it make sense to you?

**Comment by jackpoz** [comment] 2021-07-21 18:09
I would say the minion is added after the owner has been removed from world

**Comment by jackpoz** [comment] 2021-07-21 18:50
@ckegg https://github.com/TrinityCore/TrinityCore/commit/3f08c16749984252e657d46cfaa1ef50cd3f5a15 adds a new log in the same category"entities.unit" : "SetMinion: Minion being added to owner not in world", please check if it gets triggered or if the crash still happens.

**Comment by Aokromes** [comment] 2023-09-16 22:18
no feedback after more than 2 years, closing.

**Closed by Aokromes** 2023-09-16 22:18 UTC
Labels: HasBacktrace, Priority-High, Branch-3.3.5a
