### ISSUE TITLE
Hunter's pet doing a lot of damage

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21384] opened 2018-02-09 14:29 UTC
**Description:**

Hunter pet should not hit that much with auto attack (not just Dummy).

![screen shot 1396-11-20 at 5 52 27 pm](https://user-images.githubusercontent.com/5238989/36032290-c5094b9a-0dc2-11e8-889b-22259b77b4aa.png)
![screen shot 1396-11-20 at 5 52 31 pm](https://user-images.githubusercontent.com/5238989/36032291-c538f174-0dc2-11e8-818f-9a6db181045f.png)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 303efcf

**TDB version:**  TDB 335.63

**Operating system:** Debian 9

**Comment by tkrokli** [comment] 2018-02-09 14:36
Duplicate of #21333 **Exotic hunter pet outputs excessive damage**

**Closed by tkrokli** 2018-02-09 14:36 UTC

**Comment by tje3d** [comment] 2018-02-09 14:46
@tkrokli So this can be count as confirm 😜

**Comment by tkrokli** [comment] 2018-02-09 14:55
Yes, sure it can. We prefer to get comments added to existing issue tickets instead of new tickets that will be closed, though.

**Comment by kaldown** [comment] 2018-02-13 16:52
`SELECT name, damagemodifier FROM creature_template WHERE type_flags = 65537;`

[type flags](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130008/creature+template#creature_template-type_flags)

```
+----------------------------+----------------+
| name                       | damagemodifier |
+----------------------------+----------------+
| Flesh Eating Worm          |            0.5 |
| Fledgling Chimaera         |              1 |
| Young Chimaera             |              1 |
| Silithid Ravager           |              1 |
| Murk Worm                  |            2.4 |
| Hazzali Sandreaver         |              1 |
| Centipaar Sandreaver       |              1 |
| Chimaera Matriarch         |              1 |
| Devilsaur                  |            2.4 |
| Ironhide Devilsaur         |            2.4 |
| Tyrant Devilsaur           |            2.4 |
| Gorishi Reaver             |              1 |
| Clutchmother Zavas         |              1 |
| King Mosh                  |            4.6 |
| Fledgling Chillwind        |              1 |
| Chillwind Chimaera         |              1 |
| Chillwind Ravager          |              1 |
| Soriid the Devourer        |              1 |
| Haarka the Ravenous        |              1 |
| The Evalcharr              |              1 |
| Mistwing Rogue             |              1 |
| Mistwing Ravager           |              1 |
| Dredge Worm                |              1 |
| Gorishi Hive Guard         |              1 |
| Brumeran                   |              1 |
| Rotting Worm               |            0.5 |
| Earthborer                 |            1.7 |
| Hive'Ashi Sandstalker      |              1 |
| Hive'Zora Reaver           |              1 |
| Hive'Regal Ambusher        |              1 |
| Hive'Regal Hive Lord       |              1 |
| Dredge Striker             |              1 |
| Dredge Crusher             |              1 |
| Rock Borer                 |              1 |
| Rock Worm                  |              1 |
| Deep Borer                 |            2.4 |
| Chimaerok                  |            4.6 |
| Arcane Chimaerok           |            4.6 |
| Chimaerok Devourer         |            4.6 |
| Oozeworm                   |              1 |
| Cadaverous Worm            |              1 |
| Lapress                    |            4.6 |
| Grubthor                   |              1 |
| Xil'xix                    |              1 |
| The Kurken                 |              1 |
| Infernal Hound             |              1 |
| Tyrantus                   |              1 |
| Nuramoc                    |            4.6 |
| Bladewing Bloodletter      |              1 |
| Spawn of Uvuros            |              1 |
| Young Crust Burster        |              1 |
| Vilewing Chimaera          |              1 |
| Ice Heart Jormungar Feeder |              1 |
| Wooly Rhino Bull           |              1 |
| Loque'nahak                |            4.6 |
| Frostwing Chimaera         |              1 |
| Tundra Crawler             |              1 |
| Wooly Rhino Matriarch      |              1 |
| Wooly Rhino Calf           |              1 |
| Hulking Jormungar          |            4.6 |
| Ice Heart Jormungar Spawn  |              1 |
| Shardhorn Rhino            |              1 |
| Snowdrift Jormungar        |              1 |
| Ice Steppe Rhino           |              1 |
| Ravenous Jormungar         |              1 |
| Yggdras Worm               |              1 |
| Infesting Jormungar        |              1 |
| Ravenous Jormungar         |              1 |
| Roaming Jormungar          |              1 |
| Disembodied Jormungar      |              1 |
| Ice Steppe Bull            |              1 |
| Romping Rhino              |              1 |
| Icehorn                    |              1 |
| King Krush                 |            7.5 |
| Tamable Core Hound         |              1 |
| Tamable Chimaera           |              1 |
| Tamable Devilsaur          |              1 |
| Tamable Rhino              |              1 |
| Tamable Silithid           |              1 |
| Tamable Spirit Beast       |              1 |
| Tamable Worm               |              1 |
| Gondria                    |             15 |
| Skoll                      |            7.5 |
| Arcturis                   |            7.5 |
+----------------------------+----------------+
```

SO I wonder, is that only for Gondria ? And how exact amount should be for those creatures after `tame beast` ?

**Comment by Killyana** [comment] 2018-02-13 17:26
Don't think the damagemodifier is used to calculate the damage for players pets.

**Comment by kaldown** [comment] 2018-02-13 21:40
```
select name, damagemodifier from creature_template where entry = 33776;
+---------+----------------+
| name    | damagemodifier |
+---------+----------------+
| Gondria |              1 |
+---------+----------------+
```

gondria hits me in wild
![2018-02-14--00 38 56_1366x768_scrot](https://user-images.githubusercontent.com/3754017/36175126-7d14a036-111f-11e8-9493-5b70cc37ec9b.png)

tammed gondria hits mob 
![2018-02-14--00 38 27_1366x768_scrot](https://user-images.githubusercontent.com/3754017/36175127-7d34ab56-111f-11e8-9e44-f1dcb4f9ffc9.png)

**Comment by tkrokli** [comment] 2018-02-13 21:49
@kaldown : Please, please, please post in open issue tickets, not in closed ones.
