### ISSUE TITLE
[3.3.5] Crash  Player::RefundItem

### ISSUE THREAD

**Issue by Voidx** [TrinityCore/TrinityCore#15536] opened 2015-09-17 22:03 UTC
6fedea54ef3f1c678f0869807ac38b1db72351fd , 
http://pastebin.com/buMAL3Lm
Ubuntu 12.04.5 LTS

Custom:
Trasnmogrification.

**Comment by Rushor** [comment] 2016-02-04 10:37
@Voidx: this issue is still present?

**Comment by tkrokli** [comment] 2016-02-11 11:16
Would be interesting to know if the item refund event could in any way be related to transmog.

**Comment by Rushor** [comment] 2016-02-12 06:31
no answer after monts - closing

**Closed by Rushor** 2016-02-12 06:31 UTC
Labels: Branch-3.3.5a, Comp-Core, HasBacktrace

**Comment by Rushor** [comment] 2020-05-06 10:15
This issue actually still happens sometimes (if server has trasmog)

**Comment by Shauren** [comment] 2020-05-06 10:35
Not our problem if transmog is the cause
