### ISSUE TITLE
[6.x](?) Spell Darkflight [WORGEN]

### ISSUE THREAD

**Issue by DearAdmin** [TrinityCore/TrinityCore#13652] opened 2014-12-02 00:18 UTC
Hello, When worgen classes are  changing faction to   horde , darkflight didnt removing from the spel book

http://www.wowhead.com/spell=68992/darkflight

Regards,

**Comment by VeraDev** [comment] 2015-01-16 21:30
Depends if you want it the hacky way or not, but it's hacky fixable by adding something like this;
if getRace != worgen... & HasSpell (spellId), removeSpell...
You get the logic behind it, now if you want to do it the hacky way, you must do the rest yourself.

**Comment by Rushor** [comment] 2016-02-08 11:08
table player_faction_change_spells will help you here - and check if the issue is still preent on 6.x

**Comment by Aokromes** [comment] 2016-06-15 05:34
No answer after more than 4 months, closing.

**Closed by Aokromes** 2016-06-15 05:34 UTC
Labels: Branch-6.x, Comp-Core, Sub-Spells
