### ISSUE TITLE
Core/spell: Client crash with max target over 100 units

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#23060] opened 2019-02-21 10:57 UTC
Description: Work engineering , enchant spell / players kicked  just in the same range map:   
[Personal Electromagnetic Pulse Generator]
https://www.wowhead.com/spell=54735/electromagnetic-pulse

1. enchant spell on waist
2. add 30x or 50x npc
3. use spell with waist  to creatures
=
DC / kicked players on the same range map!

Branch(es): 3.3.5
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/58c5dfac1d8d314b9243fde52466b3c933fb7d7f
OS: windows

**Comment by Killyana** [comment] 2019-02-24 09:05
This client crash is known on Onyxia encounter when a wartank use Shockwave on Whelps.
To reproduce the issue, spawn 101 npc=6225 on the same spot then .cast 54735 near the npcs, the client will crash.
If you relog the client also will crash as this npcs still have the stun aura, so it looks like the client cannot support the aura to be applied to more than 100 units.

**Comment by Warpten** [comment] 2019-02-24 10:44
https://github.com/TrinityCore/TrinityCore/commit/02a3b3d949e073a78247efa41cfc120a56b9e5fe

**Comment by Hir0shi** [comment] 2019-03-03 19:08
and That's it spell
https://wotlk-twinhead.twinstar.cz/?spell=48817

**Comment by jackpoz** [comment] 2019-03-08 15:03
does the client crash and closes or does it go to the login screen ? could you post a screenshot ?

**Comment by Killyana** [comment] 2019-03-08 15:04
It goes to the login screen with the message: "you have been disconnected from the server"

**Comment by Killyana** [comment] 2019-03-08 15:27
Caused by https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Server/WorldSession.cpp#L1540
When PacketSpoof.Policy = 1

**Comment by jackpoz** [comment] 2019-03-08 15:46
Were you able to get which packet is hitting the limit ? So we can set it to 0 to disable the limit

**Comment by Killyana** [comment] 2019-03-08 18:58
An other case where the client is kicked, just aggro 101 creatures when you backped:
```
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK (0x384), count: 101)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_SPEED_CHANGE_ACK (0xE7), count: 101)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK (0x382), count: 101)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK (0xE5), count: 101)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK (0x2DD), count: 101)
AntiDOS: Player kicked!
 
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK (0x384), count: 102)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_SPEED_CHANGE_ACK (0xE7), count: 102)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK (0x382), count: 102)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK (0xE5), count: 102)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK (0x2DD), count: 102)
AntiDOS: Player kicked!
 
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK (0x384), count: 103)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_SPEED_CHANGE_ACK (0xE7), count: 103)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK (0x382), count: 103)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK (0xE5), count: 103)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK (0x2DD), count: 103)
AntiDOS: Player kicked!
 
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK (0x384), count: 104)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_SPEED_CHANGE_ACK (0xE7), count: 104)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK (0x382), count: 104)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK (0xE5), count: 104)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK (0x2DD), count: 104)
AntiDOS: Player kicked!
 
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK (0x384), count: 105)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_SPEED_CHANGE_ACK (0xE7), count: 105)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK (0x382), count: 105)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK (0xE5), count: 105)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK (0x2DD), count: 105)
AntiDOS: Player kicked!
 
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK (0x384), count: 106)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_SPEED_CHANGE_ACK (0xE7), count: 106)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK (0x382), count: 106)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK (0xE5), count: 106)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK (0x2DD), count: 106)
AntiDOS: Player kicked!
 
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK (0x384), count: 107)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_SPEED_CHANGE_ACK (0xE7), count: 107)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK (0x382), count: 107)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK (0xE5), count: 107)
AntiDOS: Player kicked!
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK (0x2DD), count: 107)
AntiDOS: Player kicked!
 
AntiDOS: Account 1, IP: 127.0.0.1, Ping: 0, Character: Hilliium, flooding packet (opc: CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK (0x384), count: 108)
AntiDOS: Player kicked!

**Comment by jackpoz** [comment] 2019-03-08 19:41
disabling the limit for those then

**Comment by Killyana** [comment] 2019-03-09 14:51
Fixed by https://github.com/TrinityCore/TrinityCore/commit/9d34739d690056522a3cde4f50e31c3b8b94fab7

**Closed by Killyana** 2019-03-09 14:51 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Spells

**Comment by Killyana** [comment] 2019-03-09 14:58
Ref:
``` sql
DELETE FROM smart_scripts WHERE entryorguid=6225 AND source_type=0 AND id=0;
INSERT INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, event_param5, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, COMMENT) VALUES
(6225, 0, 0, 0, 0, 0, 100, 0, 5, 30, 2300, 3900, 0, 11, 1604, 64, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "Mechano-Tank - Combat CMC - Cast 'Dazed'");
