### ISSUE TITLE
Latest core - all characters need to be renamed (and can't create a new character)

### ISSUE THREAD

**Issue by mcsescott** [TrinityCore/TrinityCore#24917] opened 2020-06-28 16:21 UTC
**Description:**

Downloaded and compiled latest core and 830 DB.  Upon logging into existing characters, the client disconnects with Blizzard error 51900319.  When I log back in, the character is set to rename, and I am unable to rename it to anything.  Thus, not able to log in.

Serer startup log attached, if it helps:  
[Server.log](https://github.com/TrinityCore/TrinityCore/files/4842594/Server.log)

In addition, when I try to make an existing character, the seer states that any name I type in has mature language.

**Expected behavior:**

Should be able to log into existing character.

Attempt to log into existing character, see the problems above.

------------
**Branch(es):**  
Master

**TC rev. hash/commit and Operting System:** 
TrinityCore rev. 6040f8eb3167 2020-06-28 12:26:39 +0200 (master branch) (Win64, RelWithDebInfo, Static)

**Comment by Shauren** [comment] 2020-06-28 16:23
Client locale?
Server db2 locale?
RealmZone, StrictPlayerNames?

**Comment by mcsescott** [comment] 2020-06-28 16:41
In worldserver.conf, 
StrictPlayerNames = 0
StrictCharterNames = 0
DBC.Locale = 0

In config.wtf from client:
SET textLocale "enUS"
SET audioLocale "enUS"

From auth.realmlist:
'1', 'Kifaru', 'mounteverest.game-host.org', '192.168.1.20', '255.255.255.0', '8085', '0', '0', '1', '0', '0', '34769', '1', '1'

**Comment by Shauren** [comment] 2020-06-28 18:06
Duplicate of #24916

**Closed by Shauren** 2020-06-28 18:06 UTC
Labels: Branch-master
