### ISSUE TITLE
[3.3.5] [Quest] Torch Catching - Midsummer Fire Festival

### ISSUE THREAD

**Issue by Phentora** [TrinityCore/TrinityCore#24893] opened 2020-06-25 09:04 UTC
**Description:**
Currently players cannot do the quest **[Torch Catching](https://www.wowhead.com/quest=11657/torch-catching)** since using the provided item **[Unlit Torches](https://www.wowhead.com/item=34833/unlit-torches)** does not trigger the required behavior. Meaning that after the player uses the item, he will not do the throw animation and neither will the torch actually be thrown.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 3ac1992afbeb 2020-06-24 22:53:41 +0200 (3.3.5 branch) (Unix, Release, Static)

**Operating system:** 
Ubuntu 19.04

**Comment by jackpoz** [comment] 2020-06-25 10:03
should the old issue be reopened then ?

**Comment by Phentora** [comment] 2020-06-25 10:25
Well i cannot reopen that issue sadly. That was my first option.

**Comment by ipriver** [comment] 2020-06-25 10:47
Can confirm that fix didn't work, the quest is still broken.

**Comment by Rothend** [comment] 2020-06-25 11:16
Cannot reproduce. The item itself ([Juggling Torch](https://www.wowhead.com/item=34599)) works, and that's what I fixed on that PR. Catching the torch requires the quest Torch Catching to be rewarded.

Steps to confirm that it works:
.add 34599
.q a 11923
.q c 11923
.q rew 11923
.tele dalaran
Launch the torch on your character's position, it will be thrown and caught and it will count for the achievement.

Now, the Torch Catching/More Torch Catching quests are actually bugged and not completable, so you can't catch the torch as a normal player :P I'll try to fix those too, just wanted to say that the issue isn't related to the merged PR or the achievement Torch Juggler.

**Comment by Phentora** [comment] 2020-06-25 11:21
My apologies if the title of the bug isn't correct. I have tried using the item and it has the same behavior as before the fix. Meaning, there is no throw animation and no torch is displayed anywhere. I did not use any GM commands, as i just picked up the quest normally.

I just want to be clear that the item itself does nothing after it's spell is casted. Thank you for the reply by the way!

**Comment by Rothend** [comment] 2020-06-25 11:29
The item that I fixed in that PR is 34599. It's not the one given when you accept that quest, it's the reward that you can also buy from the vendor.

I didn't mean to cause confusion, I fixed that one without checking if the previous steps were working :) I'll see what I can do to fix the quest too.

**Comment by Phentora** [comment] 2020-06-25 11:31
I have also updated the bug report to match reality.

**Comment by Rothend** [comment] 2020-06-25 11:36
Only thing to change is that the quest item is actually [https://www.wowhead.com/item=34833](Unlit Torches) (ID: 34833), not Juggling Torch.

Thanks for editing the issue!

**Closed** 2020-08-12 11:40 UTC
Labels: Branch-3.3.5a, Comp-C++Script
