### ISSUE TITLE
[3.3.5/4.3.4/6.x] Some wrong Proc Flag handling

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#13987] opened 2015-01-30 15:55 UTC
Rev.: a93c40143f4e79577ac8e0a3faee92b1effbcd89

It appears that some proc flags like
PROC_FLAG_DONE_SPELL_MELEE_DMG_CLASS 
PROC_FLAG_DONE_SPELL_RANGED_DMG_CLASS 
PROC_FLAG_DONE_SPELL_NONE_DMG_CLASS_POS 
PROC_FLAG_DONE_SPELL_NONE_DMG_CLASS_NEG 
PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_POS 
PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG;
are being handled at the wrong place.

The named flags seem to be suposed to proc on spell launch instead of spell hit. The consequence of this late handling is the delay of several procs that should proc when a spell is successfully casted regardless if the hit result is positive or negative. (Didn't test yet if a spell miss result will break the proc in this case)
##

**Comment by Unholychick** [comment] 2015-02-03 18:31
as every other issue with procs, incomplete new proc system is the cause of this. as you described procs on cast are not handled correctly

**Comment by ariel-** [comment] 2016-12-01 05:53
Fixed with new proc system

**Closed by ariel-** 2016-12-01 05:53 UTC
Labels: Comp-Core, Sub-Spells
