### ISSUE TITLE
6x problem undead

### ISSUE THREAD

**Issue by deadmanevil** [TrinityCore/TrinityCore#14651] opened 2015-05-04 18:51 UTC
edbd44a67530f2938864fd054182553b3d5ab1ac
Nor you can create an undead that have rigomortis

**Comment by Killyana** [comment] 2015-05-04 20:08
More description will help.

**Comment by tkrokli** [comment] 2015-05-04 20:45
- http://collab.kpsn.org/display/tc/The+Issuetracker+and+You
- https://github.com/TrinityCore/TrinityCore/wiki
- http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/

**Comment by deadmanevil** [comment] 2015-05-05 18:03
when you create an undead you can not move because it has the spell rigomortis

**Comment by tkrokli** [comment] 2015-05-05 19:30
That is true, I tested it on the 4.3.4 branch a month or 2 ago. I thought it was a new feature introduced in Cataclysm, since I didn't create any undead characters on the live servers in 2011 or later. So I can confirm that it happens in the 4.3.4 source. Isn't this just a matter of waiting out the duration of the spell (or using `.unaura all` on the new character, if you are in a hurry)? ["It's not a bug, it's a feature." -Microsoft]

**Comment by Aokromes** [comment] 2015-05-05 19:37
Strange that the bug exists on 4.3.4 branch i pushed a fix for it months ago.

**Comment by tkrokli** [comment] 2015-05-05 19:39
OK, maybe it is longer than just a couple of months since I compiled 4.3.4 - I just included it to explain that I now understand what the OP is talking about.

**Comment by Killyana** [comment] 2015-05-05 19:53
This https://github.com/TrinityCore/TrinityCore/commit/fc7b6a9e0fac5b0fb36e692eb29671fdbcf9fa4c was pushed to the 6.x branch no?

**Comment by tkrokli** [comment] 2015-05-05 20:04
OK, I see now that I must have tested the 4.3.4 branch in January or very early February. So I guess the OP is trying to say that [[Quest 24959 - Fresh out of the Grave](http://www.wowhead.com/quest=24959/fresh-out-of-the-grave)] is not working on 6.x ?

**Comment by Regigicas** [comment] 2015-05-08 21:20
Working fine using https://github.com/TrinityCore/TrinityCore/commit/347e954086c71d6286f08a5467de8a41457684ad
And TDB 6.01 + updates

http://i.gyazo.com/c658ef5ec5fba414da96567feea6fdfc.mp4

**Closed** 2015-05-08 21:38 UTC
Labels: Branch-6.x, Comp-Database
