### ISSUE TITLE
Zelfrax is Summoned Twice

### ISSUE THREAD

**Issue by WOW-Reborn** [TrinityCore/TrinityCore#22364] opened 2018-09-01 02:17 UTC
**Description:**

Cleansing Witch Hill Zelfrax summon twice.

**Current behaviour:**

The script is working correctly but after you kill Zelfrax, its like the spell loops by itself and Zelfrax is summoned again for a second time making you have to kill the mob twice. 

**Expected behaviour:**

Zelfrax should only be summoned one time.

**Steps to reproduce the problem:**

Have the quest Cleansing Witch Hill (11183)
Use the torch to summon Zelfrax
Kill the first Zelfrax, and you will notice the beam starts again and a second one is summoned.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

ca7ee982db4d25c464acf6daadc150d58dafa016

**Operating system:**

Windows Server 2016

**Comment by WOW-Reborn** [comment] 2018-09-01 08:34
`UPDATE `smart_scripts` SET `event_flags` = 1 WHERE `entryorguid` = 4792 AND `source_type` = 0 AND `id` = 0 AND `link` = 0`

**Comment by WOW-Reborn** [comment] 2018-09-01 08:34
This seems to solve the issue with the script running a second time.

**Comment by Killyana** [comment] 2018-09-01 12:27
@ZenoX92 the event 70, 1 (SMART_EVENT_GO_STATE_CHANGED, 1 - Ready) is called when the gameobject respawn and despawn.

The call in despawn is probably wrong, I don't know if you could reproduce the issue in an older core.

**Comment by ZenoX92** [comment] 2018-09-03 04:49
I cannot reproduce it in my old core (TrinityCore rev. 1cc3d33), but it's because the gameobject don't despawn once it's respawned. This was fixed in later commits, so now it despawns as intended.

Maybe this could be a temporal fix:
```sql
-- "Swamp Eye" Jarl
UPDATE `smart_scripts` SET `event_flags`=1 WHERE `entryorguid`=4792 AND `source_type`=0 AND `id`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid`=4792 AND `source_type`=0 AND `id`=1;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(4792,0,1,0,38,0,100,0,2,2,0,0,0,78,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"\"Swamp Eye\" Jarl - On Data Set - Reset All Scripts");

-- Zelfrax
DELETE FROM `smart_scripts` WHERE `entryorguid`=23864 AND `source_type`=0 AND `id`=3;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(23864,0,3,0,6,0,100,0,0,0,0,0,0,45,2,2,0,0,0,0,19,4792,0,0,0,0,0,0,"Zelfrax - On Just Died - Set Data to \"Swamp Eye\" Jarl");

**Comment by Killyana** [comment] 2019-02-25 15:12
The issue is that  SetLootState(GO_READY); is called by GO_JUST_DEACTIVATED: it must probably be changed to SetLootState(GO_NOT_READY); it fixes the issue for me.

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/GameObject/GameObject.cpp#L782

**Closed** 2019-03-02 15:40 UTC
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-GameObject
