### ISSUE TITLE
3.3.5. Flametongue rank 6 bugged with dual wielding.

### ISSUE THREAD

**Issue by Mecar1997** [TrinityCore/TrinityCore#23979] opened 2019-12-20 12:45 UTC
**Description:**

Flametongue rank 6 works incorrectly while dual-wielding.

**Current behaviour:**

If you cast flametongue rank 6 on both your weapons, you will get the bonus spell damage only once, and only the last weapon on which you casted flametongue (generally the offhand) will trigger the fire damage proc. The other weapon won't.

Only rank 6 has this issue.

**Expected behaviour:**

Flametongue should get a total of 116 spell damage, and deal fire damage with both weapons.

**Steps to reproduce the problem:**

1 . Dual Wield
2 . Cast Flametongue rank 6 on both weapons, or cast any other rank of Flametongue + Flametongue rank 6.

**Branch(es):**

3.3.5

**Operating system:** Win10

**Comment by illfated** [comment] 2019-12-20 13:02
Please add the core revision hash you are using, so it will be easier for other users to be sure they are on the same core rev. as you when testing and reproducing your issue.

**Comment by RealLushen** [comment] 2020-10-10 12:49
Up! - Have the same Issue.

**Comment by illfated** [comment] 2020-10-10 12:56
@RealLushen : Please add your core rev. hash string, to help us track the affected core versions.
The source is often updated more than once a day, and the time of a comment post does not tell us your version.
(@Mecar1997 : I bet you don't remember which version you were running at the time of your report.)

**Comment by RealLushen** [comment] 2020-10-10 12:59
@illfated The last time I merged with the TC 3.3.5a Branch was at the "2016‑11‑02" - Since we are using a very old Version of TrinityCore. Our Core is a heavily modified TrinityCore. :)

**Comment by Aokromes** [comment] 2020-10-10 13:26
no hash after 10 months, and the only other feedback a 2016 core.

**Closed** 2020-10-10 13:26 UTC
Labels: Branch-3.3.5a, Sub-Spells

**Comment by illfated** [comment] 2020-10-10 15:11
Good point. To report an actual issue in the source, please provide proof that the issue can be replicated on clean and very recent TC source (rev. hash is mandatory).
