### ISSUE TITLE
[3.3.5] Pathing issues - Falling under the map

### ISSUE THREAD

**Issue by Espionage724** [TrinityCore/TrinityCore#15630] opened 2015-09-29 06:09 UTC
Build: https://github.com/TrinityCore/TrinityCore/commit/e5e2b093d20cda27ff4a24e82deed980d15ab523

DB GUID: 84582

Right after he does the "By the foul teat of Kil'Jaden's rotted torso" dialog, he proceeds to head to the next waypoint (leaving the building he walked into), and falls through the hill that's in his path. Eventually he stops falling and proceeds to float to the destination.

![wowscrnshot_092915_015832](https://cloud.githubusercontent.com/assets/6378956/10156351/12c43fbc-664e-11e5-9d94-3ca68cbbd803.jpg)

![wowscrnshot_092915_015835](https://cloud.githubusercontent.com/assets/6378956/10156354/1928cb52-664e-11e5-83cb-cc6e15432fb7.jpg)

**Comment by tkrokli** [comment] 2015-09-29 17:19
I'm thinking this could be a general problem and that it happens to several NPCs with waypoints.
My favorite is the [[Ratchet Bruiser]](http://wotlk.openwow.com/npc=3502) who patrols alongside the bank, the FP and [[Gazlowe]](http://wotlk.openwow.com/npc=3391)'s hut.
The guard disappears into the ground right at the corner of the bank, opposite [[Sputtervalve]](http://wotlk.openwow.com/npc=3442) (Samophlange quest giver), then reappears on the return path, closer to Gazlowe's hut.

**Comment by Kittnz** [comment] 2015-09-30 13:42
could be mmap or vmap issues too

**Comment by Espionage724** [comment] 2015-09-30 14:11
If someone else could verify that particular NPC (he's in Azuremyst Isles I think), that'd be great.

I compiled and used the content extractors under Linux, and extracted them about 13 days ago.

**Comment by Killyana** [comment] 2015-09-30 16:07
Something is weird about the WP:
After this point:  845820, 5, -4222.78, -12518.7, 45.5044, 0, 5000, 0, 331, 100, 0 (say text: "By the foul teat of Kil'Jaden's) the npc must move to the next point:  845820, 6, -4207.76, -12512, 45.0063, 0, 0, 0, 0, 100, 0 but this doesn't happen, it looks he move to a node that doesn't exist before he resume the path to 845820, 7, -4153.39, -12523.1, 45.0063, 0, 0, 0, 0, 100, 0

**Comment by jackpoz** [comment] 2015-09-30 19:16
the underground issue happens between waypoint 6 and 7, recast doesn't find a proper path so it just builds a shortcut between the 2 waypoints

**Comment by jackpoz** [comment] 2015-09-30 20:04
waypoint 5 is actually a little bit underground and this breaks pathfinding. Setting the Z to a little bit higher fixes the issue
```sql
UPDATE waypoint_data SET position_z = 45.5099 WHERE id = 845820 AND POINT = 5;
```

**Comment by Killyana** [comment] 2015-09-30 20:32
The issue still need to be fixed as it effects other npcs.

**Comment by tkrokli** [comment] 2015-10-01 04:53
TrinityCore rev. 1dcf186dfd24 2015-09-30 22:31:00 +0200 (3.3.5 branch) (Win64, Release) / TDB 335.59
Followed Artificer Daelo around on 3 laps of his waypoints, he keeps his feet on the ground now. :+1:

**Comment by MrSmite** [comment] 2015-10-01 06:36
> The issue still need to be fixed as it effects other npcs.

Yep, there's an arena mob that paths around Darnassus that has the bounce/float issue. I don't remember who it is though, they're not spawned right now.

**Comment by tkrokli** [comment] 2015-10-01 08:04
There are also the pathing [Darnassian Protectors, NPC entry 4423](http://wotlk.openwow.com/npc=4423), DB GUID: 46328, current GUID: 258 and DB GUID: 46325, current GUID: 436. They are falling down under ground across the path from Rellian Greenspyre and the static Darnassian Protector DB GUID: 46323, current GUID: 267, near the path up to night elf riding trainer Jartsam and the saber handler Lelanai.

To be more concise and to the point, they lose the ground at the area where their waypoints meet, where they both turn around and their waypoint paths seem to cross each other or overlap.

![wowscrnshot_100115_100154](https://cloud.githubusercontent.com/assets/4903600/10215618/8aadceea-6823-11e5-907b-3eb075e7b1be.jpg)

**Comment by tkrokli** [comment] 2015-10-12 01:55
This issue in itself was fixed by Killyana's commit https://github.com/TrinityCore/TrinityCore/commit/1dcf186dfd245315454ea5f907ab3efce477cbed, but will it be kept open as it is now for posting other NPC issues to be followed up? Would you like more feedback on similar NPCs who seem to fall through the map or walk in the air, are there any specific criteria for what should be posted here? :)

**Comment by Rushor** [comment] 2016-02-04 09:26
updated the title to a more general one, pls add more npcs which are affected by this issue.

**Comment by Kittnz** [comment] 2016-02-04 11:07
auto generated paths are also having this issue

**Comment by tkrokli** [comment] 2016-04-28 07:01
To all of you who have posted examples here: please check if your issue may have been fixed now by commit https://github.com/TrinityCore/TrinityCore/commit/9ad952c3bc87a03cc39c2c44a301857b8f62df7c (merge of PR #16736 [**Solve many of the creature falling through floor issues.**](https://github.com/TrinityCore/TrinityCore/pull/16736)).

I can confirm that by now, using rev. b82ffb88f7e6 2016-04-26 22:25:16 +0100 (3.3.5 branch),  my example in https://github.com/TrinityCore/TrinityCore/issues/15630#issuecomment-144650424 appear to be fixed, which suggests that many NPC Z axis map issues are now fixed.

**Comment by Rushor** [comment] 2016-06-05 10:35
so closing?

**Comment by Killyana** [comment] 2016-06-05 13:55
The issue here is not about npc going undremap but "recast doesn't find a proper path so it just builds a shortcut between the 2 waypoints"
And this issue is not fixed.
Also npcs going undermap during waypoints still happen,  like npc =26978

**Comment by Aokromes** [comment] 2016-11-14 05:32
blizzlike bug :trollface:

**Comment by Kittnz** [comment] 2016-11-14 07:21
@Aokromes it happens more then on retail tho, way more.

**Comment by Killyana** [comment] 2017-11-22 17:53
Cannot reproduce on rev. 9614f9d8cf29

**Closed by Killyana** 2017-11-22 17:53 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Maps/MMaps/Vmaps, Sub-Waypoints
