### ISSUE TITLE
[Quest] Locked Away

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26995] opened 2021-10-02 11:07 UTC
### Description

this is a visibility problem for NPC (farmer dalson) that spawn. It deals damage, but you can't see it.

https://github.com/TrinityCore/TrinityCore/issues/26617
https://classic.wowhead.com/npc=10836/farmer-dalson
same problem with
https://github.com/TrinityCore/TrinityCore/issues/26656
https://github.com/TrinityCore/TrinityCore/issues/26595

### Expected behaviour

https://github.com/TrinityCore/TrinityCore/commit/338abd531556822d17924025f6d460a3fd9899a2

### Steps to reproduce the problem

https://classic.wowhead.com/quest=5059/locked-away
.quest add 5059

### Branch

3.3.5

### TC rev. hash/commit

fece5bd

### Operating system

Debian 10 x64

### Custom changes

none

**Comment by offl** [comment] 2021-10-02 13:14
Please update your core and DB before reporting bugs
Can't reproduce and it was fixed in the commit you linked

**Closed by offl** 2021-10-02 13:14 UTC
Labels: Branch-3.3.5a
