### ISSUE TITLE
Inability to move companions Airship and tram

### ISSUE THREAD

**Issue by DeActiveDev** [TrinityCore/TrinityCore#17904] opened 2016-09-05 16:43 UTC
**Description**: Any  Airship or tram can't move Player or Creature Npc's and can't Player landing

**Current behaviour**: ship or tram move , but can't carry companions
![wowscrnshot_090516_202750](https://cloud.githubusercontent.com/assets/11397660/18253766/c4933024-73ac-11e6-8835-3b1fbcd67211.jpg)
![wowscrnshot_090516_211041](https://cloud.githubusercontent.com/assets/11397660/18253859/72ef59d6-73ad-11e6-9226-c487461cff27.jpg)
![wowscrnshot_090516_211004](https://cloud.githubusercontent.com/assets/11397660/18253860/787e9a24-73ad-11e6-9c6d-dab879ceaf49.jpg)

**Branch(es)**: 3.3.5 

**TC hash/commit**: 932d31598d697bd6cdb4f83ec70018e789984948  

**TDB version**:  TDB 335.61+last update

**Operating system**:  win 10

**Comment by Aokromes** [comment] 2016-09-05 16:51
cannot confirm, i can land on transports, dismount and mount without problem.

**Comment by tkrokli** [comment] 2016-09-05 16:52
Part duplicate of [**[Core / Pet] Pets do not follow owner onto transports**](8772) #8772,
part duplicate of [**[3.3.5] Core/Transport - Orgrim's Hammer (not in raid) problem with npc's**](16071) #16071
(general issue with pets, general issue with NPCs moving behind the gunship/airship)

**Closed by tkrokli** 2016-09-05 16:52 UTC

**Comment by DeActiveDev** [comment] 2016-09-05 18:57
yes
 2 day ago Transport.cpp by mistake remove line 67
;`m_goTemplateAddon = sObjectMgr->GetGameObjectTemplateAddon(entry);`
sorry
