### ISSUE TITLE
[3.3.5] Skadi cannons won't fire harpoons.

### ISSUE THREAD

**Issue by DoctorCookie** [TrinityCore/TrinityCore#17909] opened 2016-09-06 10:07 UTC
After the rework on skadi, You get the harpoons from the adds but you won't be able to shoot the cannons with them.
you suppose to be able to shoot skadi out of the dragon.

**Branch(es)**: 3.3.5 

**TC hash/commit**:  59f340b751ba1cc8bd58329db0b16d56933f64f9

**TDB version**:  3.3.5a

**Operating system**:  windows

**Comment by Treeston** [comment] 2016-09-06 10:18
@sirikfoll

**Comment by sirikfoll** [comment] 2016-09-06 13:53
Works for me(clean core at rev 932d31598d69).
Check if you have some custom change on the harpoons gameobject_template..

**Comment by tomlevy** [comment] 2016-09-06 14:14
@sirikfoll Somehow it's working on the first try but when you are getting wipe you can't use them again, 
maybe it's my DB problem but I tried that in 2 different databases.

**Comment by tkrokli** [comment] 2016-09-06 15:39
Could this be a general issue for more than one dungeon on wipe, that some things don't reset properly upon wipe? (Compare with the Violet Hold issue #17880 , where the instance does not reset after a wipe.)

**Comment by sirikfoll** [comment] 2016-09-06 16:10
Still can't reproduce, works for me.

**Comment by Treeston** [comment] 2016-09-06 16:12
no @tkrokli

**Comment by BlackangelWow** [comment] 2016-09-07 04:07
Probably missing Spells of the Object 
What the spells should be?

**Comment by jackpoz** [comment] 2016-09-07 10:23
> but I tried that in 2 different databases.

what's that supposed to mean ? which 2 databases did you try ?

**Comment by Aokromes** [comment] 2016-11-14 16:40
This was fixed months ago no?

**Comment by Aokromes** [comment] 2016-11-26 04:31
No answer after 12d, closing, if this bug is still valid open a new ticket.

**Closed by Aokromes** 2016-11-26 04:31 UTC
Labels: Feedback-WaitingResponse
