### ISSUE TITLE
3.3.5 Warlock Drain Soul - No Soul Shard

### ISSUE THREAD

**Issue by WOW-Reborn** [TrinityCore/TrinityCore#22223] opened 2018-08-04 01:30 UTC
**Description:**

Warlock Drain Soul does not grant a soul shard upon killing a creature that grants XP.

**Current behaviour:**

Currently when you use Drain Soul on a mob that grants XP all you receive is the random soul shard for hitting the mob.  When you kill the mob you do not get a soul shard for its death.

**Expected behaviour:**

You should get a soul shard when a mob dies that grants XP.

**Steps to reproduce the problem:**

1. Play using a warlock with the drain soul spell.
2. Use drain soul on mob when their health is low so that you can kill him while the effect is still going.
3. Mob dies but you didn't get a soul shard.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5cdb53896f89+

**Operating system:** 

Windows Server 2012

**Comment by Pharonax** [comment] 2018-08-04 11:33
Confirmed on rev c48a596c66c075c876c860a7d5c036d033de0b9d

**Comment by WOW-Reborn** [comment] 2018-08-05 16:15
I fixed the bug on my server but I don't know how "trinity core" likes you to post the fixes. 
SpellId	SchoolMask	SpellFamilyName	SpellFamilyMask0	SpellFamilyMask1	SpellFamilyMask2	ProcFlags	SpellTypeMask	SpellPhaseMask	HitMask	AttributesMask	ProcsPerMinute	Chance	Cooldown	Charges
-1120	0	5	1	0	0	65536	1	0	0	1	0	0	0	0

I'm sure something in this isn't right as I am learning myself LOL but it does produce random shards and produce a shard on a mobs death.

**Comment by PolarCookie** [comment] 2018-08-05 21:01
```sql
DELETE FROM `spell_proc` WHERE `SpellId` = -1120;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(-1120, 0, 5, 1, 0, 0, 65536, 1, 2, 0, 1, 0, 0, 0, 0);
```
 
Macro to delete all shards in bag, for testing convenience.
```lua
#show Soul Shard
/run for i=0,4 do for j=1,GetContainerNumSlots(i) do local iID=GetContainerItemID(i,j) if iID~=nil then local name=GetItemInfo(iID) if name =="Soul Shard" then PickupContainerItem(i,j) DeleteCursorItem() end end end end
```

**Comment by illfated** [comment] 2018-08-05 21:28
@WOW-Reborn : as you can see, **PolarCookie** has posted using the SQL format in TrinityCore.
If you want to post similar suggestions in the future, you can use **```sql**  on a line above the SQL code
and finish the code block with 3 back ticks (with no text after) if you need to write normal text below the block.

This is known as GitHub flavored MarkDown:
- https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

**Comment by WOW-Reborn** [comment] 2018-08-05 21:48
Ok thanks :) I'm still learning the proper way to do things. Glad to see at least we got some sort of solution to this issue.

**Comment by hauspie** [comment] 2018-08-07 10:39
Bug and fix confirmed working in revision `5cdb53896f89`

WOW-Reborn If you want, i can try to make a proper pull request on your behalf soon so that your fix can be merged.

**Comment by Aokromes** [comment] 2018-08-07 11:15
sql only fixes don't belongs to pull requests.

**Comment by Keader** [comment] 2018-08-07 11:56
About (https://github.com/TrinityCore/TrinityCore/issues/22223#issuecomment-410547766)
Why delete+insert, if entry already exist?
Why not just update?

**Comment by illfated** [comment] 2018-08-08 18:51
Good point. I am used to only updating existing data, unless we talk about long, complex SAI scripts or many lines of messy data.
TrinityCore rev. 5cdb53896f89 2018-08-02 19:09:40 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
```sql
SELECT * FROM `spell_proc` WHERE `SpellId` = -1120;
```
```
SpellId  SchoolMask  SpellFamilyName  SpellFamilyMask0  SpellFamilyMask1  SpellFamilyMask2  ProcFlags  SpellTypeMask  SpellPhaseMask  HitMask  AttributesMask  ProcsPerMinute  Chance  Cooldown  Charges
-------  ----------  ---------------  ----------------  ----------------  ----------------  ---------  -------------  --------------  -------  --------------  --------------  ------  --------  -------
  -1120           0                0                 0                 0                 0          0              0               0        0               1               0       0         0        0
```
So a more practical `UPDATE` query could look something like this (your codestyle may vary):
```sql
UPDATE `spell_proc`
SET `SpellFamilyName`=5, `SpellFamilyMask0`=1, `ProcFlags`=65536, `SpellTypeMask`=1, `SpellPhaseMask`=2
WHERE `SpellId`= -1120;
```

**Comment by Keader** [comment] 2018-08-11 01:01
Proc flags change? feels like hack :)

**Comment by WOW-Reborn** [comment] 2018-08-11 18:13
Well Keader if you know a better solution i'm all ears.  Like I said I don't know much about Trinitycore so i'm learning this as I go along lol

**Comment by Hir0shi** [comment] 2018-09-13 20:43
Confirm

**Comment by wow-enthusiast** [comment] 2019-10-08 01:58
Somewhere along the line, drain soul got completely broken - no one can get soul shards, no matter how long they drain soul.

**Comment by Jildor** [comment] 2020-03-25 10:04
this still bug? I can't reproduce

**Comment by Rushor** [comment] 2020-03-25 11:11
@Jildor @Killyana 

https://i.imgur.com/vuyvwJQ.jpg

is fixed, can be closed

**Comment by illfated** [comment] 2020-03-25 11:31
> ![Death_Shard](https://user-images.githubusercontent.com/38162891/77532102-7d064700-6e94-11ea-810c-344b2c424765.jpg)
>

Nice. Glad to see that.

**Closed** 2020-03-25 11:31 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Spells
