### ISSUE TITLE
[6.x] Horde Silvermoon Quest Turn-In Issue: Friend of the Sin'dorei

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18062] opened 2016-10-09 16:19 UTC
**Description**: As the title says, to turn in 'Friend of the Sin'dorei', one must possess the 'Head of Dar'Khan' (Item 22653). When I attempted to turn in, the quest box had the reward as 'Currency Token Test Token 4'. See screen shot. http://i.imgur.com/V6aAO8c.jpg Clicking on 'Complete Quest' returns the onscreen error 'The item was not found."

**Current behaviour**: Unable to turn in quest.

**Expected behaviour**: Quest should be turned in, reward given and deleted from quest log. 

**Steps to reproduce the problem**:
1. Kill Dar'Kahn
2. Loot Head
3. Attempt to turn in.

**Branch(es)**: 6.x

**TC hash/commit**:   TrinityCore rev. c676e80 2016-09-29 23:30:47 +0200 (6.x branch) (Unix, Release, Static)

**TDB version**:  6.04

**Operating system**: Windows 10

**Comment by Shauren** [comment] 2016-10-09 16:28
Test after 8fba569cb93e8497b639056fc07fd3f049bac959

**Comment by funjoker** [comment] 2016-10-14 16:23
Quest can be turned in.
Quest is removed from Questlog.

Bugs existing:
No Reputation, No Gold Reward, Item reward is incorrect.
Questwindow doesn't close itself.

**Comment by SnapperRy** [comment] 2016-10-14 18:22
> Quest window doesn't close itself

This bug exists on 3.3.5 branch too.

It is usually caused when the RewardNextQuest is not available to the player. But in this case it is correct. Haven't been able to find the issue yet.

**Comment by tkrokli** [comment] 2016-10-14 19:00
@SnapperRy : could it have anything to do with the issue [**Incorrect sequence of quest objectives in packet SMSG_QUERY_QUEST_INFO_RESPONSE and SMSG_QUEST_GIVER_QUEST_DETAILS**](18061) #18061 ?

**Comment by BahDumbBugs** [comment] 2016-10-15 18:13
Since the bug exists on 3.3.5 branch as well, shouldn't the label be applied to this too? Thanks for the help and insight to everyone so far!

**Comment by tkrokli** [comment] 2016-10-15 19:59
If you mean SnapperRy's comment "This bug exists on 3.3.5 branch too.", that reference is not pointing to this specific quest, only the detail that if you get a quest completion window that will not close when clicking the **[Complete Quest]** button, it is caused by `RewardNextQuest` not being available to the player.

**Comment by Keldo** [comment] 2016-11-16 00:49
You will also notice that this quest is available before **Traitors Destruction** when it should not be until that quest is complete

**Closed** 2016-12-01 16:41 UTC
Labels: Branch-master, Comp-Database, Sub-Quests
