### ISSUE TITLE
Issues with the door of the main boss in Steamvault dungeon

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21484] opened 2018-02-23 01:26 UTC
**Description:**

After activated the two  "Main chamber Access Panel" it doesn't allow the player to enter the main boss room, because the door keeps locked.

**Current behaviour:**
Warlord Kalithresh's room can't be accessed after activating the two "Main chamber Access Panel"

**Expected behaviour:**
Warlord Kalithresh's room should be accessed after activating the two "Main chamber Access Panel"

**Steps to reproduce the problem:**

1. Step Enter Steamvault dungeon
2. Step Kill first boss (Thespia) and use the "Main chamber Access Panel"
3. Step Kill second boss (Mekginner) and use the "Main chamber Access Panel"
4. Step  Try to open Warlord Kalithresh's door

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 

94b5d9b

**TDB version:**  
335.64

**Operating system:** Win 10 x64

**Comment by ariel-** [comment] 2018-02-23 01:33
Duplicate of #21067

**Closed by ariel-** 2018-02-23 01:33 UTC
