### ISSUE TITLE
The Valiant's Challenge: defeating the Argent Champion gives no credit

### ISSUE THREAD

**Issue by Nocturne1501** [TrinityCore/TrinityCore#22210] opened 2018-08-01 02:46 UTC
**Description:**

The Argent Champion in The Valiant's Challenge (Stormwind) does not give credit after being defeated.

**Current behaviour:**

After defeating the Argent Champion, no quest credit is given.

**Expected behaviour:**

Credit should be given for defeating the Argent Champion.

**Steps to reproduce the problem:**

1. .quest add 13699 (The Valiant's Challenge, Stormwind)
2. Fight the Argent Champion
3. Receive no credit, rendering quest unbeatable

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 44819052a743+ 2018-07-26 03:23:06 +0000 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Operating system:**

Ubuntu 18.04

**Comment by illfated** [comment] 2018-08-01 17:58
Is this issue specific to the Alliance side, or is Alliance the only side you have tested?

**Comment by Nocturne1501** [comment] 2018-08-02 06:50
I have only tested this with the quest I listed.

**Comment by illfated** [comment] 2018-08-02 10:58
OK, so Alliance character, then. Going to test if I can reproduce it on Horde side.

**Comment by pedroevil51** [comment] 2018-08-02 12:28
`DELETE FROM `smart_scripts` WHERE (`entryorguid`=33707 AND `source_type`=0);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(33707, 0, 1, 0, 63, 0, 100, 512, 0, 0, 0, 0, 0, 80, 3370700, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Arg Champion - Just created - Call timed actionlist"),
(33707, 0, 2, 0, 52, 0, 100, 0, 0, 33707, 0, 0, 0, 11, 63010, 0, 0, 0, 0, 0, 12, 1, 0, 0, 0, 0, 0, 0, "Arg Champion - On text over - Cast Charge"),
(33707, 0, 3, 0, 0, 0, 100, 0, 0, 0, 1500, 4000, 0, 11, 62544, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "Arg Champion - IC - Cast Thrust"),
(33707, 0, 4, 0, 9, 0, 100, 0, 5, 5, 4000, 7000, 0, 11, 62575, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "Arg Champion - On more than 5 yard range - Cast Shield-Breaker"),
(33707, 0, 5, 0, 0, 0, 100, 0, 9000, 11000, 9000, 10000, 0, 114, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 20, 0, 0, "Arg Champion - IC - Move forward 20 yards"),
(33707, 0, 6, 7, 9, 0, 100, 0, 9, 15, 3000, 3000, 0, 11, 63010, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "Arg Champion - On 10-12 yard range - Cast Charge"),
(33707, 0, 7, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 11, 62575, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "Arg Champion - Linked with previous event - Cast Shield-Breaker"),
(33707, 0, 8, 9, 2, 0, 100, 513, 1, 6, 60000, 60000, 0, 2, 35, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Arg Champion - On HP% between 1% and 6% - Change faction to 35"),
(33707, 0, 9, 10, 61, 0, 100, 512, 0, 0, 0, 0, 0, 45, 0, 1, 0, 0, 0, 0, 10, 85139, 33518, 0, 0, 0, 0, 0, "Arg Champion - On HP% between 1% and 6% - set data"),
(33707, 0, 10, 11, 61, 0, 100, 512, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 21, 50, 0, 0, 0, 0, 0, 0, "Arg Champion - Linked with previous event - Say text"),
(33707, 0, 11, 0, 61, 0, 100, 512, 0, 0, 0, 0, 0, 41, 3000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Arg Champion - Linked with previous event - Despawn in 3 sec"),
(33707, 0, 12, 13, 5, 0, 100, 0, 60000, 60000, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 21, 50, 0, 0, 0, 0, 0, 0, "Arg Champion - On player killed - Say text"),
(33707, 0, 13, 14, 61, 0, 100, 512, 0, 0, 0, 0, 0, 41, 4000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Arg Champion - Linked with previous event - Despawn in 1 ms"),
(33707, 0, 14, 0, 61, 0, 100, 512, 0, 0, 0, 0, 0, 33, 33708, 0, 0, 0, 0, 0, 18, 100, 0, 0, 0, 0, 0, 0, "Credito da quest");`

Maybe a fix? idk if its blizzlike (i just added a killed monster credit)
https://github.com/TrinityCore/TrinityCore/commit/c48a596c66c075c876c860a7d5c036d033de0b9d

**Comment by LluisMas** [comment] 2018-08-02 12:38
@pedroevil51 It's linked to the event named (On player killed) 
And the one we need is (On HP% between 1% and 6%)

**Comment by pedroevil51** [comment] 2018-08-02 13:17
@LluisMas Why player killed would give quest credit? i linked on the despawn, but maybe if we link on event 10 its blizzlike

**Comment by Killyana** [comment] 2018-08-02 13:53
The SAI was working correctly on previous commit, so no need to change it, as the issue is on core side:
Squire Danny  - On gossip select - store target
Arg Champion - On HP% between 1% and 6% - set data to Squire Danny 
Squire Danny  - On data set - Cross cast quest credit on stored target

**Comment by Pharonax** [comment] 2018-08-02 23:34
@Killyana are you suggesting it is the core part of SmartAI? If so, what is it?

**Comment by Killyana** [comment] 2018-08-03 00:09
Maybe https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/SmartScripts/SmartScript.cpp#L1650
I'm not sure.

**Comment by Pharonax** [comment] 2018-08-03 14:54
If it's a core issue in the SmartAI, it would be very gamebreaking

**Comment by Killyana** [comment] 2018-08-03 22:23
The issue is invoker_cast no longer works with the target 12 and 17, 18, 21 (But it works with 7)

**Comment by Pharonax** [comment] 2018-08-04 01:06
@Killyana so basically, if I understand this correctly, you can replace invoker cast with the kill credit action and just replace the target type? If so, why not do this?

Also would action cast_spell with KC spell work in this situation?

**Comment by Killyana** [comment] 2018-08-04 14:01
The SAI is correct and mustn't be changed, changing the spell by a kill credit action is called a hack, you will get a db error, there's 55 SAI line effected by this issue not only this quest:
``` sql
 SELECT * FROM `smart_scripts` WHERE `action_type` IN (85) AND target_type IN (12,17, 18, 21);

**Comment by Killyana** [comment] 2018-08-10 23:27
Closed by https://github.com/TrinityCore/TrinityCore/commit/0df3cb5bcc8097070b1f215032d3914d6a577f01

**Closed by Killyana** 2018-08-10 23:27 UTC
Labels: Branch-3.3.5a, Sub-ScriptingEngine
