### ISSUE TITLE
[Master] Compile error then compile fails

### ISSUE THREAD

**Issue by GreyPaladin** [TrinityCore/TrinityCore#18938] opened 2017-01-23 21:02 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description: Compile Fails at mapextractor**

**Current behaviour: 
Scanning dependencies of target mapextractor
[ 98%] Building CXX object src/tools/map_extractor/CMakeFiles/mapextractor.dir/System.cpp.o
/media/games/wow/6x/core/src/tools/map_extractor/System.cpp: In function ‘bool ConvertADT(const string&, const string&, int, int, uint32)’:
/media/games/wow/6x/core/src/tools/map_extractor/System.cpp:665:53: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             if (*((uint64*)holes[mcnk->iy][mcnk->ix]) != 0)
                                                     ^
[ 98%] Building CXX object src/tools/map_extractor/CMakeFiles/mapextractor.dir/DB2.cpp.o
[ 98%] Building CXX object src/tools/map_extractor/CMakeFiles/mapextractor.dir/loadlib.cpp.o
[ 98%] Linking CXX executable mapextractor
../../../dep/CascLib/libcasc.a(CascDecompress.cpp.o): In function `CascDecompress(unsigned char*, unsigned int*, unsigned char*, unsigned int)':
CascDecompress.cpp:(.text+0x5f): undefined reference to `inflateInit_'
CascDecompress.cpp:(.text+0x96): undefined reference to `inflate'
CascDecompress.cpp:(.text+0xa0): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
src/tools/map_extractor/CMakeFiles/mapextractor.dir/build.make:161: recipe for target 'src/tools/map_extractor/mapextractor' failed
make[2]: *** [src/tools/map_extractor/mapextractor] Error 1
CMakeFiles/Makefile2:2241: recipe for target 'src/tools/map_extractor/CMakeFiles/mapextractor.dir/all' failed
make[1]: *** [src/tools/map_extractor/CMakeFiles/mapextractor.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2** 

**Branch(es): Master** 

**TC rev. hash/commit: 7b43adc**  

**TDB version: TDB_full_703.00_2016_10_17**  

**Operating system: Ubuntu 16.04.1 LTS**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment] 2017-01-23 21:37
https://travis-ci.org/TrinityCore/TrinityCore/builds/194549345 (Commit 7b43adc)

Status: https://github.com/TrinityCore/TrinityCore/blob/master/README.md

It compiles in debian with clang, so it is most likely something in your setup.
Use help sources like https://community.trinitycore.org/forum/5-help-and-support/
or ask in IRC: #trinity @ irc.rizon.net (Rules: https://trinitycore.atlassian.net/wiki/display/tc/IRC)

**Comment by Keldo** [comment] 2017-01-23 22:05
Fresh compile on Debian 8 x64 at 12am PST (US), success, if you are not using the tools on your Linux server then I recommend shutting the tools off in Cmake before you compile.

**Comment by tkrokli** [comment] 2017-01-23 23:13
Closing this because the "issue" is not caused by the TC source per se.

**Closed by tkrokli** 2017-01-23 23:13 UTC
