### ISSUE TITLE
Core/Movement: movement delay is too high

### ISSUE THREAD

**Issue by Seyden** [TrinityCore/TrinityCore#19271] opened 2017-03-10 12:04 UTC
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Movement delay is too high.

**Current behaviour:**

Actually if you open 2 wow clients at the same time and you move with one of them.. you will see the huge delay.

As example.. if you would use a spell that gives you an animation.. the animation would be instant visible for the other client.. but the movement that should be handled with the animation is not sync

**Steps to reproduce the problem:**

1. Open 2 WoW clients
2. Move with one of the characters
3. Look at the delay when the character moves in the other wow process

**Branch(es):** master

**TC rev. hash/commit:**  6067d19dfc43f40590a2052d3ce9b75a14920aa3

**Operating system:** Windows Server 2012 R2

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Eredar** [comment] 2017-03-10 14:28
Tested it and it's not too high. For some reason it says 9-12 ms ping on localhost and actually it looks like that. For example other Blizzard game Overwatch has way more bad sync with 50 ms ping.

**Comment by Seyden** [comment] 2017-03-10 14:32
i don't talk about the ping.. try knockback or just move forward and backward.. i will make a video later

**Comment by Eredar** [comment] 2017-03-10 14:37
Reported knockback in other issue. It has delay only for caster. But not sure about movement, for me it seems fine.

**Comment by Seyden** [comment] 2017-03-10 14:55
Knockback doesn't have delay for caster.. the caster sees the delay correct.. all other players not.. but its not only knockback

**Comment by Eredar** [comment] 2017-03-10 15:10
Looks like we have different cores XD Because typhoon target was knocked back instantly for me and seen only half way in the air for caster. Use it on other player, not npc.

**Comment by Seyden** [comment] 2017-03-10 15:36
Wait wait.. you have to knock yourself back while looking on the other client.

**Comment by streetrat** [comment] 2017-03-10 18:24
in WorldSession::HandleMovementOpcode
try to comment out this line
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Handlers/MovementHandler.cpp#L386
`movementInfo.time = movementInfo.time + m_clientTimeDelay + MOVEMENT_PACKET_TIME_DELAY;`
and see if anything changed

**Comment by Takenbacon** [comment] 2017-03-11 01:13
When you first login movement is usually a bit delayed (assuming it has something to do with client interpolation calculation), wait about a minute before checking it.

**Comment by Palabola** [comment] 2017-03-11 08:49
Delay exists, and it has some connection with Speed update, if a player got new speed any speed or effect like knockback it can be desynced for other clients. 
It can be reproduced with .mod speed command aswell.

**Comment by Seyden** [comment] 2017-03-12 11:30
@Takenbacon thats what i saw to.. but if you do something with a special movement, the movement gets a delay again xD after sometime, the delay is gone and your movement is instant again..

@streetrat already tried to out comment it.. didn't helped :/

@Palabola oh ok,, didn't checked this

**Comment by Seyden** [comment] 2017-03-12 12:27
https://www.youtube.com/watch?v=VxJkjRP_xUs

That video is with this line being commented out

`movementInfo.time = movementInfo.time + m_clientTimeDelay + MOVEMENT_PACKET_TIME_DELAY;`

Look specially at the first 15-20 seconds and after that at 3:50

**Comment by P-Kito** [comment] 2017-03-14 03:00
Wtf 2 seconds delay Oô

**Comment by Seyden** [comment] 2017-03-14 20:29
Summons @Shauren

**Comment by chaodhib** [comment] 2017-03-31 22:22
The 3.3.5 branch has the same issue. The issue is indeed related to the timestamp field inside the movement packets. This field (and the concept behind it) is currently not well understood. [This PR ](https://github.com/TrinityCore/TrinityCore/pull/18189) is also linked to the issue. Progress is slow though.

**Comment by Seyden** [comment] 2017-07-28 08:30
push.. the delay is way bigger than tought..

**Comment by Langerz82** [comment] 2018-01-25 06:43
Not sure if this will help, but it takes an average of defined samples and adds it onto the timer, rather than individual values which may have lag spikes.

See:
https://gist.github.com/Langerz82/264ecae42b007f22c468cf4316b7b77e

**Comment by Langerz82** [comment] 2018-01-25 22:59
I made it load the movement packets super fast right away, but it's clipping, see if i can get it stable.

**Comment by Langerz82** [comment] 2018-01-30 12:46
Fuck so excited think I got it working. I'll send the patch once I am done. How do I do a second PR without affecting one already waiting?

**Comment by tje3d** [comment] 2018-01-30 12:49
@Langerz82 You need new branch that track's TrinityCore/TrinityCore -> 3.3.5

**Comment by chaodhib** [comment] 2018-01-30 12:50
Just submit what you got for review. The other PR (if you are

**Comment by chaodhib** [comment] 2018-01-30 12:50
Just submit what you got for review. The other PR (if you are ta

**Comment by Langerz82** [comment] 2018-01-30 12:53
Here is the gist:
https://gist.github.com/Langerz82/77770f68f55a9d0f6ed6b97d6e539817

**Comment by Langerz82** [comment] 2018-06-20 03:11
It was shown only 1 extra packet is needed to sync the client so I'll make a patch later today that condenses the code.

**Comment by Seyden** [comment] 2018-06-20 06:30
Why I didn't see your comments :o and btw... are you sure that this spamMovement is correct ?

**Comment by Langerz82** [comment] 2018-06-20 07:20
It's code is over the top for what it needs to do. I will be making a much shorter patch and PR it for it to be discussed and tested properly. My advice best wait till my new patch comes out and do not use it on a production server until it's committed.

**Comment by Langerz82** [comment] 2018-06-20 07:31
Here is the revised patch I will be submitting for PR (in-case you want to test early).

https://gist.github.com/Langerz82/9a894c226710da08af1ccfa22c0490b0

**Comment by Langerz82** [comment] 2018-07-22 12:17
The following code only sends a heartbeat to other players in the map when the player has changed to one. This will hopefully sync the clients without messing with packet flooding etc.
Needs testing, I couldnt de-sync my clients on the latest 335 version even with 3 clients (my computer is beast).

```diff
diff --git a/src/server/game/Handlers/MovementHandler.cpp b/src/server/game/Handlers/MovementHandler.cpp
index dd8f9bd94c..a47fc0e541 100644
--- a/src/server/game/Handlers/MovementHandler.cpp
+++ b/src/server/game/Handlers/MovementHandler.cpp
@@ -104,6 +104,22 @@ void WorldSession::HandleMoveWorldportAck()
         return;
     }
 
+    // Send a heartbeat to all players in the map to sync clients.
+    /*Map::PlayerList const& players = GetPlayer()->GetMap()->GetPlayers();
+    if (!players.isEmpty())
+    {
+        for (Map::PlayerList::const_iterator it = players.begin(); it != players.end(); ++it)
+        {
+            Player* target = it->GetSource();
+            if (target && target->IsInWorld())
+            {
+                WorldPacket* data;
+                GetPlayer()->BuildHeartBeatMsg(data);
+                target->GetSession()->SendPacket(data);
+            }
+        }
+    }*/
+
     // battleground state prepare (in case join to BG), at relogin/tele player not invited
     // only add to bg group and object, if the player was invited (else he entered through command)
     if (_player->InBattleground())
```

**Comment by chaodhib** [comment] 2019-04-06 12:28
Please test again once https://github.com/TrinityCore/TrinityCore/pull/18189 is merged and give me your feedback.

**Comment by chaodhib** [comment] 2019-04-16 20:27
The PR has been merged now. Please test again.

**Comment by Killyana** [comment] 2019-04-16 21:21
The delay is approximately 500ms, so works as intended.

**Comment by chaodhib** [comment] 2019-04-17 22:08
Good news! I'll wait for more feedback before closing this issue.

**Comment by Sorikoff** [comment] 2019-04-19 07:56
I can confirm movement is way more smooth than before.

**Comment by chaodhib** [comment] 2019-04-21 20:44
Nice! Closing the issue since it seems solved now. Will re-open if needed.

**Closed by chaodhib** 2019-04-21 20:44 UTC
Labels: Branch-3.3.5a, Branch-master, Comp-Core, Sub-Movement
