### ISSUE TITLE
Boss/Script: Rotface

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23799] opened 2019-09-15 19:42 UTC
**Description:** After Rotface encounter players will remains in combat with Entry: 37013
Puddle Stalker

**Steps to reproduce the problem:**

1. .go c id 36627
2. start the combat and go inside the green goo
3. Kill the boss
4. You will remain in combat with some triggers:
Combat refs: (Combat state: 1 | Manager state: 1)
[PvE] Puddle Stalker (SpawnID 201653)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 215a6cee2489

**Comment by RR2739-VCN** [comment] 2019-09-16 23:35
Confirmed. You will remain in combat until you relog or gm clears your combat.

**Comment by illfated** [comment] 2019-09-17 20:31
Is this regardless of normal/heroic and 10/25 man modes?

**Comment by OcelotGear** [comment] 2019-11-05 20:02
@illfated yes

**Comment by Jildor** [comment] 2019-11-05 20:39
Then should be fixed like kologarn https://github.com/TrinityCore/TrinityCore/pull/23866

**Comment by OcelotGear** [comment] 2019-11-06 00:01
With that method if you enter the flood when the boss has already died, you turn back into combat.

**Comment by Jildor** [comment] 2019-11-06 14:04
So those triggers should be despawned when rotface die?

**Comment by Killyana** [comment] 2019-11-06 14:17
If you kill Rotface and get stuck in combat with this triggers, go to Festergut and kill it and it will stop the combat, something in Festergut script or Putricide script stop the combat with this npcs triggers once Festergut dies.

**Comment by jackpoz** [comment] 2020-07-19 19:47
are those Puddle Stalkers supposed to be despawned or be passive after Rotface dies or ?

**Comment by offl** [comment] 2020-07-19 19:59
We need to check sniffs, usually we don't despawn triggers and other invisible helpers

**Comment by Shauren** [comment] 2020-07-20 13:19
These triggers are permanently spawned on retail (before and after fight) but they should never enter combat themselves

**Comment by Jildor** [comment] 2020-07-20 15:50
related with: #24156 and #24290
also can happens by example with temp triggers summons like ICC - lanathel Swarming Shadows.
before combat/threat rewrite those NPCs didn't get stuck in combat, I don't know what can be the best way to fix this.

**Comment by jackpoz** [comment] 2020-07-20 16:09
> These triggers are permanently spawned on retail (before and after fight) but they should never enter combat themselves

ah right, that's due to the combat rewrite, right ? a lot of things entering combat when they shouldn't.

**Comment by jackpoz** [comment] 2020-07-20 21:31
Please test https://github.com/TrinityCore/TrinityCore/pull/25086

**Closed** 2020-07-22 18:18 UTC
Labels: Branch-3.3.5a, Comp-C++Script, Sub-Instances
