### ISSUE TITLE
Core/Pet: Voidwalker - Interrupts Spell: 'Consume Shadows' while moving

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#14054] opened 2015-02-06 21:49 UTC
npc=1860
http://www.wowhead.com/spell=36472/

The Voidwalker interrupts alway his cast 'Consume Shadows' if it is currently moving/following it's owner.

Demonstration:
http://youtu.be/rbRdcYri5Wg

How it should be:
Usually it should stay on it's place until it is finished with it's cannelcast.
##

**Comment by Pro100Hens** [comment] 2015-05-13 08:02
confirm

**Comment by dr-j** [comment] 2015-05-13 09:25
Confirmed

**Comment by Rushor** [comment] 2015-05-13 11:49
spellidupdate:
ID - 17767 Schatten verzehren (Rang 1)

**Comment by Rushor** [comment] 2015-05-13 13:27
hackfix, but it solves the problem: https://gist.github.com/Rushor/86d626a93dac2edde3bd

**Comment by MartinBT** [comment] 2015-05-16 09:45
I am not proficient regarding Trinity but logically in the core this should be fixed in Spell.cpp in this method void Spell::handle_immediate(), where on channeling a spell checking if it's a pet and stoping it's movement etc.

**Comment by Warpten** [comment] 2015-05-16 12:39
No.

**Comment by immvp** [comment] 2015-05-21 10:45
Confirm

**Comment by Kittnz** [comment] 2015-05-26 20:00
i tested this and my pet stays when casting consume shadows
db3b22c63e7efcce9871f116b2eacd721d71490b

**Comment by Nyeriah** [comment] 2015-05-26 21:37
@Kittnz It works fine if you cast it while the pet is still but if you're moving then it interrupts itself (at least that's what I have been experiencing)

**Comment by Nyeriah** [comment] 2015-05-26 22:23
@Rushor I tried your script and it works (but needs few changes in order for it to work). Firstly you're missing overrides in the Register() methods, secondly the SpellEffects change at later ranks of this spell so it won't work for ranks 8 and 9. You need to change the aura removal hook to EFFECT_0 - SPELL_AURA_PERIODIC_HEAL, then it works with every rank.

**Comment by Rushor** [comment] 2015-05-26 22:44
https://gist.github.com/Rushor/3756ff7e6ab0e45ad8a9
override still missing
i changed it some time ago for the triggered spell, same result actually

**Comment by Nyeriah** [comment] 2015-05-26 23:16
I went with https://gist.github.com/Nyeriah/ce980bfefcd638403fa1 as then I don't need a second entry for the stealth aura and still it'd work with every rank

**Comment by robinsch** [comment] 2015-05-27 20:41
```diff

diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 94bb904..9df23c8 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -3260,6 +3260,10 @@ void Spell::handle_immediate()
             m_caster->AddInterruptMask(m_spellInfo->ChannelInterruptFlags);
             SendChannelStart(duration);
         }
+
+        // interrupt movement at channeled spells for creature case
+        if (m_caster->GetTypeId() == TYPEID_UNIT && m_caster->isMoving())
+            m_caster->StopMoving();
     }
 
     PrepareTargetProcessing();

**Comment by tkrokli** [comment] 2015-05-28 10:49
Would you like a PR on https://github.com/TrinityCore/TrinityCore/issues/14054#issuecomment-106067096 or does it need more testing to confirm that it is safe to use?

**Comment by tkrokli** [comment] 2016-01-13 23:46
The label [Feedback-PatchFix] is no longer accurate. The suggested fix got outdated and deprecated.

**Comment by tkrokli** [comment] 2016-05-13 21:13
Looks like Keader's PR [**Core/Movement: Fix issues where creatures cancel spell casts chasing target and Implement SPELL_ATTR5_CAN_CHANNEL_WHEN_MOVING**](https://github.com/TrinityCore/TrinityCore/pull/17037) #17037 could be interesting.

**Comment by Kittnz** [comment] 2016-05-14 08:11
Any update since 2ae85d86d3d1c6a465f9382ec31f6649afa4326c ?

**Comment by tkrokli** [comment] 2016-05-14 14:51
Not unless you count Keader's latest PR (top of the list in https://github.com/TrinityCore/TrinityCore/pulls) which isn't merged yet (removal of `ClearUnitState(UNIT_STATE_CASTING);` for some cases).
I just mentioned #17037 (2ae85d8) in case it could be useful in this issue.

**Closed** 2016-11-02 22:17 UTC
Labels: Comp-Core, Feedback-PatchFix, Sub-Spells
