### ISSUE TITLE
[3.3.5][6.x] DB/Quest: There Exists No Honor Among Birds

### ISSUE THREAD

**Issue by Kodekc** [TrinityCore/TrinityCore#16921] opened 2016-04-06 09:46 UTC
http://www.wowhead.com/quest=11470/there-exists-no-honor-among-birds
http://www.wowhead.com/item=34124/trained-rock-falcon
http://www.wowhead.com/npc=24783/trained-rock-falcon
http://wotlk.openwow.com/object=190222
http://wotlk.openwow.com/object=186946
World of Warcraft Quest Guide: https://www.youtube.com/watch?v=EpqOQFo-4Fw&feature=youtu.be

.quest add 11470
.go object 55419
use quest item

- Quest is made, but does not work correctly. Eggs can be collected simply by pressing the number "1" in the management of a falcon on the spot. Even to fly do not need to in nests. Falcon flies,crawls on the ground)
- Fjord Hawk Egg not despawn after use
- Need add waypoints to http://www.wowhead.com/npc=24787/fjord-hawk-matriarch

Branch: 3.3.5
TC hash/commit: ef7a91d
TDB version: 335.60

**Comment by dr-j** [comment] 2016-04-06 12:08
https://github.com/TrinityCore/TrinityCore/issues/16191

**Comment by dr-j** [comment] 2016-04-08 18:50
Well seems these eggs just will not despawn even if you activate guid with command nothing at all happens egg stays visible to players

:~~~
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN(17) AND `SourceEntry`= 44422;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(17,0,44422,0,0,30,0,186946,5,0,0,0,0,'',"Spell 'Scavenge' target GameObject 'Fjord Hawk Egg'");
~~~

Prevents the spell from being cast if no egg is present but does not stop been used multiple times on same egg

**Comment by Kodekc** [comment] 2016-04-14 20:51
Perhaps useful
[21463_2016-04-14_23-33-45_02E2C59E_parsed.txt](https://github.com/TrinityCore/TrinityCore/files/219930/21463_2016-04-14_23-33-45_02E2C59E_parsed.txt)

**Comment by dr-j** [comment] 2016-04-14 21:57
we already have sniffs of this quest but nothing particulary useful to fix this.

When the second spell effect of the Scavenge spell hits the gameobject it should show despawn animation and despawn.  The spell effect of the spell on the egg is activate gameobject, nearby entry, no target cant tell if the spell does in fact hit the egg or not since seems these eggs cannot be despawned on tc (not even when activated via .gobject activate.

Also another thing which does in fact point towards missing data is that on retail (even in 7 year old video of this quest) these eggs glitter to say they are part of quest but on tc there is no sparkle and every sniff of these eggs I have seen so far just has same data as what is already in db.  Whats even stranger about these gos is that they are type 3 chest even though are not lootable and have no data in loot tables.

**Comment by Kodekc** [comment] 2016-04-14 22:08
```sql
-- Rework spawn gameobject Fjord Hawk Egg

SET @OGUID := ; -- The choice trinity team

DELETE FROM `gameobject` WHERE  `id`=186946;
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES 
(@OGUID, 186946, 571, 0, 0, 1, 1, 509.4861, -6098.01, 291.9964, 2.146753, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+1, 186946, 571, 0, 0, 1, 1, 407.5395, -6107.578, 240.9682, 4.398232, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+2, 186946, 571, 0, 0, 1, 1, 466.4106, -6104.29, 249.9144, 0.6283169, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+3, 186946, 571, 0, 0, 1, 1, 535.6348, -6106.879, 251.0206, 5.061456, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+4, 186946, 571, 0, 0, 1, 1, 401.5692, -6083.999, 291.5049, 3.647741, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+5, 186946, 571, 0, 0, 1, 1, 352.8478, -6034.293, 294.8475, 2.775069, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+6, 186946, 571, 0, 0, 1, 1, 366.45, -6065.836, 251.2561, 5.654869, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+7, 186946, 571, 0, 0, 1, 1, 389.8568, -6107.326, 185.4172, 4.363324, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+8, 186946, 571, 0, 0, 1, 1, 350.9662, -6067.787, 200.9692, 2.495818, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+9, 186946, 571, 0, 0, 1, 1, 437.9177, -6138.564, 170.1889, 3.612838, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+10, 186946, 571, 0, 0, 1, 1, 490.1093, -6141.555, 140.8691, 2.722713, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+11, 186946, 571, 0, 0, 1, 1, 533.775, -6132.441, 141.2471, 3.38594, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+12, 186946, 571, 0, 0, 1, 1, 559.9716, -6103.84, 293.4162, 3.543024, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+13, 186946, 571, 0, 0, 1, 1, 328.7657, -6049.496, 184.5204, 6.230826, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+14, 186946, 571, 0, 0, 1, 1, 349.9867, -5966.508, 289.8404, 0.1396245, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+15, 186946, 571, 0, 0, 1, 1, 357.0147, -6111.493, 93.49896, 2.234018, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+16, 186946, 571, 0, 0, 1, 1, 315.6613, -6069.47, 81.00819, 4.310966, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+17, 186946, 571, 0, 0, 1, 1, 333.6173, -5967.8, 256.1725, 5.235988, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+18, 186946, 571, 0, 0, 1, 1, 310.1069, -6000.228, 245.1931, 1.256636, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+19, 186946, 571, 0, 0, 1, 1, 407.5395, -6107.578, 240.9682, 4.398232, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+20, 186946, 571, 0, 0, 1, 1, 565.6453, -6168.584, 74.99892, 0.1919852, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+21, 186946, 571, 0, 0, 1, 1, 522.453, -6164.119, 75.93553, 0.7330382, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+22, 186946, 571, 0, 0, 1, 1, 542.2305, -6192.157, 30.81212, 5.218536, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+23, 186946, 571, 0, 0, 1, 1, 592.9944, -6111.055, 239.2773, 4.468043, 0, 0, 0, 1, 120, 255, 1, 0),
(@OGUID+24, 186946, 571, 0, 0, 1, 1, 630.7746, -6143.756, 159.4507, 5.602507, 0, 0, 0, 1, 120, 255, 1, 0);
```
Now there are 19 (Coordinates all wrong), should be 25.

**Comment by dr-j** [comment] 2016-04-14 22:28
well theres 19 eggs in tc database, I have 26 in sniff I did back in 2014 but seems different sniffs have different amounts and spawn positions maybe these should be pooled as with quiet a few others gos and creatures.

Anyway spawns will not fix any of the issues with this quest since as it stands at the moment there does not need to be a single egg spawned as you can use the scavenge spell without the need for a single egg and even if conditioned so item can only be used while near go can still be spammed

But I suspect the gameobject template entry itself is missing data even though in every sniff I have checked data for the egg object is same as we already have in db but in retail video of this quest these sparkle when on this quest as other quest objects do but on tc there is no sparkle on these eggs when on quest, also when activated on tc these do not despawn, check yourself via .gobject activate [guid of egg]

**Comment by tkrokli** [comment] 2016-04-14 22:33
Is it possible in any way that the sniffs could be wrong or incomplete, that the eggs should be a specific quest object and not a chest object? (I don't know, I am just guessing from reading your descriptions.)

**Comment by sirikfoll** [comment] 2016-04-14 23:19
If someone makes the pool for the objects, code below should fix all the problems, otherwise, the object will not respawn.
```sql
DELETE FROM `creature_template_addon` WHERE `entry`=24783;
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(24783, 0, 0, 0, 1, 0, 43775);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN(13,17) AND `SourceEntry`=44422;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(17,0,44422,0,0,30,0,186946,5,0,0,0,0,'',"Spell 'Scavenge' target GameObject 'Fjord Hawk Egg'"),
(13,1,44422,0,0,31,0,5,186946,0,0,0,0,'',"Spell 'Scavenge' target GameObject 'Fjord Hawk Egg'");

DELETE FROM `spell_script_names` WHERE `spell_id`=44422;
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(44422, 'spell_q11470_scavenge');
```
```cpp
class spell_q11470_scavenge: public SpellScriptLoader
{
    public:
        spell_q11470_scavenge() : SpellScriptLoader("spell_q11470_scavenge") { }

        class spell_q11470_scavenge_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_q11470_scavenge_SpellScript);

            void HandleActiveObject(SpellEffIndex effIndex)
            {
                PreventHitDefaultEffect(effIndex);
                GetHitGObj->Delete();
            }

            void Register() override
            {
                OnEffectHitTarget += SpellEffectFn(spell_q11470_scavenge_SpellScript::HandleActiveObject, EFFECT_0, SPELL_EFFECT_ACTIVATE_OBJECT);
            }
        };

        SpellScript* GetSpellScript() const override
        {
            return new spell_q11470_scavenge_SpellScript();
        }
};

**Comment by Kodekc** [comment] 2016-04-14 23:29
```sql
-- Fjord Hawk Matriarch
UPDATE `creature_template` SET `InhabitType`='5' WHERE  `entry`=24787;
-- Pathing for Entry: 24787 'TDB FORMAT' 
SET @NPC := 115835;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=491.5974,`position_y`=-6158.39,`position_z`=144.1042 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,491.5974,-6158.39,144.1042,0,0,1,0,100,0),
(@PATH,2,509.5939,-6162.629,111.2709,0,0,1,0,100,0),
(@PATH,3,526.574,-6162.785,95.60418,0,0,1,0,100,0),
(@PATH,4,574.4791,-6163.997,95.60418,0,0,1,0,100,0),
(@PATH,5,603.0228,-6169.135,135.1598,0,0,1,0,100,0),
(@PATH,6,621.6965,-6158.342,152.5963,0,0,1,0,100,0),
(@PATH,7,637.6,-6155.499,154.6354,0,0,1,0,100,0),
(@PATH,8,663.0421,-6125.693,179.4132,0,0,1,0,100,0),
(@PATH,9,656.72,-6138.115,215.4652,0,0,1,0,100,0),
(@PATH,10,639.1322,-6143.215,215.4652,0,0,1,0,100,0),
(@PATH,11,618.7733,-6150.35,208.0208,0,0,1,0,100,0),
(@PATH,12,588.9388,-6145.327,208.0208,0,0,1,0,100,0),
(@PATH,13,554.6487,-6152.367,187.5208,0,0,1,0,100,0),
(@PATH,14,528.2413,-6138.124,166.6597,0,0,1,0,100,0),
(@PATH,15,497.937,-6157.058,187.5208,0,0,1,0,100,0),
(@PATH,16,482.7061,-6146.376,174.6875,0,0,1,0,100,0),
(@PATH,17,491.5974,-6158.39,144.1042,0,0,1,0,100,0);

-- Pathing for Entry: 24787 'TDB FORMAT' 
SET @NPC := 115836;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=520.6224,`position_y`=-6137.84,`position_z`=169.3022 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,520.6224,-6137.84,169.3022,0,0,1,0,100,0),
(@PATH,2,539.8384,-6131.232,149.1912,0,0,1,0,100,0),
(@PATH,3,520.709,-6158.917,160.4134,0,0,1,0,100,0),
(@PATH,4,485.8767,-6155.685,160.4134,0,0,1,0,100,0),
(@PATH,5,438.8145,-6158.287,160.4134,0,0,1,0,100,0),
(@PATH,6,419.3206,-6156.742,160.4134,0,0,1,0,100,0),
(@PATH,7,390.6546,-6143.165,160.4134,0,0,1,0,100,0),
(@PATH,8,377.2733,-6114.98,160.4134,0,0,1,0,100,0),
(@PATH,9,383.0898,-6128.999,185.83,0,0,0,1,100,0),
(@PATH,10,417.4906,-6154.904,185.83,0,0,1,0,100,0),
(@PATH,11,452.2428,-6147.803,185.83,0,0,1,0,100,0),
(@PATH,12,497.4655,-6150.674,185.83,0,0,1,0,100,0),
(@PATH,13,520.6224,-6137.84,169.3022,0,0,1,0,100,0);

-- Pathing for Entry: 24787 'TDB FORMAT' 
SET @NPC := 115837;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=596.8774,`position_y`=-6114.975,`position_z`=271.1343 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,596.8774,-6114.975,271.1343,0,0,1,0,100,0),
(@PATH,2,595.4591,-6109.405,278.3748,0,0,1,0,100,0),
(@PATH,3,571.2776,-6109.743,290.4025,0,0,1,0,100,0),
(@PATH,4,556.7193,-6108.814,297.3566,0,0,1,0,100,0),
(@PATH,5,517.0029,-6104.844,297.3566,0,0,1,0,100,0),
(@PATH,6,503.9214,-6117.692,297.3566,0,0,1,0,100,0),
(@PATH,7,466.3313,-6107.801,271.1343,0,0,1,0,100,0),
(@PATH,8,475.6375,-6120.523,271.1343,0,0,1,0,100,0),
(@PATH,9,500.4033,-6130.543,271.1343,0,0,1,0,100,0),
(@PATH,10,542.1522,-6114.92,271.1343,0,0,1,0,100,0),
(@PATH,11,567.1166,-6129.524,271.1343,0,0,1,0,100,0),
(@PATH,12,596.8774,-6114.975,271.1343,0,0,1,0,100,0);

-- Pathing for Entry: 24787 'TDB FORMAT' 
SET @NPC := 115843;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=290.8945,`position_y`=-6070.151,`position_z`=84.36917 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,290.8945,-6070.151,84.36917,0,0,1,0,100,0),
(@PATH,2,273.076,-6034.628,84.36917,0,0,1,0,100,0),
(@PATH,3,268.3575,-6009.71,121.8221,0,0,1,0,100,0),
(@PATH,4,282.7736,-6034.701,150.6469,0,0,1,0,100,0),
(@PATH,5,297.921,-6060.3,111.1191,0,0,1,0,100,0),
(@PATH,6,324.4433,-6101.173,115.008,0,0,1,0,100,0),
(@PATH,7,351.7174,-6115.625,115.008,0,0,1,0,100,0),
(@PATH,8,380.059,-6146.51,102.4525,0,0,1,0,100,0),
(@PATH,9,381.592,-6162.233,80.36916,0,0,1,0,100,0),
(@PATH,10,363.2276,-6145.913,80.36916,0,0,1,0,100,0),
(@PATH,11,338.3981,-6105.44,80.36916,0,0,1,0,100,0),
(@PATH,12,319.2164,-6096.714,84.36917,0,0,1,0,100,0),
(@PATH,13,290.8945,-6070.151,84.36917,0,0,1,0,100,0);

-- Pathing for Entry: 24787 'TDB FORMAT' 
SET @NPC := 115845;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=360.9156,`position_y`=-6061.682,`position_z`=302.8403 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,360.9156,-6061.682,302.8403,0,0,1,0,100,0),
(@PATH,2,389.247,-6078.495,302.8403,0,0,1,0,100,0),
(@PATH,3,392.2037,-6094.839,296.007,0,0,1,0,100,0),
(@PATH,4,374.589,-6096.534,288.5903,0,0,1,0,100,0),
(@PATH,5,358.6935,-6082.393,274.9237,0,0,1,0,100,0),
(@PATH,6,338.8949,-6049.761,274.9237,0,0,1,0,100,0),
(@PATH,7,320.3495,-6021.407,274.9237,0,0,1,0,100,0),
(@PATH,8,306.0276,-5998.132,285.257,0,0,1,0,100,0),
(@PATH,9,313.4884,-5983.751,285.2291,0,0,1,0,100,0),
(@PATH,10,320.7385,-5972.151,286.1277,0,0,1,0,100,0),
(@PATH,11,330.6828,-6007.996,302.8403,0,0,1,0,100,0),
(@PATH,12,349.4529,-6033.62,302.8403,0,0,1,0,100,0),
(@PATH,13,360.9156,-6061.682,302.8403,0,0,1,0,100,0);

-- Pathing for Entry: 24787 'TDB FORMAT' 
SET @NPC := 115844;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=389.949,`position_y`=-6113.926,`position_z`=217.1557 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,389.949,-6113.926,217.1557,0,0,1,0,100,0),
(@PATH,2,365.9727,-6083.048,249.1279,0,0,1,0,100,0),
(@PATH,3,348.9503,-6058.797,249.1279,0,0,1,0,100,0),
(@PATH,4,334.4755,-6041.239,249.1279,0,0,1,0,100,0),
(@PATH,5,306.4679,-6010.077,240.8223,0,0,1,0,100,0),
(@PATH,6,305.4742,-6011.148,217.1557,0,0,1,0,100,0),
(@PATH,7,308.0244,-6019.713,217.1557,0,0,1,0,100,0),
(@PATH,8,331.7084,-6052.974,217.1557,0,0,1,0,100,0),
(@PATH,9,350.9348,-6071.563,217.1557,0,0,1,0,100,0),
(@PATH,10,371.7133,-6102.678,217.1557,0,0,1,0,100,0),
(@PATH,11,389.949,-6113.926,217.1557,0,0,1,0,100,0);

**Comment by Kodekc** [comment] 2016-04-15 00:34
``` sql
-- Trained Rock Falcon
UPDATE `creature_template` SET `unit_flags`='16810248' WHERE  `entry`=24783;
-- Fjord Hawk Matriarch (Fix model)
UPDATE `creature_model_info` SET `combat_reach`='3' WHERE  `modelid`=22106;

**Comment by Kodekc** [comment] 2016-04-15 12:03
Test 15.04.2016 - The NPC (Trained Rock Falcon) does not fly. Despite the fact that the aura of the flight added

**Comment by sirikfoll** [comment] 2016-04-15 12:07
Sure? i just added the sql that I posted here and it's flying '-'

**Comment by tkrokli** [comment] 2016-04-15 13:58
@Kodekc : if you read my comment containing my test result from February 16 in https://github.com/TrinityCore/TrinityCore/issues/16191#issuecomment-184560788 [**[3.3.5][ 6.x] DB/Creature: Trained Rock Falcon doesn't fly #16191**](16191) you will find that my only problem was that I could not pick up the eggs. Most of the other things worked (flying/controlling the falcon etc.) so I am pretty sure we only need to fix the eggs.

**Comment by Kodekc** [comment] 2016-04-15 14:18
@tkrokli : I think I missed something somewhere kernel upgrade ... I will be very grateful if you help. At the NPC is missing MOVEMENTFLAG_CAN_FLY :-(

**Comment by tkrokli** [comment] 2016-04-15 19:58
Add this SQL code to your `world` DB (the same SQL as I posted in my linked comment) :
```sql
-- add aura 'Flying' to Trained Rock Falcon
DELETE FROM `creature_template_addon` WHERE `entry`= 24783;
INSERT INTO `creature_template_addon` (`entry`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES
(24783, 0, 0, 0, 1, 0, 54422);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`= 17 AND `SourceEntry`= 44422;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(17,0,44422,0,0,31,0,5,186946,0,0,0,0,'',"Spell 'Scavenge' target GameObject 'Fjord Hawk Egg'");
```
If you have added the SQL code you posted higher up on this page to your `world` DB, that is OK too.

**Comment by Kodekc** [comment] 2016-04-17 17:03
@tkrokli : That's all there is. The problem I have is with MOVEMENTFLAG_CAN_FLY for this bird and I can not understand why :-(

.list auras shows flight

**Comment by Kodekc** [comment] 2016-04-27 08:01
What do you think, if the eggs are to translate between phases?

**Comment by tkrokli** [comment] 2016-04-27 11:03
I don't think it is a good idea to use phasing, at least not in 3.3.5, because there is no obvious phases there in retail WoW. Maybe it is easier to use phasing in 6.x (I don't know), but it should not be needed.
BTW, I have not done any testing on this issue since February, so I have to test again later this week.

**Comment by Kodekc** [comment] 2016-05-04 08:16
Are there any news?

**Comment by tkrokli** [comment] 2016-05-04 18:03
Sorry, I have been too busy with my own PRs and other stuff, so I have not been able to focus on getting this tested to see if the contents work as intended. I hope someone else has time to import + test your fixes and give you some feedback in the meanwhile. I had the intention of testing it and reporting back, but I got caught up in lots of other stuff. I encourage others to test your SQL fixes and see if the quest will work as intended or not. Testing and feedback is more than welcome. :-)

**Comment by dr-j** [comment] 2016-05-17 14:57
There are a few gameobjects with this problem on tc (ie seem to be missing despawn state) another example is http://wotlk.openwow.com/object=191136 which never despawns and quest item can be repeatedly spammed on same go, I have checked sniff data on this too and the object despawns as soon as quest credit given and nothing else in sniff so when the shoot comes out that must be despawn animation however on tc these will never despawn or change state (even via gm command)

**Comment by Aokromes** [comment] 2016-05-26 02:36
If the fix here is valid, plz open a PR.

**Comment by sirikfoll** [comment] 2016-05-26 02:42
Only sql fixes here, the one bellow and maybe the pathing part from https://github.com/TrinityCore/TrinityCore/issues/16921#issuecomment-210202046
```sql
DELETE FROM `creature_template_addon` WHERE `entry`=24783;
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(24783, 0, 0, 0, 1, 0, 43775);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN(13,17) AND `SourceEntry`=44422;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(17,0,44422,0,0,30,0,186946,5,0,0,0,0,'',"Spell 'Scavenge' target GameObject 'Fjord Hawk Egg'"),
(13,1,44422,0,0,31,0,5,186946,0,0,0,0,'',"Spell 'Scavenge' target GameObject 'Fjord Hawk Egg'");

**Comment by Kodekc** [comment] 2016-05-26 13:57
damn eggs =)

**Comment by Aokromes** [comment] 2016-06-15 10:46
If nothing else is needed here i will close it tomorrow.

**Comment by Killyana** [comment] 2016-06-15 15:35
Pathing part must be pushed also.

**Closed** 2016-06-18 07:28 UTC
Labels: Branch-3.3.5a, Branch-6.x, Comp-Database, Feedback-PatchFix
