### ISSUE TITLE
Core/Script The spell Drain Soul has a critical issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19662] opened 2017-05-09 03:02 UTC
**Description:**

The spell Drain Soul (ID: 198590) given to Warlock class in the specialization of Affliction, has a critical issue..

Drain Soul (channeled): Drains the target's soul, causing (x) shadow damage over 6 sec, and healing you for 200% of the damage done. Generates 1 Soul Shard if the target dies during this effect.

**Current behaviour:**

The damage done and the healing are working fine, but if the target dies during this effect does not generate a Soul Shard.

PD: This issue makes imposible the testing process of the following spells and talents: Unstable affliction (ID:30108), Contagion (ID: 196105), Seed of corruption (ID: 27243), Summon Doomguard (ID: 18540), Summon Infernal (ID: 1122), Sow of Seeds (ID: 196226), becuase they all need a Soul Shard to be used. Also Summon Demon needs a Soul Shard, affecting the following spells: Health Funnel (ID: 755), Command Demon (ID: 119898), because they need a summoned demon to be used.

**Expected behaviour:**

If the target dies during the effect of Drain Soul, a Soul Shard should be generated.

**Steps to reproduce the problem:**

1. Create a Warlock character.
2. Reach level 13 and choose the specialization of Affliction.
3. Use Drain Soul on an enemy target until it dies.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=198590/drain-soul

**Comment by timsar2** [comment] 2017-07-28 05:36
..., but if the target dies during this effect does not generate a Soul Shard.
warlock must energize like rouge combo pint. no more create sould shards in warlock bag.

**Comment by HannibalRoG** [comment] 2017-07-28 05:42
Use the link to wowhead, according to wowhead the last change was in 7.2.0 and yes it generates 1 Soul Shard if the target dies during this effect.

**Comment by timsar2** [comment] 2017-07-28 05:50
i was create a warlock in blizzard server.warlock has new soul shards system as i said it's like rouge combo point, also add item 6265(soul shards) in TC server and it's not work for spells who need's soul shards.
the spells are deactivate because warlock has no soul shards.

**Comment by gmillerd** [comment] 2017-07-28 06:43
Yes, shard (the power) is not generating with the current system. It has nothing to do with the item soul shard. In modern WoW warlocks are power based.

Please see the variety of other issues related to warlock on master. I believe HannibalRoG knows this has he has reported all the spec issues.

https://github.com/TrinityCore/TrinityCore/issues/17773

Additionally, Warlocks's don't get their rested power levels.

**Comment by timsar2** [comment] 2017-07-29 07:04
i used SetPower(Power_soul_shard,10);  for test.
warlock will generate soul shards and you can cast spell's who need soul.
also in fire talent spell's has 6% chance to generate soul you can test it by cast fire spell

**Comment by matanshukry** [comment] 2021-03-28 16:24
Am I missing something or is this duplicate of #17773 ?

**Closed** 2021-03-28 16:56 UTC
Labels: Branch-master, Sub-Spells
