### ISSUE TITLE
Zeppelin Transportation Issues With Pets

### ISSUE THREAD

**Issue by LewisPotato** [TrinityCore/TrinityCore#21439] opened 2018-02-18 19:14 UTC
**Description:**

A movement issue with pets on Zeppelins.

**Current behaviour:**

When you hop aboard a zeppelin your pet will get on however when the zeppelin starts to move the pet slowly slides off the back and then attempts to try and get back to you then despawns as soon as it starts to go faster.

**Expected behaviour:**

Pets should stay foot on the zeppelin with the owner.

**Steps to reproduce the problem:**

1. Get on a zeppelin or a boat (not tested boats) and then summon a pet such as a warlock or hunter pet.

**Branch(es):**

3.3.5a

**TC rev. hash/commit:** 

TrinityCore rev. adae429aa010 2018-02-13 16:15:27 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  The latest.

**Operating system:** Windows 10

P.S: This also happens with the Traveler's Tundra mount. When you despawn the mount the NPC's fly straight off the back.

**Comment by tkrokli** [comment] 2018-02-18 19:19
Basically the same issue as **[Core / Pet] Pets do not follow owner onto transports** #8772
I suggest closing this issue and posting in #8772.

**Comment by LewisPotato** [comment] 2018-02-18 20:35
Eh just close it if it's already being dealt with (properly). I'm new to the issue tracker system. :-)

**Comment by ariel-** [comment] 2018-02-18 20:49
Duplicate of #8772

**Closed by ariel-** 2018-02-18 20:49 UTC
Labels: Feedback-WaitingResponse
