### ISSUE TITLE
NPC: Bloodmage Lynnore displaying incorrect quest status icon

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25662] opened 2020-11-19 10:51 UTC
**Description:**

Bloodmage Lynnore in Blasted Lands is showing an incorrect quest completion flag when 1 quest is available and 1 is in progress and not ready for turn-in.
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=7506

<details>

![image](https://user-images.githubusercontent.com/66294837/99656084-96f23b00-2ab0-11eb-9b35-67fd58e5a891.png)

</details>

**Expected behaviour:**

NPC should be showing (in this case) quest available icon.

**Steps to reproduce the problem:**

1. Go to Bloodmage Lynnore
2. Take both quests - The Basilisk's Bite and Vulture's Vigor
a) https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=2601
b) https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=2603
3. Complete The Basilisk's Bite only and turn quest in
4. Icon will now display quest ready for turn-in flag - even though it's not

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. cc8287927b9c 2020-11-18 20:09:34 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:** Windows 7 64bit

**Comment by illfated** [comment] 2020-11-19 20:16
Hmm. At first, I thought maybe this had something to do with the mess you get from shared quest item requirements, but this is more about the completed quest not showing up at all in the gossip (from my point of view, at least). Glad you posted this, I can easily go check this out myself, since my character just made it into the upper half of level bracket 50-60.

**Comment by illfated** [comment] 2020-11-19 21:30
Oh well. I can't replicate your findings by doing only what you wrote in the text. The quest completed correctly for me:

<details>
<summary>Details</summary>

![WoWScrnShot_111920_221646](https://user-images.githubusercontent.com/38162891/99725301-31547d80-2ab5-11eb-87a0-438445e1abac.jpg)

</details>

I do not see the quest "[Infallible Mind](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=2602)" offered yet (not sure why, maybe it is because the quest "[The Basilisk's Bite](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=2601)" has not been rewarded yet).

By the way, it looks like you have taken one or more other quests requiring the same type of quest items ([Basilisk Brain](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=8394) required for the quest "[A Boar's Vitality](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=2583)"), which increases the need for more reproduction details this issue.

**Comment by illfated** [comment] 2020-11-19 21:56
I am now trying to compile a list of the same quest items you have in your inventory for the following quests:
- https://classic.wowhead.com/quest=2583/a-boars-vitality
- https://classic.wowhead.com/quest=2603/vultures-vigor

I believe these parts (quests taken, quest items looted) are necessary to complete your list of requirements to reproduce your issue.

BTW, I just turned in [A Boar's Vitality](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=2583) and the quest [Infallible Mind](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=2602) immediately became available to me, so that detail is not an issue at all.

**Comment by illfated** [comment] 2020-11-19 22:39
OK, so I am able to reproduce your issue to some extent:

![WoWScrnShot_111920_233200](https://user-images.githubusercontent.com/38162891/99732290-87c6b980-2abf-11eb-844d-7792d9764e03.jpg)

Note: in addition to your description above, I took the extra quest "[A Boar's Vitality](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=2583)" (ID 2583) listed in your image to get the issue to show up. I also checked that the quest marker above Bloodmage Lynnore did not change into a yellow ❔ before I had collected 8 or 9 [Vulture Gizzards](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=8396), so _the quest item count_ is the real conundrum here.

**Comment by TQPS** [comment] 2020-11-19 23:07
Great pickup.

**Comment by illfated** [comment] 2020-11-20 03:49
Also note: After dropping the quest and retaking it, the quest status shows up correctly. (same rev. hash, https://github.com/TrinityCore/TrinityCore/commit/cc8287927b9c9f0bf20143972fd4d3c338bff688)

**Comment by dr-j** [comment] 2020-12-04 23:44
See https://github.com/TrinityCore/TrinityCore/issues/25603 has I used these quests as an example in a comment I made there

Think its because when you have more than one quest in log and you loot items the count for all quests which require item update simultaneously and when when you turn in a quest does not update quest status of other quests which needed same item when one was turned in or quests are still marked as complete even though you no longer have all required items due to previous turn in

**Comment by illfated** [comment] 2020-12-05 10:42
Good point. Still feels like the act of sorting bag contents can affect that issue even for the first quest hand-in.

**Closed** 2021-07-28 10:06 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Quests
