### ISSUE TITLE
Druid spell - Frenzied Regeneration. Healing ticks should have a chance to crit.

### ISSUE THREAD

**Issue by noszone** [TrinityCore/TrinityCore#24602] opened 2020-05-11 12:35 UTC
**Description:**
Problem spell - Frenzied Regeneration of druid.
It seems it was never did't work.
Periodic healing (tics, hots) from Frenzied Regeneration does not produce a crit tick as per spell crit chance of caster.

a) According to Worldoflogs.com:
http://www.worldoflogs.com/reports/jv7ne5lzf5461ffz/details/0/
Raid log 09/21/2010, druid Juxtaposed, in the Healing by Spell tab and the Healing done table, it is clear that Frenzied Regeneration has crit:
[20:31:36.346] Juxtaposed gains Frenzied Regeneration from Juxtaposed
[20:31:36.346] Juxtaposed casts Frenzied Regeneration
[20:31:37.391] Juxtaposed Frenzied Regeneration Juxtaposed +6524
[20:31:38.328] Juxtaposed Frenzied Regeneration Juxtaposed +5276 (O: 1249)
[20:31:39.330] Juxtaposed Frenzied Regeneration Juxtaposed +*9787*
[20:31:40.347] Juxtaposed Frenzied Regeneration Juxtaposed +*0* (O: 9787)
[20:31:41.363] Juxtaposed Frenzied Regeneration Juxtaposed +0 (O: 6525)
[20:31:42.380] Juxtaposed Frenzied Regeneration Juxtaposed +0 (O: 6524)
[20:31:43.328] Juxtaposed Frenzied Regeneration Juxtaposed +*0* (O: 9787)
[20:31:44.335] Juxtaposed Frenzied Regeneration Juxtaposed +0 (O: 3915)
[20:31:45.334] Juxtaposed Frenzied Regeneration Juxtaposed +6525
[20:31:46.358] Juxtaposed Frenzied Regeneration Juxtaposed +6524
[20:31:46.358] Juxtaposed's Frenzied Regeneration fades from Juxtaposed
[20:35:19.750] Juxtaposed gains Frenzied Regeneration from Juxtaposed
[20:35:19.750] Juxtaposed casts Frenzied Regeneration
[20:35:20.760] Juxtaposed Frenzied Regeneration Juxtaposed +6525
[20:35:21.708] Juxtaposed Frenzied Regeneration Juxtaposed +6554
[20:35:22.698] Juxtaposed Frenzied Regeneration Juxtaposed +*9830*
[20:35:23.705] Juxtaposed Frenzied Regeneration Juxtaposed +*9831*
[20:35:24.711] Juxtaposed Frenzied Regeneration Juxtaposed +6554
[20:35:25.750] Juxtaposed Frenzied Regeneration Juxtaposed +6554
[20:35:26.769] Juxtaposed Frenzied Regeneration Juxtaposed +0 (O: 6554)
[20:35:27.684] Juxtaposed Frenzied Regeneration Juxtaposed +0 (O: 6554)
[20:35:28.703] Juxtaposed Frenzied Regeneration Juxtaposed +0 (O: 6553)
[20:35:29.715] Juxtaposed Frenzied Regeneration Juxtaposed +4610 (O: 1944)
[20:35:29.715] Juxtaposed's Frenzied Regeneration fades from Juxtaposed
Calculation = 6254*1,5=9787. Where 6254 is normal tick and 1.5 is crit multiplier.

b) According to the entry, a Frenzied Regeneration should have a chance of crit.
http://ru.wowhead.com/spell=22842#english-comments
Last comment by Brachamul.

c) Additional resources to check about spell.
1. http://forums.elitistjerks.com/topic/7738-frenzied-regeneration-and-crits/
2. http://www.gamefaqs.com/boards/534914-world-of-warcraft/44289391/485057762
3. https://www.warmane.com/changelog?expansion=2&id=8
4. https://valkyrie-wow.org/boards/index.php?showtopic=1025
Each tick can individually crit, using the Druid's spell crit rate.
The critical ticks use the spell (base) crit multiplier, 1.5.

**Expected behavior:**
Each tick can individually crit, using the Druid's spell crit rate.
The critical ticks use the spell (base) crit multiplier, 1.5.

**Branch(es):**
3.3.5

**TC rev. hash/commit:**
TrinityCore: ecac9d79e359+ 2020-05-03 03:12:34

**Operating system:**
Debian GNU/Linux 10

**Comment by Keader** [comment] 2020-05-11 14:03
duplicate of https://github.com/TrinityCore/TrinityCore/issues/20798

**Closed** 2020-05-11 14:03 UTC
