### ISSUE TITLE
DB/Quest: An End To All Things... (12779)

### ISSUE THREAD

**Issue by IlPicasso** [TrinityCore/TrinityCore#20071] opened 2017-07-22 23:48 UTC
**Description:**

This seems to be a bug in the DK quest named An End To All Things, where you need to kill 150 SOLDIERS and 10 Scarlet Ballistas, however when you try to kill the ballistas in the dragon they seems to have infinite life

**Current behaviour:**

Scarlet Ballistas have got infinite health.
You attack them and they heal automatically.

**Expected behaviour:**

Their health don't get restored so in the next attack they get destroyed.

**Steps to reproduce the problem:**

Just start the quest, and try to complete it, you wont be able to

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/134700b28fb176a8cad5dc7a04edd771e72da09a

**TDB version:**  335.63

**Operating system:** Ubuntu 16.04

**Comment by tkrokli** [comment] 2017-07-23 18:40
TrinityCore rev. f2f45765e408 2017-07-23 02:07:18 +0200 (3.3.5 branch) (Win64, Release, Static)
Using World DB: TDB 335.63 + updates up to and including `2017_07_21_01_world.sql`

Confirmed, HP resets immediately on the turret NPC. Please also note that the Scarlet Ballista does not return fire either.
- http://www.wowhead.com/quest=12779/an-end-to-all-things
- http://www.wowhead.com/npc=29104/scarlet-ballista
- http://www.wowhead.com/spell=53117/ballista-assault

`AIName = TurretAI`

**Comment by tkrokli** [comment] 2017-07-24 07:21
TrinityCore rev. 1de89579c75f 2017-07-23 18:01:42 +0200 (3.3.5 branch) (Win64, Release, Static)

Update regarding behavioural symptoms: it is possible to engage and defeat the ballistas in MELEE combat. You need to modify your player character HP to more than 500 K HP, though, because it will take several minutes to defeat the ballista in melee fight as a DK at level 56-58 (not that this scenario is practical or useful in any way, I just mention this in case you want to test the current issue.

Myself, I used `.modify hp 5000 000` (5 000 K HP) to feel comfortable about being shot at by both the ballista as well as the Tirisfal Archers and Scarlet Crusader soldiers. I spent the best part of 10 minutes before I was able to kill the ballista in melee combat. I know it is not even a practical workaround, I just did it to test this issue and see if it was possible to find out more about the root cause.

I am thinking that this has got something to do with aggro range mixed with SmartAI -- which also leads to and causes the weird behaviour described in **[[3.3.5] Strange NPC movement behavior](https://github.com/TrinityCore/TrinityCore/issues/19998) #19998** (yes, there are several examples of that yo-yo string ball effect in the DK start area scenario too, in particular where and when hostile & friendly NPC paths converge).

BTW, I hope there is a simpler way of getting to that quest than just starting a new DK character and play for 1-2 hours before you get that close to the end (right before the attack on Light's Hope Chapel at the very end).

**Comment by IlPicasso** [comment] 2017-07-24 07:26
@tkrokli 

Here is a pdump that is during the quest 

Http://f.cgm.rs/Jamely

Just 
.pdump load Jamely (ACCOUNT NAME) (new character name) 

I created a npc that completes the quest for you until this is fixed

**Comment by tkrokli** [comment] 2017-07-24 07:31
Well, thanks for the workaround (although I won't need it), maybe someone else will want to use your temporary solution.

I simply posted my info to provide some insight into the current state of the source code and this issue, in case it could be helpful in solving the problems.

**Comment by Infinito47** [comment] 2017-08-09 11:01
Any progress in this issue? This seem to happen to almost all vehicles. The creatures do not seem to target your vehicle, and reset. 

I hackfixed it by reducing the Health of the NPCs, but that's a really dirty hackfix.

**Comment by tkrokli** [comment] 2017-08-09 11:33
@Infinito47 : The real issue is that the ballistas will not target the Frostbrood Vanquisher vehicle (like you said).
Finding and solving the targeting issue is how it should be fixed to be a valid solution.
I don't know yet if this is directly related to threat/aggro handling.

**Comment by Tauriella** [comment] 2017-08-19 14:33
Many quests are broken :-1: 

Death Comes From On High ( The eye does not automatically fly to the starting Point )
Into the Realm of Shadows  ( You can't leave the region with the horse, (making a rubber band effect) )
Massacre At Light's Point ( You can't use the lore if you click on it you will be placed next to the lore )

**Comment by ConradBunton** [comment] 2017-08-23 22:33
That NPC has not infinite life, he only leave combat after the first shot.
You can reduce hp to 50k until the bug fix.

**Comment by Jildor** [comment] 2017-09-07 15:35
I think the problem is related  with TurretAI and threat

Can you take a look here @Treeston

**Comment by Infernales** [comment] 2017-09-25 19:47
This bug occurred after the commit e2a1ccd by @Treeston.

**Comment by higyigma** [comment] 2017-11-05 18:46
Any update on this?

**Comment by yvomsx** [comment] 2017-11-10 19:06
@Aokromes Any Update on this? due to @Treeston not replying yet.

**Comment by SYLARSS** [comment] 2017-11-20 11:48
Can we just make the ballista with lower health, to be killed with 1 hit ? I will try today to see is it working like that.

**Comment by jerbookins** [comment] 2017-11-25 04:58
de80cd2e0de4

Still broken

**Comment by Infinito47** [comment] 2017-11-30 09:34
@SYLARSS A really bad hackfix is to reduce the HP of the creatures by using the modifier so you can 1shot them.

**Comment by ConradBunton** [comment] 2017-12-29 21:44
Perhaps a start of answer : Spell 53117 is unusable against a player.

**Comment by tkrokli** [comment] 2017-12-29 22:09
I presume you're referring to these:
- http://www.wowhead.com/npc=29104/scarlet-ballista#abilities
  - http://www.wowhead.com/spell=53117/ballista-assault
  - http://www.wowhead.com/spell=53118/ballista-assault

Then again, why is the ballista able to shoot at melee range?

**Comment by Aokromes** [comment] 2018-01-03 19:49
test after 532ab1c

**Comment by SYLARSS** [comment] 2018-01-10 21:52
Tested and you can kill ballistas but have 1 problem with ballistas they don't shoot. You can close this issue and open a new with the ballista attack :) thanks @Aokromes

**Closed** 2018-01-10 22:03 UTC
Labels: Branch-3.3.5a, Comp-Core, Comp-Database, Priority-High, Sub-Quests, Sub-ScriptingEngine, Sub-Spells
