### ISSUE TITLE
DK starting area phase 2, Crypt of Remembrance; lacking spirit healer and bugged ghost world

### ISSUE THREAD

**Issue by GitGoppy** [TrinityCore/TrinityCore#25931] opened 2021-01-24 13:24 UTC
Branch 3.3.5a
commit a06a755

When the second phase of DK starting area begins, the player has to finish quests from NPCs in Crypt of Remembrance.
The quests require for players to go into a guarded New Avalon city with the help of a one time army of ghouls that attack the entrance.

If the player dies the battle maiden will come to resurrect you, if you don't accept the resurrection or you die a second time (the battle maiden won't come), you will be forced to release your spirit which will spawn in Crypt of Remembrance.
The map shows that there should be a spirit healer there, but there isn't one. Also leaving the crypt to enter the scarlet village will cause a glitching effect where the ghost world colour overlay and sky constantly interchange the non ghost overlay of the world. The crypt graveyard has the ghost overk, the scarlet village has the real overlay in one area, and ghost phase near the scourge front lines.

So this clipping between two worlds should be fixed and a spirit healer should be present at the crypt of remembrance graveyard.

**Comment by GitGoppy** [comment] 2021-01-24 13:27
MAP ID: 609
Area ID: 4298

**Comment by offl** [comment] 2021-01-25 16:06
Duplicate of #25230

**Closed by offl** 2021-01-25 16:06 UTC
Labels: Branch-3.3.5a
