### ISSUE TITLE
[3.3.5] Crash fix don't work correct

### ISSUE THREAD

**Issue by bahajan95** [TrinityCore/TrinityCore#18255] opened 2016-11-15 16:14 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Appeared crash after the last commits I can not say exactly but I think because of this fix
https://github.com/TrinityCore/TrinityCore/commit/64304d8b2b33ac04d3013d47b2f50c5023300c2e not working from this crash was and at the moment there is a delay of 1 minute and then crash
**Current behaviour:** (Tell us what happens.)
 When the player comes to the game world and uses the spell and goes crash but not immediately as it was before the fix https://github.com/TrinityCore/TrinityCore/commit/64304d8b2b33ac04d3013d47b2f50c5023300c2e debug can't collect because I collected on the production server out there at the moment players play, sorry for bad English - 
**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. Player comes a paladin or hunter for 30 seconds there is a crash
2. This is fix don't work https://github.com/TrinityCore/TrinityCore/commit/64304d8b2b33ac04d3013d47b2f50c5023300c2e

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
335
**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/64304d8b2b33ac04d3013d47b2f50c5023300c2e

**TDB version:**   TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Debian 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment] 2016-11-15 16:19
i cant reproduce.
The crash fixed by that commit, is for cases like: ``` me->ApplySpellImmune(0, IMMUNITY_SCHOOL, SPELL_SCHOOL_MASK_MAGIC, true);``` with spell = 0. and for me, works very well.

**Comment by bahajan95** [comment] 2016-11-15 16:21
but crashes before these commits were gone, I rewrote the commits and started crashes, rewrote all the commits since November 13, before them there were no crashes and in debug to collect will not

**Comment by bahajan95** [comment] 2016-11-15 16:22
error when compile was not I can give you access to your repository in bitbucket you can check

**Comment by bahajan95** [comment] 2016-11-15 16:28
so I roll back the commits now?

**Comment by DDuarte** [comment] 2016-11-15 16:29
**Re-open** __this__ issue when you have a crashlog.

**Closed by DDuarte** 2016-11-15 16:29 UTC

**Comment by bahajan95** [comment] 2016-11-15 16:32
you are reading what I write? I don't have time to gather in debug I put it on the server already, before these commits were not crashes 
![photo_2016-11-15_21-33-07](https://cloud.githubusercontent.com/assets/13211961/20314125/f4436766-ab7a-11e6-9ba1-18c9f30189c1.jpg) then started the crashes, the commits have been rewritten correctly without errors

**Comment by DDuarte** [comment] 2016-11-15 17:10
>  I don't have time to gather in debug

And we don't have time to fix your problems.

**Comment by Mrgrasser** [comment] 2016-11-15 18:03
where is crash log ?!!!! I tested your Steps to reproduce the problem and i don't have crash, but some time when start worldserver.exe have crash but again start worldserver.exe fixed and work SV

**Comment by ariel-** [comment] 2016-11-15 18:07
The crash fix works as intended. As @Keader says, it's for scripts.

If you don't put your Crashlog in debug mode, it's impossible to know what is your crash/it's caused by custom code (I see many commits you have rewritten the author :confused: )

**Comment by Mrgrasser** [comment] 2016-11-15 18:49
@ariel-  Some of these crashes due to problems with the operating system that rarely happens When the start Worldserver.exe . To try again fixed

**Comment by bahajan95** [comment] 2016-11-16 03:07
![photo_2016-11-16_08-05-15](https://cloud.githubusercontent.com/assets/13211961/20333290/54cdb3d6-abd3-11e6-9f46-0dd727b51032.jpg)
the aura disappears and goes crash look on the upside 0 seconds and crash
GDB brings up this BT
![photo_2016-11-16_08-05-25](https://cloud.githubusercontent.com/assets/13211961/20333320/9921d062-abd3-11e6-9f36-0b303399afe2.jpg)
look to the left in the log putty

**Comment by bahajan95** [comment] 2016-11-16 03:09
now I think the commit is related with this commit https://github.com/TrinityCore/TrinityCore/commit/cbb5c073ceb951fa138bb05b55de8b21ffd83063 help.

**Comment by Aokromes** [comment] 2016-11-16 03:29
use pastebin instead printscreen to show crashlogs.

**Comment by ariel-** [comment] 2016-11-16 03:41
Seems you got a crash when Lifebloom is removed.

I cannot reproduce on f3bdd705c0e3ab28585406ae8e08da44a09b14df
Try again with clean TC.

**Comment by bahajan95** [comment] 2016-11-16 13:49
http://pastebin.com/iUwvLEe3 crash logs
