### ISSUE TITLE
DB/Quest: Gaffer Jacks fishing loot  fix

### ISSUE THREAD

**Issue by MehdiAria** [TrinityCore/TrinityCore#19111] opened 2017-02-11 21:50 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Fix the Gaffer Jack item fishing location.
- http://www.wowhead.com/quest=1579/gaffer-jacks (http://wotlk.openwow.com/quest=1579)
- http://www.wowhead.com/item=6717/gaffer-jack (http://wotlk.openwow.com/item=6717)

**Current behaviour:** (Tell us what happens.) 

The item drops everywhere in Darkshore.

**Expected behaviour:** (Tell us what should happen instead.)

This should drop in Mist's Edge, Auberdine and The Long Wash. (Very low drop chance on Darkshore)

**Steps to reproduce the problem:**

1. Obtain the quest "Gaffer Jacks" (http://www.wowhead.com/quest=1579/gaffer-jacks)
2. Go anywhere in Darkshore outside the areas Auberdine and The Long Wash.
3. Start fishing and notice that you get the quest item there too.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) **3.3.5**

**TC rev. hash/commit:**  97dd18cb7818

**TDB version:**   TDB 335.62

**Operating system:**  Windows 7 32 bit

Suggested fix:

```sql
-- Fixing the Gaffer Jack item fishing location.
UPDATE `reference_loot_template` SET `Chance`='3' WHERE (`Entry`='11104') AND (`Item`='6717')
DELETE FROM `fishing_loot_template` WHERE (`Entry`='442') AND (`Item`='6717');
INSERT INTO `fishing_loot_template` (`Entry`, `Item`, `Chance`) VALUES ('442', '6717', '-100');
DELETE FROM `fishing_loot_template` WHERE (`Entry`='453') AND (`Item`='6717');
INSERT INTO `fishing_loot_template` (`Entry`, `Item`, `Chance`) VALUES ('453', '6717', '-100');
DELETE FROM `fishing_loot_template` WHERE (`Entry`='452') AND (`Item`='6717');
INSERT INTO `fishing_loot_template` (`Entry`, `Item`, `Chance`) VALUES ('452', '6717', '-100');
```

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment] 2017-02-12 22:20
1. Your fix needs improvements to match TrinityCore SQL standards. Here is what it should look like:
```sql
-- Fixing the Gaffer Jack item fishing location.
UPDATE `reference_loot_template` SET `Chance`= 3 WHERE `Entry`= 11104 AND `Item`= 6717;

DELETE FROM `fishing_loot_template` WHERE `Item`= 6717 AND `Entry` IN (442,452,453);
INSERT INTO `fishing_loot_template` (`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`,`Comment`) VALUES
(442, 6717, 0, -100, 1, 1, 0, 1, 1, "Gaffer Jack can be fished in the Auberdine area"),
(452, 6717, 0, -100, 1, 1, 0, 1, 1, "Gaffer Jack can be fished in the Mist's Edge area"),
(453, 6717, 0, -100, 1, 1, 0, 1, 1, "Gaffer Jack can be fished in The Long Wash area");
```
2. Even if these coding details are easy to solve, I would like to know where you have found evidence / proof that this item should only drop in those 3 areas. Sure, I can see that it follows logically from the quest description and that it is reasonable to assert that the quest items should be found near the docks of Auberdine, since it is most likely that the drunk gnome lost it near the docks or close to Auberdine. It would still be preferable to know what source you have used to select those areas.

3. Why replace the existing `Chance` value 25 with 3 in the `reference_loot_template`? Shouldn't the chance be 100 as long as you have got the quest? Or is this value part of the total list for Entry 11104?
```sql
SELECT * FROM `reference_loot_template` WHERE `Entry`= 11104;
```
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  -------
11104    6303          0    18.5              0         1        1         1         1  (NULL)
11104    6307          0     0.5              0         1        1         1         1  (NULL)
11104    6351          0     0.5              0         1        1         1         1  (NULL)
11104    6353          0     0.5              0         1        1         1         1  (NULL)
11104    6358          0      10              0         1        1         1         1  (NULL)
11104    6361          0       0              0         1        1         1         1  (NULL)
11104    6717          0      25              1         1        1         1         1  (NULL)
11104   12238          0      30              0         1        1         1         1  (NULL)
```

**Comment by offl** [comment] 2017-02-12 22:39
```sql

DELETE FROM `fishing_loot_template` WHERE `Item`= 6717 AND `Entry` IN (442,452,453);
INSERT INTO `fishing_loot_template` (`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`,`Comment`) VALUES
(442, 6717, 0, 100, 1, 1, 0, 1, 1, "Gaffer Jack can be fished in the Auberdine area"),
(452, 6717, 0, 100, 1, 1, 0, 1, 1, "Gaffer Jack can be fished in the Mist's Edge area"),
(453, 6717, 0, 100, 1, 1, 0, 1, 1, "Gaffer Jack can be fished in The Long Wash area");
```
Currently chance cannot be negative.

**Comment by tkrokli** [comment] 2017-02-12 22:51
Well, the quest loot chance was bumped up to 100% in patch 3.3.0 (quest removed in patch 4.0.3a).
The player should be able to get 8x of the quest item from 8 fishing casts, given that the fishing skill is 30+.
- http://www.wowhead.com/quest=1579/gaffer-jacks#comments:id=920789

Also, the player should be able to loot a fish, a bottle or chest at the same time as the quest item. Doesn't that require for it to be in the reference table? (I don't know enough about reference tables).

**Comment by offl** [comment] 2017-02-13 02:00
To be honest I still can't understand why he think that the item should drop only in certain areas :D

**Comment by tkrokli** [comment] 2017-02-13 02:09
Good point, I can't find any online information saying explicitly that it can only be fished in those 3 areas.

My suggestion, that it would be logical from a realistic perspective (lost in the area near the docks) and that it is very close to the quest giver, is not something that can be used as a reason for changing the current DB information. I presume it is based on sniffs or that the quest is automatically delimited by category.

**Comment by offl** [comment] 2017-02-13 02:19
I found [this](https://web.archive.org/web/20101004041008/http://www.wowhead.com/item=6717#.).
But yes, maybe will be better to touch nothing here.

**Comment by offl** [comment] 2017-02-13 02:24
[Well](http://www.wowhead.com/item=6717/gaffer-jack#comments:id=213231)..

**Comment by tkrokli** [comment] 2017-02-13 02:32
Yes, I agree with the descriptions saying that the quest item can be fished anywhere in the waters of Darkshore. The reason most map pins are close to Auberdine is that most players haven't gone far from Auberdine before they start fishing for that quest item (and also to catch some Darkshore Grouper fish http://www.wowhead.com/quest=1141/the-family-and-the-fishing-pole). Proof is needed to make changes.

**Comment by offl** [comment] 2017-02-13 06:13
We can fix the chance and close the issue. The chance of the item for the quest [Electropellers](http://www.wowhead.com/quest=1580/electropellers#comments) too should be updated.

Can we use this?
```sql
UPDATE `reference_loot_template` SET `Chance`=100,`GroupId`=0 WHERE `Entry` IN (11103,11104) AND `Item` IN (6717,6718);
```

**Comment by tkrokli** [comment] 2017-02-13 17:37
It should fix http://www.wowhead.com/quest=1580/electropellers (I remember I had to fish a lot to catch http://www.wowhead.com/item=6718/electropeller when fishing in Darkshore in 2015 or early in 2016), but should a separate issue be opened since it is for a different quest?

Oh right, that SQL is both for the quest above as well as for the follow-up quest. Perhaps we should just rename this issue to refer to both quests before adding that fix and closing this issue.

**Comment by tkrokli** [comment] 2017-02-13 18:02
When looking at those 2 `reference_loot_template` tables, I wonder if we should look at the total % chance and see if they should be updated to have a combined chance of 100% when adding the loot chances:
```sql
SELECT * FROM `reference_loot_template` WHERE `Entry`= 11103;
```
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  -------
11103     858          0     0.5              0         1        1         1         1  (NULL)  -- Lesser Healing Potion
11103    3385          0     0.5              0         1        1         1         1  (NULL)  -- Lesser Mana Potion
11103    6289          0       0              0         1        1         1         1  (NULL)  -- Raw Longjaw Mud Snapper
11103    6291          0      18              0         1        1         1         1  (NULL)  -- Raw Brilliant Smallfish
11103    6308          0      15              0         1        1         1         1  (NULL)  -- Raw Bristle Whisker Catfish
11103    6309          0     0.4              0         1        1         1         1  (NULL)  -- 17 Pound Catfish
11103    6310          0     0.2              0         1        1         1         1  (NULL)  -- 19 Pound Catfish
11103    6311          0    0.06              0         1        1         1         1  (NULL)  -- 22 Pound Catfish
11103    6363          0    0.03              0         1        1         1         1  (NULL)  -- 26 Pound Catfish
11103    6364          0    0.01              0         1        1         1         1  (NULL)  -- 32 Pound Catfish
11103    6645          0     0.3              0         1        1         1         1  (NULL)  -- Bloated Mud Snapper
11103    6718          0      25              1         1        0         1         1  (NULL)  -- Electropeller
11103   12238          0      30              0         1        1         1         1  (NULL)  -- Darkshore Grouper
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  -------
                          =   90
```
```sql
SELECT * FROM `reference_loot_template` WHERE `Entry`= 11104;
```
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  -------
11104    6303          0    18.5              0         1        1         1         1  (NULL)  -- Raw Slitherskin Mackerel
11104    6307          0     0.5              0         1        1         1         1  (NULL)  -- Message in a Bottle
11104    6351          0     0.5              0         1        1         1         1  (NULL)  -- Dented Crate
11104    6353          0     0.5              0         1        1         1         1  (NULL)  -- Small Chest
11104    6358          0      10              0         1        1         1         1  (NULL)  -- Oily Blackmouth
11104    6361          0       0              0         1        1         1         1  (NULL)  -- Raw Rainbow Fin Albacore
11104    6717          0      25              1         1        1         1         1  (NULL)  -- Gaffer Jack
11104   12238          0      30              0         1        1         1         1  (NULL)  -- Darkshore Grouper
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  -------
                          =   85
```
Then again, I am not quite sure how the `GroupId` works in `reference_loot_template`, if it should be 0 or 1 to make the reference loot work as intended. I guess it should be possible to find out by reading https://trinitycore.atlassian.net/wiki/display/tc/loot_template#loot_template-GroupId , but I still find it difficult to understand the whole concept.

**Comment by tkrokli** [comment] 2017-02-13 18:19
BTW, according to `fishing_loot_template` in TDB 335.62, `reference_loot_template` WHERE `Entry`= 11104, this loot drops in all of Darkshore (area ID 148 - https://trinitycore.atlassian.net/wiki/display/tc/AreaTable)
```sql
SELECT * FROM `fishing_loot_template` WHERE `Item` IN (11103, 11104) ORDER BY `Entry`;
```
```
 Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
------  ------  ---------  ------  -------------  --------  -------  --------  --------  -------
   148   11104      11104     100              0         1        1         1         1  (NULL) -- Darkshore
   443   11103      11103     100              0         1        0         1         1  (NULL) -- Falfarren River
   445   11103      11103     100              0         1        0         1         1  (NULL) -- Cliffspring Falls
   448   11103      11103     100              0         1        0         1         1  (NULL) -- Grove of the Ancients
   454   11103      11103     100              0         1        0         1         1  (NULL) -- Wildbend River
   456   11103      11103     100              0         1        0         1         1  (NULL) -- Cliffspring River
  2077   11103      11103     100              0         1        0         1         1  (NULL) -- Twilight Vale
```
On the other hand, 11103 (Electropeller etc.) seems to drop only in name-specific waters or rivers.

**Comment by offl** [comment] 2017-02-13 21:52
Don't know, I just follow existing examples.
```sql
SELECT * FROM `reference_loot_template` WHERE `QuestRequired`;
```

**Closed** 2017-02-18 06:26 UTC
Labels: Branch-3.3.5a, Comp-Database, Feedback-FixOutdatedMissingWIP, Sub-Quests
