### ISSUE TITLE
[Quest] We Call Him Steelfeather

### ISSUE THREAD

**Issue by lordofthedread** [TrinityCore/TrinityCore#6859] opened 2012-06-20 09:17 UTC
The quest We Call Him Steelfeather (http://www.wowhead.com/quest=11418) in Howling fjord is bugged.

How it should work :

use the provided item http://www.wowhead.com/item=34026 to see through the eyes of the hyppogriph Steelfeather, after a it should go atop of its nest and render the quest complete.

How it does work :

using the provided item makes you seeing through the creature eyes but also makes the creature comes to you. Waiting for the end of the debuff does not give credit.

On rev : 225d264 TDB 11.47+
##

**Comment by Aokromes** [comment] 2016-03-07 09:55
This can be pushed?

**Comment by Aokromes** [comment] 2016-06-13 12:14
If anyone needs sniff ican supply it.

**Comment by mittelerde** [comment] 2016-11-25 20:05
Hackfix for this Quest:


`INSERT INTO `smart_scripts` VALUES (24514, 0, 5, 0, 8, 0, 255, 0, 43969, 0, 0, 0, 33, 24515, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Steelfeather - In Combat - Quest Credit \'We Call Him Steelfeather\' (Phase 1) (No Repeat)');`

**Comment by Rushor** [comment] 2016-11-26 20:22
```sql
-- We Call Him Steelfeather (11418)
UPDATE creature_template SET AIName='SmartAI', ScriptName='' WHERE entry=24514;
DELETE FROM smart_scripts WHERE entryorguid=24514 AND source_type=0;
INSERT INTO smart_scripts VALUES(24514, 0, 0, 1, 8, 0, 100, 0, 43969, 0, 0, 0, 19, 524288, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On Spell Hit - Evade Hack');
INSERT INTO smart_scripts VALUES(24514, 0, 1, 2, 61, 0, 100, 0, 0, 0, 0, 0, 60, 1, 300, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On Spell Hit - Set Fly');
INSERT INTO smart_scripts VALUES(24514, 0, 2, 3, 61, 0, 100, 0, 0, 0, 0, 0, 64, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'On Spell Hit - Store Target');
INSERT INTO smart_scripts VALUES(24514, 0, 3, 0, 61, 0, 100, 0, 0, 0, 0, 0, 53, 1, 24514, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On Spell Hit - Start WP');
INSERT INTO smart_scripts VALUES(24514, 0, 4, 5, 40, 0, 100, 0, 5, 0, 0, 0, 33, 24515, 0, 0, 0, 0, 0, 12, 1, 0, 0, 0, 0, 0, 0, 'On WP Reach - Kill Credit');
INSERT INTO smart_scripts VALUES(24514, 0, 5, 6, 61, 0, 100, 0, 0, 0, 0, 0, 28, 43969, 0, 0, 0, 0, 0, 12, 1, 0, 0, 0, 0, 0, 0, 'On WP Reach - Remove Aura');
INSERT INTO smart_scripts VALUES(24514, 0, 6, 0, 61, 0, 100, 0, 0, 0, 0, 0, 41, 2000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On WP Reach - Despawn');
DELETE FROM conditions WHERE SourceTypeOrReferenceId=17 AND SourceEntry=43969;
INSERT INTO conditions VALUES (17, 0, 43969, 0, 0, 31, 1, 3, 24514, 0, 0, 0, 0, '', 'Requires Steelfeather');
DELETE FROM waypoints WHERE entry=24514;
INSERT INTO waypoints VALUES (24514, 1, 2613, -5086.51, 398.899, 'Steelfeather'),(24514, 2, 2640.59, -5144.9, 427.292, 'Steelfeather'),(24514, 3, 2611.1, -5253.76, 419.437, 'Steelfeather'),(24514, 4, 2575.39, -5252.23, 382.764, 'Steelfeather'),(24514, 5, 2570.71, -5228.31, 376.612, 'Steelfeather');
DELETE FROM creature_text WHERE entry IN(24139, 24131);
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES
(24131, 0, 0, 'Why not? Just think how much better it\'ll look with the hatchlings to either side --', 12, 0, 100, 0, 0, 0, 'Trapper Jethan'),
(24131, 1, 0, 'What? I\'m just sayin\' that\'s how we do things in Grizzly Hills.', 12, 0, 100, 0, 0, 0, 'Trapper Jethan'),
(24139, 0, 0, 'Y\'hear that, Jethan? You\'re not getting that Steelfeather trophy now that we know she\'s a mother.', 12, 0, 100, 0, 0, 0, 'Gil Grisert'),
(24139, 1, 0, 'Jethan!', 12, 0, 100, 0, 0, 0, 'Gil Grisert');
UPDATE creature_template SET AIName='SmartAI', ScriptName='' WHERE entry=24139;
DELETE FROM smart_scripts WHERE entryorguid=24139 AND source_type=0;
DELETE FROM smart_scripts WHERE entryorguid=24139*100 AND source_type=9;
INSERT INTO smart_scripts VALUES (24139, 0, 0, 0, 20, 0, 100, 0, 11418, 0, 0, 0, 80, 24139*100, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On Quest Rewarded - Script9');
INSERT INTO smart_scripts VALUES (24139*100, 9, 0, 0, 0, 0, 100, 0, 1000, 1000, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Script 9 - Talk');
INSERT INTO smart_scripts VALUES (24139*100, 9, 1, 0, 0, 0, 100, 0, 8000, 8000, 0, 0, 1, 0, 0, 0, 0, 0, 0, 19, 24131, 0, 0, 0, 0, 0, 0, 'Script 9 - Talk');
INSERT INTO smart_scripts VALUES (24139*100, 9, 2, 0, 0, 0, 100, 0, 5000, 5000, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Script 9 - Talk');
INSERT INTO smart_scripts VALUES (24139*100, 9, 3, 0, 0, 0, 100, 0, 3000, 3000, 0, 0, 1, 1, 0, 0, 0, 0, 0, 19, 24131, 0, 0, 0, 0, 0, 0, 'Script 9 - Talk');
``` 
(not my script)

**Comment by TULOA** [comment] 2017-08-02 02:35
Unless this should be working confirmed broken on:

TrinityCore rev. a0bdf7e83687+ 2017-07-25 21:54:11 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)
TDB 335.63

**Comment by lactoseti** [comment] 2019-04-05 20:53
Just tried this on c52eb49 and having no luck; is this known to be broken?  (Unsure because it looks like last thing on here is "closed," but it's marked open?

**Comment by illfated** [comment] 2019-04-06 16:15
> it looks like last thing on here is "closed," but it's marked open?

The closed issue is #22497 and is only linked here because it was closed as a duplicate of this issue (see https://github.com/TrinityCore/TrinityCore/issues/22497#issuecomment-423813201). The issue ticket on this page (#6859) is still open.

**Comment by Rushor** [comment] 2020-01-13 20:59
updated the script pls try again

**Comment by dr-j** [comment] 2020-01-29 15:33
~~~sql 
-- We Call Him Steelfeather (11418)
-- Steelfeather SAI
SET @ENTRY := 24514;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry` IN(@ENTRY,@ENTRY+1);
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid`IN(-114324,-114325) AND `source_type`=0;

INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(-114324,0,0,0,38,0,100,0,1,1,0,0,53,1,2451501,0,0,0,0,1,0,0,0,0,0,0,0,"Hypogrypth chick - On Data Set - Start WP"),
(-114325,0,0,0,38,0,100,0,1,1,0,0,53,1,2451502,0,0,0,0,1,0,0,0,0,0,0,0,"Hypogrypth chick - On Data Set - Start WP"),
(-114324,0,1,0,38,0,100,0,2,2,0,0,24,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Hypogrypth chick - On Data Set - Evade"),
(-114325,0,1,0,38,0,100,0,2,2,0,0,24,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Hypogrypth chick - On Data Set - Evade"),
(@ENTRY,0,0,1,8,0,100,0,43969,0,0,0,19,524288,0,0,0,0,0,1,0,0,0,0,0,0,0,"Steelfeather - On Spellhit 'Feathered Charm' - Remove Flag In Combat"),
(@ENTRY,0,1,2,61,0,100,0,0,0,0,0,60,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Steelfeather - On Spellhit - Set Fly On"),
(@ENTRY,0,2,3,61,0,100,0,0,0,0,0,64,1,0,0,0,0,0,7,0,0,0,0,0,0,0,"Steelfeather - On Spellhit - Store Targetlist"),
(@ENTRY,0,3,4,61,0,100,0,0,0,0,0,127,2,1,0,0,0,0,1,0,0,0,0,0,0,0,"Steelfeather - On Spellhit - Remove Movement"),
(@ENTRY,0,4,0,61,0,100,0,0,0,0,0,53,1,@ENTRY,0,0,0,0,1,0,0,0,0,0,0,0,"Steelfeather - On Spellhit - Start WP"),
(@ENTRY,0,5,0,40,0,100,0,1,@Entry,0,0,80,@ENTRY*100+00,2,0,0,0,0,1,0,0,0,0,0,0,0,"Steelfeather - On Reached WP1  - Run Script"),
(@ENTRY,0,6,7,40,0,100,0,2,@Entry,0,0,28,43968,0,0,0,0,0,12,1,0,0,0,0,0,0,"Steelfeather - On Reached WP2  - Despawn"),
(@ENTRY,0,7,0,61,0,100,0,0,0,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Steelfeather - On Reached WP2  - Evade");

-- Actionlist SAI
SET @ENTRY := 2451400;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,9,0,0,0,0,100,0,0,0,0,0,54,2000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Steelfeather Script -Pause WP'"), 
(@ENTRY,9,1,0,0,0,100,0,0,0,0,0,66,0,0,0,0,0,0,8,0,0,0,0,0,0,3.944444,"Steelfeather Script -Set Orientation'"), 
(@ENTRY,9,2,0,0,0,100,0,0,0,0,0,45,1,1,0,0,0,0,9,24515,0,20,0,0,0,0,"Steelfeather Script -Set Data to Spotted Hyppogrypth Hatchling'"), 
(@ENTRY,9,3,0,0,0,100,0,2000,2000,0,0,45,2,2,0,0,0,0,9,24515,0,20,0,0,0,0,"Steelfeather Script -Set Data to Spotted Hyppogrypth Hatchling'"), 
(@ENTRY,9,4,0,0,0,100,0,0,0,0,0,11,43984,2,0,0,0,0,12,1,0,0,0,0,0,0,"On Script - Cast 'Steelfeather Quest Credit'");

DELETE FROM `waypoints` WHERE `entry`in(24514,2451501,2451502);
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `orientation`, `point_comment`) VALUES 
(24514, 1,2575.582, -5219.65, 375.2497, 0, 'Steelfeather'),
(24514, 2,2470.353, -5202.818, 349.8742, 0, 'Steelfeather'),
(2451501, 1,2575.237, -5223.781, 374.644, 0, 'Steelfeather Chick 1'),
(2451502, 1,2573.845, -5222.854, 374.2438, 0, 'Steelfeather Chick 2');

DELETE FROM conditions WHERE SourceTypeOrReferenceId=17 AND SourceEntry=43969;
INSERT INTO conditions VALUES
(17, 0, 43969, 0, 0, 31, 1, 3, 24514, 0, 0, 0, 0, '', 'Requires Steelfeather');


DELETE FROM `creature_text` WHERE `CreatureID` IN (24139, 24131);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES 
(24131, 1, 0, "Why not? Just think how much better it'll look with the hatchlings to either side --", 12, 0, 100, 6, 0, 0, 23549, 0, 'Trapper Jethan'),
(24131, 0, 0, "What? I\'m just sayin\' that\'s how we do things in Grizzly Hills.", 12, 0, 100, 1, 0, 0, 23551, 0, 'Trapper Jethan'),
(24131, 2, 0, "Hey, Gil, you give my offer any more thought? I\'ll have plenty of skins and preserved meat to trade for those heavy yeti furs or down your men are working with.", 12, 0, 100, 1, 0, 0, 22937, 0, 'Trapper Jethan'),
(24139, 1, 0, "Y'hear that, Jethan? You're not getting that Steelfeather trophy now that we know she's a mother.", 12, 0, 100, 1, 0, 0, 23548, 0, 'Gil Grisert'),
(24139, 0, 0, "Jethan!", 12, 0, 100, 25, 0, 0, 23550, 0, 'Gil Grisert'),
(24139, 2, 0, "Much as I\'d like to do business with you, Jethan, all this stuff is the property of the Alliance expeditionary forces.", 12, 0, 100, 274, 0, 0, 23938, 0, 'Gil Grisert');

UPDATE `creature_template` SET `AIName`='SmartAI', ScriptName='' WHERE `entry`= 24139;

DELETE FROM `smart_scripts` WHERE entryorguid=24139 AND source_type=0;
DELETE FROM `smart_scripts` WHERE entryorguid IN(2413900,2413901) AND source_type=9;
INSERT INTO `smart_scripts` VALUES
(24139,   0, 0, 0,20, 0,100,0, 11418, 0,   0, 0, 0, 80, 2413900, 2, 0, 0,  0,    0, 1, 0,      0, 0, 0, 0, 0, 0, 0,'On Quest Rewarded - Script9'),
(24139,   0, 1, 0,20, 0,100,0, 11292, 0,   0, 0, 0, 80, 2413901, 2, 0, 0,  0,    0, 1, 0,      0, 0, 0, 0, 0, 0, 0,'On Quest Rewarded - Script9'),
(2413901, 9, 0, 0, 0, 0,100,0, 1000, 1000, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0,           19,  24131, 0, 0, 0, 0, 0, 0, 0,'Script 9 - Talk'),
(2413901, 9, 1, 0, 0, 0,100,0, 6000, 6000, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0,            1,  0,     0, 0, 0, 0, 0, 0, 0,'Script 9 - Talk'),
(2413900, 9, 0, 0, 0, 0,100,0, 1000, 1000, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,            1,  0,     0, 0, 0, 0, 0, 0, 0,'Script 9 - Talk'),
(2413900, 9, 1, 0, 0, 0,100,0, 8000, 8000, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,           19, 24131,  0, 0, 0, 0, 0, 0, 0, 'Script 9 - Talk'),
(2413900, 9, 2, 0, 0, 0,100,0, 5000, 5000, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,            1, 0,      0, 0, 0, 0, 0, 0, 0,'Script 9 - Talk'),
(2413900, 9, 3, 0, 0, 0,100,0, 3000, 3000, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,           19, 24131,  0, 0, 0, 0, 0, 0, 0, 'Script 9 - Talk');

**Comment by dr-j** [comment] 2020-01-29 15:39
and timing for wp is right arrives at point  in sniff and sets orientation and chicks move then 2 seconds later credit spell gets cast and moves back to original position

**Comment by Rushor** [comment] 2020-02-18 22:33
@dr-j maybe adding the waypoint_data to waypoints then?

**Comment by Killyana** [comment] 2020-02-18 23:25
We fixed SMART_ACTION_PAUSE_MOVEMENT you can know just pause waypoint_data

**Comment by dr-j** [comment] 2020-02-19 02:28
I already tried that in script the problem was once had completed sai wp to nest and back would loose all movement and just not move again

**Comment by illfated** [comment] 2020-02-19 22:37
Maybe Rushor's suggestion (https://github.com/TrinityCore/TrinityCore/issues/6859#issuecomment-587937890) could be worth looking into, now that you have tested again?

> @dr-j maybe adding the waypoint_data to waypoints then?

**Comment by Rushor** [comment] 2020-03-25 22:55
so the remaining issue is related to some generic wp handling issues?

**Comment by Killyana** [comment] 2020-03-25 23:08
I think it's fixed, need to check.

**Closed** 2020-08-31 20:13 UTC
Labels: Branch-3.3.5a, Branch-master, Comp-Database, Feedback-FixOutdatedMissingWIP, Sub-Quests
