### ISSUE TITLE
Tricky Maizer Server Crash

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#29083] opened 2023-06-20 11:17 UTC
### Description

https://gist.github.com/PivanDepolo/137f35f220785d3cad172b005e9fbbee

### Expected behaviour

Must not crash

### Steps to reproduce the problem

Just hit https://www.wowhead.com/npc=57223/tricky-maizer via https://www.wowhead.com/spell=108853/fire-blast or https://www.wowhead.com/spell=11366/pyroblast

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/f4d35546b021ac9bc023c9d9c618f8ee3155122c

### Operating system

Debian 11

### Custom changes

None

**Comment by Shauren** [comment] 2023-06-29 09:25
Duplicate of #28887

**Closed by Shauren** 2023-06-29 09:25 UTC
Labels: Branch-master
