### ISSUE TITLE
[3.3.5]: Bug with unstuck

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#17291] opened 2016-06-05 07:31 UTC
**Description**:
Bug with unstuck. NOT blizzlike.
**Current behaviour**: Tell us what happens
If we using "unstuck", we teleports to the starting location.
**Expected behaviour**: Tell us what should happen instead
We need to move to some other X, Y, or Z. Like official server.
**Steps to reproduce the problem**:
1. Create a character
2. Go to the random location
3. Use "unstuck"

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5
**TC hash/commit**:  
3bba685
**TDB version**:  
Maybe, all.
**Operating system**:  
All.

**Comment by SnapperRy** [comment] 2016-06-05 07:34
Unstuck should teleport you to home position if your hearthstone is out of cooldown. If not, it will "nudge" you a few yards forward, like a mage's Blink.

**Comment by stas730** [comment] 2016-06-05 07:37
Yes. But it teleports to home position with/without normal Hearthstone.

**Comment by Keader** [comment] 2016-06-05 11:38
in 6.x teleport from near graveyard.
in 3.3.5 i always teleported by home position -start position-  (this is right i think)

**Comment by stas730** [comment] 2016-06-05 11:56
Start position is not home position. Create new Hearthstone but you will back to start location.

**Comment by Keader** [comment] 2016-06-05 11:57
Yeap, it is true

**Comment by LordUsagi** [comment] 2016-06-06 03:17
A couple of points with this one actually...

- If the player is dead, it will return them to the graveyard closest to their corpse.
- If the player is alive, and their hearthstone is in their inventory, and their hearthstone is cooled down, it will activate their hearthstone. The 30 minute hearthstone cooldown is activated as usual.
- If the player is alive, but their hearthstone is either not in their inventory (e.g. in the bank) or their hearthstone is on cooldown, then the game will try to "nudge" the player in a seemingly random direction

[We did this over at OC](https://github.com/OregonCore/OregonCore/commit/279cad00b3a3235e9b616683b94564bdf221ed21). Although it's not the best way to go about it.

**Comment by Shauren** [comment] 2016-06-06 13:08
I have no idea how this worked on 3.3.5 but currently on retail it either uses your heartstone if you can cast it (alive & not on cooldown) otherwise it just kills you so you can run back to corpse, no trying to relocate or anything like that

**Comment by tkrokli** [comment] 2016-06-06 14:04
I remember using the 'Unstuck' command on retail during the WoTLK days when I was caught behind a gameobject in the Orgrimmar Auction House. That one time, it moved me out to the floor. I never needed that Unstuck feature much, so I can also remember being hearthstoned to my racial start position way earlier, maybe during the TBC days or in Classic (vanilla) wow.

**Comment by sirikfoll** [comment] 2017-04-08 03:09
Partially fixed by https://github.com/TrinityCore/TrinityCore/commit/0d1c53504143c5ea87754d41ea886af68b779ac1

Still an issue: If used while dead there's no immediate effect, the player will only be ported to the graveyard after a relog

**Comment by MrSmite** [comment] 2017-04-12 20:30
I posted this in a duplicate issue:

[This comment](http://www.wowhead.com/spell=7355/stuck#comments:id=349248) is for 2.4.3 and indicates the game will only use your hearthstone if not on CD:

> If you have a hearthstone it will use that to get you out of a tough spot, if not it will attempt to manually teleport your character slightly.

I don't see any description for how 3.3.5 should work so it should logically fall back to the previous 2.4.3, not whatever current retail is.

**Comment by Killyana** [comment] 2019-11-06 17:15
The issue is player->RepopAtGraveyard(); is not executed  when the player is a ghost, but if you use .revive after that you will be teleport to the graveyard.

https://github.com/TrinityCore/TrinityCore/pull/18968/files#diff-b3ff7e4adf5326d9790d99d1dee0da2dR4191

**Closed** 2024-10-05 17:01 UTC
Labels: Priority-Very-Low
