### ISSUE TITLE
[All branches] Npc Defile

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14897] opened 2015-06-15 19:29 UTC
Using rev: https://github.com/TrinityCore/TrinityCore/commit/d08524cfeb9028ead9c378cf18ddf21c63c88a2a
TDB: 11.58

After several updates from TrinityCore, players reported, cca 2 weeks ago, LK spell defile summon NPC http://www.wowhead.com/npc=38757.

**What should npc do: Npc should stay on summoned position, and just grow when player in.**

**What is doing now: Defile npc just select target and chasing him.**

**Comment by Nyeriah** [comment] 2015-06-15 19:35
https://github.com/TrinityCore/TrinityCore/pull/14780

Defile isn't the only npc, try that nexus boss with crystals, Omok or whatever it was.

**Comment by Keader** [comment] 2015-06-15 20:06
Try

UPDATE `creature_template` SET `flags_extra` = `flags_extra` | 128 WHERE `entry`=38757

**Comment by Frytiks** [comment] 2015-06-15 20:45
Thanks, reverting incomming :)

**Comment by Nyeriah** [comment] 2015-06-15 20:49
Why did you close the issue? It's not fixed at TrinityCore, so it should _not_ be closed until it is so.

**Comment by Killyana** [comment] 2015-06-15 22:29
The defensive_state from UNIT_FLAG_IMMUNE_TO_NPC was a bug, if some npcs attacks players after the commit they must be fixed by `flags_extra` =128 (if they are triggers) or by forcing the react on the script.

**Comment by Nyeriah** [comment] 2015-06-15 22:37
I don't think that's good

Either UNIT_FLAG_IMMUNE_TO_NPC should make no exception for pets, or UNIT_FLAG_IMMUNE_TO_PC should also force the creature to ignore pets.

**Comment by Killyana** [comment] 2015-06-15 22:46
The issue is with pets here?

**Comment by Nyeriah** [comment] 2015-06-15 22:47
> The issue is with pets here?

https://github.com/TrinityCore/TrinityCore/pull/14780#issuecomment-109010873

**Comment by Killyana** [comment] 2015-06-15 22:59
I tested LK without any summoned pet or totems and I get attacked by http://www.wowhead.com/npc=38757/defile , players think that the issue comes from pets because summoned npcs start attacking pets and totems before players.

**Comment by tkrokli** [comment] 2015-06-15 23:32
Like I wrote in https://github.com/TrinityCore/TrinityCore/pull/14780#issuecomment-112236354, it looks like this also happens to player combat pets when the player switches to GM ON, but the pet still gets attacked by hostile NPCs. I am guessing `.gm on` turns on the flag UNIT_FLAG_IMMUNE_TO_PC on the player, but it no longer applies to the pet, from what I have seen.

**Comment by Nyeriah** [comment] 2015-06-16 08:56
Totally unrelated to this issue - gm mode has never cleared combat state for summoned creatures

**Comment by GeneralSaurfang** [comment] 2015-06-19 07:23
Add UNIT_FLAG_PACIFIED ?

**Comment by D4R4** [comment] 2015-06-21 07:37
setting the unit_flag "DISABLE_MOVE" in the database did the trick for me,,

**Comment by Frytiks** [comment] 2015-06-21 10:20
For me disable move not works

**Comment by Killyana** [comment] 2015-06-26 15:01
Fixed by: https://github.com/TrinityCore/TrinityCore/commit/accab5451d3e62739e4aa376d25bc6623f0d3c52

**Closed by Killyana** 2015-06-26 15:01 UTC
Labels: Comp-Database, Sub-Entities
