### ISSUE TITLE
[3.3.5] Boss::Sindragosa debuff Unchained magic / stack Instability

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18945] opened 2017-01-24 13:28 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** give stack for shield Priest or  per second [Lifebloom] [Rejuvenation]  Druid or Totem Shaman and per second Shaman and paladin [holy shock] or now if use trinket give stack.

Unchained Magic
Unlimited range
Instant
Inflicts an arcane malediction on the target, causing any spells cast to result in a backlash of Arcane power after 5 sec.  Multiple spellcasts by the afflicted target will intensify the backlash.

Buff
Unchained Magic
Magical spells cast will cause a delayed backlash.
30 seconds remaining

**Current behaviour:** (Tell us what happens.) give stack for all spells no cast

**Expected behaviour:** (Tell us what should happen instead.) must give stack for all spells have casts

**Steps to reproduce the problem:**

1. go instace ICC Boss Sindragosa with Class Priest or dudu
2. start boss Sindragosa wait for  Unchained magic
3. if with Class priest use shield => give Stack Instability !!

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  2db3e86d9bf200e5049e553160bc47b7bacac621

**TDB version:**  62

**Operating system:**  win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment] 2017-01-24 17:02
> Inflicts an arcane malediction on the target, causing any spells cast

If you use PW:S with a priest, you're actually casting a spell

**Comment by Mrgrasser** [comment] 2017-01-24 19:42
I don't @Keader say every my problem is not  trinity/clean db .
 but other spells give stack for other class even with use trinket !

**Comment by Keader** [comment] 2017-01-24 19:47
I dont say it @Mrgrasser.
But you report some issues that we cant reproduce in Trinity...
So, i'm telling you to test in a clean trinity to confirm if is a Trinity issue before report.

**Comment by Mrgrasser** [comment] 2017-01-24 20:34
I tested again if there is a problem, previous problem was resolved , but in this case I did not have any changes in the code Boss .

**Comment by bahajan95** [comment] 2017-01-25 03:21
confirm

**Comment by tkrokli** [comment] 2017-01-25 03:53
@bahajan95 : when confirming, add your the TC rev. hash so we know which commit you confirmed it on.

**Comment by Mrgrasser** [comment] 2017-01-25 14:55
Trinkets gain a stack Instability , Automatically trinket for example: [Deathbringer's Will](http://www.wowhead.com/item=50362/deathbringers-will) must gain stack ?
here say which for  15 sec but is 30 seconds!!!
```
For casters, she periodically debuffs mana users with Unchained Magic, which for 15 seconds causes its victims to gain a stack of Instability every time they cast a spell (including things like Healthstones or Trinkets). 
Instability expires after 5 sec (unless refreshed by casting another spell). 
Expiration is unavoidable after Unchained Magic fades. Upon expiration, Instability deals 2k damage per stack.

link: http://wow.gamepedia.com/Sindragosa_%28tactics%29

**Comment by Killyana** [comment] 2017-01-25 15:09
No it's 30 secs: http://cata.openwow.com/spell=69762 it's DBC data
Also please link spells or trinkets that procs/or not  Unchained Magic, the issue is not clear at all.

**Comment by Mrgrasser** [comment] 2017-01-25 17:09
@Killyana I did not say that 30 seconds is wrong  , in the link have some problem for Followed Tactics, this is Very easy , Instability must gain stack whit any spells casts ,not gain stack with spells no cast.

**Comment by Killyana** [comment] 2017-01-26 14:58
Give some example of spells that are not casted but stacks Instability.

**Comment by Mrgrasser** [comment] 2017-01-27 14:27
this is some spells no cast but stacks Instability :
[[Power World : Shield](http://wotlk.openwow.com/spell=48066)] , [[Rejuvenation](http://wotlk.openwow.com/spell=48441)] , [[Glyph of Rejuvenation](http://wotlk.openwow.com/spell=54755)] , [[Lifebloom](http://wotlk.openwow.com/spell=48451)] , [[Lay on Hands](http://wotlk.openwow.com/spell=48788)] , [ [Holy Shock](http://wotlk.openwow.com/spell=48821)] , [[Judgement Of Light](http://wotlk.openwow.com/spell=20185)] , [[Holy Nova](http://wotlk.openwow.com/spell=48076)] , [[Circle of Healing](http://wotlk.openwow.com/spell=48089)] , [ [Vampiric Embrace](http://wotlk.openwow.com/spell=15290)] , [[Prayer of Mending](http://wotlk.openwow.com/spell=48113)] , [[Healing Stream Totem](http://wotlk.openwow.com/spell=58757)] [[Earth Shield](http://wotlk.openwow.com/spell=49284)] , [[Death Coil](http://wotlk.openwow.com/spell=62904)] , [[Mend Pet](http://wotlk.openwow.com/spell=48990)] , [[Lifeblood](http://wotlk.openwow.com/spell=55503)}

**Comment by Mrgrasser** [comment] 2017-01-27 17:38
In this regard, the temporary am going to help to resolve this problem?
I do not know exactly how the system proc works

**Comment by ariel-** [comment] 2017-01-27 18:24
http://www.wowhead.com/spell=69762/unchained-magic#comments:id=1024570:reply=448220

> Rikeni on 2010/04/22 (Patch 3.3.3)
My understanding is that while you have the Unchained Magic debuff, *anything* that you cast will cause a stack of Instability to build up. As a disc priest, I can confirm that **Renew**, **Prayer of Mending**, and **Power Word: Shield will build stacks**. **Pain Suppression will also build stacks**. I have been told that a mage's Blink will also build stacks. So **regardless of whether you are a healer or a dps caster, any spell that is cast will create one stack of Instability (not just healing spells for healers and dps spells for dps)**. However, channeled spells will not build more stacks

**Comment by Mrgrasser** [comment] 2017-01-27 18:49
like @ariel- so [Power World : Shield] must gain stacks Instability , but other must gain ?

**Comment by Keader** [comment] 2017-01-27 18:53
If i remember right, all spell cast should apply stacks of Instability.
Including "Instant Cast" spells, and channel (like mind fly, penance, etc)

**Comment by Mrgrasser** [comment] 2017-01-27 18:55
@Keader  Categories bit difficult spells because of their high

**Comment by Keader** [comment] 2017-01-27 18:57
what?

**Comment by ariel-** [comment] 2017-01-27 22:52
> However, channeled spells will not build more stacks

Mind flay should only get one stack on initial cast, ticks shouldn't proc additional stacks

**Comment by MrDelta** [comment] 2017-01-28 02:02
@ariel- anyway.
this is
 Invalid-IncompleteData/NotTrinityCore label 
or not?

**Comment by MrSmite** [comment] 2017-01-28 02:38
I don't know if this helps but __Aliena__ formerly of Tankspot has a walkthrough of this fight. At 1:44 she explains that for "a random casters", "every spell cast" causes the debuff.

https://www.youtube.com/watch?v=o89tT2o87r0&list=PL9D63669ADB127CEC&index=26

And for reference, here is a big list of her walkthroughs.

https://www.youtube.com/playlist?list=PL9D63669ADB127CEC

**Comment by Mrgrasser** [comment] 2017-01-28 08:52
@MrSmite problem is for spells cast and no cast , other things worked some true

**Comment by Mrgrasser** [comment] 2017-01-28 16:13
@ariel- The idea of not temporary ?

**Comment by ariel-** [comment] 2017-01-29 04:41
What?

**Comment by DeActiver** [comment] 2017-01-29 06:30
what?!! Reply've trained to do? !!Answer the question that you are going to run by u fucked to any spells trinity now say what , u don't konw what is splls cast and no cast, this is for new proc system all spells fucked u. In addition, if you are jealous partner than the @Shauren 
In closing comment 2dc939c2041c73952ee64e9834c1f61b0eadf395 It turns out. where want clean fucked maybe some years later

**Comment by Mrgrasser** [comment] 2017-01-29 07:17
@DeActiver we don't have War together , Anyone can compete with other this is not kept so envy, Please keep in marginalized.

**Comment by tkrokli** [comment] 2017-01-29 10:04
@Mrgrasser : Well said. Do you think you can explain your question to ariel-, "The idea of not temporary ?"

**Comment by Mrgrasser** [comment] 2017-01-29 16:41
:D yes , ariel- always have idea for fix , I mean, clearly did not.
my question is with table spell_proc can fix this spell ? or need script?

**Comment by Keader** [comment] 2017-01-29 17:07
@DeActiver You are free to revert any fix that you want in your local machine. Now please before complain about someone's work, spend sometime helping this community... people here "work" without any payment, with the main objective of learning. If you can do better, please do and share with us.

**Comment by ariel-** [comment] 2017-01-29 17:10
Plus, I do this for fun and I don't want to "compete" with anyone, the proc system was abandoned 2 years ago, I took the work on my own hands, it was a necessary change.

We knew that it'd break stuff, but ranting instead of giving exact details of why things aren't working as intended isn't going to help fix them.

**Comment by sirikfoll** [comment] 2017-01-29 17:26
This issue should be closed, there's no bug here..

Mrgrasser, you are misunderstanding "cast time" with "cast", spells with no cast time, such as [Power World : Shield] and [Rejuvenation] should give stacks, as it is right now ^^

**Comment by Mrgrasser** [comment] 2017-01-29 17:37
@sirikfoll I have some spells maybe in the say some spells I have fault. [Rejuvenation] not gain stacks , You take a look at healer ,If what you say is true then healers must die , especially class druid in this issue will be very difficult . now must close ?!! 
you can قead on to see this more and more accurate.

**Closed** 2017-01-29 17:44 UTC
Labels: Invalid-Intended/WontFix/Blizzlike

**Comment by Mrgrasser** [comment] 2017-01-29 17:47
real like any noobe was don't have Information , like keader new rank now you are fun :D

**Comment by ariel-** [comment] 2017-01-29 19:15
Proper report: #19005
