### ISSUE TITLE
[crash] Unit::RemoveAurasByType

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#13851] opened 2015-01-03 18:56 UTC
I recently get this crash.

http://pastebin.com/nZRMrkm8

51f5ce1b7364b730cb0bdabcfd6ad18794213f95

**Comment by avengerweb** [comment] 2015-01-13 22:17
Confirm

**Comment by jackpoz** [comment] 2015-03-07 22:37
any "confirm" is useless without a crashlog

**Comment by Eldro** [comment] 2015-05-03 13:42
http://pastebin.com/b7w3ZB0e
Confirm

**Comment by jackpoz** [comment] 2015-05-03 15:02
https://github.com/TrinityCore/TrinityCore/wiki

**Comment by Frytiks** [comment] 2015-05-03 18:35
I can confirm this crash too, but it`s so rare.

**Comment by tkrokli** [comment] 2015-05-03 19:50
jackpoz commented on 7 Mar :
> any "confirm" is useless without a crashlog

**Comment by Xxxhackerxxx** [comment] 2015-05-13 05:09
Confirm

**Comment by Voidx** [comment] 2015-07-01 03:28
http://pastebin.com/3zrEHrLg
so much crash.

**Comment by jackpoz** [comment] 2015-07-01 07:03
@Voidx https://github.com/TrinityCore/TrinityCore/wiki , your crash report is incomplete

**Comment by Aokromes** [comment] 2015-11-03 20:00
To long time since the last crash closing, if anyone have any new crash related to this open a new ticket.

**Closed by Aokromes** 2015-11-03 20:00 UTC
Labels: Branch-3.3.5a, HasBacktrace

**Comment by zanzark** [comment] 2016-06-02 04:31
Still crashing today.

**Comment by tkrokli** [comment] 2016-06-02 07:11
@zanzark : there is a new issue posted for this kind of crash. Post your comment & crash log there:
**[[3.3.5][Crash]Unit::RemoveAurasByType](17063) #17063**

**Comment by jackpoz** [comment] 2016-06-02 09:29
> Still crashing today.

This message is totally useless and doesn't provide anything useful to move towards a fix. Take your time to read how to properly report a crash.
