### ISSUE TITLE
Silithyst Mound/Geyser 

### ISSUE THREAD

**Issue by YukkiKun** [TrinityCore/TrinityCore#26236] opened 2021-03-13 18:03 UTC
**Description:**

In Silithus there are some objects on ground Silithyst Mount/Geyser, when you click on them nothing happends.

**Expected behaviour:**

While you travel in Silithus you find some Silithyst Mound or Silithyst Geyser on ground, when you click on them they should give you this buff https://wotlk.evowow.com/?spell=29519 and run with it in your faction camp and get this buff https://wotlk.evowow.com/?spell=29534

This video has a great explanation ( 1:17 - 2:01 )
https://www.youtube.com/watch?v=_YpumVmwybc

**Steps to reproduce the problem:**

1. Go to Silithus
2. Find a Silithyst Mound or Silithyst Geyser.
3. Click on it and nothing happened.

**Branch(es):**

3.3.5

**TC rev. hash/commit: 84ad438**

TrinityCore rev. 84ad438 2021-03-05 22:22:56 +0100 (3.3.5 branch) (Win64, Release, Static)

**Operating system:**

Windows 7 x64

**Comment by offl** [comment] 2021-03-13 18:04
Duplicate of #15906

**Closed by offl** 2021-03-13 18:04 UTC
Labels: Branch-3.3.5a
