### ISSUE TITLE
[quest bug] can not finish quest [ the light of dawn ]

### ISSUE THREAD

**Issue by humanana** [TrinityCore/TrinityCore#23335] opened 2019-05-31 20:58 UTC
**after the fight and come to an end event with speech it stop working with the text in world console **

**3.3.5 branch**
win 8.1 x64

TrinityCore rev. 33074b34c8bc 2019-05-31 17:29:33 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...
GameObject (template id: 191609) has invalid faction (faction template id) #0
GameObject (template id: 191609) has invalid faction (faction template id) #0
GameObject (template id: 191609) has invalid faction (faction template id) #0
GameObject (template id: 191609) has invalid faction (faction template id) #0
GameObject (template id: 191609) has invalid faction (faction template id) #0
GameObject (template id: 191609) has invalid faction (faction template id) #0
GameObject (template id: 191609) has invalid faction (faction template id) #0
GameObject (template id: 191609) has invalid faction (faction template id) #0
Could not load MMAP name:Ebon Hold, id:609, x:29, y:44 (mmap rep.: x:29, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:28, y:44 (mmap rep.: x:28, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:30, y:43 (mmap rep.: x:30, y:43)
Could not load MMAP name:Ebon Hold, id:609, x:27, y:44 (mmap rep.: x:27, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:28, y:44 (mmap rep.: x:28, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:27, y:44 (mmap rep.: x:27, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:27, y:44 (mmap rep.: x:27, y:44)
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
Could not load MMAP name:Ebon Hold, id:609, x:27, y:44 (mmap rep.: x:27, y:44)
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
Could not load MMAP name:Ebon Hold, id:609, x:27, y:44 (mmap rep.: x:27, y:44)
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
Could not load MMAP name:Ebon Hold, id:609, x:27, y:44 (mmap rep.: x:27, y:44)
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
GameObject (template id: 190769) has invalid faction (faction template id) #0
Could not load MMAP name:Ebon Hold, id:609, x:27, y:44 (mmap rep.: x:27, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:28, y:44 (mmap rep.: x:28, y:44)
GameObject (template id: 190767) has invalid faction (faction template id) #0
GameObject (template id: 190767) has invalid faction (faction template id) #0
GameObject (template id: 190767) has invalid faction (faction template id) #0
GameObject (template id: 190767) has invalid faction (faction template id) #0
GameObject (template id: 190767) has invalid faction (faction template id) #0
GameObject (template id: 190767) has invalid faction (faction template id) #0
GameObject (template id: 190767) has invalid faction (faction template id) #0
GameObject (template id: 190767) has invalid faction (faction template id) #0
Could not load MMAP name:Ebon Hold, id:609, x:29, y:44 (mmap rep.: x:29, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:28, y:44 (mmap rep.: x:28, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:27, y:44 (mmap rep.: x:27, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:30, y:43 (mmap rep.: x:30, y:43)
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 49028 proc, because the spell does not have an entry in Spell.dbc.
Could not load MMAP name:Ebon Hold, id:609, x:29, y:44 (mmap rep.: x:29, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:28, y:44 (mmap rep.: x:28, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:30, y:43 (mmap rep.: x:30, y:43)
Could not load MMAP name:Ebon Hold, id:609, x:29, y:44 (mmap rep.: x:29, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:28, y:44 (mmap rep.: x:28, y:44)
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 49028 proc, because the spell does not have an entry in Spell.dbc.
Could not load MMAP name:Ebon Hold, id:609, x:29, y:44 (mmap rep.: x:29, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:28, y:44 (mmap rep.: x:28, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:30, y:43 (mmap rep.: x:30, y:43)
Could not load MMAP name:Ebon Hold, id:609, x:29, y:44 (mmap rep.: x:29, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:28, y:44 (mmap rep.: x:28, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:30, y:43 (mmap rep.: x:30, y:43)
Could not load MMAP name:Ebon Hold, id:609, x:29, y:44 (mmap rep.: x:29, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:28, y:44 (mmap rep.: x:28, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:30, y:44 (mmap rep.: x:30, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:28, y:44 (mmap rep.: x:28, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:27, y:44 (mmap rep.: x:27, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:29, y:44 (mmap rep.: x:29, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:30, y:43 (mmap rep.: x:30, y:43)
Could not load MMAP name:Ebon Hold, id:609, x:30, y:44 (mmap rep.: x:30, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:28, y:44 (mmap rep.: x:28, y:44)
Could not load MMAP name:Ebon Hold, id:609, x:29, y:44 (mmap rep.: x:29, y:44)

the mmap is activated

![trin2](https://user-images.githubusercontent.com/51247678/58734540-dee75300-8421-11e9-99bc-256ff656389b.JPG)

![trin](https://user-images.githubusercontent.com/51247678/58734389-84e68d80-8421-11e9-87cb-04b7abc88b22.JPG)

**Comment by illfated** [comment] 2019-06-01 11:07
Likely duplicate of issue ticket **[3.3.5][6.x] The Light of Dawn** #13294

Please also note that `GameObject (template id: xxxxxx) has invalid faction (faction template id) #0` is unlikely to affect this issue and that one of the ways to make sure the event will work, is to follow and stay close to Highlord Darion Mograine at all times, to avoid losing him if he gets stuck after starting the charge. Sometimes he will even die and despawn if you ride ahead or out of Line of Sight from him.

**Comment by illfated** [comment] 2019-06-01 11:13
Also note:
- https://www.wowhead.com/spell=49028/dancing-rune-weapon
```
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 49028 proc, because the spell does not have an entry in Spell.dbc.
```
1. Dancing Rune Weapon functionality is limited and needs more development in TC source.
2. Dancing Rune Weapon is unlikely to affect the issue you have opened.

**Closed** 2019-06-01 11:52 UTC
