### ISSUE TITLE
Vendor item

### ISSUE THREAD

**Issue by nc059** [TrinityCore/TrinityCore#27988] opened 2022-06-01 09:38 UTC
### Description

When I buy an item with incrtime the item disappears from the seller once the menu is reopened

![Sans titre-1](https://user-images.githubusercontent.com/106661765/171374137-9ff49a46-576a-4951-8d01-098dc1faae37.jpg)

### Expected behaviour

the item must be available without the possibility to buy it once exhausted

### Steps to reproduce the problem

INSERT` INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `DamageModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES (75010, 0, 0, 0, 0, 0, 1692, 0, 0, 0, 'Lisa Rochepierre', 'Médecin', '', 0, 5, 5, 0, 121, 128, 1, 1.14286, 1, 0, 0, 2000, 2000, 1, 1, 1, 0, 2048, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 1, 2, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, '', `12340);

INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (75010, 0, 1251, 5, 15, 0, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (75010, 0, 2581, 5, 15, 0, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (75010, 1, 961, 10, 100, 0, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (75010, 2, 118, 2, 45, 0, 0);

### Branch

3.3.5

### TC rev. hash/commit

TDB 335.22021

### Operating system

windows 10

### Custom changes

no

**Comment by Jinnaix** [comment] 2022-06-01 10:08
> Steps to reproduce the problem
no

Excuse me?
I am ignoring the fact that i could not find out who that npc is and that there is no valid revision given.

Before buying:
![image](https://user-images.githubusercontent.com/37972361/171379734-9dadafe4-9b80-4371-9889-24103426fbe8.png)

After buying, closing and reopening the vendor menu:
![image](https://user-images.githubusercontent.com/37972361/171379869-8411c139-aedf-4653-822c-d1b910246ffb.png)


Not being able to replicate on 38dc5667ba13d5c1d094330b0f57ba0ee9b2dde5

**Comment by jackpoz** [comment] 2022-06-01 10:28
> ### Steps to reproduce the problem
> no

could you please include the steps to recreate the vendor with the same data you set ? maybe the issue is in the SQL data

**Comment by Aokromes** [comment] 2022-06-01 10:37
https://i.imgur.com/pMB8kJY.png

**Comment by CraftedRO** [comment] 2022-11-04 19:30
f2fcd6746c72 I can confirm this , I wanted to test [updated respawn time](https://github.com/TrinityCore/TrinityCore/commit/53618acd29f3b1013f7fe0d6be319bd4a928d286) for for Formula: Runed Adamantite Rod at Vodesiin and after I closed the npc menu I waited few minutes and I opened again but this time formula dissapeared.

**Comment by CraftedRO** [comment] 2022-11-04 19:30
f2fcd6746c72 I can confirm this , I wanted to test [updated respawn time](https://github.com/TrinityCore/TrinityCore/commit/53618acd29f3b1013f7fe0d6be319bd4a928d286) for for Formula: Runed Adamantite Rod at Vodesiin and after I buyed it , I closed the npc menu I waited few minutes and I opened again but this time formula dissapeared at all.

**Comment by CraftedRO** [comment] 2022-11-04 19:37
f2fcd6746c72 I can confirm this , I wanted to test [updated respawn time](https://github.com/TrinityCore/TrinityCore/commit/53618acd29f3b1013f7fe0d6be319bd4a928d286) for for Formula: Runed Adamantite Rod at Vodesiin and after I closed the npc menu I waited few minutes and I opened again but this time formula dissapeared.

![WoWScrnShot_110422_212719](https://user-images.githubusercontent.com/24683355/200060753-e1a41473-5fa2-4b6a-a937-03194c650df8.jpg)

**Comment by offl** [comment] 2022-11-04 20:11
Out of curiosity what happens and what shouldn't happen?

**Comment by CraftedRO** [comment] 2022-11-04 20:15
Probably after sold out it shoudn't be removed completly from vendor list but instead his item icon become grayed out , not sure but someone with retail account can easy test this out.

**Comment by heyitsbench** [comment] 2023-04-02 00:26
> Out of curiosity what happens and what shouldn't happen?

As an example with 'High Admiral "Shelly" Jorrik' and his 'Plans: Solid Iron Maul', buying the item will cause it to show up as greyed out, but closing and opening the menu will not show the item at all.

**Comment by CraftedRO** [comment] 2023-04-02 19:21
> > Out of curiosity what happens and what shouldn't happen?
> 
> As an example with 'High Admiral "Shelly" Jorrik' and his 'Plans: Solid Iron Maul' on Wrath Classic at least, buying the item will cause it to show up as greyed out, but closing and opening the menu will not show the item at all.

if that's valid for all npc then this issue is invalid

**Comment by heyitsbench** [comment] 2023-04-02 19:24
> if that's valid for all npc then this issue is invalid

As far as I've seen from the few times I've bought limited stock items on Classic, the behavior I observed is consistent with all vendors.

**Closed** 2023-04-06 16:09 UTC
Labels: Comp-Core, Branch-3.3.5a
