### ISSUE TITLE
Halion HP Sharing

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#17899] opened 2016-09-04 21:15 UTC
Halion HP Sharing doesn't after Separation ( when both fire and shadow bosses appears )

1- get 2 groups
2- hit the boss until 50%
3- both groups teleport to fire and kill the boss  ( here shadow boss will be healed, but it isn't share it with fire boss )

**Branch(es)**: 3.3.5
**TC hash/commit**:  5868509a6366d0ba7a0fe819c3ece0e4a57c7029
**TDB version**:  61
**Operating system**:  Debian

**Comment by Nyeriah** [comment] 2016-09-04 21:17
Spell range issue, for some reason if you move one boss too far away from the other it simply won't heal

**Comment by sirikfoll** [comment] 2016-12-24 02:13
I wasn't able to reproduce this bug using the steps provided.
Sucklifex, Nyeriah, is there anything specific I need to do? Or the issue isn't valid anymore?

**Comment by Keader** [comment] 2017-01-08 03:34
15 days without answers, so closing.

**Closed by Keader** 2017-01-08 03:34 UTC
Labels: Branch-3.3.5a, Feedback-WaitingResponse, Sub-Spells
