### ISSUE TITLE
[3.3.5][Hunter] Volley

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#18129] opened 2016-10-23 12:39 UTC
**Description**: it doesn't proc when aspect of the viper is active
**Branch(es)**: 3.3.5
**TC hash/commit** 7905c3cb877d5c3b101c50f3fc81c6df77b91c75:  
**TDB version**:  62
**Operating system**:  Linux

**Comment by tkrokli** [comment] 2016-10-23 12:53
proc? I thought Volley was a regular hunter spell cast, from the task bar. How are you trying to trigger it?

BTW: it would be nice with some more info around the problem itself, like spell ID etc.

**Comment by Keader** [comment] 2016-10-23 13:10
maybe is:
Aspect of the viper, dont proc with Volley.
Aspect of the viper, should return some % of mana with attacks.

**Comment by sucklifex** [comment] 2016-10-23 13:20
When SpellID 34074 ( Aspect of the Viper ) is active
SpellID 58431 should trigger  Aspect of the Viper, but it wont trigger

**Comment by Keader** [comment] 2016-10-23 13:30
@ariel-

**Comment by tkrokli** [comment] 2016-10-23 14:43
https://web.archive.org/web/20100731011248/http://www.wowhead.com/spell=34074

Details:

| Type | Value | Type | Value |
| ---- | ------ | ---- | ------ |
| Cost | None | Duration | n/a |
| Range | 0 yards (Self) | School | Nature |
| Cast time | Instant | Mechanic | n/a |
| Cooldown | 1 second | Dispel type | n/a |
| Effect # 1 | Apply Aura: Mod Total Power Regen % |
| | Value: 4 every 3 seconds |
| Effect # 2 | Apply Aura: Mod Damage Done % (127) |
| | Value: -50 |

- http://wotlk.openwow.com/spell=34074
- http://wotlk.openwow.com/spell=58431
- http://wotlk.openwow.com/spell=58432

**Comment by noryad** [comment] 2016-10-24 02:57
Sorry but you are wrong.
Aspect of the Viper causes each ranged attack (including the initial application of Serpent Sting, all three charges of Explosive Shot, all three missiles of Multi-Shot, **but not including the ticks of Serpent Sting or the damage of Volley**) to generate a percentage of the Hunter's maximum mana.

**Comment by ccrs** [comment] 2016-10-24 03:15
essentially, it shouldn't proc if there is no target hit
finally this is solved :D 

close the issue :3

**Closed** 2016-10-24 08:21 UTC

**Comment by sucklifex** [comment] 2016-10-24 12:53
@ccrs it event doesn't trigger if target exist, it doesn't proc at all

**Comment by Keader** [comment] 2016-10-24 12:58
@sucklifex  read https://github.com/TrinityCore/TrinityCore/issues/18129#issuecomment-255637766

**Comment by sucklifex** [comment] 2016-10-24 13:58
@noryad  @Keader  http://wow.gamepedia.com/Aspect_of_the_Viper

Patch 3.0.2 (2008-10-14): The hunter takes on the aspect of the viper, **causing ranged attacks** to regenerate mana but reducing total damage done by 50%. Mana is gained based on ranged weapons speed.

**Comment by noryad** [comment] 2016-10-24 14:30
@sucklifex 
Look the segment Mana Regeneration Formula in both web sities
http://wow.gamepedia.com/Aspect_of_the_Viper
http://wowwiki.wikia.com/wiki/Aspect_of_the_Viper
Literaly
Aspect of the Viper caused each ranged attack (including the initial application of [Serpent Sting], all three charges of [Explosive Shot], all three missiles of [Multi-Shot], **but not including the ticks of Serpent Sting or the damage of [Volley]**) to generate a percentage of the Hunter's maximum mana.

**Comment by DeActiver** [comment] 2016-11-02 01:01
now must wait for complete proc re-write :| , I hope to soon be completely resolved past errors :+1:

**Comment by DeActiver** [comment] 2016-11-05 12:02
-ariel don't have idea temporary for this problem ? Or you want to be completed ?

**Comment by tkrokli** [comment] 2016-11-05 15:36
@DeActiver : This is **not** a problem in TrinityCore source. If you want Aspect of the Viper to proc on Volley (not blizzlike), you have to find a solution elsewhere, because TrinityCore developers want to write the code so it works like it used to do back in 2008-2010. The spell is **working as intended** for the moment.

**Comment by DeActiver** [comment] 2016-11-05 16:24
so before Aspect of the Viper to proc on Volley was buged , now is ok , Thank you @tkrokli

**Comment by tkrokli** [comment] 2016-11-05 16:49
No, I mean that Aspect of the Viper does **not** proc on Volley, just as confirmed in https://github.com/TrinityCore/TrinityCore/issues/18129#issuecomment-255756883

> [Aspect of the Viper](http://wow.gamepedia.com/Aspect_of_the_Viper) causes each ranged attack (including the initial application of Serpent Sting, all three charges of Explosive Shot, all three missiles of Multi-Shot, **but not including the ticks of [Serpent Sting](http://wow.gamepedia.com/Serpent_Sting#Patches_and_hotfixes) or the damage of [Volley](http://wow.gamepedia.com/Volley)**) to generate a percentage of the Hunter's maximum mana.

**Comment by DeActiver** [comment] 2016-11-12 21:02
@tkrokli Aspect of the Viper does not proc on Volley yes!!!,  but number of hitted targets by the spell have problem for that % mana from volley damage? or no ?

**Comment by tkrokli** [comment] 2016-11-12 23:13
I don't know enough about those details. Please check available patch notes info online.

[![volley_335a](https://cloud.githubusercontent.com/assets/4903600/20242032/57908f56-a928-11e6-9760-4b316540ab35.png)](https://web.archive.org/web/20101003134007/http://www.wowhead.com/spell=1510)

[Spell Details, Volley (1510)](https://web.archive.org/web/20101003134007/http://www.wowhead.com/spell=1510)

| Type | Value | Type | Value |
| ---- | ------ | ---- | ------ |
| Cost | 17% of base mana | Duration | 6 seconds |
| Range | 35 yards (Medium-Long) | School | Arcane |
| Cast time | Channeled | Mechanic | n/a |
| Cooldown | n/a | Dispel type | n/a |
| Effect # 1 | Persistent Area Aura: Dummy
| | Value: 50 
| | Radius: 8 yards
| | Server-side script |
| Effect # 2 | Apply Aura: Periodically trigger spell |
| | Interval: 1 second |
| | [![Volley](http://cdn.openwow.com/wotlk/icons/medium/ability_marksmanship.jpg)](https://web.archive.org/web/20100923133841/http://www.wowhead.com/spell=42243) [Volley (42243)](https://web.archive.org/web/20100923133841/http://www.wowhead.com/spell=42243) |
***
[Spell Details, Volley (42243)](https://web.archive.org/web/20100923133841/http://www.wowhead.com/spell=42243)

| Type | Value | Type | Value |
| ---- | ------ | ---- | ------ |
| Cost | None | Duration | n/a |
| Range | 100 yards (Tower) | School | Arcane |
| Cast time | Instant | Mechanic | n/a |
| Cooldown | n/a | Dispel type | n/a |
| Effect | School Damage (Arcane) |
| | Value: 52 |
| | Radius: 8 yards |
***
http://wow.gamepedia.com/index.php?title=Volley&oldid=2358743

**Comment by DeActiver** [comment] 2016-11-12 23:37
I know Spells Details , volley is ok , and Aspect of the Viper is ok , "Aspect of the Viper+volley" not proc but one part not true , after a while Will notice . So End
