### ISSUE TITLE
Black Temple: High Warlord Naj'entus - broken movement

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#17461] opened 2016-06-26 12:29 UTC
**Description**: High Warlord Naj'entus cannot move around in his room correctly.

**Current behaviour**: When pulled by ranged spells, he cannot chase you. He stuck on his platform and sometimes "levitates". Path is really broken...

**Expected behaviour**: Boss should chase the target in all room.

**Steps to reproduce the problem**:
1. vmaps / mmaps enabled
2. `.go creature id 22887`
3. Start him out of "platform".
4. Pull inside of platform sometimes he can follow you, sometimes not.

Vid about it: https://youtu.be/35YBeRwPqcE

**Branch(es)**: 3.3.5

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/2710c655ffbbdb128e89609667d45fb02e4d818c

**TDB version**:  335.61

**Operating system**:  win10

**Comment by Keader** [comment] 2016-11-09 19:02
```sql
UPDATE `creature_template` SET `flags_extra`=`flags_extra`|536870912 WHERE `entry`=22887;
```

is not the proper fix, but is better that broken all fight :)

**Comment by jackpoz** [comment] 2016-11-10 11:59
could you check with .mmap chat commands if there are valid paths ? loading the tile in recastdemo https://github.com/jackpoz/recastnavigation should help too

**Comment by Keader** [comment] 2016-11-10 12:19
hmm
Using .mmap path , in some points in the room, has no "valid path"
look:

Najentus place: 
Keader's path to Keader:
Building: SmoothPath
Result: true - Length: 2 - Type: 8
StartPosition     (436.614, 773.312, 11.936)
EndPosition       (436.614, 773.312, 11.936)
ActualEndPosition (436.614, 773.312, 11.936)
![wowscrnshot_111016_091202](https://cloud.githubusercontent.com/assets/7120913/20176321/6adb95a2-a72e-11e6-9040-1c4b07bf7253.jpg)

A valid path:
![wowscrnshot_111016_091253](https://cloud.githubusercontent.com/assets/7120913/20176329/7565fb02-a72e-11e6-8cb2-a8ce0e3ffc04.jpg)

Some steps foward:
![wowscrnshot_111016_091308](https://cloud.githubusercontent.com/assets/7120913/20176348/856e48a6-a72e-11e6-8c00-5dceb348681d.jpg)


Creatures have path until this point:

Map: 564 (Black Temple) Zone: 3959 (Black Temple) Area: 3959 (Black Temple) Phase: 1
X: 448.299988 Y: 850.005981 Z: 12.438400 Orientation: 2.984510
![wowscrnshot_111016_091732](https://cloud.githubusercontent.com/assets/7120913/20176427/e95e42d0-a72e-11e6-839d-ac8e6170453f.jpg)

Any step forward dont find "a valid path" anymore

**Comment by akrom23** [comment] 2016-11-10 16:12
[![recast.png](https://s21.postimg.org/8jriib9ev/recast.png)](https://postimg.org/image/fzqs43x43/)

Everything seems to look good. But something is wrong with the platform(excatly in transiton between it and water - you can see it here: https://youtu.be/35YBeRwPqcE?t=183)

**Comment by jackpoz** [comment] 2016-11-10 16:24
the screenshots above are missing the *.mmtile loaded tho, there should be a button called "Load mmtile" or so. Then with Test Navmesh you can check why the pathfinding fails

**Comment by akrom23** [comment] 2016-11-10 16:53
Yeah, i've got this button, but when i click on it, only empty Log window appears.

**Comment by jackpoz** [comment] 2016-11-12 09:49
if you place .map, .mmap and .mmtile files in the Bin\Meshes folder it will load the pathfinding tile

**Comment by jackpoz** [comment] 2016-11-12 09:56
there's no walkable area outside of the platform and where there's water
![black temple](https://cloud.githubusercontent.com/assets/1153754/20236986/6c5d866c-a8c6-11e6-8705-0f33db06a2b5.png)

**Comment by ccrs** [comment] 2016-11-21 21:34
vmaps separate both regions with edges, so the pathgenerator simply cant cross the line.

I think those edges shouldnt be generated and instead use liquid detection in pathgenerator

**Comment by ccrs** [comment] 2016-11-21 21:40
Its like creating cliffs on each ground to water transition, doesnt make sense. Probably its an inherited behaviour or something like that.

**Comment by jackpoz** [comment] 2016-11-22 09:37
I'm not following what vmaps have to do in this case. When you say "it's like creating cliff" do you mean you debugged mmaps_generator and found that behavior ?

**Comment by ccrs** [comment] 2016-11-22 10:10
ah sorry brain fart, I meant mmaps

**Comment by ccrs** [comment] 2016-11-22 10:16
and when I did say it may be an inherited behaviour I meant mangos or w/e

the workaround that is done is
````bool farFromPoly = (distToStartPoly > 7.0f || distToEndPoly > 7.0f);````

**Comment by ccrs** [comment] 2016-11-22 10:24
soooo a workaround for the workaround:

- if there is a difference in liquids between the initial point and the destination use shortcut instead of pathfinding
(though its worth checking how much extra work does it add for the core to check that liquid data on every single generated path)

**Comment by akrom23** [comment] 2016-11-22 10:27
Shortcut is built only if all points from path is in water. In this situation, initial point is on the platform, so the result is no path.

**Comment by ccrs** [comment] 2016-11-22 10:29
read https://github.com/TrinityCore/TrinityCore/issues/17461#issuecomment-262201104 what u said is kinda unrelated.

**Comment by akrom23** [comment] 2016-11-22 10:30
Ok.

**Comment by ccrs** [comment] 2016-11-22 10:34
ok, nevermind its not kinda unrelated but a little bit different xd

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/PathGenerator.cpp#L202

here is the part where it checks if there is no reference for the path then it checks here https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/PathGenerator.cpp#L208 if it should actually create a shortcut, so doesnt depend on all the points being in the water or in the air, but just the destination or the initial point xd

so yeah, just a little bit different of what u said 💃

**Comment by ccrs** [comment] 2016-11-22 11:16
Also I don't know the filter logic (````void PathGenerator::CreateFilter()````, ````void PathGenerator::UpdateFilter()````) but feels like its not working as it should

**Comment by ccrs** [comment] 2016-11-22 12:07
so, making a recap, there are two solutions

**Easy**:
make a shortcut if there is a liquid difference between initial and final points
- problems:
under texture movements
![image](https://cloud.githubusercontent.com/assets/4329612/20522880/b82d9098-b0b2-11e6-88da-abc59232a0b2.png)
incorrect assumptions
![image](https://cloud.githubusercontent.com/assets/4329612/20522994/55fb2a38-b0b3-11e6-923d-76ab9c488684.png)
(and this could even be applied to charge paths, imagine the clown fiesta)

**Correct one**:
Mixed path
![image](https://cloud.githubusercontent.com/assets/4329612/20523263/7f8841fa-b0b4-11e6-8160-9c869a286962.png)
Is there a way to make this?
Calculate a poly based path till the "edge" and fill the remaning path with a shortcut?

**Comment by jackpoz** [comment] 2016-11-22 13:15
> soooo, didnt debug the creation process but checked the result I guess

That's useless, the bug is in the creation process, not in the result (and the result can be seen already at https://github.com/TrinityCore/TrinityCore/issues/17461#issuecomment-260112865 , it clearly shows where the walkable mesh is).

The whole initial part of Black Temple should be walkable, by looking at mmtile result in RecastDemo is looks like the liquid part is marked as non-walkable. Whether this is the actual issue or not should be checked debugging mmaps_generator tool. To me it makes no sense to handle that part as swimmable water.

**Comment by ccrs** [comment] 2016-11-22 13:21
I agree, but thats just a problem of maybe tolerance in "water level"
the surface is heigh enough for it to be defined as swimmable and therefore two areas are created with the so called "edge". You can move freely inside each area, but u cannot cross the frontier.

The real issue though is the one I've described, fix it and all the issues will be solved afaik.

**Comment by jackpoz** [comment] 2016-11-22 13:30
> the surface is heigh enough for it to be defined as swimmable

can you swim in it ? do creatures swim on it in retail ?

**Comment by ccrs** [comment] 2016-11-22 13:32
No, its considered as "normal floor".
I was not saying it was the correct behaviour, but describing the problem.

**Comment by ccrs** [comment] 2016-11-22 13:34
btw I dont know still the way to load maps on RecastDemo, how do u get the *.obj files?

**Comment by ccrs** [comment] 2016-11-22 19:27
````c++
G3D::Vector3 const end = endPos;
if (_sourceUnit->GetBaseMap()->IsInWater(end.x, end.y, end.z + 0.1f) && G3D::fuzzyGt(_sourceUnit->m_positionZ + 0.5f, end.z) && _sourceUnit->m_positionZ - end.z < 6.f)
{
    BuildShortcut();
    _type = PathType(PATHFIND_NORMAL | PATHFIND_NOT_USING_PATH);
    return;
}
````

like I said, a workaround for a workaround, but something like this might work.

**Comment by ccrs** [comment] 2016-11-22 19:36
well that worked
![image](https://cloud.githubusercontent.com/assets/4329612/20538890/618310c4-b0f3-11e6-949b-732ef38d6775.png)

**Comment by jackpoz** [comment] 2016-11-23 09:14
I don't understand why you are focusing on this workaround instead of the actual issue in mmaps_generator.

**Comment by ccrs** [comment] 2016-11-23 09:50
I am not focusing in the workaround (actually as you see its working so no need to think over that again).

The problem is to decide wether the "edges" are necessary or not. The choice is "simple"
- Erase the edges and rely on liquid detection
- Keep the edges and handle the transitions correctly

And if you want to focus on why this particular case is handled as water and not as ground, well it feels like an exception to me because the water level is a little bit higher than common cases. So dunnow if there is no will to enter into the main issue (at least for its the main issue) you can simply add the area in the map as an exception in the generator.

**Comment by Shauren** [comment] 2016-11-23 10:02
Did you test whether #18297 has any impact on it?

**Comment by ccrs** [comment] 2016-11-23 10:05
Nope, but seems kinda unrelated, right?

> Due to this typo some objects could be left out during BIH generation and thus never checked for intersection. This breaks height and LoS calculations in some areas.

**Comment by Keader** [comment] 2016-12-03 12:10
tested after 2402f476424531a175d9a016f433321f00608501 and no changes

**Comment by Killyana** [comment] 2016-12-03 16:31
I tested the new vmaps after #18297 it changes absolutely nothing for this issue or for https://github.com/TrinityCore/TrinityCore/issues/9753

**Comment by zorix** [comment] 2016-12-03 16:32
Please read https://github.com/TrinityCore/TrinityCore/pull/18364#issuecomment-264649509 and try again with changes in this PR if you can. (because maybe I made a mistake)

**Comment by Aokromes** [comment] 2016-12-03 16:52
0df0cb3

**Comment by Keader** [comment] 2019-12-25 01:02
I'm having this exactly issue again in rev 98f383695b537189af5be2f6e030d26a7b3adb9c
Something break it again. Najentus cant go out of platform.
.mmap path return 2 points like in https://github.com/TrinityCore/TrinityCore/issues/17461#issuecomment-259676287

**Comment by Keader** [comment] 2019-12-25 01:02
@jackpoz , @zorix can take a look?

**Comment by jackpoz** [comment] 2019-12-25 10:55
Please build the tile with debugOutput, load it in recastdemo (custom tc fork) and post a screenshot

**Comment by Killyana** [comment] 2019-12-25 13:26
Cannot reproduce, everything looks fine https://imgur.com/a/IPUOYZT

**Closed by Killyana** 2019-12-25 13:26 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Maps/MMaps/Vmaps
