### ISSUE TITLE
Spell/Druid "Prowl" (5215)

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#25936] opened 2021-01-24 19:14 UTC
**Description:**

Prowl set the Druid invisble but not in Catform

**Expected behaviour:**

Prowl should activate your catform and makes you invsible.

**Steps to reproduce the problem:**

1. Create a Druid
2. Use Prowl when you are in Human form

**Branch(es):**

master

**TC rev. hash/commit:** 

e601c6d1f9b9743e92e9562abd9f2d24d9aaf175

**Operating system:** 

Debian 10

**Comment by offl** [comment] 2021-01-25 15:54
Duplicate of #19742

**Closed by offl** 2021-01-25 15:54 UTC
Labels: Branch-master
