### ISSUE TITLE
[Quest] Help Those That Cannot Help Themselves

### ISSUE THREAD

**Issue by Bilibox** [TrinityCore/TrinityCore#26478] opened 2021-04-25 23:05 UTC
**Description:**

Spam clicking the D.E.H.T.A. Trap Smasher counts towards the quest objective multiple times.

Spawning the item in and using it on a Trapped Mammoth Calf will give you the cooldown and 1 second spell cast time, but when you have the quest No cast time is required and the Cooldown is non-existent allowing you to Spam click the item until you have completed the quest.

**Expected behaviour:**

The item given should have a 15 second cooldown, and only give you progress when casting has finished.

**Steps to reproduce the problem:**
1. Grab [Help Those That Cannot Help Themselves](https://wotlkdb.com/?quest=11876) from [Arch Druid Lathorius <D.E.H.T.A.>](https://wotlkdb.com/?npc=25809)
2. Find a [Trapped Mammoth Calf](https://wotlkdb.com/?npc=25850).
3. Spam click the [D.E.H.T.A. Trap Smasher ](https://wotlkdb.com/?item=35228) on the [Trapped Mammoth Calf](https://wotlkdb.com/?npc=25850).

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/d5f1fefe7f6772b11e9fbb052bfd36be9bda98e2

**Operating system:** 

Windows

**Comment by dr-j** [comment] 2021-04-26 08:34
This would have been converted to SAI a long time ago if there was not a load of different entries for this object each with own entry of which one is apawned of each entry (im not talking about the calf but the actual trap) which makes writing sai totarget trap problematic when theres like 20+ different entries of trap, much same issue as why ethereum prisons have not been converted to sai either due to huge variation in gobs used

**Comment by offl** [comment] 2021-05-22 16:20
Confirmed in 26cc8e1e2032
.go game id 188022
.q a 11876
use provided item once
no cast time, no cooldown
wait 5 sec, don't use item again
use provided item again

It works correctly only if you use item on already closed trap
Moreover it works correctly if count is 8/8

Spell and objects has no script and I even can't understand what exactly triggers the event

**Comment by dr-j** [comment] 2021-05-22 18:49
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/zone_borean_tundra.cpp#L1269

**Comment by offl** [comment] 2021-05-23 00:18
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/World/item_scripts.cpp#L222
Indeed, stupid item scripts
Well, that gives some hope

**Comment by malcrom** [comment] 2021-10-08 00:58
You guys comment on stuff but don't fix it.

**Comment by Jinnaix** [comment] 2021-10-08 08:43
It DOES need a sub if you never created a PTR account before.

**Comment by CraftedRO** [comment] 2024-10-05 08:18
4d083b074ff7307d8f492d6f55f315425f299720 cannot reproduce, most likely fixed by https://github.com/TrinityCore/TrinityCore/pull/28304

**Closed** 2024-10-05 09:16 UTC
Labels: Sub-Quests, Branch-3.3.5a
