### ISSUE TITLE
DB/Quest: Update 'Abandoned Mail' (12711)

### ISSUE THREAD

**Issue by Ayahuasca420** [TrinityCore/TrinityCore#26807] opened 2021-08-13 01:47 UTC
### Description

This quest is an auto-complete quest, but it's flags aren't actually correct.
The quest is only flagged 128 and should be 65536 more : 65664

**Story :**
I was testing some DK start zone and at this quest, when I took it it had no text nor objectives. It was endable at the same gameobject, but since I knew it was intended to be an auto-complete quest, I did not give it back. I gave it up, went to the DB and figured out the flags were incorrect. I edited it to be 65664 then performed a .reload quest_template on my realm and clicked on the mailbox again. It then worked as expected.

### SQL fix

```sql
--UPDATE `quest_template` SET `Flags` = 65664 WHERE `id` = 12711;
```

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 22b70a281ab3 2021-08-11 03:11:09 +0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by offl** [comment] 2021-08-14 13:02
Duplicate of #26052

**Comment by offl** [comment] 2021-08-14 13:03
And quest_template.flags should not be changed

**Closed by offl** 2021-08-14 13:02 UTC
Labels: Feedback-PatchFix, Comp-Database, Branch-3.3.5a
