### ISSUE TITLE
Creature/Movement: Creature fighting and movement behavior

### ISSUE THREAD

**Issue by Eredar** [TrinityCore/TrinityCore#18512] opened 2016-12-18 23:40 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Creatures stack in one position, when you pull a pack of them.

**Current behaviour:** If you pull a pack of npcs and move alittle they will eventually stack up in one point and even "sync" their animation,

**Expected behaviour:** On blizzard servers, after pursue they are spreading around their target (not only a player, but around other npc's too).

**Steps to reproduce the problem:**

1.  Create any character. 
2.  .levelup or modify hp untill you can handle few mobs at the same time and not die.
3.  Pull any 3-4-5 npcs at the same time (boars infront of Orgrimmar with arcane torrent for example) , and move a bit.

**Branch(es):** master

**TC rev. hash/commit:**  32570f7203bb27206f8eb1669a35fa6f0c8f931b

**TDB version:**  TDB 703.00

**Operating system:**  Win 10 x64 Pro

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Eredar** [comment] 2016-12-19 09:19
For example of blizzard server behavior:
https://www.youtube.com/watch?v=X1v8uIeOD7E

**Comment by malcrom** [comment] 2016-12-30 16:55
It seems in blizz they are assigned an attack angle.

**Comment by Rushor** [comment] 2016-12-30 17:08
More info info in https://github.com/dalaranwow/dalaran-wow/issues/1204

example how it should look like https://www.youtube.com/watch?v=GDAldody2YY

**Comment by Eredar** [comment] 2017-02-25 14:23
Any info on this issue? I figured out what causes twitching when creature is pursuing a player. Chase movement resets when the creature reach hitrange, but on retail it will not stop until player stop moving. Ie there shouldn't be chase cancelation if player is still moving. Also seems like npc performs simple distance check to other objects nearby once in a 3 seconds or something around that, so if they too close to their target (more than half hitrange) they making two steps back. And if they too close to any ally they make same two steps away from them.

**Comment by Eredar** [comment] 2017-02-25 14:26
Summon @Shauren

**Comment by Eredar** [comment] 2017-03-19 12:11
Actually not cosmetic, it has direct impact on the gameplay, npcs should not stack in one point as they doing right now. It makes many fights different, this issue is really annoying in the instances.

**Comment by malcrom** [comment] 2017-04-05 12:02
I may have an easy fix for this will test and report.

**Comment by Rushor** [comment] 2017-07-02 08:51
more information about it here: https://github.com/dalaranwow/dalaran-wow/issues/4711


**Current behaviour**: The way the mobs move and position themselves is not blizzlike. Three different current behaviors.

1. When you stand very close to their center, they just sit still.
2. When you strafe sideways, they don't predict your movement.
3. When you gather them up, they sit there and stack.

**Expected behaviour**: In retail, the mobs behaved differently.
1. When you stand very close to their center, they should back up a few steps and create some room between you and itself. This is helpful when you tank and need to back up the mob a short amount. Typically a boss.
2. When you strafe sideways, they move to where you're going to be ahead of time instead, usually causing them to catch up to you quicker if you are perpendicular to it. This is helpful to move mobs quicker around, which is beneficial for tanking.
3. When gathered, they try to separate in a cone-like pattern. This is helpful for loot. Like pulling a large pack of mobs and killing them all, you have an easier time looting all of them without going over the same mob a hundred times. It is also useful for knowing how many mobs you roughly have instead of guessing 5 or 10.
**Steps to reproduce the problem**:

1. Stand almost on top of the center of the mob. It doesn't back up.

2. Strafe perpendicular to the mob. It won't lead you.

3. Pull a bunch of mobs and confine them. They won't separate.

**Include proofs for this behaviour**:

Here is a video: https://www.youtube.com/watch?v=Yf47ZI42DY8. In the same order as the list. 

WotLK retail video: https://www.youtube.com/watch?v=KmOPuziOWuA. It's a tanking guide, but it mentions and/or shows all of these intended behavior being true in-game. Time stamps:

1. 3:01 to 3:41
2. 7:07 to 8:51
3. 6:07 to 6:50

**Comment by Eredar** [comment] 2017-07-02 20:29
I guess it could be done in CombatAI Update function. Two simple range checks for target and allies. I will test it later.

**Comment by Rushor** [comment] 2017-07-03 06:38
alright thanks @Eredar

**Comment by offl** [comment] 2020-09-12 23:33
Duplicate of #20922

**Closed by offl** 2020-09-12 23:33 UTC
Labels: Branch-3.3.5a, Branch-master, Comp-Core, Priority-Cosmetic, Sub-Entities
