### ISSUE TITLE
Core/Entity : new dialogs in WoW Legion

### ISSUE THREAD

**Issue by rksmw** [TrinityCore/TrinityCore#17992] opened 2016-09-24 17:07 UTC
**Description**:

Hello, I am trying to recreate the initial mission of the hunters of demons, someone has some idea of since it could do http://oi68.tinypic.com/x5umtc.jpg
What in warcraft the IIIrd was a dialog, now my question is, for this type of dialogs it is a necessary algun script in lua or in c ++

**Current behaviour**: not work

**Expected behaviour**: Tell us what should happen instead

--removed--

**Steps to reproduce the problem**:

1.It is necessary opcodes, or is just a matter of scrips

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue)

**Tags 7.0.3/22594**

Edited by DDuarte

**Comment by tkrokli** [comment] 2016-09-24 17:15
This looks like an "improved" duplicate of #17985. If issue #17985 is the same, please close the old one.

BTW, your issue looks more like a question than a report, so maybe post it in the TC Forum (https://community.trinitycore.org) instead?

**Comment by Nelidon** [comment] 2016-09-24 18:54
Conversation entity.

**Closed** 2017-05-14 09:40 UTC
Labels: Branch-master, Comp-Core, Sub-Entities
