### ISSUE TITLE
Halion HP Sharing

### ISSUE THREAD

**Issue by Nastrand** [TrinityCore/TrinityCore#9231] opened 2013-02-17 01:30 UTC
When halion enter to phase 2 and you must change to the twilight realm, the twilight halion must have is health in the same point of the normal halion, this is at 75% but in TC this doesn't work and when you change to the twilight realm, the twilight halion still having his health at 100% i think this caused because he get out of combat (because in the moment he  appear in the twilight realm dont have any enemy, because the players still in the normal realm for, at least, 2 more seconds)

Hash: 2d861b71ce9753ffa4d899acdbb0ca44bcb13128
TDB 50

Halion Entry: 39863
Twilight halion: 40142
Controller Halion: 40146

**Comment by Nikectory** [comment] 2016-01-26 14:12
Confirmed on rev https://github.com/TrinityCore/TrinityCore/commit/f4e2fb8f79e5a223506d9e514b7adf18c2198bab

Also the boss doesn't leave combat state and reset position after disengaging or a raid wipe, making impossible to re-enter the istance and retrieve corpse, which this basically makes impossibile to repeate the fight.
Should I open a separate issue for this?

**Comment by Warpten** [comment] 2016-07-05 09:06
Closing since PR fixed that, reopen if still broken

**Closed by Warpten** 2016-07-05 09:06 UTC
Labels: Comp-C++Script, Sub-Instances
