### ISSUE TITLE
After update & recompile, Server & DBErrors log

### ISSUE THREAD

**Issue by zmple** [TrinityCore/TrinityCore#18022] opened 2016-09-29 06:05 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: Recently i update the code and recompile my local server and client resource(Database has already autoupdate), after that, i start the worldserver, a lot of errors/warnings come out in DBErrors.log, about GameObject,spell,NPCText,Table creature_model_info etc. Long time for searching past and recompile could not resolve the problem, it seems my Database isn't match the core. My friends also get this bug, i will append my log in Mega share link, how can i do, thx:)

**DBErrors.log**: https://mega.nz/#!91cRWKyA!dG62USW-9L5dO7NPUJFi6nAmRU5Qcu2VWzGsN5zUJMM

**Some Detail Species**: 
1. Spell `17` did not pass Validate() function of script `spell_pri_power_word_shield` - script will be not added to the spell
2. GameObject (Entry: 126337 GoType: 8) have data0=2061 but SpellFocus (Id: 2061) not exist.
3. The spell 57933 listed in `spell_group` does not exist
4. NPCText (ID: 518) has a probability (Index: 0) set, but no BroadcastTextID to go with it
5. Creature (Entry: 78837) has non-existing faction template (0).
Creature (Entry: 78837) has invalid unit_class (0) in creature_template. Set to 1 (UNIT_CLASS_WARRIOR).
6. Creature (ID: 56923, Expansion: 3) has different `HealthScalingExpansion` in difficulty 1 mode (ID: 57704, Expansion 0).
...

**Branch(es)**: 6.x / 7.x new

**TDB version**:  6.04

**Operating system**:  Mac OS 10.11.6

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by DDuarte** [comment] 2016-09-29 06:07
You didn't seem to do anything wrong, those errors are expected since they were not fixed (yet).

**Comment by DDuarte** [comment] 2016-09-29 06:08
Dupe of #15829

**Closed by DDuarte** 2016-09-29 06:08 UTC
Labels: Branch-6.x, Invalid-Duplicate
