### ISSUE TITLE
[Quest] Blood Quickening

### ISSUE THREAD

**Issue by pak3935** [TrinityCore/TrinityCore#15733] opened 2015-10-18 18:37 UTC
http://www.wowhead.com/quest=24879/blood-quickening
have fixed on this quest?
TrinityCore rev. 601c46f63d10 2015-07-13 21:05:41 +0200 (3.3.5 branch) (Win64, Debug)

**Comment by tkrokli** [comment] 2015-10-18 20:05
This was only available in the patches 3.3.2 - 3.3.5a, raid quest, 10 or 25 man. Anyone done it lately?

**Comment by Rushor** [comment] 2015-10-19 17:43
no learn english and fullfill the objectives given by http://collab.kpsn.org/display/tc/The+Issuetracker+and+You
closing is wrong here @pak3935

**Comment by tkrokli** [comment] 2015-10-19 18:17
Rushor, do you know that quest 24879 is bugged? I was thinking about testing it 20 hours ago, but I would have to go there with only 1 player character, which would not meet regular raid requirements. Since that would be cheating, using the worldserver.conf option to ignore raid, it could compromise the test quite a lot, I think. I would also need to use a lot of other cheat options from a single character. Not sure how valid a test will be without using anything from 5 to 10 players.

**Comment by Rushor** [comment] 2015-10-19 19:10
i got some reports that sometimes the player does not get the questcredit even if Infiltrator Minchar is successfully rescued. some people assume that the reason for this is, that the player was infight and it failed because of this - need to investigate this further

**Comment by tkrokli** [comment] 2015-10-19 19:16
OK, I guess that could be reason good enough to reopen this issue (but I don't know for sure).

**Comment by Rushor** [comment] 2015-10-19 20:02
@pak3935 should describe detailed how he reproduced the bug

**Comment by tkrokli** [comment] 2015-10-19 20:59
Yes, that was sort of what I tried to ask for in my first comment here, although it probably was unclear.

**Comment by Nyeriah** [comment] 2015-10-19 22:30
The 25m version of the quest used to not work because you get credit for 10m in 25 too

**Comment by Rushor** [comment] 2015-10-20 08:38
well then

```diff
diff --git a/src/server/scripts/RG/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp b/src/server/scripts/RG/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp
index 93d3761..2b48cee 100644
--- a/src/server/scripts/RG/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp
+++ b/src/server/scripts/RG/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp
@@ -229,7 +229,7 @@ class boss_blood_queen_lana_thel : public CreatureScript
                 {
                     instance->SetData(DATA_BLOOD_QUICKENING_STATE, DONE);
                     if (Player* player = killer->ToPlayer())
-                        player->RewardPlayerAndGroupAtEvent(NPC_INFILTRATOR_MINCHAR_BQ, player);
+                        player->RewardPlayerAndGroupAtEvent(Is25ManRaid() ? NPC_INFILTRATOR_MINCHAR_BQ_25 : NPC_INFILTRATOR_MINCHAR_BQ, player);
                     if (Creature* minchar = me->FindNearestCreature(NPC_INFILTRATOR_MINCHAR_BQ, 200.0f))
                     {
                         minchar->SetUInt32Value(UNIT_NPC_EMOTESTATE, 0);

diff --git a/src/server/scripts/RG/Northrend/IcecrownCitadel/icecrown_citadel.h b/src/server/scripts/RG/Northrend/IcecrownCitadel/icecrown_citadel.h
index 0153e3c..209f35a 100644
--- a/src/server/scripts/RG/Northrend/IcecrownCitadel/icecrown_citadel.h
+++ b/src/server/scripts/RG/Northrend/IcecrownCitadel/icecrown_citadel.h
@@ -173,6 +173,7 @@ enum CreaturesIds
     NPC_ALCHEMIST_ADRIANNA                      = 38501,
     NPC_ALRIN_THE_AGILE                         = 38551,
     NPC_INFILTRATOR_MINCHAR_BQ                  = 38558,
+    NPC_INFILTRATOR_MINCHAR_BQ_25               = 39123,
     NPC_MINCHAR_BEAM_STALKER                    = 38557,
     NPC_VALITHRIA_DREAMWALKER_QUEST             = 38589,
```

**Comment by pak3935** [comment] 2015-10-20 12:32
@Rushor thanks for the fix

**Comment by Rushor** [comment] 2015-10-20 12:51
@pak3935 : do not close issues until they are fixed in the repo. use http://collab.kpsn.org/display/tc/Creating+a+Pull+Request to create a pullrequest for the fix, if you have time for this

**Closed** 2015-10-23 10:06 UTC
