### ISSUE TITLE
SMART_EVENT_JUST_SUMMONED

### ISSUE THREAD

**Issue by humaniti** [TrinityCore/TrinityCore#17408] opened 2016-06-17 18:46 UTC
**Description**:
SMART_EVENT_JUST_SUMMONED Smart AI event is not working in the latest  rev.

**Current behaviour**:
SMART_EVENT_JUST_SUMMONED is just doing nothing, if the NPC is scripted this way.
**Expected behaviour**:ell us what should happen instead
If event type is Just Summoned, if the NPC get summoned by any Smart Script or C++ script, he should start doing the script

EDIT: If you summon the creature by .npc add or spell it works, but if you add it with SmartAI Spawn it not works.

**AS a workaround, we've figured out, that if SmartAI summons an NPC with  the (SMART_ACTION_SUMMON_CREATURE) action type, the spawned npc will not do anything to the following events:
SMART_EVENT_RESET = 25
SMART_EVENT_RESPAWN = 11
SMART_EVENT_UPDATE_OOC = 1
SMART_EVENT_JUST_SUMMONED = 54

If you manually spawn the npc with .npc add, the script works, but if smartAi summons the npc, it does nothing.**

**Steps to reproduce the problem**:
1. Make a `smart_script` with `SMART_EVENT_JUST_SUMMONED (54)`
2. Try it out

**Branch(es)**: 3.3.5 / 6.x 
6.x

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/5da217877be7f22db3bfc8ee06ca1ffad172d281

**TDB version**:  Latest TDB

**Comment by P-Kito** [comment] 2016-06-17 19:02
It was working for me a long time, dont see a reason why I should bug now ;o

**Comment by Ulduar** [comment] 2016-06-17 19:05
Field creature_entry not empty?
``` CPP
struct
        {
            uint32 creature;
            uint32 cooldownMin;
            uint32 cooldownMax;
        } summoned;
```
I could be wrong, but the field uint32 creature; should not be 0.

**Comment by dr-j** [comment] 2016-06-17 19:06
Well from previous experience with 3,3,5 event 54 does not work on all npcs, if a npc is spawned by sai (not spell) or you just npc add temp to spawn the npc the event will always start, most of the times it also works when the creature is summoned by a spell but I have came across several npcs which are summoned by spells which refuse to run actions triggered using event 54 and have ended up having to substitute sai action 11 to trigger event instead but ok since none of the creatures spawned in worldby default.

**Comment by humaniti** [comment] 2016-06-17 19:09
@dr-j  thanks for pointing out this, edited the main report.
EDIT: If you summon the creature by .npc add or spell it works, but if you add it with SmartAI Spawn it not works.

**Comment by dr-j** [comment] 2016-06-17 19:13
What summontype are you using in the sai and if spell to summon works why not write the sai to summon via spell if theres a spell to summon the creature in question and it works if summoned by spell as if theres a spell to summon a temp creature this is usually the correct way to temp spawn it or the spell which triggers that spell p:

**Comment by humaniti** [comment] 2016-06-17 19:15
@dr-j Timed_Despawn (id 3)

**Comment by Killyana** [comment] 2016-06-17 19:16
You have to provide the script, no one can guess why it doesn't work.

**Comment by humaniti** [comment] 2016-06-17 19:17
-- Portal from Orgrimmar
SET @ENTRY := 44630;
SET @SOURCETYPE := 0;

DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=@SOURCETYPE;
UPDATE creature_template SET AIName="SmartAI" WHERE entry=@ENTRY LIMIT 1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES 
(@ENTRY,@SOURCETYPE,0,0,54,0,100,0,0,0,0,0,11,55761,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Ogrimmar Portal - Cast Animation");

For instance, this should cast an effect spell on the spell itself if just_summoned, but doing nothing. The interesting fact, these scripts worked 1-2 week ago.

**Comment by Ulduar** [comment] 2016-06-17 19:22
``` CPP
ID - 55761 Air Revenant Entrance
=================================================

Category = 0, SpellIconID = 1, activeIconID = 0, SpellVisual = (12183,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000 [3] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x00000180 (SPELL_ATTR0_HIDDEN_CLIENTSIDE, SPELL_ATTR0_HIDE_IN_COMBAT_LOG)
AttributesEx1: 0x00000040 (SPELL_ATTR1_CHANNELED_2)
AttributesEx5: 0x00000001 (SPELL_ATTR5_UNK0)
=================================================
Spell Level = 0, base 0, max 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRangeNegative = 0, MinRangePositive = 0
    MaxRangeNegative = 0, MaxRangePositive = 0

Cast time (Id 1) = 0,00

Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 0, charges - 0
=================================================
Effect 0: Id 46 (SPELL_EFFECT_SPAWN) DIFFICULTY_NONE
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
```

**Comment by Killyana** [comment] 2016-06-17 19:22
How 44630 is summoned?

**Comment by Ulduar** [comment] 2016-06-17 19:23
http://www.wowhead.com/npc=44630/portal-from-orgrimmar

**Comment by humaniti** [comment] 2016-06-17 19:27
http://www.wowhead.com/quest=26965/

**Comment by Ulduar** [comment] 2016-06-17 19:28
Ah yes, Sylvana quest. Yes, spell should not have aura and duration. Only simple effect.

**Comment by humaniti** [comment] 2016-06-17 19:29
If you cast the spell with .cast  , it shows the effect, so it kinda works, just the just_summoned thingy makes nothing there.

**Comment by Ulduar** [comment] 2016-06-17 19:30
Then I do not understand anything. It is necessary to look in the kernel code. Maybe there will be an answer to the question.

**Comment by Ulduar** [comment] 2016-06-17 19:34
@humaniti i'll found similar issue https://github.com/TrinityCore/TrinityCore/issues/13045

**Comment by humaniti** [comment] 2016-06-17 19:35
@Ulduar oh seems to be interesting, but i still dont see the point, why is this not working as intended.

**Comment by Ulduar** [comment] 2016-06-17 19:37
You still try to use 63 events. Can be used on creature and GO. 54 used only for creature.

**Comment by humaniti** [comment] 2016-06-17 19:39
@Ulduar I'm gonna look into this, but gonna leave this issue here, because its still an issue :dancer:

**Comment by Ulduar** [comment] 2016-06-17 19:40
While the issue is not solved, use 63 event instead of 54 event.

**Comment by humaniti** [comment] 2016-06-17 19:42
@Ulduar Thank you for pointing on this, nice help!:)

**Comment by Ulduar** [comment] 2016-06-17 19:43
Try it and please report the result!

**Comment by humaniti** [comment] 2016-06-17 19:44
@Ulduar tried out, if i spawn the npc with .npc add it casts the effect, but with smartAI summon, it makes nothing.

**Comment by Ulduar** [comment] 2016-06-17 19:52
You restart server after apply SmartScript with event 63.

**Comment by humaniti** [comment] 2016-06-17 19:53
Ofc  i did :D

**Comment by Ulduar** [comment] 2016-06-17 19:58
Try again with SMART_EVENT_RESET = 25, or SMART_EVENT_RESPAWN = 11,.

**Comment by humaniti** [comment] 2016-06-17 20:02
With SMART_EVENT_RESET = 25 same effect, if summoned by script, does nothing, if summoned with .npc add it casts the spell.
With SMART_EVENT_RESPAWN = 11 same.

**Comment by Ulduar** [comment] 2016-06-17 20:04
Then I do not understand anything.

**Comment by humaniti** [comment] 2016-06-17 20:06
It can be an issue with the Summon, but im sure these things worked 2 weeks ago.

**Comment by Ulduar** [comment] 2016-06-17 20:11
Creature not have extraflag = 128? Or Pacify, Silence unit flags?

**Comment by humaniti** [comment] 2016-06-17 20:15
npcflag =  0
unit_flags = 33555200 - to be unselected
unit_flags2 = 2048 - from sniffs
flags_extra =  0

**Comment by humaniti** [comment] 2016-06-17 20:18
Seems strange, because if NPC has OOC Script (id - 0) and gets summoned via SmartAI , it makes nothing also, im getting more and more sure that this is wrong by NPC spawning with SmartAI

**Comment by Ulduar** [comment] 2016-06-17 20:27
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/scripts/Kalimdor/HallsOfOrigination/boss_earthrager_ptah.cpp#L230
``` CPP
case EVENT_QUICKSAND:
                        // Spell not in DBC, it is not cast either, according to sniffs
                        if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100.0f, true))
                            if (Creature* quicksand = me->SummonCreature(NPC_QUICKSAND, *target))
                                quicksand->SetUInt32Value(UNIT_CREATED_BY_SPELL, SPELL_SUMMON_QUICKSAND);
                        events.ScheduleEvent(EVENT_QUICKSAND, 10000, 0, PHASE_DISPERSE);
                        break;
```
Maybe add this in core. Something like that. We summon the creature with SAI and send UNIT_FIELD = UNIT_CREATED_BY_SPELL. For it is thought that he was summoned to spell and see what happens. Nothing else comes to me until things.

**Comment by Ulduar** [comment] 2016-06-17 20:31
/cast Summon @Shauren 
What do you think? You may suggest how to be? Thanks advance.

**Comment by humaniti** [comment] 2016-06-17 20:43
@Ulduar send it in packet?

**Comment by Ulduar** [comment] 2016-06-17 21:10
Last try with https://github.com/TrinityCore/TrinityCore/blob/92b74d6bdcff0f23aa1e1b8c76889ed5aacd4a5b/src/server/game/AI/SmartScripts/SmartScriptMgr.h#L141
``` SQL
-- <Could not generate name> SAI
SET @ENTRY := 44630;
UPDATE creature_template SET AIName="SmartAI" WHERE entry=@ENTRY LIMIT 1;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,37,0,100,0,0,0,0,0,78,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Portal From Orgrimmar - On Init - Call Script Reset."),
(@ENTRY,0,1,0,25,0,100,0,0,0,0,0,11,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Portal From Orgrimmar - On Reset - Cast Spell Air Revenant Entrance on Self.");
```

**Comment by humaniti** [comment] 2016-06-18 07:57
@Ulduar with this, nothing happens.

**Comment by Ulduar** [comment] 2016-06-18 20:57
Try last last again used with SMART_ACTION_SUMMON_CREATURE_GROUP,  instead SMART_ACTION_SUMMON_CREATURE.
All, not have more idea.

**Comment by humaniti** [comment] 2016-06-20 16:59
@Shauren any idea why SMART_ACTION_SUMMON_CREATURE summons Creatures, and they do not do anything?

**Comment by tkrokli** [comment] 2016-06-21 03:34
Might be an opcode issue, but I suppose that needs to be verified. Another example is that some NPCs don't cast quest reward spell upon quest completion, like The Kessel Run:
- http://www.wowhead.com/quest=9663/the-kessel-run
- https://gnaxi.net/wow/keira2/#/quest/9663

**Comment by humaniti** [comment] 2016-06-21 06:26
@tkrokli interesting fact, whats the difference between .npc add, and SMART_ACTION_SUMMON_CREATURE?

**Comment by humaniti** [comment] 2016-06-21 06:26
in core ofc

**Comment by tkrokli** [comment] 2016-06-21 07:30
It is not so much about the actual SMART_ACTION feature as it is about scripted vs player SpellCast. I can't say for sure because I don't know exactly what causes it, but if you take a look at the newest PR created 15 minutes ago ("fix ItemUpgrade..") you will see what kind of work could be needed to fix it.

**Comment by Ulduar** [comment] 2016-06-24 16:16
You can test this:
https://github.com/TrinityCore/TrinityCore/commit/587710feb5f4de21204900d57c7a34320aadb85e#diff-254c10a38aa23d502bc3288b35f3fd0fR51
Used summon npc without spell, but send UNIT_CREATED_BY_SPELL (spell not exist in dbc in comment)
Maybe we can add Something similar. Yes it is hack, but it may be working hack.
Making the kernel think that NPC was caused by a spell!
P.S: Quicksand used SAI. https://github.com/TrinityCore/TrinityCore/commit/587710feb5f4de21204900d57c7a34320aadb85e#diff-254c10a38aa23d502bc3288b35f3fd0fR51

**Comment by Ulduar** [comment] 2016-07-08 17:13
``` CPP
case SMART_ACTION_SUMMON_CREATURE:
        {
            ObjectList* targets = GetTargets(e, unit);
            if (targets)
            {
                float x, y, z, o;
                for (ObjectList::const_iterator itr = targets->begin(); itr != targets->end(); ++itr)
                {
                    (*itr)->GetPosition(x, y, z, o);
                    x += e.target.x;
                    y += e.target.y;
                    z += e.target.z;
                    o += e.target.o;
                    if (Creature* summon = GetBaseObject()->SummonCreature(e.action.summonCreature.creature, x, y, z, o, (TempSummonType)e.action.summonCreature.type, e.action.summonCreature.duration))
                        summon->SetUInt32Value(UNIT_CREATED_BY_SPELL, e.action.summonCreature.createdSpellId);
                }

                delete targets;
            }

            if (e.GetTargetType() != SMART_TARGET_POSITION)
                break;

            if (Creature* summon = GetBaseObject()->SummonCreature(e.action.summonCreature.creature, e.target.x, e.target.y, e.target.z, e.target.o, (TempSummonType)e.action.summonCreature.type, e.action.summonCreature.duration))
                summon->SetUInt32Value(UNIT_CREATED_BY_SPELL, e.action.summonCreature.createdSpellId);
            break;
        }
```

``` CPP
struct
        {
            uint32 creature;
            uint32 type;
            uint32 duration;
            uint32 createdSpellId;
        } summonCreature;
```
@humaniti you can test with in game. Created spell  you can pointer = 75550 (spell not exist in dbc.)
attackInvoker deleted, because useless.

**Comment by Ulduar** [comment] 2016-08-14 15:36
@humaniti 
@tkrokli 
My suggested solution testing in game and working.
Also add SetData for summon creature (various creature for example can have different waypoint, Sunwell epilogue event - http://www.wowhead.com/npc=26289 Shattered Sun Riftwaker
for example.

SAI Core:
``` CPP
case SMART_ACTION_SUMMON_CREATURE:
        {
            ObjectList* targets = GetTargets(e, unit);
            if (targets)
            {
                float x, y, z, o;
                for (ObjectList::const_iterator itr = targets->begin(); itr != targets->end(); ++itr)
                {
                    (*itr)->GetPosition(x, y, z, o);
                    x += e.target.x;
                    y += e.target.y;
                    z += e.target.z;
                    o += e.target.o;
                    if (Creature* summon = GetBaseObject()->SummonCreature(e.action.summonCreature.creature, x, y, z, o, (TempSummonType)e.action.summonCreature.type, e.action.summonCreature.duration))
                    {
                        summon->SetUInt32Value(UNIT_CREATED_BY_SPELL, e.action.summonCreature.createdSpellId);
                        summon->AI()->SetData(e.action.summonCreature.setField, e.action.summonCreature.setData);
                    }
                }

                delete targets;
            }

            if (e.GetTargetType() != SMART_TARGET_POSITION)
                break;

            if (Creature* summon = GetBaseObject()->SummonCreature(e.action.summonCreature.creature, e.target.x, e.target.y, e.target.z, e.target.o, (TempSummonType)e.action.summonCreature.type, e.action.summonCreature.duration))
            {
                summon->SetUInt32Value(UNIT_CREATED_BY_SPELL, e.action.summonCreature.createdSpellId);
                summon->AI()->SetData(e.action.summonCreature.setField, e.action.summonCreature.setData);
            }
            break;
        }
```
``` CPP
struct
        {
            uint32 creature;
            uint32 type;
            uint32 duration;
            uint32 createdSpellId;
            uint32 setField;
            uint32 setData;
        } summonCreature;
```

SQL for example:
``` SQL
-- Summon Enabler Stalker SAI
SET @ENTRY := 200000;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,38,0,100,0,20,20,0,0,64,10,0,0,0,0,0,7,0,0,0,0,0,0,0,"Summon Enabler Stalker - On Data Set 20 20 - Store Targetlist"),
(@ENTRY,0,1,0,60,0,100,1,15000,15000,0,0,70,0,0,0,0,0,0,10,452563,74347,0,0,0,0,0,"Summon Enabler Stalker - On Update - Respawn Closest Creature 'Mordresh Fire Eye' (No Repeat)");

-- Mordresh Fire Eye SAI
SET @ENTRY := 74347;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,60,0,100,1,1000,1000,0,0,71,0,0,12784,0,0,0,1,0,0,0,0,0,0,0,"Mordresh Fire Eye - On Update - Change Equipment (No Repeat)"),
(@ENTRY,0,1,0,0,0,100,0,2400,3600,5500,7700,11,150001,0,0,0,0,0,2,0,0,0,0,0,0,0,"Mordresh Fire Eye - In Combat - Cast Lava Burst"),
(@ENTRY,0,2,0,0,0,100,0,15000,17000,17000,17000,11,150015,0,0,0,0,0,5,0,0,0,0,0,0,0,"Mordresh Fire Eye - In Combat - Cast Summon Blazing Servitor"),
(@ENTRY,0,3,0,4,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Mordresh Fire Eye - On Aggro - Say Line 0"),
(@ENTRY,0,4,0,6,0,100,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Mordresh Fire Eye - On Just Died - Say Line 1"),
(@ENTRY,0,5,0,5,0,100,0,0,0,0,0,1,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Mordresh Fire Eye - On Killed Unit - Say Line 3"),
(@ENTRY,0,6,0,1,0,100,0,14000,14000,14000,16000,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,"Mordresh Fire Eye - Out of Combat - Say Line 2"),
(@ENTRY,0,7,0,60,0,100,0,1000,1000,0,0,5,10,0,0,0,0,0,0,0,0,0,0,0,0,0,"Mordresh Fire Eye - On Update - Play Emote 10"),
(@ENTRY,0,8,0,7,0,100,0,0,0,0,0,12,200000,1,20000,75550,20,20,1,0,0,0,0,0,0,0,"Mordresh Fire EyE - On Evade - Summon Enable Stalker and Set Created Spell for Summon Enable Stalker and Set Data 20 20."),
(@ENTRY,0,9,0,7,0,100,0,0,0,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Mordresh Fire EyE - On Evade - Despawn Instant.");

DELETE FROM `spell_scripts` WHERE `id` = 150015;
INSERT INTO `spell_scripts` (`id`, `effIndex`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES
('150015','0','0','15','150067','0','0','0','0','0','0');

DELETE FROM `creature_text` WHERE `entry` = 74347;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
('74347','0','0','Your bones will be added to this pile!  Burn!','14','0','100','0','0','45954','78546','3','Mordresh Fire Eye SAY_AGGRO'),
('74347','1','0','I have fallen before...','14','0','100','0','0','45955','80142','3','Mordresh Fire Eye SAY_DEATH'),
('74347','2','0','Soon Amnennar will return!','14','0','100','0','0','45956','78481','3','Mordresh Fire Eye SAY_CONQUEROR_1'),
('74347','2','1','Our conquest of Kalimdor begins and nothing will survive our wrath!','14','0','100','0','0','45957','78482','3','Mordresh Fire Eye SAY_CONQUEROR_2'),
('74347','3','0','Too hot for you?','14','0','100','0','0','45958','78547','3','Mordresh Fire Eye SAY_KILL_1'),
('74347','3','1','Another soldier for Amnennar\'s army.','14','0','100','0','0','45959','78548','3','Mordresh Fire Eye SAY_KILL_2'),
('74347','3','2','You\'ll dance the rest!','14','0','100','0','0','45960','78549','3','Mordresh Fire Eye SAY_KILL_3');

DELETE FROM `creature` WHERE `id` = 74347;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `PhaseId`, `PhaseGroup`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
('452563','74347','129','0','0','2','0','0','0','0','2462.51','675.627','63.8982','5.20222','43200','0','0','1761372','36246','0','0','0','0','0');
```
Aggro Mordresh and evade (target seld and use command .gm on or .combat) 
And wait. Summon Enable Stalker SAI working and respawn Mordresh.

**Comment by Ulduar** [comment] 2016-08-15 19:57
Any feedback?

**Comment by tkrokli** [comment] 2016-08-16 05:14
Looks like you could open a Pull Request with your material above. Looks interesting, because I have started looking into how to fix the bugs in the SAI script for the Quest http://www.wowhead.com/quest=13549/tails-up .

The current SAI now puts the beasts to sleep when they become male entries, not right after the blowgun has been used on them. I also got some SAI errors in DBErrors.log which suggests that maybe the wrong `creature_template`.`entry` is used for the summoned creatures (changing template entry on the Frost Leopards and Icepaw Bears). I thought about using event 54 `SMART_EVENT_JUST_SUMMONED`, to make the summoned entries say their quest related texts (Boss Whisper, 42), but I see that won't work as I had thought (or at least not yet, in any case).

**Comment by humaniti** [comment] 2016-08-16 15:07
@Ulduar Hello!
Thanks for the review, strange thing, in the latest rev, the SAI started to work again... eh.

**Comment by Ulduar** [comment] 2016-08-16 16:10
@humaniti 
@tkrokli 
Indeed strange, 
You can add script SAI in core separately and test may either work.

@tkrokli About pull request - you can open pr, if you want. Trinity Core member have a better chance to be heard.

**Comment by tkrokli** [comment] 2016-08-16 17:51
I am a bit confused now, it took some time before I noticed that @humaniti reported this issue on 6.x and I have not actually been able to verify if it works or not on 3.3.5 (I am mostly focused on 3.3.5). Because **dr-j** mentioned that it does not work on all NPCs in 3.3.5, I thought it was an issue for both branches and that maybe your code posted above would fix that particular issue with some NPCs not working with event 54 `SMART_EVENT_JUST_SUMMONED`. I would like some more confirmation if that code will solve it before I go ahead with opening a PR for it, because PR code should be verified as solving an issue, notably verified by the PR author.

**Comment by Ulduar** [comment] 2016-08-16 18:33
New code suggested set created spell, in issue it pointed out that if the NPC is summoned with the help of spells, it SAI working. I thought, what if we add the ability to change UNIT_CREATED_BY_SPELL, to NPC thought that he was called by a spell.
Also SetData for npc, has having the same record, but you need to perform different actions. To avoid static spawn and run through guid. Here for example Shattered Sun Riftwaker, have two different positions and different spawn movepoint.

On 6.x testing on Mordresh Fire Eye, Summon Enable Stalker run SAI. And respawn Mordresh.
@dr-j say, what on 3.3.5 not working too. Not testing on 3.3.5, but 6.x solution testing.

**Comment by xinef1** [comment] 2017-01-28 13:18
Tested and can't confirm, works fine. Also checked the code and see no issues with AI selection.

**Comment by Lopfest** [comment] 2017-07-30 18:26
I would like to add a few things.
Creatures summoned by spells also doesn't respond to SAI events.
Example of spells:
- 128700 - Summon Spirit of Fire
- 107784 - Summon Ox Cart, Cursed Pools -> Farmlands
- 103538 - Summon Spirit of Water
- 104017 - Summon Spirit of Water
- 114453 - Summon Ox Cart, Farmlands -> Temple

Creatures are also not responding to SMART_EVENT_SPELLHIT

**Comment by Lopfest** [comment] 2017-10-03 18:21
possibly fixed by this commit d7c85d719306ad6f3e239e7e43975eb70bbdbc9f

**Comment by tkrokli** [comment] 2017-10-03 22:11
@humaniti : can you confirm that it works now, so this issue can be closed?

**Comment by msoky** [comment] 2018-03-25 18:25
any news? can be closed?

**Comment by Killyana** [comment] 2018-03-25 19:16
Yes looks to be fixed:
``` sql
-- Portal from Orgrimmar
SET @ENTRY := 44630;
SET @SOURCETYPE := 0;

DELETE FROM `smart_scripts` WHERE `entryorguid` IN (321,@ENTRY) AND `source_type`=@SOURCETYPE;
UPDATE creature_template SET AIName="SmartAI" WHERE entry IN (321,@ENTRY);
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES 
(@ENTRY,@SOURCETYPE,0,0,54,0,100,0,0,0,0,0,11,55761,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Ogrimmar Portal - Cast Animation"),
(321,@SOURCETYPE,0,0,1,0,100,1,0,0,0,0,12,@ENTRY,8,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Ogrimmar Portal - Cast Animation");

**Closed by Killyana** 2018-03-25 19:16 UTC
Labels: Branch-master
