### ISSUE TITLE
Samophlange:After receiving the task, the task object status will not be refreshed.

### ISSUE THREAD

**Issue by TS-BAH** [TrinityCore/TrinityCore#29393] opened 2023-10-26 14:19 UTC
### Description

Samophlange
Close off the Fuel Control Valve, the Regulator Valve and the Main Control Valve then use the control console again.
 
Shut off Main Control Valve
 
Shut off Fuel Control Valve
 
Shut off Regulator Valve

After receiving the task, the task object status will not be refreshed.
You need to log out and log in again.

### Expected behaviour

no

### Steps to reproduce the problem

no

### Branch

3.3.5

### TC rev. hash/commit

no

### Operating system

Windows 10 x64

### Custom changes

no

**Comment by Legoso** [comment] 2024-01-06 02:59
TrinityCore rev. 0c1e5fea69bb+ 2024-01-04 20:55:19 +0100 (3.3.5 branch) (Win64, Release, Static)

**TDB 335.23061** and updates up to TrinityCore rev. 0c1e5fea69bb .

Confirmed. I have noticed this a couple of times before, both during the last 6 months and more than a year ago, but I thought it was caused by my game client addons. I tested it now without any addons loaded, just to make sure.

**Samophlange quest chain, minimum level 10, recommended level 14-16:**
- https://aowow.trinitycore.info/?quest=894 (starting quest picked up from [Sputtervalve](https://aowow.trinitycore.info/?npc=3442) in Ratchet, between the flight master and the bank)
- **https://aowow.trinitycore.info/?quest=900 (valve gameobjects activation issue)**
- https://aowow.trinitycore.info/?quest=901 (console key retrieval)
- https://aowow.trinitycore.info/?quest=902 (return to Ratchet)

Worth noticing:
- Upon taking quest 900, the valves should turn active, but they do not. You have to log out and log in again to activate the valves. It is not enough to abandon the quest and retake it from the console.
- If you abandon quest 900 after logging in to see the gameobjects active, the valves stay active, so you have to log out and in again to turn them off.

**Comment by Legoso** [comment] 2024-01-06 03:22
Actually, this is a duplicate of #24952 . Please close this ticket & refer new comments to #24952 .

**Closed** 2024-01-06 11:03 UTC
Labels: Branch-3.3.5a, Invalid-IncompleteData/OrNotTrinityCore
