### ISSUE TITLE
[Dev] WIP Catmullrom waypoint movement

### ISSUE THREAD

**Issue by Pitcrawler** [TrinityCore/TrinityCore#13467] opened 2014-10-27 10:09 UTC
I started to play around a little with the core and made the following change to WaypointMovementGenerator.cpp

``` diff
diff --git a/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp b/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
index 942996b..5b8dd8b 100755
--- a/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
+++ b/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
@@ -153,6 +153,16 @@ bool WaypointMovementGenerator<Creature>::StartMove(Creature* creature)
             trans->CalculatePassengerPosition(formationDest.x, formationDest.y, formationDest.z, &formationDest.orientation);
     }

+   if (creature->IsFlying())
+   {
+       for (uint32 i = 0; i < i_path->size() - i_currentNode; i++)
+       {
+           init.Path().push_back(G3D::Vector3(i_path->at(i_currentNode + i)->x, i_path->at(i_currentNode + i)->y, i_path->at(i_currentNode + i)->z));
+       }
+       init.SetSmooth();
+       init.Launch();
+       return true;
+   }
     //! Do not use formationDest here, MoveTo requires transport offsets due to DisableTransportPathTransformations() call
     //! but formationDest contains global coordinates
     init.MoveTo(node->x, node->y, node->z);
```

This made all the flying NPCs that have waypoint data use catmullrom movement. But there are some things that certainly need improvements which I can't take care of because I have really little knowledge when it gets to core programming:
At each WP the remaining path is rebuild which is unnecessary (memory consumption) and not blizzlike.
At the last WP there is no next WP so no path is build and point movement is used instead of catmullrom.
Flying creatures that have inhabitType!=4 (i.e. 5 or 7) don't use catmullrom movement. I guess the core doesn't handle them correctly so they don't get their movementflags.
Swimming creatures don't use catmullrom movement.
##

**Comment by jackpoz** [comment] 2015-03-07 22:46
any update on this ?

**Comment by Kittnz** [comment] 2015-03-08 10:14
No one is working on it, hope someone picks it up.

**Comment by click** [comment] 2015-04-01 21:20
Ok, let's continue on this one ...
**Single pathing**
Example with 20 "real" waypoints:
1-2-3...18-19-20-**21** - 21 is the same as the "final" waypoint (20) - describes that we're on the endpoint.

**Cyclic pathing**
Example with 20 "real" waypoints:
1-2-3....20-*21-22-23* - 21-22-23 is the same as 1-2-3 - describes that we're on a cyclic path.
[23:12:30] <%click> describes that the path should repeat and continue as normal

**Comment by MrSmite** [comment] 2015-04-01 21:30
Question: After a path is generated would it make sense to save it to the DB (since the path should technically never change)?

**Comment by malcrom** [comment] 2015-04-01 21:32
Isn't the client doing the smoothing? we have many catmullrom paths in waypoint_data the same as offi sends to client. We are just sending them a point at a time.

**Comment by click** [comment] 2015-04-01 21:57
@MrSmite : no, the path is actually picked up FROM the database, core just need to know the criterias above.
Final point twice = Full endpoint
First three repeated as last three = cyclic
The client most probably also knows about this criteria, so it can interpolate correctly clientside.
@malcrom: The client does the smoothing based on standard Catmullrom definitions and us shipping the right info to it. Which iwe obviously don't.

**Comment by MrSmite** [comment] 2015-04-02 02:51
@click Ah, ok. I thought the goal was to calculate a path for use with mmaps to replace the waypoints we already had.

**Comment by Aokromes** [comment] 2016-05-26 03:14
Any new here?

**Comment by Riztazz** [comment] 2016-06-05 16:20
We took a crack at it and this is what we came up with.

There is few issues which sadly i have no idea how to fix. Sorry about the music

Issue 1:
https://youtu.be/8Pbq1BdkmyU
You can see at the end of path how npc slides on the ground before it turns

issue 2:
https://youtu.be/UdHsr3r6Hm0

Again, no clue why this happens, probably because a lot of waypoints are stacked on top of each other when we extract them via waypointCreator( http://i.imgur.com/S7ffv0V.png visualization of that npc path), or issue with spline implementation



Also code itself would probably need some refactoring to fit tc standards, sadly i do not have time to work on that anymore so here's the code and i hope someone, one day will pick it up and finish this or get some cool idea how to to write it in a better way :P 

https://github.com/Riztazz/TrinityCore/commit/6728f202a64d0b352d16474283607166be52e04b

**Comment by Aokromes** [comment] 2016-06-05 22:59
15$ bounty added here.

**Comment by MrSmite** [comment] 2016-06-06 06:54
> https://youtu.be/8Pbq1BdkmyU

This technically isn't a slide but rather a version of the [Wagon Wheel Effect](https://en.wikipedia.org/wiki/Wagon-wheel_effect). The NPC changes her facing direction before the final waypoint. In doing so her walk animation appears to be going against the direction of travel, causing the "slide" effect.

**Comment by Kittnz** [comment] 2016-06-06 15:30
points with faceing in should not be using catmullrom

**Comment by Riztazz** [comment] 2016-06-06 15:55
why?

**Comment by Kittnz** [comment] 2016-06-06 16:25
I guess it depence in what case, but a lot of times you see npc's reach a point and then keep standing on that same spot and change facing

**Comment by Riztazz** [comment] 2016-06-06 17:27
It only happens when points are stacked on top of each other, probably due to unit making little arc between non-straight lines (when smooth is enabled that is), dunno what is causing this and how to go about it ;p

**Comment by MrSmite** [comment] 2016-06-07 04:28
> but a lot of times you see npc's reach a point and then keep standing on that same spot and change facing

Yes, that's what I think is expected behavior. For some reason though it seems that the waypoint prior to the final one causes the NPC to change her facing, at least in the two videos supplied:

facing-> step -> step -> step -> *<-facing* step->

**Comment by Shauren** [comment] 2016-06-07 06:42
I see the mistake in that code
`for (auto i = i_currentNode; i < end; ++i)`
`end` is currently assigned to `i_path->size()` but you cant put in the ENTIRE path to spline, you have to stop adding nodes at the first point with delay after `i_currentNode`

**Comment by funjoker** [comment] 2016-09-27 16:08
https://www.bountysource.com/issues/5546590-dev-wip-catmullrom-waypoint-movement-15-bounty

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=5546590)](https://www.bountysource.com/issues/5546590-dev-wip-catmullrom-waypoint-movement-15-bounty?utm_source=5546590&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by funjoker** [comment] 2016-11-25 17:05
Bountysource do something xD

**Comment by Aokromes** [comment] 2016-11-25 17:28
i mailed them, still waiting for answer.

**Comment by Keader** [comment] 2017-01-20 13:38
Fix reverted in a3c6880579f3326088ecbe5b8c08c4b75ed91a59 so... reopen this

**Comment by jackpoz** [comment] 2017-01-20 15:07
lul the bounty was awarded

**Comment by robinsch** [comment] 2017-01-20 17:44
ez money

**Comment by funjoker** [comment] 2017-03-12 08:37
Well xD RIP my money, it was fun. :P

**Closed** 2024-10-07 18:29 UTC
Labels: Sub-Waypoints, Priority-FutureFeatureRequest, Feedback-FixOutdatedMissingWIP, Comp-Core
