### ISSUE TITLE
[Crash] WorldSession::HandleCalendarGetCalendar

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#14477] opened 2015-03-30 17:05 UTC
It seems that this crash has come back. I had several crashes like this in last week. But only this one with a good log.

http://pastebin.com/tDPuPUCa

62a5ee8e2cceb625ea24145a3d1fad98674a7442
##

**Comment by jackpoz** [comment] 2015-03-31 17:51
any custom patch or anything we should know about ?

**Comment by Pirricli** [comment] 2015-03-31 17:53
Crossfaction BG, Transmogrification by Rochet and passive antihack.

**Comment by Pirricli** [comment] 2015-04-05 21:16
http://pastebin.com/MncqjTdF

8a54cc043b018ff8f3c849a48d347862cd03f3fc

**Comment by Pirricli** [comment] 2015-04-11 12:13
http://pastebin.com/9ZGKv1qB

c7bc73c1677dfcd031f615b7c1d56be2ca736b78

**Comment by Rochet2** [comment] 2015-04-11 14:03
`258` Hmm .. is that mapid supposed to be valid? Dont think it is.

**Comment by Pirricli** [comment] 2015-04-11 14:08
and why it appears? I don't have  custom zones or maps.

**Comment by Aokromes** [comment] 2015-04-11 14:19
Maybe it's lfg map id, not map id.

**Comment by jackpoz** [comment] 2015-04-11 21:26
that's the value of a local variable not yet initialized, it's totally useless

**Comment by Pirricli** [comment] 2015-04-12 16:47
http://pastebin.com/uYMGdyME

08a62f19b808a347aae56b4f5a689233c6a03db0

**Comment by Demonid** [comment] 2015-04-21 01:58
Confirmed, today i had 3 crashes about this same thing but i don't have a proper crashlog to show.

**Comment by jackpoz** [comment] 2015-04-21 07:21
how do you know it's the same crash if you don't have a crashlog ?

**Comment by Pirricli** [comment] 2015-05-30 10:16
http://pastebin.com/SEWRQaYi

43ae8727ace4a0bcaaa8665adea78e578be454f3

**Comment by Raydor** [comment] 2015-05-31 13:43
Confirmed, a lot of crashes

https://github.com/TrinityCore/TrinityCore/commit/562da2e8b2b0814b47027dfd1af2dd0d98378f88

**Comment by jackpoz** [comment] 2015-05-31 14:22
@Raydor writing "a lot of crashes" without posting the crash logs is totally useless

**Comment by Raydor** [comment] 2015-05-31 15:09
http://pastebin.com/4RtKHZ0x

**Comment by Raydor** [comment] 2015-06-04 09:42
http://pastebin.com/E2HbGhzp
http://pastebin.com/sEdbd5EZ

**Comment by jackpoz** [comment] 2015-06-04 10:20
@Raydor could you build TC in Debug mode to get more details in the crash log ?

**Comment by Raydor** [comment] 2015-06-04 11:58
@jackpoz I have it already on debug mode u.u

**Comment by jackpoz** [comment] 2015-06-04 20:47
@Raydor do you have any custom patch to help track down the issue ? No matter how many tries we do we can't reproduce the crash with debugging tools running

**Comment by Raydor** [comment] 2015-06-05 08:59
I don't have custom patches to help track down the issue :/.

I use Linux, I don't know if this crash happens on windows too.

**Comment by Raydor** [comment] 2015-06-07 19:15
Just keep posting crashlogs, maybe any of these help...
http://pastebin.com/UbMx0fyX
http://pastebin.com/UFZmPp5a

**Comment by Aokromes** [comment] 2015-06-07 19:17
Can you try compiling with -O0? it's hard to fix something we can reproduce....

**Comment by jackpoz** [comment] 2015-06-19 18:47
please apply https://github.com/jackpoz/TrinityCore/commit/83a2173237d943917bdf6e762b761706baa6690c and add a new logger type
>Logger.calendar.crashfix=2,Calendar

and point it to a new appender
>Appender.Calendar=2,2,1,Calendar.log,a

Post the crashlog and the Calendar.log

@Raydor does it still happen every 5-10 hours ? can you trying disabling all custom patches for few hour to make sure it's actually a bug in TC code ?

**Comment by Aokromes** [comment] 2015-06-21 10:33
@Raydor, can you do:

```sql
SELECT 	COUNT(*)FROM `characters`.`calendar_events`;

**Comment by Raydor** [comment] 2015-06-21 18:08
@Aokromes 0 results, there are no calendar_events (It seems that dungeon saves are not saved in the DB as events).

@jackpoz I got it, tomorrow i'll restart the server to implement it and as soon as it crashes i'll post here the logs (I put an static map in uint32 mapid to avoid crashes as a temp solution so now I reverted that and put your code, let's see if we can catch the crash with that).

**Comment by jackpoz** [comment] 2015-06-29 20:23
any feedback on my patch ?

**Comment by Raydor** [comment] 2015-06-30 08:41
@jackpoz No crashes at the moment, I modified the saves to be 1 week instead 2 days (in worldserver.conf) and put .instance unbind all to all the players (because right now there is no point on my server to not let the players unbind the instances we have whenever they want (we are not a blizzlike server, only have X dungeons)).
I have your code in my server already, still waiting for a crash, maybe your patch fixed the issue or maybe there are no crashes because, as I said, players can now unbind their instances manually.

**Comment by jackpoz** [comment] 2015-06-30 12:50
maybe wait another week then revert my changes to see if they affect in any way the crash rate.

**Comment by jackpoz** [comment] 2015-07-08 20:22
how is the issue going ?

**Comment by Raydor** [comment] 2015-07-09 13:43
Still no crashes, tried reverting your changes and still no crashes, maybe no crashes because now in my server players have .i u all command and they don't let the instances to reset the saves by itselves, I can not remove that command to my players :/.

**Comment by jackpoz** [comment] 2015-07-09 15:37
@Pirricli can you apply https://github.com/TrinityCore/TrinityCore/issues/14477#issuecomment-113604130 and report back the results ?

**Comment by Pirricli** [comment] 2015-07-10 14:23
I'll restart tomorrow with the patch applied, but I have crashes from month to month.

**Comment by Runico** [comment] 2015-07-31 13:14
http://paste.ubuntu.com/11973218/

**Comment by jackpoz** [comment] 2015-07-31 18:04
@Runico did you do anything of https://github.com/TrinityCore/TrinityCore/issues/14477#issuecomment-113604130 ?

**Comment by Runico** [comment] 2015-08-01 02:51
@jackpoz, No, I did not know about that comment, I will apply that ASAP

**Comment by Runico** [comment] 2015-09-03 21:14
@jackpoz http://paste.ubuntu.com/12267127/ with log

**Comment by jackpoz** [comment] 2015-09-04 07:00
@Runico something is wrong with your crashlog, it shows
>WorldSession::HandleCalendarGetCalendar (this=0x7f2958c24880) at /usr/include/boost/system/error_code.hpp:499

which is clearly wrong: boost/system/error_code.hpp:499 has nothing to do with HandleCalendarGetCalendar()

**Comment by Runico** [comment] 2015-09-04 07:56
@jackpoz, It's for multiple restarts, Another issue is this crash won't happen if uptime is below 1day, So I will restart worldserver every morning and worldserver won't crash

**Comment by jackpoz** [comment] 2015-09-04 08:38
I'll change the patch to log when was the last time instance reset times got modified

**Comment by jackpoz** [comment] 2015-09-06 19:12
I added some more logs to https://github.com/jackpoz/TrinityCore/commit/a76729ae251531b2f3e34929849dacb3ed0209ba , please apply this one (this applies on a clean 3.3.5, you have to revert my previous patch).

**Comment by jackpoz** [comment] 2015-09-06 19:27
I added some more logs to https://github.com/jackpoz/TrinityCore/commit/bd08803ea610ca85c2f03aa5361c42e4e32c9b82 , please apply this one (this applies on a clean 3.3.5, you have to revert my previous patch).

**Comment by jackpoz** [comment] 2015-09-09 20:42
it is probably not a coincidence that there is a crash https://github.com/TrinityCore/TrinityCore/issues/14983 accessing a InstanceSaveMgr field declared close to m_resetTimeByMapDifficulty (which is the field triggering the crash here) and the 2 crashes are most likely linked

**Comment by jackpoz** [comment] 2015-11-02 16:39
any feedback about https://github.com/TrinityCore/TrinityCore/issues/14477#issuecomment-138117084 ?

**Comment by Pirricli** [comment] 2015-11-02 20:25
No news for the moment...

**Comment by Rushor** [comment] 2016-02-08 09:24
@Pirricli: this issue is still present?

**Comment by Pirricli** [comment] 2016-02-08 20:22
I applied the jackpot patch months ago and no crashes for the moment.

**Comment by jackpoz** [comment] 2016-08-31 14:59
any news ?

**Comment by Aokromes** [comment] 2016-11-26 04:37
@jackpoz how about push https://github.com/TrinityCore/TrinityCore/issues/14477#issuecomment-138117084 into repo? it won't hurt.
For the issue per se, no answer after 5 months and no crash after more than a year, closing. If this bug is still valid open a new ticket.

**Closed by Aokromes** 2016-11-26 04:37 UTC
Labels: Comp-Core, HasBacktrace

**Comment by jackpoz** [comment] 2016-11-26 08:12
I think the issue got fixed because the patch triggered a full rebuild, the patch itself doesn't change the code (or it disabled some exotic compiler optimization).
They could remove it and see what happens
