### ISSUE TITLE
Whip Lashers in Dire Maul have broken/glitchy paths

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19372] opened 2017-03-26 08:14 UTC
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Whip Lashers (ID 13022) have broken/glitchy paths. They commonly fall through the floor, or walk halfway through the floor.

https://gfycat.com/AgileWhirlwindGavial

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 986d830ae7b4 2017-03-23 03:58:03 +0100 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment] 2017-03-27 17:23
They have random move not WP, it's probably related to vmap or mmpas

**Comment by Aokromes** [comment] 2017-03-27 17:35
blizzlike bug :trollface:

**Comment by tkrokli** [comment] 2017-03-29 03:12
This type of bug is not specific to Dire Maul or Whip Lashers. You can see it other places in the game too. Not sure if it is more frequent in Azeroth (old world) than in the newer areas like Outland & Northrend, but feel free to check.

**Comment by Kittnz** [comment] 2017-03-29 09:55
What @Killyana said 👍

**Comment by ccrs** [comment] 2017-03-29 19:28
with the incommin refactor of RandomMovementGenerator this will be fixed, most likely 💃

**Comment by offl** [comment] 2017-12-18 20:10
Try after 9614f9d8cf295d4135346d59e67fa47b51d2ed88

**Comment by Killyana** [comment] 2017-12-18 21:51
Cannot reproduce on rev. b9b667f9253c

**Closed by Killyana** 2017-12-18 21:51 UTC
Labels: Branch-3.3.5a, Priority-Cosmetic, Sub-Waypoints
