### ISSUE TITLE
[3.3.5] Only players getting kickeds from Icecrown Citadel

### ISSUE THREAD

**Issue by VictorQueiroz** [TrinityCore/TrinityCore#14126] opened 2015-02-12 18:33 UTC
Players enter on Icecrown Citadel, attack mobs and get kicked out from server.

That was the revision that I was using when the problem starts:
```
TrinityCore rev. 6b8437f4f3d7 2015-01-27 14:13:33 +0200 (3.3.5 branch) (Unix, Release) (worldserver-daemon)
```

I tried with non-custom compilations too. Like the b1a4a8f435d2ba03e45f3a579c6ec48baf2a7cfb which is the hash that I am using right now, I did to see if the bug was the Transmoglification mod, but nothing changed.

For some reason, if you are a game master, nothing happens to you, but if you are a player you got high latency and lost connection from server. No server error, no db error, no auth error. And it's really stranger because I think that an instance script has nothing to do with the account session, isn't it?

Help you guys can help me out.

I'm hosting on a:
```
Amazon EC2 (m3.xlarge)
Intel Xeon E5-2670 v2 (Ivy Bridge)
4 vCPU
15 GB RAM
```

**Comment by Noeliel** [comment] 2015-02-12 18:34
Care to elaborate?

**Comment by VictorQueiroz** [comment] 2015-02-12 18:38
Already did. There is some way to me or TrinityCore team to fix that? Or it is a bad configuration problem?

**Comment by DDuarte** [comment] 2015-02-12 18:40
collab.kpsn.org/display/tc/The+Issuetracker+and+You

**Comment by VictorQueiroz** [comment] 2015-02-12 20:28
I updated my issue. Should I create another with the new informations?

**Comment by ariel-** [comment] 2015-02-12 21:06
Don't use custom patches (6b8437f4f3d7) isn't a valid commit hash in TC repo.

**Comment by Kittnz** [comment] 2015-02-12 21:48
b1a4a8f435d2ba03e45f3a579c6ec48baf2a7cfb

**Comment by VictorQueiroz** [comment] 2015-02-13 00:00
What do you mean by tagging this revision here?

**Comment by Kittnz** [comment] 2015-02-13 08:09
easy to click xD nothing really

**Comment by D4R4** [comment] 2015-02-13 09:36
Cannot reproduce, 
1) try a fresh TC on your Amazon EC2
2) compile,run and test your current core on your home PC
that would at least narrow it down alittle

if the issue persist in the second case we can't help you here.

**Comment by jackpoz** [comment] 2015-02-13 21:34
is there anything in worldserver logs ?

**Comment by Aokromes** [comment] 2015-02-15 11:29
No one else can reproduce this bug, closing this.

**Closed by Aokromes** 2015-02-15 11:29 UTC
Labels: Branch-3.3.5a, Invalid-CannotReproduce, Sub-Instances
