### ISSUE TITLE
Tools/vmap: AoE randomly hits out of LoS in caves

### ISSUE THREAD

**Issue by Regrad** [TrinityCore/TrinityCore#21121] opened 2017-12-26 01:03 UTC
**Description:**

DeathKnight AoE spells randomy does not work in caves. 

**Current behaviour:**

DeathKnight AoE spells randomy does not work in caves. Video of this bug: https://youtu.be/p_qnxZ0Pt9g

`vmap.enableLOS = 0` fix problem.

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  f0614b57a59a8525a6634e1465a83ef8fa27839e

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** CHANGEME OS

**Comment by tkrokli** [comment] 2017-12-26 11:40
Added back the deleted issue ticket template. We do recommend keeping the issue template to encourage posting enough information about the issue.

I don't know exactly how to describe the cause of this issue, but it looks like it is related to parts of the terrain behaving like it is out of LoS, even though the player is visibly in LoS of the selected point in the terrain. Maybe it is a terrain layer issue, not entirely sure. It can sometimes cause error messages while fishing too, if I remember correctly.

**Comment by jackpoz** [comment] 2017-12-26 11:59
could you provide some spell id/spell names ?

**Comment by jackpoz** [comment] 2017-12-26 12:05
@Golrag could you please check if your merged PR caused this issue ? Could you open a new PR with the fix ?

**Comment by Golrag** [comment] 2017-12-26 13:01
I would like some coordinates for this, if it's fixed with what I have now I will make a PR today

**Comment by jackpoz** [comment] 2017-12-26 15:47
@Golrag did you find the cave of the video above to check if your fix handles it ?

**Comment by Golrag** [comment] 2017-12-26 16:00
I did not sadly but I tried a lot of caves in northrend and had some fun with a draenei dk with .cheat cooldown and .cheat power and spam dead n decay without issues

**Comment by rockz1152** [comment] 2017-12-27 00:30
Looks like it's not just Death and Decay, but other targeted AoE abilities such as blizzard. 
I was able to reproduce this on a mage in Orgrimmar. Fresh build and map extraction.

Rev.  84f69a3b6c9e
.go xyz 2098.85 -4664.11 46.40 1
try to cast blizzard between the three target dummies and you should get "Target no in line of sight" when you clearly are.

**Comment by Golrag** [comment] 2017-12-27 11:26
Can't reproduce with my PR :p

**Comment by jackpoz** [comment] 2017-12-29 22:49
Please try after https://github.com/TrinityCore/TrinityCore/commit/e42903ec16f4849b71bc8736e3151a1e11d3cd25

**Closed by jackpoz** 2017-12-29 22:49 UTC
Labels: Branch-3.3.5a, Sub-Maps/MMaps/Vmaps, Sub-Spells
