### ISSUE TITLE
[3.3.5] PVP Achievements

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14397] opened 2015-03-17 15:45 UTC
For sure, when i revert this commits, all is okay https://github.com/TrinityCore/TrinityCore/commit/abee9046a6d92e2f0ba9de9c97ce6304c2fcb883 https://github.com/TrinityCore/TrinityCore/commit/61ba5e4f34211c2f0f286e70d8ace37714ca3c56

How to:
Step 1. Download rev before https://github.com/TrinityCore/TrinityCore/commit/abee9046a6d92e2f0ba9de9c97ce6304c2fcb883

Step 2. Create character and login into world. After logging you can logout.

Step 3. Apply commits https://github.com/TrinityCore/TrinityCore/commit/abee9046a6d92e2f0ba9de9c97ce6304c2fcb883 https://github.com/TrinityCore/TrinityCore/commit/61ba5e4f34211c2f0f286e70d8ace37714ca3c56

Step 4. Login into game. You will get all PVP achievements + WOW 4th Anniversary + WOW 5th Anniversary http://prntscr.com/6hxc4n

-----------------------------------------------------------------------------------------------------------------------------------

My actual rev is: https://github.com/TrinityCore/TrinityCore/commit/03104087fa87ffff3340f9e2ce5939231aea417b

DB: TDB 11.57

**Comment by Nyeriah** [comment] 2015-03-17 18:09
Can't confirm

**Comment by Aokromes** [comment] 2015-03-19 18:51
Like i said on the other place can't reproduce.

**Comment by danlapps** [comment] 2015-03-26 19:57
Cannot reproduce with up to date 3.3.5.  Suggesting closing, sounds like local problem.

**Closed** 2015-04-09 06:21 UTC
Labels: Branch-3.3.5a, Comp-Core, Invalid-CannotReproduce
