### ISSUE TITLE
[3.3.5] Creature Mature Bone Sifter Wrong state during combat

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26747] opened 2021-07-24 17:23 UTC
### Description

During the quest [Fumping](https://tbc.wowhead.com/quest=10929/fumping), [Mature Bone Sifter](https://tbc.wowhead.com/npc=22482/mature-bone-sifter) appear as it should be from hitting the [Fumper](https://tbc.wowhead.com/item=31810/fumper), however, having entered the battle, these worms are visually underground, although they can be attacked. If these worms are stunned, they will crawl out to the surface.

![WoWScrnShot_072421_195145](https://user-images.githubusercontent.com/73786888/126876334-13632c01-76ca-492d-a622-c069b46260a0.jpg)
![WoWScrnShot_072421_195152](https://user-images.githubusercontent.com/73786888/126876336-075f049f-4d8f-4b0c-a9c5-83942fa7ec45.jpg)

### Expected behaviour

[Mature Bone Sifter](https://tbc.wowhead.com/npc=22482/mature-bone-sifter) must be visually visible at the start of the battle, that is, be on the ground, not underground.

### Steps to reproduce the problem

1. Take quest [Fumping](https://tbc.wowhead.com/quest=10929/fumping) from [Dwarfowitz](https://tbc.wowhead.com/npc=22481/dwarfowitz) at Sha'tari Base Camp in the Bone Wastes in Terokkar Forest near Auchindoun;
2. Start summoning [Mature Bone Sifter](https://tbc.wowhead.com/npc=22482/mature-bone-sifter) with [Fumper](https://tbc.wowhead.com/item=31810/fumper);
3. Start the battle with the summoned [Mature Bone Sifter](https://tbc.wowhead.com/npc=22482/mature-bone-sifter) and notice that it is visually underground, and that you can attack it. Try to stun him and make sure he gets to the surface.
4. Become confused.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/caf68840b9bc6a435a59b2fb954c1fe779a27c66
TrinityCore rev. 2021-07-24 ‏‎12:46:23 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by offl** [comment] 2021-07-24 17:28
Duplicate of #11418

**Closed by offl** 2021-07-24 17:28 UTC
Labels: Branch-3.3.5a

**Comment by Freeman256** [comment] 2021-07-24 18:03
Oh, I'm sorry.
