### ISSUE TITLE
DB/Creature: Set correct flags on Shatterspear Laborers

### ISSUE THREAD

**Issue by shdr212** [TrinityCore/TrinityCore#25852] opened 2021-01-15 11:08 UTC
**Description:**
Shatterspear Laborers in Ruins of Mathystra in Darkshore look as if they're dead on the floor (feint death),
and can't be attacked by players. They are slain objectives for a quest ( #25801 ).

Wowhead npc link: https://www.wowhead.com/quest=13504/shatterspear-laborers
Video on a quest related to npcs, where you can see how the npcs should work: https://www.youtube.com/watch?v=87sVpn6tClM&feature=youtu.be

**Expected behaviour:**
Npcs should be alive and attackable by players.

**Steps to reproduce the problem:**

1. go to Ruins of Mathystra in Darkshore 
2. Target the Shatterspear Laborers npc

**Suggested solution:**

```sql
UPDATE `creature_template` SET `unit_flags`=0, `unit_flags2`=0, `unit_flags3`=0 WHERE `entry`=32861;
UPDATE `creature` SET `unit_flags`=0 WHERE `guid`=260181 OR `guid`=260182 OR `guid`=260188 or `guid`=260189 OR `guid`=260190;
```

**Branch(es):**
master

**TC rev. hash/commit:** 
51c126c07aa6d7044bec01183602930c3596249e

```
TrinityCore rev. 51c126c07aa6 2021-01-11 21:04:58 +0100 (master branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.0.2n  7 Dec 2017 (library: OpenSSL 1.0.2h  3 May 2016)
Using Boost version: 1.72.0
Using MySQL version: 5.7.32
Using CMake version: 3.19.2
Compiled on: Windows 10.0.19041
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
```

**Operating system:** Windows 10

**Comment by offl** [comment] 2021-01-15 15:23
Please post your solution in #25801

**Comment by shdr212** [comment] 2021-01-15 16:29
@offl I had this discussion in IRC, on whether to open a new issue or simply comment in the old one, and I understood it's better to create a new issue.

Perhaps a clear guideline in the wiki about it would be helpful.
Specifically here: https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130102/SQL+Guidelines

**Comment by offl** [comment] 2021-01-15 16:38
Usually people post solutions in old issues, I'm not sure if it's correct in all cases
Seems you're right, this one looks better

**Comment by Aokromes** [comment] 2021-01-15 18:25
updated wiki to state fixes for known bugs must be posted on existing bug reports.

**Comment by shamage** [comment] 2021-01-15 19:00
@shdr212 - thank you for your great work , NPCs behave as they should (after implementing your fix)

**Comment by illfated** [comment] 2021-01-15 20:25
@shdr212 : You can use **```sql** at the start of your SQL code block if you want to show the syntax highlighting.

**Comment by shdr212** [comment] 2021-01-15 21:50
@shamage happy to hear that!

@illfated cool edited; thank you!

**Comment by matanshukry** [comment] 2021-03-29 03:57
I believe this was merged in #25801 and can be closed?

**Comment by offl** [comment] 2021-04-01 18:31
I think the guy who wrote https://github.com/TrinityCore/TrinityCore/issues/25801#issuecomment-761105215 just applied sql locally

**Comment by matanshukry** [comment] 2021-04-01 18:41
@offl you didn't merge it? I assumed so since there wasn't any comment indicating a fix request, and you closed the issue.

**Comment by illfated** [comment] 2021-04-01 18:56
@matanshukry : If the SQL had been merged, you would have seen a commit reference in this page. Also, Aokromes took your word for it to close this ticket, without checking sources.

**Comment by matanshukry** [comment] 2021-04-01 19:15
@illfated that's kind of weird, closing the earlier issue (4 Jan) as a duplicate of the newer issue (15 Jan).
Also, last comment from a tc member in this issue was by Aokromes, which states the fix should be posted at the other issue, which it was - and then closed. Which again, I just assumed it was merged.

Anyway in light of that I'm assuming now it wasn't merge and one of those issues should be reopened.
Although we have the fix and I haven't seen any review comment about it - is there anything wrong with it not being merged yet?

**Comment by illfated** [comment] 2021-04-02 09:33
Thank you for sharing your thoughts on the issues. Fair point. Normally, the oldest ticket should stay open while the newer one(s) should be closed. One of the possible exceptions is when the newer ticket contains a better explanation or has more useful content like both suggested solutions and confirmations that the suggested solution works.

Regarding when a suggested solution can be merged, that is more up to the TC members to decide. It could be down to the amount of testing (or lack thereof), but it is usually better to get feedback from TC members why the suggested solution has not made it into the commits yet.

**Comment by mdX7** [comment] 2021-09-22 14:25
The exact creatures you specified by guid actually require the flags (these are the dead trolls in the camp, additionally i've added the raiders in the query which are also feign deathed on retail.

```sql
-- Shatterspear Laborers
UPDATE `creature_template` SET `unit_flags`=`unit_flags`&~(0x100|0x200|0x8000|0x20000000), `unit_flags2`=`unit_flags2`&~0x1, `unit_flags3`=`unit_flags3`&~0x2000 WHERE `entry`=32861;
UPDATE `creature` SET `unit_flags`=(0x100|0x200|0x8000|0x20000000), `unit_flags2`=0x1, `unit_flags3`=0x2000 WHERE `guid` IN(260181, 260182, 260188, 260189, 260190);

-- Shatterspear Raiders
UPDATE `creature` SET `unit_flags`=(0x100|0x200|0x8000|0x20000000), `unit_flags2`=0x1, `unit_flags3`=0x2000 WHERE `guid` IN(315289, 315293, 315292, 315305);
```

**Closed** 2021-09-22 14:32 UTC
Labels: Sub-Quests, Feedback-PatchFix, Comp-Database, Branch-master
