### ISSUE TITLE
6.x Worldserver crash report: WorldSession__QueuePacket

### ISSUE THREAD

**Issue by Epicurus4** [TrinityCore/TrinityCore#14449] opened 2015-03-25 21:09 UTC
Rev. ee6fd67552650ae8ae180885f7e916721f917908

https://gist.github.com/Epicurus4/b19a74a998b6cbb8b1c5

**Comment by jackpoz** [comment] 2015-03-25 21:11
https://gist.github.com/Epicurus4/b19a74a998b6cbb8b1c5#file-gistfile1-txt-L511 WorldSession is filled with 0xDDDDDDDD values, "Used by MicroQuill's SmartHeap and Microsoft's C/C++ debug free() function to mark freed heap memory", so it's indeed a free'd WorldSession object still being accessed.

**Comment by Shauren** [comment] 2015-04-23 09:53
Duplicate of #14550

**Closed by Shauren** 2015-04-23 09:53 UTC
Labels: HasBacktrace, Invalid-Duplicate
