### ISSUE TITLE
Set Health to 1 before actually killing the unit

### ISSUE THREAD

**Issue by NorthStrider** [TrinityCore/TrinityCore#16109] opened 2015-12-27 13:50 UTC
This has been discussed several times before so I tried to make something to handle this:
http://paste2.org/4YffNdWv
The change simply calls a kill preperation function to set the health to 1 and then killing the unit. Right now I am not able to setup an environment to test it. 

The change can be tested easily by casting a arcane blast spell against a npc that dies with 1 cast. The spell visual usually doesn't appear because the unit dies too fast. With that change the npc should get hit by the spell's visual effect and then die.

rev.: 9ab10d6e680ca835d1dfdfbceb9f18f330f994fc

**Comment by Trisjdc** [comment] 2015-12-27 14:40
Your patch doesn't really do anything. The death has to be delayed.

And this is a duplicate of https://github.com/TrinityCore/TrinityCore/issues/13441

**Closed** 2015-12-27 15:03 UTC
