### ISSUE TITLE
[ICC] Crash Boss_Svalna (captains) | Motionmaster

### ISSUE THREAD

**Issue by xParad0x** [TrinityCore/TrinityCore#24505] opened 2020-04-27 13:13 UTC
Server crashes all of a sudden in ICC on boss_sister_svalna. Related to Motionmaster (maybe?) crash logs always includes names:

npc_captain_arnath
npc_captain_brandon
npc_captain_grondel
npc_captain_rupert

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
b4584ee32380b6a01c681f86e59a8b8258ba39fb

*** Hardware ***
Processor: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Number Of Processors: 8
Physical Memory: 33187668 KB (Available: 25510008 KB)
Commit Charge Limit: 37381972 KB

*** Operation System ***
Windows Server 2012 Standard (Version 6.2, Build 9200)

Crash Log:
https://drive.google.com/open?id=1oNpemu0kwnHM1PL3ZiwlrK0k-DOTrqKQ

**Comment by jackpoz** [comment] 2020-04-27 13:15
is that the full log or only a part/edited ?

**Comment by xParad0x** [comment] 2020-04-27 13:19
its a full crashlog file

**Comment by jackpoz** [comment] 2020-04-27 13:36
do you have any custom changes ? Could you upload your MotionMaster.cpp file ? The lines don't seem to match with https://github.com/TrinityCore/TrinityCore/blob/b4584ee32380b6a01c681f86e59a8b8258ba39fb/src/server/game/Movement/MotionMaster.cpp

**Comment by xParad0x** [comment] 2020-04-27 13:42
The only commit i did not apply was this one
https://github.com/TrinityCore/TrinityCore/commit/d033032d33cff5dae76000f8432d78746cda9e06#commitcomment-35605170

My Motionmaster
https://drive.google.com/open?id=1D87meK6s-pbLJHWtN8782j188SfVA99Z

**Comment by jackpoz** [comment] 2020-04-27 13:50
Please, when reporting a crash and saying "TC rev. hash/commit: b4584ee " DO mention you are NOT using commit b4584ee but some custom fork with custom changes (and missing commits are custom changes).

Please reproduce the issue on a clean TC and report a crashlog . You can use https://tcubuntu.northeurope.cloudapp.azure.com/ if you want to access a clean TC server.

**Comment by jackpoz** [comment] 2020-04-27 13:51
Closing the issue as the crash happens with a custom sourcetree with missing commits. The issue can be reopened with a crashlog using clean TC checkout.

**Comment by xParad0x** [comment] 2020-04-27 13:52
i use latest TC version without 2 commits 1 is the one i linked and second is related to few quests. but sure w.e you say

**Comment by jackpoz** [comment] 2020-04-27 13:54
The commit you mentioned https://github.com/TrinityCore/TrinityCore/commit/d033032d33cff5dae76000f8432d78746cda9e06 refers to https://github.com/TrinityCore/TrinityCore/issues/23199 which is a crash in MotionMaster, so the "only" commit missing actually fixes a crash in the same class where you are experiencing the crash.

**Comment by jackpoz** [comment] 2020-04-27 14:04
Btw you are missing https://github.com/TrinityCore/TrinityCore/commit/6176ce92ea01fd33b11c2e7f8e9ebb509e80c944#diff-7f0072ea7e8aa2a3e1d6580a7e14dfde and https://github.com/TrinityCore/TrinityCore/commit/cfd63c350f5b01fd699903b17162b2f5167b1386 and https://github.com/TrinityCore/TrinityCore/commit/6fde051e4e52d98d1a6cf31b8ad3fcf95e0e83fd#diff-7f0072ea7e8aa2a3e1d6580a7e14dfde and https://github.com/TrinityCore/TrinityCore/commit/0e2342c1698d9e2dc8a8c9d559f232cbb83707cb#diff-7f0072ea7e8aa2a3e1d6580a7e14dfde and ...

**Comment by ckegg** [comment] 2020-04-28 05:23
This is not actually crashing the server, it is because thread hung up, that's why crash log has no useful information. It only occurs after all 4 captains died and when the event restarts without them. Script is trying to send captains some actions but while they died, CreatureAI hangs. Tagging them below:

https://github.com/TrinityCore/TrinityCore/blob/ee5eace3c6d1fa489572c052daef4834e9c7f12c/src/server/scripts/Northrend/IcecrownCitadel/boss_sister_svalna.cpp#L747

https://github.com/TrinityCore/TrinityCore/blob/ee5eace3c6d1fa489572c052daef4834e9c7f12c/src/server/scripts/Northrend/IcecrownCitadel/boss_sister_svalna.cpp#L571

**Comment by xParad0x** [comment] 2020-04-28 12:01
Yeap. I disabled the script last night and no crash so far. This crash is nowhere related to the commits @jackpoz listed

**Comment by Rushor** [comment] 2020-04-28 14:22
The other script for crusader has an alive check aswell, so that must be added here aswell i guess

**Comment by Jildor** [comment] 2020-04-28 14:28
@xParad0x if you know how to reproduce steps for get crash in a clean TC, please add it with the crashlog

**Comment by Aokromes** [comment] 2020-04-28 14:36
i did multiple icc runs and never crashed for me.

**Comment by xParad0x** [comment] 2020-04-28 15:35
> i did multiple icc runs and never crashed for me.

Running ICC by yourself and running ICC with 300+ players is by far a different situation

**Comment by Aokromes** [comment] 2020-04-28 16:11
> > i did multiple icc runs and never crashed for me.
> 
> Running ICC by yourself and running ICC with 300+ players is by far a different situation

i don't said i did run myself.

**Comment by jackpoz** [comment] 2020-04-28 20:57
@ckegg got a crashlog of the freeze ?

**Comment by xParad0x** [comment] 2020-04-28 21:03
Adding if alive checks fixes the issue. Which should be there in a first place

**Comment by ckegg** [comment] 2020-04-29 02:48
> @ckegg got a crashlog of the freeze ?
No I don't have it but I recorded a video when debugging a while back. Here is the video.
[https://mega.nz/file/bgcy3C5b#7ubZWZd972iPOoDe5I961a7wwPGwkpa0NH1DApjq7LQ](url)

Let  captains die first (video 1:07), go out the platform where crok stands at, re-enter the platform (video 1:15) and it freezes (video 1:18) after crok first shoutout.

I only added ->IsAlive() check on lines I mention and no more crashes.

**Comment by Faq** [comment] 2020-04-29 15:06
Not possible to reproduce, also crashlog is not full + I doubt you pulled all commits from 335 repo.

**Comment by jackpoz** [comment] 2020-04-29 19:15
Please try reproducing the issue on a clean source using commit https://github.com/TrinityCore/TrinityCore/commit/22aaf32a79cd6ce8ebb4507cdfd677f073c35178

**Closed by jackpoz** 2020-04-29 19:15 UTC
Labels: Branch-3.3.5a, HasBacktrace, Invalid-IncompleteData/OrNotTrinityCore

**Comment by ckegg** [comment] 2020-05-02 09:32
I was able to reproduce the freezes using earlier commit b48c50b , did exactly the same thing I did from video I posted earlier. Right after I tried 22aaf32 but could not reproduce the freeze.
[crash.log](https://github.com/TrinityCore/TrinityCore/files/4567412/crash.log)

**Comment by xParad0x** [comment] 2020-05-02 13:13
@ckegg yea same crash log. I normally do not report any crash logs here because of constant "Your core is custom" comments and closing reports due to that. What TC teams needs to realize is that 90% of people do not use clean TC , 90% of us cherry pick commits until we are 100% certain that new commits are fully tested and doesnt cause crashes before applying them. Its a normal practice. I can only imagine how many valid reports that were closed with a Tag "Incomplete/NotTrinity"

**Comment by jackpoz** [comment] 2020-05-02 13:36
@xParad0x could you at least push your "cherry-picked" sources to github ? What you don't realize is that it's impossible to work with a crashlog without the exact sources and you should mention right away that you have custom changes, not make us wander in the dark thinking after wasting time checking the log "hey, the lines don't match".
