### ISSUE TITLE
Pandaren Starter Area Quests and some NPC fixes

### ISSUE THREAD

**Issue by alexandre433** [TrinityCore/TrinityCore#18015] opened 2016-09-27 20:17 UTC
Pandaren starter area Quests and Some NPC Fixes.

TDB 6.04

https://gist.github.com/alexandre433/9ff41f2f303147beec08e440dfd2b8d8

**Comment by Aokromes** [comment] 2016-09-27 20:20
Thx, but, duplicate of:
https://github.com/TrinityCore/TrinityCore/pull/17021

**Closed by Aokromes** 2016-09-27 20:20 UTC
