### ISSUE TITLE
[MMAPS] Charge ignoring path sometimes

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#13847] opened 2015-01-03 13:50 UTC
If you charge onto anyone who is RIGHT IN THE EDGE of something, you charge into him without following the path (in the following photos I used .mmap path to see the issue better):

![](http://puu.sh/e0AVB/a1f07186e7.jpg)

![](http://puu.sh/e0AW1/18828dbecd.jpg)

![](http://puu.sh/e0AY9/c06bb86df1.jpg)

![](http://puu.sh/e0AYt/f5ae1d1d32.jpg)

As you can see, I just charged in a straight line ignoring the path and also my character didn't reach the top of the edge where the enemy was so I fell to the ground again.

The charge works correctly if the enemy is not in the edge, the issue is only in those places.

I'm on lastest 3.3.5a rev https://github.com/TrinityCore/TrinityCore/commit/51f5ce1b7364b730cb0bdabcfd6ad18794213f95

EDIT: I tested it with a NPC putting it in the edge and using .cometome, the NPC came to me following the path and also tested it with some waypoints and the same result, it worked ok, seems like the bug is only with the spell charge.

**Comment by jackpoz** [comment] 2015-01-03 17:11
it's not about charge ignoring the path, it's about the border that mmaps have at the bridge sides so the closest point to the target in the mmap is chosen, in this case it's probably below the bridge.
The result is the same, the cause is different.

**Comment by Raydor** [comment] 2015-01-03 18:28
Yeah, on a TrinityCore with 1 year old this works nice, so maybe its related to the changes you linked.

**Comment by Raydor** [comment] 2015-01-04 17:38
Tested it reverting the 3 commits you said, the bug is not related with them.

**Comment by Frytiks** [comment] 2015-01-04 20:24
I was have this bug too, but with blink. I reverted this commit https://github.com/TrinityCore/TrinityCore/commit/dad9b01b265b9353424150eb9b268a735054238e and all has been ok. About your charge problem. I have fixed it. That arena have more bug's. Pet can determinate if owner is on top or on bot of bridge. Also ropes is not extracted. This can be hackfixed with adding offmesh details into .txt

**Comment by Raydor** [comment] 2015-01-04 20:45
Did you fix the charge problem by adding the offmest deails into the txt or that is just for the ropes?

**Comment by jackpoz** [comment] 2015-01-05 00:01
Due to how Pathfinding implementation in TC and Recast work, adding the offmesh is not enough because the pet will keep running back and forth on the rope

**Comment by Raydor** [comment] 2015-01-05 10:52
Well, still helps with charge xD, anyway the problem with enemies in the borders is a big bug with mmaps, sadly reverting the 3 commits you said didn't help :/

**Comment by Frytiks** [comment] 2015-01-05 12:55
@Raydor Sorry i can't just i will help you. Revert RecastNavigation to https://github.com/TrinityCore/TrinityCore/commit/aa645683b8b25bfb35cb977678daf5c56c1531e6 and add offmeshpoint, and revert all commits about charge. Re-extract mmaps and it will solve your problem.

**Comment by jackpoz** [comment] 2015-01-05 13:18
https://github.com/TrinityCore/TrinityCore/commit/aa645683b8b25bfb35cb977678daf5c56c1531e6 has  invisible wall issue since it's missing the recast fix https://github.com/memononen/recastnavigation/pull/18 . If you are using that version then you have broken mmaps on your server

**Comment by Raydor** [comment] 2015-01-05 16:32
Oh wow, thanks @Frytiks but I won't revert all charge commits and RecastNavigation, it surely will bug a lot of things.

**Comment by jackpoz** [comment] 2015-01-05 18:01
if https://github.com/TrinityCore/TrinityCore/commit/4302226a853811f1346ca96a78af0e649cdb4580 gets reverted then you might have Charge to do a zig-zag path even if there is a straight line, because mmaps main goal is to find a path, not the most straight one, and that commits fixes this case

**Comment by Raydor** [comment] 2015-01-05 18:49
Yeah, anyways reverting https://github.com/TrinityCore/TrinityCore/commit/4302226a853811f1346ca96a78af0e649cdb4580 doesn't fix this issue, it changes nothing within this issue.

**Comment by Raydor** [comment] 2015-01-05 19:07
https://github.com/siley/deffender-fun-3.3.5a/commit/e139323d8c61cfbadbb69d73e699a66c4e1e0562 Found this, jackpoz can you test this to see exactly how this works? I can't record a video, it almost almost fix this issue, well it fixes it but makes charge works strange, take a look if you can.

**Comment by Frytiks** [comment] 2015-01-05 19:51
I will save your life. These custom points works. Only ropes getting bugged sometimes. But works good

**Comment by Raydor** [comment] 2015-01-05 19:54
Yeah with this, ropes ignores MMAPs but about the issue, it doesnt exactly fix this, you can't charge from below to the top of the bridge (like in my screenshots) but if you go to the ramp you can still charge and you still get a straigh charge ignoring the path.

So that's what I said, it ALMOST fix it xD.

**Comment by Raydor** [comment] 2015-01-09 15:10
https://github.com/siley/deffender-fun-3.3.5a/commit/e139323d8c61cfbadbb69d73e699a66c4e1e0562 Following this again (im trying to help mmaps devs), I tested something with this "fix".

		if (_straightLine)
		{
			float hit = 0;
			float hitNormal[3];
			memset(hitNormal, 0, sizeof(hitNormal));

			dtResult = _navMeshQuery->raycast(
							suffixStartPoly,
							suffixEndPoint,
							endPoint,
							&_filter,
							&hit,
							hitNormal,
							_pathPolyRefs + prefixPolyLength - 1,
							(int*)&suffixPolyLength,
							MAX_PATH_LENGTH - prefixPolyLength);

			// raycast() sets hit to FLT_MAX if there is a ray between start and end
			if (hit != FLT_MAX)
			{
				// the ray hit something, return no path instead of the incomplete one
				_type = PATHFIND_NOPATH;
				return;
			}
		}
		else

Deleting this do nothing, all works well with or without this (I'm talking about my issue, it surely bugs other things in other places) so I think modifying only this doesn't help us.

--------------------------------------------------------------------------------------------------

		if (_straightLine)
  		{
			float hit = 0;
			float hitNormal[3];
			memset(hitNormal, 0, sizeof(hitNormal));

			dtResult = _navMeshQuery->raycast(
							startPoly,
							startPoint,
							endPoint,
							&_filter,
							&hit,
							hitNormal,
							_pathPolyRefs,
							(int*)&_polyLength,
							MAX_PATH_LENGTH);

			// raycast() sets hit to FLT_MAX if there is a ray between start and end
			if (hit != FLT_MAX)
			{
				// the ray hit something, return no path instead of the incomplete one
				_type = PATHFIND_NOPATH;
				return;
			}
		}
		else

Deleting this makes charging from below of the bridge to follow the path (which is what we want, this or just "out of range"):
http://puu.sh/ehuwx/e1ad1dfecf.jpg
http://puu.sh/ehux5/fdd2b4a9e5.jpg
http://puu.sh/ehuxl/3c969b6b69.jpg
http://puu.sh/ehuyr/78e6bf55a3.jpg

But it makes other bugs like charging from the pillars makes a straight charge, flying above the ropes, the same as if you charge from the ramp, you can see it in the screenshots:
http://puu.sh/ehu2H/f14a6949d9.jpg
http://puu.sh/ehu3b/b0a0cc9167.jpg

To sum up, maybe the fix is to change something inside this.

--------------------------------------------------------------------------------------------------

And for the last one:

	if (_straightLine)
	{
		dtResult = DT_SUCCESS;
		pointCount = 1;
		memcpy(&pathPoints[VERTEX_SIZE * 0], startPoint, sizeof(float)* 3); // first point

		// path has to be split into polygons with dist SMOOTH_PATH_STEP_SIZE between them
		G3D::Vector3 startVec = G3D::Vector3(startPoint[0], startPoint[1], startPoint[2]);
		G3D::Vector3 endVec = G3D::Vector3(endPoint[0], endPoint[1], endPoint[2]);
		G3D::Vector3 diffVec = (endVec - startVec);
		G3D::Vector3 prevVec = startVec;
		float len = diffVec.length();
		diffVec *= SMOOTH_PATH_STEP_SIZE / len;
		while (len > SMOOTH_PATH_STEP_SIZE)
		{
			len -= SMOOTH_PATH_STEP_SIZE;
			prevVec += diffVec;
			pathPoints[VERTEX_SIZE * pointCount + 0] = prevVec.x;
			pathPoints[VERTEX_SIZE * pointCount + 1] = prevVec.y;
			pathPoints[VERTEX_SIZE * pointCount + 2] = prevVec.z;
			++pointCount;
		}

		memcpy(&pathPoints[VERTEX_SIZE * pointCount], endPoint, sizeof(float)* 3); // last point
		++pointCount;
	}
	else

Deleting this doesn't do anything too, the same as the first I talked about.

This probably doesn't do anything to help you, because this is a hackfix and doing the things I said only works if you put all of the remaining code of the "fix" but well, due to I have no idea how to fix it, i'll try to help the devs to fix this (it's a critical bug in pvp anyways, sometimes this makes you to get into walls...).

**Comment by Trisjdc** [comment] 2015-01-14 19:46
The raycast has to fail when it can't follow terrain, that's the main issue. I'm not sure how to determine this.

**Comment by Raydor** [comment] 2015-02-04 10:25
The same happens with pet's charges, also pets get underground sometimes too, but that's another issue (I think).

**Comment by Rushor** [comment] 2015-03-12 21:01
I'd like to add, that the problem also appears in EotS near the Bases, probably a helping start for those who try to reproduce/fix it...

a vid of it: https://youtu.be/yS9cZFVabXc

falling below textures originally was fixed in https://github.com/TrinityCore/TrinityCore/issues/11526

**Comment by jackpoz** [comment] 2015-06-16 19:40
@Raydor @Rushor could you try to apply https://github.com/jackpoz/TrinityCore/commit/8da85596a46c113ca9a0956382c8062872804e4e and see if it fixes the issue and cause any new trouble ?

**Comment by Raydor** [comment] 2015-06-17 08:44
@jackpoz ![](http://puu.sh/is2z9/32d41ef0fd.jpg)

It's working ok (I would like the error to appear Out of Range instead No path available but it's okay anyways <3)

**Comment by Aokromes** [comment] 2015-06-17 08:50
No path available is blizzlike.

**Comment by jackpoz** [comment] 2015-06-17 10:04
Does the rest of the arena work fine as it's supposed to do ? (ignoring pillars)

**Comment by Raydor** [comment] 2015-06-17 10:12
For me yes, I tried everything and all worked correctly.

**Closed** 2015-06-17 17:40 UTC
Labels: Sub-Maps/MMaps/Vmaps
