### ISSUE TITLE
Event: Lunar Festival Decorations Still Present After Event Finish (Stormwind)

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26062] opened 2021-02-09 07:52 UTC
**Description:**

As per title, Lunar Festival decorations are still popping away in Stormwind several days after the event has finished.

The Holiday entry is correct - starts and stops as expected (Yes, it says 2020 but the important part is the 24th)

```sql
SELECT `start_time`, `length`, `description` FROM game_event WHERE `holiday`= 327;
```
| start_time | length | description | 
| --- | ---: | --- | 
| 2020-01-24 11:01:00 | 20160 | Lunar Festival | 

However, the decorations remain.

<details>

![image](https://user-images.githubusercontent.com/66294837/107330726-1159b680-6b06-11eb-95a2-77bead798178.png)

</details>

I suspect something else is running somewhere?

**Expected behaviour:**

The decorations should have disappeared with the holiday's end time.

**Steps to reproduce the problem:**

1. Teleport or travel to Stormwind - Trade District (outside bank is a good start)
2. The crackers are still present and pop away every few cycles.

Note: I did a quick scout of Ironforge and Darnassus and didn't see any Lunar Festival decorations.

**Branch(es):**

3.3.5

TC rev. hash/commit:

TrinityCore rev. f6b22df9bd22 2021-01-13 00:53:43 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows 7 Ultimate x64 SP1

**Comment by offl** [comment] 2021-02-09 15:20
Can't reproduce
And can't find that issue about objects still being spawned after event end

**Comment by TQPS** [comment] 2021-02-10 06:04
I am going to go ahead and close this.

I built 0675be4bc3c5 today and again with bots.

Decorations are not appearing in 0675be4bc3c5 but they appear if you load the instance with 0675be4bc3c5 + Bots or the next restart if you add a bot from a fresh install.

I don't think this is a TC problem.

**Comment by Faq** [comment] 2021-02-10 06:10
Just wondering what could bot do to change how event works. You sure event was ended in your server?

**Comment by TQPS** [comment] 2021-02-10 06:40
> Just wondering what could bot do to change how event works. You sure event was ended in your server?

Yes, I did hours of testing today. 

- Built new commit 0675be4bc3c5 - ran on pristine TC server - no decorations 
- Built new commit with bots - ran on full DB with existing Bots - decorations appear
- Put new commit (no bots) - ran on full DB with Bots (let errors occur) - no decorations
- Put new commit with bots - ran on fresh TDB & clean Bot SQL (no bots spawned) - no decorations, but ...

...add a bot on clean DB - no decorations - but bring server down and up again - decorations appear.

I thought it might be something to do with `item_instance` in Character DB - but no it wasn't.

I tinkered with rebuilding World DB and leaving Character DB tables in tact - no decorations.
Add the `creature` backup of bots and decorations appear.

Same thing happened after Brewfest - a mug would appear after you added a bot and restarted server. It eventually disappeared some time later.

I understand this isn't a TC issue so it's something I will live with.

**Comment by gnothicObs** [comment] 2021-02-26 16:43
Were you able to locate the problem? I'm experiencing the same issue with Lunar Festival fireworks still being present in Thunder Bluff and Orgrimmar. All I have running is AHBot on my build.

**Comment by jackpoz** [comment] 2021-02-26 16:55
> And can't find that issue about objects still being spawned after event end

that's something I have fixed months ago about respawn times being saved in the db but not cleared when stopping an event

**Comment by jackpoz** [comment] 2021-02-26 16:55
@gnothicObs we have no clue which version you are using, please always include the commit hash when confirming an issue

**Comment by gnothicObs** [comment] 2021-02-26 16:58
> 
> 
> @gnothicObs we have no clue which version you are using, please always include the commit hash when confirming an issue

Yeah I'm not currently able to grab the rev. right away. Just wanted to tentatively see if TQPS identified where the problem was.

**Comment by illfated** [comment] 2021-02-26 19:47
@TQPS : Could your issue have anything to do with population of the `characters`.`respawn` table? Could truncating that table between server restarts make any difference in your case?

**Comment by Jinnaix** [comment] 2021-02-26 20:00
For reference, I think this is the issue offl meant, I was also affected by non despawning gameobjects back then:
https://github.com/TrinityCore/TrinityCore/issues/21132

**Comment by TQPS** [comment] 2021-03-01 07:35
@illfated  I will have a look at that. It makes sense because it's only happening when you create a bot, and that's where they're stored.

I start with a pristine server - no issues. 
Install bots - no issues.
Add a bot - no issues until you cycle the server.

The temporary fix is to do an LFG dungeon with bots and come back out - they've all despawned - until the server restarts.

The mug in Stormwind floating in mid-air stopped spawning some time ago; we've had a lot of updates to the DB and bots since then.

The exception is the Noblegarden Eggs in Goldshire, they've been there all year.

Just checked the respawn table - default is blank?

Mine looks like this - 6600+ rows

<details>

![image](https://user-images.githubusercontent.com/66294837/109465756-c4da1900-7abc-11eb-9792-84160c5d064e.png)

</details>

Safe to clear this out?

**Comment by illfated** [comment] 2021-03-01 10:28
Hmm, well, I have added some extra debug settings to my worldserver log, so I always get a lot of extra lines in Server.log from `characters`.`respawn` unless I truncate the table before starting a the server. I am guessing that it could have something to do with me using characters on a GM account, in addition to the mobs I kill during gameplay are stored for respawn later? Anyway, those lines look like the following:
```
2021-02-28_15:20:01 ERROR [maps] Loading saved respawn time of 1614479877 for spawnid (0,32067) - spawn does not exist, ignoring
2021-02-28_15:20:01 ERROR [maps] Loading saved respawn time of 1614503450 for spawnid (0,32068) - spawn does not exist, ignoring
2021-02-28_15:20:01 ERROR [maps] Loading saved respawn time of 1614503450 for spawnid (0,32070) - spawn does not exist, ignoring
2021-02-28_15:20:01 ERROR [maps] Loading saved respawn time of 1614475681 for spawnid (0,32071) - spawn does not exist, ignoring
2021-02-28_15:20:01 ERROR [maps] Loading saved respawn time of 1614475569 for spawnid (0,32073) - spawn does not exist, ignoring
2021-02-28_15:20:01 ERROR [maps] Loading saved respawn time of 1614475482 for spawnid (0,32074) - spawn does not exist, ignoring
```

**Comment by TQPS** [comment] 2021-03-01 21:34
@illfated Thank you so much for the truncate tip - that did it!

```sql
TRUNCATE TABLE respawn;
```

No more Noble Garden eggs and no more Lunar Fire Crackers.

I am not sure if this is the intended fix or what caused this, but things are looking good so far.

Bots are the only deviation from latest commits.

**Comment by illfated** [comment] 2021-03-01 21:44
Nice, good job sorting out the solution. Now, one of the difficulties in dealing with the population of the table `characters`.`respawn` is that there is no easy solution to keep that table cleared or cleaned up, at least not using SQL queries, both because it is no guarantee that the individual servers use the same DB names for the `characters` DB (ref. ticket #23712), and because it is difficult to know if everything should be removed or how to select which ones should be kept for the next server start.

**Comment by illfated** [comment] 2021-03-01 21:47
Having said that, I presume it would need to be a core solution, using similar functions to the ones used when the `characters`.`respawn` table is populated during gameplay.

**Comment by TQPS** [comment] 2021-03-01 22:09
What I am really curious about is why these gameobjects only appear after adding a bot. To be fair to he Devs, this isn't happening in a clean build. The  3.3.5 Bot server was the only one with this problem (installed over same pristine DB with same respawn table).

I'd be curious if anyone else with Bots are the only ones seeing this. I don't want the team running around trying to find fixes for unsupported changes.

**Comment by illfated** [comment] 2021-03-01 22:21
Jackpoz' bot farm comes to mind, but I guess you would need to start & stop the Lunar Festival event before testing if this happens using that bot farm addon. (Anyone else using that bot farm alongside TC 3.3.5 could also test it to see if it is reproducible.)

**Comment by TQPS** [comment] 2021-03-01 22:45
> Jackpoz' bot farm comes to mind, ....

I could never get Jackpoz's one to work. I am using Trickerer's Bot.  It comes with several SQL updates for the Character DB. I guess to make sure we're testing apples for apples, if anyone else is using Trickerer's bot and has the continual respawns.

**Comment by illfated** [comment] 2021-03-01 22:52
Fair enough. I mostly mentioned that bot farm in case someone else would like to test your scenario. (I struggle to find time to do that type of testing.)

**Comment by jackpoz** [comment] 2021-03-05 21:16
I'll close this issue as it happens only with custom changes, feel free to continue the discussion though.

**Closed by jackpoz** 2021-03-05 21:16 UTC
Labels: Branch-3.3.5a, Comp-Database
