### ISSUE TITLE
[3.3.5] Core/Position: Graveyard spawn misplaced: Jotunheim (Icecrown)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16003] opened 2015-12-14 23:47 UTC
Branch 3.3.5, commit 0bb2ba7b35c7cd136b4371f6d284eba0bd34b6e5

The Graveyard spawn for alliance (maybe horde too) when you die in Jotunheim/the Fleshworks gets you stuck inside a skeleton on the ground.

**Comment by Killyana** [comment] 2015-12-15 00:37
Coords for graveyards are on WorldSafeLocs.dbc we cannot change that.

**Comment by Treeston** [comment] 2015-12-15 08:19
Maybe the GO you get stuck on is misplaced then? Not sure.

**Comment by jackpoz** [comment] 2015-12-15 08:27
what's the blizz behavior ?

**Comment by Treeston** [comment] 2015-12-15 10:44
No idea what the behavior was during 3.3. Maybe someone could check current live?

**Comment by msoky** [comment] 2015-12-15 15:04
similar issues, dont forget
https://github.com/TrinityCore/TrinityCore/issues/15441
https://github.com/TrinityCore/TrinityCore/issues/14160
https://github.com/TrinityCore/TrinityCore/issues/14089

**Comment by Aokromes** [comment] 2015-12-15 15:19
Not related at all to those 3 tickets.

**Comment by Killyana** [comment] 2015-12-15 17:05
There's no GO at this position, it's just the map.

**Comment by Rushor** [comment] 2016-02-04 07:41
on current retail you don't have any problems to revive. if you died, you will instantly get your flying ghost mount without stucking in the map.

**Comment by Aokromes** [comment] 2016-07-06 17:49
I wonder if #17529 can fix this.

**Comment by offl** [comment] 2017-11-16 19:37
#17529 merged. Should be tested.

**Comment by Killyana** [comment] 2017-11-16 20:01
The commit wasn't cherry picked to 3.3.5

**Comment by Killyana** [comment] 2018-08-20 15:09
Cannot reproduce on rev. 86bba6421baf

**Closed by Killyana** 2018-08-20 15:09 UTC
Labels: Branch-3.3.5a, Comp-Core
