### ISSUE TITLE
[3.3.5] DB/Quest: Seeping Corruption (3) should be an instant reward from Chemist Cuely

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#23722] opened 2019-08-17 18:25 UTC
**Description:**

- https://www.wowhead.com/quest=3568/seeping-corruption
- https://www.wowhead.com/quest=3569/seeping-corruption
- https://www.wowhead.com/quest=3570/seeping-corruption
- https://www.wowhead.com/npc=8390/chemist-cuely
- https://www.wowhead.com/npc=8393/thersa-windsong

The quest Seeping Corruption (3) (ID 3570) is currently without any entry at all in the table `quest_template` and shows only the title **Seeping Corruption** and the standard quest headings in the quest log, including the text "log (Complete)" between the quest name and the **Description** heading. The quest should be an instant reward instead of accepting the empty quest before getting the `quest_reward` gossip from Chemist Cuely (8390).

**Current behaviour:**

After completing the preceding 2 quests [Seeping Corruption (1)](https://www.wowhead.com/quest=3568/seeping-corruption) + [Seeping Corruption (2)](https://www.wowhead.com/quest=3569/seeping-corruption), you get the final quest from Chemist Cuely, but it does not contain any quest related description in the quest acceptance gossip, because there is no entry for this quest in the table `quest_template` .

**Expected behaviour:**

There should be an entry for quest ID 3750 in the table `quest_template` with the appropriate `QuestType` flag (0) to make it auto-completable instead of being a quest you accept before handing it in for a reward. Chemist Cuely should show the available quest as a rewarded quest hand-in (question mark) after completing the previous 2 quests, instead of offering the quest as a normal quest with an exclamation mark above his head.

**Steps to reproduce the problem:**

1. Get a horde character (preferably a GM character) level 45 or above.  
2. Go to Chemist Cuely (8390), use the command `.quest add 3568` + `.quest complete 3568` and hand in the quest for reward and follow-up.
3. Get quest 3569 and hand it in to Thersa Windsong (8393).
4. Notice that the last quest (Seeping Corruption (3) (ID 3570)) becomes available from Chemist Cuely as a regular quest.
5. Open the last quest gossip to see that it contains almost no quest description at all, instead of being an instant reward.

**Branch(es):**

- [X] 3.3.5 (the whole quest line became deprecated from Cataclysm patch 4.0.3a)

**TC rev. hash/commit:** 

TrinityCore rev. a054ce864d29 2019-08-16 06:27:38 +0000 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1b  26 Feb 2019 (library: OpenSSL 1.1.1b  26 Feb 2019)
Using Boost version: 1.67.0
Using MySQL version: 5.7.27
Using CMake version: 3.13.4
Compiled on: Linux 5.0.0-1014-azure
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1997886944 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.19081

**Operating system:** Server: Unix (https://tcubuntu.northeurope.cloudapp.azure.com/)
Game Client: Windows 10 Home x64 Version 1903 (OS Build 18362.295)

Unfortunately, I don't know the complete solution to filling in the missing quest_template data for ID 3750, only the `QuestType` flag 0 (to make it auto completed).
- https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130261/quest+template#quest_template-QuestType

**Comment by illfated** [comment] 2019-08-18 12:45
Out of curiosity, would it be a hack if quest 3569 (https://www.wowhead.com/quest=3569/seeping-corruption) also completed quest 3570, or is there some extra DB settings to make quest 3570 go directly to the reward gossip instead of displaying the "accept quest" gossip first?

**Comment by offl** [comment] 2021-03-17 00:18
Duplicate of #26052

**Closed by offl** 2021-03-17 00:18 UTC
Labels: Branch-3.3.5a, Comp-Database, Sub-Quests
