### ISSUE TITLE
[3.3.5] [Quest] Massacre At Light's Point

### ISSUE THREAD

**Issue by rockz1152** [TrinityCore/TrinityCore#16027] opened 2015-12-17 00:08 UTC
Rev: b967047

When attacking the mobs on the beach from the boat, they do not appear to try and attack back.
Also after killing all available mobs within view distance, they do not seem to respawn immediately as they should, instead take about 5 minutes to reappear.
http://www.wowhead.com/quest=12701/massacre-at-lights-point
[Quest Video](https://www.youtube.com/watch?v=h4aHk7H6XfA)

**Comment by tkrokli** [comment] 2015-12-17 02:14
TrinityCore rev. 850a4468b4fc 2015-12-16 18:58:33 +0100 (3.3.5 branch) (Win64, Release)
TDB 335.60 + updates. Confirmed. But TC has been like this for as long as I can remember (2 years).

**Comment by dixanackmad** [comment] 2016-02-01 11:25
confirmed on b1d0855624d1c83850fc36f5242437d7f7c1336b the Scarlet Fleet Defender do not seem to respawn immediately, they take a lot of time to respawn.

**Comment by Kittnz** [comment] 2016-02-01 14:41
they do but you can go to the other ship and kill those

**Comment by tkrokli** [comment] 2016-02-01 15:25
Yes, that is the way to complete the quest on TC source. I don't remember if it is supposed to be completable by using only 1 cannon. From what I have seen all the time when I have tested the entire DK starting area on 3.3.5, you need to move to at least another cannon on the same ship or to the second ship. The only issue I see, is that the Scarlet Fleet Defenders never attack the player on any of the ships.

**Comment by Kittnz** [comment] 2016-02-01 16:08
it is, on retail you can do it with 1 canon, they respawn really quick

**Comment by rockz1152** [comment] 2016-02-01 16:16
Retail behavior can be seen in the following video which was also in the original post.
https://youtu.be/h4aHk7H6XfA?t=97

**Comment by Aokromes** [comment] 2016-02-01 17:26
#13787

**Comment by GnaXi** [comment] 2016-06-25 21:54
I'm not sure why this issue was closed, as the main concern of this issue was:
> When attacking the mobs on the beach from the boat, they do not appear to try and attack back.

This isssue is in no way related to #13787

**Comment by Aokromes** [comment] 2016-06-25 22:21
It's duplicate, the respawn part is duplicate of 13787 and the another of another ticket.

**Closed by Aokromes** 2016-06-25 22:21 UTC

**Comment by GnaXi** [comment] 2016-06-26 06:50
I can't seem to find the mentioned ticket (Aggro not transferred to vehicle).

**Comment by tkrokli** [comment] 2016-06-26 09:54
Aokromes: do you mean : **[[3.3.5.][6.x][Core/SAI] Vehicles attack and act as regular mobs](7450)** **#7450**

**Comment by GnaXi** [comment] 2016-06-27 16:13
Is it just me, or does it still not seem like it's related to the bug of this issue?
