### ISSUE TITLE
[ICC][BPC][Fix] Prince Keleseth's Shadow Prison

### ISSUE THREAD

**Issue by D4R4** [TrinityCore/TrinityCore#12034] opened 2014-05-08 15:31 UTC
The spell Shadow Prison casted by Keleseth when you enter combat with the BPC in Heroic mode is supposed put damaging stacks on you when you move.
The spell works as it is intended but if you 'Taunt' Keleseth as soon as you enter combat the spell's initial cast will get interrupted and it will be gone for the entire fight.
##

**Comment by Aokromes** [comment] 2016-05-26 02:05
If the fix here is valid, plz open a PR.

**Comment by tkrokli** [comment] 2016-05-26 20:47
@D4R4 : do you want to open a PR for this fix, or do you think it will be classified as a hack?
```diff
diff --git a/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp b/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
index 51711f9..1cfb9bd 100644
--- a/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
+++ b/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
@@ -409,7 +409,7 @@ class boss_prince_keleseth_icc : public CreatureScript
                 if (IsHeroic())
                 {
                     me->AddAura(SPELL_SHADOW_PRISON, me);
-                    DoCast(me, SPELL_SHADOW_PRISON_DUMMY);
+                    DoCast(me, SPELL_SHADOW_PRISON_DUMMY,true);
                 }
             }
 
```
(diff based on 3.3.5 rev. dc67505)

**Comment by Shauren** [comment] 2016-05-27 10:32
This fix is not valid. SPELL_SHADOW_PRISON_DUMMY has a cast time of 2.5 seconds, casting it with a triggered flag will skip the cast time and apply it instantly.

**Comment by ccrs** [comment] 2016-05-27 20:23
same bug as always, if there is a spell cast with cast time after a spell cast with cast time, the second one wont be casted.
Example: two events or tasks that are executed at the same time (on the same update tick)

**Comment by sirikfoll** [comment] 2016-05-27 20:45
I remember seeing in sniffs cases where a spell cast fail and then the spell is casted again, usually it fail because of Category locked. So isn't this some sort of missing feature?

**Comment by ccrs** [comment] 2016-05-27 23:41
It is, somewhere (AI probably) the cast should be stored to cast it on next tick (an successively).
The problem is a cast that is possible or correct on one update tick, maybe its not on the next one.

**Comment by Keader** [comment] 2017-01-02 12:18
I cant reproduce it in https://github.com/TrinityCore/TrinityCore/commit/cfafca7517a9239d3a137679f1e536910f374a8f
Someone can confirm if this issue is still valid?

**Comment by ccrs** [comment] 2017-01-02 17:24
with the changes to scripts preventing parallel events that include casts with casttimes
AKA adding on the end of the while loops
````c++
                    if (me->HasUnitState(UNIT_STATE_CASTING))
                        return;
````
issues like this should be unlikely, not sure to say impossible

but again, this issue was not completely related to that, so... wait?

**Comment by Keader** [comment] 2017-01-02 20:13
Already has it in current code ccrs.
I cant reproduce it anymore, so closing...
if someone can provide someway to reproduce it in current revs, please make a new issue.

**Closed by Keader** 2017-01-02 20:13 UTC
Labels: Branch-3.3.5a, Comp-C++Script, Feedback-WaitingResponse
