### ISSUE TITLE
Naxxramas: Maexxna pathfinding issue

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#21480] opened 2018-02-22 19:16 UTC
**Description:**

Maexxna is currently experiencing some pretty odd attack range/pathfinding issues. If you get aggro (Tank) and run up to the side of her web, she will stop half way down the slope and stop attacking, as long as you keep aggro on her and stay out of range. As soon as someone else gets aggro or you run down to her, she will continue attacking. See screenshot below.

http://prntscr.com/iifg9j

**Current behaviour:**

See above explanation.

**Expected behaviour:**

Maexxna should not stop half way up the slope and stop attacking the target.

**Steps to reproduce the problem:**

1. Go to Maexxna
2. Start encounter
3. Run to the top of the side wall on the right side as you enter

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  eb7d22d

**TDB version:**  TDB 335.64

**Operating system:** Windows Server 2012

**Comment by Treeston** [comment] 2018-02-22 19:20
Known issue, attack range checks on movechase use 2D distance, should use 3D.

See discussion [here](https://github.com/TrinityCore/TrinityCore/commit/274dede3dc89fa72ec1687d5ff454feba9849e47#r27495586).

**Comment by Foereaper** [comment] 2018-02-22 19:22
Ah, I see

**Comment by Keader** [comment] 2018-02-22 21:24
And more discussion here: https://github.com/TrinityCore/TrinityCore/issues/16549

**Comment by chaodhib** [comment] 2018-02-28 09:29
This issue and #16549 are not excatly duplicate. They are caused by a different reason.

The good news is that this issue is easy to solve: https://github.com/TrinityCore/TrinityCore/commit/274dede3dc89fa72ec1687d5ff454feba9849e47#r27495586.

Will submit PR shortly.

**Comment by chaodhib** [comment] 2018-02-28 12:33
After investigation, even though the change in https://github.com/TrinityCore/TrinityCore/commit/274dede3dc89fa72ec1687d5ff454feba9849e47#r27495586 is necessary, it is not enough to fix the issue with Maexxna. Indeed, like said by @Keader, the other part of the problem is https://github.com/TrinityCore/TrinityCore/issues/16549.

So i will merge https://github.com/TrinityCore/TrinityCore/commit/274dede3dc89fa72ec1687d5ff454feba9849e47#r27495586 and close this ticket. The rest of the discussion should be done in https://github.com/TrinityCore/TrinityCore/issues/16549. That issue is fixed by https://github.com/TrinityCore/TrinityCore/pull/17850, which should be merged in a near future hopefully.

**Closed by chaodhib** 2018-02-28 12:33 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Movement
