### ISSUE TITLE
[3.3.5] Burning blade Apprentice summons wrong voidwalker

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#19762] opened 2017-05-15 13:08 UTC
Description:

Burning blade Apprentice ( 3198 ) summons the wrong voidwalker as pet.

Current behaviour:

Currently the npc casts the wrong voidwalker as pet, the pet has 2300HP in a starter zone..

Expected behaviour:

Burning blade apprentice should summon correct voidwalker as pet

Steps to reproduce the problem:

burning blade apprentice ( npc=3198 ) summons voidwalker ( spell= 12746 )
Voidwalker has too high HP ( around 2300 ) and his spells hits really hard
Step 3
POSSIBLE SOLLUTION:

change the spell in smartai to another summon voidwalker spell that matches the level and starter zone or change the HP of the voidwalker..

Branch(es):

3.3.5

TC rev. hash/commit:

TrinityCore rev. e036d22+ 2017-05-10 02:41:50 +0200 (3.3.5 branch) (Unix, Debug, Static)

TDB version: TDB 335.63

Operating system: ubuntu server 16.04

**Comment by tkrokli** [comment] 2017-05-15 13:40
Duplicate of **[3.3.5] Overpowered Demon Minions in Durotar and perhaps elsewhere. #281**
Please post in that ancient issue, it is the exact same problem.

**Closed by tkrokli** 2017-05-15 13:40 UTC

**Comment by tkrokli** [comment] 2017-05-15 13:42
Your input is appreciated, but we do prefer that you post in existing open issues, allowing us to focus on closing only one issue with one solution.
