### ISSUE TITLE
Exotic hunter pet outputs excessive damage [60$]

### ISSUE THREAD

**Issue by Gooyeth** [TrinityCore/TrinityCore#21333] opened 2018-01-30 16:28 UTC
**Description:**

The elite/rare pets of the "Exotic beasts" talent have excessive damage.

**Current behaviour:**

They cause damage from 10k to 20k depending on the player's equipment.

**Steps to reproduce the problem:**

1. Get the pet "Gondria"  (http://www.wowhead.com/npc=33776/gondria)
2. Equip http://www.wowhead.com/item-set=-273/wrathful-gladiators-pursuit y others pieces wrathful
3. Cause damage with the pet

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 1acfefb973895b0e3df3c8d9b43b920d2a1b5392

**TDB version:** TDB 335.63

**Operating system:** Debian 9

**Comment by tkrokli** [comment] 2018-01-31 08:00
Exotic Beasts in 3.3.5a: https://wow.gamepedia.com/index.php?title=Exotic_Beasts&oldid=2185890

**Beast Mastery** is the 51 point talent in the Beast Mastery tree of hunters. It allows the hunter to tame exotic beasts and grants four extra skill points to spend in the pet's talent tree.

**Comment by tkrokli** [comment] 2018-01-31 08:04
Not sure if I will get time to test this before the weekend.
Would appreciate if other users can confirm this too,
as well as suggestions for source code references.

**Comment by TecDian** [comment] 2018-02-13 03:21
Confirmed. Gondria is the best dd in raid. No icc T10heroic char can compete.^^

**Comment by Killyana** [comment] 2018-02-13 18:09
Someone can test the damage with this?
``` sql
UPDATE `creature_template` SET `DamageModifier`=4.6 WHERE `entry` IN (33776);

**Comment by tje3d** [comment] 2018-02-13 19:29
@Killyana works good, now Gondria hits 2k-3k non-crit and 5k-7K crit ( 6.2k hunter )

**Comment by Jildor** [comment] 2018-02-13 19:32
Pets get damagemodifier? I don't remember that

**Comment by Keader** [comment] 2018-02-13 19:40
looks wrong to me too lol

**Comment by kaldown** [comment] 2018-02-13 21:53
```
select name, damagemodifier from creature_template where entry = 33776;
+---------+----------------+
| name    | damagemodifier |
+---------+----------------+
| Gondria |            999 |
+---------+----------------+

```
![2018-02-14--00 50 21_1366x768_scrot](https://user-images.githubusercontent.com/3754017/36175664-4b33b082-1121-11e8-94cb-8ed28df41fc9.png)
![2018-02-14--00 50 11_1366x768_scrot](https://user-images.githubusercontent.com/3754017/36175665-4b7648c0-1121-11e8-9865-f48ef1495830.png)

```
select name, damagemodifier from creature_template where entry = 33776;
+---------+----------------+
| name    | damagemodifier |
+---------+----------------+
| Gondria |            1 |
+---------+----------------+

```

![2018-02-14--00 38 56_1366x768_scrot](https://user-images.githubusercontent.com/3754017/36175666-4b9b1538-1121-11e8-8123-e4cc985c2e2a.png)
![2018-02-14--00 38 27_1366x768_scrot](https://user-images.githubusercontent.com/3754017/36175667-4bc54100-1121-11e8-9b3c-39eb9e63d1f5.png)

**Comment by Killyana** [comment] 2018-02-13 22:12
Pets musn't use damage modifier from the original on creature_template, it must be fixed.

**Comment by kaldown** [comment] 2018-02-13 23:19
@Killyana when you say "pet" you mean a creature that already tamed? For instance. This particular creature hits a lot while not tamed, but after successful taming creature damage should be fixed to what?
if use 4.6f by default, Gondria hits for 2k (non crit). if 1.0f -> 150. So which walue should be default after taming, or I didn't understand you right?

**Comment by Killyana** [comment] 2018-02-13 23:40
I don't know, but I'm certain the damage modifier musn't be used. A core dev will check this.

**Comment by ariel-** [comment] 2018-02-14 00:44
I'm not quite sure of that, what is the point to have a exotic pet if it doesn't out-dps the normal pets?, somehow they must manage to have different damage

**Comment by Shauren** [comment] 2018-02-14 08:45
The point of exotic pets is their abilities, not damage (spirit mend, bloodlust)

**Comment by MrSmite** [comment] 2018-02-19 21:37
> I'm not quite sure of that, what is the point to have a exotic pet if it doesn't out-dps the normal pets?, somehow they must manage to have different damage

All pets are normalized for damage, armor, health after they're tamed. The only benefit to exotic pets are their skins and special abilities. While not official blue posts, here are some discussions that support this statement:

http://forums.wow-petopia.com/viewtopic.php?t=2006&p=41725#p41700
https://eu.battle.net/forums/en/wow/topic/8715772582#post-3
https://us.battle.net/forums/en/wow/topic/2267592068#post-2
https://eu.battle.net/forums/en/wow/topic/17613041167#post-2

**Comment by kaldown** [comment] 2018-02-19 22:01
So what to do after all?
> All pets are normalized after they're tamed.
or it must be?
Is Gondria damage normalized before\after taming?

**Comment by MrSmite** [comment] 2018-02-20 01:15
> So what to do after all?

If they're using damage modifier then that is not considered 'blizzlike' and should be fixed.

**Comment by tje3d** [comment] 2018-05-04 15:04
Any hackfix or update on this?

**Comment by illfated** [comment] 2018-05-04 20:14
I haven't checked values or combat logs, but I noticed mostly during the last 4 weeks (playing alone as a level 80 hunter on `3.3.5`) that other spirit beasts behave much the same way as Gondria (I tamed Skoll + Loque'nahak in addition to Gondria) and found that I had to pay attention and get at least get some shots in to avoid losing loot when they killed normal hostile NPCs too fast (usually when I fought more than 1 normal mob). I still subscribe to what was said in https://github.com/TrinityCore/TrinityCore/issues/21333#issuecomment-365139109 😄

**Comment by Tatara902** [comment] 2018-05-06 18:18
The main issue here is that pets inherit the damage of the tamed beast (DamageMod in DB), this bug happens when you tame a elite creature from anywhere, however the highest level of the creature the highest damagemod in db so if you want a pet with a lot of damage you can tame a pet from a dungeon/raid or northern zone.

**Comment by MrSmite** [comment] 2018-05-07 22:04
> Now TC uses the damage of the wild animals to calculate the damage of the pets. But there should be an extra table or formula to calculate the damage of all those pet families according to level and normal/elite.

This is not correct. According to patch 3.1.0:

> https://wow.gamepedia.com/Patch_3.1.0
>All Cunning, Ferocity, and Tenacity pets now have identical bonuses - +5% Health,+5% Armor,+5% Damage

So it doesn't matter wether the pet is a cat, bear, boar or strider. Nor does it matter if it is elite, normal or exotic. The way Trinity does it is wrong but that's mainly because nobody could get a proper table sniffed to see what the pets had on retail when tamed.

**Comment by Aokromes** [comment] 2018-05-07 22:16
Maybe after https://github.com/TrinityCore/TrinityCore/commit/743980a6255a222827d4cc8555eccb14192cb260 it can be fixed properly.

**Comment by Keader** [comment] 2018-05-07 22:17
i dont think so...
Need spell scale system xD

**Comment by MrSmite** [comment] 2018-05-08 03:59
I think the issue is nobody knows what the baseline of the tamed pet should be. It's true that untamed animals have varying stats based on family (eg: a level 20 cat has higher AGI / DMG but lower HP than a level 20 bear) but when they're tamed, they're supposed to all be normalised... but to what?

One of the classic examples is Broken Tooth, a level 37 cat from the Badlands. Prior to normalization it had a tamed attack speed of 1.0 (which no other level 37 cat had) but after normalization it was adjusted to 2.0 just like bears, boars and everything else. So I guess in that regard it's simple enough to make all tamed pets have 2.0 attack but that doesn't help with HP, AGI, etc. We simply don't know what the base values are per level.

**Comment by Jildor** [comment] 2018-05-08 08:43
Can be caused by this commit?
f1986c6aafdf2457902a7a4cc7acc903cbbdc7bb

**Comment by jerbookins** [comment] 2018-09-17 08:42
Just a little bit of anecdotal evidence to support that Exotic pets are in fact OP AF 🔥

```
[G] [Archimonda]: Recount - DPS for Last Fight
[G] [Archimonda]: 1. Bitey <Archimonda> 1688.6 (77.3%)
[G] [Archimonda]: 2. Archimonda 495.4 (22.6%)(edited)
[G] [Archimonda]: Recount - Damage Done for Last Fight
[G] [Archimonda]: 1. Bitey <Archimonda> 98412 (1688.6, 77.3%)
[G] [Archimonda]: 2. Archimonda 28773 (495.5, 22.6%)
```
Solo killed Durn the Hungerer 67+ (probably could have just let my pet do it to be perfectly honest).
127,185 hp in 58 seconds as a 67 hunter with Heirloom gear and double talent points (maxed out bm, half way into marksman).

Just as a side note, because this hunter is literally the first hunter I've ever made in Warcraft, I don't know if hunter pets are supposed to be able to use more than just the 4 skill slots in the pet bar but the pets are definitely using all of their available skills even those NOT pinned to the pet bar.

**Comment by MrSmite** [comment] 2018-09-17 18:20
> Just as a side note, because this hunter is literally the first hunter I've ever made in Warcraft, I don't know if hunter pets are supposed to be able to use more than just the 4 skill slots in the pet bar but the pets are definitely using all of their available skills even those NOT pinned to the pet bar.

I played a Hunter almost exclusively on retail back in TBC/WotLK and can say without a doubt that pets are not supposed to use skills that are not on their hotbar. There are obviously skills in the Beastmastery tree but those are activated by the player so shouldn't be auto-casting.

Now for the caveat... on retail, there was a bug where pet skills in the spellbook retained their auto-cast state, most notably Cower. Naturally, this caused a crap ton of problems with aggro.

**Comment by jerbookins** [comment] 2018-09-18 00:04
In the video you can see that Call of the Wild, Rabid, Monstrous Bite, and Bite are on the pet spellbar and that it is using both Cower and Dash with autocast on.

https://streamable.com/1xp4b

**Comment by MrSmite** [comment] 2018-09-18 04:32
Yep, that's the bug I was talking about.

But it also appears your pet spells are ignoring their focus requirements and cooldowns. In the beginning, Monstrous Bite appears to fire 3 times before the cooldown appears, and Bite has a 25 focus requirement and even with 2 points in Bestial Dicipline, you would'nt generate focus fast enough for it to fire without any delay.

**Comment by ciber96** [comment] 2019-06-05 14:10
I can confirm this is still an issue. On our server we made a hackfix that normalized basic damage, but critic damage scales up to 20k. We had to disable exotic pets for know.

**Comment by ciber96** [comment] 2019-06-11 13:04
I can confirm this commit broke pets damage: https://github.com/TrinityCore/TrinityCore/commit/f1986c6aafdf2457902a7a4cc7acc903cbbdc7bb

We reverted it on our server and now pets are back to normal.

**Comment by jerbookins** [comment] 2019-06-13 03:47
@ciber96 so when you say 

> pets are back to normal

do you mean that they are still broken or did commit f1986c6 normalize all pets as they should be?

**Comment by illfated** [comment] 2019-06-13 13:44
I read his comment to mean that the pet damage is normalized after reverting that specific commit.

**Comment by Aokromes** [comment] 2019-06-14 10:37
added 60$ here

**Comment by jackpoz** [comment] 2019-06-14 13:34
A PR has been opened at https://github.com/TrinityCore/TrinityCore/pull/23403 . Please give it a try and report feedback there

**Comment by ariel-** [comment] 2019-06-14 15:22
3d7166c1c78e0e0011af840b76f3f5a8ccccaaa0 was a followup to f1986c6aafdf2457902a7a4cc7acc903cbbdc7bb. Can't recall whether Pets inherited from Creature, but this was done before.

**Comment by jackpoz** [comment] 2019-06-14 17:58
So this doesn't happen anymore on clean TC 335 ?

**Closed** 2019-06-15 13:10 UTC
Labels: Branch-3.3.5a, Priority-High, Sub-PetMinion, bounty
