### ISSUE TITLE
Creature respawn time

### ISSUE THREAD

**Issue by jimteck** [TrinityCore/TrinityCore#19557] opened 2017-05-06 06:17 UTC
**Creature respawn time not correct:**

The time of the revival of the mob is not correct.

**
The respawn time is 100 seconds, but now the creature's respawn time is more than 10 years in datebase respawn time 100 sec:**

**The time of revival should be 100 seconds**

  3.3.5a

TrinityCore rev. 4843544c2178+ 2017-05-05 05:52:49 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB 335.63**

**Operating system:Win 7 (x64) OS**

![wowscrnshot_050617_085526](https://cloud.githubusercontent.com/assets/17785949/25770389/c4046890-323c-11e7-8cdc-a8f79144ad34.jpg)

**Comment by Aokromes** [comment] 2017-05-06 06:22
If we ask creature ids, it's because something, 
cannot reproduce.

http://i.imgur.com/3OwMHUh.jpg
http://i.imgur.com/ggoZFhD.jpg

**Comment by Keader** [comment] 2017-05-06 11:16
I saw this same behavior in some Bosses with DespawnAtEvade

**Comment by tkrokli** [comment] 2017-05-08 19:02
TrinityCore rev. 538f60a880c4 2017-05-07 20:15:19 +0200 (3.3.5 branch) (Win64, Release, Static)
TDB 335.63 plus updates up to and including `2017_05_07_01_world.sql`

Unable to reproduce that issue on straight source, Creature respawns in 5 minutes as expected.
Those creatures have got `SpawnTime: Full:5m Remaining:5m35s` (plus some seconds) in Shadowglen.

**Comment by Taaboy** [comment] 2017-05-09 05:40
I feel we are overlooking something here, and may not be a bug for the extra time. As in long spawn times, i can't recall a 300-500 sec respawns that long in open area for non elite or rares mobs in that expansion.
They may have been a general mistake and blanket set those creatures spawn times, there was a lot of mistakes made in that expansion and still today the community are fixing , but also i think we are also forgetting this

```
rank
The rank of the creature:
Rank
Name
Default Respawn Time
Creature.spawntimesecs
Corpse Decay Time
Worldserver.conf (Corpse.Decay)
Total Default Respawn
spawntimesecs + Corpse.Decay
0	Normal	5 min	60 sec	6 min
1	Elite	5 min	5 min	10 min
2	Rare Elite	5 min	5 min	10 min
3	Boss	5 min	1 hour	1 hour, 5 min
4	Rare	5 min	5 min	10 min
Note 1: An NPC's rank is mostly visual (which also requires your Cache to be cleared to see changes). Changing this value will not change its health, damage, or loot. However, it will change the respawn time of the creature.
Note 2: Respawn times can be modified in two other places: Creature.spawntimesecs (only for that single GUID of the creature) and in the worldserver.conf file under the "Corpse.Decay" settings (for ALL creatures of the same rank). The default `spawntimesecs` for all spawned creatures is 300 seconds (5 minutes). For example, using the ".npc add" command to spawn a "Normal" NPC will give it a default respawn time of 6 minutes (spawntimesecs + Corpse.Decay time). Also, the creature must decay first before it can respawn. For this reason, the Corpse Decay Time of the creature is also it's minimum respawn time, since setting the creature's Creature.spawntimesecs = 0 will remove the Default Respawn Time. In the example above, setting our Normal NPC's spawntimesecs = 0 will mean the creature's respawn time decreases from 6 minutes to 60 seconds.
Note 3: If you want the creature to show a skull or "??" in the portrait (often with Bosses), set the type_flags to 4.
```

**Comment by Aokromes** [comment] 2017-05-09 05:51
totaly unrelated to this ticket.

**Comment by Taaboy** [comment] 2017-05-09 08:23
Well true or false is corpse delay in rank table added to the timer, if not the wiki for rank needs to be updated.
 For example, using the ".npc add" command to spawn a "Normal" NPC will give it a default respawn time of 6 minutes (spawntimesecs + Corpse.Decay time). **Also, the creature must decay first before it can respawn**

Shown buy your Example jpg of http://i.imgur.com/ggoZFhD.jpg  5Min57Sec, So the corpse hasn't decayed yet , so respawn action has not come into play.

So from the time of Actual Kill to Pickup of loot corpse delay is 60sec's , So depends when OP took screenshot and ran .npc info for the time to show up in log, when respawn will happen will vary but the base spawn time will set to creature table  spawntimesecs   + creature_template table  rank.

If this not true then the Wiki is wrong and either be outdated/updated or the tables are wrong thru the DB and the script in core is a problem processing the DB tables .

I have tried this on 3.3.5 and Master , with a stop watch and for me the times come in within few second's of the time stated , from your examples you have shown spawntimesec+rank setting.

**Comment by tkrokli** [comment] 2017-05-09 16:26
@Keader , do you agree to closing this issue and opening a new one, if you (or anyone else) can document that the 3.3.5 source shows creatures with invalid respawn time?

**Comment by Killyana** [comment] 2017-05-09 17:07
It's better to wait for the dynamic spawns before trying to fix anything related to respawn.

**Comment by obsidean** [comment] 2017-05-15 11:08
This isn't very scientific, but try again with a newly created character.  I had this issue, then I deleted my character and created a new one and the issue stopped occurring.  I have no idea why.

**Comment by Killyana** [comment] 2017-05-25 20:47
To reproduce this issue:
1- Kill any npc
2- Wait until the corpse disappear
3- Close or crash the server
4- Start the server and .npc if the killed npc

**Comment by ariel-** [comment] 2017-05-26 16:42
Can't reproduce either

**Comment by Keader** [comment] 2017-05-26 19:26
I'm with all updates in chracter table, and AutoUpdater active
After Razorscale wipe (DespawnAtEvade) server crash (caused by Hotswap - #18565).
When server restart, sometimes this happens:

<details>

![wowscrnshot_052617_162243](https://cloud.githubusercontent.com/assets/7120913/26509575/b9af6356-422f-11e7-8cdb-ea6894056b27.jpg)

</details>

BossState  = Boss id 2 state is 0 (NOT_STARTED).

**Comment by Killyana** [comment] 2017-06-05 22:43
I'm still able to reproduce this issue on rev. a97439e8d63c
Just the respawn time changed from SpawnTime: Full:5m Remaining:1412268760d4h16m49s  to SpawnTime: Full:5m Remaining:5899515379d8m12s

**Comment by ariel-** [comment] 2017-06-06 03:01
Do you have any repro steps?

**Comment by tkrokli** [comment] 2017-06-06 03:02
Try https://github.com/TrinityCore/TrinityCore/issues/19557#issuecomment-304119655

**Comment by Killyana** [comment] 2017-06-06 03:08
yes same steps as before.

**Comment by ariel-** [comment] 2017-06-06 03:25
I couldn't repro before with those steps, any specific creature id/guid you tested this with?

**Comment by Killyana** [comment] 2017-06-06 04:23
It happen with any npc, example:
DB GUID: 16936
Entry: 2358.
SpawnTime: Full:5m Remaining:1412268760d4h21m1s

**Comment by ariel-** [comment] 2017-06-06 04:47
Can't reproduce (c35793941b3aae9b54dce92389aa528d40050754)

```
NPC currently selected by player:
DB GUID: 16936, current GUID: 60.
Faction: 76.
npcFlags: 0.
Entry: 2358.
DisplayID: 3719 (Native: 3719).
Level: 34.
EquipmentId: 1 (Original: 1).
Health (base): 954. (max): 954. (current): 0.
InhabitType: 3
Unit Flags: 32768
UNIT_FLAG_UNK_15 (0x8000)
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 76.
SpawnTime: Full:5m Remaining:2m52s
Loot: 2358 Pickpocket: 2358 Skinning: 0
InstanceID: 0
Phasemask: 1
```

**Comment by Demonid** [comment] 2017-06-06 05:12
@Killyana Cant reproduce, are you sure your DB Structure is updated? Recently the creature_spawn tabla was changed: 4c593f12caa162c1bfb831bdbed934bb39155ddb

**Comment by Killyana** [comment] 2017-06-06 05:34
This is weird, I don't have this file sql/updates/characters/3.3.5/2017_04_12_01_characters.sql there"s only 2017_04_19_00_characters.sql on sql/updates/characters/3.3.5
After executing the missing sql, the issue is fixed.

**Closed by Killyana** 2017-06-06 05:34 UTC
Labels: Branch-3.3.5a, Comp-Core

**Comment by ariel-** [comment] 2017-06-06 06:36
Because it was merged on the TDB updates, you lost the sql between TDB 62 and 63 and never ran the 62 to 63 character update sql
