### ISSUE TITLE
[3.3.5] Winter Grasp has some bug after zone/area IDs from vmap data in the liquid update

### ISSUE THREAD

**Issue by shenhuyong** [TrinityCore/TrinityCore#19867] opened 2017-06-09 12:45 UTC
Winter Grasp has some bug after f6c849729b27b77228704b595de3adaf24da2c10.

**Description:**
After commit f6c849729b27b77228704b595de3adaf24da2c10, Winter Grasp has some bug.
 The Relic can't click and GO_WINTERGRASP_KEEP_COLLISION_WALL not disappeared after BATTLEFIELD_WG_OBJECTTYPE_DOOR_LAST be destroyed.
 I think it seems some code not working from BfWGGameObjectBuilding::Destroyed().
If I reverted  f6c849729b27b77228704b595de3adaf24da2c10 , this bug disappeared.

I add a line  sWorld->SendGlobalText("Hello world", NULL);  in the first line of BfWGGameObjectBuilding::Destroyed(). But nothing happens after I destroyed any GO in BFWG. I'm sure BfWGGameObjectBuilding::Destroyed() not working after  f6c849729b27b77228704b595de3adaf24da2c10 , BfWGGameObjectBuilding::Destroyed() be called from BattlefieldWG::ProcessEvent().

**Steps to reproduce the problem:**

1. Destroyed GO_WINTERGRASP_KEEP_COLLISION_WALL in BF Winter Grasp.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 55d8c2b919402c459826bfca327f08b3b18c6f9a
 
**Operating system:** Windows 10

**Comment by Aokromes** [comment] 2017-06-09 12:48
Duplicate of https://github.com/TrinityCore/TrinityCore/issues/19832 duplicate of #8661 and that commit was before that PR even was created.

**Closed by Aokromes** 2017-06-09 12:48 UTC

**Comment by shenhuyong** [comment] 2017-06-09 12:51
It is not a duplicate issue, it works fine before commit  f6c849729b27b77228704b595de3adaf24da2c10

**Comment by Aokromes** [comment] 2017-06-09 12:56
https://github.com/TrinityCore/TrinityCore/issues/8661#issuecomment-177931233
