### ISSUE TITLE
Scripts/Naxxramas: Noth the Plaguebringer gets stuck

### ISSUE THREAD

**Issue by RowinRuizendaal** [TrinityCore/TrinityCore#23909] opened 2019-11-12 21:51 UTC
Description:
Noth the Plaguebringer gets stuck in phase 2 upon teleporting back from the balcony to the room

Current behaviour:
Noth the Plaguebringer gets stuck in phase 2 upon teleporting back from the balcony to the room. Noth is just not teleporting back to the room.

Expected behaviour:
Noth should teleport downstairs and the fight should continue.

Steps to reproduce the problem:

Start fighting Noth The Plaguebringer. Wait for phase 2, Noth teleports to balcony and not teleporting back.

Branch(es): 3.3.5

TC rev. hash/commit:
TrinityCore rev. c79571a09678 2019-11-03 17:00:24

TDB version: TDB 335.19101

Operating system: windows server 2012

**Comment by ckegg** [comment] 2019-11-13 09:38
https://github.com/TrinityCore/TrinityCore/blob/9597195e82dc030bfadb001ddfc832041924a13b/src/server/scripts/Northrend/Naxxramas/boss_noth.cpp#L132 is the problem

https://github.com/TrinityCore/TrinityCore/blob/9597195e82dc030bfadb001ddfc832041924a13b/src/server/scripts/Northrend/Naxxramas/boss_noth.cpp#L299 is not teleporting Noth back

**Comment by ccrs** [comment] 2019-11-14 22:10
that was fast lul

**Comment by illfated** [comment] 2019-11-15 15:47
Yeah. If you remember from way back earlier, he described how he needed to reduce his involvement here to gain more peace and control over his spare time.

**Comment by WoWPortal** [comment] 2019-12-11 22:36
Removing DoCastAOE(SPELL_TELEPORT_BACK); and replacing it with const xyz solves the issue.

**Comment by illfated** [comment] 2019-12-11 22:54
Sorry, my mind is a bit slow. Are you saying "when line 299 is removed, the script works" ?

**Comment by WoWPortal** [comment] 2019-12-12 13:00
No you misunderstand.
Not removing but replacing it with const coordinates and not a spell

**Comment by illfated** [comment] 2019-12-12 18:42
Very well, thank you for pointing out what needs to be done. Let us hope someone else has got suggestions for what can be done to make it work again.

**Comment by Treeston** [comment] 2019-12-12 18:47
> No you misunderstand. removing spell cast and replacing it with const coordinates and not a spell

That's a hack. Figure out what's causing the spellcast to fail.

**Comment by Keader** [comment] 2019-12-14 19:41
Since https://github.com/TrinityCore/TrinityCore/commit/49d0a5bbb69dd352bac0009625ded2c472b66805 just get the return of cast, an check why 💃

**Comment by WoWPortal** [comment] 2019-12-15 13:54
49d0a5b
Breaks many encounters and that commit is absolutely unnecessary.

**Comment by junker1609** [comment] 2020-01-31 12:52
Noth teleports back into the middle of the room but he is unassailable and not selectable.

**Comment by illfated** [comment] 2020-01-31 17:10
How about checking the logs to see what is happening when Noth teleports back and see if there are any errors in the logs?

**Comment by junker1609** [comment] 2020-01-31 17:18
> How about checking the logs to see what is happening when Noth teleports back and see if there are any errors in the logs?

I dont think so, u can join me in the test if u wanna see the problem more closely

**Comment by xParad0x** [comment] 2020-01-31 20:45
The problem is easily solved by adding attack nearest player line and removing ImmuneToPC from the script as its not needed and breaks Noth attack

**Comment by junker1609** [comment] 2020-02-01 13:59
Original code
**246-252 boss_noth.cpp** `events.SetPhase(PHASE_BALCONY);
                        me->SetReactState(REACT_PASSIVE);
                        me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                        me->SetImmuneToPC(true);
                        me->AttackStop();
                        me->StopMoving();
                        me->RemoveAllAuras();`

I have to remove ImmuneToPC like that ? 
**246-252 boss_noth.cpp** `events.SetPhase(PHASE_BALCONY);
                        me->SetReactState(REACT_PASSIVE);
                        me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                        me->SetImmuneToPC();
                        me->AttackStop();
                        me->StopMoving();
                        me->RemoveAllAuras();`
and 
**304-308 boss_noth.cpp**`case EVENT_GROUND_ATTACKABLE:
                        me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                        me->SetImmuneToPC();
                        me->SetReactState(REACT_AGGRESSIVE);
                        break;`

If u can show its will be cool @xParad0x , Thank you.

**Comment by Killyana** [comment] 2020-02-01 14:51
The issue is related to combat/threat:
This is what .debug threat will show once the boss teleport:
Noth the Plaguebringer (GUID 21) does not threaten any units.
Threat list of Noth the Plaguebringer (GUID 21, SpawnID 127801):
1.   Drood   (GUID 3)  - threat 0.000000 [OFFLINE]
End of threat list.

Also the reset in this case will not be executed when the boss get out of combat: 
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Naxxramas/boss_noth.cpp#L98

This is a generic issue we saw it in Broggok script: https://github.com/TrinityCore/TrinityCore/commit/1bdc792559fbf4fa713fce40cdcf012e63fdc741#diff-361226ee2d7dc2bfd9b9d27273a3bad2L60

Reliquary of the Lost also has the same issue, and I encounter it here https://github.com/TrinityCore/TrinityCore/issues/21570#issuecomment-580914031

**Comment by xParad0x** [comment] 2020-02-02 15:13
@junker1609 

                   case EVENT_GROUND_ATTACKABLE:
                        me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                        //me->SetImmuneToPC(false);
                        me->SetReactState(REACT_AGGRESSIVE);
                        DoZoneInCombat();
                        AttackStart(me->SelectNearestPlayer(50.0f));
                        break;


and remove any line that has  me->SetImmuneToPC(false); and   me->SetImmuneToPC(True);

**Comment by junker1609** [comment] 2020-02-05 20:07
> @junker1609
> 
> ```
>                case EVENT_GROUND_ATTACKABLE:
>                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
>                     me->SetReactState(REACT_AGGRESSIVE);
>                     DoZoneInCombat();
>                     AttackStart(me->SelectNearestPlayer(50.0f));
>                     break;
> ```
> 
> and remove any line that has me->SetImmuneToPC(false); and me->SetImmuneToPC(True); and your script will work fine, me->SetImmuneToPC is absolutely not needed here as me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE); takes care of that already

Its fonctionnal yes ! Thank you.

**Comment by Killyana** [comment] 2020-02-15 15:03
The offline threat is causing this issue, allowing immune pc/npcs to have online threat fix it, but the teleport timer looks wrong, and if you "gm on" after the teleportation ends the boss will keep following you.
``` diff
diff --git a/src/server/game/Combat/ThreatManager.cpp b/src/server/game/Combat/ThreatManager.cpp
index 0743d70fd3..a4e5dfd94a 100644
--- a/src/server/game/Combat/ThreatManager.cpp
+++ b/src/server/game/Combat/ThreatManager.cpp
@@ -99,10 +99,10 @@ bool ThreatReference::ShouldBeOffline() const
 {
     if (!_owner->CanSeeOrDetect(_victim))
         return true;
-    if (!_owner->_IsTargetAcceptable(_victim) || !_owner->CanCreatureAttack(_victim))
-        return true;
-    if (!FlagsAllowFighting(_owner, _victim) || !FlagsAllowFighting(_victim, _owner))
-        return true;
+//    if (!_owner->_IsTargetAcceptable(_victim) || !_owner->CanCreatureAttack(_victim))
+//        return true;
+//    if (!FlagsAllowFighting(_owner, _victim) || !FlagsAllowFighting(_victim, _owner))
+//        return true;
     return false;
 }

**Comment by Killyana** [comment] 2020-03-28 15:36
The boss has more than one issue, for example it will keep follow the player after an evade https://imgur.com/wQAw6aj

**Comment by illfated** [comment] 2020-03-28 15:58
True. I confirmed that this issue is still in effect just a few moments ago on tcubuntu.northeurope.cloudapp.azure.com . Noth the Plaguebringer follows the player (even GM) around all of Naxxramas, regardless of which quarter you visit (didn't test moving on to Sapphiron or Kel'Thuzad). Interesting to watch what happens if you go there with a mage, warlock or hunter with your pet active. Set your pet to Aggressive and watch your pet twitch endlessly between attacking and stopping the attack, as fast as the game animation will allow it.

**Comment by jjo72ddd** [comment] 2020-04-17 04:09
```
events.SetPhase(PHASE_BALCONY);
me->SetReactState(REACT_PASSIVE);
me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
me->SetImmuneToPC(true);
me->AttackStop();
me->StopMoving();
me->RemoveAllAuras();
```

ok, if I delete the line ```me->SetImmuneToPC(true)```, can the player select the boss and attack him?

**Comment by Jildor** [comment] 2020-08-25 09:57
Should be closed by: https://github.com/TrinityCore/TrinityCore/commit/1181b636c0cec174367906808c999641ca7897fc

**Closed** 2020-08-25 10:19 UTC
Labels: Branch-3.3.5a, Comp-C++Script, Sub-Instances
