### ISSUE TITLE
Warden not printing checks into the log file.

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#14676] opened 2015-05-10 16:13 UTC
3.3.5 #14605 TDB_full_58
TrinityCore rev. 10f7ed91f1af+ 2015-05-07 05:57:13 -0700 (3.3.5 branch) (Unix, Release) (worldserver-daemon)

Hiho! Is this normal, that with this setup below, warden isn't saving logs? Server is normally creating a file warden.txt (in a warden folder) but it isn't printing anything inside. GM command logs are working, so I'm asking. 

Appender.Console=1,3,0
Appender.Server=2,2,0,Server.log,w
Appender.GM=2,2,15,gm/gm.log
Appender.DBErrors=2,2,0,DBErrors.log
Appender.Warden=2,4,0,warden/warden.log

**Comment by Aokromes** [comment] 2015-05-10 16:14
2015-05-03_22:58:52 WARN  [warden] [Player: xxxxxxxx (GUID Full: xxxxxxxxxxxxxx Type: Player Low: xxxxxxx, Account: xxxxxxxx)] failed Warden check 209. Action: Ban

**Comment by selenir** [comment] 2015-05-10 16:20
Ok. The new file was created (with a date) but nothing is written inside. Console shows:
"[Player: xxx (GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1)] failed Warden check 209. Action: Kick".

Tried chmods, turning server off.

Thank you.

**Comment by tkrokli** [comment] 2015-05-10 16:23
For an issue to be valid, you need to include your core revision hash and TDB version.
You also did not include your **Logger.warden** setting, which is disabled (#) by default.

**Comment by selenir** [comment] 2015-05-10 16:28
Logger.warden=3,Console Server

**Comment by tkrokli** [comment] 2015-05-10 16:31
If this works for you, fine, you can close the issue. If you think this is an issue affecting all users and that it needs to be fixed, at least provide your TrinityCore revision hash, preferably also TDB version.

**Comment by selenir** [comment] 2015-05-10 16:33
Provided in the first post. It isn't working. I need to save the logs to the file. It's created, but the server isn't writing into it.

**Comment by tkrokli** [comment] 2015-05-10 16:38
Please provide the core revision info as well, from line 1 in your Worldserver console or log.

**Comment by selenir** [comment] 2015-05-10 16:39
Updated first comment.

**Comment by Aokromes** [comment] 2015-05-10 16:51
change 4 to 3.

**Closed by Aokromes** 2015-05-10 16:51 UTC
Labels: Invalid-IncompleteData/NotTrinityCore

**Comment by tkrokli** [comment] 2015-05-10 16:55
@selenir : look at your core revision hash, which is "10f7ed91f1af+", the + meaning that you have added other commit(s) to the source (not a TC core rev.) and that the date 2015-05-07 does not have any commits from TrinityCore: https://github.com/TrinityCore/TrinityCore/commits/3.3.5

**Comment by selenir** [comment] 2015-05-10 17:19
Is it really that important? 

Still not working. It is Appender.Warden=2,3,15,warden/warden.log from the beginning.
I think that this line is wrong: Logger.warden=3,Console Server

**Comment by tkrokli** [comment] 2015-05-10 17:23
The reason TrinityCore wants you to use a valid core revision hash is that the developers need to know that your issue is happening in a recent core from clean TC source. Too many unknown factors otherwise.

**Comment by selenir** [comment] 2015-05-10 17:34
It is clear, that i have the latest revision (#14605). I just added the transmogrification system from Rochet (it is connected to TC2 somehow, I don't understand this). This is the one improvement I've made.

**Comment by tkrokli** [comment] 2015-05-10 17:43
> I just added the transmogrification system from Rochet [...]

Sure, but it is still required to add that info to the top of your first post in an issue, so long as you want your post to be handled as a valid issue. BTW, #14605 is just a PR and is not yet merged with TC source.

If you doubt me regarding the required info, see this forum post:

http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/

![TrinityCore Forum](https://camo.githubusercontent.com/223d419a88fb8a0dbc03e08818169ff3f23414d0/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3533393337342f3537383736312f63393236613631612d633836312d313165322d396131312d6231333265306330366137332e706e67 "The issue tracker and you")

**Comment by selenir** [comment] 2015-05-10 17:49
Thank you for informing me. I am new here, didn't know everything.

The main problem will remain unsolved, right? :D

**Comment by tkrokli** [comment] 2015-05-10 18:25
According to Aokromes in his post https://github.com/TrinityCore/TrinityCore/issues/14676#issuecomment-100662333, is is not possible to reproduce on clean source :
```
Appender.Warden=2,3,15,warden/warden.log

2015-05-03_22:58:52 WARN [warden] [Player: xxxxxxxx (GUID Full: xxxxxxxxxxxxxx Type: Player Low: xxxxxxx, Account: xxxxxxxx)] failed Warden check 209. Action: Ban
```
See also Aokromes' post https://github.com/TrinityCore/TrinityCore/issues/14676#issuecomment-100668151 :
> change 4 to 3.

Based on this info, I half expected to see the label [Invalid-CannotReproduce], but the issue remains closed unless you can provide better documentation that this affects all users of the source and that the source should work in a different way when working properly. I don't know about it, though. I don't use Warden.

**Comment by Carbenium** [comment] 2015-05-10 20:09
@selenir: You are right that
```
Logger.warden=3,Console Server
```
is wrong. It shoud be 
```
Logger.warden=3,Console Warden
```
if the error messages should be printed on the console and to the warden.log file.

**Comment by tkrokli** [comment] 2015-05-10 22:45
:+1: Good point. I feel stupid for not noticing that before now. :8ball:

**Comment by selenir** [comment] 2015-05-11 09:06
God, THANK YOU!

**Comment by tkrokli** [comment] 2015-05-11 09:11
@Aokromes, @Carbenium : I know that the conf files have low priority when it comes to suggesting changes, but wouldn't it be a lot better to change some of the most used Logger names to the same name as its Appender name in the Logging section?

**Comment by Aokromes** [comment] 2015-05-11 09:34
By default no warden separate log is created, it belongs to the user to adapt the logs to the needs he got.
