### ISSUE TITLE
n_offset server crash

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#29076] opened 2023-06-18 12:29 UTC
### Description

https://gist.github.com/PivanDepolo/6e0bcbe90c1f2d8270ebcd4b497d7759

### Expected behaviour

Must not crash

### Steps to reproduce the problem

idk

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/f93b4d6c438b337d15bf1666f6f0e050beb97ce4

### Operating system

Debian 11

### Custom changes

No

**Comment by Shauren** [comment] 2023-06-18 12:37
Duplicate of #28983

**Closed by Shauren** 2023-06-18 12:37 UTC
Labels: Branch-master

**Comment by PivanDepolo** [comment] 2023-06-23 08:20
This seems to happen when a Hunter or Warlock summons pets.
