### ISSUE TITLE
MaxPrimaryTradeSkill ; Can't learn all professions?

### ISSUE THREAD

**Issue by M-Pan** [TrinityCore/TrinityCore#15575] opened 2015-09-22 22:56 UTC
Config allows for a range from 0-10 but there are 11 professions available in-game- Is 10 a client limitation or can the max be raised by one to allow characters to actually learn all 11?

By my count: 
    1. Alchemy 
    2. Enchanting
    3. Herbalism
    4. Jewelcrafting
    5. Mining
    6. Tailoring
    7. Blacksmithing
    8. Engineering
    9. Inscription
    10. Leatherworking
    11. Skinning

Core: 02d014c69d53 (3.3.5)
DB:  TDB 335.59

**Comment by tkrokli** [comment] 2015-09-22 22:59
Well, the documentation is off by 1 count, the amount of professions IS 11. Not sure if it was intended.
And YES, you can learn all 11 if you just set the Worldserver.conf setting to 11 instead of 2 or 10.

Fun fact: "It goes to 11" is a hidden reference to Spinal Tap, they turned their amps up to 11 (not 10).

**Comment by M-Pan** [comment] 2015-09-22 23:04
Confirmed. Changed the config to 11, restarted the server and learned my 11th profession.

I'll file a pull request shortly. Feel free to close this issue.

**Comment by tkrokli** [comment] 2015-09-22 23:09
I can't close this issue, but you can do it yourself. Just check the buttons below. :smiling_imp:

**Comment by DDuarte** [comment] 2015-09-23 00:02
Config text should be fixed.

**Closed** 2015-09-23 00:06 UTC
