### ISSUE TITLE
Worldserver crash when i enter the server

### ISSUE THREAD

**Issue by MattcoreCS** [TrinityCore/TrinityCore#19272] opened 2017-03-10 13:41 UTC
TrinityCore rev. 6067d19dfc43 2017-03-08 19:22:48 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36C0 (14016)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36BF (14015)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F7 (14071)] from [Player: Account: 1]
[Player: Account: 1] Client tried to call not implemented method ResourcesService.GetContentHandle({ program: 16974 stream: 1634756212 version: 1701729619 })
No defined handler for opcode [UNKNOWN OPCODE 0x36BB (14011)] sent by [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36C0 (14016)] from [Player: Account: 1]
Received not handled opcode [CMSG_QUEUED_MESSAGES_END 0x376C (14188)] from [Player: Porian GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x20000400200308C00000000000000295 Type: Creature Entry: 3107 Low: 661 Entry: 3107
Received not handled opcode [CMSG_DF_GET_JOIN_STATUS 0x3612 (13842)] from [Player: Porian GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
Received not handled opcode [CMSG_DF_GET_SYSTEM_INFO 0x3611 (13841)] from [Player: Porian GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
Received not handled opcode [CMSG_LFG_LIST_GET_STATUS 0x3609 (13833)] from [Player: Porian GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
Received not handled opcode [CMSG_QUERY_COUNTDOWN_TIMER 0x31A2 (12706)] from [Player: Porian GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
Received not handled opcode [CMSG_REQUEST_CONQUEST_FORMULA_CONSTANTS 0x328D (12941)] from [Player: Porian GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
Received not handled opcode [CMSG_REQUEST_LFG_LIST_BLACKLIST 0x327E (12926)] from [Player: Porian GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
Received not handled opcode [CMSG_GARRISON_REQUEST_LANDING_PAGE_SHIPMENT_INFO 0x32CA (13002)] from [Player: Porian GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
CMSG_DB_QUERY_BULK: [Player: Porian GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1] requested unsupported unknown hotfix type: 3386291891
Attempt get value from non-existed value field: 2317 (count: 216) for object typeid: 3 type mask: 9
 

Info:

Branch: Master

Commit: Latest, updated

OS: Windows server 2008 R2

I created a new shaman troll and i did the first quests, when i receive my second quest, my game acts like I'm without internet connection, and a few moments later, the world server crashes.

I really don't know what to do :/

**Comment by DDuarte** [comment] 2017-03-10 14:01
Post the crashlog.

**Comment by MattcoreCS** [comment] 2017-03-10 14:10
My bad.

Log: https://gist.github.com/MattcoreCS/565a65c60426078684180e9c380cab3b

**Comment by DDuarte** [comment] 2017-03-10 14:39
I actually meant the crashlog, it's a .txt file in the `Crashes` folder.

**Comment by MattcoreCS** [comment] 2017-03-10 14:45
crashlog: https://gist.github.com/MattcoreCS/f473e248017f520ec6be7d89d8d7201f

**Comment by DDuarte** [comment] 2017-03-10 14:52
Thanks, duplicate of #19270

**Closed by DDuarte** 2017-03-10 14:52 UTC
Labels: Branch-master
