### ISSUE TITLE
[3.3.5] CRASH - ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#19254] opened 2017-03-06 02:08 UTC
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
[ad6ecbf09b24+_worldserver.exe_[5-3_20-54-40].txt](https://github.com/TrinityCore/TrinityCore/files/819985/ad6ecbf09b24._worldserver.exe_.5-3_20-54-40.txt)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** ad6ecbf
TrinityCore rev. ad6ecbf09b24+ 2017-03-04 12:22:21 -0300 (master branch) (Win
32, RelWithDebInfo, Static) (worldserver-daemon) ready...

My cloned repository had 3.3.5 as master branch some time ago

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:** Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment] 2017-03-06 02:27
You have any repro steps?
Because this crash log sees the same of #19227
You can reproduce this crash in a clean TC?

( if your tc is not clean, you can use ecfb346d1af39305923db1f19a4568355c4d94e5 to fix your crash)

**Comment by Ovahlord** [comment] 2017-03-06 09:53
Nullpointer reference at spell_sindragosa_s_fury  once again.

**Comment by jackpoz** [comment] 2017-03-06 11:03
Yup, and this time the properly written code shows a nice assertion triggered :)

**Comment by jackpoz** [comment] 2017-03-08 08:28
@Noryad you can change the assert to a NULL check to fix the issue locally

**Comment by Keader** [comment] 2017-03-18 02:45
12 days without answers so closing...
If you have repro steps, pooke me or open a new ticket

**Closed by Keader** 2017-03-18 02:45 UTC
Labels: Branch-3.3.5a, Feedback-WaitingResponse, HasBacktrace
