### ISSUE TITLE
[Aggro] No Aggro from respawning mobs when in range but not moving

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#1031] opened 2011-05-16 22:29 UTC
So I never played on retail, but I noticed something that didn't seem right to me, so forgive me if I'm totally off. Also I'm not certain which component this belongs to.
1. Enter combat by going near a group of mobs
2. Kills all mobs
3. Stand still and wait for respawn
4. Upon respawn mobs will not attack you until you move.

Also you can attack npcs of the group without drawing the others attention when doing ranged attacks (= as in not moving).
You can also jump and turn yourself around, as long as you don't move horizontally.
##

**Comment by Killyana** [comment] 2015-04-14 14:39
This happen also when you summon a npc, so when a creature spawn, respawn or reset it must check if there's an attackable unit in range, this will fix many issues an avoid extra useless code like "just_summoned attack closest_enemy"

**Comment by Skiopz** [comment] 2015-07-21 13:13
Yup, this is still here on db3a355 and it would be cool to get it working as intended ! :+1:

**Comment by tkrokli** [comment] 2015-07-21 15:37
I did not think this issue existed any longer until yesterday (3c4484d782ac) when I tested the Death Knight quest chain again (to verify or reproduce issues etc.). While doing the quest [[The Gift That Keeps On Giving]](http://www.wowhead.com/quest=12698/the-gift-that-keeps-on-giving) and using [[Gift of the Harvester]](http://www.wowhead.com/item=39253/gift-of-the-harvester) (quest item). Before I had gained any ghouls from the miners, the hostile ghost spawned instead in the first 2 miner kills. I just stood still, waiting for them to attack, but they did not attack before I started moving. Later, when I had collected 2 ghouls, I could not tell if the hostile ghost moved first or the ghouls moved first to attack the ghost.

**Comment by Frytiks** [comment] 2015-07-21 16:07
No, that issue still exist

**Comment by tkrokli** [comment] 2015-07-21 16:19
OK, I should have stated "issue confirmed on 3c4484d782ac" in my previous comment.

**Comment by Treeston** [comment] 2016-08-17 09:43
This issue no longer exists on latest TC revision. Closing.

**Comment by Killyana** [comment] 2019-05-08 18:57
Broken again

**Comment by Shauren** [comment] 2019-05-08 19:00
Dont dig out ancient issues that were fixed but got broken again - open a new one

**Closed** 2019-05-08 19:00 UTC
Labels: Sub-Entities, Sub-Miscellaneous
