### ISSUE TITLE
Core/Vehicles: Remove dead passenger

### ISSUE THREAD

**Issue by Sorikoff** [TrinityCore/TrinityCore#24119] opened 2020-01-30 10:37 UTC
**Description:**

Installed and added as passenger vehicle accessory can not be removed from vehicle after death (but possible while alive).

Notable example is vehicle `28782` and accessory `28768` (DK quest: `12687`). Dark Rider of Acherus must exit vehicle after death but he remains in it until despawned.

**Steps to reproduce the problem:**

1. Move `me->ExitVehicle()` from hook `EnterCombat()` to `JustDied()` (c. 28768)
2. Kill 28768
3. Notice that 28768 remains on 28782

**TC rev. hash/commit:**  TrinityCore rev. 0ec2a5fd745c 2020-01-27 02:49:36 +0100 (3.3.5 branch)

**Comment by Aokromes** [comment] 2020-01-30 10:38
right, the same problem is for example with players and yogg saron tentacles.

**Comment by offl** [comment] 2020-01-30 11:33
Duplicate of #23095

**Closed** 2020-01-30 11:34 UTC
