### ISSUE TITLE
Mr. Smite pulls more adds than intended

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19164] opened 2017-02-19 06:05 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Pulling Mr. Smite anywhere agros more than just pirates. Starting the fight agroes a few of the pirates standing behind him.

He should not be pulling the pirates behind him.

**Branch(es):**
3.3.5

**TC rev. hash/commit:**
 76f3e0edea88 2017-02-18 11:36:02 +0100 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**  
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by MrSmite** [comment] 2017-02-19 07:25
Pulling Mr. Smite anywhere aggros more than just pirates ;)

Anyway, I can confirm this behavior on a slightly older core too. I'm not sure if it's a linking issue or if he needs to have a faction change so the pirates won't assist.

**Comment by ariel-** [comment] 2017-02-20 17:27
@MrSmite: Control your damn adds!

**Comment by MrSmite** [comment] 2017-02-21 02:55
> Control your damn adds!

I know, right! I yelled at them to *check out that noise* and they just stand around stroking their parrots!

I'll have to improvise.

**Comment by offl** [comment] 2017-12-18 21:07
```cpp
me->SetNoCallAssistance(true);
```
?

**Comment by Teppic1** [comment] 2017-12-18 21:19
This is being caused by chain aggro not being like it is in retail (i.e. a simple radius rather than continuing chain from npc to npc). The pirates are sufficiently distant that they shouldn't be pulled automatically.

**Comment by jerbookins** [comment] 2017-12-19 02:01
Here's a video of what looks like BC live server footage of a 41 paladin killing Mr. Smite

https://www.youtube.com/watch?v=OS54uMVd1iU

When Smite is pulled by you attacking the stealthed pirates at the bottom of the ramp, he pulls the two extra pirates behind him.

**Comment by gmillerd** [comment] 2017-12-19 04:07
In the current HEAD db of 335 making it up that ramp after smite is tough, you can easily pull the whole side with Cookie if you carelessly walk up the ramp at level.

The whole boat has aggro issues like this,  the pirates come off the upper scaffolding when you pass under it, pulling the guys on the ramp and the base of the ramp. It's a train wreck to fight all that at level.

I realize this was a bit of thing in retail as well, perhaps its the parrots being pre summoned and they make the aggro "bloom".

The speed at which pirates flee ... whoa, Deadmines is aptly named.

**Comment by Teppic1** [comment] 2017-12-19 09:34
Reduce assistance radius to 5 yards (approximate retail value) and he won't pull the pirates. The default in TC is too high (10 I think) to compensate for no chaining of assistance.

**Comment by offl** [comment] 2020-03-29 15:07
Another way https://github.com/cmangos/tbc-db/commit/a5887777dfcd63689e9e2ae2add6cb11a28d7826
But focus on this comment:
> Aggro Linking is done in creature_linking, callforassist pulse chainpulls other nonrelated mobs

If Mr. Smite must be in formation with some NPCs, then the issue must be fixed by making all creatures in formations stop call for assistance on aggro. Because from my expirience sometimes some formations(MGTR) are close to each other but can be pulled separately.
So in future it is not about a new extra flag. You can't add it to all creatures. Simply because sometimes it will make some formations behavior non-blizzlike.

One formation can still aggro another formation by accident if creatures from one formation are already in combat(creature was feared into another pack).
Single creatures with waypoint almost always are without formations and can be single-pulled.

**Comment by Killyana** [comment] 2020-03-29 16:34
This is the current formations:
``` sql
DELETE FROM `creature_formations` WHERE `memberGUID` IN (79337,79330,79338,79345,79346);
INSERT INTO `creature_formations` (`leaderGUID`,`memberGUID`,`dist`,`angle`,`groupAI`, `point_1`, `point_2`) VALUES
-- Mr Smith and the 2 Defias Blackguard in front
(79337, 79337, 0, 0, 515, 0, 0),
(79337, 79345, 0, 0, 515, 0, 0),
(79337, 79346, 0, 0, 515, 0, 0),
-- The 2 pirates behind
(79338, 79338, 0, 0, 515, 0, 0),
(79338, 79330, 0, 0, 515, 0, 0);
```
I tried putting all this spawns in the same AI with no assist when the boss aggro, but still callforassist is called for the 2 spawns behind him.

Also the position of this 2 pirates is wrong (probably like all spawn in this instance) they must be much closer.
``` sql
(@CGUID+307, 657, 36, 1581, 0, 3, 1, 0, 0, 0, -28.81776, -795.674, 19.39633, 6.021386, 7200, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 657 (Area: 0 - Difficulty: 0)
(@CGUID+309, 657, 36, 1581, 0, 3, 1, 0, 0, 0, -21.87397, -802.9406, 19.76329, 1.727876, 7200, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 657 (Area: 0 - Difficulty: 0)
```

**Comment by offl** [comment] 2020-03-29 17:12
https://youtu.be/OZo2s5sI-TA?t=236
https://youtu.be/Jm_5e3UEPq4?t=286

**Comment by Killyana** [comment] 2020-03-29 17:46
We will respawn the instance an other time.

**Closed by Killyana** 2020-03-29 17:46 UTC
Labels: Branch-3.3.5a
