### ISSUE TITLE
Island of exiles.

### ISSUE THREAD

**Issue by NiganNi** [TrinityCore/TrinityCore#25720] opened 2020-12-14 12:05 UTC
Description:
When I choose the island of exiles, I appear in the initial location

Steps to reproduce the problem:

Create a hero
Choose an island of exiles

Branch(es): master
TrinityCore rev. 5f3a2d2 2020-12-11 22:19:19 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

Operating system:
Win 10

**Comment by MaxtorCoder** [comment] 2020-12-14 12:07
Duplicate of #25711

**Closed** 2020-12-14 12:39 UTC
Labels: Branch-master
