### ISSUE TITLE
[General] Evade/Movement Issues

### ISSUE THREAD

**Issue by Amit86** [TrinityCore/TrinityCore#4943] opened 2012-01-24 17:03 UTC
Hey
I didnt really know how to classify these problems im having

It started with the issue in ToC where some mobs got stuck in evade - this was fixed by applying this #4877 by @Vincent-Michael

The problem persist with other, more general mobs like world mobs etc
Players attack a mob, he keeps evading and when they try to run away he keeps following them to the end of time (or till server crashes/they die)

I have no idea how to reproduce this but im sure many of you have seen this problem or heard of it at least 1 time

Please confirm.

Hash: 8776158
##

**Comment by ibakula** [comment] 2015-03-16 12:12
One way to reproduce this "evade bug" is to go into the Zul'Aman and fight "Nalorakk", let him kill you and then release the spirit, enter the instance and fight him again.. which you'll be unable to because he'll evade all of your attacks or you'll possibly see "out of range" bug.

While I was debugging I stumbled upon the following.

Callstack:
Creature::CanStartAttack(who, false) Line: 1387
CreatureAI::MoveInLineOfSight(who) Line: 135
boss_nalorakk::boss_nalorakkAI::MoveInLineOfSight(Unit* Who) Line: 218

Autos:
CanFly() returned false
GetDistanceZ(who) returned 7.xxxf

I am not sure if I was of any help but this is what I've managed to debug on my own.
Under "CreatureAI::MoveInLineofSight", Line on which you can find "me->CanStartAttack" then returns false and exits the MoveInLineOfSight function.

What would have fixed this issue is:
HomeMovementGenerator<Creature>::Finalize
If the HomeMovementGenerator<Creature>::arrived was evaluated to true, because the NPC would clear its Evade state.
Or:
boss_nalorakk::boss_nalorakkAI::Reset() Line 166
If you added "me->ClearUnitState(UNIT_STATE_EVADE);" after the line above

Both of these ways may be the incorrect way of fixing this.

Also, when scripting a creature movement and then using a Clear function, for some reason the boss becomes un-attackable.. "out of range"

Example of this issue can be found in "Zul'Jin"

After the clear function happens, the creature's unit state flags are equal to: 
UNIT_STATE_CASTING | UNIT_STATE_MELEE_ATTACKING

Zul'Jin in the eagle phase should not be moving.

I may not be good at programming or debugging at all but I'd be interested to see what's the proper way to resolve this.

And also I do run a bit outdated TrinityCore revision (of my own fork) with a several hundreds/thousands of cherry-picked commits that happened after the time of Boost's implementation, because I wasn't too sure whether the boost implemented revision was stable and tested enough until now but otherwise I do have the most of your commits applied.

Cheers!

**Comment by jackpoz** [comment] 2015-03-16 12:54
Re-opening till someone can either confirm/deny

**Comment by Frytiks** [comment] 2015-03-16 18:16
I can confirm it on last rev.

**Comment by ille** [comment] 2015-03-16 18:17
@ibakula @ jackpoz 
may its related to the CombatStart() part?
https://github.com/TrinityCore/TrinityCore/issues/4943#issuecomment-58331386

**Comment by Demonid** [comment] 2015-03-17 02:18
@jackpoz I recently updated my core to rev cf14e9051d15e33ca9fa87be3287d2a628faedef and some NPC and Sindragosa went into evade mode.

So i think the fix you added some time ago jackpoz is not fully working.

Add this two codes and should work better:

diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 1eed96c..f5f1ea4 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -11639,7 +11639,7 @@ void Unit::SetInCombatWith(Unit* enemy)
 
 void Unit::CombatStart(Unit* target, bool initialAggro)
 {
-    if (initialAggro)
+    if (initialAggro && !target->HasUnitState(UNIT_STATE_EVADE))
     {
         if (!target->IsStandState())
             target->SetStandState(UNIT_STAND_STATE_STAND);

diff --git a/src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp b/src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp
index 986014e..4ff16af 100644
--- a/src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp
+++ b/src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp
@@ -30,9 +30,9 @@ void HomeMovementGenerator<Creature>::DoInitialize(Creature* owner)
 
 void HomeMovementGenerator<Creature>::DoFinalize(Creature* owner)
 {
+    owner->ClearUnitState(UNIT_STATE_EVADE);
     if (arrived)
     {
-        owner->ClearUnitState(UNIT_STATE_EVADE);
         owner->SetWalk(true);
         owner->LoadCreaturesAddon(true);
         owner->AI()->JustReachedHome();

**Comment by jackpoz** [comment] 2015-03-17 08:10
https://github.com/TrinityCore/TrinityCore/issues/4943#issuecomment-58350856 already commented on the changes above

**Comment by elperro22** [comment] 2015-05-03 20:33
Confirmed on 09aed2565966c96d403afe44a0cce423c59cb4ec

**Comment by Raydor** [comment] 2015-05-20 14:26
The sindragosa evade is just because you didn't kill all the bosses before fighting her, the bug is on the doors or something (in the official, you couldn't enter to fight her until you killed all the bosses).

**Comment by Rushor** [comment] 2016-02-02 07:56
further example:

@Treeston wrote:
> 3.3.5 0316dff24530da83ef3466500ee8bd4e1af548ba

> [Quest: Tails Up](http://www.wowhead.com/quest=13549/tails-up#comments)

> Behavior is broken compared to retail:

> - After being [dart](www.wowhead.com/item=44890)-ed, the mob evades to its spawn point and  keeps pathing (even though now friendly) instead of falling asleep and staying where it is.
 - After "talking" to the now-friendly mob and selecting the gossip option, if it is a male, it _then_  falls asleep (it is supposed to go aggressive and attack you). If it is a female, it just sits there   doing nothing (it's supposed to go passive and follow you around).
 - The identified mobs also take a very long time to despawn, meaning if you don't get lucky > enough to complete the quest on the first go around (or there's multiple players) you're in for a > very long wait (unless you kill the identified mobs).

**Comment by jackpoz** [comment] 2016-02-02 08:55
does the Tails Up quest issue have anything to do with the behavior described in the issue description ?
>Players attack a mob, he keeps evading and when they try to run away he keeps following them to the end of time

**Comment by Rushor** [comment] 2016-02-02 09:05
the mainissue is triggered by evading issues.
and because this is the mainticket for all evading issues, i added the inforamtion here

like we did it with all other issues:
https://github.com/TrinityCore/TrinityCore/issues/5217
https://github.com/TrinityCore/TrinityCore/pull/7748
https://github.com/TrinityCore/TrinityCore/issues/7986
https://github.com/TrinityCore/TrinityCore/issues/9116
https://github.com/TrinityCore/TrinityCore/issues/9150
https://github.com/TrinityCore/TrinityCore/issues/10489
https://github.com/TrinityCore/TrinityCore/issues/10826
https://github.com/TrinityCore/TrinityCore/pull/11039
https://github.com/TrinityCore/TrinityCore/issues/11218
https://github.com/TrinityCore/TrinityCore/issues/12186
https://github.com/TrinityCore/TrinityCore/issues/9275
https://github.com/TrinityCore/TrinityCore/issues/5447

**Comment by jackpoz** [comment] 2016-02-02 09:25
https://github.com/TrinityCore/TrinityCore/issues/16363#issuecomment-176076240
>We are evading because the gossip won't show if we are in combat

This sounds like a very specific issue related to the SAI script of that quest, not a general evading issue. Gossips not showing in combat is also totally unrelated.

Piling up different issues in the same page and moving the discussion of different topics in the same place will just get messy. If you want to have a main ticket, create a new one with a task for each sub-ticket without closing them (also called "Milestone")

**Comment by kontownik** [comment] 2016-02-02 11:43
you can test this one https://github.com/TrinityCore/TrinityCore/issues/4943#issuecomment-37418596

**Comment by MrSmite** [comment] 2016-07-30 18:10
I wonder if this could be related;

```C++
bool CreatureAI::_EnterEvadeMode(EvadeReason /*why*/)
{
    if (!me->IsAlive())
        return false;

    me->RemoveAurasOnEvade();

    // sometimes bosses stuck in combat?
    me->DeleteThreatList();
    me->CombatStop(true);
    me->LoadCreaturesAddon();
    me->SetLootRecipient(NULL);
    me->ResetPlayerDamageReq();
    me->SetLastDamagedTime(0);

    if (me->IsInEvadeMode())
        return false;

    return true;
}
```

Notice how this function clears all combat / threat info but then returns *FALSE* if *IsInEvadeMode()*. Maybe that check should be done before clearing everything. Also, why would *_EnterEvadeMode()* even be called if creature is already in evade?

**Comment by tkrokli** [comment] 2016-07-30 18:56
I am purely guessing here, but maybe that check should be moved up before the reset calls and check for "not Evading" instead?
```cpp
bool CreatureAI::_EnterEvadeMode(EvadeReason /*why*/)
{
    if (!me->IsAlive())
        return false;

    if (!me->IsInEvadeMode())
        return false;

    me->RemoveAurasOnEvade();

    // sometimes bosses stuck in combat?
    me->DeleteThreatList();
    me->CombatStop(true);
    me->LoadCreaturesAddon();
    me->SetLootRecipient(NULL);
    me->ResetPlayerDamageReq();
    me->SetLastDamagedTime(0);

    return true;
}
```
I am not any good at coding, so it may be a logical mistake. More like "food for thought".

**Comment by MrSmite** [comment] 2016-07-30 19:40
@tkrokli 

I agree the check should be at the top but the original check is correct, at least in the contex of when *_EnterEvadeMode* is called from *EnterEvadeMode*. Your check would always tell the creature it can't evade.

The problem is debugging since it's hard to trigger the "stuck in evade" problem.

**Comment by Treeston** [comment] 2016-07-30 21:05
EnterEvadeMode gets overridden a lot. The idea is that the overriding method can then call _EnterEvadeMode to get basic functionality without needing to replicate code.

**Comment by Killyana** [comment] 2016-07-30 21:06
I didn't see this bug since months.

**Comment by MrSmite** [comment] 2016-07-30 21:19
> EnterEvadeMode gets overridden a lot. The idea is that the overriding method can then call _EnterEvadeMode to get basic functionality without needing to replicate code.

Ok, well in that case I think that check should at least be moved to the top.

**Comment by CrazyPeppers** [comment] 2016-10-31 16:35
If this thread is still referring to mobs getting stuck in this “passive player-following” evade state then I have experienced it with a recent build as well (I rebuilt the core when TDB 335.62 was released on 17Oct).  
The most reliable way I’ve seen to recreate it is with ranged combat from 2 sources, either 2 players or a player and pet.  It also seems to happen just as the mob is changing its target.  I haven’t been able to recreate this if combat is melee, it only happens when the mob is moving in to attack and taking damage from 2 different threats.
  
Method of recreation using a Warlock and imp:
1.	Set the imp firebolt to repeat attack
2.	Issue attack command for imp
3.	Use wand or Shadowbolt (or other spells that generates a lot of agro) once the mob targets the imp

I hope this info helps.

**Comment by Aokromes** [comment] 2016-11-27 06:05
This bug/fix is still valid after fe68b2e99851a888c5182d7bebddfea67459afd3 ?

**Comment by CrazyPeppers** [comment] 2016-11-28 01:37
I just updated my core and should have feedback to you in a day or two.

**Comment by Keader** [comment] 2016-11-28 01:49
not fixed by this commit.
fe68b2e99851a888c5182d7bebddfea67459afd3 not fixed any issues, is just codestyle/cleanup ^^

**Comment by CrazyPeppers** [comment] 2016-12-01 03:20
Confirmed.  This issue is still present as of cd687fb (Core/Scripts: Partial Revert in 87977b0 misunderstand concept).  
I was able to recreate using the method I noted above.

**Comment by dikkedeur** [comment] 2017-05-04 09:23
This bug is still present unfortunatly.
specially when you have a pet.

Make a warlock and let a pet have aggro, for example Goretusk
Mobs are evading my attacks but still can damage me.

**Comment by ibakula** [comment] 2017-05-04 09:55
@dikkedeur
Could you please describe the steps of reproduction more briefly?

**Comment by tkrokli** [comment] 2017-05-04 20:26
@ibakula : I think you would want more _detailed_ description, not a shorter description?

**Comment by dikkedeur** [comment] 2017-05-04 21:01
its hard to reproduce.. but this is what i got.

1. Make a Warlock, get a warlock pet
2. Attack a mob with your character and another guy, your friend for example
3. Let a pet take aggro, like a taunt for example
Attack a mob after your pet gets aggro and he will evade

sadly after a restart of the server it stopped and havent encountered it.. so it might be a lucky shot?

**Comment by ibakula** [comment] 2017-05-11 07:57
@tkrokli: In steps, briefly.
@dikkedeur: Thanks, I'm going to try compiling and seeing whether if it happens then too

**Comment by Regrad** [comment] 2017-05-27 09:22
Two range players shoot a neutral mob. First the mob runs to the first player, gets hit from the second, the second player comes out on top in agro and we have evade mob.

**Comment by Regrad** [comment] 2017-05-27 09:23
This method also works with the warlock's imp.

**Comment by Treeston** [comment] 2017-05-27 09:24
Hm, interesting. Let me see if that's a reliable repro, we've been lacking one of those.

**Comment by Treeston** [comment] 2017-05-27 09:43
I can't seem to reproduce on f2b0819e5368. Can you provide details of repro?

1. What mob are you using?
2. What attacks/spells cause it?
3. What's the timing of the attacks/spells?
4. Can you provide video (would greatly help in reconstructing)

**Comment by Regrad** [comment] 2017-05-27 10:31
https://youtu.be/ZlVAZok_Ws4
If you continue to shoot it leads to mob attack in evade mode.

**Comment by Regrad** [comment] 2017-05-27 10:33
https://youtu.be/8T45UZb_yyE
Here it is.

**Comment by Treeston** [comment] 2017-05-27 11:00
Interesting, thanks a lot.

**Comment by Treeston** [comment] 2017-05-27 17:04
Alright, looking into it now. This is reliable repro - trying to find cause.

**Comment by ariel-** [comment] 2017-05-27 17:22
Maybe related to #19768?

**Comment by Treeston** [comment] 2017-05-27 17:27
Yes, that's definitely the root cause of this particular bug. However, this also allows us to reproduce the "general" follow-while-evading bug, which might be helpful.

**Closed** 2017-05-28 20:18 UTC
Labels: Priority-High, Sub-Miscellaneous

**Comment by MrSmite** [comment] 2017-05-29 18:58
Nice work!
