### ISSUE TITLE
SendQuestGiverQuestDetails no work

### ISSUE THREAD

**Issue by dio85** [TrinityCore/TrinityCore#27837] opened 2022-02-28 16:54 UTC
### Description

 SendQuestGiverQuestDetails(quest, _player->GetGUID(), false, true); here the _player->GetGUID() send unknown value
so in this packet cannot read the value
[https://cdn.discordapp.com/attachments/883018217914789928/947440276778147880/unknown.png](url)

I tried to add to PlayerChoiceResponse at QuestHandler after Rewards.

### Expected behaviour

 _player->GetGUID() send unknown value so in this packet cannot read the value.

### Steps to reproduce the problem

Add to HandlePlayerChoiceResponse these lines:
[https://pastebin.com/XKScD72P](url)
after  if (playerChoiceResponse->Reward)

### Branch

master

### TC rev. hash/commit

latest/i modified with this my, so different .

### Operating system

Win 10 x64 

### Custom changes

[https://pastebin.com/XKScD72P](url)

**Comment by Aokromes** [comment] 2022-03-20 13:58
no hash after 20d, closing.

**Closed by Aokromes** 2022-03-20 13:58 UTC
Labels: Branch-master, Invalid-IncompleteData/OrNotTrinityCore

**Comment by dio85** [comment] 2022-03-20 15:36
TC rev. hash/commit
latest/i modified with this my, so different . So, if i write the fuckin hash, you can handle it? No. i write what is the problem. Read first.

**Comment by MaxtorCoder** [comment] 2022-03-20 17:07
So rude. Reproduce on clean TC and then give hash. If it doesn't happen on clean TC it's a you problem. 😄

**Comment by dio85** [comment] 2022-03-21 14:32
the not clean if you upload this, so... use your brain pls.

**Comment by MaxtorCoder** [comment] 2022-03-21 14:35
> the not clean if you upload this, so... use your brain pls.

We CANNOT help you on this issue if you don't reproduce on a clean TrinityCore source, because it might just be entirely possible that this is an issue on your side since we have NO IDEA of knowing what you altered to your code base.

This is also the reason why you are REQUIRED to provide a commit hash.

**Comment by dio85** [comment] 2022-03-21 15:09
but if you add this, the tc not clean, and the hash changed omfg  :D

**Comment by dio85** [comment] 2022-03-21 15:20
Nothing crash, just the fuckin QuestGiverDetails no work. the quest window popup, and show the quest, just if you click the accept, no work.  Read the fuckin issue.

**Comment by MaxtorCoder** [comment] 2022-03-21 15:22
What part of "It's an issue on your side" don't you understand, you added custom changes which resulted in this issue to appear. Sounds to me like you have no idea what this Github is for, this Github is for reporting issues for TrinityCore, not some custom core that you work on.

**Comment by dio85** [comment] 2022-03-21 15:28
:D So. if anyone download the core... and not make anything on it, that leacher or anything. If yes, nothing help. But waithing for PR's. fuck logic. How to make PR, if what i want use, no work on that handler. just the fuckin playerguid on questdetails send UNKNOWN Data, in that handler. and that handler tc. without or with my changes.
