### ISSUE TITLE
Gnomer-gooooone! quest teleport is not working

### ISSUE THREAD

**Issue by KarMaSSo** [TrinityCore/TrinityCore#26072] opened 2021-02-10 21:24 UTC
**Description:**

In Booty Bay. After completing quest Gnomer-gooooone! from Scooty, I have quest item - Goblin Transporder, but after I step on the pad I'm not teleported to Gnomeregan.

**Expected behaviour:**

Scooty's teleport should transport me to Gnomeragan.

**Steps to reproduce the problem:**

1. Talk to Nogg next to Sovik and accept Rig Wars quest in Orgrimmar.
2. Travel to Booty Bay and talk to Scooty, accept quest Gnomer-gooooone!
3. You should have quest item - Goblin Transporder in Your backpack and after You step on Scooty's teleport You should be transported to Gnomeregan.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

N/A

**Operating system:** 

Windows 10 Home

**Comment by offl** [comment] 2021-02-10 21:32
Duplicate of #18871

**Closed by offl** 2021-02-10 21:32 UTC
Labels: Branch-3.3.5a, Invalid-IncompleteData/OrNotTrinityCore
