### ISSUE TITLE
End of The Light of Dawn Quest Broken

### ISSUE THREAD

**Issue by sawd20** [TrinityCore/TrinityCore#25658] opened 2020-11-18 10:15 UTC
**Quest : The Light of Dawn: the last quest of DK lvling Story line that give dk the portal **

the Quest wont complete cuze of the Highlord Darion donsnt evade the Fight and stay at one place Also minions leave during fight and retrun 

**Expected behaviour:**
 highlord Darion  and his army should captured by Tirion to complete the Quest

**Steps to reproduce the problem:**
1. speak to Highlord Darion Morgraine / npc=29173 / https://www.wowhead.com/npc=29173/highlord-darion-mograine.  
2. move to the church with army of dead
3. fight till Highlord Tirion Capture Morgraine 

**Branch(es):**

3.3.5

**Operating system:** Win OS

![WoWScrnShot_111620_115310](https://user-images.githubusercontent.com/55743285/99517040-c59ed300-2943-11eb-98c4-f0f2eb8a577a.jpg)
![WoWScrnShot_111620_123354](https://user-images.githubusercontent.com/55743285/99517052-c899c380-2943-11eb-8cb0-18c995858f74.jpg)

**Comment by offl** [comment] 2021-10-02 21:36
Duplicate of #26135

**Closed by offl** 2021-10-02 21:36 UTC
Labels: Branch-3.3.5a, Invalid-IncompleteData/OrNotTrinityCore
