### ISSUE TITLE
[6.x/7.x] Scenario System (50$ bounty)

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#17905] opened 2016-09-05 22:11 UTC
**Description**:
Read this: http://wow.gamepedia.com/Scenario

> From Warlords of Draenor onwards, there are no new endgame scenarios, and thus, no scenario rewards. Instead, some quests use scenario mechanics, which are seamlessly integrated into the main world using phasing, rather than being their own instances.

Scenarios are like additional Quests without typical Questgiver Questender Mechanics.
It's to provide content for players. Scenarios are most time used in OpenWorld as some story content.
In Dungeons it shall guide through the dungeon and reward people if completing it.

**Current behaviour**: No Implementation 

**Expected behaviour**: 
- Dungeon scenarios are stored inside DB2 file
- World must be stored inside WorldDB or HotfixesDB or it's via AchievementCriteria.
- State of scenario must be saved and loaded
- Packets must be updated and researched (Unk Bits)
- Entering a WorldScenario with POI must be displayed on Map
- Achievements related to Scenario must be granted
- Bonus Objectives must be loaded and rewarded

Is there a scaling with itemlevel?
for example the artifact scenarios.

**Branch(es)**: 6.x

**TDB version**:  6.04

**Operating system**:  Win 10

**Bountysource**
https://www.bountysource.com/issues/37599527-6-x-7-x-scenario-system

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=37599527)](https://www.bountysource.com/issues/37599527-6-x-7-x-scenario-system-50-bounty?utm_source=37599527&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**forked Branches**
https://github.com/Krudor/TrinityCore/tree/scenarios_cleanup

**Comment by EragorDev** [comment] 2016-09-13 21:57
Yes, good ! It's very important on Legion !

**Comment by funjoker** [comment] 2016-09-27 15:42
@Krudor 
Have fun ^^

**Comment by tkrokli** [comment] 2016-09-27 15:53
Duplicate of issue #17858 - bounty rewarded.

**Comment by tkrokli** [comment] 2016-09-27 15:55
Sorry, mistaken issue. My bad.

**Comment by tkrokli** [comment] 2016-11-06 23:34
Reopening the issue do activate BountySource again (the bounty got killed).

**Comment by tkrokli** [comment] 2016-11-06 23:51
Bounty issue fixed and bounty tagged/paid. Closing.

**Closed by tkrokli** 2016-11-06 23:51 UTC
Labels: bounty, Branch-master

**Comment by funjoker** [comment] 2016-11-07 00:21
Well Bountysource is quiet slow.
