### ISSUE TITLE
[3.3.5] Cubes anywhere

### ISSUE THREAD

**Issue by ShinDarth** [TrinityCore/TrinityCore#15895] opened 2015-11-24 23:36 UTC
Rev: https://github.com/TrinityCore/TrinityCore/commit/302623a1516e487ad64f2028aec287b99372e33a

After character's death, a strange cube appears. Sometimes it vanishes when you resurrect, sometimes it doesn't.

![](http://s23.postimg.org/xfaey2223/Screenshot_from_2015_11_25_00_32_53.png)

**Comment by Kinzcool** [comment] 2015-11-24 23:40
That cube is the default model when there's an invalid ID/model path.

**Comment by tkrokli** [comment] 2015-11-25 02:07
Last time that happened to me, it was because of bad files in my 3.3.5a game client. If game objects were represented by a cube permanently on your screen, it would clearly be a game client issue.

**Comment by Keader** [comment] 2015-11-26 22:13
In Ulduar, usually happens constantly.
This began to happen makes about 1 month or a little more.

**Comment by Trisjdc** [comment] 2015-11-27 11:36
This is caused by https://github.com/TrinityCore/TrinityCore/commit/3c82b498cc694d9ed04e29079a4c61d68dc7741e

Poor thinking of changing the expected result of Unit::getGender for players when there are so many odd places where it is used, including corpse creation. I think the cubes are exactly because of the corpses with invalid info for the set gender.

**Comment by Shauren** [comment] 2015-11-27 13:18
Corpse? Will have this fixed then.

**Comment by Trisjdc** [comment] 2015-11-27 13:26
This is just a symptom of a larger though, which is a lot of code that assumes Unit::getGender for players to be the actual gender of the player, rather than the current display. Better not close this issue until the underlying problem is fixed.

But yeah, this particular problem is fixed by just changing this: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.cpp#L4791

**Closed** 2015-11-27 17:30 UTC
