### ISSUE TITLE
[CRASH] in spell_malygos_vortex_visual

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#21360] opened 2018-02-04 23:26 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
in spell_malygos_vortex_visual::spell_malygos_vortex_visual_AuraScript::OnRemove (this=<optimized out>) at /Sources/src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp:1828

**Current behaviour**: 

- https://pastebin.com/3UTeYsx4
- https://pastebin.com/BfgzGjdv

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
Dont know

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
8f71307e5619c8ef1801488812e20d07714fd733

**TDB version**:  
335.63

**Operating system**:  
Linux x64, Static

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment] 2018-02-04 23:32
Duplicate of #21315

**Comment by tkrokli** [comment] 2018-02-04 23:32
Looks identical to the crash reported in
**Scripts/Eye Of Eternity: Malygos - Vortex Visual crash** #21315

**Closed** 2018-02-04 23:32 UTC
