### ISSUE TITLE
[3.3.5a] Patrollers near Omorok the Tree Shaper (Nexus)

### ISSUE THREAD

**Issue by wotlk-enthusiast** [TrinityCore/TrinityCore#24359] opened 2020-03-28 18:31 UTC
**Description:**
In The Nexus, the patrollers near Omorok the Tree Shaper do not patrol, forcing the player group to fight them at the same time as Omorok himself.

**Current behaviour:**
The patrol group moves around in their own little corner.

**Expected behaviour:**
The patrol group should walk around Omorok, and down the ramp, allowing players to engage and kill them without killing Omorok first.

**Steps to reproduce the problem:**

1. Make GM toon
2. Go to Omorok the Tree Shaper
3. Watch the patrolling group from the ramp (Crystalline Protector and friends)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. b166d12cbef0 2020-03-21 21:14:49 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Online players: 0 (max: 6)
Active connections: 0 (max: 6) Queued connections: 0 (max: 0)
Server uptime: 1 Day 10 Hours 22 Minutes 59 Seconds.
Update time diff: 50.

**Operating system:** Linux

**Comment by Rushor** [comment] 2020-03-29 18:33
by sunwell

```sql
UPDATE `creature` SET `wander_distance`=0, `movementType`=2 WHERE guid=126445;
DELETE FROM `creature_addon` WHERE `guid` = 126445;
INSERT INTO `creature_addon` VALUES (126445, 1264450, 0, 0, 4097, 0, 0, '');
DELETE FROM `waypoint_data` WHERE id=1264450;
INSERT INTO `waypoint_data` VALUES (1264450, 1, 258.853, -240.519, -9.10091, 0, 0, 0, 0, 100, 0),(1264450, 2, 266.729, -242.493, -8.32708, 0, 0, 0, 0, 100, 0),(1264450, 3, 275.521, -239.43, -8.25407, 0, 0, 0, 0, 100, 0),(1264450, 4, 281.801, -232.557, -8.25407, 0, 0, 0, 0, 100, 0),(1264450, 5, 287.606, -233.488, -8.484, 0, 0, 0, 0, 100, 0),(1264450, 6, 296.215, -237.034, -11.5626, 0, 0, 0, 0, 100, 0),(1264450, 7, 303.604, -240.565, -14.0888, 0, 0, 0, 0, 100, 0),(1264450, 8, 317.284, -247.168, -14.0888, 0, 0, 0, 0, 100, 0),(1264450, 9, 321.445, -249.176, -14.0888, 0, 0, 0, 0, 100, 0),(1264450, 10, 314.126, -245.501, -14.0888, 0, 0, 0, 0, 100, 0),(1264450, 11, 306.529, -242.441, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450, 12, 302.244, -240.714, -13.7846, 0, 0, 0, 0, 100, 0),(1264450, 13, 292.602, -236.383, -10.4792, 0, 0, 0, 0, 100, 0),(1264450, 14, 288.324, -234.462, -8.82875, 0, 0, 0, 0, 100, 0),(1264450, 15, 282.729, -232.895, -8.25401, 0, 0, 0, 0, 100, 0),(1264450, 16, 277.275, -238.912, -8.25401, 0, 0, 0, 0, 100, 0),(1264450, 17, 268.603, -244.83, -8.25406, 0, 0, 0, 0, 100, 0),(1264450, 18, 258.127, -244.109, -8.25406, 0, 0, 0, 0, 100, 0),(1264450, 19, 253.805, -238.514, -8.49638, 0, 0, 0, 0, 100, 0),(1264450, 20, 247.398, -227.432, -8.49771, 0, 0, 0, 0, 100, 0);
DELETE FROM `creature_formations` WHERE memberGUID IN (126444, 126445, 126605, 126606);
INSERT INTO `creature_formations` VALUES (126445, 126445, 0, 0, 515, 0, 0);
INSERT INTO `creature_formations` VALUES (126445, 126444, 4, 0, 515, 0, 0);
INSERT INTO `creature_formations` VALUES (126445, 126606, 5.66, 45, 515, 0, 0);
INSERT INTO `creature_formations` VALUES (126445, 126605, 4, 90, 515, 0, 0);
```

**Comment by wotlk-enthusiast** [comment] 2020-03-29 22:27
This works.  Not sure how far they're supposed to pat from Retail, but they certainly come down the platform and allow us to grab them before the boss.

**Comment by wotlk-enthusiast** [comment] 2020-04-04 19:45
So......how do we attract the attention of a dev to integrate this into the code base?

**Comment by illfated** [comment] 2020-04-04 20:17
Needs updating to follow TC SQL code style (values listing & all field names for the inserts).

**Comment by illfated** [comment] 2020-04-04 20:28
Reformatted SQL (please check the content, I picked the field names from 1-2 year old issue tickets)

```sql
UPDATE `creature` SET `wander_distance` = 0, `movementType` = 2 WHERE `guid` = 126445;

DELETE FROM `creature_addon` WHERE `guid` = 126445;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES
(126445, 1264450, 0, 0, 4097, 0, 0, '');

DELETE FROM `waypoint_data` WHERE `id` = 1264450;
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_type`, `action`, `action_chance`, `wpguid`) VALUES
(1264450,  1, 258.853, -240.519, -9.10091, 0, 0, 0, 0, 100, 0),
(1264450,  2, 266.729, -242.493, -8.32708, 0, 0, 0, 0, 100, 0),
(1264450,  3, 275.521, -239.43,  -8.25407, 0, 0, 0, 0, 100, 0),
(1264450,  4, 281.801, -232.557, -8.25407, 0, 0, 0, 0, 100, 0),
(1264450,  5, 287.606, -233.488,  -8.484,  0, 0, 0, 0, 100, 0),
(1264450,  6, 296.215, -237.034, -11.5626, 0, 0, 0, 0, 100, 0),
(1264450,  7, 303.604, -240.565, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450,  8, 317.284, -247.168, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450,  9, 321.445, -249.176, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450, 10, 314.126, -245.501, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450, 11, 306.529, -242.441, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450, 12, 302.244, -240.714, -13.7846, 0, 0, 0, 0, 100, 0),
(1264450, 13, 292.602, -236.383, -10.4792, 0, 0, 0, 0, 100, 0),
(1264450, 14, 288.324, -234.462, -8.82875, 0, 0, 0, 0, 100, 0),
(1264450, 15, 282.729, -232.895, -8.25401, 0, 0, 0, 0, 100, 0),
(1264450, 16, 277.275, -238.912, -8.25401, 0, 0, 0, 0, 100, 0),
(1264450, 17, 268.603, -244.83,  -8.25406, 0, 0, 0, 0, 100, 0),
(1264450, 18, 258.127, -244.109, -8.25406, 0, 0, 0, 0, 100, 0),
(1264450, 19, 253.805, -238.514, -8.49638, 0, 0, 0, 0, 100, 0),
(1264450, 20, 247.398, -227.432, -8.49771, 0, 0, 0, 0, 100, 0);

DELETE FROM `creature_formations` WHERE `memberGUID` IN (126444, 126445, 126605, 126606);
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES
(126445, 126444, 4,     0, 515, 0, 0),
(126445, 126445, 0,     0, 515, 0, 0),
(126445, 126605, 4,    90, 515, 0, 0),
(126445, 126606, 5.66, 45, 515, 0, 0);
```

**Comment by illfated** [comment] 2020-04-04 20:33
This way it is easier to read the content and maybe catch any typos or incorrect values.

**Comment by wotlk-enthusiast** [comment] 2020-04-17 19:35
The only thing I changed was added the missing field visibilityDistanceType in creature_addon.

Now what? Do we @mention a dev? Close the ticket?  

Sorry for the n00b questions, I want to get the right habits for when I keep doing this.

```sql
UPDATE `creature` SET `wander_distance` = 0, `movementType` = 2 WHERE `guid` = 126445;

DELETE FROM `creature_addon` WHERE `guid` = 126445;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`, `visibilityDistanceType`, `auras`) VALUES
(126445, 1264450, 0, 0, 4097, 0, 0, 0, '');

DELETE FROM `waypoint_data` WHERE `id` = 1264450;
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_type`, `action`, `action_chance`, `wpguid`) VALUES
(1264450,  1, 258.853, -240.519, -9.10091, 0, 0, 0, 0, 100, 0),
(1264450,  2, 266.729, -242.493, -8.32708, 0, 0, 0, 0, 100, 0),
(1264450,  3, 275.521, -239.43,  -8.25407, 0, 0, 0, 0, 100, 0),
(1264450,  4, 281.801, -232.557, -8.25407, 0, 0, 0, 0, 100, 0),
(1264450,  5, 287.606, -233.488, -8.484,   0, 0, 0, 0, 100, 0),
(1264450,  6, 296.215, -237.034, -11.5626, 0, 0, 0, 0, 100, 0),
(1264450,  7, 303.604, -240.565, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450,  8, 317.284, -247.168, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450,  9, 321.445, -249.176, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450, 10, 314.126, -245.501, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450, 11, 306.529, -242.441, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450, 12, 302.244, -240.714, -13.7846, 0, 0, 0, 0, 100, 0),
(1264450, 13, 292.602, -236.383, -10.4792, 0, 0, 0, 0, 100, 0),
(1264450, 14, 288.324, -234.462, -8.82875, 0, 0, 0, 0, 100, 0),
(1264450, 15, 282.729, -232.895, -8.25401, 0, 0, 0, 0, 100, 0),
(1264450, 16, 277.275, -238.912, -8.25401, 0, 0, 0, 0, 100, 0),
(1264450, 17, 268.603, -244.83,  -8.25406, 0, 0, 0, 0, 100, 0),
(1264450, 18, 258.127, -244.109, -8.25406, 0, 0, 0, 0, 100, 0),
(1264450, 19, 253.805, -238.514, -8.49638, 0, 0, 0, 0, 100, 0),
(1264450, 20, 247.398, -227.432, -8.49771, 0, 0, 0, 0, 100, 0);

DELETE FROM `creature_formations` WHERE `memberGUID` IN (126444, 126445, 126605, 126606);
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES
(126445, 126444, 4, 0, 515, 0, 0),
(126445, 126445, 0, 0, 515, 0, 0),
(126445, 126605, 4, 90, 515, 0, 0),
(126445, 126606, 5.66, 45, 515, 0, 0);
```

**Comment by illfated** [comment] 2020-04-17 20:50
Thank you for adding the missing column. I have been busy elsewhere and with my job.
Let me see: Have you tested if that SQL content works as intended and expected, that it solves the issue and does not look hacky in any way?

**Comment by illfated** [comment] 2020-04-17 20:54
If you can test the SQL changes on your own 3.3.5 build and see that it works without bugs, post a comment about it. Confirming if it works or not is essential here.
When confirmed to be working, the TC devs (usually Killyana or dr-j ) will check it as a suggested solution, before making a closing commit to the db files in the source.

**Comment by wotlk-enthusiast** [comment] 2020-04-19 19:00
Confirmed that it works on build cfd63c350f5b, functions as intended, though as I said earlier I'm not sure how far the group is supposed to pat in retail but they certainly come down the ramp and allow us to engage them before the boss instead of with the boss as it was before.  It does not look hacky in any way to me, looks more like we're adding missing data to the database.

**Closed** 2020-04-19 19:34 UTC
Labels: Comp-Database, Sub-Waypoints

**Comment by illfated** [comment] 2020-04-19 19:51
@wotlk-enthusiast : Mismatch between number of named columns (8) and number of values (9) in your SQL (sorry for not having a local setup to test this on my side).

**Comment by wotlk-enthusiast** [comment] 2020-04-19 20:10
What the hell, I pasted this perfectly and it ran, but now that I re-pasted it, I got the same error.  

Fixed SQL here:

```sql
UPDATE `creature` SET `wander_distance` = 0, `movementType` = 2 WHERE `guid` = 126445;

DELETE FROM `creature_addon` WHERE `guid` = 126445;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`, `visibilityDistanceType`, `auras`) VALUES
(126445, 1264450, 0, 0, 4097, 0, 0, '');

DELETE FROM `waypoint_data` WHERE `id` = 1264450;
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_type`, `action`, `action_chance`, `wpguid`) VALUES
(1264450,  1, 258.853, -240.519, -9.10091, 0, 0, 0, 0, 100, 0),
(1264450,  2, 266.729, -242.493, -8.32708, 0, 0, 0, 0, 100, 0),
(1264450,  3, 275.521, -239.43,  -8.25407, 0, 0, 0, 0, 100, 0),
(1264450,  4, 281.801, -232.557, -8.25407, 0, 0, 0, 0, 100, 0),
(1264450,  5, 287.606, -233.488, -8.484,   0, 0, 0, 0, 100, 0),
(1264450,  6, 296.215, -237.034, -11.5626, 0, 0, 0, 0, 100, 0),
(1264450,  7, 303.604, -240.565, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450,  8, 317.284, -247.168, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450,  9, 321.445, -249.176, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450, 10, 314.126, -245.501, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450, 11, 306.529, -242.441, -14.0888, 0, 0, 0, 0, 100, 0),
(1264450, 12, 302.244, -240.714, -13.7846, 0, 0, 0, 0, 100, 0),
(1264450, 13, 292.602, -236.383, -10.4792, 0, 0, 0, 0, 100, 0),
(1264450, 14, 288.324, -234.462, -8.82875, 0, 0, 0, 0, 100, 0),
(1264450, 15, 282.729, -232.895, -8.25401, 0, 0, 0, 0, 100, 0),
(1264450, 16, 277.275, -238.912, -8.25401, 0, 0, 0, 0, 100, 0),
(1264450, 17, 268.603, -244.83,  -8.25406, 0, 0, 0, 0, 100, 0),
(1264450, 18, 258.127, -244.109, -8.25406, 0, 0, 0, 0, 100, 0),
(1264450, 19, 253.805, -238.514, -8.49638, 0, 0, 0, 0, 100, 0),
(1264450, 20, 247.398, -227.432, -8.49771, 0, 0, 0, 0, 100, 0);

DELETE FROM `creature_formations` WHERE `memberGUID` IN (126444, 126445, 126605, 126606);
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES
(126445, 126444, 4, 0, 515, 0, 0),
(126445, 126445, 0, 0, 515, 0, 0),
(126445, 126605, 4, 90, 515, 0, 0),
(126445, 126606, 5.66, 45, 515, 0, 0);
```

This time I tried extra hard to make sure it was right. Copy pasted, rolled back, copy pasted again, worked both times.  Sorry! Ugh maybe I'm not cut out for this, haha

**Comment by illfated** [comment] 2020-04-19 20:11
OK, fair enough. I think it was only about these lines:
```sql
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`, `visibilityDistanceType`, `auras`) VALUES
(126445, 1264450, 0, 0, 4097, 0, 0, 0, '');
```

**Comment by illfated** [comment] 2020-04-19 20:14
BTW, everyone can make mistakes. I certainly do so, more often than I want to remember. (During my last Windows IT-Pro PR, I overlooked 2 errors I intended to correct, but forgot it because I tried to be quick & efficient). The important part is to keep track and make corrections as soon as possible.

**Comment by wotlk-enthusiast** [comment] 2020-04-19 20:14
4097 should be bytes2, extra zero got added between bytes2 and auras.  

I know exactly why too, a line break in my text editor put that sql on multiple lines, so when I edited it manually I thought I deleted a zero and put it back. 

I put the correct code above, and also as a comment in your commit comment.

**Comment by illfated** [comment] 2020-04-19 20:20
Thanks. I have not yet managed to rebuild my local setup, hence my reduced ability to contribute.
