### ISSUE TITLE
[3.3.5] Exploding sheep (engineering) does not explode.

### ISSUE THREAD

**Issue by Wombyte2** [TrinityCore/TrinityCore#25601] opened 2020-10-23 13:15 UTC
**Description:**

The "Exploding Sheep" (crafted by engineer's) does not explode.
It just follows the nearest enemy and does nothing at all. 

**Expected behaviour:**

It should explode if it gets near an enemy. 

**Steps to reproduce the problem:**

1. Craft one exploding sheep. 
2. Go to an enemy and spawn your exploding sheep.
3. The sheep will walk towards the enemy, but nothing will happen.

**Branch(es):**

3.3.5 October 2020 release

**Comment by offl** [comment] 2020-10-23 13:54
Duplicate of #21753

**Closed by offl** 2020-10-23 13:54 UTC
Labels: Branch-3.3.5a, Invalid-IncompleteData/OrNotTrinityCore
