### ISSUE TITLE
{Spell/hunter}Hunter trap vs invisibility creatures

### ISSUE THREAD

**Issue by TheAvichay** [TrinityCore/TrinityCore#10179] opened 2013-07-02 08:01 UTC
Hello every one.
I have noticed that when Hunter place his trap and an invisibility creature stepping on it the trap disappear.
U can see that when a Hunter fighting a Rouge/Druid, while the Rouge/Druid is still in invisibility the trap will just disappear instid of discovering the Rouge/Druid.

Snake Trap : http://www.wowhead.com/spell=34600/snake-trap - ID 34600
Freezing Trap : http://www.wowhead.com/spell=60192/freezing-trap ID : 60192
Frost Trap : http://www.wowhead.com/spell=80018/frost-trap - ID : 80018
Explosive Trap : http://www.wowhead.com/spell=13813/explosive-trap - ID : 13813
Those are the traps that disappear when an invisibility creature stepping on it.

TBD: 335.51
Hash: d967162
Linux,SQL.
Thx for help,
Avichay.
##

**Comment by tkrokli** [comment] 2015-05-07 00:14
@TheAvichay, @Natureknight : are you still available to confirm if this issue still exists in current source?

**Comment by Rushor** [comment] 2015-06-24 11:57
how to reproduce:

1) Hunter: place trap in front of you
2) Hunter: move out of range and leave the playe of the trap (move ~10 yards)
3) Rouge: moves towards the trap
> trap will be removed

If the hunter stays in front of the trap, the stealthed rougue will be cauaght in the trap

**Comment by Rushor** [comment] 2015-06-24 12:12
and a video to clarify it: https://youtu.be/LsKfiu-CS6g

**Comment by robinsch** [comment] 2015-06-24 14:08
@Rushor Check where AnyUnfriendlyNoTotemUnitInObjectRangeCheck operator returns false

**Comment by Rushor** [comment] 2015-06-24 14:33
hm kay it returns for:
- units which are not alive
- for creatures which are CREATURE_TYPE_NON_COMBAT_PET
- for totems
- for nonattackable targets

so maybe isTargetableForAttack must be modified in this check

**Comment by robinsch** [comment] 2015-06-24 14:50
I know this by reading the code, what I don't know is if some of them return false if unit is not visibil to caster.

**Comment by Rushor** [comment] 2015-06-24 14:54
corrious note: if we test this with creatures evrything works fine
- setup trap
- pull creature
- add stealth for creature
- creature runs over stealth

=> creature will be caught in the trap

**Comment by tkrokli** [comment] 2015-06-24 15:54
TrinityCore rev. 0cba5558cf11 2015-06-24 11:05:36 +0200 (3.3.5 branch) (Win64, Release)
Confirmed. If I run Rushor's scenario from the video, entering a duel with a hunter and a rogue, placing the trap will freeze the rogue if the hunter does not move. If the hunter moves 10 m away (or more), the trap will disappear when the rogue steps on the trap. Also, if the rogue is already frozen, the trap will break if the hunter moves away the suggested distance from the ice block.

Hunter (Admiral Akbar style) : "It's a trap!"
Rogue (Matrix style) : "There is no trap..."

**Comment by robinsch** [comment] 2015-07-05 16:35
Fails because of SpellCastResult SpellInfo::CheckTarget(Unit const* caster, WorldObject const* target, bool implicit) const - if (!HasAttribute(SPELL_ATTR6_CAN_TARGET_INVISIBLE) && !caster->CanSeeOrDetect(target, implicit))

**Comment by robinsch** [comment] 2015-07-05 19:06
Currently I can't think of a proper way to implement it then adding SPELL_ATTR6_CAN_TARGET_INVISIBLE to trap effect spells.

**Comment by robinsch** [comment] 2015-07-06 14:08
```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 17915e5..a0549e8 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -11886,7 +11889,7 @@ bool Unit::_IsValidAttackTarget(Unit const* target, SpellInfo const* bySpell, Wo
             return false;
 
     // can't attack invisible (ignore stealth for aoe spells) also if the area being looked at is from a spell use the dynamic object created instead of the casting unit.
-    if ((!bySpell || !bySpell->HasAttribute(SPELL_ATTR6_CAN_TARGET_INVISIBLE)) && (obj ? !obj->CanSeeOrDetect(target, bySpell && bySpell->IsAffectingArea()) : !CanSeeOrDetect(target, bySpell && bySpell->IsAffectingArea())))
+    if ((!bySpell || !bySpell->HasAttribute(SPELL_ATTR6_CAN_TARGET_INVISIBLE)) && (obj ? !obj->CanSeeOrDetect(target, bySpell && bySpell->IsAffectingArea()) : !CanSeeOrDetect(target, bySpell && bySpell->IsAffectingArea())) && !bySpell->IsTrapSpellEffect())
         return false;
 
     // can't attack dead

diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 30c02db..dfc11e7 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -1967,11 +1967,7 @@ void Spell::prepareDataForTriggerSystem(AuraEffect const* /*triggeredByAura*/)
     m_procEx = PROC_EX_NONE;
 
     // Hunter trap spells - activation proc for Lock and Load, Entrapment and Misdirection
-    if (m_spellInfo->SpellFamilyName == SPELLFAMILY_HUNTER &&
-        (m_spellInfo->SpellFamilyFlags[0] & 0x18 ||     // Freezing and Frost Trap, Freezing Arrow
-        m_spellInfo->Id == 57879 ||                     // Snake Trap - done this way to avoid double proc
-        m_spellInfo->SpellFamilyFlags[2] & 0x00024000)) // Explosive and Immolation Trap
-
+    if (m_spellInfo->IsTrapSpellEffect())
         m_procAttacker |= PROC_FLAG_DONE_TRAP_ACTIVATION;
 
     /* Effects which are result of aura proc from triggered spell cannot proc

diff --git a/src/server/game/Spells/SpellInfo.cpp b/src/server/game/Spells/SpellInfo.cpp
index ea5e4c8..6426bfc 100644
--- a/src/server/game/Spells/SpellInfo.cpp
+++ b/src/server/game/Spells/SpellInfo.cpp
@@ -1301,6 +1301,17 @@ bool SpellInfo::IsAuraExclusiveBySpecificPerCasterWith(SpellInfo const* spellInf
     }
 }
 
+bool SpellInfo::IsTrapSpellEffect() const
+{
+    if (SpellFamilyName == SPELLFAMILY_HUNTER &&
+        (SpellFamilyFlags[0] & 0x18 ||     // Freezing and Frost Trap, Freezing Arrow
+        Id == 57879 ||                     // Snake Trap - done this way to avoid double proc
+        SpellFamilyFlags[2] & 0x00024000)) // Explosive and Immolation Trap
+        return true;
+
+    return false;
+}
+
 SpellCastResult SpellInfo::CheckShapeshift(uint32 form) const
 {
     // talents that learn spells can have stance requirements that need ignore
@@ -1502,7 +1513,7 @@ SpellCastResult SpellInfo::CheckTarget(Unit const* caster, WorldObject const* ta
         return SPELL_FAILED_BAD_TARGETS;
 
     // check visibility - ignore stealth for implicit (area) targets
-    if (!HasAttribute(SPELL_ATTR6_CAN_TARGET_INVISIBLE) && !caster->CanSeeOrDetect(target, implicit))
+    if (!HasAttribute(SPELL_ATTR6_CAN_TARGET_INVISIBLE) && !caster->CanSeeOrDetect(target, implicit) && !IsTrapSpellEffect())
         return SPELL_FAILED_BAD_TARGETS;
 
     Unit const* unitTarget = target->ToUnit();

diff --git a/src/server/game/Spells/SpellInfo.h b/src/server/game/Spells/SpellInfo.h
index cfa9877..bc73b66 100644
--- a/src/server/game/Spells/SpellInfo.h
+++ b/src/server/game/Spells/SpellInfo.h
@@ -430,6 +430,7 @@ public:
     bool IsSingleTarget() const;
     bool IsAuraExclusiveBySpecificWith(SpellInfo const* spellInfo) const;
     bool IsAuraExclusiveBySpecificPerCasterWith(SpellInfo const* spellInfo) const;
+    bool IsTrapSpellEffect() const;
 
     SpellCastResult CheckShapeshift(uint32 form) const;
     SpellCastResult CheckLocation(uint32 map_id, uint32 zone_id, uint32 area_id, Player const* player = NULL) const;
```

**Comment by Rushor** [comment] 2015-07-06 14:14
i love you (#nohomo) :D

**Comment by Killyana** [comment] 2015-07-06 14:57
Excellent, open a PR.

**Comment by P-Kito** [comment] 2015-07-07 03:17
Who is this robinsch and why is he so smart.

**Comment by tkrokli** [comment] 2015-07-07 07:15
Well, he has been dealing with code for at least 4 years now on the TC Forum , if not longer.

**Comment by robinsch** [comment] 2015-07-07 08:12
Well actually I've been working almost 6 years with TC but only on 2.4.3 branch, after 6 years of development there is not much left to do and that's why I started to contribute to TC 3.3.5.

**Comment by MrSmite** [comment] 2015-07-08 05:13
I still think this is a *resist* which is also a broken feature by Blizzard...

> http://us.battle.net/wow/en/forum/topic/2267599521#1
> Q: Why do hunter traps continue to be resisted when the hunter is both spell pen capped, and specced 2/2 into Survival Tactics?
>
> A: It’s just a technical limitation. The way the code works, the traps are objects and not part of the player. We can calculate how much damage they should do based on player stats, but it is currently impossible for them to inherit things like spell pen. 
>
> It is absolutely a problem though and we do want to fix it.

**Comment by robinsch** [comment] 2015-07-08 06:51
You are wrong.

**Comment by Raydor** [comment] 2015-07-08 18:58
@robinsch http://pastebin.com/SZJT8wvU

**Comment by robinsch** [comment] 2015-07-08 19:01
obj == NULL;

**Comment by robinsch** [comment] 2015-07-08 19:03
nullptr, add a bySpell to the last check.

**Comment by Raydor** [comment] 2015-07-21 18:38
@robinsch The code makes a bug where pets can chase a rogue that go in stealth.

**Comment by robinsch** [comment] 2015-07-21 21:54
Pet's should be able to chase Rogue's that go in Stealth. Only Vanish should break chasing.

**Comment by Raydor** [comment] 2015-07-22 09:16
It makes at least the pet from the priest (shadowfiend) keep chasing the rogue when he vanishes and it breaks the vanish.

**Comment by lineagedr** [comment] 2015-08-14 07:05
Works with @robinsch fix. But snake trap does not get detected everything else does.

**Comment by Rushor** [comment] 2015-08-22 12:15
Edit: also noticed that neither of the traps remove stealth. Rogue stays frozen in stealth lol

source that they should remove it? moreover this is an other issue and can be ignored in this issue

**Comment by robinsch** [comment] 2015-08-22 14:27
Stealth should always be removed by any harmful spell. https://github.com/TrinityCore/TrinityCore/pull/14824

**Comment by lineagedr** [comment] 2015-08-22 17:48
@robinsch Thank you.

**Comment by Rushor** [comment] 2015-08-29 10:23
@robinsch @Raydor 
in order to carify the issue with the chasing pets:

```c++
// can't attack invisible (ignore stealth for aoe spells) also if the area being looked at is from a spell use the dynamic object created instead of the casting unit.
    if ((!bySpell || !(bySpell->AttributesEx6 & SPELL_ATTR6_CAN_TARGET_INVISIBLE)) && (obj ? !obj->CanSeeOrDetect(target, bySpell && bySpell->IsAffectingArea()) : !CanSeeOrDetect(target, bySpell && bySpell->IsAffectingArea())) && (bySpell && !bySpell->IsTrapSpellEffect()))
```

problem:
dk summons ghoul
rogue casts dot on dk (rogue is infight with dk now)
ghoul attacks rogue
rogue casts vanish > ghoul still follows rogue and meleehits him

as long as the rogue in infight with the dk (and the dot is ticking on the dk) the ghoul will detect the rogue and follow him.

that's a big problem with this patch ^^

**Comment by MrSmite** [comment] 2015-08-30 00:32
This is technically [blizz-like](http://us.battle.net/wow/en/forum/topic/2046965130)

In the past when someone posted a bug here that was identified as never fixed on retail, the bug was left in Trinity too. IMO this bug is annoying though and it wouldn't hurt to fix it ;)

**Comment by Raydor** [comment] 2015-08-30 09:38
@MrSmite this patch doesn't affect hunter pets, only DK ghoul and priest shadowfiend are the ones that still chasing the rogue when he vanishes, hunter pets stop chasing him.

**Comment by Rushor** [comment] 2015-08-30 09:56
maybe because the showfiend and the ghoul have an overritten UpdateAI and hunterpets only have the normal PetAI?

**Comment by MrSmite** [comment] 2015-08-31 02:28
@Raydor Right but according to the GM response I quoted, Hunter pets are *supposed to* keep chasing so technically Trinity isn't Blizz-like in that fashion. I don't necessarily think it's worth changing this feature of Hunter pets in Trinity though.

**Comment by Aokromes** [comment] 2016-05-26 01:54
If the fix here is valid, plz open a PR.

**Comment by mik1893** [comment] 2016-06-07 08:03
adding Death and Decay to the list of spells in the check function also fixes #16154

**Comment by Persephone** [comment] 2016-10-12 21:46
Any news on this? Would be legit to have this fix, such an unfair advantage rogues have atm

**Comment by Persephone** [comment] 2016-10-28 09:47
@ariel-  Would you know how to fix this? Really such an annoying issue atm

**Closed** 2016-10-30 03:17 UTC
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Spells
