### ISSUE TITLE
GAMEOBJECT_TYPE_GOOBER doesn't cast any spells

### ISSUE THREAD

**Issue by giridhar123** [TrinityCore/TrinityCore#18752] opened 2017-01-06 20:37 UTC
**Description:** Every gameobject with type 10 (GAMEOBJECT_TYPE_GOOBER) with spell id in data10 field should cast a spell when you click on it.

**Current behaviour:** The spell isn't casted

**Expected behaviour:** The gameobject should cast the spell

**Steps to reproduce the problem:**

1. Just find any gameobject in game with type 10 and data10 field different from 0
(you can run this query to find them)
`SELECT * FROM gameobject_template WHERE TYPE = 10 AND data10 > 0;`
2. Right click on it and you will see that the object doesn't cast the spell (for some gameobject you can only open it)

P.S.
I already fixed the problem but I don't know if it is correct.
Line 1464 of GameObject.cpp
`spellCaster = NULL;`

Why is the spellCaster set to NULL?
From lines 1887

```
 if (spellCaster)
        spellCaster->CastSpell(user, spellInfo, triggered);
    else
CastSpell(user, spellId);
```

I tried adding comment to spellCaster = NULL; and it works and it works too if you change the line 
`CastSpell(user, spellId);`
to
`user->CastSpell(user, spellId);`

**Branch(es):** master (i think 3.3.5 too)

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/01e44cb794344902078518b9f424695f70b99242

**TDB version:**  Latest

**Operating system:**  Windows

**Comment by Rushor** [comment] 2017-01-07 11:59
> I tried adding comment to spellCaster = NULL; and it works and it works too if you change the line
CastSpell(user, spellId);
to
user->CastSpell(user, spellId);

well, would you like to open a pr for this then?

**Comment by giridhar123** [comment] 2017-01-07 12:30
I never did that, and i don't know how to do it :D

**Comment by Rushor** [comment] 2017-01-07 12:35
@giridhar123 https://trinitycore.atlassian.net/wiki/display/tc/Creating+a+Pull+Request#suk=

**Comment by giridhar123** [comment] 2017-01-07 12:39
Thanks

**Comment by Rochet2** [comment] 2017-01-07 12:50
Commit that introduced the null: https://github.com/TrinityCore/TrinityCore/commit/7c4f2f520f4047b10d94e44f6af1c910ff4bdbcf

**Comment by giridhar123** [comment] 2017-01-07 13:04
Hmmm i don't understand the utility of that null.

Maybe because the spell cast is declared here

```
if (spellId)
                {
                    for (GuidSet::const_iterator it = m_unique_users.begin(); it != m_unique_users.end(); ++it)
                        // m_unique_users can contain only player GUIDs
                        if (Player* owner = ObjectAccessor::GetPlayer(*this, *it))
                            owner->CastSpell(owner, spellId, false);

                    m_unique_users.clear();
                    m_usetimes = 0;
                }
```

But that doesn't works

**Comment by xinef1** [comment] 2017-01-07 14:24
Goobers require some more love, unique_users should be only used for rituals.

<details>

```diff

 src/server/game/Entities/GameObject/GameObject.cpp | 36 ++++++++++------------
 1 file changed, 17 insertions(+), 19 deletions(-)

diff --git a/src/server/game/Entities/GameObject/GameObject.cpp b/src/server/game/Entities/GameObject/GameObject.cpp
index f1365ac..c170931 100644
--- a/src/server/game/Entities/GameObject/GameObject.cpp
+++ b/src/server/game/Entities/GameObject/GameObject.cpp
@@ -634,19 +634,6 @@ void GameObject::Update(uint32 diff)
             //if Gameobject should cast spell, then this, but some GOs (type = 10) should be destroyed
             if (GetGoType() == GAMEOBJECT_TYPE_GOOBER)
             {
-                uint32 spellId = GetGOInfo()->goober.spellId;
-
-                if (spellId)
-                {
-                    for (GuidSet::const_iterator it = m_unique_users.begin(); it != m_unique_users.end(); ++it)
-                        // m_unique_users can contain only player GUIDs
-                        if (Player* owner = ObjectAccessor::GetPlayer(*this, *it))
-                            owner->CastSpell(owner, spellId, false);
-
-                    m_unique_users.clear();
-                    m_usetimes = 0;
-                }
-
                 SetGoState(GO_STATE_READY);
 
                 //any return here in case battleground traps
@@ -1193,6 +1180,10 @@ void GameObject::SwitchDoorOrButton(bool activate, bool alternative /* = false *
 
 void GameObject::Use(Unit* user)
 {
+    // we cannot use go with not selectable flags
+    if (HasFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE))
+        return;
+
     // by default spell caster is user
     Unit* spellCaster = user;
     uint32 spellId = 0;
@@ -1291,7 +1282,7 @@ void GameObject::Use(Unit* user)
 
                 if (itr->second)
                 {
-                    if (Player* ChairUser = ObjectAccessor::FindPlayer(itr->second))
+                    if (Player* ChairUser = ObjectAccessor::GetPlayer(*this, itr->second))
                     {
                         if (ChairUser->IsSitState() && ChairUser->GetStandState() != UNIT_STAND_STATE_SIT && ChairUser->GetExactDist2d(x_i, y_i) < 0.1f)
                             continue;        // This seat is already occupied by ChairUser. NOTE: Not sure if the ChairUser->GetStandState() != UNIT_STAND_STATE_SIT check is required.
@@ -1335,6 +1326,10 @@ void GameObject::Use(Unit* user)
         {
             GameObjectTemplate const* info = GetGOInfo();
 
+            // Goober cannot be used with this flag, skip
+            if (HasFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE))
+                return;
+
             if (Player* player = user->ToPlayer())
             {
                 if (info->goober.pageId)                    // show page...
@@ -1378,20 +1373,23 @@ void GameObject::Use(Unit* user)
             if (uint32 trapEntry = info->goober.linkedTrapId)
                 TriggeringLinkedGameObject(trapEntry, user);
 
-            SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
-            SetLootState(GO_ACTIVATED, user);
+            if (info->GetAutoCloseTime())
+            {
+                SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
+                SetLootState(GO_ACTIVATED, user);
+                if (!info->goober.customAnim)
+                    SetGoState(GO_STATE_ACTIVE);
+            }
 
             // this appear to be ok, however others exist in addition to this that should have custom (ex: 190510, 188692, 187389)
             if (info->goober.customAnim)
                 SendCustomAnim(GetGoAnimProgress());
-            else
-                SetGoState(GO_STATE_ACTIVE);
 
             m_cooldownTime = time(NULL) + info->GetAutoCloseTime();
 
             // cast this spell later if provided
             spellId = info->goober.spellId;
-            spellCaster = nullptr;
+            spellCaster = user;
 
             break;
         }

```

</details>

**Comment by giridhar123** [comment] 2017-01-08 12:45
Should we make a new pull request?

**Comment by Keader** [comment] 2017-01-08 12:49
for c++ fixes, yes ^^

**Comment by giridhar123** [comment] 2017-01-18 18:08
Hey guys, i made the pull request:
https://github.com/TrinityCore/TrinityCore/pull/18885

**Comment by Killyana** [comment] 2018-03-11 14:57
This is fixed?

**Comment by ariel-** [comment] 2018-03-11 17:29
Nope, just refs, but it can be fixed now

**Comment by jackpoz** [comment] 2019-01-08 07:47
@ariel- any news about this ?

**Comment by jackpoz** [comment] 2019-04-18 17:36
> 1. SELECT * FROM gameobject_template WHERE TYPE = 10 AND data10 > 0;

it would have been better to have at least 1 example (how do I even know if the GO cast the spell or not ?)

**Comment by jackpoz** [comment] 2019-04-18 18:13
tried with gameobject 164881 casting https://wotlk.evowow.com/spell=15344, it correctly added some items to my bags

![image](https://user-images.githubusercontent.com/1153754/56381773-16a18f00-6216-11e9-8efc-d7ae875b6b89.png)

If it doesn't work with some specific GameObject, then write some proper how to reproduce steps with clear commands (.go xyz or .gobj add)

**Closed by jackpoz** 2019-04-18 18:13 UTC
Labels: Comp-Core, Feedback-FixOutdatedMissingWIP, Sub-Entities, Sub-Spells

**Comment by funjoker** [comment] 2019-04-18 22:53
Well it’s Master issue. Since new 335 gobject cast system is not in master this bug is kinda correct.

CP missing like fuck.
