### ISSUE TITLE
[3.3.5] Bosses respawning

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#18824] opened 2017-01-13 18:50 UTC
**Description:** Bosses can respawn after you kill him.

**Expected behaviour:** Boss should never respawn after you kill him (after state = DONE).

**Steps to reproduce the problem:**

1. Kill some boss
2. Wait respawn

It was fixed by this commit: f826ecb4b2e8cc1fa54419947dff041a580d9c03
But reverted in : b3d44d6c366c7e4f12a6ce30ee5cf6b9bff68a06

Now need a new solution to fix Bosses without entry in linked_respawn.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  a17e3673b2d775db12ff16cba928648200679889

**Comment by joschiwald** [comment] 2017-01-13 23:56
how is it even possible that a boss can respawn?

**Comment by Treeston** [comment] 2017-01-13 23:57
Instance extension works now, they have a 1 week respawn timer (most of them) in the core.

Core doesn't have any option for "never respawn".

**Comment by joschiwald** [comment] 2017-01-14 00:30
maybe that will be a better solution to implement a never respawn option like -1 in creature.spawntimesecs

**Comment by sirikfoll** [comment] 2017-01-14 00:37
The -1 in creature.spawntimesecs may not be effective because of the _DespawnAtEvade funcionality, it calls a respawn that should be allowed in that case, checking bossState is the simpler way I can think of.

**Comment by joschiwald** [comment] 2017-01-14 00:44
that are 2 different respawn triggers, db respawntimer triggers on death, _DespawnAtEvade is a manuell respawn trigger

**Comment by Treeston** [comment] 2017-01-14 00:58
What @joschiwald says is theoretically correct, but would require us to rewrite respawn logic.

I don't know if the instance boss case is widespread enough for that.

**Comment by joschiwald** [comment] 2017-01-14 01:04
or maybe spawntime 0 because gameobject uses negativ spawntime to determine despawned by default (see loot chests)

**Comment by Treeston** [comment] 2017-01-14 01:35
spawntime 0 is instant respawn iirc

**Comment by Keader** [comment] 2017-01-14 11:30
So why remove the old fix if dynspawn is not ready? This modification just broken things and i cant see reason...
That modification should be done, when dynspawn is ready.

**Comment by Treeston** [comment] 2017-01-14 12:43
Because adding more and more differences that need to be fixed before dynspawn is ready will not lead to dynspawn ever being ready.

**Comment by Keader** [comment] 2017-01-14 13:31
yes, we need change it in every single script that dont have entrys in linked_spawn, and use it for every single new scripts... instead be inside of BossAI (that dont need change nothing).
I realy cant see any benefit in b3d44d6c366c7e4f12a6ce30ee5cf6b9bff68a06, because now need change more stuffs, so to me you still be "adding more and more differences that need to be fixed before dynspawn is ready "

**Comment by Treeston** [comment] 2017-01-14 13:32
The existing system (CanSpawn in AI) is simply not compatible with dynspawn. It's that simple.

The system needs to be removed for dynspawn to work.

**Comment by Noryad** [comment] 2017-01-17 14:46
Confirmed. We defeated Lord Marrowgar, Lady Deathwhisper, Gunship Battle, Deathbringer Saurfang, Festergut and Rotface in the early hours of 01/15/2017 and on Monday morning Lady Deathwhisper was alive, not the rest of mencioned bosses. the same situation is present at this moment (17/01/2017).

**Comment by Keader** [comment] 2017-01-17 15:01
Only Lady Deathwhisper and Blood Prince Council should respawn in ICC (caused by this bug), because other bosses has entry in linked_respawn.
I disagree with fix proposed in #18827, is much work to a "temp fix".
Maybe implement a "DB flag" like Jocshiwald suggest...
Btw, i cant do anything before finish illidan.

**Comment by Treeston** [comment] 2017-01-17 19:50
@Keader I wonder...should all creatures with bind flag never respawn naturally (unless spawn time override)?

**Comment by Keader** [comment] 2017-01-17 20:08
I think so...
But what happens in cases like Dungeons normal? Like Pit of Saron. Bosses dont have this flag... and dont should respawn

**Comment by Treeston** [comment] 2017-01-17 20:14
hrm, don't we have dungeon boss flag in there somewhere

if so we could just not schedule respawn if the respawn timer isn't specifically provided (in death logic)

**Comment by ariel-** [comment] 2017-01-19 10:35
> The existing system (CanSpawn in AI) is simply not compatible with dynspawn. It's that simple.

Why not? Can't it be made to call AI to check spawn possibility?

**Comment by Treeston** [comment] 2017-01-19 13:20
There is no AI object before the creature is spawned, because there is no creature object before it's spawned.

**Comment by Noryad** [comment] 2017-01-21 07:51
> ps: keep in mind the fix in #18827 is just a temporary fix

#18827 does not work, Lady Deathwhisper reappears after 24 hours.

**Comment by Keader** [comment] 2017-01-21 11:22
@Noryad you need make some changes in lady script to make that pr works.
Try add it:

```diff

diff --git a/src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp b/src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp
index f178498..57abd43 100644
--- a/src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp
+++ b/src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp
@@ -185,10 +185,10 @@ class DaranavanMoveEvent : public BasicEvent
         Creature& _darnavan;
 };
 
-class boss_lady_deathwhisper : public CreatureScript
+class boss_lady_deathwhisper : public BossCreatureScript
 {
     public:
-        boss_lady_deathwhisper() : CreatureScript("boss_lady_deathwhisper") { }
+        boss_lady_deathwhisper() : BossCreatureScript("boss_lady_deathwhisper", DATA_LADY_DEATHWHISPER) { }
 
         struct boss_lady_deathwhisperAI : public BossAI
         {
```

But again, this solution dont looks good to me  :/

**Comment by Treeston** [comment] 2017-01-21 13:02
i think easiest proper fix is a test when scheduling respawn (same method called by despawnonevade). if dungeon boss flag + no override respawn time -> never respawn.

will look into it.

**Comment by ariel-** [comment] 2017-01-21 19:19
> There is no AI object before the creature is spawned, because there is no creature object before it's spawned.

Strange then, how did the prev system work?

**Comment by Treeston** [comment] 2017-01-21 19:33
One creature object per GUID, recycled on respawn. Which is a horrible hack.

**Comment by Noryad** [comment] 2017-01-22 05:10
@Keader now it works ok

**Comment by Noryad** [comment] 2017-01-25 16:46
How would be for boss_blood_council? The following does not work for me...
```
class boss_blood_council_controller : public BossCreatureScript
{
    public:        
		boss_blood_council_controller() : BossCreatureScript("boss_blood_council_controller", DATA_BLOOD_PRINCE_COUNCIL) { }
```

**Comment by Treeston** [comment] 2017-01-25 17:27
IDK if princes have linked respawn with their controller.

**Comment by Keader** [comment] 2017-01-25 17:32
I removed princes spawn, they are summoned by controller (like illidari council in black temple).
So, if they respawn is because controller respawn. Controller has BossAI and using that code should never respawn.

```diff
diff --git a/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp b/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
index a6ec97c..fbab3f9 100644
--- a/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
+++ b/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
@@ -208,10 +208,10 @@ uint32 const PrincesData[] =
     DATA_PRINCE_VALANAR
 };
 
-class boss_blood_council_controller : public CreatureScript
+class boss_blood_council_controller : public BossCreatureScript
 {
     public:
-        boss_blood_council_controller() : CreatureScript("boss_blood_council_controller") { }
+        boss_blood_council_controller() : BossCreatureScript("boss_blood_council_controller", DATA_BLOOD_PRINCE_COUNCIL) { }
 
         struct boss_blood_council_controllerAI : public BossAI
         {
```

@Noryad BossState = 3 (DONE) when you build this code ?

**Comment by Keader** [comment] 2017-01-27 18:44
@Treeston Why not link this "NO-RESPAWN" to flags like: CREATURE_FLAG_EXTRA_DUNGEON_BOSS or CREATURE_FLAG_EXTRA_INSTANCE_BIND ?
All bosses should has this flags

**Comment by Noryad** [comment] 2017-01-27 19:37
@Keader when I tested it, Lady Deathwhisper and Blood Prince Council had been defeated and reappeared after 24 hours. with the temporary fix Lady Deathwhisper does not appear in the room, the opposite of Blood Prince Council.

**Comment by Keader** [comment] 2017-01-28 14:53
My suggestion about this issue is:

https://gist.github.com/Keader/70286275ce21fc6f4530f42f121b4bf7

**Comment by Treeston** [comment] 2017-01-28 15:59
That breaks DespawnAtEvade

**Comment by Treeston** [comment] 2017-02-07 13:32
Re-tagging #18827 for fix

**Comment by Noryad** [comment] 2017-02-17 18:49
Fix not working for difficulty 25 rev. c63f378

**Comment by Noryad** [comment] 2017-02-19 13:19
#18827 merged in 94a6dd7
At this time it works ok for 10 man, not for 25 man, current revision 76f3e0e

![lady_1](https://cloud.githubusercontent.com/assets/30839/23102701/fbd7b9e0-f662-11e6-8723-813c6b4b2526.jpg)

**Comment by Treeston** [comment] 2017-02-19 16:16
What is the output of `.npc info`

**Comment by Noryad** [comment] 2017-02-19 17:47
![lady info](https://cloud.githubusercontent.com/assets/30839/23104736/6849a71c-f688-11e6-9990-91db37329ae6.jpg)

**Comment by Treeston** [comment] 2017-02-19 17:48
Interesting, she doesn't get instance boss flag. No entry in `instance_encounter`?

**Closed** 2017-02-19 18:26 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-Instances

**Comment by Keader** [comment] 2017-02-19 19:07
Thank you @Noryad
