### ISSUE TITLE
[master] Mage - Blazing Barrier

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#19088] opened 2017-02-09 19:17 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Blazing Barrier doesn't absorb damage.

**Current behaviour:** Blazing Barrier doesn't absorb damage.

**Expected behaviour:** Blazing Barrier should absorb X amount of damage.

**Steps to reproduce the problem:**

1. Select Mage
2. Cast Blazing Barrier

**Branch(es):** master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/8aacc07727835ad3f81bebde3308cfdc4de2f26e

**TDB version:**  703.00 + updates

**Operating system:**  Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment] 2017-02-09 19:41
Fair enough, this time there does not seem to exist any other issues about `Blazing Barrier`.

Your issue post is somewhat lacking in information, please consider adding relevant information to make it easier to reproduce your issue (even for users who don't know the mage class well enough).

Add practical and relevant information from the following list:
- link(s) to spell(s) on wowhead/wowpedia/wowwiki pages relevant to patch 7.1.5 (or current master rev.)
- details about which level the player needs to be to obtain the spell
- details on the expected values (or refer to online sources)
- suggestions for what kind of damage is useful to test the spell

**Comment by DoctorKraft** [comment] 2017-02-09 20:43
It must look something like this

```
class spell_mage_blazing_barrier : public SpellScriptLoader
{
    public:
        spell_mage_blazing_barrier() : SpellScriptLoader("spell_mage_blazing_barrier") { }

        class spell_mage_blazing_barrier_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_mage_blazing_barrier_AuraScript);

            void CalculateAmount(AuraEffect const* /*aurEff*/, int32& amount, bool& canBeRecalculated)
            {
                canBeRecalculated = false;
                float bonus = 0.7f;

                if (Unit* caster = GetCaster())
                    amount += int32(bonus * caster->SpellBaseHealingBonusDone(GetSpellInfo()->GetSchoolMask()));
            }

            void Register() override
            {
                DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mage_blazing_barrier_AuraScript::CalculateAmount, EFFECT_0, SPELL_AURA_SCHOOL_ABSORB);
            }
        };

        AuraScript* GetAuraScript() const override
        {
            return new spell_mage_blazing_barrier_AuraScript();
        }
};
```

**Comment by ArcaneFox** [comment] 2017-02-10 01:00
Yes it is working. :D

(I'm still learning the TrinityCore and my solution is similar except for the absorb amount which is 7.0f plus versiality. After this I will also update the Ice Barrier.)

**Comment by ArcaneFox** [comment] 2017-02-10 07:34
The following code is working but the amount of absorb and reflect aren't correct:

```
SPELL_MAGE_BLAZING_BARRIER_TRIGGERED         = 235314

// 235313 - Blazing Barrier [7.1.5]
class spell_mage_blazing_barrier : public SpellScriptLoader
{
    public:
        spell_mage_blazing_barrier() : SpellScriptLoader("spell_mage_blazing_barrier") { }

        class spell_mage_blazing_barrier_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_mage_blazing_barrier_AuraScript);

            bool Validate(SpellInfo const* /*spellInfo*/) override
            {
                if (!sSpellMgr->GetSpellInfo(SPELL_MAGE_BLAZING_BARRIER_TRIGGERED))
                    return false;
                return true;
            }

            void CalculateAmount(AuraEffect const* /*aurEff*/, int32& amount, bool& canBeRecalculated)
            {
                canBeRecalculated = false;
                if (Unit* caster = GetCaster())
                    amount += int32(7.0f * caster->SpellBaseHealingBonusDone(GetSpellInfo()->GetSchoolMask()));
            }

            void ReflectDamage(AuraEffect* aurEff, DamageInfo & dmgInfo, uint32 & /*absorbAmount*/)
            {
                Unit* target = GetTarget();
                Unit* caster = GetCaster();
                if (caster && target && target->IsWithinMeleeRange(caster))
                {
                    int32 amount = 0.5f * caster->SpellBaseDamageBonusDone(GetSpellInfo()->GetSchoolMask());
                    target->CastCustomSpell(dmgInfo.GetAttacker(), SPELL_MAGE_BLAZING_BARRIER_TRIGGERED, &amount, NULL, NULL, true, NULL, aurEff);
                }
            }

            void Register() override
            {
                DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mage_blazing_barrier_AuraScript::CalculateAmount, EFFECT_0, SPELL_AURA_SCHOOL_ABSORB);
                AfterEffectAbsorb += AuraEffectAbsorbFn(spell_mage_blazing_barrier_AuraScript::ReflectDamage, EFFECT_0);
            }
        };

        AuraScript* GetAuraScript() const override
        {
            return new spell_mage_blazing_barrier_AuraScript();
        }
}
```

**Comment by DoctorKraft** [comment] 2017-02-10 11:05
I think the cause is `GetSchoolMask()` for absorb, get spellpower value * 7.0f (0.7f?) 

For reflect it's a bad idea this, because it's a proc so you need use `HandleProc` (OnEffectProc) on EFFECT_1 and normaly you don't need use a `CastCustomSpell` because the spell trigerred have already good amount. You need just get caster for calculate damage

I don't have spellwork for rev 7.1.5 but i think my idea is good ^^

**Comment by DoctorKraft** [comment] 2017-02-10 11:55
For absorb it's good with this (my bad)
```
        void CalculateAmount(AuraEffect const* /*aurEff*/, int32& amount, bool& canBeRecalculated)
        {
            canBeRecalculated = false;

            if (Unit* caster = GetCaster())
                amount = int32(caster->SpellBaseHealingBonusDone(GetSpellInfo()->GetSchoolMask()) * 7.0f);
        }
```

**Comment by ArcaneFox** [comment] 2017-02-10 13:11
After equipping this item the absorb amount is incorrect. I think the versatility calculation is missing/wrong in the core.

![wowscrnshot_021017_140052](https://cloud.githubusercontent.com/assets/25306170/22827837/319cec78-ef9a-11e6-8744-baf24002a060.jpg)

**Comment by DoctorKraft** [comment] 2017-02-10 13:17
don't look tooltip is totally wrong (not scripted for moment) and yes versability are wrong or not correctly update in aura tooltip ^^

**Comment by ArcaneFox** [comment] 2017-02-10 13:19
Ah okay :)

**Comment by DoctorKraft** [comment] 2017-02-10 13:20
the correct scripting is

```
class spell_mage_blazing_barrier : public SpellScriptLoader
{
    public:
        spell_mage_blazing_barrier() : SpellScriptLoader("spell_mage_blazing_barrier") { }

        class spell_mage_blazing_barrier_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_mage_blazing_barrier_AuraScript);

            void CalculateAmount(AuraEffect const* /*aurEff*/, int32& amount, bool& canBeRecalculated)
            {
                canBeRecalculated = false;

                if (Unit* caster = GetCaster())
                    amount = int32(caster->SpellBaseDamageBonusDone(GetSpellInfo()->GetSchoolMask()) * 7.0f);
            }

            void HandleProc(AuraEffect const* /*aurEff*/, ProcEventInfo& eventInfo)
            {
                PreventDefaultAction();

                Unit* caster = eventInfo.GetDamageInfo()->GetAttacker();
                Unit* target = eventInfo.GetDamageInfo()->GetVictim();
                if (!caster || !target)
                    return;

                caster->CastSpell(target, SPELL_MAGE_BLAZING_BARRIER_TRIGGERED, true);
            }

            void Register() override
            {
                DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mage_blazing_barrier_AuraScript::CalculateAmount, EFFECT_0, SPELL_AURA_SCHOOL_ABSORB);
                OnEffectProc += AuraEffectProcFn(spell_mage_blazing_barrier_AuraScript::HandleProc, EFFECT_1, SPELL_AURA_PROC_TRIGGER_SPELL);
            }
        };

        AuraScript* GetAuraScript() const override
        {
            return new spell_mage_blazing_barrier_AuraScript();
        }
};
```
```
Proc flag 0x00000028, chance: 100%, charges: 0, cooldown: 0
=================================================
  03 Taken damage from melee strike hit
  05 Taken damage by Spell that use melee weapon
=================================================
```
But no proc on my core Oo

**Comment by Keader** [comment] 2017-02-10 13:26
Missing entry in spell_proc?

**Comment by DoctorKraft** [comment] 2017-02-10 13:27
No, i have try but nothing also ><

**Comment by matukaa** [comment] 2017-02-10 14:32
`AddPct(amount, caster->ToPlayer()->GetRatingBonusValue(CR_VERSATILITY_DAMAGE_DONE));`

Use versatility! By doing this I get the exact same number as in the tooltip

**Comment by Keader** [comment] 2017-02-10 14:34
And pooke ariel-, he know better about proc system 💃

**Comment by matukaa** [comment] 2017-02-10 14:47
Btw, it won't proc if you fully absorb the incoming damage. current implementation doesn't let it proc

**Comment by DoctorKraft** [comment] 2017-02-10 15:00
I don't understand @matukaa. How the spell is supposed proc ?

**Comment by matukaa** [comment] 2017-02-10 16:14
check the implementation for procs. no aura will proc if you fully absorb the incoming damage. like you have 10k absorb, you get 2k damage, damage will be reduced to 0 due to absorb, proc will fail :) you could try with PROC_EX_ABSORB (0x400) but I believe it won't proc not even with that one.

**Comment by ariel-** [comment] 2017-02-10 18:11
Keader: in master the old spell_proc_event system is still in use.

**Comment by ArcaneFox** [comment] 2017-02-11 17:35
After fixing the ReflectDamage method (AddPct), the AfterEffectAbsorb callback is works for me with good reflect damage.

**Comment by Shauren** [comment] 2017-02-11 18:01
Do not manually factor in versatility please, it is completely not implemented in core

**Comment by DoctorKraft** [comment] 2017-03-22 15:57
Fixed https://github.com/TrinityCore/TrinityCore/commit/e13f82d18d16bb979c97d73cef507827c2f22e9d can be closed

**Comment by tkrokli** [comment] 2017-03-22 15:59
Closed by commit https://github.com/TrinityCore/TrinityCore/commit/e13f82d18d16bb979c97d73cef507827c2f22e9d , as stated by @DoctorKraft .

**Closed by tkrokli** 2017-03-22 15:59 UTC
Labels: Branch-master, Comp-C++Script, Feedback-FixOutdatedMissingWIP, Sub-Spells
