### ISSUE TITLE
[3.3.5] Banish Charms in Arathi Highlands

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14020] opened 2015-02-03 10:35 UTC
Hi all, in Arathi Highlands, elementals drop items you could use to banish other kind of elementals.

Like these:
http://www.wowhead.com/item=4480/thundering-charm
http://www.wowhead.com/item=4481/cresting-charm

But they don't work.

I'm running version rev. f3e86d3 2015/01/01 so i'm few updates behind.

**Comment by Rushor** [comment] 2015-02-03 12:43
```sql
/* SAI for Burning Exile */
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=2760;
DELETE FROM `smart_scripts` WHERE `entryorguid`=2760;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(2760, 0, 0, 0, 8, 0, 100, 0, 4130, 0, 0, 0, 41, 500, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Burning Exile - on spellhit - Despawn');

/* SAI for Cresting Exile */
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=2761;
DELETE FROM `smart_scripts` WHERE `entryorguid`=2761;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(2761, 0, 0, 0, 1, 0, 100, 1, 1000, 1000, 1800000, 1800000, 11, 12544, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Cresting Exile - Out Of Combat - Cast Frost Armor'),
(2761, 0, 1, 0, 0, 0, 100, 0, 1400, 7300, 25600, 32300, 11, 865, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Cresting Exile - In Combat - Cast Frost Nova'),
(2761, 0, 2, 0, 8, 0, 100, 0, 4131, 0, 0, 0, 41, 500, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Cresting Exile - on spellhit - Despawn');

/* SAI for Thundering Exile */
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=2762;
DELETE FROM `smart_scripts` WHERE `entryorguid`=2762;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(2762, 0, 0, 0, 1, 0, 100, 1, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - Out Of Combat - Allow Combat Movement'),
(2762, 0, 1, 2, 4, 0, 100, 0, 0, 0, 0, 0, 11, 9532, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - On Aggro - Cast Lightning Bolt'),
(2762, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 23, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - On Aggro - Increment Phase'),
(2762, 0, 3, 0, 9, 0, 100, 0, 0, 40, 3300, 6600, 11, 9532, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - At 0 - 40 Range - Cast Lightning Bolt'),
(2762, 0, 4, 5, 3, 0, 100, 0, 0, 15, 0, 0, 21, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - At 15% Mana - Allow Combat Movement'),
(2762, 0, 5, 0, 61, 0, 100, 0, 0, 0, 0, 0, 23, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - At 15% Mana - Increment Phase'),
(2762, 0, 6, 0, 9, 0, 100, 1, 35, 80, 0, 0, 21, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - At 35 - 80 Range - Allow Combat Movement'),
(2762, 0, 7, 0, 9, 0, 100, 1, 0, 5, 0, 0, 21, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - At 0 - 5 Range - Allow Combat Movement'),
(2762, 0, 8, 0, 9, 0, 100, 0, 5, 15, 0, 0, 21, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - At 5 - 15 Range - Allow Combat Movement'),
(2762, 0, 9, 10, 3, 0, 100, 0, 30, 100, 0, 0, 21, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - At 100% Mana - Allow Combat Movement'),
(2762, 0, 10, 0, 61, 0, 100, 0, 0, 0, 0, 0, 23, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - At 100% Mana - Increment Phase'),
(2762, 0, 11, 0, 0, 0, 100, 0, 1600, 15100, 18900, 25400, 11, 11824, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - In Combat - Cast Shock'),
(2762, 0, 12, 0, 8, 0, 100, 0, 4132, 0, 0, 0, 41, 500, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Thundering Exile - on spellhit - Despawn');
```

**Comment by tkrokli** [comment] 2015-02-03 21:45
@ikir83 : when you say "But they don't work.", do you mean "they don't drop (from the elementals)"?

@Rushor : I will go for a test run in Arathi Highlands, before and after insert. Feedback tomorrow, I hope.

**Comment by ikir83** [comment] 2015-02-03 22:46
@tkrokli 
Elementals drop them, but they didn't work. You can use (and consume them) but target elementals are not banished.

**Comment by tkrokli** [comment] 2015-02-03 23:18
OK, thanks for the clarification. Useful info while testing before and after adding Rushor's SAI script.

**Comment by tkrokli** [comment] 2015-02-08 00:24
Issue confirmed on https://github.com/TrinityCore/TrinityCore/commit/0c9e39f1510c838cb3c84fc7502db9dd00bd4771 merged with https://github.com/tkrokli/TrinityCore/commit/073c14eb4e5080f229661278b1be09e2f39179cc with https://github.com/TrinityCore/TrinityCore/commit/03edeeb9d81728ed856d05cace9e264f0d0c37fc manually added.

Picked up and tested all 3 of these charms on their respective exiles:
http://www.wowhead.com/item=4479/burning-charm - Use: [Banishes a Thundering Exile](http://www.wowhead.com/spell=4132/banish-thundering-exile)
http://www.wowhead.com/item=4480/thundering-charm - Use: [Banishes a Cresting Exile](http://www.wowhead.com/spell=4131/banish-cresting-exile)
http://www.wowhead.com/item=4481/cresting-charm - Use: [Banishes a Burning Exile](http://www.wowhead.com/spell=4130/banish-burning-exile)

The only effect from using the items was to aggro the mobs from a slightly longer distance than my regular (Death Knight) spell range. When activating the item, the spell checked if the mob was the correct type, though. OK, done testing before applying SQL SAI script.

Exit game, added script to DB, restarted server & game. Script works as intended.
Tested 20 of each charm, though there were only 12, 13 and 14 mobs of each type.
Interesting side effect: from the first 12 Thundering Charms I used on the Cresting Exiles, my DK character triggered [Retaliation] ~50% of the times after the NPC was banished/dispelled/despawned.

The banish (despawn) effect was approximately as expected, 1-2 second(s) fade effect.

**Closed** 2015-02-09 06:27 UTC
Labels: Comp-Database, Feedback-PatchFix
