### ISSUE TITLE
[3.3.5][Bug - Dungeon Finder] Allways 1 dps missing

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#17012] opened 2016-04-21 14:35 UTC
**Current behaviour**: When 5 person join with the correct roles you should be prompted with the enter dungeon button. It's not happening, it allways shows that one dps is missing. But if you join as party, it will work.

**Expected behaviour**: You should be able to join without party.

**Steps to reproduce the problem**:

1.  Get five people of the same level range to join dungeon finder 3 dps, 1 healer , 1 tank
2.  Check that nothing happens.

**Branch(es)**: 335

**TC hash/commit**:  02d7df6aa435+

**TDB version**:  TDB 335.57

**Operating system**:  Centos 7 64 Bits

**Comment by Rushor** [comment] 2016-04-21 14:44
reason https://github.com/TrinityCore/TrinityCore/issues/16241 ?

**Comment by silvermcd123** [comment] 2016-04-21 15:02
@Rushor  Not really

**Comment by jackpoz** [comment] 2016-04-21 17:38
Enable debug logs for lfg and check the reason why they didn't match. please try with 5 fresh new characters with no instance locks.

**Comment by Aokromes** [comment] 2016-04-21 19:02
[20:54:30] Someone has declined the dungeon invite. You have been returned to the front of the dungeon queue.
[20:54:34] Someone has declined the dungeon invite. You have been returned to the front of the dungeon queue.
[20:54:35] Someone has declined the dungeon invite. You have been returned to the front of the dungeon queue.
[20:55:23] You have been removed from the Dungeon queue because you did not accept the invitation.

**Comment by silvermcd123** [comment] 2016-04-22 00:30
@jackpoz i will try and will come back with it.

**Comment by boom8866** [comment] 2016-04-22 12:37
confirm

**Comment by jackpoz** [comment] 2016-04-22 13:22
> confirm

what are you confirming exactly ? did you try https://github.com/TrinityCore/TrinityCore/issues/17012#issuecomment-213032006 ?

**Comment by boom8866** [comment] 2016-04-22 16:52
one player selected multiple roles   

confirm

**Comment by boom8866** [comment] 2016-04-22 16:56
The test is 16241, but 100% is not confirmed, if you can teach me how to use the code limit can only choose an occupation, a few days I will have the result.

**Comment by silvermcd123** [comment] 2016-04-26 00:24
Multiple Roles is the cause

**Comment by Rushor** [comment] 2016-04-26 06:19
if mutliple roles is the cause, can we close this, because it's a duplicate from https://github.com/TrinityCore/TrinityCore/issues/16241 ?

**Comment by boom8866** [comment] 2016-04-27 14:33
@Rushor   OK!

**Closed** 2016-04-27 16:49 UTC
Labels: Invalid-CannotReproduce
