### ISSUE TITLE
[335] PvP Flag - Manual toggle does not work properly (PvE Realm)

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#13103] opened 2014-09-11 21:00 UTC
**Core:** 0392bf9bdfaed726a1ef473bb477b338765f4806
**DB:** N/A
### Bug:

On a PVE realm (realm type 6) when a player types _/PVP_ to turn on their flag, it is not properly tracked across logout or zone changes from hearthing. The core doesn't handle it properly when the player is spawned into the world.

Finally, if you type /PVP to turn _off_ your flag, when the timer runs out it does not remove the player's PvP status.
### Details:

**_Example 1_**
- Log in and go to a non-sanctuary zone (such as Goldshire)
- Type /PVP to turn on your flag
- Log out
- Log in

At this point the player will NOT have the PVP flag on their portrait **and** _IsPvP()_ returns FALSE however typing _/PVP_ thinking it will turn the flag on displays the message:

> You will be unflagged for PvP in five minutes...

**_Example 2_**
- Type /PVP to turn on your flag
- Use your Hearthstone

At this point the player will NOT have the PVP flag on their portrait and  typing _/PVP_ thinking it will turn the flag on displays the message:

> You will be unflagged for PvP in five minutes...

**_Example 3_**
- Type /PVP to turn on your flag
- Type /PVP to turn off your flag

Wait until the timer runs out (don't hearth or change zones). Notice you are still flagged for PvP until you hearth or change zones.
### Conclusion

The core doesn't seem to be properly tracking the PvP status. In some cases, _IsPvP()_ it thinks it's disabled but in terms of _/PVP_ it thinks it's enabled. Other cases it simply doesn't remove PVP status when it should.
### Notes:
- I honestly can't remember if it should be disabled at logout or not. I don't think it should unless logged out longer than 5 minutes but I can't be sure.
- I don't know about other realm types but I don't think this is realm specific, it seems more like a generic PvP issue.
- I haven't tested on normal zone changes (eg: loading screens into / out of the Deeprun Tram)
##

**Comment by Rushor** [comment] 2015-01-22 11:44
so probably we can try to find out first, why typing /pvp after relog returns the error-message. there must be something which saves the pvp-status after login and logout :/

**Comment by Rushor** [comment] 2015-01-23 14:20
i think the problem is somewhere here in the toggleaction:
https://github.com/Rushor/TrinityCore/blob/3.3.5/src/server/game/Handlers/MiscHandler.cpp#L467

**Comment by Frytiks** [comment] 2015-04-15 18:04
Confirmed.

**Comment by Rushor** [comment] 2015-04-15 18:20
confirmation is useless

**Comment by Frytiks** [comment] 2015-04-15 22:54
Can someone try this ? http://pastebin.com/Ubd6uvHW

**Comment by Frytiks** [comment] 2015-07-02 08:38
Still confirmed on https://github.com/TrinityCore/TrinityCore/commit/2263cb9e1015ed0f6dbf83b63d8f0332bcbe6205

**Comment by Frytiks** [comment] 2015-08-27 08:22
New note: On my server it's done only for some characters, not all. For some players pvp turn on or off properly, but for some characters totally not.

**Comment by Keader** [comment] 2016-01-02 02:21
Any news?

**Comment by Rushor** [comment] 2016-01-02 10:47
Keader pls..

**Comment by Rushor** [comment] 2016-01-26 07:52
@Frytiks: i tested your patch and sadly it doesn't changed anything

**Comment by Rushor** [comment] 2018-04-25 08:27
This was fixed by https://github.com/TrinityCore/TrinityCore/pull/19930 ?

**Closed** 2018-04-25 09:34 UTC
Labels: Comp-Core, Feedback-FixOutdatedMissingWIP, Sub-PvP-Zones
