### ISSUE TITLE
[Patch-Fix] [spell_priest] Shadow Word Death.

### ISSUE THREAD

**Issue by e000** [TrinityCore/TrinityCore#9346] opened 2013-03-05 06:00 UTC
[spell_priest] Use AfterHit handler for SW: Death, and use TrueDamage (which includes all damage bonuses).
- We use after hit handler so that we can check if the target is alive after the spell has landed.
- Use GetTrueDamage instead of GetHitDamage to get the damage actually done by the spell. I'm pretty sure this is what blizz uses, the damage is reflected onto you after all damage mods are calculated, meaning you can effectively 1 shot yourself with SW:Death. (refs: [1](http://www.wowhead.com/spell=32379#comments:id=116734), [2](http://www.wowhead.com/spell=32379#comments:id=883120))
##

**Comment by ariel-** [comment] 2016-12-01 05:58
The issue is no longer current as of 343419ab992ca3b8dd93e87e8a16a1ee097447bf. Closing.

**Closed by ariel-** 2016-12-01 05:58 UTC
Labels: Branch-3.3.5a, Comp-Core, Priority-FutureFeatureRequest, Sub-Spells
