### ISSUE TITLE
Problem in hellfire

### ISSUE THREAD

**Issue by Voidx** [TrinityCore/TrinityCore#16092] opened 2015-12-23 22:42 UTC
Im not sure about this problem but wen restart server all is ok, anybody know the reason of this:
https://www.youtube.com/watch?v=TD0-qJxWBq0
I take a video cause is dificult to splain the problem

(ba1e00399db9c90bbba2c295ad93415d9f1acada, no adds)

**Comment by msoky** [comment] 2015-12-23 23:14
Falling mount or lags at end of video?

**Comment by tkrokli** [comment] 2015-12-24 00:05
If it is not the falling gryphon or lag, I don't know, because the videos does not describe much.

**Comment by Voidx** [comment] 2016-01-05 16:41
please view vide with audio, a sound start and all wow lags.

**Comment by msoky** [comment] 2016-01-05 16:45
can anyone reproduce it? sound is really bad...probably that is not trinitycore problem, maybe it is computer problem

**Comment by Voidx** [comment] 2016-01-07 11:13
I test it on 3 computers. And only happend in this map. wen enter to inn

**Comment by tkrokli** [comment] 2016-01-08 01:49
The only thing I can compare that sound to, is a broken sound file. Have you tried turning off sound to see if the client gets lag then? I think the "kitchen abmience sound" is the one that starts alongside the music, but it looks like that sound file might be broken on your client. In your video, the game client seems to play the music file correctly, but not the ambience.

**Comment by Kittnz** [comment] 2016-01-08 07:28
could be a bad client, just find another client and try again

**Comment by Aokromes** [comment] 2016-01-08 09:12
You have tried to reproduce it on a clean TC and without any addons?

**Comment by Rushor** [comment] 2016-02-02 09:50
no answer after nearly one month - closing

**Closed by Rushor** 2016-02-02 09:50 UTC
Labels: Invalid-CannotReproduce

**Comment by sirikfoll** [comment] 2016-02-15 02:03
this just happened in the server i play, the client almost freezes(1fps or so) and keeps playing a strange sound, like something is in a loop. But that core is not clean. maybe it have something with the known crash with the quest The Exorcism of colonel jules(the assert that was crashing was removed from the core i'm using)

**Comment by Voidx** [comment] 2016-03-04 05:31
Sirikfoll thanks for some info, Not sure why close but it continue feeze players ^^

**Comment by Killyana** [comment] 2016-03-27 20:23
Related to The Exorcism of colonel jules quest.
