### ISSUE TITLE
Core/SAI: SMART_ACTION_CAST or SMART_ACTION_SELF_CAST or SMART_ACTION_INVOKER_CAST does not work for gameobjects (creatures?) inside action list if action list is called inside SMART_EVENT_SPELLHIT

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#25053] opened 2020-07-15 15:25 UTC
**Description:**

We have one gameobject script which uses SMART_ACTION_INVOKER_CAST inside timed action list. And timed action list is called inside SMART_EVENT_SPELLHIT. But SMART_ACTION_CAST or SMART_ACTION_INVOKER_CAST or SMART_ACTION_SELF_CAST does not work inside action lists in case of gameobjects(creatures?) IF timed action list is called inside SMART_EVENT_SPELLHIT.
Everything works just fine if SMART_ACTION_INVOKER_CAST is used inside SMART_EVENT_SPELLHIT and not inside action list.

**Expected behaviour:**

SMART_ACTION_CAST or SMART_ACTION_SELF_CAST or SMART_ACTION_INVOKER_CAST must work inside timed action lists if action list was called inside SMART_EVENT_SPELLHIT. **Or we should investigate it because the script I'm talking about probably must be handled by spell script and not by SAI.** Didn't checked another scripts. We need to know if it can be used in another scripts or we just need to use spell scripts and waste no time for fixing that issue. Or fix it if it was broken at some point because it could be related to more issues.

**Steps to reproduce the problem:**

1. .q a 11140
2. open provided item
3. go game id 186283
4. use 'Salvage Kit'

Current script is here:
```sql
SELECT * FROM smart_scripts WHERE entryorguid=186283 OR entryorguid=18628300 OR entryorguid=18628301
```

So when the item is used, player must cast https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=42288 on self or cast https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=42289 (notice the spell has condition but it doesn't matter since everything works out of timed action list)
Nothing happens currently but if you force player to cast the spells not inside timed action list, everything works.
Initially I was thinking it does not work because we use target type 7 (invoker) and invoker (player) wasn't stored properly or was removed. But gameobject simply can't cast spells (I tried another spell) with SMART_ACTION_CAST too inside action list if action list was called inside SMART_EVENT_SPELLHIT.

Also nothing here is related to gameobject despawn. Everything works even with despawn if spell is used not inside action list.

**Branch:** 3.3.5
**TC rev. hash/commit:** 8675fd756ff9

**Comment by offl** [comment] 2020-07-15 15:36
Also I wrote the update to use recently implemented effect Activate Object
This version too does not work(I mean spell cast, despawn part works)
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 13 AND `SourceEntry` = 42287;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(13,1,42287,0,0,31,0,5,186283,0,0,0,0,"","Group 0: Spell 'Salvage Wreckage' (Effect 0) targets object 'Shipwreck Debris'"),
(13,2,42287,0,1,31,0,5,186283,0,0,0,0,"","Group 1: Spell 'Salvage Wreckage' (Effect 1) targets object 'Shipwreck Debris'"),
(13,4,42287,0,2,31,0,5,186278,0,0,0,0,"","Group 2: Spell 'Salvage Wreckage' (Effect 2) targets object 'Burning Wreckage'");

DELETE FROM `smart_scripts` WHERE `entryorguid` = 186283 AND `source_type` = 1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(186283,1,0,0,8,0,100,0,42287,0,0,0,0,87,18628300,18628301,0,0,0,0,1,0,0,0,0,0,0,0,0,"Shipwreck Debris - On Spellhit 'Salvage Wreckage' - Run Random Script");
```

@ZenoX92 do you remember if you tested https://github.com/TrinityCore/TrinityCore/issues/22245? Because if not, that thing probably was always broken or not implemented

**Comment by ZenoX92** [comment] 2020-07-15 22:24
> @ZenoX92 do you remember if you tested #22245? Because if not, that thing probably was always broken or not implemented

It's been a while since that, but I'm pretty sure I tested it, and it used to work just fine.

**Comment by offl** [comment] 2020-07-15 23:34
Thanks
So something was broken in past two years

**Comment by offl** [comment] 2020-07-23 19:17
(Probably) working solution with stored target https://github.com/TrinityCore/TrinityCore/issues/25099#issuecomment-663159288. Didn't tested.

**Comment by Rushor** [comment] 2020-07-25 08:33
what if we save the target with action 64 and then use target 12 in actionlist?

**Comment by offl** [comment] 2020-07-25 16:50
It will probably work. But since it worked without stored target before I just want to know should we fix this unique case or just ignore it. Maybe it affects more scripts or will affect more scripts in future(have no idea).

We also can add CPP script to the spell and SAI here will be not involved at all.

**Comment by jackpoz** [comment] 2020-08-05 20:11
the spell https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=42287 has "Activate Object: (15)" spell effect and that's GameObjectActions::Despawn . As the action list SMART_ACTION_CALL_RANDOM_TIMED_ACTIONLIST is scheduled on next update, the action is never executed

**Comment by jackpoz** [comment] 2020-08-06 11:54
unless there is a case where a despawn is not involved (either from SAI or from spell effect Activate Object), I'm going to close this ticket

**Comment by jackpoz** [comment] 2020-08-07 13:18
closing as the issue described is caused by the GameObject being despawned before SMART_ACTION_CALL_RANDOM_TIMED_ACTIONLIST can be executed (unrelated to the issue title)

**Closed by jackpoz** 2020-08-07 13:18 UTC
Labels: Branch-3.3.5a, Comp-Core, Sub-ScriptingEngine
