### ISSUE TITLE
[Escort Quest] A Fine Mess

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#1722] opened 2011-05-27 22:51 UTC
Quest http://www.wowhead.com/quest=2904/a-fine-mess doesn't have a script for it, therefore cannot be completed.
Kernobee: http://www.wowhead.com/npc=7850

TDB 40 Core: 48b0570f5333

**Comment by Trisjdc** [comment] 2016-01-08 18:24
This quest is still broken, why is the issue closed? There was no commit as far as I can see.

**Comment by Navedonar** [comment] 2016-10-16 17:56
.

**Comment by CrazyPeppers** [comment] 2017-03-02 03:00
Here is a potential solution.  
If someone could test it with a group I would appreciate the results, I’m not entirely certain that Kernobee SAI lines 1 and 16 are need (the group event happens) for the non-invoker players.  
I also couldn’t get the Action_follow to end  (id = 9) without transferring the follow to a non-moving creature, in the invisible trigger.  I wasn’t sure which trigger creature type to use but “Invisible Location Trigger” seemed reasonable.

What’s Missing:
-Kernobee’s start text and agro (I just couldn’t find reference but I know he did say something)

`-- Invisible Trigger for A Fine Mess Quest
SET @TRIGGUID := 213820;
DELETE FROM `creature` WHERE `guid`=@TRIGGUID;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(@TRIGGUID,19656,90,0,0,1,1,0,0,-355.45,7.006,-152.85,2.40887,300,0,0,4121,0,0,0,0,0,0);`

-- Kernobee Waypoint
SET @ENTRY := 7850;
DELETE FROM `waypoints` WHERE `entry` = @ENTRY;
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES 
(@ENTRY, 1, -349.3, 4.72, -152.847, "Kernobee end waypoint for quest (A Fine Mess)"),
(@ENTRY, 2, -324.6, -4.96, -152.847, "Kernobee exit waypoint for quest (A Fine Mess)");

-- Kernobee Text
SET @ENTRY := 7850;
DELETE FROM `creature_text` WHERE `entry` = @ENTRY;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(@ENTRY,'0','0','Thank you for rescuing me! Word of your deed will not go unnoticed.','12','0','0','0','0','0','0','0','Kernobee End Say 1'),
(@ENTRY,'1','0','Kernobee cheers!','16','0','0','4','0','0','0','0','Kernobee End Say 2'),
(@ENTRY,'2','0','I see the exit! Hurry, hurry!','12','0','0','0','0','0','0','0','Kernobee End Say 3');

-- Kernobee SAI
SET @ENTRY := 7850;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,1,19,0,100,512,2904,0,0,0,64,1,0,0,0,0,0,7,0,0,0,0,0,0,0,"Kernobee - On Quest 'A Fine Mess' Taken - Store Targetlist Leader"),
(@ENTRY,0,1,2,61,0,100,512,2904,0,0,0,64,2,0,0,0,0,0,16,0,0,0,0,0,0,0,"Kernobee - On Quest 'A Fine Mess' Taken - Store Targetlist Group"),
(@ENTRY,0,2,3,61,0,100,512,2904,0,0,0,29,0,0,0,0,0,0,12,1,0,0,0,0,0,0,"Kernobee - On Quest 'A Fine Mess' Taken - Start Follow Stored Target"),
(@ENTRY,0,3,4,61,0,100,512,2904,0,0,0,81,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Quest 'A Fine Mess' Taken - Set Npc Flag "),
(@ENTRY,0,4,5,61,0,100,512,2904,0,0,0,19,768,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Quest 'A Fine Mess' Taken - Remove Flags Immune To Players & Immune To NPC's"),
(@ENTRY,0,5,6,61,0,100,512,2904,0,0,0,91,7,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Quest 'A Fine Mess' Taken - Remove Flag Standstate Dead"),
(@ENTRY,0,6,0,61,0,100,512,2904,0,0,0,2,250,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Quest 'A Fine Mess' Taken - Set Faction 250"),
(@ENTRY,0,7,0,7,0,100,512,0,0,0,0,91,7,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Evade - Remove Flag Standstate Dead"),
(@ENTRY,0,8,0,6,0,100,512,0,0,0,0,6,2904,0,0,0,0,0,12,2,0,0,0,0,0,0,"Kernobee - On Just Died - Fail Quest 'A Fine Mess'"),
(@ENTRY,0,9,10,75,0,100,512,0,19656,4,1000,29,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Kernobee - On Distance To Creature - Start Follow Invoker"),
(@ENTRY,0,10,11,61,0,100,512,0,0,0,0,53,0,7850,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Distance To Creature - Start Waypoint"),
(@ENTRY,0,11,0,61,0,100,1,0,0,0,0,23,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Distance To Creature - Increment Phase"),
(@ENTRY,0,12,13,40,1,100,512,1,0,0,0,54,20000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Waypoint 1 Reached - Pause Waypoint (Phase 1)"),
(@ENTRY,0,13,14,61,1,100,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Waypoint 1 Reached - Say Line 0 (Phase 1)"),
(@ENTRY,0,14,15,61,1,100,1,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Waypoint 1 Reached - Say Line 1 (Phase 1)"),
(@ENTRY,0,15,16,61,1,100,0,0,0,0,0,15,2904,0,0,0,0,0,12,1,0,0,0,0,0,0,"Kernobee - Out of Combat - Quest Credit 'A Fine Mess' (Phase 1) (No Repeat)"),
(@ENTRY,0,16,17,61,1,100,0,0,0,0,0,26,2904,0,0,0,0,0,12,2,0,0,0,0,0,0,"Kernobee - Out of Combat - Quest Credit 'A Fine Mess' (Phase 1) (No Repeat)"),
(@ENTRY,0,17,0,61,1,100,0,1,0,0,0,23,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Waypoint 1 Reached - Increment Phase (Phase 1)"),
(@ENTRY,0,18,0,1,2,100,1,14000,14000,0,0,1,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - Out of Combat - Say Line 2 (Phase 2) (No Repeat)"),
(@ENTRY,0,19,0,56,2,100,0,0,7850,0,0,59,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Waypoint Resumed - Set Run On (Phase 2)"),
(@ENTRY,0,20,0,58,2,100,0,0,7850,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Waypoint Finished - Despawn Instant (Phase 2)");
`

**Comment by tkrokli** [comment] 2017-03-03 18:40
Thanks for working on this, nice to see something being done about it. 👍

Just a couple of details needing improvements:
1. `SET @ENTRY := 7850;` and `SET @TRIGGUID := 213820;` can be moved to the top of the SQL
2. You only need 1 `SET @ENTRY := ` for the entire SQL as long as `@ENTRY` is only used to represent 1 value
3. Remove single quotation marks `' '` from integer values (numbers) in the `creature_text` query.

**Comment by offl** [comment] 2017-03-03 19:44
```sql
-- Invisible Trigger for A Fine Mess Quest
SET @TRIGGUID := 213820;
DELETE FROM `creature` WHERE `guid`=@TRIGGUID;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(@TRIGGUID,19656,90,0,0,1,1,0,0,-355.45,7.006,-152.85,2.40887,300,0,0,4121,0,0,0,0,0,0);
```
It's a hack. Something [like this](https://github.com/scriptdev2/scriptdev2/blob/4550c59d319a3535eceff9f87ee72fab046577cd/scripts/eastern_kingdoms/gnomeregan/gnomeregan.cpp#L679) looks better.

```sql
-- Kernobee Waypoint
SET @ENTRY := 7850;
DELETE FROM `waypoints` WHERE `entry` = @ENTRY;
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES 
(@ENTRY, 1, -349.3, 4.72, -152.847, "Kernobee end waypoint for quest (A Fine Mess)"),
(@ENTRY, 2, -324.6, -4.96, -152.847, "Kernobee exit waypoint for quest (A Fine Mess)");
```
I [can't understand](https://www.youtube.com/watch?v=Bv0WKTNodJI) why SD2 and you think that he should have waypoints.
```sql
-- Kernobee Text
SET @ENTRY := 7850;
DELETE FROM `creature_text` WHERE `entry` = @ENTRY;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(@ENTRY,0,0,'Thank you for rescuing me! Word of your deed will not go unnoticed.',12,0,0,0,0,0,3929,0,"Kernobee End Say 1"),
(@ENTRY,1,0,'%s cheers!',16,0,0,4,0,0,3928,0,"Kernobee End Say 2"),
(@ENTRY,2,0,'I see the exit! Hurry, hurry!',12,0,0,0,0,0,3948,0,"Kernobee End Say 3");
```
Now without apostrophes around numbers and with BroadcastTextId.

And according to [this video](https://www.youtube.com/watch?v=V5mZn3a5-vA) his events should be based on his current position.
Also maybe he should use this text before despawn.
```
%s waves goodbye to everyone.
```

**Comment by CrazyPeppers** [comment] 2017-03-03 19:54
https://www.youtube.com/watch?v=Bv0WKTNodJI
That was the video I try to base this one on.  Sorry, I was not trying to supply a hacky option. 
Thanks for cleaning it up.

**Comment by offl** [comment] 2017-03-03 20:35
>  I wasn't sure how else to get that effect without waypoints. Please let me know what you would suggest.

If ```target_type``` = 0 creature will stop following.
For example:
Start:
```sql
SELECT * FROM `smart_scripts` WHERE `action_type`=29 AND `target_type`;
```
Stop:
```sql
SELECT * FROM `smart_scripts` WHERE `action_type`=29 AND !`target_type`;
```

**Comment by CrazyPeppers** [comment] 2017-03-03 20:48
I had tried target_type = 0 already but he still continued to follow the player.  I could get it to work if I entered the invisible target's id  in the first follow action (following the player) but then he despawned too quick after completing the follow and there doesn't seem to be a variable to control that time.  
It is possible the problem is with my trinity build, it has been a few months since I updated it.  I'll try updating this weekend and seeing if that fixes the follow_complete issue.

**Comment by ZenoX92** [comment] 2018-03-05 07:44
I'm not an expert fixing escort quests, but I hope this could be of help:
```sql
-- Quest "A Fine Mess"
-- Pooling for Kernobee
SET @GUID := 213878;
SET @POOL := 1118;
DELETE FROM `creature` WHERE `guid` BETWEEN @GUID AND @GUID+6;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES
(@GUID,7850,90,0,0,1,1,0,1,-637.053,101.836,-194.48,4.76023,7200,0,0,896,0,0,0,0,0,"",0),
(@GUID+1,7850,90,0,0,1,1,0,1,-577.696,28.5626,-197.735,4.76023,7200,0,0,896,0,0,0,0,0,"",0),
(@GUID+2,7850,90,0,0,1,1,0,1,-618.832,153.15,-199.654,6.25451,7200,0,0,896,0,0,0,0,0,"",0),
(@GUID+3,7850,90,0,0,1,1,0,1,-600.079,15.9729,-179.679,5.47311,7200,0,0,896,0,0,0,0,0,"",0),
(@GUID+4,7850,90,0,0,1,1,0,1,-540.499,21.528,-179.737,1.53634,7200,0,0,896,0,0,0,0,0,"",0),
(@GUID+5,7850,90,0,0,1,1,0,1,-533.081,34.7292,-199.0739,1.89563,7200,0,0,896,0,0,0,0,0,"",0),
(@GUID+6,7850,90,0,0,1,1,0,1,-621.389,51.785,-199.647,5.47311,7200,0,0,896,0,0,0,0,0,"",0);

DELETE FROM `pool_template` WHERE `entry`=@POOL;
INSERT INTO `pool_template` (`entry`, `max_limit`, `description`) VALUES
(@POOL,1,"Kernobee");

DELETE FROM `pool_creature` WHERE `pool_entry`=@POOL;
INSERT INTO `pool_creature` (`guid`, `pool_entry`, `chance`, `description`) VALUES
(@GUID,@POOL,0,"Kernobee (7850) - Spawn 1"),
(@GUID+1,@POOL,0,"Kernobee (7850) - Spawn 2"),
(@GUID+2,@POOL,0,"Kernobee (7850) - Spawn 3"),
(@GUID+3,@POOL,0,"Kernobee (7850) - Spawn 4"),
(@GUID+4,@POOL,0,"Kernobee (7850) - Spawn 5"),
(@GUID+5,@POOL,0,"Kernobee (7850) - Spawn 6"),
(@GUID+6,@POOL,0,"Kernobee (7850) - Spawn 7"),
(30135,@POOL,0,"Kernobee (7850) - Spawn 8");

-- Texts
DELETE FROM `creature_text` WHERE `CreatureID` IN (7850,7897);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(7850,0,0,"I see the exit! Hurry, hurry!",12,0,100,5,0,0,3948,0,"Kernobee"),
(7850,1,0,"%s cheers!",16,0,100,4,0,0,3928,0,"Kernobee"),
(7850,2,0,"Thank you for rescuing me! Word of your deed will not go unnoticed.",12,0,100,0,0,0,3929,0,"Kernobee"),
(7850,3,0,"%s waves goodbye to everyone.",16,0,100,3,0,0,3930,0,"Kernobee"),
(7850,4,0,"Uh oh....",12,0,100,0,0,0,3953,0,"Kernobee"),
(7850,5,0,"Get me out of here!",12,0,100,5,0,0,3881,0,"Kernobee"),
(7897,0,0,"%s activates!",14,0,100,0,0,0,3926,0,"Alarm-a-bomb 2600"),
(7897,1,0,"Self-destruct sequence activated.",14,0,100,0,0,0,3927,0,"Alarm-a-bomb 2600"),
(7897,2,0,"Anti-escape countermeasures activated. Self-destruct in t-minus 20 seconds....",14,0,100,0,0,0,3949,0,"Alarm-a-bomb 2600"),
(7897,3,0,"Alarm-a-bomb unit 2600 has failed. Self-destruct override [ACTIVE]. Cooldown [ACTIVE].",14,0,100,0,0,0,3950,0,"Alarm-a-bomb 2600");

-- Kernobee
UPDATE `creature_addon` SET `bytes1`=0 WHERE `guid`=30135;

UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=7850;
DELETE FROM `smart_scripts` WHERE `entryorguid`=7850 AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid`=785000 AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(7850,0,0,1,19,0,100,0,2904,0,0,0,29,2,180,0,0,0,0,7,0,0,0,0,0,0,0,"Kernobee - On Quest 'A Fine Mess' Taken - Start Follow Player"),
(7850,0,1,2,61,0,100,0,0,0,0,0,64,1,0,0,0,0,0,16,0,0,0,0,0,0,0,"Kernobee - On Quest 'Rescue From Jaedenar' Taken - Store Targetlist"),
(7850,0,2,3,61,0,100,0,0,0,0,0,91,7,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Quest 'Rescue From Jaedenar' Taken - Remove Flag Standstate 'Dead'"),
(7850,0,3,4,61,0,100,0,0,0,0,0,83,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Quest 'Rescue From Jaedenar' Taken - Remove Npc Flag Questgiver"),
(7850,0,4,5,61,0,100,0,0,0,0,0,19,768,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Quest 'Rescue From Jaedenar' Taken - Remove Unit Flag 'Immune To NPCs' & 'Immune To Players'"),
(7850,0,5,6,61,0,100,0,0,0,0,0,2,250,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Quest 'Rescue From Jaedenar' Taken - Set Faction 250"),
(7850,0,6,7,61,0,100,0,0,0,0,0,1,5,0,0,0,0,0,12,1,0,0,0,0,0,0,"Kernobee - On Quest 'Rescue From Jaedenar' Taken - Say Line 5"),
(7850,0,7,0,61,0,100,0,0,0,0,0,45,1,1,0,0,0,0,10,30134,7897,0,0,0,0,0,"Kernobee - On Quest 'Rescue From Jaedenar' Taken - Set Data to Alarm-a-bomb 2600"),
(7850,0,8,0,6,0,100,0,0,0,0,0,6,2904,0,0,0,0,0,12,1,0,0,0,0,0,0,"Kernobee - On Death - Fail Quest 'A Fine Mess'"),
(7850,0,9,0,11,0,100,0,0,0,0,0,90,7,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Respawn - Add Flag Standstate 'Dead'"),
(7850,0,10,11,38,0,100,1,1,1,0,0,1,0,0,0,0,0,0,12,1,0,0,0,0,0,0,"Kernobee - On Data Set - Say Line 0"),
(7850,0,11,12,61,0,100,0,0,0,0,0,29,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Data Set - Stop Follow"),
(7850,0,12,13,61,0,100,0,0,0,0,0,69,0,0,0,0,0,0,8,0,0,0,-337.215,-0.165544,-152.847,0,"Kernobee - On Data Set - Move to Position"),
(7850,0,13,0,61,0,100,0,0,0,0,0,80,785000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Data Set - Run Script"),
(785000,9,0,0,0,0,100,0,11000,11000,0,0,15,2904,0,0,0,0,0,12,1,0,0,0,0,0,0,"Kernobee - On Script - Quest Credit 'A Fine Mess'"),
(785000,9,1,0,0,0,100,0,0,0,0,0,45,3,3,0,0,0,0,19,7897,0,0,0,0,0,0,"Kernobee - On Script - Set Data to Alarm-a-bomb 2600"),
(785000,9,2,0,0,0,100,0,500,500,0,0,1,1,0,0,0,0,0,12,1,0,0,0,0,0,0,"Kernobee - On Script - Say Line 1"),
(785000,9,3,0,0,0,100,0,4000,4000,0,0,66,0,0,0,0,0,0,12,1,0,0,0,0,0,0,"Kernobee - On Script - Set Orientation"),
(785000,9,4,0,0,0,100,0,1000,1000,0,0,1,2,0,0,0,0,0,12,1,0,0,0,0,0,0,"Kernobee - On Script - Say Line 2"),
(785000,9,5,0,0,0,100,0,5000,5000,0,0,1,3,0,0,0,0,0,12,1,0,0,0,0,0,0,"Kernobee - On Script - Say Line 3"),
(785000,9,6,0,0,0,100,0,3000,3000,0,0,69,0,0,0,0,0,0,8,0,0,0,-297.319,-7.321,-152.849,0,"Kernobee - On Script - Move to Position"),
(785000,9,7,0,0,0,100,0,2000,2000,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kernobee - On Script - Despawn");

-- Alarm-a-bomb 2600
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=7897;
DELETE FROM `smart_scripts` WHERE `entryorguid`=7897 AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (789700,789701) AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(7897,0,0,0,38,0,100,0,1,1,0,0,80,789700,2,0,0,0,0,1,0,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Data Set - Run Script"),
(7897,0,1,0,38,0,100,1,1,1,0,0,29,2,270,0,0,0,0,19,7850,200,0,0,0,0,0,"Alarm-a-bomb 2600 - On Data Set - Start Follow Kernobee"),
(7897,0,2,0,38,1,100,1,2,2,0,0,45,1,1,0,0,0,0,19,7850,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Data Set - Set Data to Kernobee (Phase 1)"),
(7897,0,3,0,38,1,100,1,3,3,0,0,80,789701,2,0,0,0,0,1,0,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Data Set - Run Script (Phase 1)"),
(789700,9,0,0,0,0,100,0,0,0,0,0,22,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Script - Set Event Phase 1"),
(789700,9,1,0,0,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Script - Say Line 0"),
(789700,9,2,0,0,0,100,0,4000,4000,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Script - Say Line 1"),
(789700,9,3,0,0,0,100,0,276000,276000,0,0,1,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Script - Say Line 2"),
(789700,9,4,0,0,0,100,0,6000,6000,0,0,1,4,0,0,0,0,0,19,7850,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Script - Say Line 4 (Kernobee)"),
(789700,9,5,0,0,0,100,0,14000,14000,0,0,11,9874,0,0,0,0,0,1,0,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Script - Cast 'Self Destruct'"),
(789700,9,6,0,0,0,100,0,500,500,0,0,51,0,0,0,0,0,0,19,7850,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Script - Kill Kernobee"),
(789700,9,7,0,0,0,100,0,0,0,0,0,37,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Script - Kill Self"),
(789701,9,0,0,0,0,100,0,0,0,0,0,103,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Script - Set Rooted On"),
(789701,9,1,0,0,0,100,0,0,0,0,0,1,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Script - Say Line 3"),
(789701,9,2,0,0,0,100,0,12000,12000,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Alarm-a-bomb 2600 - On Script - Despawn");

-- Areatrigger
DELETE FROM `areatrigger_scripts` WHERE `entry`=1105;
INSERT INTO `areatrigger_scripts` (`entry`, `ScriptName`) VALUES
(1105,"SmartTrigger");

DELETE FROM `smart_scripts` WHERE `entryorguid`=1105 AND `source_type`=2;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(1105,2,0,0,46,0,100,0,0,0,0,0,45,2,2,0,0,0,0,10,30134,7897,0,0,0,0,0,"Areatrigger - On Trigger - Set Data to Alarm-a-bomb 2600");

**Comment by tkrokli** [comment] 2018-03-05 10:50
Cosmetic detail: when `@GUID` is used in an increment list of GUIDs, it is common to use `@GUID+0` for the first entry, to make the list counting more obvious as well as to keep column alignment somewhat coherent.

I have not had time to test this yet, but it looks promising at first glance.

**Comment by Killyana** [comment] 2018-03-06 19:28
Cannot find any source about Kernobee multiple spawn positions.

**Comment by ZenoX92** [comment] 2018-03-06 20:16
Here there is a comment referring that Kernobee is not always in the same position. (5th comment)
http://www.wowhead.com/quest=2904/a-fine-mess

I got the spawns from an old mangos repack.

**Comment by Killyana** [comment] 2018-03-06 20:23
Yes, it explains why wowhead shows 5 spawn positions

**Closed** 2018-03-06 21:07 UTC
Labels: Branch-3.3.5a, Comp-Database, Feedback-PatchFix, Sub-Quests, Sub-Waypoints
