### ISSUE TITLE
Build error - OpenSSL CRYPTO

### ISSUE THREAD

**Issue by Gooyeth** [TrinityCore/TrinityCore#21724] opened 2018-03-28 06:02 UTC
**Description:**

I have compiled in clean, without TOOLS, Release.

 **OpenSSL 1.1.0f 25 May 2017**

![imagen](https://user-images.githubusercontent.com/566327/38011368-6340ca9c-321a-11e8-88bb-0920c12f3eb7.png)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** f39919ca8c323e5f0005b29a49ff9d5b8c5fd96b

**Operating system:** Windows 10

**Comment by Artamedes** [comment] 2018-03-28 14:09
OpenSSL = 1.0.x 
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977296/Windows+Requirements

**Comment by Shauren** [comment] 2018-03-28 14:11
100% sure you fucked up cmake step

**Comment by shamage** [comment] 2018-03-28 14:28
Something very similar I already had - I suggest checking the OpenSSL and CMake library as well as its configuration

**Comment by Gooyeth** [comment] 2018-03-28 15:09
@Artamedes: It is supported https://github.com/TrinityCore/TrinityCore/commit/efef6b5e36a8cd8eca023b8aa6a5d8cbd532ca68
@Shauren: I have been working since the support for OpenSSL 1.1 was added, but I had not cleaned the cmake, now I have started from zero and it shows me the error.

**Comment by Gooyeth** [comment] 2018-03-28 18:47
Using Cmake 3.8.2 also shows error.

**Comment by Gooyeth** [comment] 2018-03-28 18:55
@Shauren: The OpenSSL headers is locating me in another site:

**Found OpenSSL library:** optimized;C:/OpenSSL-Win64/lib/VC/libssl64MD.lib;C:/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/OpenSSL-Win64/lib/VC/libssl64MDd.lib;C:/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib
**Found OpenSSL headers:** C:/Program Files/**_Anaconda3_**/Library/include

Possible error

**Comment by tkrokli** [comment] 2018-03-28 19:16
For comparison, a working Windows 10 OpenSSL 1.0.2 installation looks like this in CMake 3.10.1:

Found OpenSSL library: optimized;C:/OpenSSL-Win64/lib/VC/ssleay32MD.lib;C:/OpenSSL-Win64/lib/VC/libeay32MD.lib;debug;C:/OpenSSL-Win64/lib/VC/ssleay32MDd.lib;C:/OpenSSL-Win64/lib/VC/libeay32MDd.lib
Found OpenSSL headers: C:/OpenSSL-Win64/include

Looks like you got OpenSSL confused with Anaconda3 Libs there.

**Comment by shamage** [comment] 2018-03-28 20:16
For comparison - I have a working installation Win 10 Pro, OpenSSL 1.0.2n v CMake 3.10.2 
![ashampoo_snap_2018 03 28_22h11m48s_001_](https://user-images.githubusercontent.com/7515044/38053835-6b33b866-32d5-11e8-92eb-e92127005674.png)

**Comment by tkrokli** [comment] 2018-03-28 20:38
@Gooyeth : Before I close this, do you agree that this is a personal configuration issue and not an issue affecting any other users? (I know, I should have tested this myself, but other issues take up most of my time.) It would be nice if someone else could confirm your issue as something caused by the source and not only by incorrect personal software configuration.

**Comment by Gooyeth** [comment] 2018-03-28 21:54
@tkrokli: No, it is not an error of my configuration. Since the project should not take another address by default, keeping in mind that even my Windows registers have the address C:\OpenSSL-64

![imagen](https://user-images.githubusercontent.com/566327/38058253-75ee063e-329f-11e8-8737-c320c7e41be0.png)

I changed manually (which should not be) the address and now has compiled correctly.

**Comment by tkrokli** [comment] 2018-03-28 22:46
The only reason I can think of, is that Anaconda3 could have changed the OpenSSL location in your Windows Registry, but I don't know for certain (I don't have Anaconda installed on my computer).

**Comment by Aokromes** [comment] 2018-03-28 22:48
it's very likely cmake tries to search 1st openssl location on "archivos de programa" or "anaconda" than "openssl"

**Comment by Gooyeth** [comment] 2018-03-28 23:02
@tkrokli: My Windows registry, has always been the same, I have not reinstalled OpenSSL.

It would be necessary to install and test: https://repo.continuum.io/archive/ (I have 4.3)

**Comment by tkrokli** [comment] 2018-04-01 12:27
I was able to replicate your issue by ignoring how to handle installations of dependency software. I simply installed 1.1.0h (1.1.0.8) Win64 on top of the already installed 1.0.2n version and got something very similar in the build process. Unfortunately I did not save the Visual Studio output to compare it word for word with your example, but I was able to resolve my issue by completely uninstalling OpenSSL Win64, deleting the CMake cache and deleting the Build folder content, then reinstalling 1.1.0h and rebuilding CMake build files from scratch. Seems like it works OK, at least it builds without errors.

I still need to test how it works after compile is done, since the core dependency files are different. I also have not tested installing Anaconda, but I think it matters more how and when OpenSSL is installed (I followed the wiki instructions this time). I recommend that you try uninstalling OpenSSL completely, delete the build folder files and then reinstall OpenSSL 1.1.0.

**Comment by shamage** [comment] 2018-04-01 14:08
I Confirm - if there is a problem of the same or similar nature, the best solution is to remove / uninstall OpenSSL, CMake and all other related components - then reinstall and follow the wiki procedure. If you adhere to the wiki procedure, I guarantee that this will happen. I tried it 5 times. 
My assembly :  OpenSSL 1.0.2n  ( 7 Dec 2017 ) ;  Cmake 3.10.2 ; MySQL 5.7.20 ;
TrinityCore rev. 14fda395ba7f  2018-03-28  22:50:04 ( master branch ) (Win64,RelWithDebInfo, Static)

**Comment by tkrokli** [comment] 2018-04-01 22:45
Update: I installed Anaconda 5.1.0 64-bit for Windows
`Anaconda3-5.1.0-Windows-x86_64.exe` available from
- https://www.anaconda.com/download/
- https://repo.continuum.io/archive/Anaconda3-5.1.0-Windows-x86_64.exe

just an hour ago and then ran CMake + full compile w/install in VS2017 15.6.4 - no errors.

I made a note of one of the install setup details, though:

![anaconda3_510_setup](https://user-images.githubusercontent.com/4903600/38178225-633a2aaa-360e-11e8-93e7-239f806de9bb.png)

If you have added Anaconda to the system PATH environment variable by ticking the box above,
it counts as "not following the recommended installation procedure".

Based on my experience as a computer support agent for the last 20 years,
this does not look like a TrinityCore issue to me  (feel free to disagree).

**Comment by tkrokli** [comment] 2018-04-02 10:04
Please note that I am very tempted to close this issue as "user configuration issue" because it is quite possible to have Anaconda3 installed without breaking TC use of OpenSSL (I didn't even need to copy any of the OpenSSL 1.1.0h dependency files to my 3.3.5 core folder to make it work). Please provide more feedback that this issue is possible to reproduce even if wiki requirements and normal software configuration considerations are followed, to keep this issue staying open.

**Closed** 2019-01-17 02:19 UTC
Labels: Branch-3.3.5a, Feedback-WaitingResponse
