### ISSUE TITLE
[6.x] Core/Spell: Can't cast a spell after landing a flying mount.

### ISSUE THREAD

**Issue by Maibenrai** [TrinityCore/TrinityCore#15916] opened 2015-11-29 08:06 UTC
Rev. 14b8944aa255d3d9d05714f913e9554633205c7c

When you land Golden Gryphon (not tested with other flying mounts), you can't cast a spell until you have moved. It just displays " Can't do that while moving".

Short video: https://www.dropbox.com/s/99amexclze01qza/2015-11-29_09-59-46.mp4?dl=0

**Comment by Aokromes** [comment] 2016-06-15 07:47
This bug is still valid?

**Comment by tkrokli** [comment] 2016-07-02 17:50
This issue looks very similar to issue https://github.com/TrinityCore/TrinityCore/issues/6236 and related to commit https://github.com/TrinityCore/TrinityCore/commit/7c25f3cffd0c4e15a9ff08982914fd95d5cafe2f , but I will do a test on 6.x and see if the same issue (or this one) exists there (too).

**Comment by tkrokli** [comment] 2016-07-04 21:53
TrinityCore rev. d0d76abc9dc7 2016-07-04 22:52:07 +0200 (6.x branch) (Win64, Debug, Static)
TDB 6.04 plus updates up to and including `2016_06_30_00_world.sql`

Issue confirmed @ Level 60, also it is not possible to mount again after dismounting, game client shows the message **Can't do that while moving** even if the character is standing still.

I will attempt to cherry-pick the 3.3.5 commit https://github.com/TrinityCore/TrinityCore/commit/7c25f3cffd0c4e15a9ff08982914fd95d5cafe2f into my 6.x branch to see if it can solve this issue or not (just hope that attempt won't crash my server, though).

**Comment by tkrokli** [comment] 2016-07-05 00:18
TrinityCore rev. a2ac2b3cc7a0 2016-07-05 00:19:53 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_06_30_00_world.sql`

No, it is not possible to replicate the original issue (as a hunter), I am able to cast spells when sitting on a mount. The current issue is too different from the one above, so I vote for closing this.

**Comment by tkrokli** [comment] 2016-07-10 17:04
TrinityCore rev. 22d29ce0494c 2016-07-10 11:27:38 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_07_05_02_world.sql`

It is possible to reproduce the error after landing a flying mount by casting a non-attack spell like Mount, Revive Pet, Dismiss Pet (Call Pet on a previously dismissed pet works, though).

**Comment by Killyana** [comment] 2017-12-08 23:00
This is still valid?

**Comment by tkrokli** [comment] 2017-12-08 23:13
I don't have a working `master` core + 7.2.5 game client combination, so I can't test at the moment. Anyone else want to check this?

**Comment by ArcaneFox** [comment] 2017-12-09 08:56
I can't reproduce this. I can cast spells on the land and in the air too.

https://github.com/TrinityCore/TrinityCore/commit/23a66baab181b9b1c15be7fa89e881cc0b793a6f

**Closed** 2017-12-09 08:59 UTC
Labels: Branch-master, Comp-Core, Sub-Spells
