### ISSUE TITLE
Spell: Heroic Leap

### ISSUE THREAD

**Issue by NiganNi** [TrinityCore/TrinityCore#25763] opened 2020-12-24 21:47 UTC
**Description:**
Heroic Leap(class:warrior) does not work. No animation no effect.
Must:
Leap through the air toward a target location, slamming down with destructive force to deal (10% of Attack power) Physical damage to all enemies within 8 yards.

Branch(es):
master

Revision: TrinityCore rev. 5710f377e76e 2020-12-23 17:53:13 +0100 (master branch) (Win64, RelWithDebInfo, Static)

OS: Win

**Steps to reproduce the problem:**
1)Create characters warrior.
2)cmd .levelup 32.
4)Use spell Heroic Leap ( https://www.wowhead.com/spell=6544/heroic-leap )

**Comment by offl** [comment] 2020-12-24 22:48
Duplicate of #20000

**Closed by offl** 2020-12-24 22:48 UTC
Labels: Branch-master
