### ISSUE TITLE
Quests: Pilgrim's Bounty Cooking Quest Issues

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25669] opened 2020-11-23 04:19 UTC
**Description:**

There's an issue with the Pilgrim's Bounty cooking quests if you accept them in bulk as you travel to the cities.
Example the Pumpkin Pie is required for 2 quests; Easy As Pie and Pumpkin Pie:
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=44836#objective-of-quest
1) https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=14054
2) https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=14024

If you cook up all 25 (5+20) when you get your pumpkins, you can only turn in 1 of the quests. 

I think the stuffing is the other example.

<details>

![image](https://user-images.githubusercontent.com/66294837/99928396-0a3fc980-2d9d-11eb-89ff-b3ac30e3555b.png)

</details>

You have to hand in 1 quest first then cook the second batch for it to work.

<details>

![image](https://user-images.githubusercontent.com/66294837/99928460-5ab72700-2d9d-11eb-8925-b59fa3135949.png)

</details>

**Expected behaviour:**

Quests should be detecting the item count correctly and both quests should be able to be completed without having to do each one separately.

**Steps to reproduce the problem:**

1. Accept all/as many of the quests as you go to each of the cities for ingredients
2. For any of the quests that use the same ingredients - 1 will be for 5 (Seasonal?) and 1 will be for 20 (Daily?)
3. Cook all 25 ingredients
4. Hand in first quest 
5. Hand in second quest - you wont be able to

Workaround: Make another batch for the required number - and quest can be turned in

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

cc82879 2020-11-18 20:09:34 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:** 

Windows 7 x64

**Comment by offl** [comment] 2020-11-23 04:38
Duplicate of #25603

**Closed by offl** 2020-11-23 04:38 UTC
Labels: Branch-3.3.5a
