### ISSUE TITLE
DB/Spells: Spells no longer requiring caster to be behind target

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19736] opened 2017-05-10 03:34 UTC
**Description:**

Spell "Shred" (ID: 5221) it´s up-to-date one.
Spell "Shred" (ID: 5221) that cause X physical damage to the target and awards 1 combo point.
Requires "Cat Form" (ID: 768)

**Current behaviour:**

To activate the spell, the player is required to be behind the objective.

**Expected behaviour:**

It is not necessary to be behind the objective and 1 attack awards 1 combo point.

**Steps to reproduce the problem:**

1. Create a Night Elf player/Druid
2. Reach level 15
3. Select the "feral" specialization.
4. Activate the spell "Shred".

**Branch(es):** Master

**TC rev. hash/commit:** 7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  720.00 + updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=5221/shred

**Comment by DoctorKraft** [comment] 2017-05-11 21:22
Fix
```sql
/* Remove SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET on 5221 - Shred */
DELETE FROM `spell_custom_attr` WHERE `entry` = 5221;
```

**Comment by HannibalRoG** [comment] 2017-05-11 21:24
Thanks @DoctorKraft i will tested today.

**Comment by HannibalRoG** [comment] 2017-05-11 22:59
Yes, that solved the problem.

**Comment by HannibalRoG** [comment] 2017-05-12 01:33
Somebody labeled this with Feedback-PatchFix, please.

**Comment by tkrokli** [comment] 2017-05-12 10:24
http://www.wowhead.com/spell=5221/shred
https://trinitycore.atlassian.net/wiki/display/tc/spell_custom_attr#spell_custom_attr-attributes

The TC source is possibly using old info for Shred, from before 6.x (WoD).

**[Patch 6.0.2](https://wow.gamepedia.com/Patch_6.0.2) (2014-10-14):** Now available for all druid specializations. No longer has behind enemy position requirement. Now deals 400% damage.
- https://wow.gamepedia.com/Shred#Patches_and_hotfixes

Druid:  [[Shred]](https://wow.gamepedia.com/Shred) no longer requires the druid to be behind the target.
- https://wow.gamepedia.com/Patch_6.0.2#Facing_requirements

**Comment by DoctorKraft** [comment] 2017-05-12 11:15
@tkrokli Yes, it's exactly this

**Comment by tkrokli** [comment] 2017-05-12 11:26
Very well. If there are any other issues opened by @HannibalRoG and the problem is similar (TC source using old info), please document the changes like I did above to save time for other TrinityCore devs wanting to know if suggested changes are valid.

**Comment by Keader** [comment] 2017-05-12 11:56
@tkrokli if is valid, merge it :)

**Comment by DoctorKraft** [comment] 2017-05-12 12:24
Full list of spell with custom attributes deprecated
```sql
-- Remove SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET from Backstab (53)
DELETE FROM `spell_custom_attr` WHERE `entry` = 53;
-- Remove SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET from Garrote (703)
DELETE FROM `spell_custom_attr` WHERE `entry` = 703;
-- Remove SPELL_ATTR0_CU_REQ_TARGET_FACING_CASTER from Gouge (1776)
DELETE FROM `spell_custom_attr` WHERE `entry` = 1776;
-- Remove SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET from Ambush (8676)
DELETE FROM `spell_custom_attr` WHERE `entry` = 8676;
-- Remove SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET from Shred (5221)
DELETE FROM `spell_custom_attr` WHERE `entry` = 5221;
```

**Comment by tkrokli** [comment] 2017-05-12 13:08
Very well, if those spells can be documented from change logs in the patch pages or spell pages, it should be valid.
The SQL can be shortened a bit without missing any of the existing documentation, like this:
```sql
-- Remove SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET from Backstab (53), Garrote (703), Shred (5221), Ambush (8676)
DELETE FROM `spell_custom_attr` WHERE `entry` IN (53, 703, 5221, 8676);

-- Remove SPELL_ATTR0_CU_REQ_TARGET_FACING_CASTER from Gouge (1776)
DELETE FROM `spell_custom_attr` WHERE `entry` = 1776;
```

**Comment by tkrokli** [comment] 2017-05-12 14:01
Documentation on https://wow.gamepedia.com :

[[Backstab]:](https://wow.gamepedia.com/Backstab#Patches_and_hotfixes)
**[Patch 6.0.2](https://wow.gamepedia.com/Patch_6.0.2) (2014-10-14):** Backstab can now be used on either side of the target, in addition to behind the target. (See also: [facing requirements](https://wow.gamepedia.com/Patch_6.0.2#Facing_requirements))

[[Garrote]:](https://wow.gamepedia.com/Garrote#Patches_and_hotfixes)
**[Patch 5.0.4](https://wow.gamepedia.com/Patch_5.0.4) (2012-08-28):** No longer requires the rogue to be behind the target.

[[Shred]:](https://wow.gamepedia.com/Shred#Patches_and_hotfixes)
**[Patch 6.0.2](https://wow.gamepedia.com/Patch_6.0.2) (2014-10-14):** Now available for all druid specializations. No longer has behind enemy position requirement. Now deals 400% damage.

[[Ambush]:](https://wow.gamepedia.com/Ambush#Patch_changes)
**[Patch 6.0.2](https://wow.gamepedia.com/Patch_6.0.2) (2014-10-14):** No longer requires the rogue to be behind the target.
[[Find Weakness]](https://wow.gamepedia.com/Find_Weakness) effects have been merged into baseline Ambush,  [[Garrote]](https://wow.gamepedia.com/Garrote), and  [[Cheap Shot]](https://wow.gamepedia.com/Cheap_Shot) for Subtlety rogues.

[[Gouge]:](url)
**[Legion Patch 7.0.3](https://wow.gamepedia.com/Patch_7.0.3) (2016-07-19):** Now available only to Outlaw and awards 1 combo point. No longer requires the target to face the rogue.
_Facing requirement need to be confirmed._

http://www.wowhead.com/spell=1776/gouge#changelog
"Target must be facing you." removed from the wowhead description in patch 7.0.1 (Fri Feb 12 2016) Build 20740

**Closed** 2017-05-12 18:25 UTC
Labels: Branch-master, Comp-Database, Feedback-PatchFix, Sub-Spells

**Comment by ariel-** [comment] 2017-05-12 18:40
> Backstab can now be used on either side of the target, in addition to behind the target.

It just opens up the angle, but you must still be behind

**Comment by tkrokli** [comment] 2017-05-12 19:32
> It just opens up the angle, but you must still be behind

OK, so it was wrong to remove that spell, I take it. But does that behaviour need to be scripted, or is it supported directly by the game client / dbc info with the spell being present in `spell_custom_attr` ?

**Comment by DoctorKraft** [comment] 2017-05-12 20:08
@ariel-  Hm no, are you sure ? Because in patch 7.0.1 Build 20740 the facing requirement it's totally removed, need only one spell script for add extra damage if player is behind target

**Comment by ariel-** [comment] 2017-05-12 20:22
I do not know, admittedly, but there's clearly a distinct wording on it ("can now be used on _either side of the target_, in addition to behind the target" instead of "no longer requires the druid to be behind the target"

**Comment by DoctorKraft** [comment] 2017-05-12 20:29
@ariel- ah yes but this changelog is valable for Patch 6.0.2 
In 7.0.1 it's removed, check this http://www.wowhead.com/spell=53/backstab#changelog

**Comment by tkrokli** [comment] 2017-05-12 21:12
Interesting to see that the new description from patch 7.0.1 says "Damage increased by 30% when behind your target.".
Also interesting to notice the number of effects (1-4):
Effect # 4	Dummy
Value: 30
Server-side script

**Comment by DoctorKraft** [comment] 2017-05-12 21:22
> need only one spell script for add extra damage if player is behind target

Yeah, it's what I was talking about. We can script after with one spellscript, it's easy
But no requirement for facing are needed now
