### ISSUE TITLE
[6.x] hunter bug

### ISSUE THREAD

**Issue by deadmanevil** [TrinityCore/TrinityCore#15750] opened 2015-10-21 06:01 UTC
bars the action of hunter pets are not bug out or not are activated
c85647e6999b7717ae27a2d59ecd7c904e792992

**Comment by Rushor** [comment] 2015-10-21 08:39
duplicate of https://github.com/TrinityCore/TrinityCore/issues/14794

**Closed by Rushor** 2015-10-21 08:39 UTC
