### ISSUE TITLE
ins ulduar boss_razorscale and boss_flame_leviathan bug

### ISSUE THREAD

**Issue by irajviky** [TrinityCore/TrinityCore#14058] opened 2015-02-07 13:05 UTC
instance ulduar boss razor harpoon is not use and respawn
instance ulduar boss flame is not combat

**Comment by Nyeriah** [comment] 2015-02-07 14:22
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

And duplicate of https://github.com/TrinityCore/TrinityCore/issues/13056

**Closed by Nyeriah** 2015-02-07 14:22 UTC
