### ISSUE TITLE
[3.3.5] Problems with EscortAI

### ISSUE THREAD

**Issue by Tonghost** [TrinityCore/TrinityCore#18401] opened 2016-12-03 21:18 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** After 28050f338dfc6 some quests works strange. For example 

- http://www.wowhead.com/quest=12701 (the mine car is standing still)
- http://www.wowhead.com/quest=12801 (Highlord Darion Mograine randomly stops working after battle or after charging to Lich King (spell 53679)) The Light of dawn

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  0df0cb30ca9d

**TDB version:**  335.62

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crash log with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by joshwhedon** [comment] 2016-12-04 03:58
Issues are occuring with Arthas in the Culling of Stratholme too.

**Comment by el-druida** [comment] 2016-12-05 11:14
Also with npc 7998 in gnomeran... the whole problem is caused by "the smooth movement" implementation

**Comment by robinsch** [comment] 2016-12-05 12:20
The defias traitor is also super weird after smooth movement

**Comment by Killyana** [comment] 2016-12-05 12:35
@Riztazz can you take a look to this issue?

**Comment by Rushor** [comment] 2016-12-05 12:51
http://wotlk.openwow.com/npc=467
http://wotlk.openwow.com/quest=155

as mentioned in the issue, if you accept the escortquest, the creature will run with speed (30) up in the air and despawns after some time, because the player is then too far away.

This behaviour is always the same with escortquests currently. Moreover the creature no longer waits if it has script_waypoint and a point with waittime > 0.

**Comment by Riztazz** [comment] 2016-12-05 13:19
Im not home till 20 december so i do not have access to my PC, i'll try to work with teamviewer but dunno how it will turn out with my potato pc ;p

**Comment by Riztazz** [comment] 2016-12-06 09:30
I do not understand what is going on, i think this is related to spline itself.

This is what happens when spline is launched 
```
TC>MoveSpline
spline Id: 999
flags:

time passed: 0
total  time: 179574
spline point Id: 1
path  point  Id: 0
mode: Linear
points count: 48
point 0 : (-10508.4, 1068, 55.2122)
point 1 : (-10508.4, 1068, 55.2111)
point 2 : (-10508.4, 1068, 55.21)
point 3 : (-10518.3, 1074.84, 53.96)
point 4 : (-10534.8, 1081.92, 49.88)
point 5 : (-10546.5, 1084.88, 50.13)
point 6 : (-10555.3, 1084.45, 45.75)
point 7 : (-10566.6, 1083.53, 42.1)
point 8 : (-10575.8, 1082.34, 39.46)
point 9 : (-10585.7, 1081.08, 37.77)
point 10 : (-10600.1, 1078.19, 36.23)
point 11 : (-10608.7, 1076.08, 35.88)
point 12 : (-10621.3, 1073, 35.4)
point 13 : (-10638.1, 1060.18, 33.61)
point 14 : (-10655.9, 1038.99, 33.48)
point 15 : (-10664.7, 1030.54, 32.7)
point 16 : (-10708.7, 1033.86, 33.32)
point 17 : (-10754.4, 1017.93, 32.79)
point 18 : (-10802.3, 1018.01, 32.16)
point 19 : (-10832.6, 1009.04, 32.71)
point 20 : (-10866.6, 1006.51, 31.71)
point 21 : (-10880, 1005.1, 32.84)
point 22 : (-10892.5, 1001.32, 34.46)
point 23 : (-10906.1, 997.11, 36.15)
point 24 : (-10922.3, 1002.23, 35.74)
point 25 : (-10936.3, 1023.38, 36.52)
point 26 : (-10933.3, 1052.61, 35.85)
point 27 : (-10940.2, 1077.66, 36.49)
point 28 : (-10957.1, 1099.33, 36.83)
point 29 : (-10956.5, 1119.9, 36.73)
point 30 : (-10939.3, 1150.75, 37.42)
point 31 : (-10915.1, 1202.09, 36.55)
point 32 : (-10892.6, 1257.03, 33.37)
point 33 : (-10891.9, 1306.66, 35.45)
point 34 : (-10896.2, 1327.86, 37.77)
point 35 : (-10906, 1368.05, 40.91)
point 36 : (-10910.2, 1389.33, 42.62)
point 37 : (-10915.4, 1417.72, 42.93)
point 38 : (-10926.4, 1421.18, 43.04)
point 39 : (-10952.3, 1421.74, 43.4)
point 40 : (-10980, 1411.38, 42.79)
point 41 : (-11006.1, 1420.47, 43.26)
point 42 : (-11022, 1450.59, 43.09)
point 43 : (-11025.4, 1491.59, 43.15)
point 44 : (-11036.1, 1508.32, 43.28)
point 45 : (-11060.7, 1526.72, 43.19)
point 46 : (-11072.8, 1527.77, 43.2)
point 47 : (-11072.8, 1527.77, 43.2)
```

everything seems okay, now this is what we can see in sniffs:
```
ServerToClient: SMSG_ON_MONSTER_MOVE (0x00DD) Length: 224 ConnIdx: 0 Time: 12/06/2016 08:35:17.047 Number: 125
GUID: Full: 0xF1300001D3000027 Type: Creature Entry: 467 Low: 39
Toggle AnimTierInTrans: false
Position: X: -10508.4 Y: 1068 Z: 55.2111
Move Ticks: 795
Spline Type: Normal (0)
Spline Flags: None (0)
Move Time: 179574
Waypoints: 45
Waypoint Endpoint: X: -11072.8 Y: 1527.77 Z: 43.2
[1] Waypoint: X: -11020.6 Y: 1068.135 Z: 55.20555
[2] Waypoint: X: -11030.35 Y: 1074.885 Z: 53.95555
[3] Waypoint: X: -10534.85 Y: 1082.135 Z: 49.70555
[4] Waypoint: X: -10546.6 Y: 1084.885 Z: 49.95555
[5] Waypoint: X: -10555.35 Y: 1084.635 Z: 45.95555
[6] Waypoint: X: -10566.6 Y: 1083.635 Z: 42.20555
[7] Waypoint: X: -10575.85 Y: 1082.385 Z: 39.70555
[8] Waypoint: X: -10585.85 Y: 1081.135 Z: 37.95555
[9] Waypoint: X: -10600.1 Y: 1078.385 Z: 36.45555
[10] Waypoint: X: -10608.85 Y: 1076.135 Z: 35.95555
[11] Waypoint: X: -10621.35 Y: 1073.135 Z: 35.45555
[12] Waypoint: X: -10638.1 Y: 1060.385 Z: 33.70555
[13] Waypoint: X: -10656.1 Y: 1551.135 Z: 33.70555
[14] Waypoint: X: -10664.85 Y: 1542.635 Z: 32.70555
[15] Waypoint: X: -10708.85 Y: 1545.885 Z: 33.45555
[16] Waypoint: X: -10754.6 Y: 1530.135 Z: 32.95555
[17] Waypoint: X: -10802.1 Y: 1530.135 Z: 32.20555
[18] Waypoint: X: -10832.6 Y: 1521.135 Z: 32.95555
[19] Waypoint: X: -10866.6 Y: 1518.635 Z: 31.95555
[20] Waypoint: X: -10879.85 Y: 1517.135 Z: 32.95555
[21] Waypoint: X: -10892.35 Y: 1513.385 Z: 34.70555
[22] Waypoint: X: -10906.1 Y: 1509.135 Z: 36.20555
[23] Waypoint: X: -10922.1 Y: 1514.385 Z: 35.95555
[24] Waypoint: X: -10936.1 Y: 1535.385 Z: 36.70555
[25] Waypoint: X: -10933.1 Y: 1052.635 Z: 35.95555
[26] Waypoint: X: -10940.1 Y: 1077.885 Z: 36.70555
[27] Waypoint: X: -10957.1 Y: 1099.385 Z: 36.95555
[28] Waypoint: X: -10956.35 Y: 1120.135 Z: 36.95555
[29] Waypoint: X: -10939.1 Y: 1150.885 Z: 37.45555
[30] Waypoint: X: -10915.1 Y: 1202.135 Z: 36.70555
[31] Waypoint: X: -10892.6 Y: 1257.135 Z: 33.45555
[32] Waypoint: X: -10891.85 Y: 1306.635 Z: 35.45555
[33] Waypoint: X: -10896.1 Y: 1327.635 Z: 37.95555
[34] Waypoint: X: -10905.85 Y: 1367.885 Z: 40.95555
[35] Waypoint: X: -10910.1 Y: 1389.135 Z: 42.70555
[36] Waypoint: X: -10915.35 Y: 1417.635 Z: 42.95555
[37] Waypoint: X: -10926.35 Y: 1421.135 Z: 43.20555
[38] Waypoint: X: -10952.1 Y: 1421.635 Z: 43.45555
[39] Waypoint: X: -10979.85 Y: 1411.135 Z: 42.95555
[40] Waypoint: X: -11006.1 Y: 1420.385 Z: 43.45555
[41] Waypoint: X: -11021.85 Y: 1450.385 Z: 43.20555
[42] Waypoint: X: -11025.35 Y: 1491.385 Z: 43.20555
[43] Waypoint: X: -11036.1 Y: 1508.135 Z: 43.45555
[44] Waypoint: X: -10548.6 Y: 1526.635 Z: 43.20555
```sql

What the heck are those points 1 and 2? they're not valid path points at all

and this is creatures path in DB:
```sql
INSERT INTO `waypoints` VALUES (467, 1, -10508.4, 1068, 55.21, '');
INSERT INTO `waypoints` VALUES (467, 2, -10518.3, 1074.84, 53.96, '');
INSERT INTO `waypoints` VALUES (467, 3, -10534.8, 1081.92, 49.88, '');
INSERT INTO `waypoints` VALUES (467, 4, -10546.5, 1084.88, 50.13, '');
INSERT INTO `waypoints` VALUES (467, 5, -10555.3, 1084.45, 45.75, '');
INSERT INTO `waypoints` VALUES (467, 6, -10566.6, 1083.53, 42.1, '');
INSERT INTO `waypoints` VALUES (467, 7, -10575.8, 1082.34, 39.46, '');
INSERT INTO `waypoints` VALUES (467, 8, -10585.7, 1081.08, 37.77, '');
INSERT INTO `waypoints` VALUES (467, 9, -10600.1, 1078.19, 36.23, '');
INSERT INTO `waypoints` VALUES (467, 10, -10608.7, 1076.08, 35.88, '');
INSERT INTO `waypoints` VALUES (467, 11, -10621.3, 1073, 35.4, '');
INSERT INTO `waypoints` VALUES (467, 12, -10638.1, 1060.18, 33.61, '');
INSERT INTO `waypoints` VALUES (467, 13, -10655.9, 1038.99, 33.48, '');
INSERT INTO `waypoints` VALUES (467, 14, -10664.7, 1030.54, 32.7, '');
INSERT INTO `waypoints` VALUES (467, 15, -10708.7, 1033.86, 33.32, '');
INSERT INTO `waypoints` VALUES (467, 16, -10754.4, 1017.93, 32.79, '');
INSERT INTO `waypoints` VALUES (467, 17, -10802.3, 1018.01, 32.16, '');
INSERT INTO `waypoints` VALUES (467, 18, -10832.6, 1009.04, 32.71, '');
INSERT INTO `waypoints` VALUES (467, 19, -10866.6, 1006.51, 31.71, '');
INSERT INTO `waypoints` VALUES (467, 20, -10880, 1005.1, 32.84, '');
INSERT INTO `waypoints` VALUES (467, 21, -10892.5, 1001.32, 34.46, '');
INSERT INTO `waypoints` VALUES (467, 22, -10906.1, 997.11, 36.15, '');
INSERT INTO `waypoints` VALUES (467, 23, -10922.3, 1002.23, 35.74, '');
INSERT INTO `waypoints` VALUES (467, 24, -10936.3, 1023.38, 36.52, '');
INSERT INTO `waypoints` VALUES (467, 25, -10933.3, 1052.61, 35.85, '');
INSERT INTO `waypoints` VALUES (467, 26, -10940.2, 1077.66, 36.49, '');
INSERT INTO `waypoints` VALUES (467, 27, -10957.1, 1099.33, 36.83, '');
INSERT INTO `waypoints` VALUES (467, 28, -10956.5, 1119.9, 36.73, '');
INSERT INTO `waypoints` VALUES (467, 29, -10939.3, 1150.75, 37.42, '');
INSERT INTO `waypoints` VALUES (467, 30, -10915.1, 1202.09, 36.55, '');
INSERT INTO `waypoints` VALUES (467, 31, -10892.6, 1257.03, 33.37, '');
INSERT INTO `waypoints` VALUES (467, 32, -10891.9, 1306.66, 35.45, '');
INSERT INTO `waypoints` VALUES (467, 33, -10896.2, 1327.86, 37.77, '');
INSERT INTO `waypoints` VALUES (467, 34, -10906, 1368.05, 40.91, '');
INSERT INTO `waypoints` VALUES (467, 35, -10910.2, 1389.33, 42.62, '');
INSERT INTO `waypoints` VALUES (467, 36, -10915.4, 1417.72, 42.93, '');
INSERT INTO `waypoints` VALUES (467, 37, -10926.4, 1421.18, 43.04, 'walk here and say');
INSERT INTO `waypoints` VALUES (467, 38, -10952.3, 1421.74, 43.4, '');
INSERT INTO `waypoints` VALUES (467, 39, -10980, 1411.38, 42.79, '');
INSERT INTO `waypoints` VALUES (467, 40, -11006.1, 1420.47, 43.26, '');
INSERT INTO `waypoints` VALUES (467, 41, -11022, 1450.59, 43.09, '');
INSERT INTO `waypoints` VALUES (467, 42, -11025.4, 1491.59, 43.15, '');
INSERT INTO `waypoints` VALUES (467, 43, -11036.1, 1508.32, 43.28, '');
INSERT INTO `waypoints` VALUES (467, 44, -11060.7, 1526.72, 43.19, '');
INSERT INTO `waypoints` VALUES (467, 45, -11072.8, 1527.77, 43.2, 'say and quest credit');
```

Im clueless what the hell is going on, if we limit creatures path to 20 points (creature 467) everything works fine :/ Maybe @Shauren or @jackpoz got a clue, because i sure dont have one and i dont understand splines at all ;p I'll move to escortAI (scripts) and see whats going on there now

**Comment by Shauren** [comment] 2016-12-06 10:06
@Riztazz pointing you to the debugger first.

**Comment by Riztazz** [comment] 2016-12-06 11:59
@Rushor 

You said
"This behaviour is always the same with escort quests currently."
Please give me other examples if you can, cant find anything else that behaves like that and i need more data;p

**Comment by Rushor** [comment] 2016-12-06 12:47
@Riztazz try it with the quest from http://wotlk.openwow.com/npc=3584

**Comment by Riztazz** [comment] 2016-12-06 13:32
@Rushor anything in outland and above maybe?

I did debug it shauren and everything looks fine up to this point https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/Spline/MoveSplineInit.cpp#L127

So somewhere in here https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/Spline/MovementPacketBuilder.cpp#L111 has to transform those points, but its only for some creatures and like i said before, if i limit the path size in WaypointMovementGenerator it seems to work fine, still clueless;p

**Comment by el-druida** [comment] 2016-12-06 14:53
@Riztazz try with creature 7998 in gnomeran, she summons the first wave of mobs, gets in combat and then she stucks.

**Comment by jackpoz** [comment] 2016-12-06 16:19
_clicks on "Unsubscribe" after getting **@**'ed_

**Comment by xinef1** [comment] 2016-12-13 22:44
@Riztazz 
The problem comes from packing too distant points in one movement packet for linear spline (without catmull interpolation flag, so only affects walking units) if you check how the packet for linear movement is created you will notice that values are passed as offsets to the middle point of the path (middle is calculated as a point between first and last one - https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/Spline/MovementPacketBuilder.cpp#L108). As a side note, the parser probably reverses this process so you see full coordinates and not offsets.

You have to pass 3 offsets (x, y, z) on 32 bits which gives that the offset should be no greater than 2^11-1 or 2^10-1 for one coordinate (z in this case), however it cannot be greater than 2^9-1 and 2^8-1 respectively. If you check how the appendPackXYZ function works, you will notice that passed offsets are multiplied by 4, thus you have to reduce the initial offsets to 2^9-1 and 2^8-1 respectively. Otherwise the value will just overflow and some random junk will be sent to client which actually happens and you observe this as an unit dash in random direction with super speed (much larger distance has to be covered in same amount of time). You have two options:
* reduce path packing to flying units only
* ensure that for linear path no offsets greater than 2^9-1 will appear on this path

If you choose second option you will have to ensure that no offset is greater than 2^9-1 / 2^8-1. You may use following code from the shitcore as a reference.

```c++
void SmartAI::GenerateWayPointArray(Movement::PointsArray* points)
{
    if (!mWayPoints || mWayPoints->empty())
        return;

    // Flying unit, just fill array
    if (me->m_movementInfo.HasMovementFlag((MovementFlags)(MOVEMENTFLAG_CAN_FLY|MOVEMENTFLAG_DISABLE_GRAVITY)))
    {
        // xinef: first point in vector is unit real position
        points->clear();
        points->push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
        uint32 wpCounter = mCurrentWPID;
        WPPath::const_iterator itr;
        while ((itr = mWayPoints->find(wpCounter++)) != mWayPoints->end())
        {
            WayPoint* wp = (*itr).second;
            points->push_back(G3D::Vector3(wp->x, wp->y, wp->z));
        }
    }
    else
    {
        for (float size = 1.0f; size; size *= 0.5f)
        {
            std::vector<G3D::Vector3> pVector;
            // xinef: first point in vector is unit real position
            pVector.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
            uint32 length = (mWayPoints->size() - mCurrentWPID)*size;

            uint32 cnt = 0;
            uint32 wpCounter = mCurrentWPID;
            WPPath::const_iterator itr;
            while ((itr = mWayPoints->find(wpCounter++)) != mWayPoints->end() && cnt++ <= length)
            {
                WayPoint* wp = (*itr).second;
                pVector.push_back(G3D::Vector3(wp->x, wp->y, wp->z));
            }

            if (pVector.size() > 2) // more than source + dest
            {
                G3D::Vector3 middle = (pVector[0] + pVector[pVector.size()-1]) / 2.f;
                G3D::Vector3 offset;

                bool continueLoop = false;
                for (uint32 i = 1; i < pVector.size()-1; ++i)
                {
                    offset = middle - pVector[i];
                    if (fabs(offset.x) >= 0xFF || fabs(offset.y) >= 0xFF || fabs(offset.z) >= 0x7F)
                    {
                        // offset is too big, split points
                        continueLoop = true;
                        break;
                    }
                }
                if (continueLoop)
                    continue;
            }
            // everything ok
            *points = pVector;
            break;
        }
    }
}
```

This change also brings a few problems. Especially for events and scripting points actions. If you send whole path, and at some point, lets say x, use StopMoving, the unit won't stop at point x, but somewhere between x and end of the path (depending on the latency and so on, usually just a bit further yet in most cases facing in wrong direction, eg. shifted by 180° because it started moving to the next point which is behind), this is a visual on the client only, as the core wont update unit position anymore. The easiest solution is to create a stopmoving that not only stops current spline, but creates new one that stops at point x. This will result in a small jump on client, but the unit will be positioned as initially you wanted it to. The proper solution would consist of creating a list of such a points and send the path up to those points which is probably not what blizzard does. I'm pretty sure it was solved in completely different approach as this is too complicated. I've written this code few years ago and would probably do it differently now.

Also creating multipoint generator is a bit more complicated. This code contains many flaws and will not work as intended. You can not depend on internal spline index counter if you assume that the spline may be altered in any way (stopped, broken into smaller parts, etc.). Let's analyze the following code of yours:
```c++
            // speed changed during path execution, calculate remaining path and launch it once more
            if (i_recalculateSpeed)
            {
                i_recalculateSpeed = false;

                if (!Stopped())
                    return StartMove(creature);
            }
            else
            {
                uint32 pointId = uint32(creature->movespline->currentPathIdx());
                if (pointId > i_currentNode)
                {
                    OnArrived(creature);
                    i_currentNode = pointId;
                    FormationMove(creature);
                }
}
```

Most notably those lines:
```c++
uint32 pointId = uint32(creature->movespline->currentPathIdx());
if (pointId > i_currentNode)
```

If by any chance the spline is interrupted and started anew (by scripted action or speed recalculation) the internal spline counter is reset to 0. Thus you cannot compare it to currentNode, you need to trace **changes** of spline internal id.

If you have other questions feel free to ask.

**Comment by akrom23** [comment] 2016-12-14 08:11
>  Most notably those lines:
> 
> uint32 pointId = uint32(creature->movespline->currentPathIdx());
> if (pointId > i_currentNode)
> If by any chance the spline is interrupted and started anew (by scripted action or speed recalculation) the internal spline counter is reset to 0. Thus you cannot compare it to currentNode, you need to trace changes of spline internal id.

@xinef1: If waypoint move is reinitialized after some interrupt or sthg, ``currentPathIdx()`` is increased by ``point_Idx_offset`` set here: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp#L206

> int32 MoveSpline::currentPathIdx() const
> {
>     int32 point = point_Idx_offset + point_Idx - spline.first() + (int)Finalized();
>     if (isCyclic())
>         point = point % (spline.last()-spline.first());
>     return point;
> }

In this case, ``point_Idx_offset `` is ``i_currentNode``

**Comment by xinef1** [comment] 2016-12-14 12:06
@akrom23
True (didn't study the code thoroughly), but when I was remaking the escorts few years ago it also presented some problems (can't remember what exactly now). Maybe it is not the case anymore. Anyway there are some other errors that break escorts as you can see. I would start with checking if proper MovementInforms are called and if you can really depend on this index.

**Comment by xinef1** [comment] 2016-12-27 22:39
@Riztazz 
It's always bad to use someone else code without credits
mOOCReached, void SmartAI::AttackStart(Unit* who)

**Comment by irgc** [comment] 2016-12-27 23:54
cunfirm
Please add on pulls......

**Comment by irgc** [comment] 2016-12-29 16:58
A;dev
help to solve the problem

Last Quest area [The Light of Dawn]

We need to fix this problem.....................................

**Comment by Rushor** [comment] 2016-12-29 17:09
if it's too gamebreaking for you, revert https://github.com/TrinityCore/TrinityCore/commit/28050f338dfc66e0c40b6a3915bf96e38e0613e5 In the next days @Riztazz or @xinef1will fix the issue.

**Comment by irgc** [comment] 2016-12-30 16:42
http://www.wowhead.com/quest=12701
http://www.wowhead.com/quest=12801

tested on  TrinityCore/releases TDB 335.61/TDB 335.62
fixed.
------------------------
./We have to wait
What will the new version/.

A.DEV

**Comment by irgc** [comment] 2017-01-02 22:14
†

**Comment by starrheld** [comment] 2017-01-03 09:21
Any updates on this?

**Comment by Riztazz** [comment] 2017-01-03 09:32
I can post a hack that checks for diffrences in offsets but that probably won't be accepted, for 4.0 and higher build when something like this occurs you gotta add uncompressed spline flag.
For a proper fix we need a sniff of a creature with realllly big difference between starting point and destination to see what blizzard actually did with something like this, so if you got more creatures with that issue, i need to know which ones. Kittnz and shauren checked all those creatures posted here and sadly they do not have any sniffs of those creatures.
More information is required

**Comment by irgc** [comment] 2017-01-03 21:56
I wish the sooner the problem is resolved

Quest is an important

[the light of dawn]

**Comment by Riztazz** [comment] 2017-01-03 22:46
```diff
diff --git a/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp b/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
index 9a2db04..d54ad85 100755
--- a/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
+++ b/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
@@ -164,22 +164,55 @@ bool WaypointMovementGenerator<Creature>::StartMove(Creature* creature)
 
     float finalOrient = 0.0f;
     uint8 finalMove = WAYPOINT_MOVE_TYPE_WALK;
+    int32 currentMaxPoints = i_path->size();
+    bool pathLengthValid = false;
 
     Movement::PointsArray pathing;
-    pathing.reserve((i_path->size() - i_currentNode) + 1);
 
-    pathing.push_back(G3D::Vector3(creature->GetPositionX(), creature->GetPositionY(), creature->GetPositionZ()));
-    for (uint32 i = i_currentNode; i < i_path->size(); ++i)
+    while (!pathLengthValid)
     {
-        WaypointData const &waypoint = i_path->at(i);
+        pathing.clear();
 
-        pathing.push_back(G3D::Vector3(waypoint.x, waypoint.y, waypoint.z));
+        pathing.push_back(G3D::Vector3(creature->GetPositionX(), creature->GetPositionY(), creature->GetPositionZ()));
 
-        finalOrient = waypoint.orientation;
-        finalMove = waypoint.move_type;
+        for (int32 i = i_currentNode; i < currentMaxPoints; ++i)
+        {
+            WaypointData const& waypoint = i_path->at(i);
 
-        if (waypoint.delay)
-            break;
+            pathing.push_back(G3D::Vector3(waypoint.x, waypoint.y, waypoint.z));
+
+            finalOrient = waypoint.orientation;
+            finalMove = waypoint.move_type;
+
+            if (waypoint.delay)
+                break;
+        }
+
+        pathLengthValid = true;
+
+        if (pathing.size() > 2)
+        {
+            G3D::Vector3 middle = (pathing[0] + pathing[pathing.size() - 1]) / 2.f;
+
+            for (uint32 i = 1; i < pathing.size(); ++i)
+            {
+                G3D::Vector3 offset = middle - pathing[i];
+                if (std::fabs(offset.x) >= 0xFF || std::fabs(offset.y) >= 0xFF || std::fabs(offset.z) >= 0x7F)
+                {
+                    --currentMaxPoints;
+                    // if currentMaxPoints <= i_currentNode, then we have no more valid points in path - return immediately
+                    if (currentMaxPoints < 0 || currentMaxPoints <= int32(i_currentNode))
+                    {
+                        TC_LOG_ERROR("misc", "WaypointMovementGenerator::StartMove: creature %s (%s) has invalid point (%s), which is too far away from other points in path. Creature stops pathing!",
+                            creature->GetName().c_str(), creature->GetGUID().ToString().c_str(), pathing[i].toString().c_str());
+                        return false;
+                    }
+
+                    pathLengthValid = false;
+                    break;
+                }
+            }
+        }
     }
 
     // if we have only 1 point, only current position, we shall return

```

This is a 'hacky' way to fix it for now (monsters running away god knows where) - i have no idea how blizzard dealt with those on 3.3.5. In higher builds - cataclysm and higher we just have to set the spline to Uncompressed and everything will be fine

**Comment by irgc** [comment] 2017-01-03 22:53
Riztazz i love u .

**Comment by mazdafil** [comment] 2017-01-06 09:13
Dear developers, could you post the commit that espouse these problems? may be you cancel 28050f3?

**Comment by Rushor** [comment] 2017-01-06 09:20
revert is not an option (the fix is not totally gamebreaking) @Riztazz is already working on a solution

**Comment by Keader** [comment] 2017-01-06 11:53
I agree with Rushor, revert is only in cases that no one is working and is gamebreaking.

**Comment by mazdafil** [comment] 2017-01-06 13:16
So because so many not working quests

**Comment by irgc** [comment] 2017-01-06 13:45
:disappointed:

**Comment by Rushor** [comment] 2017-01-06 13:51
bad news everyone :(

<Rushor> work here https://github.com/TrinityCore/TrinityCore/issues/18401
<Riztazz> Rushor: no idea how to fix it on 3.3.5 without hack, dunno how blizzard does it
<Riztazz> and according to Malcrom the entire code is wrong
<Riztazz> since blizz isnt sending entire path
<Rushor> then we should revert it for now?
<Riztazz> he wants to send each point seperetly and then calculate offsets between unit position and point
<Riztazz> which would require vmap and mmap calculations in that
<Riztazz> which pretty much means dead tc
<Riztazz> since its so shit at optimization ;p
<Riztazz> yeah
<Rushor> wanna create a pr for that then?

**Comment by mazdafil** [comment] 2017-01-06 14:06
don't understand what the problem is to undo the wrong commit. canceled as 584d347 because it really was a mistake. so it is here.

**Comment by Rushor** [comment] 2017-01-06 14:17
that's what i tried to say in my last post :)

**Comment by irgc** [comment] 2017-01-06 14:18
More of  quests after this update is buged..
What to do now
Can only use the version TDB62 Release;

**Comment by mazdafil** [comment] 2017-01-06 14:31
TDB62 or 703 are they playable? when I collected the last time it did not work nachalnye quests in Northshire, not Working quests Pandaren. on TrinityCoreLegasy 4.3.4 is not working Gilneas. only 3.3.5 was healthy. already it is not working. I made checkout

**Comment by irgc** [comment] 2017-01-07 00:36
Does this problem will go away?

When resolves

on update?

**Comment by ccrs** [comment] 2017-01-07 14:46
Try again on header and report any change on the issue

**Comment by Eliminationzx** [comment] 2017-01-07 15:20
@ccrs  The problem still exists. Check [this quest.](http://www.wowhead.com/quest=12308/escape-from-silverbrook)

**Comment by xinef1** [comment] 2017-01-07 15:25
@Eliminationzx Which problem, visual run in strange direction? ccrs patch was not meant to fix this problem

**Comment by Eliminationzx** [comment] 2017-01-07 15:32
@xinef1, yes. Visual part is still bugged.

**Comment by ccrs** [comment] 2017-01-07 23:38
We can add to the list that the new system doesnt use pathfinding

**Comment by Noryad** [comment] 2017-01-08 03:31
The same problem in:
1- Icefang .go zonexy 53.128944, 65.502464, 67
2- Injured Icemaw Matriarch .go xyz 7333.873535, -2061.036621, 764.351135, 571, 1.354540

**Comment by Rushor** [comment] 2017-01-20 13:36
can be closed since https://github.com/TrinityCore/TrinityCore/pull/18888 was merged

**Comment by Aokromes** [comment] 2017-01-20 13:36
a3c6880

**Closed by Aokromes** 2017-01-20 13:36 UTC
Labels: Branch-3.3.5a, Comp-Core, Feedback-FixHack, Sub-Waypoints

**Comment by BahDumbBugs** [comment] 2017-02-02 16:31
a6acd88 commit still shows not working [The Light of Dawn]. Let me know if anything needs testing from this point moving forward on this issue. My player is parked there.

Moving on.

**Comment by azanoni** [comment] 2017-05-08 23:25
there is not fix at the moment? should be a good solution make autocomplete for this quest?

**Comment by bumbummen99** [comment] 2017-05-20 20:54
The dynspawn branch is about to be merged soon and it will fix all related issues. I would not expect any temporary solution as the source will stay blizzlike and these quests are not autocomplete on the official servers (You have to figure it out by the information available on the web to make it autocomplete on your source).
Watch the pull request's progress here:
https://github.com/TrinityCore/TrinityCore/pull/19056
