### ISSUE TITLE
[Instance] ICC Sindragosa - Ice Tomb Summon

### ISSUE THREAD

**Issue by deny70** [TrinityCore/TrinityCore#6541] opened 2012-05-17 17:32 UTC
well first off this is my first one but never mind lol.So its known sindragosa is realy screwed with the thombs......they have line of sight isues, DMG from bombs are took from all raid members :3 thanks for your time :D

**Comment by tkrokli** [comment] 2015-01-21 19:25
> @Rushor can u send me the code please? I cannot open the websites http://pastebin.com/9ywfCnUK,sorry.

I suppose you are referring to this page & code: http://pastebin.com/9ywfCnUK
(your link was broken by making ".sorry" part of your own link) Anyway, the code looks like this:
```diff
 -1335,6 +1335,13 @@
     if (!IsInMap(obj))
         return false;
 
+    // hack for ice tomb's gameobject
+    if (obj->GetTypeId() == TYPEID_UNIT)
+        if (obj->GetEntry() == 36980 /* Ice Tomb */)
+            return true;
+    if (GetTypeId() == TYPEID_UNIT)
+        if (GetEntry() == 36980 /* Ice Tomb */)
+            return true;
     float ox, oy, oz;
     obj->GetPosition(ox, oy, oz);
     return IsWithinLOS(ox, oy, oz);
```
Note: that code is tagged as a hack fix.

**Comment by D4R4** [comment] 2015-02-11 12:08
@tkrokli the hackfix worked 100% for quite some but recently with it only direct spells hit the Tomb and aoe spells like warrior's Whirwind or for example priest's mind seer deal no damage and still cant get passed the LoS check somehow, need to fix the hack fix :) working on that atm

**Comment by tkrokli** [comment] 2015-02-11 14:56
Good to hear that, @D4R4 :dragon_face: it will be nice to bring some good news to my fellow players later on. :dragon:

**Comment by D4R4** [comment] 2015-02-11 16:29
@tkrokli @Dorsch I managed to do what Dorsch said, and I must admit it is looking pretty good,

so baisically the GO doesn't spawn when the IceTomb npc is created but instead only for a friction of second it is spawned BEFORE the FrostBomb hits the gound and instantly Deleted AFTER it has done it's damage,

``_owner->CastSpell((Unit*)NULL, SPELL_FROST_BOMB, false, NULL, NULL, _sindragosaGUID);``

seems to be working with no problem, gonna post the code later today

**Comment by tkrokli** [comment] 2015-02-11 16:39
Good job! Nice to see that your investigation has paid off! :+1:

**Comment by D4R4** [comment] 2015-02-11 17:55
https://gist.github.com/D4R4/2f0fe5736eb174d60de6

This fixes the issue with IceBlock's LoS by only making them for a friction of second when the Bombs hit the ground, 
Beware it's a pretty big hackfix, but will not ruin anything else

If targets behind IceTombs in phase three shouldn't be IcyGriped use the same mechanic for it,(spawn the GO's right before the spell cast of IcyGrip and Delete them afterwards) I'm not sure folks behind the ice should be immune to IcyGrip tho...

**Comment by tkrokli** [comment] 2015-05-06 09:43
This just in: for the sake of experimenting with non-blizzlike settings while troubleshooting, try this hack:
```diff
/src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp @Line 58-61

57	57	     SPELL_BLISTERING_COLD       = 70123,
- 58		 SPELL_FROST_BEACON          = 70126,
- 59		 SPELL_ICE_TOMB_TARGET       = 69712,
- 60		 SPELL_ICE_TOMB_DUMMY        = 69675,
- 61		 SPELL_ICE_TOMB_UNTARGETABLE = 69700,
+	58	     SPELL_FROST_BEACON          = 70157,
+	59	     SPELL_ICE_TOMB_TARGET       = 70157,
+	60	     SPELL_ICE_TOMB_DUMMY        = 70157,
+	61	     SPELL_ICE_TOMB_UNTARGETABLE = 70157,
62	62	     SPELL_ICE_TOMB_DAMAGE       = 70157,
```
Yes, I know this is not blizzlike and I know this is a hack, but this is just for troubleshooting the ICC event. One of my contacts used this hack and was able to complete the event in a normal fashion with a 10 man group without issues, with these values. According to him, this is the only change in that script. Think what you want, but I see it as a possible way of testing what is going on in the event, with the script being what it currently is, otherwise.
- http://www.wowhead.com/spell=70157/ice-tomb
- http://www.wowhead.com/npc=36853/sindragosa#abilities

**Comment by Flameshot** [comment] 2015-06-03 10:23
-1335,6 +1335,13 @@
     if (!IsInMap(obj))
         return false;

+    // hack for ice tomb's gameobject
+    if (obj->GetTypeId() == TYPEID_UNIT)
+            return true;
+    if (GetTypeId() == TYPEID_UNIT)
+            return true;
     float ox, oy, oz;
     obj->GetPosition(ox, oy, oz);
     return IsWithinLOS(ox, oy, oz);

I used this since one week ago when I saw it is not working anymore but idk why.

**Comment by tkrokli** [comment] 2015-06-03 10:44
@Flameshot : Pro tip: use the markdown code **```diff** on line 1 of your post to highlight like my post.

Then add ``` below the code / above your comment text, to see your comment as normal text.

**Comment by Flameshot** [comment] 2015-06-03 11:00
I worked on an old script and changed for me to work: http://pastebin.com/wbNBmvpG

and this is the sql part: http://pastebin.com/FVdu1yJQ

**Comment by Frytiks** [comment] 2015-06-03 17:05
Also phase should start if sindragosa has lower health then 85%

**Comment by Shauren** [comment] 2015-06-03 17:29
@Frytiks no that is a myth. It has been already verified that its purely timed.

**Comment by Frytiks** [comment] 2015-06-03 18:44
@shauren then sorry :) but ice tomb should never target tank ?

**Comment by Yehonal** [comment] 2015-10-13 13:36
Hello guys

About the bug i think that it is an issue related to how TrinityCore Calculate the LOS
Seems that the LOS is calculated checking the center of an entity area instead of its perimeter
 
Said that, since the "tomb npc" has the same position of the game object that is spawned "under" it, you cannot target the npc itself

I'll show you a draw as example:

![image](https://cloud.githubusercontent.com/assets/147092/10456166/0c8bad10-71c0-11e5-9216-6e4cef4f2ad4.png)

This kind of change will fix a lot of other kind of similar bugs IMHO

**Comment by Rushor** [comment] 2015-10-29 10:29
@Frytiks what makes a tank to a tank? also how do you separate between maintank and offtank :/

**Comment by Frytiks** [comment] 2015-10-29 10:36
maintank have aggro with boss, you can code it, if no tank, then top aggro, but not blizzlike i think

**Comment by Rushor** [comment] 2015-10-30 16:45
there are serveral encounters which remove player with tankspeccs from their targetlist. in the spellscripts of sindragosa we can find a isHealer() check maybe, thsi can be added for tanks too

**Comment by Golrag** [comment] 2015-11-02 16:24
@Yehonal try this: 
```diff
diff --git a/src/server/game/Entities/Object/Object.cpp b/src/server/game/Entities/Object/Object.cpp
index e4d9e61..bf23e41 100644
--- a/src/server/game/Entities/Object/Object.cpp
+++ b/src/server/game/Entities/Object/Object.cpp
@@ -1147,7 +1147,10 @@ bool WorldObject::IsWithinLOSInMap(const WorldObject* obj) const
         return false;
 
     float ox, oy, oz;
-    obj->GetPosition(ox, oy, oz);
+    float angle = obj->GetAngle(&GetPosition());
+    ox = obj->GetPositionX() + obj->GetObjectSize() * std::cos(angle);
+    oy = obj->GetPositionY() + obj->GetObjectSize() * std::sin(angle);
+    oz = obj->GetPositionZ();
     return IsWithinLOS(ox, oy, oz);
 }
```
Won't PR it yet, don't know if it breaks something.

Note: this won't fix the icetomb being not in LoS because: 
UNIT_FIELD_COMBATREACH: 1069547520/1.5
On 6.6.2 (retail) it is UNIT_FIELD_COMBATREACH: 1086324736/6

**Comment by dixanackmad** [comment] 2016-01-30 08:54
Confirmed on: b1d0855624d1c83850fc36f5242437d7f7c1336b

**Comment by Aokromes** [comment] 2016-01-30 09:07
Test https://github.com/TrinityCore/TrinityCore/pull/15807

**Comment by Kittnz** [comment] 2016-05-26 14:54
c0cc4f7c68c65c35354e04468c2a610516243692

**Closed by Kittnz** 2016-05-26 14:54 UTC
Labels: Branch-3.3.5a, Branch-6.x, Comp-C++Script, Comp-Core, Sub-Instances, Sub-Spells

**Comment by cshaaa** [comment] 2016-05-29 02:13
well done！！
