### ISSUE TITLE
Re-Logging any class with a pet causes a Fatal Exception error

### ISSUE THREAD

**Issue by tomm7** [TrinityCore/TrinityCore#14275] opened 2015-03-01 23:14 UTC
rev. 9f27296bd226 +
DB: TDB 6.00
Re-Logging any class with a pet causes a Fatal Exception error in the client.  World server stays up, I have added the root log with everything after logging one of these classes.
http://pastebin.com/ZZk8UMWq
http://pastebin.com/YrWGjYHZ

**Comment by DDuarte** [comment] 2015-03-01 23:17
That commit rev does not exist.

Duplicate of #14135

**Closed** 2015-03-01 23:25 UTC
Labels: Branch-6.x, Comp-Core, HasBacktrace
