### ISSUE TITLE
[3.3.5a] 80% of all players kicked

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#15175] opened 2015-07-27 19:12 UTC
b574c99

I don't know how to reproduce this. I have like 300 players online, doing instances, BG's, arenas, duels, talking - doing everything. It happens once per day, maybe two times (I know that this can be an attack or something). 80% of the server players are kicked from the server and rolled back by 1-30 seconds (i have playersave set to 30 secs). Rest of them is fine (it happens totally randomly)

Is there ANY option that the server causes this? RAM? CPU? Whatever? (RAM usage isn't big, CPU too, 4 procs of 6, 6gb of 12).

There's a known issue with oversizing packets with auth/worldserver, but I don't think that's it because it just freezes wserv/auth, not kicks the players.

**Comment by MrSmite** [comment] 2015-07-27 21:45
Why are you saving the player so often? 300 players every 30 seconds seems like a lot of work, perhaps MySQL is getting overloaded from all the queries?

**Comment by Rochet2** [comment] 2015-07-27 22:03
Is the server compiled as 64 bit?

**Comment by P-Kito** [comment] 2015-07-28 00:49
Any Crashlog?

**Comment by digz6666** [comment] 2015-07-28 01:08
I think crash is happening, you should check your crashlog.

**Comment by selenir** [comment] 2015-07-28 13:47
Compiled in 64, Ubuntu 14.

It's a powerful machine, saving every 30s doesn't lag or something. And it's not a crash. When I get kicked as a GM (not always in this 80% part) I just type .server info and there's an old uptime.
But yeah, It crashes sometimes (maybe my own fixes etc).

Do you have any solution to debug the server and see a proper crashlog with 300 players online? 2 mounts ago I decided to put a Debug Mode + GDB but laggs were incredible, people didn't want to play and server didn't want to crash :D

**Comment by Aokromes** [comment] 2015-07-28 13:49
How you put server on debug mode?

**Comment by selenir** [comment] 2015-07-28 14:15
Mounts omg. Months*

Compiled it with parameters given by you and opened with GDB. 

Do you mean that it shouldn't lag?

**Comment by Smokexyz** [comment] 2015-07-28 14:16
I think if you run it in gdb it will likely cause the disconnections.

**Comment by selenir** [comment] 2015-07-28 14:19
I am not running this in Debug or GDB. I did months ago to find out what was causing crashes.

Now I am running only with Release mode and 4 of 8 cores.

I am just asking that is there any way to put a debug mode and discover a crashbug with that players online amount (with no lags).

**Comment by Smokexyz** [comment] 2015-07-28 14:23
Yes If you run it in gdb or if the program dumps a crash log every time it crashes, for gdb to read later on.

**Comment by MrSmite** [comment] 2015-07-28 22:09
> It's a powerful machine, saving every 30s doesn't lag or something

What I was getting at was mysql having a problem. Saving 300 players every 30 seconds is a lot of information and you might be choking your connections causing the server to boot everyone.

It's just a thought since there has never been a clear *mysql.ini* tutorial for Trinity. Don't know if there's anything here that might help but check it out if you have time:

[10+ Ways to Crash or Overload MySQL](https://www.percona.com/blog/2007/11/13/10-ways-to-crash-or-overload-mysql/)

**Comment by Aokromes** [comment] 2015-10-25 16:30
No one else confirmed this "bug", and no word for months, closing.

**Closed by Aokromes** 2015-10-25 16:30 UTC
Labels: Invalid-CannotReproduce
