### ISSUE TITLE
Create two characters with the same name

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#21656] opened 2018-03-17 04:57 UTC
**Description:**
When creating a character, you can duplicate it. there will be 2 players with the same name.

**Current behaviour:**
When creating a character, repeatedly press enter and click "Accept" simultaneously, you will get disconnected, log back and see 2 players created with the same name. Try a few times, seem to be quite easy to reproduce.
Each will have it's own GUID, but same name.

![wowscrnshot_031718_015424](https://user-images.githubusercontent.com/11219553/37551785-696656cc-2986-11e8-99b8-fb3429c723f4.jpg)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 282886984415

**Comment by shenhuyong** [comment] 2018-03-17 05:40
Confirm, and I can not delete these two characters until restart world server.

**Comment by Keader** [comment] 2018-03-17 11:57
Nice hahaha

**Comment by Killyana** [comment] 2018-03-17 12:02
This is an old issue, introduced before July 2017

**Comment by Shauren** [comment] 2018-03-17 13:06
async stronk?

**Comment by irgc** [comment] 2018-03-17 19:15
Why so much bug has been raised :laughing:

**Comment by ariel-** [comment] 2018-03-17 20:25
> Why so much bug and crashs has been raised 😆
all changed back on TDB62 OR TDB63 🙄

> This is an old issue, introduced before July 2017

**Comment by irgc** [comment] 2018-03-18 14:27
What time is it possible to fix this problem?
long time?

**Comment by Blackpearlwbr** [comment] 2018-03-26 01:40
Not quite sure how, but seems to be some similar issues with faction change, character customize, and so on.

**Comment by Jildor** [comment] 2018-03-26 09:16
Can be related with #20106 too??

**Comment by Shauren** [comment] 2018-03-26 09:32
no

**Comment by WildCoffee** [comment] 2018-03-28 10:32
The name field in the characters table in the character database isn't required to be unique. While it's marked as a KEY, it's just an index so it doesn't require them to be unique. Dropping the existing index and recreating it as unique then making the field unique in the creation SQL should fix it or at least make it so the second add will fail.

**Comment by Shauren** [comment] 2018-03-28 12:14
Thats a partial solution - proper one should also inform the client that name already exists

**Comment by WildCoffee** [comment] 2018-03-28 12:48
When it's legitimate it's already handled in CharacterHandler and it will return a name already in use. The problem is you can flood the server with CMSG_CHAR_CREATE by rapidly clicking Accept and hitting enter. You can get the client to send a second CMSG_CHAR_CREATE packet before the server responds to the first which I think is creating the duplicate.

```
C->S: [Player: Account: 1] [CMSG_CHAR_CREATE 0x0036 (54)]
C->S: [Player: Account: 1] [CMSG_CHAR_CREATE 0x0036 (54)]
S->C: [Player: Account: 1] [SMSG_CHAR_CREATE 0x003A (58)]
S->C: [Player: Account: 1] [SMSG_CHAR_CREATE 0x003A (58)]
``` 

I think a more complete solution would be to ignore any incoming CMSG_CHAR_CREATE packets from that account until after the server responds. For the time being, maybe enforcing on the database as a backup line of defence would be a good idea?

**Comment by irgc** [comment] 2018-04-06 22:26
Who can fix this problem?

**Closed** 2018-04-10 18:55 UTC
Labels: Branch-3.3.5a, Comp-Core, Comp-Database, Sub-Database, Sub-Player

**Comment by irgc** [comment] 2018-04-10 20:31
fixed by @Shauren
:cupid:
