### ISSUE TITLE
[3.3.5] Seal of of Righteousness - Damagecalculation

### ISSUE THREAD

**Issue by Expecto** [TrinityCore/TrinityCore#14446] opened 2015-03-25 17:46 UTC
1 - Create Paladin
2 - Use Seal of Righteousness
3 - In Seal of Righteousness indicate correct damage 21 per tick in reality damage 20 per tick...
4 - Look Screenshot: 

Patch in Kernel: Russian localization for locales_creature

http://www.imageup.ru/img293/2084250/wowscrnshot_032515_203634.jpg

Rev Hash: 9a2e9ecccc5ed4d300025f3b6d1cffc6af11265d
TDB Last Rev for 3.3.5a

**Comment by MrSmite** [comment] 2015-03-27 07:35
Shouldn't it be effected by resistances? Even low level mobs have a chance to partially resist magic.

**Comment by Nyeriah** [comment] 2015-03-27 07:36
Since when is there resistance to holy damage?

**Comment by MrSmite** [comment] 2015-03-27 07:42
There is no specific holy resistance but I've seen my Paladin's seals and judgements resisted. I never thought much of it since it doesn't happen often.

**Comment by Nyeriah** [comment] 2015-03-27 07:56
Yeah, and damage can't really be resisted ("mitigated") unless the creature has specifically resistance to the damage school. I would also assume it was something among these lines if it was a full resist but in this case it's not.

When did you get these judgment resists though? There was an ancient bug that caused druid's marks to add holy resistance to players. And also some oddity with some old bosses such a Maexna having holy resistance set, but I thought they were long gone

**Comment by Nyeriah** [comment] 2015-03-27 08:08
Anyway

```
Shanalla's Seal of Righteousness hits Defias Thug for 1 Holy.
```

At level 1 when the tooltip says it should tick for 2

**Comment by MrSmite** [comment] 2015-03-28 02:46
I don't believe NPCs are supposed to have resistances to specific schools, they simply roll a chance to resist on cast / each tick. The "no resistance for Holy" is for players so they won't resist a heal. If you do a google search for resistance and read the various wiki entries, they're inconsistent as to wether NPCs actually have a resistance stat.

The Judgement resist was a while ago but I just figured it was supposed to be a "miss" and it was being picked up wrong by the client. There are a few things the client misinterprets from the core when it comes to Lua functions.

Anyway, in this case it sounds like the core is possibly not adding spell power or some other stat in *DealDamage()*

**Comment by ariel-** [comment] 2015-04-09 19:02
I think the issue is a low-level one, but simple to correct, you see, when the spell basepoints are calculated, the core uses a naive float to int cast.

In SpellEffectInfo::CalcValue

```c++
    // base amount modification based on spell lvl vs caster lvl
    if (caster)
    {
        int32 level = int32(caster->getLevel());
        if (level > int32(_spellInfo->MaxLevel) && _spellInfo->MaxLevel > 0)
            level = int32(_spellInfo->MaxLevel);
        else if (level < int32(_spellInfo->BaseLevel))
            level = int32(_spellInfo->BaseLevel);
        level -= int32(_spellInfo->SpellLevel);
        basePoints += int32(level * basePointsPerLevel);
```

This, while working, truncates the float calculated value, instead of rounding it, so, if the damage of the seal was 1.8 (for example), this value is then truncated to 1.

Something like
```diff
-        basePoints += int32(level * basePointsPerLevel);
+        basePoints += std::lroundf(level * basePointsPerLevel);
```

Should work

**Comment by ccrs** [comment] 2015-04-09 21:13
this type of casts should be checked all over the core...

**Comment by Rushor** [comment] 2016-02-08 09:31
@ariel- : open up a pr for this one pls :)

**Comment by Eliminationzx** [comment] 2016-02-08 15:59
It's just wrong calculation.
http://wowwiki.wikia.com/wiki/Attack_power_coefficient
 ```diff
 src/server/scripts/Spells/spell_paladin.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/server/scripts/Spells/spell_paladin.cpp b/src/server/scripts/Spells/spell_paladin.cpp
index 8bd4b3e..847de04 100644
--- a/src/server/scripts/Spells/spell_paladin.cpp
+++ b/src/server/scripts/Spells/spell_paladin.cpp
@@ -1358,7 +1358,7 @@ class spell_pal_seal_of_righteousness : public SpellScriptLoader
                 float ap = GetTarget()->GetTotalAttackPowerValue(BASE_ATTACK);
                 int32 holy = GetTarget()->SpellBaseDamageBonusDone(SPELL_SCHOOL_MASK_HOLY);
                 holy += eventInfo.GetProcTarget()->SpellBaseDamageBonusTaken(SPELL_SCHOOL_MASK_HOLY);
-                int32 bp = int32((ap * 0.022f + 0.044f * holy) * GetTarget()->GetAttackTime(BASE_ATTACK) / 1000);
+                int32 bp = int32((ap * 0.0225f + 0.0355f * holy) * GetTarget()->GetAttackTime(BASE_ATTACK) / 1000);
 ```

**Comment by Keader** [comment] 2016-02-08 18:26
https://github.com/TrinityCore/TrinityCore/issues/14446#issuecomment-181439156

work for me xD, ty for share, PR are welcome :+1:

**Comment by Keader** [comment] 2016-02-15 17:21
@Rushor close this please :)

**Closed** 2016-02-15 17:33 UTC
Labels: Branch-3.3.5a, Comp-Core, Feedback-PatchFix, Sub-Spells
