### ISSUE TITLE
[3.3.5][6.x] Core/Quest: Congratulations!

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#16030] opened 2015-12-17 00:33 UTC
b967047

[This quest](http://www.wowhead.com/quest=12604) is available for completion every day without completing the prerequisite quest [Troll Patrol](http://www.wowhead.com/quest=12501) within 20 minutes.

**Comment by dr-j** [comment] 2016-02-11 11:09
http://www.wowhead.com/spell=51573/on-patrol

**Comment by tkrokli** [comment] 2016-02-17 01:15
`.cast 51573` on self -> `.list auras` (self):
id: 51573 [[On Patrol]](http://www.wowhead.com/spell=51573/on-patrol) effmask: 1 charges: 0 stack: 1 slot 0 duration: 1164899 maxduration: 1200000   caster: player guid: 1
```sql
-- quest 12604 'Congratulations!' is only available if player has aura 51573 'On Patrol'
DELETE FROM `conditions` WHERE `SourceEntry`= 12604 AND `ConditionValue1`= 51573;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(20, 0, 12604, 0, 0, 1, 0, 51573, 0, 0, 0, 0, 0, '', "Show quest mark 12604 'Congratulations!' only if player has aura 51573 'On Patrol'.");
```
I believe the logic should be correct. I have not had time to test it yet.

**Comment by tkrokli** [comment] 2016-02-17 04:23
Well. I think I got an idea. Just have to test it first. Maybe 12501 & 12563 are deactived quests? If so,
**my suggested solution will be this:**
```sql
-- Quest 12604 'Congratulations!' should only be offered if:

-- 1) player has completed all objectives for Quest 12587 'Troll Patrol' AND
UPDATE `quest_template_addon` SET `PrevQuestID`= 12587 WHERE `ID`= 12604;

-- 2) player still has aura 51573 'On Patrol' active (duration 20 minutes)
DELETE FROM `conditions` WHERE `SourceEntry`= 12604 AND `ConditionValue1`= 51573;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(20, 0, 12604, 0, 0, 1, 0, 51573, 0, 0, 0, 0, 0, '', "Show quest mark 12604 'Congratulations!' if player has aura 51573 'On Patrol'.");
```
For now, I can confirm that the quest is gone from Commander Kunz' initial quest gossip.

**Comment by dr-j** [comment] 2016-03-01 13:13
Some updates to this 

~~~sql
UPDATE `quest_template_addon` SET `PrevQuestID`= 12587 WHERE `ID`= 12604;

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN(19,20) AND`SourceEntry`= 12604 AND `ConditionValue1`IN(51573,53707);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(19, 0, 12604, 0, 0, 1, 0, 51573, 0, 0, 0, 0, 0, '', "Show quest mark 12604 'Congratulations!' if player has aura 51573 'On Patrol'."),
(20, 0, 12604, 0, 0, 1, 0, 51573, 0, 0, 0, 0, 0, '', "Show quest mark 12604 'Congratulations!' if player has aura 51573 'On Patrol'."),
(19, 0, 12604, 0, 0, 1, 0, 53707, 0, 0, 0, 0, 0, '', "Show quest mark 12604 'Congratulations!' if player has aura 51573 'On Patrol Heartbeat Script'."),
(20, 0, 12604, 0, 0, 1, 0, 53707, 0, 0, 0, 0, 0, '', "Show quest mark 12604 'Congratulations!' if player has aura 51573 'On Patrol Heartbeat Script'.");

UPDATE `creature_template` SET `AIName`='SmartAI', `ScriptName`=''  WHERE `entry` =28039;
DELETE FROM `smart_scripts` WHERE `entryorguid` =28039 AND `source_type`=0;

INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(28039, 0, 0, 1, 19, 0, 100, 0, 12596, 0, 0, 0, 85, 51506, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Pa''Troll - Invoker Cast Clear Patrol Quests'),
(28039, 0, 1, 0, 61, 0, 100, 0, 0, 0, 0, 0, 85, 51509, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Pa''Troll - Invoker Cast Clear Patrol Quests II'),
(28039, 0, 2, 3, 19, 0, 100, 0, 12587, 0, 0, 0, 85, 51573, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Invoker Cast On Patrol'),
(28039, 0, 3, 4, 61, 0, 100, 0, 0, 0, 0, 0, 85, 53712, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Invoker Cast Clear DAILY Patrol SUBQuests 00'),
(28039, 0, 4, 5, 61, 0, 100, 0, 0, 0, 0, 0, 85, 53713, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Invoker Cast Clear DAILY Patrol SUBQuests 01'),
(28039, 0, 5, 6, 61, 0, 100, 0, 0, 0, 0, 0, 85, 53715, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Invoker Cast Clear DAILY Patrol SUBQuests 02'),
(28039, 0, 6, 7, 61, 0, 100, 0, 0, 0, 0, 0, 85, 53716, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Invoker Cast Clear DAILY Patrol SUBQuests 03'),
(28039, 0, 7, 0, 61, 0, 100, 0, 0, 0, 0, 0, 28, 53707, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Remove Aura'),
(28039, 0, 8, 0, 20, 0, 100, 0, 12587, 0, 0, 0, 85, 53707, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Remove Aura');

DELETE FROM `creature_queststarter` WHERE  `id`=28039 AND `quest`IN(12501,12563);
~~~

1) Quests which are a requirement to complete quest now get reset and/or removed from quest log on quest accept
2) Appears 12501 and 12563 are marked as depreciated and unavailable on wowhead also judging that only comments on this before the comment about been removed was early in wotlk possibly beta have a feeling these may have been removed (Maybe wrong here)
3) Have had to use additional aura for this otherwise completing Troll Patrol a single time and then taking the quest the next day will allow congratulations to be taken without having to complete quest again, seems setting prev quest in db only works if quest has never been completed by player but once it has been completed once will always be available regardless of wether prerequisite was completed that same day or not and same with db conditions

**Comment by tkrokli** [comment] 2016-03-01 16:39
Yes, it looks like the 12501 version and 12563 version got deprecated around patch 3.1.0 (or maybe earlier), if the wowhead comment section can be used as an indicator of when the changes happened. Although I find it a bit odd how the quest number 12587 was known already at patch 3.0.3 when I compare with how much was written on the other 2 pages. Could be a mistake on wowhead's part, though.
(Of course, I know that some wowhead info is inaccurate and can not be used as factual documentation.)

**Comment by dr-j** [comment] 2016-03-01 16:55
Ye already updated that as think was changed in cata in wotlk each quest as unique sub-set of quests (this was probably changed so each npc has own pool as there appears to be only one quest in game now but still give random quests.

Version 1 12501 requires: -
* Troll Patrol: The Alchemists Apprentice
* Troll Patrol: Intestinal Fortitude
* Troll Patrol: Whatdya Want, a Medal?
* Troll Patrol: High Standards
Version 2 12563 requires: -
* Troll Patrol: The Alchemists Apprentice
* Troll Patrol: Something for the Pain
* Troll Patrol: Done to Death
* Troll Patrol: Creature Comforts
Version 3 12587 requires: -
* Troll Patrol: The Alchemists Apprentice
* Troll Patrol: Can You Dig It?
* Troll Patrol: Throwing Down
* Troll Patrol: Couldn't Care Less
Pa'Troll (Non Daily) requires: -
* Lab Work
* Something for the Pain
* Throwing Down
* Creature Comforts

quests where already linked in quest template as negative prev quest however I discovered that even if you had previously returned quest then these are permamently available

this is probably due to same reason as why if prev quest for congratulations is set in quest_template addon you only have to ever complete quest once and then is available every day after that.

seems when it comes to dailies conditions both in conditions or quest_template addon only checks that prequest has ever been completed not if it as only been completed on the same day.

anway since this seems correct pooling the 3 versions of Troll Patrol, removing previous quest for sub-quests and using conditions for quest taken instead (ye conditions for taken or complete still work for dailies but rewarded will always return as been rewarded once quest has been completed once.

**Comment by r00ty-tc** [comment] 2016-03-01 17:31
```SQL
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(28039, 0, 0, 1, 19, 0, 100, 0, 12596, 0, 0, 0, 85, 51506, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Pa''Troll - Invoker Cast Clear Patrol Quests'),
(28039, 0, 1, 0, 61, 0, 100, 0, 0, 0, 0, 0, 85, 51509, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Pa''Troll - Invoker Cast Clear Patrol Quests II'),
(28039, 0, 2, 5, 19, 0, 100, 0, 12587, 0, 0, 0, 85, 51573, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Invoker Cast On Patrol'),
(28039, 0, 3, 5, 19, 0, 100, 0, 12501, 0, 0, 0, 85, 51573, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Invoker Cast On Patrol'),
(28039, 0, 4, 5, 19, 0, 100, 0, 12563, 0, 0, 0, 85, 51573, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Invoker Cast On Patrol'),
(28039, 0, 5, 6, 61, 0, 100, 0, 0, 0, 0, 0, 85, 53712, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Invoker Cast Clear DAILY Patrol SUBQuests 00'),
(28039, 0, 6, 7, 61, 0, 100, 0, 0, 0, 0, 0, 85, 53713, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Invoker Cast Clear DAILY Patrol SUBQuests 01'),
(28039, 0, 7, 8, 61, 0, 100, 0, 0, 0, 0, 0, 85, 53715, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Invoker Cast Clear DAILY Patrol SUBQuests 02'),
(28039, 0, 8, 9, 61, 0, 100, 0, 0, 0, 0, 0, 85, 53716, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Invoker Cast Clear DAILY Patrol SUBQuests 03'),
(28039, 0, 10, 0, 61, 0, 100, 0, 0, 0, 0, 0, 28, 53707, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Remove Aura'),
(28039, 0, 11, 0, 20, 0, 100, 0, 12587, 0, 0, 0, 85, 53707, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Remove Aura'),
(28039, 0, 12, 0, 20, 0, 100, 0, 12501, 0, 0, 0, 85, 53707, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Remove Aura'),
(28039, 0, 13, 0, 20, 0, 100, 0, 12563, 0, 0, 0, 85, 53707, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Commander Kunz - On Quest Accept Troll Patrol - Remove Aura');
```

SmartAIMgr::LoadSmartAIFromDB: Entry 28039 SourceType 0, Event 8, Link Event 9 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 28039 SourceType 0, Event 10, Link Source Event not found or invalid. Event will never trigger.

Should be 9-12, or there is a missing 9?

**Comment by tkrokli** [comment] 2016-03-01 17:33
Thank you for the careful explanation. I was not know aware of the limitation in `CONDITION_QUESTREWARDED`.

**Comment by dr-j** [comment] 2016-03-01 19:00
Updated had already noticed those linking auras

also removing prevquest for congratulations as have two auras (both of which are cast at quest accept in sniff).

http://www.wowhead.com/spell=51573/on-patrol
http://www.wowhead.com/spell=53707/on-patrol-heartbeat-script

The second gives no visual aura and lasts for 10 mins longer than the visual aura
so casting both on quest accept, and removing 53707 on return of any version of troll patroll
removing 51573 on return of congratulations.

Congratulations is only takable if player has aura 51573 but does not have 53707

**Closed** 2016-03-01 20:08 UTC
Labels: Comp-Database, Sub-Quests
