### ISSUE TITLE
[Master] crash Spell::SelectImplicitAreaTargets

### ISSUE THREAD

**Issue by vinin80** [TrinityCore/TrinityCore#19118] opened 2017-02-12 14:34 UTC
**Description:** Hunter Talent Survivalist crashing server

http://pastebin.com/MZ7QmhyJ (raw: http://pastebin.com/raw/MZ7QmhyJ)

**Branch(es):** master

**Steps to reproduce the problem:**

1.  Create Hunter
2. Use talent Survivalist
3.  crash

**TC rev. hash/commit:** 26bb056

**Operating system:** Linux Debian

**Comment by matukaa** [comment] 2017-02-12 21:28
This is a duplicate issue. We have already one for this one, we agreed that it's an Assert error (not implemented target selector)
See this issue: https://github.com/TrinityCore/TrinityCore/issues/18868

**Comment by tkrokli** [comment] 2017-02-13 02:02
Very well. Closing this issue as a duplicate of #18868 .

**Closed by tkrokli** 2017-02-13 02:02 UTC
Labels: Branch-master, HasBacktrace
