### ISSUE TITLE
[3.3.5] DB/Creature: Prince Valanar walking on ground level (Death's Breach)

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#16330] opened 2016-01-20 10:17 UTC
TrinityCore rev. c606ac53d661 2016-01-20 01:38:30 +0100 (3.3.5 branch) (Win64, Release),
TDB 335.60 + all updates up to and including `2016_01_20_01_world.sql`

This is a continuation of issue #1674, Prince Valanar has still got the same issue of walking on ground level when he should be walking on top of the podium. This is the phase where you have accepted the quest "The Will of the Lich King" (http://www.wowhead.com/quest=12714/the-will-of-the-lich-king) from Highlord Darion Mograine and go to Prince Valanar down on Death's Breach to deliver it to Prince Valanar, then picking up the quest "The Crypt of Remembrance" (http://www.wowhead.com/quest=12715/the-crypt-of-remembrance).

In-game screenshot:
![wowscrnshot_012016_105005](https://cloud.githubusercontent.com/assets/4903600/12445559/2b551eb4-bf65-11e5-9ba5-51dbab5c7bc4.jpg)
No game addons, straight TC 3.3.5 source with no extra code added (core rev. hash also in the image).

**Comment by Takenbacon** [comment] 2016-01-20 16:47
Do you have vmaps extracted and enabled?

**Comment by tkrokli** [comment] 2016-01-20 20:48
Oh yes, they certainly are. DBC, maps, Vmaps and Mmaps are extracted from the same game client as the one I use to play the game. I extract new DBC/maps files at least once each month. I always enable Mmaps because I know how weird NPCs behave when Mmaps are disabled. Vmaps are always enabled in my server configs by default (TrinityCore default). I never change that Vmaps part.

**Comment by Kittnz** [comment] 2016-01-20 21:12
I'v seen this aswell, from what i understand is the gob is spawned after the npc and thats why the npc is inside it

**Comment by Aokromes** [comment] 2016-01-20 21:13
Strange, i am sure this was fixed long, long time ago.

**Comment by tkrokli** [comment] 2016-01-20 21:20
It might have worked before, but there are still things like this happening other places in the source too. Example:  **[Item "Instant Statue Pedestal" not working](10599)** #10599

I also thought about including the Lich King having the same issue for the quest "The Scarlet Apocalypse" like it was before in the issue  **[[NPC] Prince Valanar and Lich King are underground](5636)** #5636 , but I am uncertain if they are separate issues or not (see issue #5636 for more details).

**Comment by LordUsagi** [comment] 2016-01-20 23:25
I think in the case of 129547 he should probably have a flying flag, if he is spawned up in the air.

**Comment by tkrokli** [comment] 2016-01-20 23:53
@LordUsagi : Good idea, although I don't have the sniff values available for `guid 129547` to check if it should be flying. Currently, its `InhabitType` = 3 (Ground + Water) (https://trinitycore.atlassian.net/wiki/display/tc/creature_template#creature_template-InhabitType), although I am confused about the meaning of this NPC being mounted as well as having the same gossip as the other Death Knight Initiates who are available for the quest "Death's Challenge": `Are you challenging me, $g brother:sister;?`.

**Comment by Saben65** [comment] 2016-01-22 23:59
@tkrokli I believe on retail they fly down, dismount and become targets players can duel.

**Comment by tkrokli** [comment] 2016-01-23 00:36
OK, then that guid needs some scripting, although I am uncertain how that works when the only difference is the GUID and not the `creature_template`.`entry` 28406 (which includes all the others).

**Comment by Saben65** [comment] 2016-01-23 03:38
The mount should be done in creature_addon and the SAI would need to be done with the guid, though I do not know if that overrides the entry SAI.

**Comment by tkrokli** [comment] 2016-01-23 03:45
https://trinitycore.atlassian.net/wiki/display/tc/smart_scripts#smart_scripts-entryorguid
Yes, I see now that it should be possible to write a SAI for a specific GUID, although I don't know if we have got sniffs for the movement of `guid = 129547`. Maybe we have, maybe you can get it if we don't.
I must admit that I have never noticed that this specific NPC flew before landing and then dismounted. It would be cool if you could confirm that this is what happens to that NPC in that phase of this area. :)

**Comment by LordUsagi** [comment] 2016-01-23 03:57
We should probably open a second issue, we're breaking away from the main point.

**Comment by tkrokli** [comment] 2016-01-23 06:06
True. I will start moving my info to a new issue as soon as I have completely rewritten my latest PR.

**Comment by Kizarr** [comment] 2016-05-31 07:14
This fixes this issue and others confirmed working

-- Quest 12779, An End to All Things - Autocomplete
update quest_template set RequiredNpcOrGo1 = 0, RequiredNpcOrGoCount1 = 0, RequiredNpcOrGo2 = 0, RequiredNpcOrGoCount2 = 0, RequiredNpcOrGo3 = 0, RequiredNpcOrGoCount3 = 0, RequiredNpcOrGo4 = 0, RequiredNpcOrGoCount4 = 0, RequiredItemId1 = 0, RequiredItemCount1 = 0, RequiredItemId2 = 0, RequiredItemCount2 = 0, RequiredItemId3 = 0, RequiredItemCount3 = 0, RequiredItemId4 = 0, RequiredItemCount4 = 0 WHERE id = 12779;

-- Many creatures and quest givers
DELETE FROM creature WHERE id = 29110;
DELETE FROM creature WHERE guid >= 600300 and guid <= 600399;
INSERT INTO creature (guid, id, map, spawnMask, phaseMask, modelid, equipment_id, position_x, position_y, position_z, orientation, 
spawntimesecs, spawndist, currentwaypoint, curhealth, curmana, MovementType, npcflag, unit_flags, dynamicflags) VALUES 
(600300, 29110, 609, 1, 1, 0, 0, 2312.04, -5741.28, 153.918, 3.82047, 300, 0, 0, 27890000, 0, 0, 0, 0, 0),
(600301, 29488, 609, 1, 128, 0, 0, 2350.32, -5693.07, 382.239, 4.40647, 300, 0, 0, 5066, 0, 0, 0, 0, 0),
(600302, 31084, 0, 1, 256, 0, 1, 2376.85, -5649.96, 382.437, 3.76597, 300, 0, 0, 11156000, 2129000, 0, 0, 134218496, 0),
(600303, 29480, 0, 1, 256, 0, 0, 2349.73, -5665.52, 382.241, 3.88324, 300, 0, 0, 232470, 0, 0, 0, 0, 0),
(600304, 29110, 609, 1, 128, 0, 0, 2349.65, -5667.98, 382.242, 3.77423, 300, 0, 0, 27890000, 0, 0, 0, 0, 0),
(600305, 29488, 609, 1, 128, 0, 0, 2324.85, -5658.95, 382.241, 3.57788, 300, 0, 0, 4906, 0, 0, 0, 0, 0),
(600306, 29501, 609, 1, 128, 0, 0, 2400.32, -5726.76, 153.923, 5.36891, 300, 0, 0, 5066, 0, 0, 0, 0, 0);

-- Quest 12801, The Light of Dawn - Autocomplete
update quest_template set RequiredNpcOrGo1 = 0, RequiredNpcOrGoCount1 = 0, RequiredNpcOrGo2 = 0, RequiredNpcOrGoCount2 = 0, RequiredNpcOrGo3 = 0, RequiredNpcOrGoCount3 = 0, RequiredNpcOrGo4 = 0, RequiredNpcOrGoCount4 = 0, RequiredItemId1 = 0, RequiredItemCount1 = 0, RequiredItemId2 = 0, RequiredItemCount2 = 0, RequiredItemId3 = 0, RequiredItemCount3 = 0, RequiredItemId4 = 0, RequiredItemCount4 = 0 WHERE id = 12801;

-- Quest 13166, The battle for the Ebon Hold
update quest_template set RequiredNpcOrGo1 = 0, RequiredNpcOrGoCount1 = 0, RequiredNpcOrGo2 = 0, RequiredNpcOrGoCount2 = 0, RequiredNpcOrGo3 = 0, RequiredNpcOrGoCount3 = 0, RequiredNpcOrGo4 = 0, RequiredNpcOrGoCount4 = 0, RequiredItemId1 = 0, RequiredItemCount1 = 0, RequiredItemId2 = 0, RequiredItemCount2 = 0, RequiredItemId3 = 0, RequiredItemCount3 = 0, RequiredItemId4 = 0, RequiredItemCount4 = 0 WHERE id = 13166;

**Comment by tkrokli** [comment] 2016-05-31 08:08
@Kizarr : that "fix" is hacky and unacceptable, TC will not set quests to autocomplete when the quests are functional as they are. Your `DELETE FROM` queries are wrong too, use `BETWEEN @GUID AND @GUID+xx`. Also, spawning of more creatures can only be accepted if it is based on sniffs. And this is just from superficial browsing through that SQL, without looking closer at the details.

**Comment by Kizarr** [comment] 2016-05-31 19:48
I didn't make it but I did fox lich king issue and prince valor problem.

**Comment by tkrokli** [comment] 2016-05-31 20:21
If you get rid of the 'quest autocomplete' parts, maybe then we can talk about which parts can be looked at closer to see if there is anything useful in there. I don't know how soon I will have time to check out the spawning, but maybe I will test just the NPC spawn part to see if it contains anything useful or valid.

**Comment by Kizarr** [comment] 2016-05-31 21:26
Updated http://pastebin.com/bgxhQyAQ

**Comment by Kizarr** [comment] 2016-05-31 22:33
I'm testing this try this to se if fixes issue. http://pastebin.com/v1ReguQ9

**Comment by tkrokli** [comment] 2016-05-31 23:07
Huh? What on earth has http://www.wowhead.com/npc=4727/elder-thunder-lizard got to do with this?

**Comment by lyn1337** [comment] 2016-05-31 23:57
hæ?
@tkrokli maybe it does fix the issue. ;) ;)

**Comment by tkrokli** [comment] 2016-06-01 00:09
Lol, are we reading the same thing? from Kizarr's pastebin link http://pastebin.com/v1ReguQ9
```sql
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `DeathState`, `MovementType`) VALUES
(28907,4727,1,1,1,0,0,-1724.81,2862.98,78.5843,3.12499,300,5,0,1536,0,0,1),
(28907,4727,1,1,1,0,0,-1724.81,2862.98,78.5843,3.12499,300,5,0,1536,0,0,1),
```
`id` in `creature` table = `entry` in `creature_template` :
```sql
SELECT * FROM `creature` WHERE `id` = 4727;
```
(result: 40 creatures with the same entry)

```sql
SELECT * FROM `creature_template` WHERE `entry` = 4727;
```
```
 entry  difficulty_entry_1  difficulty_entry_2  difficulty_entry_3  KillCredit1  KillCredit2  modelid1  modelid2  modelid3  modelid4  name                  subname  IconName  gossip_menu_id  minlevel  maxlevel     exp  faction  npcflag  speed_walk  speed_run   scale    rank  dmgschool  BaseAttackTime  RangeAttackTime  BaseVariance  RangeVariance  unit_class  unit_flags  unit_flags2  dynamicflags  family  trainer_type  trainer_spell  trainer_class  trainer_race    type  type_flags  lootid  pickpocketloot  skinloot  resistance1  resistance2  resistance3  resistance4  resistance5  resistance6  spell1  spell2  spell3  spell4  spell5  spell6  spell7  spell8  PetSpellDataId  VehicleId  mingold  maxgold  AIName  MovementType  InhabitType  HoverHeight  HealthModifier  ManaModifier  ArmorModifier  DamageModifier  ExperienceModifier  RacialLeader  movementId  RegenHealth  mechanic_immune_mask  flags_extra  ScriptName  VerifiedBuild
------  ------------------  ------------------  ------------------  -----------  -----------  --------  --------  --------  --------  --------------------  -------  --------  --------------  --------  --------  ------  -------  -------  ----------  ---------  ------  ------  ---------  --------------  ---------------  ------------  -------------  ----------  ----------  -----------  ------------  ------  ------------  -------------  -------------  ------------  ------  ----------  ------  --------------  --------  -----------  -----------  -----------  -----------  -----------  -----------  ------  ------  ------  ------  ------  ------  ------  ------  --------------  ---------  -------  -------  ------  ------------  -----------  -----------  --------------  ------------  -------------  --------------  ------------------  ------------  ----------  -----------  --------------------  -----------  ----------  -------------
  4727                   0                   0                   0            0            0      2764         0         0         0  Elder Thunder Lizard  (NULL)   (NULL)                 0        37        38       0       14        0           1    1.14286       1       0          0            2000             2000             1              1           1           0         2048             0       0             0              0              0             0       1           0    4727               0    100013            0            0            0            0            0            0    5401   20536   20535   20543       0       0       0       0               0          0        0        0                     1            1            1            1.15             1              1               1                   1             0           0            1                     0            0                      12340
```
`name -> Elder Thunder Lizard`

**Comment by lyn1337** [comment] 2016-06-01 00:46
@tkrokli My first name (Lyn) actually is Norwegian, but I do live in Germany and don't speak it or Fin much. (: Yep, I was only kidding. Not sure how spawning thunder lizards will help. :smile:

**Comment by Kizarr** [comment] 2016-06-01 02:15
Lol typo.... I had update let me fix...

**Comment by tkrokli** [comment] 2016-06-01 02:42
OK, at least this time you got the NPC IDs right. Have to look at it later, got lots of other stuff going on.

**Comment by Kizarr** [comment] 2016-06-02 06:15
Okay you can also try this http://pastebin.com/BNpCSMNL

**Comment by lyn1337** [comment] 2016-06-02 12:13
@Kizarr Kizarr, maybe you could share some thoughts to your approach and what you're trying to do. 
It seems to me, you're spawning the prince and the king to the same pos with different values for health? Your table structure looks different, too.

**Comment by tkrokli** [comment] 2016-06-02 14:13
TrinityCore rev. 6007f2a6a0ac 2016-06-02 00:31:32 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.61 + updates up to and including `2016_06_01_12_world.sql` `'8DC7CF8'`
```sql
SELECT * FROM `creature_template` WHERE `entry` IN (28907,29110);
```
```
 entry  modelid1  modelid2  modelid3  modelid4  name            subname  IconName  gossip_menu_id  minlevel  maxlevel     exp  faction  npcflag  speed_walk  speed_run   scale    rank  dmgschool  BaseAttackTime  RangeAttackTime  BaseVariance  RangeVariance  unit_class  unit_flags  unit_flags2  dynamicflags  family  trainer_type  trainer_spell  trainer_class  trainer_race    type  type_flags  lootid  pickpocketloot  skinloot  resistance1  resistance2  resistance3  resistance4  resistance5  resistance6  spell1  spell2  spell3  spell4  spell5  spell6  spell7  spell8  PetSpellDataId  VehicleId  mingold  maxgold  AIName   MovementType  InhabitType  HoverHeight  HealthModifier  ManaModifier  ArmorModifier  DamageModifier  ExperienceModifier  RacialLeader  movementId  RegenHealth  mechanic_immune_mask  flags_extra  ScriptName  VerifiedBuild
------  --------  --------  --------  --------  --------------  -------  --------  --------------  --------  --------  ------  -------  -------  ----------  ---------  ------  ------  ---------  --------------  ---------------  ------------  -------------  ----------  ----------  -----------  ------------  ------  ------------  -------------  -------------  ------------  ------  ----------  ------  --------------  --------  -----------  -----------  -----------  -----------  -----------  -----------  ------  ------  ------  ------  ------  ------  ------  ------  --------------  ---------  -------  -------  -------  ------------  -----------  -----------  --------------  ------------  -------------  --------------  ------------------  ------------  ----------  -----------  --------------------  -----------  ----------  ---------------
 28907     25514         0         0         0  Prince Valanar                                  0        72        72       2     2082        2           1    0.99206       1       1          0            2000             2000             1              1           1         768         2048             0       0             0              0              0             0       6          32       0               0         0            0            0            0            0            0            0       0       0       0       0       0       0       0       0               0          0        0        0  SmartAI             0            3            1               1             1              1             7.5                   1             0           0            1               8388624            0                      12340
 29110     24191         0         0         0  The Lich King                                   0        83        83       2     2100        2           1    1.14286       1       3          0            2000             2000             1              1           1         768         2048             0       0             0              0              0             0       6          36       0               0         0            0            0            0            0            0            0       0       0       0       0       0       0       0       0               0          0        0        0                      0            3            1            2000           500              1              35                   1             0         169            1               8388624            0                      12340
```
(columns `difficulty_entry_1/2/3` + `KillCredit1/2` removed for readability)

`creature` table,  `guid`/`id`/`name` 130344/28907/Prince Valanar and 130896/29110/The Lich King:
```sql
SELECT * FROM `creature` WHERE `id` IN (28907,29110);
```
```
  guid      id     map  zoneId  areaId  spawnMask  phaseMask  modelid  equipment_id  position_x  position_y  position_z  orientation  spawntimesecs  spawndist  currentwaypoint  curhealth  curmana  MovementType  npcflag  unit_flags  dynamicflags  VerifiedBuild
------  ------  ------  ------  ------  ---------  ---------  -------  ------------  ----------  ----------  ----------  -----------  -------------  ---------  ---------------  ---------  -------  ------------  -------  ----------  ------------  ---------------
130344   28907     609       0       0          1          4    25514             0     2316.65    -5738.61     155.981     0.733038            360          0                0       9610        0             0        0           0             0              0
130896   29110     609       0       0          1        192        0             0     2310.27    -5742.21     161.207      3.85718            360          0                0   27890000        0             0        0           0             0              0
```

current content in the  `creature` table vs Kizarr's suggestion:
```
  guid      id     map  zoneId  areaId  spawnMask  phaseMask  modelid  equipment_id  position_x  position_y  position_z  orientation  spawntimesecs  spawndist  currentwaypoint  curhealth  curmana  MovementType  npcflag  unit_flags  dynamicflags  VerifiedBuild
------  ------  ------  ------  ------  ---------  ---------  -------  ------------  ----------  ----------  ----------  -----------  -------------  ---------  ---------------  ---------  -------  ------------  -------  ----------  ------------  ---------------
130344   28907     609       0       0          1          4    25514             0     2316.65    -5738.61     155.981     0.733038            360          0                0       9610        0             0        0           0             0              0
130344   28907     609                          1          4        0             0     2316.65    -5738.61     155.981     0.733038            360          0                0       9610        0             0        0
------  ------  ------  ------  ------  ---------  ---------  -------  ------------  ----------  ----------  ----------  -----------  -------------  ---------  ---------------  ---------  -------  ------------  -------  ----------  ------------  ---------------
130896   29110     609       0       0          1        192        0             0     2310.27    -5742.21     161.207      3.85718            360          0                0   27890000        0             0        0           0             0              0
130896   29110     609                          1        192        0             0     2310.27    -5742.21     161.207      3.85718            360          0                0   13945000        0             0        0
------  ------  ------  ------  ------  ---------  ---------  -------  ------------  ----------  ----------  ----------  -----------  -------------  ---------  ---------------  ---------  -------  ------------  -------  ----------  ------------  ---------------
```
There is not much change compared to TDB 335.61, except for 2 things:
- Prince Valanar's `modelid` has been removed
- The Lich King's hp has been reduced from `27 890 000` to `13 945 000`

I see no reason to change the LK's hp, so only the modelid removal should be tested & explained.

**Comment by lyn1337** [comment] 2016-06-02 15:48
> I see no reason to change the LK's hp, so only the modelid removal should be tested & explained.

Not really… when the field `modelid` in table `creature` is set to 0, the core will just choose a random value, which isn't 0 from `modelid1` to `modelid4` in `creature_template` for it instead.
Entry 29110 (the king) also has no such model set in `creature`. 

I think we might as well apply this:
```sql
-- remove unnecessarily set model id from Prince Valanar spawn
UPDATE `creature` SET `modelid`=0 WHERE `guid`=130344;
```

**Comment by tkrokli** [comment] 2016-06-03 00:08
You are quite correct, Prince Valanar has got the default `modelid1 = 25514` in `creature_template`.

**Comment by lyn1337** [comment] 2016-06-03 04:01
@tkrokli It does make a difference, but Valanar is still displayed correctly. Possible explanations are likely this core logic being younger than the db entry, or a mistake by the person who spawned this area. `VerifiedBuild = 0`

**Comment by Kizarr** [comment] 2016-06-03 06:59
Here's fix for prince valanar with the right coords. I was doing some testing from other cores ignore other stuff. 

http://image.prntscr.com/image/0470426bad7e4c13af4ecef1c13c891b.png

**Comment by Kittnz** [comment] 2016-06-03 07:02
I don't call that a fix @Kizarr

**Comment by Kizarr** [comment] 2016-06-03 07:04
@kittnz change the z coords to 160.981 it fixes the issue.

**Comment by Kizarr** [comment] 2016-06-03 07:12
@Kittnz Scratch that found a bug I trying z coords in creature db 156.981

**Comment by Aokromes** [comment] 2016-06-03 07:28
Hack:

[9] GUID: Full: Type: Creature Entry: 28907 Low: 927
[9] Object Type: Unit (3)
[9] Update Flags: Living, StationaryObject (96)
[9] Movement Flags: None (0)
[9] Extra Movement Flags: None (0)
[9] GUID 2: Full: Type: Creature Entry: 28907 Low: 927
[9] Time: -1616821493
[9] Position: X: 2316.619 Y: -5742.296 Z: 155.9813

ServerToClient: SMSG_ON_MONSTER_MOVE (0x4C53) Length: 53 ConnIdx: 0 Time: 11/14/2011 02:11:44.000 Number: 58822
GUID: Full: Type: Creature Entry: 28907 Low: 927
Toggle AnimTierInTrans: false
Position: X: 2316.619 Y: -5742.296 Z: 155.9813

ServerToClient: SMSG_ON_MONSTER_MOVE (0x4C53) Length: 53 ConnIdx: 0 Time: 11/14/2011 02:11:50.000 Number: 58912
GUID: Full: Type: Creature Entry: 28907 Low: 927
Toggle AnimTierInTrans: false
Position: X: 2316.619 Y: -5742.296 Z: 155.9813

ServerToClient: SMSG_ON_MONSTER_MOVE (0x4C53) Length: 53 ConnIdx: 0 Time: 11/14/2011 02:11:51.000 Number: 58914
GUID: Full: Type: Creature Entry: 28907 Low: 927
Toggle AnimTierInTrans: false
Position: X: 2316.648 Y: -5738.609 Z: 155.9813

**Comment by tkrokli** [comment] 2016-06-03 10:26
OK, so you're thinking to spawn him with no movement_flags and then script the movement? :suspect:

**Comment by lyn1337** [comment] 2016-06-03 13:38
I wonder why all Z values are lower than FloorZ (=156.024002).
Shouldn't these be updated?
```sql
UPDATE `creature` SET `position_z`=156.025 WHERE `guid`=130344;

UPDATE `smart_scripts` SET `target_z`=156.025 WHERE `entryorguid`=2890700 and`id`=3;
UPDATE `smart_scripts` SET `target_z`=156.025 WHERE `entryorguid`=2890700 and`id`=1;
UPDATE `smart_scripts` SET `target_z`=156.025 WHERE `entryorguid`=2890700 and`id`=6;
UPDATE `smart_scripts` SET `target_z`=156.025 WHERE `entryorguid`=2890700 and`id`=10;
UPDATE `smart_scripts` SET `target_z`=156.025 WHERE `entryorguid`=2890700 and`id`=14;
```

I gave this a try yesterday; it doesn't solve the issue completely, as Valanar still is ankle-deep in his podium. :confused:

**Comment by tkrokli** [comment] 2016-06-03 14:16
Thanks for checking that, I'll have to test that later. Maybe up the values more, like `156.03` or more.

**Comment by lyn1337** [comment] 2016-06-03 14:42
@tkrokli Oh, I'm sorry, I forgot to mention that I tried upping it to 156.05 too, but didn't succeed. Curse this hot weather. :icecream:

**Comment by Aokromes** [comment] 2016-06-03 15:36
Again, hack, this comes from retail:

[9] GUID 2: Full: Type: Creature Entry: 28907 Low: 927
[9] Time: -1616821493
[9] Position: X: 2316.619 Y: -5742.296 Z: 155.9813

**Comment by tkrokli** [comment] 2016-06-03 15:54
`Z: 155.9813` ... interesting. Will have to check that later. lyn1337 - you will test that too?

**Comment by lyn1337** [comment] 2016-06-03 16:51
Checked. Tried updating the spawn with the retail Z only and along with the retail X and Y  plus updated Z in the SAI – he's on the ground again. :disappointed:
Then again, why would Z be lower than FloorZ?

**Comment by tkrokli** [comment] 2016-06-03 20:25
Good question, I would have thought that a higher Z coordinate would place him more correctly in height, but maybe there is something that I have misunderstood in the spawning process. Have you tried with a full 1.0 extra in the Z coordinate to see if anything useful happens?

**Comment by Aokromes** [comment] 2016-06-03 20:41
Ingame npc info:
[22:39:44] Position: 2316.649902 -5738.609863 153.920074.
Maybe creature spawns before gameobject and because that it's moved to floor.

**Comment by tkrokli** [comment] 2016-06-03 20:48
Yes, that is very likely. That used to be the common issue with any NPCs who sink into the ground.

**Comment by lyn1337** [comment] 2016-06-03 21:50
@tkrokli & @Aokromes But if it was like that, sooner or later SAI would make him walk up onto it again.

The values from retail posted by Aokromes don't work here. (below FloorZ) This could be caused by the podium GO being some kind of lower on retail, so if we want to use this Z, we need sniffed values for the GO as well.
Both podium and Valanar have `VerifiedBuild = 0`.
…
which leads me into proposing this:

```sql
SET @z_ground := 153.920074; -- GroundZ
SET @z_floor := 156.12; -- FloorZ post GO repositioning
SET @valanar := 130344; -- Prince Valanar (entry: 28907) spawn
SET @podium := 66361; -- podium spawn (entry: 190919)

-- update spawn with sniffed retail values for X and Y and FloorZ value by gps command
UPDATE `creature` SET `position_x`=2316.619, `position_y`=-5742.296, `position_z`=@z_floor WHERE `guid`=@valanar;

-- update SAI movement with FloorZ value by gps command
UPDATE `smart_scripts` SET `target_z`=@z_floor WHERE `entryorguid`=2890700 and`id`=3;
UPDATE `smart_scripts` SET `target_z`=@z_floor WHERE `entryorguid`=2890700 and`id`=1;
UPDATE `smart_scripts` SET `target_z`=@z_floor WHERE `entryorguid`=2890700 and`id`=6;
UPDATE `smart_scripts` SET `target_z`=@z_floor WHERE `entryorguid`=2890700 and`id`=10;
UPDATE `smart_scripts` SET `target_z`=@z_floor WHERE `entryorguid`=2890700 and`id`=14;

-- update the podium gameobject with GroundZ value by gps command
UPDATE `gameobject` SET `position_z`=@z_ground WHERE `guid`=@podium;

-- Scarlet Enclave: remove unnecessary model id  from Prince Valanar in the creature table
UPDATE `creature` SET `modelid` = 0 WHERE `guid` =@valanar;
```
(Tested Query: Yes)

This is now fully working for me. I tried teleporting somewhere else and back again plus respawning Valanar.
And in case it should stop working, it can't be fixed by simply repositioning the creature or objects.

core_version: TrinityCore rev. 2d2544fab025 2016-06-03 17:57:05 +0200 (3.3.5 branch) (Unix, Release)
db_version: TDB 335.61

p.s. made a screenshot, but I think it's too dark.

**Comment by Aokromes** [comment] 2016-06-03 21:55
GO coords:

[12] GUID: Full: 0xF112E9C900000077 Type: GameObject Entry: 190921 Low: 119
[12] Object Type: GameObject (5)
[12] Update Flags: StationaryObject, GORotation (576)
[12] Stationary Position: X: 2314.327 Y: -5740.21 Z: 153.9207

**Comment by lyn1337** [comment] 2016-06-03 22:14
So the Z difference on retail is 2.0606 vs 2.199926 here. Tested, this doesn't work for me / us.
Did they change the GO model? :laughing:

**Comment by jackpoz** [comment] 2016-06-03 22:24
The NPC is spawned at 155.981003, then SAI moves it around with MoveSplineInit::MoveTo() that calls path.CalculatePath(dest.x, dest.y, dest.z, forceDestination) that ignores spawned gameobjects.
```
_actualEndPosition = {x=2311.37988 y=-5740.14014 z=153.920074 }
```

**Comment by lyn1337** [comment] 2016-06-03 23:17
@jackpoz does this also cause the gps command to display wrong FloorZ at only certain points of the go?

**Comment by jackpoz** [comment] 2016-06-04 13:02
Please try after https://github.com/TrinityCore/TrinityCore/commit/1347d7cf7a8656f3db9d8b2f6e6d955e1fa8c129

**Comment by lyn1337** [comment] 2016-06-04 17:23
@jackpoz He appears sunken again. At least for me.

**Comment by tkrokli** [comment] 2016-06-04 17:58
TrinityCore rev. 1347d7cf7a86 2016-06-04 15:01:39 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.61 + updates up to and including `2016_06_02_01_world.sql` (DBs rebuilt from scratch)

Started a new character, played it from creation to quest "The Will of the Lich King" (12714). At first, it looked like there was no change, so I thought "No, this can't be right with the new changes." and I exited the game, deleted my game client Cache folder and tried again. Looks a lot better :

![wowscrnshot_060416_194954](https://cloud.githubusercontent.com/assets/4903600/15801216/31ca8952-2a8e-11e6-91bd-a2858a3ec03a.jpg)

I am tempted to say that https://github.com/TrinityCore/TrinityCore/commit/1347d7cf7a8656f3db9d8b2f6e6d955e1fa8c129 has fixed the issue, but to be on the safe side, I would like to get confirmation from more users to see that this is not just a random event. :+1:

**Comment by Killyana** [comment] 2016-06-04 18:09
Once in this area try gm on/of and mod phase 4 many times and you will get this http://i.imgur.com/5rJ5iAO.jpg
Looks like if the npc is loaded before the gob on client side it will appear on the ground.

**Comment by tkrokli** [comment] 2016-06-04 18:31
OK, I see what you mean, so my experience is more or less just an opportune coincidence. I suppose I will have to test again with my game client addons loaded as well, just to see if they affect this too for me.

**Comment by lyn1337** [comment] 2016-06-04 18:55
@Killyana He returns to the top of it for me. And the gps command returns incorrect FloorZ, even if he is.

**Comment by tkrokli** [comment] 2016-06-04 19:17
Looks like I need to delete my game client Cache folder each time to make him appear on top of the GO.

**Comment by Kizarr** [comment] 2016-12-18 08:04
Any progress on this yet?

**Comment by greenbagels** [comment] 2017-02-06 13:55
Still getting this on rev. c2a36c9 and 355.62. Oddly enough, a simple relog (back to character screen and back in) while standing in front of the pedestal fixed the issue, at least for the Lich King in the later phase (who appeared nearly entirely inside the large pedestal).

**Comment by tkrokli** [comment] 2017-02-06 20:18
Yes, the status is pretty much unchanged from when we discussed this on Jun 4, 2016.

**Comment by Killyana** [comment] 2017-12-30 09:50
Cannot reproduce after https://github.com/TrinityCore/TrinityCore/commit/e42903ec16f4849b71bc8736e3151a1e11d3cd25

**Closed** 2017-12-30 10:51 UTC
Labels: Branch-3.3.5a, Priority-Cosmetic, Sub-Entities, Sub-Maps/MMaps/Vmaps

**Comment by offl** [comment] 2021-08-31 22:07
https://youtu.be/5DMYXMDoQpI?t=31 on retail it's bugged too
