### ISSUE TITLE
Quest: Princess Must Die! Pigs dont move also do not attack together

### ISSUE THREAD

**Issue by Bluechen80** [TrinityCore/TrinityCore#21961] opened 2018-05-25 02:14 UTC
Quest: Princess Must Die!

Description:
In a Blizzlike Version of 3.3.5a the Pig named Princess has Company from 2 "Porcine Entourage" and they walk together (like u can see here: https://www.youtube.com/watch?v=0bDDFFT502E from Minute: 0:53 i know it says Vanilla but it was the same in 3.3.5a) in a Circle. If u attacked one of them they attack together.

Level 9 Warlock

Current behaviour:
they just stand in the middle and dont move (the dont walk in a Circle) also when u attack one of them the others dont care and dont attack.

Expected behaviour:
walk as a pack together in Circle. If u attack one, all attacks you.

Branch(es): 3.3.5a

TrinityCore rev. 17539f1cb319 2018-05-24

TDB version: TDB 335.64 latests updates installed

Operating system: Windows 10

Using configuration file C:/Trinity/authserver.conf.
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.65.1
MySQL client library: 5.6.39
MySQL server ver: 5.6.39-log

**Comment by ZenoX92** [comment] 2018-05-25 20:10
This should fix the issue. However, there's still a problem. If you attack one of them at melee, all 3 will atack you, as intended; but if you attack one of them from distance, only the one you attacked will attack you. Maybe there's an issue with groupAI in creature_formations?
```sql
-- Pathing for Princess
UPDATE `creature` SET `position_x`=-9785.24, `position_y`=-880.61, `position_z`=39.6131, `MovementType`=2 WHERE `guid`=80849;
UPDATE `creature` SET `position_x`=-9785.44, `position_y`=-883.454, `position_z`=39.6473 WHERE `guid`=80850;
UPDATE `creature` SET `position_x`=-9781.22, `position_y`=-881.556, `position_z`=39.5677 WHERE `guid`=80848;

DELETE FROM `creature_addon` WHERE `guid`=80849;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(80849,808490,0,0,0,0,"");

DELETE FROM `creature_formations` WHERE `leaderGUID`=80849;
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES
(80849,80849,0,0,515,0,0),
(80849,80850,3,240,515,0,0),
(80849,80848,3,60,515,0,0);

DELETE FROM `waypoint_data` WHERE `id`=808490;
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_type`, `action`, `action_chance`, `wpguid`) VALUES
(808490,1,-9785.24,-880.61,39.6131,0,0,0,0,100,0),
(808490,2,-9792.77,-872.876,39.5751,0,0,0,0,100,0),
(808490,3,-9793.2,-867.623,39.4678,0,0,0,0,100,0),
(808490,4,-9774.36,-847.313,39.7919,0,0,0,0,100,0),
(808490,5,-9767.83,-847.814,39.6107,0,0,0,0,100,0),
(808490,6,-9752.2,-863.369,39.4772,0,0,0,0,100,0),
(808490,7,-9753.51,-871.917,39.5511,0,0,0,0,100,0),
(808490,8,-9769.58,-886.229,39.4867,0,0,0,0,100,0),
(808490,9,-9776.63,-887.336,39.5384,0,0,0,0,100,0);

**Comment by Killyana** [comment] 2018-05-25 20:20
Looks to be related to the combat system rewrite.

**Comment by ZenoX92** [comment] 2018-05-25 20:43
Maybe we should open a new issue for that and close this?

**Comment by Killyana** [comment] 2018-05-25 20:46
Yes.

**Comment by Bluechen80** [comment] 2018-05-25 21:19
There's a house on the same spot. There a three NPCs in the house. If you attack one, all three come, so that must be the same mechanics. Shouldn't that also work for the pigs? Just as an idea.

**Closed** 2018-05-26 19:47 UTC
Labels: Branch-3.3.5a, Comp-Database, Feedback-PatchFix, Sub-Waypoints
