### ISSUE TITLE
Hunter stuck in melee attack stance

### ISSUE THREAD

**Issue by saftig** [TrinityCore/TrinityCore#9347] opened 2013-03-05 09:36 UTC
I have encountered this issue pretty frequently and it's getting a bit tedious. In order to recreate the issue, you obviously need a hunter. Just use "Raptor Strike" and before it strikes the targeted creature, go out of melee range. This also happens if the targeted mob starts fleeing as you're about to hit it. This will render the hunter unable to do any melee attacks as it seems to be stuck in melee attack-mode, you will need to relog to fix this issue. I'm not sure that this is something that is hunter specific or if it occurs to other classes aswell nor am I sure if it's isolated to "Raptor Strike". It can also be hard to reproduce as the target needs to be on the edge what is considered melee range. 
 
If the target goes out of range the attack should ofcourse reset and not force the hunter into an endless loop trying to melee attack the old target.
 
I'm running TC 5d4e657e91604b37dc0af814ff7562e3a084139b, TDB full 335.51 with all updates applied. Vmaps and MMaps running, no additional patches.
 
I've been inactive in the emulation community for quite some time now, but I'd be happy to have a look at it if someone could point me in the right direction.

**Comment by tkrokli** [comment] 2015-05-26 01:39
TrinityCore rev. 9e3001a44b7f 2015-05-25 01:07:52 +0200 (3.3.5 branch) (Win64, Release)

Unable to reproduce this issue. Melee attack stance properly resets and is not stuck on my characters.
The only time my hunter characters seem stuck (in combat) is when using ranged weapons and move out of LoS (which is a completely different issue, ofc). Tested training dummies as well, just to be sure.

I am guessing that this problem has been fixed around the same (unknown) time as issue https://github.com/TrinityCore/TrinityCore/issues/9960 was fixed.

**Comment by Rushor** [comment] 2016-02-09 11:41
same as https://github.com/TrinityCore/TrinityCore/issues/13595. closing this, because the orther issue contains more sources/proofs

**Closed by Rushor** 2016-02-09 11:41 UTC
Labels: Comp-Core
