### ISSUE TITLE
wow lich king 10 normal. boss is dying automatically.

### ISSUE THREAD

**Issue by Adizbek** [TrinityCore/TrinityCore#19204] opened 2017-02-25 20:30 UTC
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Raid dungeon, Citadel of Lich King. When you attack him all is good. But when his hp below 50% he automatically dies. Whats wrong with him? Only in dungeon 10 normal. Other mods works correctly. 25 works well.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5
**TC rev. hash/commit:**  
TrinityCore rev. 278353673639 2017-02-21 21:02:12 +0500 (3.3.5 branch) (Unix, Release, Static) 
**TDB version:**  
TDB 335.62
**Operating system:**  
Debian 8

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment] 2017-02-25 20:33
you said 3.3.5a and linked master branch commit.

**Comment by Adizbek** [comment] 2017-02-26 03:40
I update commit. I find this when I typed .server info.

**Comment by Adizbek** [comment] 2017-02-26 05:14
Thanks. I will try today.

**Comment by Aokromes** [comment] 2017-02-26 07:59
there is no such rev on tc repositories.

**Comment by Adizbek** [comment] 2017-02-26 09:21
I have found thia when typed in console. Later I tell you exact rev. from git.

**Comment by tkrokli** [comment] 2017-02-26 09:30
`TrinityCore rev. 278353673639 2017-02-21 21:02:12 +0500 (3.3.5 branch) (Unix, Release, Static)` **_is already_** your exact core rev. hash in git, at least before you update/revert/switch to straight and unchanged TC source.

**Comment by sirikfoll** [comment] 2017-02-28 19:33
Can't reproduce this on 2e68736afcab26d0bb8e1408fa639d09d4772dfb

**Comment by tkrokli** [comment] 2017-02-28 19:40
Closing issue as invalid, both because of non-TC rev. hash & because it is not reported on straight TC source.

**Closed by tkrokli** 2017-02-28 19:40 UTC
Labels: Invalid-CannotReproduce, Invalid-IncompleteData/NotTrinityCore
