### ISSUE TITLE
DB/Quest: It Rolls Downhill (12673)

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17771] opened 2016-08-12 18:54 UTC
**Description**:
Controling of the Blight Geists does not work.

http://www.wowhead.com/quest=12673/it-rolls-downhill
https://www.youtube.com/watch?v=xWkWniMfcK4

**Branch(es)**: 3.3.5 / 6.x
**TC hash/commit**:  
TC>TrinityCore rev. 194fbd17923a 2016-08-12 11:33:02 +0200 (335 branch)
**TDB version**:  
TDB_full_world_335.61_2016_04_11.sql + all updates
**Operating system**:  

Win7 64Bit

**Comment by tkrokli** [comment] 2016-08-12 18:59
"[...] does not work." is a very vague description. Please add more details about how it is expected to work and what happens when it doesn't work (where it stops working) in your post. Please also add some links to the quest and the involved NPC(s) that this issue affects. TC developers don't have time to look up all this information for you, so please help us to help you by entering more info in your issue post.

**Comment by Tauriella** [comment] 2016-08-12 19:09
If you use the Scepter of Suggestion on  Blight Geists nothing happens. 
Normal have your Char 1min control over the Blight Geists he harvests for you.

**Comment by dr-j** [comment] 2016-08-13 14:00
This works however as the same problems with the rest of the npcs you must use skeptor on later in chain

When you take control of the geist the first thing you must to do is intruct it to follow you via pet bar if you just try and harvest blight without telling it to follow you first this will break once you get too far away unless you tell it to follow.

Its the same with http://www.wowhead.com/quest=12690/fuel-for-the-fire where unless you tell the bloated abdomination to follow you first will fail.

and with http://www.wowhead.com/quest=12686/zero-tolerance where unless you tell the servant of drakuru to follow you first will end up attacking you instead of target you send it to.

**Comment by Tauriella** [comment] 2016-08-13 15:21
Arrrg i have don't sea the Petmenu.
i will blind :-1: 
Thank you for help and sorry for my blindness.

**Comment by tkrokli** [comment] 2016-08-23 03:12
Closing this as "not an issue with TC source" due to user error.

**Comment by dr-j** [comment] 2016-08-23 09:30
Atually this is bugged as you should not have to tell the pet to follow you after summon it should do this automatically not stay where summoned until either told to follow or summoner goes out of range.

**Comment by tkrokli** [comment] 2016-08-23 12:15
OK, reopening this issue because of existing bug confirmed.

**Comment by Killyana** [comment] 2016-11-22 09:21
https://github.com/TrinityCore/TrinityCore/issues/17945

**Closed by Killyana** 2016-11-22 09:21 UTC
Labels: Branch-3.3.5a, Comp-Database, Sub-Quests
