### ISSUE TITLE
[Crash-6.x]  std::_Hashtable<unsigned int, std::pair<unsigned int const, CriteriaProgress>, std::allocator<std::pair<unsigned int const, CriteriaProgress> >, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node (this=0x7fff7dd1e0c8, this@entry=0x7fff7dd1e0d0, __n=1634, __k=@0x7fffb3300880: 5373, __code=<optimized out>) at /usr/include/c++/4.9/bits/hashtable.h:1445

### ISSUE THREAD

**Issue by Darkiu** [TrinityCore/TrinityCore#14908] opened 2015-06-17 17:46 UTC
REV: https://github.com/TrinityCore/TrinityCore/commit/d2142ac380863716ecea6f4aa44f7e556e44dfd9

Link: http://pastebin.com/gZdPCA7X

Thanks.

**Comment by soulfrost** [comment] 2015-07-06 14:45
any news?

**Comment by soulfrost** [comment] 2015-07-27 10:50
any news?

**Comment by Aokromes** [comment] 2015-07-27 10:54
No.

**Comment by Myst** [comment] 2015-07-30 14:35
Confirmed. I'm working on fix this as soon as I solve this I will make a PR.

**Comment by Aokromes** [comment] 2015-11-03 20:04
To long time since the last crash closing, if anyone have any new crash related to this open a new ticket.

**Closed by Aokromes** 2015-11-03 20:04 UTC
Labels: Branch-6.x, HasBacktrace
