### ISSUE TITLE
[3.3.5] Core/Crash: ~SpellEvent ABORTED

### ISSUE THREAD

**Issue by L30m4nc3r** [TrinityCore/TrinityCore#16675] opened 2016-02-24 16:30 UTC
**Description**:
We trying test ulduar and start fight with Yogg (25) (idk maybe problem not here, but maybe it help you).
And server crashed.

**Branch**: 335
**TC hash/commit**:
https://github.com/TrinityCore/TrinityCore/commit/e60f575ac8d0c148f8f7ad1d38ee7c62c2c2254d
**TDB version**:
TDB 335.60
**Operating system**:
Ubuntu 14.04

I know it is useless crash log:
[//]: # https://gist.github.com/L30m4nc3r/7813c47df8600ba7d2cb

**Comment by EternalDark** [comment] 2016-02-25 14:19
I noticed after a crash Yogg Saron evade. Specifically, Phase 1 - unfortunately not survived logs.

**Comment by jackpoz** [comment] 2016-02-26 16:37
can you try reproducing the crash, maybe with worldserver built with more debug informations ?

**Comment by EternalDark** [comment] 2016-02-26 17:32
``` QUOTE
can you try reproducing the crash, maybe with worldserver built with more debug informations ?
```
Cannot, I removed the C ++ script and replaced the SmartAI.

**Comment by L30m4nc3r** [comment] 2016-02-26 19:55
cmake ../ -DPREFIX=/wow/TrinityCore/build /wow/TrinityCore \
-DWITH_COREDEBUG=0 \
-DCMAKE_C_FLAGS="-ggdb3 -g3 -O3" \
-DCMAKE_INSTALL_PREFIX=/wow/TrinityCore/build/

**Comment by L30m4nc3r** [comment] 2016-04-06 08:47
again crash, idk reason.
`~SpellEvent: Creature 1850 tried to delete non-deletable spell 63886. Was not deleted, causes memory leak.`

**Comment by Naios** [comment] 2016-07-02 11:05
Stacktrace: https://gist.github.com/Naios/7ef9417ac83a5e1ea3a4b2ef9946023e

**Comment by jackpoz** [comment] 2016-07-02 16:28
MapId: 564 Black Temple
Position: X = 449.595001, Y = 401.194000, Z = 118.621002
Creature Name: "Shade of Akama"
Player Name: "Ishlo"

**Comment by Naios** [comment] 2016-07-02 16:39
The crash is reproduceable with https://github.com/Naios/TrinityCore/tree/shadeakama

```
.go xyz 548 401 113 564
```

**Comment by Naios** [comment] 2016-07-02 16:45
Second crashlog when using `KillAllEvents(true)`: https://gist.github.com/Naios/460d46ff21ae2b981fc40bc9aeb08bdb

**Comment by Keader** [comment] 2016-07-03 12:54
@Naios i'm still having crashs with hotswap on Shade of Akama

**Comment by Naios** [comment] 2016-07-03 17:57
Could you create a crashlog in full debug mode please?

**Comment by Keader** [comment] 2016-07-03 21:19
i cant reproduce without hotswap
and with hotswap, has debug mode?

**Comment by Naios** [comment] 2016-07-03 21:23
just compile it in debug... the crashlog is in the Crashes directory then.

**Comment by Keader** [comment] 2016-07-04 00:35
Crashes folder is always empty ._.

**Comment by Naios** [comment] 2016-07-04 00:55
Could you explain me step by step  how i can reproduce the issue?

**Comment by Keader** [comment] 2016-07-04 01:21
Go to Shade of Akama with Hotswap active
Dont need start the boss, just change something in source and save. Hotswap will compile and reload scripts. After it, shade of akama will reset. Do the same step again (change something and save).
When Shade of Akama appear again (after scripts reload) server crash. Normally happens in second or third reload script.

**Comment by jackpoz** [comment] 2016-07-04 08:28
is the original issue with static linking fixed ? can we close this issue ?

**Comment by Naios** [comment] 2016-07-04 10:33
No it isn't since the original crashlogs shows that the event cancellation was forced at
Unit destruction which is another case.

Maybe it's better to open another ticket for @Keader's issue.

**Comment by Keader** [comment] 2016-07-09 23:23
Ok (#17557)
this can be closed :+1:

**Comment by Naios** [comment] 2016-07-09 23:29
No it can't, this is another issue which is caused through destruction of the unit object.

**Closed** 2016-08-29 20:06 UTC
Labels: Branch-3.3.5a, Comp-Core, HasBacktrace, Priority-High, Sub-Spells
