### ISSUE TITLE
[3.3.5] Some enchant are item and not usable

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14632] opened 2015-05-01 00:12 UTC
Checking AH i've noticed some enchant weapon are sold as useless items and can't be used

![ench1](https://cloud.githubusercontent.com/assets/10136428/7424868/712be28a-efa7-11e4-93e9-674aed234d32.png)
![ench2](https://cloud.githubusercontent.com/assets/10136428/7424869/715d7cfa-efa7-11e4-886f-77c0fc35c5a3.png)

Tried on rev 2695a5fe3562 2015-04-26

**Comment by tkrokli** [comment] 2015-05-01 00:41
You misread your core rev. hash 2b95a5fe3562 . The 2nd character in your hash is b, not 6.
`2b95a5fe3562264f52f1ca9296faf411a90d5d8d` (**DB/Quest: What Do You Feed a Yeti, Anyway?**)

**Comment by ikir83** [comment] 2015-05-01 08:06
Sorry for the core rev hash.

Nope i can buy the item (it is white not red) and it is a useless item, not a weapon not an usable enchant. I'm not talking about the formula. For example Enchant weapon spirit works but for example potency is wrong, it should be an usable item for all.

This:
http://www.wowhead.com/spell=27972/potency

**Comment by dr-j** [comment] 2015-05-02 17:53
Well seems there are two items called ones called enchant weapon - potency this is white item and is not usable and is marked as not been available to players on wowhead http://www.wowhead.com/item=35459/enchant-weapon-potency#comments

and then theres Formula: Enchant Weapon Potency http://www.wowhead.com/item=22553/formula-enchant-weapon-potency this one works as intended as learns recipe when right click if you have enchanting

**Comment by dr-j** [comment] 2015-05-02 17:59
same with http://www.wowhead.com/item=35454/enchant-weapon-major-healing and http://www.wowhead.com/item=28281/formula-enchant-weapon-major-healing the one which does not work is marked by wowhead has not been available to players.

**Comment by dr-j** [comment] 2015-05-02 18:03
and the none working items are not present any loot_template entry or at npc_vendor so in other words on clean tc unobtainable

**Comment by tkrokli** [comment] 2015-05-02 19:37
> [...] and is marked as not been available to players on wowhead [...]

Doesn't the comment `This item is not available to players.` mean that it was removed in Cata or later?
Or does it actually mean that it has never been available in-game, maybe only in PTR?

**Comment by Aokromes** [comment] 2015-05-02 19:50
cannot reproduce on clean TC with default settings, if you are using custom settings blacklist those items on config.

**Closed by Aokromes** 2015-05-02 19:50 UTC

**Comment by ikir83** [comment] 2015-05-03 05:38
I just increased the item in AH no other strange settings. How i can blacklist them? Thanks.

**Comment by tkrokli** [comment] 2015-05-03 06:10
If you look at the item ID from the item links above (in dr-j's posts), you will see that you need to blacklist the items [35454](http://www.wowhead.com/item=35454/enchant-weapon-major-healing) and [35459](http://www.wowhead.com/item=35459/enchant-weapon-potency#comments) in the [Auction House Bot] section of your Worldserver.conf file.

**Comment by ikir83** [comment] 2015-05-03 06:17
Right!
AuctionHouseBot.forceExcludeItems = ""

Thanks!

**Comment by ikir83** [comment] 2015-05-19 12:42
Still in my server auction house, a lot of items are not usale. There is also a Frostmourne demo art item

![schermata 2015-05-19 alle 14 24 50](https://cloud.githubusercontent.com/assets/10136428/7703067/4e19a448-fe35-11e4-950d-14cb0ba12ff3.png)

**Comment by Aokromes** [comment] 2015-05-19 12:49
Like i told you, use AuctionHouseBot.forceExcludeItems.
