### ISSUE TITLE
3.3.5 command table issue

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#16949] opened 2016-04-12 15:29 UTC
**Description**: command table throws error

**Current behaviour**: issuing a command, EX: .additem
https://gist.github.com/Keldo/bb072544ceda94d2107c447f3468f644

**Expected behaviour**: command should execute

**Steps to reproduce the problem**:

1. pull origin 3.3.5
2. cmake...
3. make
4. make install
5. launch worldserver
6. issue command

**Branch(es)**: 335

**TC hash/commit**: 131ef5f2d682

**TDB version**: 335.61

**Operating system**: Debian Linux

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment] 2016-04-12 15:31
Try updating your core.

**Comment by Jaihoob** [comment] 2016-04-12 16:58
my core is last commit and no rbac command work 
in game or in console no such command

**Comment by Keldo** [comment] 2016-04-12 18:54
Git cloned the whole rev again, ran cmake, make and it failed. Seems the script changes are broke? Wasnt having any issues until the ScriptManager was changed, that is where it is failing

**Comment by tkrokli** [comment] 2016-04-12 19:03
TrinityCore rev. e2687b31ed73 2016-04-12 20:06:04 +0200 (3.3.5 branch) (Win64, Release)

I know that most of the `.rbac` commands don't work in-game by default on a gm character, probably because of rbac permissions set to not be available in-game, although most of them should work in the console. I found a new change during the last 24 or 48 hours that I had not expected, the `server` console command is not available any more:
```
TC>TrinityCore rev. e2687b31ed73 2016-04-12 20:06:04 +0200 (3.3.5 branch) (Win64, Release) (worldserver-daemon) ready...

TC>server exit
There is no such command
TC> server
There is no such command
TC> _
```

**Comment by Naios** [comment] 2016-04-12 19:51
Are you speaking about the dynamic or the static build (or both?)

**Comment by Naios** [comment] 2016-04-12 20:10
I need a detailed step by step explanation how you built the worldserver (dynamic, statically), and which commands aren't working. I can't estimate anything from `command table throws error` or `issue command` since on my machine the commands work.

**Comment by Keldo** [comment] 2016-04-12 20:13
try .additem #itemid  or the steps that throkli did as we are both having the same issues. then check you DBError.log

**Comment by Jaihoob** [comment] 2016-04-12 20:18
i lost all my command and i build it dynamic

**Comment by Naios** [comment] 2016-04-12 20:19
But the static build isn't affected?

**Comment by Jaihoob** [comment] 2016-04-12 20:33
im my first try with static that was not working 
[DBErrors.txt](https://github.com/TrinityCore/TrinityCore/files/215885/DBErrors.txt)

**Comment by Jaihoob** [comment] 2016-04-12 20:36
do i need to set script manually to dinamyc or i let them defaut?

**Comment by Keldo** [comment] 2016-04-12 20:37
because static is set by default, my last 2 attempts have failed to build at Scrip Manager

**Comment by tkrokli** [comment] 2016-04-12 20:58
In CMake 3.5.1, I only used the `default` settings, where all the lines beginning with `SCRIPTS_` are set to `default`. Is it important to test the 3 other values (disabled, dynamic and static) to find out if there are differences between them? Does it make any difference that I use VS2013 update 5 in this case?

**Comment by DDuarte** [comment] 2016-04-12 21:01
Cannot reproduce with 'static', Ubuntu 15.10

> TrinityCore rev. 323c967a76cf 2016-04-12 17:04:49 +0100 (3.3.5-Graphana branch) (Unix, Release)

**Comment by Naios** [comment] 2016-04-12 21:05
Read https://trinitycore.atlassian.net/wiki/display/tc/Using+the+script+hotswapping+system first please. The SCRIPTS_ variables are responsible for the building behaviour, if it is set to "default the value from the "SCRIPT" variable is used.

When you leave the optionss at it's default value the build is linked statically with all scripts enabled (like it was all time before the change).

I'm wondering because i can't reproduce the issue.
Adding items works well even with linking dynamically with MSVC 2015.
Ubuntu Clang (dynamic) seems to work as well (ingame tests are ongoing).

**Comment by Keldo** [comment] 2016-04-12 21:06
CMake Error at src/server/scripts/CMakeLists.txt:162 (add_library):
  The target name "scripts_/easternkingdoms" is reserved or not valid for
  certain CMake features, such as generator expressions, and may result in
  undefined behavior.


CMake Error at src/server/scripts/CMakeLists.txt:166 (target_link_libraries):
  Cannot specify link libraries for target "scripts_/easternkingdoms" which
  is not built by this project.


-- Configuring incomplete, errors occurred!
 this using -DSCRIPTS="dynamic"

**Comment by Naios** [comment] 2016-04-12 21:10
Update your source

**Comment by Jaihoob** [comment] 2016-04-12 21:13
i try with setting my script manualy dynamic in camke and my project give me 38 object instead of 26
38>------ Build started: Project: ALL_BUILD, Configuration: Release Win32 ------
38>  Building Custom Rule D:/TrinityCore/CMakeLists.txt
38>  CMake does not need to re-run because D:\TrinityCore\build\CMakeFiles\generate.stamp is up-to-date.
========== Build: 38 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

and my command working again

**Comment by tkrokli** [comment] 2016-04-12 21:26
TrinityCore rev. e2687b31ed73 2016-04-12 20:06:04 +0200 (3.3.5 branch) (Win64, Release)

Setting all 11 `SCRIPTS_*` values manually to static makes it work again. Only 23 projects on `static` and `default` in VS2013 update 5. It also removed all the messages in DBErrors.log .

**Comment by Naios** [comment] 2016-04-12 21:28
So you mean setting SCRIPTS="static" and all SCRIPTS_* to default triggers the error, but setting all SCRIPTS_* manually doesn't trigger the error?

**Comment by tkrokli** [comment] 2016-04-12 21:33
The `SCRIPTS` variable in my CMake 3.5.1 only shows a tick box `[√]` (on/off), but it looks like setting the `default` value on all 11 `SCRIPTS_*` settings turns the SCRIPTS variable to `disabled` :
```
* Script configuration (ON):
    |
    |  disabled
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |

Configuring done
Generating done
```

**Comment by Naios** [comment] 2016-04-12 21:38
You need to delete your build directory as mentioned in https://github.com/TrinityCore/TrinityCore/commit/9cc97f226d79e8e0bbe1fdc386ec9f065c0a2226.

I close this issue since the issues mentioned above should be fixed when using the latest version and removing the build directory.

**Closed by Naios** 2016-04-12 21:38 UTC
Labels: Branch-3.3.5a, Comp-Core, Priority-Critical

**Comment by tkrokli** [comment] 2016-04-12 21:51
Confirmed. To make the script hotswapping system work as intended, deleting the CMake cache or manually delete the existing content of the build directory **is required** before running cmake again.
