### ISSUE TITLE
ICC events are missing?

### ISSUE THREAD

**Issue by Krutok** [TrinityCore/TrinityCore#28111] opened 2022-07-13 16:29 UTC
### Description

When you have killed the 3rd boss (Saurfang), then a ship comes flying normally and the other Saurfang picks up the dead man and brings him to the ship and later Jaina and the king come through the portal, talk a little and disappear and then NPCs come and build a camp where you can repair and sell.

Is this a bug or is it missing or does the event not happen because I have to skip the airship fight because the NPC bots can't do it?

The other thing is when you go up to Professor Putricide, the doors normally close and you have to complete an event there.
Unfortunately, this is missing and you get to the boss without an event.

The event with the spiders when you go to Singragosa is also completely missing. Normally when you come into the room the gate closes and big spiders spawn and then there are 2 other big mobs and when you kill them the gate opens again and you can go to the boss

### Expected behaviour

As I said in ICC after killing the 3rd boss, a portal should appear where Jaina and the king will appear and talk a little and then NPCs will spawn and set up camp

And Professor Putricide is missing the intermediate event.

And maybe it would be a possibility to add an option to the NPC Muradin to skip the gunship fight and complete the bossfight, because the teleport there is also not active with my portal hack.

Because for lowpop private servers that would be an option to fix the problem.

### Steps to reproduce the problem

here is the event that is missing.: https://www.youtube.com/watch?v=pwD8UJETGmo
here video from my server: https://youtu.be/2d_CP1m0_VU

after killing the boss despawn and no outro event.

The event on the horde side works but only half. There he picks up the corpse and disappears, but no camp is set up. there is no event at the alliance.

### Branch

3.3.5

### TC rev. hash/commit

I have no debug about it because the events are probably completely missing

### Operating system

Debian 11

### Custom changes

Trinitycore with Bots and this is only one custom Change: https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots

--> **TrinityCore rev. 5737aaad1ece+ 2022-07-08 21:23:04 +0000 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)**

**Comment by Aokromes** [comment] 2022-07-13 17:40
duplicate of a lot of tickets, lazy to search other tickets
https://github.com/TrinityCore/TrinityCore/issues/3963

**Closed by Aokromes** 2022-07-13 17:40 UTC
Labels: Branch-3.3.5a
