### ISSUE TITLE
[3.3.5] [Paladin] [Talent] Sanctified Wrath

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14609] opened 2015-04-26 20:19 UTC
Rev:https://github.com/TrinityCore/TrinityCore/commit/83ffc5fca8648c90bc7f5d1e023faf82edada1cf
TDB: 11.58

There is problem with spell. It bypass damage through shield, but it's bypassing like 80-90%  of shield, not 50%

http://prntscr.com/6yicr6

![](https://image.prntscr.com/image/RtyKbN7.jpg)

##

**Comment by xiledra** [comment] 2015-05-01 02:41
It is 50% of current damage that is absorbed, not 50% total damage output
if shield has 1200 absorb then it can absorb up to 600 damage.
If your damage would be lower than 600, then it would be equal to 50% of total damage output

**Comment by Aokromes** [comment] 2015-05-01 08:30
So, incorrect report?

**Comment by xiledra** [comment] 2015-05-01 13:42
Yes, this part of spell is fine, but it does not work anyway.
If damage is lower than absorb amount, then it is fully absorbed instead of bypassing shield with 50% of damage done.

**Comment by Frytiks** [comment] 2015-06-04 18:16
Any news on this ? Shields is uselles vs retri Paladin now

**Comment by Rushor** [comment] 2016-02-05 10:16
fixed with https://github.com/TrinityCore/TrinityCore/pull/15033 ?

**Comment by tkrokli** [comment] 2016-02-15 22:59
@Frytiks : can you confirm if the original issue is solved by the PR linked by Rushor (#15033)?

**Comment by Re3os** [comment] 2017-05-19 18:23
@tkrokli confirm https://github.com/TrinityCore/TrinityCore/commit/7afe0b7fb005999dfb8bfae45b7d22abbec29b93

**Comment by ariel-** [comment] 2017-05-19 18:26
There is no way to know in that screenshot, you should test before and after the absorb effect

**Comment by tkrokli** [comment] 2017-05-19 18:27
OK @Re3os , so if I understand you correctly, you are saying that you are using the current [3.3.5](https://github.com/TrinityCore/TrinityCore/commits/3.3.5) commit https://github.com/TrinityCore/TrinityCore/commit/7afe0b7fb005999dfb8bfae45b7d22abbec29b93 and that you say that the issue is solved?

**Comment by Re3os** [comment] 2017-05-19 18:27
@tkrokli yes

**Comment by tkrokli** [comment] 2017-05-19 18:28
What about @ariel-'s comment above, have you tested it like he said?

**Comment by adeutscher** [comment] 2020-04-11 20:10
I've tested this with a build based off of 0844ad2, and for my 2 cents I think this issue can be closed as fixed.

Steps performed:

1. Create a priest to be the victim of a hit, level to 80 for decently-large numbers: `.level 79`
2. Teach the priest a shield: `.learn 48066`
3. Create a paladin, level to 80: `.level 79`
	* Not yet teaching them Sanctified Wrath.
4. Max the paladin's weapon skill: `.maxskill`
5. Gave the paladin a few items with +Hit rating (convenience):
	* `.additem 50612`
	* `.additem 50627`
	* `.additem 49907`
	* `.additem 49475`
6. Teach the paladin Avenging Wrath: `.learn 31884`
8. Have the priest cast Power Word: Shield on themselves. Have the paladin attack them with Avenging Wrath active. Observe results.
	* Until the shield is fully burned through, hits are recorded as misses that don't show up in the combat log. Concerning, but this doesn't interfere with the focus of the issue.
9. Navigate through the Retribution tree until you can get Sanctified Wrath
10. Learn a single rank of Sanctified Wrath.
11. Repeat steps 8, shield and attack with Avenging Wrath active. Observe results.
12. Learn the second rank of Sanctified Wrath
13. Repeat step 8, shield and attack with Avenging Wrath active. Observe results.

Results:
 
* 0/2 Sanctified Wrath, no shield: 350-353 damage per swing
* 0/2 Sanctified Wrath: Successfully 'absorbed'. (miss bug, though the shield can still be burned through and behaves as expected)
* 1/2 Sanctified Wrath: 88 damage per swing, with 264-266 damage absorbed per swing (~25% of total damage)
* 2/2 Sanctified Wrath: 175-177 damage per swing with 176-177 damage absorbed per swing

**Closed** 2020-04-11 22:35 UTC
Labels: Sub-Spells
